### ISSUE TITLE
media buttons as hotkeys are not working after upgrade to Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#1003]
Original [issue 1101](https://code.google.com/p/ddb/issues/detail?id=1101) created by Alexey-Yakovenko on 2014-04-28T12:19:25.000Z:

1.upgrade to or clean install Ubuntu 14.04 (bug exists on both cases)

2.set any media key (play,pause,next...) to any action

3.nothing happens when testing that hotkey, However, other non-media keys works as expected

What version of the product are you using? On what operating system and CPU architecture?
v 0.6.1
Ubuntu 14.04 LTS x64

<b>How did you install the product?</b>
downloaded .dep package from your website

<b>Please provide any additional information below.</b>
bug detected on a laptop (HP Pavillion dv6) which has a separate 'fn' key to trigger media actions and also on a pc with a generic keyboard with physical media buttons

good luck and thanks for this amazing app :)

Ahmed gamal

**Comment by Cactus64k** [comment]
Hi, im using deadbeef 0.7.2 [static] on Debian Jessie.
My hardware is Asus N56VZ laptop with multimedia keys.
And I  have problem with this buttons. They dont working. I set "Playback -> Toggle Pause" as XF86AudioPlay. And have no effect.

**Comment by Alexey-Yakovenko** [comment]
@Cactus64k It's quite possible that your desktop environment intercepts those keys before they reach deadbeef. There are two ways to solve this:

1. If you're using GNOME, or derived system, try using this plugin https://github.com/barthez/deadbeef-gnome-mmkeys/
    (It's available as prebuilt binaries here: http://deadbeef.sourceforge.net/plugins.html)
2. change your system settings so that your desktop environment stops intercepting the multimedia keys.

Hope that helps.

**Comment by Cactus64k** [comment]
Im using Mate. And advice of system setting is help. Thanks.

**Comment by elmo667** [comment]
@Alexey-Yakovenko Hi, started having this problem today after upgrading ubuntu to 21.10. Most notably this includes the switch to wayland. I know wayland is still highly experimental and all, but would it be possible to check for wayland support RE global hotkeys? Ive switched back to xorg for now of course, but maybe in the far future wayland will replace xorg and we gotta be ready for that

**Comment by Alexey-Yakovenko** [comment]
@elmo667 I don't think Wayland provides the same support for global hotkeys as X11. So there's a possibility that we're not going to get global hotkeys on Wayland + Deadbeef. To my best understanding, using MPRIS is the way to go with Wayland / GNOME, and there's a Deadbeef plugin for that.
