### ISSUE TITLE
Individual track titles not displayed when playing one-track FLAC files with embedded cue-sheet

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#1067]
Original [issue 1165](https://code.google.com/p/ddb/issues/detail?id=1165) created by Alexey-Yakovenko on 2014-07-31T08:54:11.000Z:

<b>What steps will reproduce the problem?</b>
1. Open a FLAC with with embedded cue list and track information
2. Look at the track/album information
   <b>3.</b>

<b>What is the expected output? What do you see instead?</b>

The &quot;Title&quot; field is showing the album title for all tracks, whereas the track names should be displayed instead. The FLAC files are correctly tagged. (I can provide samples if needed)

It appears Deadbeef is picking the first TITLE tag it finds, which is that of the album, and discards the rest.

For example, if the following is in the VORBIS_COMMENT block
comment[2]: TITLE=&lt;albumtitle&gt;

The individual cue-sheet with track titles is ignored:

  TRACK 01 AUDIO
    TITLE &quot;&lt;first track&gt;&quot;
    INDEX 01 00:00:00

In this scenario, Deadbeef shows the correct title for the artist+album, but has the same information (album name) for all tracks.

Also, for a FLAC file which _does not_ have this information as a 'comment[n]: TITLE=&lt;...&gt;', it displays 'Unknown artist - Unknown album'.

Specifically; the unknown artist+album scenario occurs if the metadata block #&nbsp;2 (VORBIS_COMMENT) has the following info, and is lacking any &quot;comment&quot; tags above it:

TITLE &quot;&lt;Albumtitle&gt;&quot;
FILE &quot;Artist - Album.flac&quot; WAVE
  TRACK 01 AUDIO
    TITLE &quot;&lt;Tracktitle&gt;&quot;
    PERFORMER &quot;&lt;Artist&gt;&quot;
    INDEX 01 00:00:00

I've verified this with a large number of files, on several different Deadbeef installations so as to to rule out any library issues, problematic .flac files, etc.

<b>What version of the product are you using? On what operating system and CPU</b>
<b>architecture?</b>

0.6.1 on various distros, Manjaro 0.8.10-t2, Ubuntu 14.04, all on x86_64.

<b>How did you install the product?</b>

From .deb (directly from the Deadbeef webpage) and via pacman from Manjaro/Arch repos.

<b>Please provide any additional information below.</b>

Thanks for a great player. Hopefully it can get even better. :)

**Comment by roddersg** [comment]
Original problem has arised - Cannot find track titles in embedded cuesheet for flac files. (BTW it works in version 0.6 with the shorted tags), but with the new formatting it does not work

**Comment by Alexey-Yakovenko** [comment]
@roddersg please post a new issue, with detailed description, and complete reproduction steps. Thanks.
