### ISSUE TITLE
Crash from dbus assertion caused by notify plugin

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#1077]
Original [issue 1175](https://code.google.com/p/ddb/issues/detail?id=1175) created by Alexey-Yakovenko on 2014-08-15T20:28:08.000Z:

Happens erratically and not often, always when starting to play a track.  Possibly more often when artwork is being invalidated from the cache.  Can't reliably reproduce.

<b>What steps will reproduce the problem?</b>
<b>Какие шаги приводят к воспроизведению</b>
<b>проблемы?</b>
<b>1.</b>
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
<b>Какой ожидаемый вывод? Что вы видите</b>
<b>вместо него?</b>

<b>What version of the product are you using? On what operating system and CPU</b>
<b>architecture?</b>
<b>Какую версию продукта вы используете? На</b>
<b>какой операционной системе и</b>
<b>архитектуре CPU?</b>
0.6.2
Crunchbang Linux
Pentium 4

<b>How did you install the product?</b>
<b>Как вы установили продукт?</b>
0.6.2 static build

<b>Please provide any additional information below.</b>
<b>Пожалуйста, предоставьте любую</b>
<b>дополнительную информацию ниже.</b>
process 22166: arguments to dbus_message_ref() were incorrect, assertion &quot;!message-&gt;in_cache&quot; failed in file dbus-message.c line 1526.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted

Looks very much as if the dbus message got unref'd (inside the thread?) before dbus_message_ref() was called.

**Comment by Soukyuu** [comment]
This started happening much more often now, it crashed one me with the same message about 4 times in the last two hours. I started noticing an increase in frequency in November releases, followed by whatever is happening now after rebuilding from source today.
```
process 3394: arguments to dbus_message_ref() were incorrect, assertion "!message->in_cache" failed in file dbus-message.c line 1700.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

**Comment by Soukyuu** [comment]
I think this might happen more often when playing mp3. Under same conditions, but playing wavpack files, the crashes are not as frequent (actually, none so far).

**Comment by Alexey-Yakovenko** [comment]
I think it could help if we rearrange the code a little..
Could you try this patch?

```
diff --git a/plugins/notify/notify.c b/plugins/notify/notify.c
index a3a8d94..dd2ebdc 100644
--- a/plugins/notify/notify.c
+++ b/plugins/notify/notify.c
@@ -239,9 +239,10 @@ static void show_notification (DB_playItem_t *track) {
 
     dbus_message_iter_append_basic(&iter, DBUS_TYPE_INT32, &v_timeout);
 
+    dbus_message_ref (msg);
+
     intptr_t tid = 0;
     if ((tid=deadbeef->thread_start(notify_thread, msg)) != 0) {
-        dbus_message_ref (msg);
         deadbeef->thread_detach (tid);  
     }
     dbus_message_unref (msg);
```

**Comment by Alexey-Yakovenko** [comment]
or maybe it would even work if we delete both dbus_message_ref and dbus_message_unref before/after the thread_start call.

**Comment by Alexey-Yakovenko** [comment]
@Soukyuu did you have a chance to try with the patch?

**Comment by Soukyuu** [comment]
Sorry, I did not have the time. I'll give it a try once I manage to get some free time, probably towards the end of the week.



Sent from my Mi phone
On Alexey Yakovenko <notifications@github.com>, Jan 11, 2017 9:42 AM wrote:

@Soukyuu<https://github.com/Soukyuu> did you have a chance to try with the patch?

**Comment by Soukyuu** [comment]
Seems like this nailed it. Was playing the same mp3 album on the patched version without any crashes. Then I restarted on the non-patched version, it crashed after two tracks.

**Comment by Soukyuu** [comment]
Hmm, just crashed again with the same message on the patched version...

**Comment by Alexey-Yakovenko** [comment]
I guess it's worth merging this patch anyway, because it sounds like it improves the stability, despite not solving it completely...

**Comment by Alexey-Yakovenko** [comment]
I just converted the notify plugin code to use libdispatch, so it won't spawn multiple threads.
I hope someone can try and see if it works (I will test as soon as I can, but currently don't have linux access).
