### ISSUE TITLE
Dark Adwaita theme choice for GTK3 UI

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#1117]
Original [issue 1215](https://code.google.com/p/ddb/issues/detail?id=1215) created by Alexey-Yakovenko on 2014-10-13T12:40:01.000Z:

It's possible to turn on dark adwaita in gtk inspector (via Ctrl+Shift+I) and everything seems to look fine (gtk 3.14), except it isn't remembered after relaunch. 
I guess it's easy to add dark adwaita option to gtk3 ui settings.

**Comment by anewuser** [comment]
It'd be nice to have an option to use a different icon set for dark themes in general. That's the only problem I have with it on KDE (using the Breeze Dark theme):

![screenshot_20160628-3](https://cloud.githubusercontent.com/assets/6733770/16437381/cd000900-3d7c-11e6-824f-b6ec32d37002.png)

**Comment by Alexey-Yakovenko** [comment]
I don't know what this is about. Deadbeef is using the system GTK theme.
It sounds a bit like deadbeef should use something else than the default theme, which sounds odd.
