### ISSUE TITLE
Unreal (UT'99, Deus Ex) tracker modules (and any module which includes sub-tracks) playback problem.

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#1128]
Original [issue 1226](https://code.google.com/p/ddb/issues/detail?id=1226) created by Alexey-Yakovenko on 2014-11-07T12:19:26.000Z:

These modules are in flawlessly readable .umx and.it formats (as far as I know, .umx is simply container for .it), but they often consist of main (first) track and  some sub-tracks. Deadbeef can only play the first track, what makes the major part of a module just unusable. I know only two specialized players, which don't have this issue and play these modules correctly, ModPlugPlayer and XMPlay (both are Windows only). As Deadbeef pretends to be the best *nix audio player, it should do all the things right. Thanks.

**Comment by kode54** [comment]
UMX is an archive format containing one module in the S3M, XM, or IT format. I have never encountered any in the MOD format. It is best added to the ddb_dumb plug-in. The problem is, the only decent implementation I've found for a proper Unreal (99) archive reader is in C++, even if it is only C++98 or so.

**Comment by Alexey-Yakovenko** [comment]
@kode54 can you link the implementation you're talking about? I remember there was UMX support in your fb2k dumb plugin, but I didn't use it because it was in C++, planning to rewrite it eventually.. but never got to it.

**Comment by kode54** [comment]
Indeed, it is the very same C++ implementation. It could probably be rewritten in C99 with some work.

**Comment by Alexey-Yakovenko** [comment]
This seems to have been done some time ago.
