### ISSUE TITLE
Unable to use area selection when starting in empty playlist zone

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#1138]
Original [issue 1236](https://code.google.com/p/ddb/issues/detail?id=1236) created by Alexey-Yakovenko on 2014-11-20T04:25:03.000Z:

I wish I could click and hold and drag the mouse over a certain selection of songs so that I don't have to select each individually if I want a certain subsection of songs.

**Comment by Lithopsian** [comment]
Can't start a selection range from the album art column either.

**Comment by Alexey-Yakovenko** [comment]
Seems like this has been fixed at some point.. Works for me now.
