### ISSUE TITLE
Auto-sort after adding songs

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#1142]
Original [issue 1240](https://code.google.com/p/ddb/issues/detail?id=1240) created by Alexey-Yakovenko on 2014-12-01T13:38:34.000Z:

<b>What steps will reproduce the problem?</b>
<b>Какие шаги приводят к воспроизведению</b>
<b>проблемы?</b>
1. Add songs
2. Notice they're at the end of the playlist

**Comment by kpcee** [comment]
This issue is solved by ["sort: added automatic playlist sort with GTK UI checkbox in playlist"](https://github.com/DeaDBeeF-Player/deadbeef/commit/2fd71913e2c3cebbb97051e467dd3c4c25f0f9e2).
