### ISSUE TITLE
(OS X) Cannot open files with Deadbeef from Finder

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#1165]
Original [issue 1263](https://code.google.com/p/ddb/issues/detail?id=1263) created by Alexey-Yakovenko on 2015-01-26T00:42:16.000Z:

<b>What steps will reproduce the problem?</b>
<b>Какие шаги приводят к воспроизведению</b>
<b>проблемы?</b>
1. Navigate to any supported audio file in the Finder
2. Select &quot;Open with&quot; and &quot;Other...&quot;
3. Allow all applications
4. Select Deadbeef's application

<b>What is the expected output? What do you see instead?</b>
<b>Какой ожидаемый вывод? Что вы видите</b>
<b>вместо него?</b>
Normally, this would cause Deadbeef to play the audio file, but instead, OS X throws an error about Deadbeef not being able to play the format.

<b>What version of the product are you using? On what operating system and CPU</b>
<b>architecture?</b>
<b>Какую версию продукта вы используете? На</b>
<b>какой операционной системе и</b>
<b>архитектуре CPU?</b>
Deadbeef for Mac OS X, version in &quot;About deadbeef&quot; claims &quot;1.0 (1).&quot; I am using OS X Mavericks (10.9.5) on an Intel i5-2520m.

<b>How did you install the product?</b>
<b>Как вы установили продукт?</b>
I installed Deadbeef from the OS X .zip file provided on the downloads page of the official Sourceforge site.

<b>Please provide any additional information below.</b>
<b>Пожалуйста, предоставьте любую</b>
<b>дополнительную информацию ниже.</b>
Numerous features are still missing from the OS X port such as MIDI playback and the Preferences menu, though these are not as important as file association problems. I tried changing the .plist file in the .app bundle to allow common formats, but it did not solve the issue.

**Comment by carlosanunes** [comment]
This seems to be working in current versions.

**Comment by Alexey-Yakovenko** [comment]
has been working since long ago
