### ISSUE TITLE
Incorrect multichannel audio routing with ALSA/PulseAudio

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#1166]
Original [issue 1264](https://code.google.com/p/ddb/issues/detail?id=1264) created by Alexey-Yakovenko on 2015-01-26T17:02:55.000Z:

<b>What steps will reproduce the problem?</b>
Какие шаги приводят к воспроизведению проблемы?

Deadbeef plays 4.0 and 5.1 audio files in a wrong way.

<b>What is the expected output? What do you see instead?</b>
Какой ожидаемый вывод? Что вы видите вместо него?

Some other audio apps (gmusicbrowser, Rhythmbox) play multichannel files with correct channel-by-channel routing - each individual channel goes to its own motherboard's output channel.

Deadbeef with its default settings &quot;ALSA output plugin&quot; with &quot;playback/recording through the PulseAudio sound server&quot; plays 4.0 files correctly, but in 5.1 files it incorrectly swaps 2 pairs of channels - Center/LFE and rear channels.

If you switch output to &quot;PulseAudio output plugin&quot; option - it does the opposite fault. It plays 5.1 files correctly (front channels go to front speakers, rear ones - to rear ones, C/LFE - to C/LFE), but shifts rear channels of 4.0 files to C/LFE output.

What version of the product are you using? On what operating system and CPU architecture?
Какую версию продукта вы используете? На какой операционной системе и архитектуре CPU?

Deadbeef 0.6.2.2-1~trusty~ppa1 installed on Ubuntu 14.04 x64

<b>How did you install the product?</b>
<b>Как вы установили продукт?</b>

ppa for Ubuntu
deb http://ppa.launchpad.net/starws-box/deadbeef-player/ubuntu trusty main

<b>Please provide any additional information below.</b>
<b>Пожалуйста, предоставьте любую</b>
<b>дополнительную информацию ниже.</b>

**Comment by Soukyuu** [comment]
Just ran into this again when fixing my pulseaudio setup - PA's remixing ends up losing rear channels on 5.1 files, while, say mpv outputs stuff correctly.

**Comment by vmm86** [comment]
Unfortunately, I'm facing exactly the same problem on my PC.

> Some other audio apps 

Guayadeque, I should say

> play  multichannel files with correct channel-by-channel routing - each individual channel goes to its own motherboard's output channel.

> Deadbeef with its default settings "ALSA output plugin" with "playback/recording through the PulseAudio sound server" plays 4.0 files correctly, but in 5.1 files it incorrectly swaps 2 pairs of channels - Center/LFE and rear channels.

> If you switch output to "PulseAudio output plugin" option - it does the opposite fault. It plays 5.1 files correctly (front channels go to front speakers, rear ones - to rear ones, C/LFE - to C/LFE), but shifts rear channels of 4.0 files to C/LFE output.

My motherboard is Gigabyte **GA-Z97-D3H** with Realtek **ALC1150** audio codec.

I'm working on Ubuntu 16.04. I've installed Deadbeef 0.7.2 using the deb installation file `deadbeef-static_0.7.2-2_amd64.deb` downloaded from the official site.

I would post to @Alexey-Yakovenko any additional information about my set-up by your instructions. Deadbeef is the best foobar2000 alternative in the Linux world, and I'd be so happy to use this player exclusively without any errors of such kind.

**Comment by vmm86** [comment]
Should I open a new issue on that problem or not?

**Comment by Alexey-Yakovenko** [comment]
@vmm86 there's no need to post duplicate issues. Thanks for the heads up that this is still valid.

**Comment by vmm86** [comment]
Please tell me how can I help to fix it out.
Deadbeef development may be a great inspiration to learn C, but I'm not so good at it at the moment. :-)

**Comment by Alexey-Yakovenko** [comment]
I didn't have a chance to look into this, as multichannel support is not high priority for me personal (it's not very common for music consumption).

I guess that we need to do some research / analysis, and find out whether all multichannel files (different formats) expose the same problem, and if that's the case, look into how to make ALSA and Pulse plugins remap the channels.

The thing is that all input plugins which support multichannel audio, do their own channel remapping, and it's very possible that behavior will differ between AAC / OGG / FLAC / WAV / TTA etc.

To my best knowledge, audio channels don't get remapped by the output plugins.

**Comment by vmm86** [comment]
I will try to test different formats and channel configuration in the nearest future, on my configuration and maybe somewhere else.

But I've got to tell you that at least Guayadeque plays the same 4.0 and 5.1 files accurately, and I believe it doesn't depend on various file types. Maybe it makes sence to pay attention to its [source code](https://github.com/anonbeat/guayadeque) as well?

**Comment by Alexey-Yakovenko** [comment]
I'm afraid Guayadeque is merely a UI for GStreamer, and is not expected to contain any actual audio-related code in its sources. But if you think looking in the source code of other program(s) may help you fix this problem in Deadbeef - feel free to do so.

**Comment by Alexey-Yakovenko** [comment]
TBH I think looking at source code of deadbeef itself may be more productive though :)

**Comment by Alexey-Yakovenko** [comment]
Out of date / needs a re-test.
