### ISSUE TITLE
Playback stops after current track ends, if it's removed from playlist while playing

### ISSUE THREAD

**Issue by ghost** [DeaDBeeF-Player/deadbeef#1245]
Пример:

```
01 Track 1 [Playing]
02 Track 2
03 Track 3
```

Удалили Track 01. Ожидается, что по его окончанию будет воспроизведён Track 2, но он пропускается и переходит к Track 3.

**Comment by Alexey-Yakovenko** [comment]
fxd

**Comment by rossnomann** [comment]
Снова вылез баг. Только теперь трек не пропускается, а воспроизведение прекращается.
DeaDBeeF 1.8.0
