### ISSUE TITLE
Fails to edit tags in some ogg files

### ISSUE THREAD

**Issue by rekcuFniarB** [DeaDBeeF-Player/deadbeef#1332]
Deadbeef can't modify tags in some ogg files. Files stay untouched, no error printed to stderr. 

Tried also last static build from [here](https://drone.io/github.com/Alexey-Yakovenko/deadbeef/files)

[Example ogg file](http://toxicity.myftp.org/Share/TMP/Audio/deadbeef_tag_issue_example.ogg)

**Comment by Lithopsian** [comment]
WFM in non-static trunk build.

**Comment by Lithopsian** [comment]
The serial number is larger than the signed 32-bit integer limit and is being returned as negative, then being treated as an error.  This is a consequence of inconsistent type definitions in the underlying Ogg libraries.  I should be able to work round it by using larger data types.  Strange it hasn't shown up more often.  Or maybe it has.

Xiph bug report (will never be fixed):
https://trac.xiph.org/ticket/1850
