### ISSUE TITLE
Wrong track is played when there is a playqueue and the playlist is on a different tab

### ISSUE THREAD

**Issue by Lithopsian** [DeaDBeeF-Player/deadbeef#1373]
1. Create two tabs with tracks.
2. Start playing a track.
3. Switch to the other tab and put some tracks into the playqueue.
4. Switch back to the first tab.
5. Press next track.
6. Press next again.
   The playback alternates between the tracks in the current tab and the playqueue tracks in the background tabs.  The sequence goes something like:
   track 1 in playqueue tab
   track 2 in current tab
   track 3 in playqueue tab
   track 4 in current teb
   etc.

**Comment by Alexey-Yakovenko** [comment]
Seems like this got fixed by some other bug fix
