### ISSUE TITLE
Playlist tab jumps about wildly when it is being resized below its natural width

### ISSUE THREAD

**Issue by Lithopsian** [DeaDBeeF-Player/deadbeef#1385]
This is easiest to see with a wide tab, so create a tab with a long name.  Then resize the playlist so that it is narrower than the tab.  As the playlist width is adjusted the tab jumps rapidly from being left-aligned to right-aligned and back again.

**Comment by Alexey-Yakovenko** [comment]
The original idea was to disallow making playlist view so small that this would cause problems.. but with the introduction of design mode, it became possible to shrink playlist even to 0px side...

Anyway, bug confirmed.

**Comment by Alexey-Yakovenko** [comment]
I think some recent changes should prevent playlist from becoming that small.
