### ISSUE TITLE
Selection properties: add the ability to display properties of the playing track, and customize the list of fields

### ISSUE THREAD

**Issue by Mael-Le-Garrec** [DeaDBeeF-Player/deadbeef#1436]
Currently, it's only possible to display the metadatas of the selectionned track.
It would be interesting to display the infos of the playing track, along with choosing what fields to display.

**Comment by mallniya** [comment]
Moreover, it well be pretty good if not only displaying, but also editing is available.

**Comment by jadenPete** [comment]
I would love to be able to choose what fields to display

**Comment by mallniya** [comment]
List of tag fields is a scope of https://github.com/DeaDBeeF-Player/deadbeef/issues/1164
