### ISSUE TITLE
Deadbeef is never accessing CDDB audio traks info when "Prefer CD-Text over CDDB" is selected

### ISSUE THREAD

**Issue by cipricus** [DeaDBeeF-Player/deadbeef#1458]
I think it normally should fetch the music CD info from CDDB (as I see under plugins the Audio CD Player plugin with options for CDDB/FreeDB - [image here](http://i.stack.imgur.com/6gewD.png) - but when I open a music CD in Deadbeef that never happens, and never did as far as I can remember. 

I have asked a [U&L question](http://unix.stackexchange.com/q/255092/32012).

Running deadbeef in terminal I see:

loading plugin /opt/deadbeef/lib/deadbeef/cdda.so

and

*\* (deadbeef:7057): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

Whole output on pastebin [here](http://pastebin.com/dDW3S1ui)

**Comment by Alexey-Yakovenko** [comment]
Please try running the latest build from here: https://sourceforge.net/projects/deadbeef/files/travis/linux/0.7/

If this doesn't help, we can have a better look.. There was some fixing after 0.6.2 release, but I don't remember 0.6.2 having any problems with CDDB.

**Comment by cipricus** [comment]
I fixed it by un-checking the option "Prefer CD-Text over CDDB" (under Preferences-Plugins-Audio CD player-Configure).

I never thought that could be the problem because I think the logic of "preferring A over B" is that A shall be selected instead of B if BOTH are present/available. But selecting that option just shows A (CD-Text, which is absent on the majority of Audio CDs - http://superuser.com/q/1025110/162573) even if there is no CD-Text there (showing generic names: track1, track 2 etc).

Is that a bug?

Thank you for your quick answer, it seems that I needed your feedback to get motivated enough and look more into it: I couldn't believe 0.7 had the same problem so I tried changing those settings.

One other thing: is there a deadbeef command to start the Audio CD directly (similar to `audacious cdda://` or `qmmp cdda://`)?

**Comment by cipricus** [comment]
That is true also for 0.7

**Comment by Alexey-Yakovenko** [comment]
Yeah, it sounds like a bug.

**Comment by Lithopsian** [comment]
Although the dialog is different and the CDDB code has changed a lot, the CD-Text stuff is pretty much the same in 0.7 as it always was.  It works fine for me with every disc I've ever tried.

The coded behaviour is to use CDDB if it is enabled, and if there is either no CD-text or if the prefer CD-text is off.  The got-CD-text check is just whether cdio_get_cdtext returns anything.  There is no guarantee that is has the fields you want, or any useful fields at all I suppose.  That flag is only used in one place so it looks very much as if your Deadbeef is being told there is CD-Text for some reason.  I have libcdio v 0.83.

**Comment by Alexey-Yakovenko** [comment]
@Lithopsian could be caused by old libcdio version in static builds. let's re-check after update.

**Comment by Lithopsian** [comment]
Could someone have a look at this now?  I think libcdio in 0.7.1 is now a new version.  I never saw the original problem, so I can't say if this has made any difference.

**Comment by Alexey-Yakovenko** [comment]
Let's assume it's fixed for now, and wait for the @cipricus feedback

**Comment by Shellcat-Zero** [comment]
I would probably recommend reopening this issue. As of 1.9.1, I am still having this issue, and I've found multiple sources [suggesting workarounds](https://unix.stackexchange.com/a/257717/250929) or alternative software. The workarounds no longer appear to work, and I am also having to explore alternative software due to this failure in CDDB lookups.

**Comment by Lithopsian** [comment]
Still works for me, using gnudb.gnudb.org and port 8880.  Only tested a couple of CDs, but then I've never had the issue with any CD so I'm probably not the best judge.  I think the default configuration is still freedb.org?  That's not going to work, freedb.org is dead for over a year.

**Comment by Alexey-Yakovenko** [comment]
alright, I'll try to change to these values, and let's see what happens.
