### ISSUE TITLE
Change Last.fm scrobbler URL to https://post.audioscrobbler.com (HTTPS)

### ISSUE THREAD

**Issue by anewuser** [DeaDBeeF-Player/deadbeef#1602]
The current default URL  is `http://post.audioscrobbler.com` . I've changed it to `https://post.audioscrobbler.com` and it works.

**Comment by Alexey-Yakovenko** [comment]
http works fine here.
Seems like your local problem.
But it's great that you found how to fix it.

**Comment by anewuser** [comment]
I didn't mean that http wasn't working. I meant that it's a better option, since the plugin sends our passwords.

**Comment by anewuser** [comment]
I meant that HTTPS would be better since the plugin has our passwords, but after opening my profile I saw that only one of the albums I listened to was scrobbled. Maybe the HTTPS URL just redirects to the HTTP sometimes, and sometimes it gives an error. I can't investigate it now, and since you plan to eventually port the plugin to the new API, it's better to leave it as it is for now.

**Comment by Alexey-Yakovenko** [comment]
Deadbeef's VFS_CURL doesn't support HTTPS on linux yet (in the official binary builds).

I'll consider changing this when this problem is fixed.

**Comment by anewuser** [comment]
Thank you for your replies and for your work on this great player.

**Comment by Alexey-Yakovenko** [comment]
Reopening as a feature request (I originally thought that it's a but report claiming it doesn't work without https)

**Comment by spirine** [comment]
last.fm do not support HTTPS scrobbling: http://www.last.fm/api/intro
Maybe https://post.audioscrobbler.com just resolve as same IP for scrobbler

**Comment by Alexey-Yakovenko** [comment]
@spirine I can't see any mention of last.fm not supporting scrobbling over HTTPS on your link.

I'm pretty sure it works fine. And yes, ip address can be the same for both HTTP and HTTPS, which doesn't really change the fact.

**Comment by m0ngr31** [comment]
Mine doesn't work until I use HTTPS as well.

**Comment by servimo** [comment]
Now scrobbling is not working in any way

**Comment by servimo** [comment]
Deadbeef scrobbler is not working

**Comment by 4oo4** [comment]
@servimo The default is using the latest API endpoint (https://ws.audoscrobbler.com), which deadbeef can't even use since it doesn't work with HTTPS. So you need to use the plain HTTP endpoint (http://post.audioscrobbler.com). HTTPS support really needs to be something that gets looked at, especially nowadays, it's only a matter of time before the HTTP endpoint gets shut off.

**Comment by 4oo4** [comment]
Hmm, doesn't seem to be quite that simple, but since it's using libcurl then it shouldn't be that difficult to add.

**Comment by Alexey-Yakovenko** [comment]
deadbeef builds are now guaranteed to support https out of the box on linux, so I was able to change the default lastfm endpoint to https.

**Comment by ckx** [comment]
Same thing just happened to me, no scrobbles, but swapping https→http→https worked. Just noting there's still something kinda wonky here, just started running debug build myself, let's see if we can go another 2 years before getting useful info lol
