### ISSUE TITLE
Add option to skip to next track after "Remove from disk" is used

### ISSUE THREAD

**Issue by anewuser** [DeaDBeeF-Player/deadbeef#1622]
The player currently keeps playing deleted tracks. It would be nice if there was an option to skip automatically to the next track.

**Comment by kpcee** [comment]
This is solved with [gtkui: improved remove from disk feature](https://github.com/DeaDBeeF-Player/deadbeef/commit/8ad89ddfbdbf494d7b406820729fad7ec91efc75).
