### ISSUE TITLE
Tracks with wrong paths are silently omitted

### ISSUE THREAD

**Issue by Kzer-Za** [DeaDBeeF-Player/deadbeef#1727]
When you import a playlist from m3u8 (probably from other formats too), the tracks, for which the paths are not found omitted (not imported) without any error messages. Expected behaviour (IMHO) is producing a message, something like:

Tracks:
no. 1 at $somepath/$somename
no. x at ...
no. y at ...
are not found.

First, when I migrated from Windows I mass-changed only "D:\" to the mountpoint in my .m3u8's, but forgot to mass-change all backslashes to slashes, so when I tried importing these playlists, nothing was happening because DeadBeeF could not find any legitimate file paths in these m3u8's and silently did not import anything. Of course, it was my mistake, but if it produced error messages, I would have immediately seen what was wrong. But it did not and it got me a while to figure out what was happening.

Second, when nothing from a playlist gets imported, at least you see it immediately. But what if just one-two files in a large playlist got renamed/moved to some other directory? If they are silently omitted, it would be hard to notice their absence in a large playlist. I think error messages for these situations are absolutely necessary.

**Comment by Alexey-Yakovenko** [comment]
There's an ongoing effort to add an error console to deadbeef, and use it for communicating error information to the user. It already works in macOS version, and used by some of the plugins (Most notably the Converter and ReplayGain).

**Comment by Alexey-Yakovenko** [comment]
This was implemented some time ago, via log window.
