### ISSUE TITLE
doesn't add/play aacplus m4a files

### ISSUE THREAD

**Issue by Sergei-Alekseev** [DeaDBeeF-Player/deadbeef#1778]
### Expected behavior
add/play files.

### Actual behavior
doesn't add/play aacplus m4a files. empty playlist.

### Steps to reproduce the behavior
add files/folder or start with cmdline.

`>deadbeef "2013 - Reasons To Kill"  (30715)
starting deadbeef 0.7.2 [static]
server_start
searching for GUI plugins in /home/serge/.local/lib32/deadbeef
searching for GUI plugins in /home/serge/.local/lib/deadbeef
searching for GUI plugins in /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 53 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
found selected GUI plugin: GTK2
loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK2.so
loading plugins from /home/serge/.local/lib32/deadbeef
loading plugins from /home/serge/.local/lib/deadbeef
loading plugins from /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 53 files
loading plugin /opt/deadbeef/lib/deadbeef/aac.so
loading plugin /opt/deadbeef/lib/deadbeef/adplug.so
loading plugin /opt/deadbeef/lib/deadbeef/alac.so
loading plugin /opt/deadbeef/lib/deadbeef/alsa.so
loading plugin /opt/deadbeef/lib/deadbeef/artwork.so
loading plugin /opt/deadbeef/lib/deadbeef/cdda.so
loading plugin /opt/deadbeef/lib/deadbeef/converter.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/dca.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_ao.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_dumb.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_mono2stereo.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_shn.so
loading plugin /opt/deadbeef/lib/deadbeef/dsp_libsrc.so
loading plugin /opt/deadbeef/lib/deadbeef/ffap.so
loading plugin /opt/deadbeef/lib/deadbeef/ffmpeg.so
loading plugin /opt/deadbeef/lib/deadbeef/flac.so
loading plugin /opt/deadbeef/lib/deadbeef/gme.so
loading plugin /opt/deadbeef/lib/deadbeef/hotkeys.so
loading plugin /opt/deadbeef/lib/deadbeef/in_sc68.so
loading plugin /opt/deadbeef/lib/deadbeef/lastfm.so
loading plugin /opt/deadbeef/lib/deadbeef/m3u.so
loading plugin /opt/deadbeef/lib/deadbeef/mms.so
loading plugin /opt/deadbeef/lib/deadbeef/mp3.so
loading plugin /opt/deadbeef/lib/deadbeef/musepack.so
loading plugin /opt/deadbeef/lib/deadbeef/notify.so
loading plugin /opt/deadbeef/lib/deadbeef/nullout.so
loading plugin /opt/deadbeef/lib/deadbeef/oss.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/pulse.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexec.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/sid.so
loading plugin /opt/deadbeef/lib/deadbeef/sndfile.so
loading plugin /opt/deadbeef/lib/deadbeef/supereq.so
loading plugin /opt/deadbeef/lib/deadbeef/tta.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_curl.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_zip.so
loading plugin /opt/deadbeef/lib/deadbeef/vorbis.so
loading plugin /opt/deadbeef/lib/deadbeef/vtx.so
loading plugin /opt/deadbeef/lib/deadbeef/wavpack.so
loading plugin /opt/deadbeef/lib/deadbeef/wildmidi.so
loading plugin /opt/deadbeef/lib/deadbeef/wma.so
selected output plugin: ALSA output plugin
INFO: loading playlist VA-Trance
INFO: from file /home/serge/.config/deadbeef/playlists/0.dbpl
INFO: loading playlist Radio
INFO: from file /home/serge/.config/deadbeef/playlists/1.dbpl
INFO: loading playlist Solar Fake
INFO: from file /home/serge/.config/deadbeef/playlists/2.dbpl
INFO: loading playlist Default
INFO: from file /home/serge/.config/deadbeef/playlists/3.dbpl
playlist load fail (/home/serge/Music/0_MUSIC_AAC/Solar Fake/2013 - Reasons To Kill)!
failed to add file or folder /home/serge/Music/0_MUSIC_AAC/Solar Fake/2013 - Reasons To Kill
convgui: gtkui plugin not found
plugin Converter GTK3 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK3 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK3 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 2.16.0
quitting gtk
gtkui_stop completed
gui plugin has quit; waiting for mainloop thread to finish
plug_disconnect_all
plug_unload_all
stopping GTK2 user interface...
quitting gtk
stopping Adplug player...
stopping ALSA output plugin...
stopping Album Artwork...
stopping Converter...
stopping dts decoder...
stopping PSF player using Audio Overload SDK...
stopping DUMB module player...
stopping Game-Music-Emu player...
stopping Hotkey manager...
stopping SC68 player (Atari ST SNDH YM2149)...
stopping last.fm scrobbler...
stopping MusePack decoder...
stopping OSD Notify...
stopping Null output plugin...
stopping OSS output plugin...
stopping PulseAudio output plugin...
stopping Shell commands...
stopping SID player...
stopping WAV/PCM player...
stopping SuperEQ...
stopping tta decoder...
stopping cURL vfs...
stopping OggVorbis decoder...
stopping VTX player...
stopping WildMidi player...
stopping FFMPEG audio player...
stopped all plugins
connecting button tray signals
all plugins had been unloaded
messagepump_free
plug_cleanup
hej-hej!
>deadbeef "2013 - Reasons To Kill" (30715) returned '0'
`
http://autogrom.ru/files/Reasons-To-Kill.zip

**Comment by Alexey-Yakovenko** [comment]
I think this issue was reported ad-hoc a few times, but never been posted to the bug tracker.. So it's good to have it here for tracking purpose. There's some ongoing work on the completely new mp4 parser + the new aac decoder based on fdk-aac, which might solve the problem soon-ish.

**Comment by Sergei-Alekseev** [comment]
if encoded with option '-signaling implicit' files plays well in deadbeef

`find -name "*.%{(cachename)@"Convert files with extension:"}" -exec ffmpeg -hide_banner -loglevel panic -stats -i {} -c:a libfdk_aac -profile:a aac_he_v2 -b:a 32k -signaling implicit -vn {}.m4a \; && ren-converted && compl`

**Comment by Alexey-Yakovenko** [comment]
This issue has been fixed in the latest build.
