### ISSUE TITLE
Deadbeef just not using some album covers.

### ISSUE THREAD

**Issue by zeebzz** [DeaDBeeF-Player/deadbeef#1835]
Deadbeef from arch linux
After installing fresh, going to Plugins > album art > configure > Fetch from local folder > add *.jpg *.png (so it uses any file at all for album art)  It misses a ton of albums

If its worth noting the source drive is NTFS.

For example, before adding .jpg and .png barely any of my covers would show up (because they have random titles), after adding .png and .jpg 90% of them now show up, but theres the odd album that just WONT display a cover

Even if they have cover.jpg inside the folder it just WONT show up. I don't get it. How do I fix this?

Most times I cant even delete the cover, download a new one, rename to cover.jpg, and it STILL doesn't work. Is it a permissions issue??? except when i check permisssions, it looks fine. Whats the deal?

**Comment by Alexey-Yakovenko** [comment]
The old artwork plugin is a mess, and can totally do what you describe.
I don't think you can fix (all) these issues just by changing settings.
The new plugin is better, but is not supported on Linux yet, and is not fully finished.
So the only option is to wait until it's done.

The main goal of the artwork-legacy was to load covers from the internet, so you could probably just enable and use that.

The new artwork plugin's goal is to be able to use as little as possible of internet, and be able to find covers locally better.

**Comment by zeebzz** [comment]
Well I'll just keep waiting.

Another example:
Put a new album on today, realize theres no artwork, go to google and download the artwork, put it inside folder...For some reason it decides to not work with this album.

It seems random.

**Comment by zeebzz** [comment]
Hey I found something.

If I open the same cover.jpg picture inside Kolourpaint, hit save, NOW it works.

Why would I have to open a downloaded .jpg file in kolourpaint just for it to show up in Deadbeef?

**Comment by Alexey-Yakovenko** [comment]
A guess it could be that it's a non-JPEG, named with .jpg extension. When you resave it -- it's saved as JPG.

You can find out more info by comparing the file contents before and after.

**Comment by Lithopsian** [comment]
If you can give a link to artwork that you downloaded and had a problem with, I can look at the file and see if there is anything odd with it. It would help to know the exact name you initially saved it as, as well as the name you saved it as from Kolourpaint.

**Comment by C0rn3j** [comment]
@Alexey-Yakovenko would the "old artwork plugin" also cause the artwork being very blurry?

Deadbeef-git (latest), GTK3

![image](https://user-images.githubusercontent.com/1641362/51554115-d2039300-1e74-11e9-9764-0b7fc9072e0b.png)

**Comment by Alexey-Yakovenko** [comment]
@C0rn3j 
You should post this as a new issue.

**Comment by Alexey-Yakovenko** [comment]
Not enough information provided, if you can provide a sample cover.jpg which doesn't load - I can fix it.
