### ISSUE TITLE
Crash with right-click on audio files from Youtube

### ISSUE THREAD

**Issue by geplus** [DeaDBeeF-Player/deadbeef#1853]
Hi,
I have some audio grabbed from Youtube.
I can play them, but when i do a right-click on the file in the playlist, the player crashes.
The message on the terminal is:

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

The audio infos from mediainfo:

Audio
ID                                       : 2
Format                               : AAC
Format/Info                        : Advanced Audio Codec
Format profile                     : LC
Codec ID                             : 40
Duration                               : 3 min 37 s
Bit rate mode                       : Variable
Bit rate                                 : 126 kb/s
Channel(s)                           : 2 channels
Channel positions                : Front: L R
Sampling rate                       : 44.1 kHz
Frame rate                            : 43.066 FPS (1024 SPF)
Compression mode               : Lossy
Stream size                            : 3.26 MiB (10%)
Title                                        : ISO Media file produced by Google Inc.
Encoded date                        : UTC 2016-08-14 03:25:54
Tagged date                          : UTC 2016-08-14 03:25:54

### Information about the software:

Deadbeef version: 0.7.2
OS: Arch Linux 64bit

**Comment by Alexey-Yakovenko** [comment]
Hello,
can you provide a full log of deadbeef from running in terminal, and possibly a GDB backtrace, created by following steps here https://github.com/DeaDBeeF-Player/deadbeef/wiki/GDB-HOWTO?

**Comment by Alexey-Yakovenko** [comment]
not enough info provided, no response from the OP
