### ISSUE TITLE
Preamp is not applied when replaygain processing is set to "None"

### ISSUE THREAD

**Issue by Lithopsian** [DeaDBeeF-Player/deadbeef#1857]
### Steps to reproduce the problem
Play any track. Set the replaygain processing pulldown to None. Slide both the preamps to -12 dB. Nothing happens.

### What's going on? Describe the problem in as much detail as possible.
Preamp behaviour has changed since 0.6.2, but I don't think this bit is intentional. When "Only prevent clipping" is selected, the preamp is applied (unless it would clip). Which preamp depends on whether there are replaygain tags matching the source mode, which may also be unintentional? Should this always be "replaygain without RG"?

### Information about the software:

Deadbeef version: trunk
OS: Debian Linux

**Comment by Alexey-Yakovenko** [comment]
I'm pretty sure this bit was intentional. Why do you think that RG preamp should be applied when RG processing is off? Wouldn't that be weird?

**Comment by Lithopsian** [comment]
I would think that "preamp without RG" would be applied when RG processing is off. No?

**Comment by Alexey-Yakovenko** [comment]
It would be applied to tracks which don't have RG info, when RG processing is ON.

**Comment by Alexey-Yakovenko** [comment]
That is also how it's called:

![image](https://user-images.githubusercontent.com/1895698/29494011-1a1734e8-85a2-11e7-8012-69b912ccc0fd.png)

**Comment by Alexey-Yakovenko** [comment]
(need to check if the name is the same in GTKUI though)

**Comment by Lithopsian** [comment]
Screenshot in English
![Uploading Screenshot.png…]()

**Comment by Alexey-Yakovenko** [comment]
your screenshot link is not working

**Comment by Lithopsian** [comment]
Is it going to say "without RG info"? Or something like "without RG tags"? I have always found it confusing which preamp is supposed to be applied when. At the moment I'm updating my Opus plugin to work in 0.7.2. It does its own replaygain since Opus is weird, but I'm trying to make it match as closely as possible.

**Comment by Alexey-Yakovenko** [comment]
> Is it going to say "without RG info"? Or something like "without RG tags"?

It's going to say "without rg info". There are no special "tags" for RG info. Tag is the whole object in the media file -- like ID3v1 or APEv2 etc. RG info may also be stored in Media Library, when this is available.

> I have always found it confusing which preamp is supposed to be applied when.

I believe it's working correctly now.

> At the moment I'm updating my Opus plugin to work in 0.7.2. It does its own replaygain since Opus is weird, but I'm trying to make it match as closely as possible.

You should not be doing your own RG implementation. What's the reason for that?

**Comment by Alexey-Yakovenko** [comment]
> At the moment I'm updating my Opus plugin to work in 0.7.2.

I'm curious why opus plugin would not work in 0.7.. Especially if it works in 0.6.
The API is backwards compatible, and input plugins made for 0.5.0 should all work in any future versions, including the soon-upcoming one (which will most likely be number 1.8.0).

**Comment by Lithopsian** [comment]
The replaygain in my plugin doesn't work in trunk because it applies its own replaygain. In 0.6, that meant reading configurations fields which have changed name. Things are a bit better now because some replaygain API is exposed and Deadbeef's internal replaygain can even be disabled, so I'm updating the pugin.

Opus is specified to use R128 gain tags in combination with a gain field contained in an Ogg page header. It is strongly recommended that the traditional REPLAYGAIN tags are not used although in practice they often are since R128 scanners are thin on the ground and scanners that set the Opus header gain almost nonexistent. The libopusfile library will automatically do its own replaygain, but obviously it only understands its own gain scheme and it needs to be overridden depending on the Deadbeef playback config. In particular it is tricky to turn replaygain off because some or all of the gain may be in the header field which is *supposed* to be *always* applied by the decoder. Opus replaygain is a bit of a mess really.

**Comment by Alexey-Yakovenko** [comment]
The way I see it is that you just need to convert whatever internal RG info you get on load into the normal replaygain fields, used by everything else, and then either let streamer do it, or call deadbeef->replaygain_apply manually. There's really no reason to do all that work manually, and get broken compatibility in every release.

**Comment by Alexey-Yakovenko** [comment]
And if you want to be compatible with replaygain scanner in deadbeef -- you also need to make sure opus plugin can write the added RG info correctly.

**Comment by Lithopsian** [comment]
There was no API to pass the necessary replaygain info to the streamer in 0.6, so I wrote it myself and did some nasty hacks to stop the streamer doing any gain itself. libopusfile actually does the replaygain automatically internally, but there are ways to turn it off partially (ie. do header gain only) or completely (do no gain, not compliant!). Now there is a formal API in Deadbeef and it may be possible to pass everything to the streamer, and I may even change the plugin to do that. I still need to know how it is all intended to work so that I can test that it actually does when I'm finished.

The plugin will already write REPLAYGAIN tags out from Deadbeef's internal REPLAYGAIN metadata, but that's just a stopgap. It really needs to be able to generate its own R128 tags (R128_TRACK_GAIN and R128_ALBUM_GAIN) from the Deadbeef scanner results. And maybe put the album gain in the Opus header, to be fully compliant with the spec. Or not, probably controlled by a user-setting. Just setting the traditional REPLAYGAIN tags works, in Deadbeef at least, but is incompatible with the spec and some other players. I'll probably make it configurable which tag/header combination gets written, with care that existing metadata doesn't accidentally get overwritten by other file edits. Will the Deadbeef scanner have any options for saving R128 values directly, or controlling the reference loudness? It is all EBU R128 anyway, right?

**Comment by Alexey-Yakovenko** [comment]
> Will the Deadbeef scanner have any options for saving R128 values directly, or controlling the reference loudness? It is all EBU R128 anyway, right?

I don't fully understand what you're asking about.. Looking in rg_scanner.c should be more helpful to you.
