### ISSUE TITLE
Feature request: Sort by "%last_modified%"

### ISSUE THREAD

**Issue by intMojIBakE** [DeaDBeeF-Player/deadbeef#1862]
I wish in the menu “edit -> sort by -> customs” ,make the command "%last_modified%" supported.
Manual from https://github.com/DeaDBeeF-Player/deadbeef/wiki/Title-formatting-2.0
Deadbeef version:0.7.2

**Comment by jakeschievink** [comment]
I would absolutely love to see this feature

**Comment by paxet** [comment]
I subscribe too. Started using deadbeef recently as audio player in Sway (Wayland), and without it my podcast audios unordered beacause no meaningfull tags are provided from the different subscriptions I have.

**Comment by mallniya** [comment]
Works as intended after https://github.com/DeaDBeeF-Player/deadbeef/pull/2366.
