### ISSUE TITLE
Album Art is not showing

### ISSUE THREAD

**Issue by giorgosioak** [DeaDBeeF-Player/deadbeef#1867]
Hello, i have done tagging my music and added album covers.
 I added a column with Album Art and it just don't show it on both GTK2 / GTK3

![Image](http://i.imgur.com/lTpOSkD.png)

GNOME's file manager shows correctly the Album Covers. [Image](http://i.imgur.com/Pz10A43.png)

### Information about the software:

Deadbeef version: 0.7.2-2
OS: Antergos ( Arch Linux )

**Comment by Alexey-Yakovenko** [comment]
You need to use "group by" in the column header context menu. Album covers only show up when grouping is enabled.
