### ISSUE TITLE
Отрицательная ширина колонок в плейлисте

### ISSUE THREAD

**Issue by LynXzp** [DeaDBeeF-Player/deadbeef#1871]
На русском потому что сложно описать.
Иногда во время работы столбцы в плейлисте исчезают или становятся бесконечной ширины, при этом их нельзя удалить или что-либо исправить из GUI. Только удаление плейлиста в режиме дизайна помогало. Или помогает правка ~/.config/deadbeef/config - в строке gtkui.columns.playlist параметр size становился отрицательным (примерно -20000).

Точно не могу сказать когда это воспроизводится. Во время изменения ширины колонок такое было. Сейчас нету. Но бывает в то время когда он запущен и никто им не пользуется. Появляется редко (раз в неделю), но заметно мешает.

Возможно это связано с новой колонкой "рейтинг" которую я добавил и соответствующим плагином (раньше такого не наблюдалось), кроме того я заменил стандартные "звездочки", на цифру, может это как-то связано.

`gtkui.columns.playlist [{"title":"Исполнитель - Альбом","id":"-1","format":"$if(%artist%,%artist%,Unknown Artist)[ (%date%) %album%]","size":"426","align":"0","color_override":"0","color":"#ff18f018"},{"title":"R","id":"-1","format":"$ifequal([%rating%], 5,5,)$ifequal([%rating%], 4,4,)$ifequal([%rating%], 3,3,)$ifequal([%rating%], 2,2,)$ifequal([%rating%], 1,1,)","size":"21","align":"0","color_override":"0","color":"#ff18f018"},{"title":"Title","id":"-1","format":"(%tracknumber%) %title%","size":"220","align":"0","color_override":"0","color":"#ff000000"},{"title":"Duration","id":"-1","format":"%length%","size":"62","align":"0","color_override":"0","color":"#ff000000"}]`

**Comment by Alexey-Yakovenko** [comment]
Вы забыли заполнить обязательную форму для создания баг репортов.

**Comment by Alexey-Yakovenko** [comment]
duplicate of #1672
