### ISSUE TITLE
Replaygain scanner adds album tags containing zero in single-track mode

### ISSUE THREAD

**Issue by Lithopsian** [DeaDBeeF-Player/deadbeef#1872]
### Steps to reproduce the problem
Scan one or more tracks in single-file track mode. Update the tags at the end.

### What's going on? Describe the problem in as much detail as possible.
In track mode, only track gains and peaks are calculated. The dialog at the end shows the track gains and peaks, with the album gain and peak column empty. However, "0.00 dB" is written to ":REPLAYGAIN_ALBUMGAIN" and "0.000000" is written to ":REPLAYGAIN_ALBUMPEAK". These meta keys should not be written at all if album values have not been scanned. And the file tags should probably be removed if already present?

### Information about the software:
Deadbeef version: master
OS: Debian Wheezy
Tested on FLAC and OGG Vorbis files.

**Comment by Lithopsian** [comment]
An alternative is to always write both track and album tags, effectively treat the per-file track gain option as a series of one-track albums.  This is what flac does.  Some tools just don't write the album tags though, like vorbisgain.

**Comment by Alexey-Yakovenko** [comment]
fixed
