### ISSUE TITLE
Hang when pressing next from tray icon while track is converting or scanning

### ISSUE THREAD

**Issue by Lithopsian** [DeaDBeeF-Player/deadbeef#1873]
### Steps to reproduce the problem
Load several tracks.
Start converting the tracks.
Start playback.
Select next from the tray icon context menu.

### What's going on? Describe the problem in as much detail as possible.
The next track goes into "buffering" and playback never starts. Converting continues.  Deadbeef is responsive but won't shut down. This also happens with replaygain scanning, but it is more difficult to tell which track is being scanned. The bug only occurs on the track that is being converted.

### Information about the software:

Deadbeef version: trunk
OS: Debian Wheezy

**Comment by Alexey-Yakovenko** [comment]
I just tried to reproduce this issue, and it isn't happening as described.

At least under pulseaudio - no problem whatsoever. ALSA seems to be broken, but not connected to converter or rgscanner.
