### ISSUE TITLE
Replaygain scan by tags doesn't produce album scan results

### ISSUE THREAD

**Issue by Lithopsian** [DeaDBeeF-Player/deadbeef#1874]
### Steps to reproduce the problem
Select several tracks from the same album (identified by artist/album or filename).
Choose replaygain selection from albums by tags.
Examine results in the dialog.

### What's going on? Describe the problem in as much detail as possible.
Track gain information is displayed, but the album columns are blank. Saving the tags produces 0.00 dB for the album gains and 0.000000 for the album peaks (see issue #1872) .  Seems to be performing a single-tracks scan.

### Information about the software:
Deadbeef version: trunk
OS: Debian Wheezy

**Comment by Alexey-Yakovenko** [comment]
note: only on linux, mac works fine.. seems like a UI issue
