### ISSUE TITLE
Replaygain scanner doesn't release playitem refs

### ISSUE THREAD

**Issue by Lithopsian** [DeaDBeeF-Player/deadbeef#1875]
### Steps to reproduce the problem
Open DeaDBeeF on command line.
Load some playitems.
Do a replaygain scan.
Close DeaDBeeF.

### What's going on? Describe the problem in as much detail as possible.
The scanned playitems are reported in red as having refc at close. The replaygain scanner does take a ref on each playitem, and so far as I can see never tries to unref them.

### Information about the software:
Deadbeef version: trunk
OS: Debian Wheezy

**Comment by Lithopsian** [comment]
Possibly this is caused by calling plugin->init(), but not plugin->free().  Red errors are reported for Ogg Vorbis tracks, but not for Flac.  Flac does not carry it (and a ref) on its info structure, so no dangling refs but there would be a memory leak from not freeing its working structures.

**Comment by Alexey-Yakovenko** [comment]
Thanks for looking into this. Has been a known issue (to me), but I didn't have time to look into this yet. You're correct that one of the ref leaks is from not calling free. There are more of them though. Working on it.

**Comment by Lithopsian** [comment]
That's fixed what I was seeing.  I'll do some more testing this weekend and see if anything more comes up.

**Comment by Alexey-Yakovenko** [comment]
I wanted to keep it open until I fix the related cocoaui ref leak too. Fixed now.
