### ISSUE TITLE
DeadBeef starts to play iso.wv with noise

### ISSUE THREAD

**Issue by BUG-reporter** [DeaDBeeF-Player/deadbeef#1876]
### Steps to reproduce the problem
Click on any iso.wv album release file
### What's going on? Describe the problem in as much detail as possible.
DeadBeef starts to play but a loudly noise appears instead of normal sound.
### Information about the software:

Deadbeef version: 0.7.2+git7375
OS: Kubuntu 17.04
Kernel 4.13.2

**Comment by Alexey-Yakovenko** [comment]
Can't reproduce. Possibly got fixed with something else.
