### ISSUE TITLE
Enhance internal DeaDBeeF sample rate converter by sample rate mapping

### ISSUE THREAD

**Issue by 111MilesToGo** [DeaDBeeF-Player/deadbeef#1880]
### Steps to reproduce the problem

DeaDBeeF's built-in sample rate converter has a fixed target sample rate as fallback when "automatic" doesn't help. I have a USB-DAC that can go up to 88.2 and 96 kHz only. Thus, both 176.4 and 192 k get downsampled to 96, which is ill-chosen for 176.4 k. There should be a sample rate mapping table which lets the user set what should be done (integer multiples only). The internal sample rate converter of Audacious does have this feature. Please consider enhancing DeaDBeeF similarly. Thank you!

Deadbeef version: 0.7.2
OS: Linux Mint 18.2, openSUSE Tumbleweed

**Comment by Alexey-Yakovenko** [comment]
Can you explain why automatic samplerate selection doesn't work in your case though?

**Comment by 111MilesToGo** [comment]
First of all, DeaDBeeF is a great player, in particular with three of the C. Boxdoerffer plugins. Thanks a lot to you for doing the DeaDBeeF project!

I have an Audioquets Dragonfly Red USB-DAC (USB Audio Class 2), and I am getting very close to what I call "near-audiophile, bit-perfect" sound from Linux (Mint and Tumbleweed). This DAC does 16 and 24 bits, at sample rates of 44.1, 48, 88.2 and 96 kHz. It doesn't do 176.4, 192 and higher. I am using the ALSA output to the "Direct hardware device without any conversions" or the "S/PDIF Digital Out Device".

So, ideally, 176.4 has to be downsampled to 88.2, and 192 to 96 - integer multiples, please.

The internal resampler of DeaDBeeF from Preferences -> DSP -> Resampler (Secret Rabbit Code) is set to "Automatic yes" and "96000" otherwise. It works perfectly in automatically sending 44.1, 48, 88.2 and 96 kHz to the DAC.

However, both 176.4 and 192 kHz are downsampled to 96 k. This is fine for 192, but not for 176.4 which should be sent as 88.2 k. Of course, I can always go to the Resampler settings and change the "96000" to "88200" manually before I play a 176.4 k file, then change it back manually afterwards. But the application could do this on its own, of course - that is what I suggest as an enhancement for DeaDBeeF.

For your reference, please take a look at
https://forums.linuxmint.com/viewtopic.php?f=48&t=253225#p1365640
(sorry, couldn't figure out how to make the link clickable on github.)
It show the Audacious Sample Rate Converter properties, where the user can enter sample rate mappings.

Could you please enhance the DeaDBeeF Resampler in a similar way by predefined sample rate mappings? Everything else in your Resample is fine. This would make DeaDBeeF even more marvellous.

Thanks a lot in advance again.

**Comment by Alexey-Yakovenko** [comment]
Ok.. Thanks for explaining the use case. It's perfectly valid.
Meanwhile, you may find this plugin useful: https://github.com/silentlexx/deadbeef_soxr
It has the feature you need, and probably does a better resampling job.

**Comment by 111MilesToGo** [comment]
Thanks. Hope you can get the Secret Rabbit Code Resampler enhanced without too much effort.

Sorry to take your time: How do I get the SoxResampler as a plugin for DeaDBeeF? I don't see it as a zip from the "Get plugins" page on your DB site. And I just started to use github a bit, but really I am not up to compiling a plugin from the source.

Can you help me out, please? THANK YOU SO MUCH in advance.

Kind regards,
111MilesToGo


Am 21.09.2017 um 13:37 schrieb Alexey Yakovenko <notifications@github.com<mailto:notifications@github.com>>:


Ok.. Thanks for explaining the use case. It's perfectly valid.
Meanwhile, you may find this plugin useful: https://github.com/silentlexx/deadbeef_soxr
It has the feature you need, and probably does a better resampling job.

**Comment by Alexey-Yakovenko** [comment]
Download source code, unzip, cd into the unpacked folder, and run `./go`.
It should build and install it.
You need to have gcc, make and libsoxr-dev installed.

**Comment by Alexey-Yakovenko** [comment]
(it's not my project, if you need binaries, you should contact the plugin's dev)

**Comment by 111MilesToGo** [comment]
Thanks for your help, but I am too inexperienced. I asked the developer for a soft binary. THANK YOU!

Am 21.09.2017 um 14:28 schrieb Alexey Yakovenko <notifications@github.com<mailto:notifications@github.com>>:


Download source code, unzip, cd into the unpacked folder, and run ./go.
It should build and install it.
You need to have gcc, make and libsoxr-dev installed.

**Comment by shoober420** [comment]
If you seek bit-perfect audio playback, you shouldn't be using resamplers at all. If you get an audiophile sound card, like the ASUS Xonar Essence STX, you won't have the need for a resampler.

**Comment by 111MilesToGo** [comment]
@shoober420: Thanks for your comment, it shows people are interested and do care. Of course it's absolutely true what you say. But my Audioquest Dragonfly Red is a great-sounding device, just limited in accepting 44.1, 48, 88.2 and 96. Guess my lappy won't house any ASUS. I had considered other budget-DACs like Oppo, but hardware was commented as crappy. My dream DAC is a Chord Hugo 2, a 10 times higher assault on my budget... So, for the time being and for exploring the audio nirvana on Linux, resampling still is needed at inputs of 176.4, 192 and higher.

**Comment by shoober420** [comment]
I see. There is the Xonar Essence STU, which is an external USB option, but if budget limits you, your kind of stuck.
