### ISSUE TITLE
HDCD decoding via plugin

### ISSUE THREAD

**Issue by 111MilesToGo** [DeaDBeeF-Player/deadbeef#1884]
Hi Alexey,

I have a substantial number of HDCD-encoded CDs ripped as-is to 16-bit/44.1k FLAC files (dBpoweramp, no HDCD decoding during the rip).  A HDCD decoder plugin is needed in DeaDBeeF in order to make use of this little audio enhancement. I have seen there is one on github, https://github.com/bp0/deadbeef-hdcd . I have no idea whether it's good or bad.

Would you mind giving it a look, and maybe put the binary zipped on your own website?

Sorry for two things: (1) I am too inexperienced to compile plugins myself, as happened today for the Sox Resampler. (2) Please forgive me for making suggestions if these are too many and not in line with your policies.

Thanks for giving it a look.

Cheers,
111MilesToGo

Deadbeef version: 0.7.2
OS: Linux Mint 18.2, openSUSE Tumbleweed

**Comment by Alexey-Yakovenko** [comment]
It's best to request the binaries from the plugin devs. You can use the issue tracker here: https://github.com/bp0/deadbeef-hdcd/issues
and ask them to use [deadbeef-plugin-builder](https://github.com/DeaDBeeF-Player/deadbeef-plugin-builder)

You don't need much experience to build either soxr resampler or the hdcd plugin.

Simply download a zip using the green "Clone or download" button, click on it to unpack, then open terminal, `cd` to the unpacked folder, and run this:

```
./build.sh
./inst.sh
```

For this plugin, you need to install libhdcd using the package manager of your linux distribution.

I'm sorry, but I can't afford time at the moment to build more plugins, as I'm busy with too many other things.

**Comment by 111MilesToGo** [comment]
Thank you, I do perfectly understand your time constraints. I will go ahead and ask the plugin devs to build a binary according to your rules. I am not sure whether I will succeed in building it myself, but thank you for your detailed hints.

Cheers,
111MilesToGo
