### ISSUE TITLE
Use another icon name for tray icon

### ISSUE THREAD

**Issue by varlesh** [DeaDBeeF-Player/deadbeef#1887]
Will be cool use another icon name for tray icon on Linux systems. It's good looking with monochrome icon themes. For example `deadbeef-panel`
![image](https://user-images.githubusercontent.com/8083855/30779611-425ffa3c-a106-11e7-8455-862189591cdb.png)

**Comment by Grief** [comment]
For KDE (Plasma 5.14) https://github.com/vovochka404/deadbeef-statusnotifier-plugin works great
![default](https://user-images.githubusercontent.com/7239315/46802916-76027c00-cd67-11e8-80be-b29a72157fd1.png)

**Comment by haggen88** [comment]
I tried this one in Cinnamon and it works fine.

[deadbeef_scalable.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/7759997/deadbeef_scalable.zip)

**Comment by Alexey-Yakovenko** [comment]
Seems like this has been resolved already
