### ISSUE TITLE
Why does the sinc-best-quality of DeaDBeeF has lower CPU usage than pulseaudio?

### ISSUE THREAD

**Issue by JulianLai** [DeaDBeeF-Player/deadbeef#1889]
### Steps to reproduce the problem
try the resample method on both softwares
### What's going on? Describe the problem in as much detail as possible.
CPU usage of DeaDBeeF: low
CPU usage of pulseaudio: high (one of the CPU core is 100%)
### Information about the software:

> Name            : pulseaudio
> Version         : 11.1-1
> Description     : A featureful, general-purpose sound server
> Architecture    : x86_64
> URL             : https://www.freedesktop.org/wiki/Software/PulseAudio/
> Licenses        : GPL
> Groups          : None
> Provides        : None
> Depends On      : libpulse=11.1-1  rtkit  libltdl  speexdsp  tdb  orc  libsoxr  webrtc-audio-processing
> Optional Deps   : pulseaudio-alsa: ALSA configuration (recommended)
> Required By     : deepin-daemon  pulseaudio-jack
> Optional For    : deadbeef  firefox  kodi  phonon-qt5  phonon-qt5-gstreamer
> Conflicts With  : None
> Replaces        : pulseaudio-xen<=9.0
> Installed Size  : 5.75 MiB
> Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
> Build Date      : Tue Sep 19 15:42:05 2017
> Install Date    : Tue Sep 19 21:04:42 2017
> Install Reason  : Installed as a dependency for another package
> Install Script  : Yes
> Validated By    : Signature

> Name            : deadbeef
> Version         : 0.7.2-2
> Description     : A GTK+ audio player for GNU/Linux.
> Architecture    : x86_64
> URL             : http://deadbeef.sourceforge.net
> Licenses        : GPL2
> Groups          : None
> Provides        : None
> Depends On      : alsa-lib  hicolor-icon-theme  desktop-file-utils  jansson
> Optional Deps   : gtk2: for the GTK2 interface [installed]
>                   gtk3: for the GTK3 interface [installed]
>                   libsamplerate: for Resampler plugin [installed]
>                   libvorbis: for Ogg Vorbis playback [installed]
>                   libmad: for MP1/MP2/MP3 playback [installed]
>                   mpg123: for MP1/MP2/MP3 playback
>                   flac: for FLAC playback [installed]
>                   curl: for Last.fm scrobbler, SHOUTcast, Icecast, Podcast support [installed]
>                   imlib2: for artwork plugin [installed]
>                   wavpack: for WavPack playback [installed]
>                   libsndfile: for Wave playback [installed]
>                   libcdio: audio cd plugin [installed]
>                   libcddb: audio cd plugin [installed]
>                   faad2: for AAC/MP4 support [installed]
>                   dbus: for OSD notifications support [installed]
>                   pulseaudio: for PulseAudio output plugin [installed]
>                   libx11: for global hotkeys plugin [installed]
>                   zlib: for Audio Overload plugin [installed]
>                   libzip: for vfs_zip plugin [installed]
>                   ffmpeg: for ffmpeg plugin [installed]
> Required By     : deadbeef-jack-git  deadbeef-mpris2-plugin  deadbeef-replaygain-scan-git
> Optional For    : None
> Conflicts With  : None
> Replaces        : None
> Installed Size  : 9.67 MiB
> Packager        : Laurent Carlier <lordheavym@gmail.com>
> Build Date      : Mon Mar 13 14:21:00 2017
> Install Date    : Fri Jun 9 11:49:02 2017
> Install Reason  : Explicitly installed
> Install Script  : No
> Validated By    : Signature

Deadbeef version: 0.7.2-2
OS: Antergos

**Comment by Alexey-Yakovenko** [comment]
Most likely it's because when you enabled sinc_best in deadbeef, resampling was still performed somewhere else, or not performed at all. Especially since you're using pulseaudio.

**Comment by JulianLai** [comment]
This problem has been solved after I install the deadbeef-git
