### ISSUE TITLE
Channels mangled when playing a track with a different number of channels

### ISSUE THREAD

**Issue by Lithopsian** [DeaDBeeF-Player/deadbeef#1894]
### Steps to reproduce the problem
Create a playlist containing tracks with different numbers of channels.
Play the tracks.
The channel mapping after the first track becomes mixed up, and playback occurs in the wrong channels.  Which channels doesn't seem to be consistent, even when using the same tracks in the same order.

### What's going on? Describe the problem in as much detail as possible.
I have no clue what is happening.  This didn't happen in 0.6.  I've attached two Ogg Vorbis tracks that can be used to test the problem.  I don't think it is a problem with the Vorbis plugin.  Seeking within a track, or manually starting playback on a new track resets everything and that track plays fine.  Maybe the output plugin format isn't reset during automatic playback of the next track?  Maybe there are some leftover buffer contents when the format changes?

### Information about the software:
Deadbeef version: trunk
OS: Debian Wheezy, tested with Alsa

**Comment by Alexey-Yakovenko** [comment]
@Lithopsian It seems there's a bug with output format setting currently. There's another confirmed bug (reported off-tracker), that bps is not set correctly either. I'm gonna look into this ASAP.

And just FYI: it doesn't make much sense to compare anything between current master and 0.6.
0.6 release was 3 years ago.

**Comment by Alexey-Yakovenko** [comment]
Please try latest. It should be fixed.
