### ISSUE TITLE
Audio Static When Playing 24bit Files on Xonar STX, Multichannel Front Speakers ALSA device

### ISSUE THREAD

**Issue by shoober420** [DeaDBeeF-Player/deadbeef#1895]
### Steps to reproduce the problem
Play any 24bit file

### What's going on? Describe the problem in as much detail as possible.
Audio Static is heard

### Information about the software:

Deadbeef version: Latest Git
OS: Arch Linux 64bit

This started with the commit from September 25th

**Comment by shoober420** [comment]
I should mention that using the "Default Audio Device" option plays the track without static, but plays it faster then normal.

**Comment by Alexey-Yakovenko** [comment]
I believe that I fixed a related issue on 25th of September. Please try to update. Let me know if the bug is still there.

**Comment by shoober420** [comment]
Please reopen, I compiled from git today with the latest commits from September 28th, and it still plays static for 24bit audio files.

**Comment by Alexey-Yakovenko** [comment]
> I should mention that using the "Default Audio Device" option plays the track without static

Please specify which output device you're using then.. when static is heard.

**Comment by Alexey-Yakovenko** [comment]
I just tried several times, no static with default settings.
You also have said that the files play fine when you select default audio device.
Not enough information provided, cannot reproduce.

**Comment by shoober420** [comment]
I use the "Xonar STX, Multichannel Front Speakers" output Device option. No static is played when using "Default Audio Device" probably because it runs through DMIX and resamples it. I'll try again today with the latest git changes.

**Comment by shoober420** [comment]
It all started when the September 25th commit.

**Comment by shoober420** [comment]
This still occurs. Please reopen, it seriously is a bug. I've been using your software for years and didn't have this issue until the September 25th commit.

**Comment by shoober420** [comment]
With a git build from today, I get the following error when trying to play 24bit files. 

cannot set sample format to 24 bps (error: Invalid argument), trying all supported formats
Found compatible format 32 bps

I've been laying 24bit audio files with Deadbeef for years, it recently has been broken (since September 25th commit)

**Comment by Alexey-Yakovenko** [comment]
I just fixed some confusing error messages, which didn't really explain much about what they do.
32 bit is as good as 24. That's what your ALSA config / soundcard / driver accepts.
Nothing is broken.

**Comment by shoober420** [comment]
It still plays static when I try to.play any 24bit audio files. It all started with the commit from September 25th.

**Comment by Alexey-Yakovenko** [comment]
FYI: there have been no commits on Sep 25th.

**Comment by shoober420** [comment]
It shows Sept 25th for this commit.

https://github.com/DeaDBeeF-Player/deadbeef/commit/6a0a9b9acdd9d4cbc194885da6c45f87de8e6430

**Comment by Alexey-Yakovenko** [comment]
It's from Sept 8th, and it requires other changes to function correctly.
Are you using a build from this specific commit?
You need to at least include that one: 1f8f7f3e8aad82c07aeafd72d2fe862b561cb7f8

**Comment by shoober420** [comment]
If you go through the commits, it says "commits from Sept 25th". That specific commit was committed on the 25th. I build from git when new commits are added.

**Comment by Alexey-Yakovenko** [comment]
> "it says"

what is the "it"? git log doesn't show any commits on that day.

**Comment by kuba160** [comment]
@Alexey-Yakovenko when you go to that commit on github (1f8f7f3) it says it was commited 7 day ago which is 26th, and when you look [github commit log](https://github.com/DeaDBeeF-Player/deadbeef/commits/master) there is a commit on 25th Sept

**Comment by Alexey-Yakovenko** [comment]
ok, I see. I think those dates are when commits are pushed to github, not when they're actually made.

**Comment by shoober420** [comment]
I'm sorry for the confusion. I promise you my 24bit audio files play with static after that commit. I literally do fresh git builds when commits are added. I stay very up to date with your software.

**Comment by Alexey-Yakovenko** [comment]
@shoober420 could be caused by 24->32 bit conversion, which is a bit hard to repro on virtualbox, which only supports 16, and I didn't have time yet to try on real hardware.

**Comment by shoober420** [comment]
Is there a way to disable that conversion and keep my files 24bit?

**Comment by Alexey-Yakovenko** [comment]
From the message your wrote in another issue conversation, it looks like your system doesn't support 24 bit, and conversion to 32 bit is the only way.

I don't understand why that is bothering you though. It doesn't affect quality. It's a very common scenario.

**Comment by shoober420** [comment]
My sound card for sure supports 24bit audio files. I've been playing them for years with Deadbeef. I don't like any conversion or resampling since I'm an audiophile, and desire bit perfect playback. 

It would be odd for a sound card to support 32bit but not 24bit. If anything, it would be the the other way around, with the card supporting 24bit but not 32bit.

My cards specs for sure go up to 24bit 192khz.

**Comment by Alexey-Yakovenko** [comment]
> My sound card for sure supports 24bit audio files. I've been playing them for years with Deadbeef.

converting 24 to 32 bit doesn't lose any precision, and it's still bit perfect.

deadbeef can play 24 bit files on devices which don't support that bit depth without problems, by converting to whatever format they do support.

> It would be odd for a sound card to support 32bit but not 24bit.

It's not odd at all.

If you're in doubt, and think that your sound card can accept 24 bit data, you can always fix your ALSA configuration, or drivers, or whatever. Currently, your system doesn't accept 24 bit streams -- which is proven by a detailed message from deadbeef console, that you posted yourself recently.

**Comment by shoober420** [comment]
Here's the specs for my card.

https://m.newegg.com/products/N82E16829132010/specs

It claims 24bit audio. Maybe it's something with my ALSA settings. Ill take a look into it when I get home from work.

**Comment by Alexey-Yakovenko** [comment]
First of all, nothing shows up at the link.

Then, it's very common when 24 bit is supported via 32 bit (essentially, padding with a zero byte).

And finally, if you're sure that you're not wrong -- you can find out very easily what your system supports by looking in the various files in /proc.

I'm not sure what the file would be called, but this works in virtualbox:

```
$ cat /proc/asound/card0/codec#0 | grep bits
    bits [0x2]: 16
    bits [0x2]: 16
    bits [0x2]: 16
```

which tells its virtual soundcard only supports 16 bits.

**Comment by shoober420** [comment]
Sorry about that link. Here's a legit working link.

https://www.asus.com/us/Essence-Hi-Fi-Audio/Xonar_Essence_STX/specifications/

I have the output for that command, including a rates output.

bits [0x0]:
    bits [0xe]: 16 20 24
    bits [0xe]: 16 20 24
    bits [0xe]: 16 20 24
    bits [0xe]: 16 20 24

rates [0x0]:
    rates [0x7f0]: 32000 44100 48000 88200 96000 176400 192000
    rates [0x7f0]: 32000 44100 48000 88200 96000 176400 192000
    rates [0x7f0]: 32000 44100 48000 88200 96000 176400 192000
    rates [0x7f0]: 32000 44100 48000 88200 96000 176400 192000

With this information, we have to figure out why deadbeef is converting 24bit audio to 32bit audio.

**Comment by shoober420** [comment]
I thought I would mention, that when I try to play a 24bit audio file with my settings since September 25th, this error message is displayed.

Output plugin: ALSA output plugin
Output device: Xonar STX, Multichannel
                         Front speakers

Use ALSA resampling: DISABLED
No Pulseaudio

cannot set sample format to 24 bps (error: Invalid argument), trying all supported formats
Found compatible format 32 bps

So we have to figure out why deadbeef is converting the 24bit audio file, which is supported by my sound card, to 32bit, which is unsupported by my sound card and deadbeef thinks is compatible, when its not.

**Comment by Alexey-Yakovenko** [comment]
> With this information, we have to figure out why deadbeef is converting 24bit audio to 32bit audio.

isn't that something we already know from past conversations?

**Comment by shoober420** [comment]
We thought it was because my card supported 32bit and not 24bit, but it's the other way around. With all the proof I've posted, from the spec sheet to the cat read out from /proc, my card does indeed support 24bit audio files. Deadbeef is converting them to 32bit, thinking my card supports 32bit, but it doesn't. So basically what I see is going on here, is Deadbeef keeps converting the 24bit files to 32bit, and since my card doesn't support 32bit, the 32bit stream is played with a bunch of static.

**Comment by Alexey-Yakovenko** [comment]
What you're writing may sound logical, but that's not how code works. If your computer didn't support 32 bit -- the code would not be able to set 32 bit output format, and send any data.

There's no need to bomb me with guesses about what is the cause of your device playing static, unless you gonna debug and fix the problem.

I will try debugging this issue on weekend, and then we'll hopefully know more.

**Comment by Alexey-Yakovenko** [comment]
Something that can be tried..

1. run aplay -L and find the device you need. It should look similar to this:
`front:CARD=I82801AAICH,DEV=0`

2. run `aplay -D "front:CARD=I82801AAICH,DEV=0" file.wav` with a file in 24 bit format

3. see if it plays correctly, and what aplay says about it

**Comment by shoober420** [comment]
When I try to play my 24bit audio file, I get this error.

aplay: set_params:1318: Sample format non available
Available formats:
- S16_LE
- S32_LE

So my ALSA configuration wrongly sees my card supporting 32bit and not supporting 24bit at all. This is so odd. This was working like a week ago. I was playing 24bit audio files perfectly fine. There was a recent alsa-lib update for Arch Linux on 9-28-2017. There must be a bug somewhere in my ALSA configuration.

**Comment by Alexey-Yakovenko** [comment]
well, at least we resolved this question. now you know how to find out what's supported and what is not.

**Comment by shoober420** [comment]
Oh no, I accidently gave the information for my nVidia HDMI audio jack information. I have "card0" and "card1" in my system. That was the information for "card1", which is the nVidia HDMI audio jack. The strange thing is, "card0", my ASUS sound card has no "codec#0" file in it. I have no idea where it would be hiding. This is driving me crazy lol. I just can't figure out why out of the blue, my 24bit audio files just randomly stop working. When I get home from work, I'll try to find how to extract information about what my system sees about my sound card in the "/proc/asound" directory. I'll have to do some snooping around.

**Comment by shoober420** [comment]
Out of desperation, I downgraded my kernel, and it still didn't play the file. So after all this, I simply downgraded Deadbeef to version 0.7.2, and lo and behold, it played perfectly fine. Although it still produces an error message.

cannot set sample format (Invalid argument), trying all supported formats

Why do you think the official 0.7.2 version of Deadbeef can play the 24bit files perfectly fine, but the git version cannot?

**Comment by shoober420** [comment]
Even stranger, I had a 32bit audio file in my collection, and tried it out using "Front Speakers", since it claims it supports S32_LE, and got an error message.

cannot set sample format to 32 bps (error: Invalid argument), trying all supported formats
Found compatible format 16 bps

**Comment by shoober420** [comment]
Ok, this is officially an issue with my sound card. It doesn't truly support bit-perfect 24bit playback. It was probably converting it to 32bit. Here's more information from this link if anyone ever comes across this.

http://ossnext.trueinstruments.com/forum/viewtopic.php?t=4710

**Comment by Alexey-Yakovenko** [comment]
The issue status didn't change, please don't close until it's fixed.

**Comment by shoober420** [comment]
Could you add a 24bit to 32bit option for deadbeef?

**Comment by shoober420** [comment]
The ASUS Xonar Essence STX, and all CMI8788-based cards require that 24-bit samples are aligned in 32-bit words in memory. So I can't play 24bit audio files with bit perfect playback, but something close to it. I'm already looking into purchasing a new DAC for my machine. In the meantime, is there an option you could add that converts 24bit audio to 32bit so my card can play back 24bit files? I see there's options for 8 to 16, and 16 to 24. Could you by chance do 24 to 32? All the information about this can be found here.

Please read this thread. It's very informative.

http://ossnext.trueinstruments.com/forum/viewtopic.php?t=4710#p18380

**Comment by Alexey-Yakovenko** [comment]
@shoober420 the issue has been fixed. Sorry, I didn't realize I somehow closed this issue by accident immediately after reopening.

I'm not going to be adding what you're asking, I will probably remove the 8/16 bit options as well, and make the output format setting more explicit.

**Comment by shoober420** [comment]
Ok, so I did some more experimenting with aplay. I found that when I used the "sysdefault", or "Default Audio Device", the card correctly selects "S24_3L" and plays the song in 24bit. For some reason, using the "Front Speakers" option will not select the "S24_3L" option, or see that it exists.

It seems like my card has some sort of secret built in resampler. I really don't know what's going on. I can simply just select the "Default Audio Device" when playing 24bit files and use "Front Speakers for 16bit. It's no big deal. I just need a higher end DAC for what I'm looking for.

**Comment by shoober420** [comment]
That commit fixed the audio distortion, but this whole thing leaves me puzzled. Could you answer some questions for me?

First, why does aplay refuse to play the file, even if I select "-f S32_LE"? Why does Deadbeef allow it to output 32bit and aplay refuses?

Second, what is going on with my card while this is happening? Is it resampling the 24bit audio to 32bit? I'm kind of confused that aplay can't play the file but Deadbeef can.

**Comment by Alexey-Yakovenko** [comment]
aplay doesn't do any processing. It only asks alsa to play a stream, and it will give an error if alsa can't do that.

default audio device is configured to use dmix, which does mixing of the sound from multiple apps, and it can perform conversion from audio formats which your driver won't accept.

so e.g. if you ask dmix to play S24_LE -- it will happily convert that to something that your driver can accept, transparently. and that's why you've been able to play 24 bit streams using aplay + default audio device.

deadbeef though can perform conversion as well as dmix, even on the devices which don't use dmix. so when you try to play S24_LE stream on front speakers device, which isn't using dmix, ALSA would refuse to set that format, but then deadbeef looks up what is possible, automatically switches to S32_LE, and does the conversion on the fly.

I hope that clarifies stuff a bit for you.

**Comment by shoober420** [comment]
Ok, thank you so much for the explanation and fixing this bug. It was a learning experience for me to say the least. I learned alot about my sound card.

**Comment by Alexey-Yakovenko** [comment]
Np, thanks for reporting the issue.
