### ISSUE TITLE
Tracks Play Faster then normal

### ISSUE THREAD

**Issue by shoober420** [DeaDBeeF-Player/deadbeef#1896]
### Steps to reproduce the problem

Play any audio file

### What's going on? Describe the problem in as much detail as possible.

When using the "Default Audio Device" option, all music is played faster then normal. This has been going on for a while now, but I never reported since I use the "Xonar STX, Multichannel Front Speakers" option, which plays tracks perfectly fine.

### Information about the software:

Deadbeef version: Latest Git
OS: Arch Linux 64bit

**Comment by shoober420** [comment]
This occurs when "Use ALSA resampling" is disabled. Tracks play fine when resampling is enabled using "Default Audio Device".

**Comment by Alexey-Yakovenko** [comment]
You have to use resampling for the unsupported hardware samplerates, otherwise music will play faster or slower.

**Comment by shoober420** [comment]
I use no resampling when using the "Xonar STX, Multichannel Front Speakers" option and it plays normal. My hardware supports the samplerates, or else it would play faster when using that option as well. It only happens when using "Default Audio Device".

**Comment by shoober420** [comment]
Please reopen this, my hardware supports the samplerates. It only plays fast when using "Default Audio Device". It plays normal with no resampling when using "Xonar STX, Multichannel Front Speakers. It's an issue with using the "Default Audio Device Option". I have an audiophile sound card, it supports many samplerates. It supports up too 24bit 192khz, and I don't have any audio files that go beyond that, so it supports everything I have.

**Comment by Alexey-Yakovenko** [comment]
There's no reason to reopen this. Even if your device supports a given samplerate, doesn't mean your driver or alsa configuration does. Find the reason why deadbeef can't use the samplerate you *think* your sound card supports, make it work, and your problem will be solved.

**Comment by Alexey-Yakovenko** [comment]
> up too 24bit 192khz

That is not quite true. According to its specs, it only supports 44.1, 48, 96, 192.
Not "up to".

**Comment by Alexey-Yakovenko** [comment]
Ok. I deciphered what you said.

You have 1 sound card.

You want to play without resampling through "Default audio device".

But when you use "Default audio device" -- that's ALSA + DMIX (by default).

ALSA + DMIX is by default configured to 48KHz, and you can only play at 48KHz.

And if you disable resampling -- you'll get wrong speed.

When you play through the "Front Speakers" device -- that goes without DMIX, and would use your soundcard's native samplerates.

Does it make sense?

**Comment by shoober420** [comment]
I have a ASUS Xonar Essence STX, it's just named "Xonar STX" in the output menu. I've been talking about the same sound card this whole time. I'll try and simplify this for you.

No resampling + Xonar STX Multichannel Front Speakers = Normal playback

No resampling + Default Audio Device = Wrong Playback (fast)

My sound card supports all my music samplerates. If it supports up too 24bit 192khz, then my card can do 44.1, 48, and 96 as well. It's a really nice card.

**Comment by Alexey-Yakovenko** [comment]
> No resampling + Default Audio Device = Wrong Playback (fast)

I explained to you above, that this is the correct behavior. DMIX (which is the default audio device) is always using 1 samplerate, which is 48000 by default. Most files will play at wrong speed without resampling. It doesn't matter which soundcard you have.

**Comment by shoober420** [comment]
I understand now. I'm sorry for the confusion. It all makes sense now. My fault.

**Comment by Alexey-Yakovenko** [comment]
no worries

**Comment by shoober420** [comment]
Please reopen this. I just found something. 16bit audio files play as intended, with them playing normal with resampling, and fast with no resampling. 24bit files on the other hand, play too fast regardless of resampling settings. I'll make a diagram to be more specific.

16bit file + Default Audio Device + resampling = normal playback

24bit file + Default Audio Device + resampling = fast playback

The 24bit file should play normal with resampling.

My system has no Pulseaudio installed.

**Comment by shoober420** [comment]
I figured out what was happening here. I had to close out of deadbeef for the resampling to enable. With resampling enable, the 24bit tracks will play at normal speed. When I switch over to "Front Speakers" I get the following error, even with resampling enabled.

cannot set sample format to 24 bps (error: Invalid argument), trying all supported formats
Found compatible format 32 bps

Since using the "Front Speakers" option forces resampling OFF, we can see why that error occurs. But whats odd is, my card supports 24bit, and doesn't support 32bit. So deadbeef saying that it found a "compatible format" which is actually not supported at all, is the issue. I have more on this in the open issue.

**Comment by Alexey-Yakovenko** [comment]
> Please reopen this. I just found something. 16bit audio files play as intended, with them playing normal with resampling, and fast with no resampling. 24bit files on the other hand, play too fast regardless of resampling settings. I'll make a diagram to be more specific.

That just means that your computer can play 16 bit streams with different samplerates, than 24 bit files. Which is also common with ALSA. I've seen that more than once.
