### ISSUE TITLE
DeaDBeeF stops music instead of switching to previous track when you're on another playlist

### ISSUE THREAD

**Issue by TotalCaesar659** [DeaDBeeF-Player/deadbeef#1900]
When DeaDBeeF plays music in playlist 1, and you switch to playlist 2 and press "Previous track" button, the player doesn't switch to previous track in playlist 1, but stops music at all. 
"Next track" button works normally.
Deadbeef version: devel
OS: Lubuntu 16.04.3

**Comment by ashed** [comment]
Totally agreee. 
Deadbeef version: 0.7.2
OS: Mint 17.3
