### ISSUE TITLE
Wrong Album Gain by Scanning Selection As Albums (By Tags)

### ISSUE THREAD

**Issue by JulianLai** [DeaDBeeF-Player/deadbeef#1904]
![deepinscreenshot_20171003111616](https://user-images.githubusercontent.com/20014762/31108574-be9d3272-a82c-11e7-9ae5-76ec30c0cef2.png)

### Steps to reproduce the problem
Scan Selection As Albums (By Tags) for the songs from the same album and same disc.
### What's going on? Describe the problem in as much detail as possible.
There are 6 discs in one album, when I scan them as albums(by tags), those songs in the same disc and same album have different replaygain.
### Information about the software:

Deadbeef version: deadbeef-git r7416.6d3fc012-1
OS: Angergos

**Comment by JulianLai** [comment]
It happens to a single disc album, too.

**Comment by Alexey-Yakovenko** [comment]
Is there anything like "disc1", "disc2" in album title in track metadata?
Album title must be identical on all tracks in the same album, for RG scanner to recognise them as single album.
On your screenshot, looks like most tracks have different "album" value, but it's all guesswork, since you forgot to provide this information.

**Comment by Alexey-Yakovenko** [comment]
FYI: this is the title formatting script which is used to compare albums:
`$if2(%artist% - %album%,%filename%)`

**Comment by JulianLai** [comment]
@Alexey-Yakovenko 
No, there are no "disc1", "disc2" in the album title
The album value are the same, but they have different album artists
![deepinscreenshot_20171003180214](https://user-images.githubusercontent.com/20014762/31119935-51b817ba-a865-11e7-9979-3d7dc9e44f3c.png)

**Comment by Alexey-Yakovenko** [comment]
what about artist name?

**Comment by JulianLai** [comment]
@Alexey-Yakovenko If they have the same artist name, the problem is gone, but there are many different artists in one album.

**Comment by JulianLai** [comment]
@Alexey-Yakovenko How about replace the %artist% with %albumartist% in that statement?

**Comment by Alexey-Yakovenko** [comment]
I'm changing to album artist, as I think that would be the right thing, but it won't help in your situation cause the album artist field is blank.

**Comment by Alexey-Yakovenko** [comment]
(%album artist% falls back to %artist% automatically when it's blank)

**Comment by JulianLai** [comment]
@Alexey-Yakovenko It works perfectly!

**Comment by Alexey-Yakovenko** [comment]
Ah, yeah I didn't notice that you have ALBUMARTIST. It's also supported.
