### ISSUE TITLE
Opus files swap channels on playback every now and then

### ISSUE THREAD

**Issue by 38github** [DeaDBeeF-Player/deadbeef#1905]
### Steps to reproduce the problem
Play and opus file and press play every now and then and notice that the channels swap from time to time.

### What's going on? Describe the problem in as much detail as possible.
Audio channels of opus files swap. Left becomes right and vice versa.

### Information about the software:
A git version compiled not that long ago using Clang and LTO. Sorry for not having the exact version. Using Pulseaudio and no DSP.

### Deadbeef version:
Git master
OS: Arch Linux x86_64

**Comment by Alexey-Yakovenko** [comment]
Does it only happen with opus? That would be weird..
Anyway, could you please try to update to the very latest build from master? There was a bug recently, that may have causes this, but it has been fixed.

**Comment by 38github** [comment]
I will compile it right away!

**Comment by 38github** [comment]
With the new build it does not seem to happen anymore and also the problem I had with FLACs sometimes playing super distorted and at low volume is also gone. Great job and a big thanks you for the replaygain scanner! With the next version I will probably be able to uninstall WINE and Foobar2000.

**Comment by Alexey-Yakovenko** [comment]
Thanks!
