### ISSUE TITLE
Deadlock (?) betwen streamer and output plugin

### ISSUE THREAD

**Issue by Lithopsian** [DeaDBeeF-Player/deadbeef#1906]
### Steps to reproduce the problem
Play a track with "stop after current" or the last in a playlist without looping, linear playback.
After the track finishes, attempt to play another track.
Sometimes, reasonably often, the track will fail to start, no tracks can be played, and Deadbeef cannot be shutdown cleanly.

### What's going on? Describe the problem in as much detail as possible.
When this happens, streamer_thread has stopped looping.  It appears to be stuck calling streamer_lock, which is held waiting for the output plugin (alsa in my case) which is also trying to acquire a lock.

This can occur in more than one arrangement, but a typical case is line 535 in palsa_stop() and line 1823 in streamer_read().  palsa_stop() is being called from the AUDIO_STALL_WAIT clause, and streamer_read() is being called from the main palsa_thread() loop.

### Information about the software:
Deadbeef version: trunk
OS: Debian Wheezy

**Comment by shoober420** [comment]
This is happening to me as well.

**Comment by Alexey-Yakovenko** [comment]
Not sure if I fixed all of the occurences, but I was able to reproduce, and fixed the cases which I could find.

**Comment by Alexey-Yakovenko** [comment]
It's still there, reopening
