### ISSUE TITLE
macOS: Audio playback of 192 kHz Ogg Vorbis causes AirPods to switch to 8 kHz output

### ISSUE THREAD

**Issue by kode54** [DeaDBeeF-Player/deadbeef#1910]
### Steps to reproduce the problem
1. Connect to AirPods.
2. Switch the system recording source to something else, so the AirPods switch to their default 44100 Hz 2ch 32-bit float format, which gets encoded to AAC 256kbps.
3. Add 192 kHz stereo Ogg Vorbis file to playlist.
4. Play it.

### What's going on? Describe the problem in as much detail as possible.

When playing the file, the CoreAudio output switches the AirPods to their other sound profile, which is 8000 Hz 16-bit 1ch, instead of staying on the current profile, which is 44100 Hz 32-bit float 2ch.

### Information about the software:

Deadbeef version: 1.0 macOS version (current HEAD as of this post)
OS: macOS 10.13 (17A405)

**Comment by Alexey-Yakovenko** [comment]
Can you please try a build from coreaudio branch? It's using a different / newer API (AudioQueue), and maybe will have fewer problems. It's not 100% stable yet, and lacks some features though.

**Comment by Alexey-Yakovenko** [comment]
I will be tough to fix that on my side, as I don't have airpods..

I hope you can run a debugger session and see what's not going well.

I'm wondering whether 8KHz output mode is set on both mac AND airpods.. And if this is the case -- we can quite easily find out why it's set.

**Comment by kode54** [comment]
I think I spotted the issue in the older code: It's sending kLinearPCMFormatFlagIsSignedInteger even when the requested format is float.

It still causes a format change cycle on the AirPods, but they switch back to AAC now.

**Comment by Alexey-Yakovenko** [comment]
I merged the new coreaudio plugin to master, so this bug is out of date. I have no way of verifying whether it's still valid though. Please let me know how it goes.

**Comment by kode54** [comment]
Nope, no longer applicable.

**Comment by Alexey-Yakovenko** [comment]
Great, thanks.
