### ISSUE TITLE
found copy of plugin "gtkui3_1" (GTK3 user interface), but newer version is already loaded

### ISSUE THREAD

**Issue by JulianLai** [DeaDBeeF-Player/deadbeef#1911]
### Steps to reproduce the problem
open deadbeef
### What's going on? Describe the problem in as much detail as possible.
found copy of plugin "gtkui3_1" (GTK3 user interface), but newer version is already loaded
### Information about the software:

Deadbeef version: deadbeef-git
OS: Antergos

**Comment by Alexey-Yakovenko** [comment]
Same as the other one.

**Comment by JulianLai** [comment]
@Alexey-Yakovenko I can't find this plugin in /usr/lib/deadbeef

**Comment by Alexey-Yakovenko** [comment]
try looking in other places.. like ~/.local/lib

**Comment by Alexey-Yakovenko** [comment]
hrm. sorry for pointing you in a wrong direction. my fault, regression after merging stuff from android branch. will fix.

**Comment by Alexey-Yakovenko** [comment]
fixed now, thanks for spotting.
