### ISSUE TITLE
Duplicate items in the menu

### ISSUE THREAD

**Issue by JulianLai** [DeaDBeeF-Player/deadbeef#1912]
![deepinscreenshot_20171016105824](https://user-images.githubusercontent.com/20014762/31593436-3238eb52-b261-11e7-9a9b-dfc3561ea940.png)

### Steps to reproduce the problem
right click on the music -> ReplayGain
### What's going on? Describe the problem in as much detail as possible.
duplicate items in the menu
### Information about the software:

Deadbeef version: deadbeef-git
OS: Antergos

**Comment by Alexey-Yakovenko** [comment]
That indicates that you have duplicate plugins, remove them - and the problem will be solved.
