### ISSUE TITLE
LossyWAV & Flac convert settings?

### ISSUE THREAD

**Issue by 38github** [DeaDBeeF-Player/deadbeef#1914]
In Foobar2000 I convert to LossyWAV using:
/d /c c:\audio_codecs\lossyWAV - -q high --linkchannels -s f -m --maxclips 0 -w --bitdist --silent --stdout|c:\audio_codecs\flac - -b 512 -5 -f -o %d --ignore-chunk-sizes

Do you know how I can setup Deadbeef to convert in a similar way? Regards

**Comment by Alexey-Yakovenko** [comment]
most likely the same.

**Comment by Alexey-Yakovenko** [comment]
is there a specific problem that you can't figure out in deadbeef?

**Comment by 38github** [comment]
I am really bad at the commands and what they actually do and therefore I can't "convert" them to appropriate Linux/Deadbeef commands. In short I am really bad at it.

**Comment by Alexey-Yakovenko** [comment]
It should be literally the same line, except `%o` in place of `%d` (a different name for the same thing)

```
lossyWAV - -q high --linkchannels -s f -m --maxclips 0 -w --bitdist --silent --stdout | flac - -b 512 -5 -f -o %o --ignore-chunk-sizes
```

**Comment by Alexey-Yakovenko** [comment]
(that's assuming you have both flac and lossyWAV in your $PATH)

**Comment by 38github** [comment]
Thank you so much! I did suspect that /d /c had to be removed and the windows dir paths. I was unsure of stdout and I see you used a space after it compared to how it is used in Foobar2000. What does the "-" after lossywav do when I use lossywav in a terminal with single files I do not have to use a "-".

It seems to work beautifuly now. I have said it before but now I am even closer to quit using Foobar2000 and WINE.

**Comment by 38github** [comment]
lossywav does not seem to create the bitdist/log file though which usually ends up in the destination and has information about how many bits has been removed. I will ask the author of LossyWAV if he might know why this happens. Hopefully he has tried it on Linux.

**Comment by 38github** [comment]
I did notice that the lossywav.log file is created one folder below where I set my output. If the audio files are set to end up in /music/when_20_summers_pass/ the lossywav.log file ends up in /music/
