### ISSUE TITLE
play Youtube to url

### ISSUE THREAD

**Issue by Artlant** [DeaDBeeF-Player/deadbeef#1919]
add the ability to play direct link to **Youtube** video.

exemple:

1. `file` `> add location`
2. insert `https://www.youtube.com/watch?v=rkDL4BqKc08`
3. deadbeef played `.m4a` file.

This opportunity would be very cool

**Comment by GitProfile** [comment]
Maybe [youtube-dl](https://github.com/rg3/youtube-dl) will help?

**Comment by Artlant** [comment]
@GitProfile 
Downloading files and listening in general can be, although not very convenient (I'm now doing this) but for example listen to a playlist in the player is not possible.
I understand that I require a not very demanded feature, in effect a substitute for downloading and listening in the stream of youtube.
B probably will close this issues as I'm almost sure that no one realizes it and everyone is lazy.

**Comment by GitProfile** [comment]
@Artlant 
Personally I have a list of streams (24/7 uptime) and I would like to listen through DeedBeef.
Is it possible?

**Comment by Alexey-Yakovenko** [comment]
@GitProfile it's not possible.
