### ISSUE TITLE
Add support for external tag editors

### ISSUE THREAD

**Issue by geplus** [DeaDBeeF-Player/deadbeef#1920]
Hi,
considering that you will not support the cover add in media tags in a short time (#1854), and that I personally have many problems with the tag edior of deadbeef (if I add new tags in some song, I cant modfy or delete them anymore), can you add support for extenal tag editors, like puddletag , for modfy the songs in the playlists or in the folders (folder browser tree view) with an exteral tag editor?

**Comment by Alexey-Yakovenko** [comment]
It is about as hard to find time to add puddletag support, as it is to add album art editor.

However, being unable to modify or remove the tags sounds weird -- this issue has not been reported before. Which version of the player are you using?

**Comment by Alexey-Yakovenko** [comment]
On the other hand.. I believe you can create a custom action using "shellexec" plugin, it comes standard, and has UI.. Then you can bind that to a hotkey. Please contact me if you want to share your issue with editing tags in deadbeef itself. There are no known issues about that.
