### ISSUE TITLE
deadbeef does not play podcast

### ISSUE THREAD

**Issue by rohshall** [DeaDBeeF-Player/deadbeef#1923]
### Steps to reproduce the problem
1. Add any podcast URL in open location prompt
### What's going on? Describe the problem in as much detail as possible.
1. Podcast episodes are not loaded
### Information about the software:

Deadbeef version: 0.7.2-2
OS: Arch Linux

**Comment by Alexey-Yakovenko** [comment]
static builds of deadbeef 072 don't support https -- that's probably why.
unless you're using HTTP. then it should work.
have you tried the latest build? like 1.8-alpha?

**Comment by Alexey-Yakovenko** [comment]
another reason could be that you're adding podcast feed directly -- that's not supported. deadbeef can only play audio streams directly, or from m3u and pls urls.

**Comment by rohshall** [comment]
Thanks for replying Alexey. Yes, I thought the podcast feeds are supported.
