### ISSUE TITLE
last.fm scrobbler not working

### ISSUE THREAD

**Issue by mistersister** [DeaDBeeF-Player/deadbeef#1928]
The scrobbler doesnt scrobble. I made sure the login info is correct, but seems like my system stopped scrobbling about a month ago. I also tried to change the http protocol to https but there was no difference. Starting the player with factory defaults didnt work wither.

I know the service is up since Spotify on Linux and Foobar on win scrobble just fine.

Im using the official static x64 build for deadbeef 0.7.2 running on Arch Linux.

**Comment by Alexey-Yakovenko** [comment]
Hello.
The most common occurrence when the scrobbling stops working is when linux system clock is off.
If it's not that -- I don't know.. Try running the latest build (the link is on the main page on github), and it might be able to display a specific error.

**Comment by mistersister** [comment]
After reading your advice, I installed a ntp deamon to sync the time and the scrobbler came back to life automagically. Its strange since I never had a ntp installed on my home computers and the scrobbler always worked fine to me.

I any case, I think its safe to close this ticket now. Thank you very much!!

**Comment by Alexey-Yakovenko** [comment]
It's not because of ntp.. just because the time is significantly off, and when scrobbles are sent -- they use the system time, and then the server rejects them.
