### ISSUE TITLE
[FLAC + CueSheet] Incorrect song is playing

### ISSUE THREAD

**Issue by aleksander** [DeaDBeeF-Player/deadbeef#1930]
### Steps to reproduce the problem

1. Add folder with one album to the playlist
1. Start play first song from the album

### What's going on? Describe the problem in as much detail as possible.

Instead of the first song from the album last song is playing.
For every other song "Failed to play track: ..." error message is displayed.
There is no such problem if I remove cuesheet from folder or if I do "add file" instead of "add folder".
Cuesheet looks exact the same as VORBIS_COMMENT block of flac metadata.

Format: flac + cuesheet
Tag type: VorbisComments | CueSheet

### Information about the software:

Deadbeef version: 7672be44
OS: Linux 4.13.12-1-ARCH

EDIT: fix typo

**Comment by Alexey-Yakovenko** [comment]
and another question: does the same problem happens if you use our binaries?

**Comment by aleksander** [comment]
> Does this happen with any flac+cue, or 1 specific album?

This happen with all 9 albums of the the same artist taken from (and grabbed by) one person.
I was unable to find another flac+cue albums in my library with such a problem.

> does the same problem happens if you use our binaries?

With your last binaries (0.7.2) there is another bug (#1851) with the same artist albums.
This bug is not reproduced with 0.7.2.

**Comment by Alexey-Yakovenko** [comment]
I didn't mean the 0.7.2 binaries - I meant the [build from master branch](https://sourceforge.net/projects/deadbeef/files/travis/linux/master/) or [a build of 1.8alpha](https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8/).

Please contact me over this email, and we can work to resolve the issue
`waker@users.sf.net`

**Comment by aleksander** [comment]
> I didn't mean the 0.7.2 binaries - I meant the build from master branch or a build of 1.8alpha.

Yes, problem reproduced on both builds (master branch static x86_64, 1.8.0-alpha3 static x86_64).

> Please contact me over this email, and we can work to resolve the issue
> waker@users.sf.net

Sent a email.

**Comment by Alexey-Yakovenko** [comment]
Thanks for the help, the problem has been fixed.

**Comment by aleksander** [comment]
Wow! That was fast. Thank you!
