### ISSUE TITLE
gtkui: convert to GtkBuilder

### ISSUE THREAD

**Issue by cspk** [DeaDBeeF-Player/deadbeef#1932]
Opening the `deadbeef.glade` UI file with recent Glade versions (3.x.x) results in nothing due to libglade deprecation in favor of GtkBuilder:
> (glade:32567): GladeUI-WARNING **: Couldnt recognize GtkBuilder xml, skipping 
 home/user/src/deadbef/plugins/gtkui/deadbeef.glade

**Comment by Alexey-Yakovenko** [comment]
deadbeef is using a custom version of Glade 2, which is provided in the tools folder.
None other Glade versions can be used.
