### ISSUE TITLE
Couldn't build deadbeef: recipe for target 'temp/gtkui-gresources.c' failed

### ISSUE THREAD

**Issue by cryptofuture** [DeaDBeeF-Player/deadbeef#1933]
### Steps to reproduce the problem
Trying to build deadbeef df8b388 

### What's going on? Describe the problem in as much detail as possible.
```
/bin/bash ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..    -std=c99 -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -g -O2  -D_GNU_SOURCE  -DLIBDIR=\"/usr/lib\" -DPREFIX=\"/usr\" -DDOCDIR=\"/usr/share/doc/deadbeef\" -DDDB_WARN_DEPRECATED=1 -c -o ddb_gui_GTK3_la-clipboard.lo `test -f 'clipboard.c' || echo './'`clipboard.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -std=c99 -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -D_GNU_SOURCE -DLIBDIR=\"/usr/lib\" -DPREFIX=\"/usr\" -DDOCDIR=\"/usr/share/doc/deadbeef\" -DDDB_WARN_DEPRECATED=1 -c clipboard.c  -fPIC -DPIC -o .libs/ddb_gui_GTK3_la-clipboard.o
/bin/bash ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..    -std=c99 -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -g -O2  -D_GNU_SOURCE  -DLIBDIR=\"/usr/lib\" -DPREFIX=\"/usr\" -DDOCDIR=\"/usr/share/doc/deadbeef\" -DDDB_WARN_DEPRECATED=1 -c -o ddb_gui_GTK3_la-rg.lo `test -f 'rg.c' || echo './'`rg.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -std=c99 -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -D_GNU_SOURCE -DLIBDIR=\"/usr/lib\" -DPREFIX=\"/usr\" -DDOCDIR=\"/usr/share/doc/deadbeef\" -DDDB_WARN_DEPRECATED=1 -c rg.c  -fPIC -DPIC -o .libs/ddb_gui_GTK3_la-rg.o
/usr/bin/glib-compile-resources --target=temp/gtkui-gresources.c --sourcedir=. --generate-source gtkui.gresources.xml
can't write to file temp/gtkui-gresources.cMakefile:1706: recipe for target 'temp/gtkui-gresources.c' failed
```
Full build log: 
[deadbeef_0.7.3-12-df8b388-ppa10~xenial_amd64.build.txt](https://github.com/DeaDBeeF-Player/deadbeef/files/1524882/deadbeef_0.7.3-12-df8b388-ppa10.xenial_amd64.build.txt)

Also had just the same problem with a0422ae 
https://launchpadlibrarian.net/339975679/buildlog_ubuntu-xenial-amd64.deadbeef_0.7.3-11-a0422ae-ppa10%7Exenial_BUILDING.txt.gz
### Information about the software:
Deadbeef version: df8b388 
OS: Ubuntu xenial

**Comment by Alexey-Yakovenko** [comment]
What you're building is definitely **not** 0.7.3, so maybe it's a good thing it fails.

0.7.3 doesn't exist, the next release is going to be 1.8.

In a way, it's a cool feature that deadbeef sources prevent making packages off random git revisions.

It would be nice to fix this before shipping 1.8 though.

**Comment by cryptofuture** [comment]
I just take last master commit every month or two and build it, for personal use. 0.7.3 was made by error sometime ago, when I wanted to build 0.7.1-3 but uploaded 0.7.3 instead. So now, i just have no other option, beside use 0.7.3, before some new version will be released. But yes, only actual commit name matters here. And point is i couldn't build df8b388

**Comment by Alexey-Yakovenko** [comment]
Well.. that's a known issue, which is marked as critical to fix before shipping 1.8, which is gonna happen pretty soon. Stay tuned.

**Comment by cryptofuture** [comment]
Roger, thanks for input!

**Comment by Alexey-Yakovenko** [comment]
oh and btw, you can still build directly, when not using ubuntu packaging, or you can use the provided binary builds.

**Comment by cryptofuture** [comment]
Note: probably you just don't need to read it all, but this clears my intentions on doing it
I know about binary packages, but I just don't like the way they was made, and at some time some package segfaulted for me, I thought about, and decided not to bother you and just do it myself. Beside I had no own 3-rd party software update reporting system at that moment, but wanted reasonably frequent master builds, but not just daily static builds.
Also, after a while I discovered that default deadbeef desktop file duplicates controls in the plank panel (which was very minor to reporting, but in case I'd made it pull request it would remove other languages beside english support in the desktop file, so thats probably reject anyway - was problem on the plank dock side), and yes I wanted also no dsp in the deadbeef package by default, so yes personal PPA was the best way to do for me.  And yes, those static daily packages was real pain , because you need to unpack it manually every time, and other packages was for release tags, which was not good for me too. Beside when I download binary package from sourceforge, i didn't even feel like In in 200x, but like I'm in 9x. And also install in opt, was not in my taste.

**Comment by Alexey-Yakovenko** [comment]
Yeah, I understand that many users want real packages, managed by their system repository, but I can't provide that. It's not under my control.

**Comment by cryptofuture** [comment]
Yes, I understand you too, since time on packaging could be used on project itself or on another important things. And its not the developer responsibility to package software in the first place.

**Comment by Alexey-Yakovenko** [comment]
Nah, the packaging process is relatively simple these days with the help of docker and services like travis-ci - it could be scripted. But, unlike other operating systems, linux distro repositories don't let the developers in. They're pretty restricted and locked out.

**Comment by cryptofuture** [comment]
It easy to automate packaging, but you can't actually test it in the every distro.
Yes like ~30 packages for popular distributions only. Only 4 packages for every common used releasename (if we not talking about rolling) for the same distro.
Actually deadbeef is quite popular and easy to package, so you could just contact (even making help needed issue on github could be enough) already made ppa maintainers, aur and etc say something like package only tags, and thats it. At least mostly the same approach was used for wireguard, but since Jason is old school he used mailling list, instead of github issue. But deadbeef would be the way easier for maintainers, since is not like you make tags too freq, and its not kernel module, where you need to do hacks for every distro releasename kernel to build it, or have new surprises when you build for arm. (I'm along wireguard ubuntu ppa maintainers). Another common approach is to find popular ppa, aur etc, and just add links to your projectpage without contacting people and write something like "I have no responsibility, but you can find binary package for your distro here".

**Comment by Alexey-Yakovenko** [comment]
and linking PPA/AUR is probably fine, except it's not much different than downloading binaries from the website.

**Comment by cryptofuture** [comment]
> and linking PPA/AUR is probably fine, except it's not much different than downloading binaries from the website.
This is might be not different for you, but its a lot more easy for the end user. For example I even configured and tunned scrapper for this purpose, to just know when some new release or tag is. But most people check new versions on websites manually, which is real pain.

**Comment by Alexey-Yakovenko** [comment]
Yeah, I agree this is not good. Right now the only way to get updates is more or less manual, like RSS, or Facebook/G+ pages, and various forum posts. I hope to come up with an in-app update notification in the future.

**Comment by Alexey-Yakovenko** [comment]
@cryptofuture it should be fixed now, please try.

**Comment by cryptofuture** [comment]
Worked, like charm!
