### ISSUE TITLE
Can't run deadbeef

### ISSUE THREAD

**Issue by JulianLai** [DeaDBeeF-Player/deadbeef#1940]
### Steps to reproduce the problem
run deadbeef
### What's going on? Describe the problem in as much detail as possible.
`GLib-GIO:ERROR:../glib/gio/gdbusconnection.c:4155:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)`
### Information about the software:

Deadbeef version: deadbeef-git
OS: Antergos (linux-mainline 4.15rc3)

**Comment by Alexey-Yakovenko** [comment]
no useful information provided

**Comment by JulianLai** [comment]
@Alexey-Yakovenko 
It doesn't happen after I reboot, still don't know why.
