### ISSUE TITLE
DeaDBeeF crashes xfce4-panel

### ISSUE THREAD

**Issue by aladar42** [DeaDBeeF-Player/deadbeef#1943]
Hey, I don't know much about development, so I have a very limited understanding of the errors, so hopefully I'm posting this on a correct project. This happens pretty much every time I play any music in Deadbeef.

### Steps to reproduce the problem
1. Play music
2. After a while xfce4-panel crashes

### What's going on? Describe the problem in as much detail as possible.
xfce4-panel crashes, attempting to bring it back up from terminal produces following errors:
```
[aladar@GLaDOS]: ~/Desktop>$ xfce4-panel
xfce4-panel: cairo-scaled-font.c:462: _cairo_scaled_glyph_page_destroy: Assertion `!scaled_font->cache_frozen' failed.

(wrapper-2.0:19220): Gtk-WARNING **: Negative content width -3 (allocation 1, extents 2x2) while allocating gadget (node button, owner PulseaudioButton)
Aborted (core dumped)
[aladar@GLaDOS]: ~/Desktop>$ xfce4-panel
xfce4-panel: cairo-scaled-font.c:462: _cairo_scaled_glyph_page_destroy: Assertion `!scaled_font->cache_frozen' failed.
Aborted (core dumped)
[aladar@GLaDOS]: ~/Desktop>$ 
(wrapper-2.0:19870): Gdk-ERROR **: The program 'wrapper-2.0' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 288 error_code 3 request_code 10 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```
After which running xfce4-panel succesfully launches it, but kills Deadbeef. Panel then functions properly until Deadbeef is launched again and music is played:

```
connecting button tray signals
xfce4-panel: cairo-scaled-font.c:462: _cairo_scaled_glyph_page_destroy: Assertion `!scaled_font->cache_frozen' failed.
Aborted (core dumped)
```

Hopefully this is an actual bug and not something I have caused on my end.
### Information about the software:

Deadbeef version: 0.7.2
OS: Arch Linux, XFCE DE

**Comment by Alexey-Yakovenko** [comment]
deadbeef crashes -> deadbeef bug
xfce crashes -> xfce bug

**Comment by aladar42** [comment]
"After which running xfce4-panel succesfully launches it, but kills Deadbeef."

Deadbeef crashes.

**Comment by Alexey-Yakovenko** [comment]
deadbeef 0.7.2 was released 1.5 years ago and didn't change. It didn't crash with XFCE.
The logs and the problem description you posted indicate a problem with your WM, there's nothing I can do.
Changing to another WM or reinstalling your OS might solve the problem.

**Comment by Alexey-Yakovenko** [comment]
If you have system tray enabled in deadbeef, someone might have broke system tray implementation in XFCE panel, so disabling this feature in deadbeef might help.

**Comment by aladar42** [comment]
Alright, thanks.
