### ISSUE TITLE
ffap: Incorrect decoding of Monkey's Audio (APE) files with single‐channel silence

### ISSUE THREAD

**Issue by announ** [DeaDBeeF-Player/deadbeef#1951]
### Steps to reproduce the problem
Play this audio file: [Pink Noise – Left channel only.ape.gz](https://github.com/DeaDBeeF-Player/deadbeef/files/1596546/Pink.Noise.Left.channel.only.ape.gz)
Alternatively, convert it and compare it with the original: [Pink Noise – Left channel only.wav.gz](https://github.com/DeaDBeeF-Player/deadbeef/files/1596547/Pink.Noise.Left.channel.only.wav.gz)

### What's going on? Describe the problem in as much detail as possible.
After an announcement, there should be 22 seconds of pink noise in the left channel. Instead, the noise is entirely absent.

This is a bug in the ffap decoder plugin with stereo frames with one silent channel.
It has been fixed in [Rockbox](https://git.rockbox.org/?p=rockbox.git;a=commit;h=dca9f42cdf577f6ca0b2abde6680e495d2a3373a) and [FFmpeg](https://github.com/FFmpeg/FFmpeg/commit/9149e9c0baaec122bc3da925d6068dffa60b5427). See these linked commits for details.

### Information about the software:
Deadbeef version: devel (2017-12-28)
OS: Ubuntu 17.10

**Comment by announ** [comment]
7bb37a8 reintroduced this bug.

**Comment by Alexey-Yakovenko** [comment]
ugh again.. I thought I tested this case :(

**Comment by Alexey-Yakovenko** [comment]
huh..  I fixed it correctly at first, but then accidentally broke it again when cleaning up the change. seems to be working correctly now.
