### ISSUE TITLE
ffap: Error decoding mono Monkey's Audio (APE) files with silence

### ISSUE THREAD

**Issue by announ** [DeaDBeeF-Player/deadbeef#1952]
### Steps to reproduce the problem
Play this audio file: [22.ape.gz](https://github.com/DeaDBeeF-Player/deadbeef/files/1598428/22.ape.gz)
Alternatively, convert it and compare it with the original: [22.wav.gz](https://github.com/DeaDBeeF-Player/deadbeef/files/1598429/22.wav.gz)

Many other files taken from the same [source](https://tech.ebu.ch/publications/sqamcd) have a similar structure and exhibit the same problem when encoded to a mono Monkey's Audio file at default settings; and almost all the rest exhibit subtler (mostly inaudible) decoding errors too.

### What's going on? Describe the problem in as much detail as possible.
Two arpeggios played on a trombone should be heard, followed by two short melodious phrases. DeaDBeeF decodes and plays only the arpeggios. (Tho, it can play the other parts if they are seeked to directly.)
The following error appears on the console:
```
ape: Error decoding frame, error=1
```
This is a regression introduced in the ffap decoder plugin by [commit db6b0ef](https://github.com/DeaDBeeF-Player/deadbeef/commit/db6b0ef12a35b929166f7d579d4e7cdf28e6a51c).

### Information about the software:
Deadbeef version: devel (2018-01-02)
OS: Ubuntu 17.10

**Comment by Alexey-Yakovenko** [comment]
ugh :(

**Comment by announ** [comment]
Here is one of the tracks that decode incorrectly, but not audibly differently: [06.ape.gz](https://github.com/DeaDBeeF-Player/deadbeef/files/1598514/06.ape.gz)
This error is printed to the console:
```
ape: Error decoding frame, ptr >= data_end
```
The decode is only missing silence at the end.

**Comment by Alexey-Yakovenko** [comment]
should be better now
