### ISSUE TITLE
AudioObjectSetPropertyData when playing random song

### ISSUE THREAD

**Issue by COOLIRON2311** [DeaDBeeF-Player/deadbeef#1953]
This pops up in log when playing random songs. I tried to find a constant pattern of when this bug (or not a bug) appears but it seems that there is no such.
```
AudioObjectSetPropertyData kAudioDevicePropertyStreamFormat: 21646174
AudioObjectSetPropertyData kAudioDevicePropertyStreamFormat: 21646174
AudioObjectSetPropertyData kAudioDevicePropertyStreamFormat: 21646174
AudioObjectSetPropertyData kAudioDevicePropertyStreamFormat: 21646174
```
Note: It pops up 4 times for one song (and one click).

DeaDBeeF version: GitHub `1637a33`
OS: macOS High Sierra 10.13.2

**Comment by COOLIRON2311** [comment]
@Alexey-Yakovenko bug stil presents but the output is a little bit different.
```
AudioObjectSetPropertyData kAudioDevicePropertyStreamFormat: 21646174
AudioObjectSetPropertyData kAudioDevicePropertyStreamFormat: 21646174
```

**Comment by Alexey-Yakovenko** [comment]
Are you sure you're running the latest build? I knew about this issue for a long time obviously, but it stopped happening for me completely after the fix.. I'll keep an eye on it, maybe it triggers after some specific condition.

**Comment by COOLIRON2311** [comment]
@Alexey-Yakovenko Yes, I am sure that I am running the latest build. The bug still presents. The only difference is that it outputs two lines into log instead of four and this only happens on the first launch of the 'damaged' song. If I switch to this song later nothing appears in log (it appeared before patch).

**Comment by Alexey-Yakovenko** [comment]
ok.. what kind of "damaged" song is it, and can you send it to me?

**Comment by COOLIRON2311** [comment]
No problem
[song.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/1606531/song.zip)

**Comment by Alexey-Yakovenko** [comment]
Tried.. there's nothing wrong with this file, and the message doesn't pop up for me..

**Comment by Alexey-Yakovenko** [comment]
anyway... I'm going to replace the coreaudio plugin again soon, to have the same code between ios and macos. so this problem most likely will be gone.

**Comment by COOLIRON2311** [comment]
@Alexey-Yakovenko I know what causes it. I am using Boom 3D for better sound quality on my Mac.
After disabling it everything works fine.

**Comment by oleksiy-unity3d** [comment]
I will check it out.

**Comment by Alexey-Yakovenko** [comment]
Yes, boom3d causes format setting call to fail even when the format is the same as current.
I had to remove the error message completely.
