### ISSUE TITLE
 Failed to load help file

### ISSUE THREAD

**Issue by Nexus01** [DeaDBeeF-Player/deadbeef#1954]
### Steps to reproduce the problem
alt+H
H

### What's going on? Describe the problem in as much detail as possible.
then the software said "Failed to load help file"
Failed to load help file
### Information about the software:

Deadbeef version:0.7.2
OS:AOSC OS 5.0(Linux version 4.13.16-aosc-main)

**Comment by Alexey-Yakovenko** [comment]
You need to install deadbeef differently, so that the help file is restored.
