### ISSUE TITLE
ALSA output distorts audio after any change to DSP chain

### ISSUE THREAD

**Issue by 64542426** [DeaDBeeF-Player/deadbeef#1959]
NOTE: below is the original bug report, however the issue happens after most changes to DSP chain, e.g. after adding or removing a node.

I noticed that activation of Equalizer (Enable options) stops music on the background. 
![2018-01-16-151620_377x28_scrot](https://user-images.githubusercontent.com/35492934/34993543-9147d90a-fac8-11e7-924e-ccaf06bbcc06.png)

And if it held checked, music doesn't start playing at the opening of the program.

Equalizer it's important to me, i use "foobar feq's" like loudness.feq, home_theater.feq etc... but if activation of equalizer doesn't works these feq's are invalid.

When i active Enable from console i receive this message:
**cannot set parameters (Invalid argument)**
This issue does not happen on the current stable version.

### Information about the software:

Deadbeef version: **deadbeef-static_devel-1_i686.tar.bz2**
https://sourceforge.net/projects/deadbeef/rss?path=/travis/linux/master

OS: Devuan GNU/Linux 1 (jessie) i686

Sound Architecture (ALSA)

Themes: GTK2

No external plugins are used.

**Comment by Alexey-Yakovenko** [comment]
I just got to try this, and there's indeed a problem (it's bigger than just the EQ though).
Meanwhile the workaround is to use pulseaudio plugin instead, which doesn't have this issue.

**Comment by 64542426** [comment]
Thanks for your reply Alexey also for looking into this task, I was waiting impatiently for a fix by checking the recent updates. By the way I looked the red bug staying there, I thought there was going to be some serious thing.

I haven't installed PulseAudio on my system, and pulse.so does not work alone. 
Nor i have in mind to install PA. I'll use DeaDBeeF without EQ like i did recently. Yes, i miss the EQ because sounds more flawless. Hope you'll find a way  to bring back on work with ALSA in the future.

Thanks again for your efforts trying to fix it.

See you in other Ticket.
Nili

**Comment by Alexey-Yakovenko** [comment]
the red bug is just a label, all bugs have the same color. it just helps with filtering.
however, the issue is critical for shipping 1.8 indeed, and I'll be working on fixing it as soon as possible.

**Comment by 64542426** [comment]
Understand, That's a good news for me Alexey, I will wait patiently. 
Thank you for your effort once again.

**Comment by Alexey-Yakovenko** [comment]
This has been fixed

**Comment by 64542426** [comment]
Thank you very much Alexey, That's a very quick fix :) Best regards!
