### ISSUE TITLE
[Feature Request] Album Hierarchy

### ISSUE THREAD

**Issue by D0RMAN** [DeaDBeeF-Player/deadbeef#1960]
It would be great to have an ability to group albums in a tree hierarchy. 

For example:
* Metallica
  * best
  * singles
    * some single 1
    * some single 2
    * some single 3 
  * albums
    * some album 1
    * some album 2
    * some album 3

Here `best`, `some single 1`, `some single 2`, `some single 3`, `some album 1`, `some album 2`, `some album 3` are leave-playlists which actually contains audio tracks. `Metallica`, `singles` and `albums` are intermediate-playlists which contains other intermediate-playlists or leave-playlists but not actually audio tracks.

**Comment by Alexey-Yakovenko** [comment]
This is a planned feature of media library (which is in the works, but not quite ready yet).
It's very unlikely to get such functionality in the playlist view though.

**Comment by Alexey-Yakovenko** [comment]
This request seems to be a subset of issue #1740, marking as duplicate.
