### ISSUE TITLE
DSD in Wavpack

### ISSUE THREAD

**Issue by greenvorbisfan** [DeaDBeeF-Player/deadbeef#1973]
При попытке добавить файл формата DSD, DSF или DFF, упакованный в Wavpack lossless,
> `wavpack -hh infile.dff outfile.wv #упаковка в Wavpack`
> `wvunpack outfile.wv #распаковка в DSD`

в логе проигрывателя вываливается ошибка:
```
ERROR: could not load: /home/user/Музыка/test_dff.wv
plt_load: failed to open file:///home/user/Музыка/test_dff.wv
```

В консоли:

`wavpack error: not configured to handle DSD WavPack files!`

Deadbeef GIT (master)
Ubuntu 17.10 x64
[Тестовый файл](https://drive.google.com/open?id=1GWLSMBfsrzOE93VA6_9A80Iz_lUst2fJ)

**Comment by Alexey-Yakovenko** [comment]
There are multiple reasons why this might be not working.

1. if you're using a static build of deadbeef, it's still using wavpack 4.x, and needs an update.
2. if you built it yourself, this indicates that the wavpack library in Ubuntu was not compiled with DSD support.

I can fix the 1st issue, but I can't do anything about the 2nd.

**Comment by greenvorbisfan** [comment]
Проверил — libwavpack скомпилирован с поддержкой DSD. Собственно, это же подтверждает и скомпилированный с ним mpd — проигрывает вышеуказанный файл без проблем.

**Comment by Alexey-Yakovenko** [comment]
ok. problem is found and fixed.

**Comment by Alexey-Yakovenko** [comment]
Static build on mac already has the feature,
but linux static builds won't get it until I update wavpack.

**Comment by greenvorbisfan** [comment]
Пересобрал с последними изменениями — отлично работает. Спасибо!
![ddb_dsd_test](https://c.radikal.ru/c10/1802/83/2bfc74a654da.png)

**Comment by ArminiusTux** [comment]
Wavpack-DSD and other DSD types play fine on Raspbian  (v1.8.0 beta 2 compiled on RPi 3 B+), assuming the audio renderer is set to PulseAudio.
