### ISSUE TITLE
Feature Request: Integrate with Discord Rich Presence to show currently playing song

### ISSUE THREAD

**Issue by StewieFellows** [DeaDBeeF-Player/deadbeef#1977]
DeaDBeeF does not show the currently playing song, play/pause status, nor album art on one's Discord profile while using the program.

Discord Canary 0.0.45-1
Deadbeef version: 0.7.2-3
OS: Manjaro Linux 17

**Comment by kuba160** [comment]
Discord Rich Presence is designed for videogames, I don't think that this feature should be standard for a music player. I have made a custom plugin that implements Discord Rich Presence:
![image](https://user-images.githubusercontent.com/6359901/37570313-94e681fa-2aee-11e8-8b65-cd786c999a0f.png)

It is very configurable:
![image](https://user-images.githubusercontent.com/6359901/37570322-c8a79236-2aee-11e8-875f-ba317ded6b25.png)

I will upload source code to github soon. If you would like to test here is a binary (compiled for x86_64 on Debian 9, can't promise it will work on your system)
[discord_presence.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/1823064/discord_presence.zip)

**Comment by StewieFellows** [comment]
Thanks for the plugin @kuba160! It worked for me on Manjaro Linux without any issues. Yeah, as far as putting the request up, I noticed someone had it working for Foobar2000. Now that I think about it...I'm wondering if they're using a plugin too.

That being said, thanks again!

**Comment by Alexey-Yakovenko** [comment]
Hi @kuba160 , would you let me know when you put it on github? I'd like to add it to wiki, and close this issue :)

**Comment by kuba160** [comment]
@StewieFellows @Alexey-Yakovenko my plugin can be found [here](https://github.com/kuba160/ddb_discord_presence)

**Comment by Alexey-Yakovenko** [comment]
Thanks, added to wiki.
