### ISSUE TITLE
Curl error 60 (SSL certificate problem) accessing lastfm for (legacy) artwork

### ISSUE THREAD

**Issue by Lithopsian** [DeaDBeeF-Player/deadbeef#1979]
### Steps to reproduce the problem
1. Configure the legacy artwork plugin to search for cover images at lastfm (and nowhere else)
2. Play a track where there should be a cover image at lastfm
3. Artwork doesn't load, default image doesn't load, and network activity is high

### What's going on? Describe the problem in as much detail as possible.
The artwork plugin finds an https location for the artwork.  When it attempts to copy down the image, Curl fails with error 60 which means there is no SSL certificate for the url.  It aborts the request and returns zero bytes and errno 0.  The artwork plugin doesn't understand this and ends up with neither a cover image nor an understanding that its request failed, so it keeps trying continuously.

The artwork plugin could be fixed to behave better in this situation, but I don't know what should be done about Curl.  Is there something in my build that has failed to load certificates?  Is it just because of Debian not automatically downloading a certificate package with libcurl?  Does vfs_curl need to catch this and pass information back to the caller?

### Information about the software:
Deadbeef version: trunk
OS: Debian

**Comment by Alexey-Yakovenko** [comment]
Have you tried fetching from the same URL using command line curl? Does it work?

**Comment by Alexey-Yakovenko** [comment]
> The artwork plugin could be fixed to behave better in this situation, but I don't know what should be done about Curl. Is there something in my build that has failed to load certificates? Is it just because of Debian not automatically downloading a certificate package with libcurl? Does vfs_curl need to catch this and pass information back to the caller?

You can find out answers to most of these questions by running curl on command line with the same URL.

> The artwork plugin doesn't understand this and ends up with neither a cover image nor an understanding that its request failed, so it keeps trying continuously.

This needs fixing.

**Comment by Lithopsian** [comment]
> Have you tried fetching from the same URL using command line curl? Does it work?

Works fine on the command line.  I can pipe the result to a file and it displays as a nice image.  Example command:
`curl https://lastfm-img2.akamaized.net/i/u/300x300/266c665f4a2447e892c57644a24756f4.png > test.png`

**Comment by Alexey-Yakovenko** [comment]
are you sure that the same version of libcurl is used by command line curl and deadbeef?

**Comment by Lithopsian** [comment]
> >     The artwork plugin doesn't understand this and ends up with neither a cover image nor an understanding that its request failed, so it keeps trying continuously.
> 
> This needs fixing.
> 

I'll put together a pull request.

**Comment by Lithopsian** [comment]
> are you sure that the same version of libcurl is used by command line curl and deadbeef?

I don't think it is.  The plugin is linked against libcurl-gnutls.so.  /usr/bin/curl is linked against libcurl.so.

**Comment by Alexey-Yakovenko** [comment]
well there you go. find a way to link deadbeef to libcurl-gnutls, and the problem will be solved. or fix the other libcurl.so to work with SSL.

**Comment by Lithopsian** [comment]
Or the other way round.  I linked vfs_curl.so against libcurl.so and it can access https urls now.  libcurl_gnutls.so is supposed to have ssl capabilities built in but obviously something not quite working.
