### ISSUE TITLE
Track Properties - Metadata fields can't Edited or Saved

### ISSUE THREAD

**Issue by 64542426** [DeaDBeeF-Player/deadbeef#1985]
### Steps to reproduce the problem
Add column > Custom > %genre%
On the playlist, right click on a song name > Track Properties > Genre
Add here : Rock
See if can be saved...

### What's going on? Describe the problem in as much detail as possible.
I don't have idea when it started but on the current dev-version Genre **%genre%** doesn't save the input i add. The Genre column remain blank.
On the stable doesn't have this issue.

### Information about the software:
N/A
No error messages are displayed on the command line during this action.

Deadbeef version: deadbeef-static (devel-1 i686)
OS: Devuan

**Comment by Lithopsian** [comment]
WFM, on trunk.  Maybe only some file types?  Are you saving the genre field after editing (return or move to different field) before clicking apply?

**Comment by 64542426** [comment]
Thanks for your asks Lithopsian,
No, not only on some files, on many different files and formats i can't sets a name like J-Pop or J-Rock on the genre But...

Now that I'm watching other fields aswell doesn't save anything to others either.

Artist
Track Title
Album

If i edit something with hand on those fields nothing is saved.

Tried different audio formats, MP3, WAV, M4a or FLAC.

^Clean DeaDBeeF profile of the current -dev version

I just came back to the DeadBeeF stable. 
No Issue on the stable is found, Edits of the tags works Ok on every fields including genre.

**Comment by Alexey-Yakovenko** [comment]
deadbeef doesn't support writing tags to WAV files.

MP3, MP4/M4A and FLAC are working fine.

I just verified on both mac and linux 64 bit, as well as linux 32 bit (ubuntu 14.04), and the tags have been written fine.

**Comment by 64542426** [comment]
Ok Ignore WAV checking... I shouldn't tested with WAV. Wrong of me.

Other...
Got it Working for every value., After Editing a value i shouldn't go directy to the Apply button, i must left click somewhere in the field then to click button Apply to accept the changes.

In the previous version it was taken directly from edits to apply button. 
However, for me it is a solved, thank you for closing and forgive me.

Nili

**Comment by Alexey-Yakovenko** [comment]
cool. yeah, GTK is quirky with inline treeview editing, and something had to be changed to make it work the same across GTK2 and GTK3.
