### ISSUE TITLE
Deadbeef erases tags when they contain a utf8 only character

### ISSUE THREAD

**Issue by KonomiKitten** [DeaDBeeF-Player/deadbeef#1991]
### Steps to reproduce the problem
1. Get any MP3 that has a tag with an emoji like character (💣) in my case.
2. Change a tag on the MP3
3. Reload the metadata and watch any tag with an emoji character be erased

You can work around the problem by changing Settings to write ID3v2.4 tags, but it's not the default and isn't even recommended according to the drop down menu.

### What's going on? Describe the problem in as much detail as possible.
Deadbeef defaults to ID3v2.3 so it can't save special characters like emoji, I believe it should default to ID3v2.4 which does not have such problems.

### Information about the software:

Deadbeef version: 0.7.2
OS: Debian GNU/Linux 9.4 (stretch)

**Comment by Alexey-Yakovenko** [comment]
According to ID3v2.3 specification, unicode text is encoded as UCS-2, which doesn't support emojis.
And the whole point of writing to ID3v2.3 is compatibility with (older) hardware players, which don't support anything else, and they don't support displaying of emojis anyway.

If you want to use a less compatible tag format, and have emojis in the tags -- feel free to use APEv2 or ID3v2.4 tags.
