### ISSUE TITLE
Shellexec command path contains two single quotes ''

### ISSUE THREAD

**Issue by 0rion8** [DeaDBeeF-Player/deadbeef#1996]
Deadbeef version: 0.7.2
OS: Ubuntu 17.04

I can't open directory with shellexec command: xdg-open %D with 2 special chars (single quote working). 2 Single quotes like '' e.g. /Brainfever (Ger) 7'' ()/ directory. Quoting "%D", ""%D"" not work. Command sed for escaping char is also not working.

**Comment by JakeSFR** [comment]
I can confirm.
Didn't really dive into those calculations in shellexec.c, but looks like it's just an off-by-one, which skips a consecutive ' character, what prevents it from escaping.

This works for me:
```
diff -ur deadbeef-master_old/plugins/shellexec/shellexec.c deadbeef-master_new/plugins/shellexec/shellexec.c
--- deadbeef-master_old/plugins/shellexec/shellexec.c	2019-12-26 17:13:39.000000000 +0100
+++ deadbeef-master_new/plugins/shellexec/shellexec.c	2019-12-27 20:52:02.531523000 +0100
@@ -99,7 +99,7 @@
             memcpy (&cmd[i], "'\"'\"'", 5);
             l += 3;
             remaining -= 3;
-            i += 5;
+            i += 4;
         }
         else if (remaining < 3) {
             fprintf (stderr, "shellexec: command is too long.\n");
```

**Comment by Alexey-Yakovenko** [comment]
Thanks, that's indeed a valid fix. Although I went further, cleaned up the code a bit, added tests and fixed more issues.
