### ISSUE TITLE
Raspberry Pi: 44.1 kHz files are played as 48 kHz

### ISSUE THREAD

**Issue by eshchenko** [DeaDBeeF-Player/deadbeef#1998]
Dear Alexey
I had found a strange behavior with the Raspberry Pi and development version of the player.
Dmitry
  
### Steps to reproduce the problem
Compile development version (including 24 bit fixes) on Raspberry Pi2.
Start to play a 44.1 kHz file (does not matter 16bit or 24bit, flac or WV) 
### What's going on? Describe the problem in as much detail as possible.
File is played as 48 kHz. 
For example the duration of a 60 seconds track is 65 seconds 
or the playback is 48/44.1 times slower than the original.

Changing the re-sampling parameters in deadbeef preferences (e.g. override sample rate) have no effect.

Stable version e.g. 0.7.2 plays the 16bit  44.1 kHz files correctly.
Development version from ~ November 2017 also plays 44.1 kHz files correctly. 

The fresh development version compiled on Intel PC plays 44.1 kHz correctly. 

### Information about the software:

Deadbeef version:
Development 
OS:
Paspberri Pi 2B
Raspbian GNU/Linux 8 (jessie)

**Comment by eshchenko** [comment]
Today I found the solution:
One has to edit ~/.config/deadbeef/dspconfig file manually and change the SRC section from the original (default???) 48 kHz to 44.1 kHz like:

SRC 1 {
        48000.000000
        2
        0
}
to 
SRC 1 {
        44100.000000
        2
        0
}
It is interesting that the third parameter can also be "1" (whatever it means) or
SRC 1 {
        44100.000000
        2
        1
}
so the crucial is the change 480 -> 441 

Dmitry

At Intel the default value in this SRC section is 48000.000000 but both 44.1 and 48 are OK.

**Comment by Alexey-Yakovenko** [comment]
hmm.. so what you're saying is that you can't set this value to 44100 using the GUI?
because that is supposed to happen when you edit the resampler settings..

and yeah, 48000 is the default, as it's the most common hardware sample rate today.

**Comment by Alexey-Yakovenko** [comment]
I just tried that, and I was able to change the resampler rate to 44100 using the UI.
Of course, default settings were still supposed to work correctly, and pick the correct sample rate from the ALSA or PulseAudio -- so the bug is still there.
But the UI vs text file editing aspect sounds weird.

**Comment by Alexey-Yakovenko** [comment]
I can't reproduce this issue.

The 44,100KHz files play at correct speed.
Resampler configuration also seems to work as expected.
I would need to know more to find out why it doesn't work for you, but I suspect that you're either missing the resampler plugin, or messed up your configuration.

Try deleting ~/.config/deadbeef completely, and see if this helps.
Also please remember to post the entire console output next time.

**Comment by eshchenko** [comment]
Sorry for my misleading information (also from my second comment it was
clear that the problem is the wrong resampler configuration)!

The trick to delete the ~/.config/deadbeef helps - default configuration
includes "Autodetect samplerate from output device" which is the trick in
my case.
Thanks for this good idea!

By the way, I am not sure that the default settings in the ALSA plugin:
"Use ALSA resampling" is a good default value in general,
but in my case, as my external USB card can play all the reasonable
sampling rates, this setting is not relevant.

The reason I was editing the resampler configuration in editor was trivial
- as a newcomer I had missed the resampler GUI.
In the new git version (in comparison with 0.7.2) the new "override sample
rate" menu appeared and I had wrong impression
that this new menu is responsible for resampling.
Also there is an opportunity to use ALSA resampling in the settings of the
ALSA plugun.
That is why I was focused on deactivating these two settings but forgot to
check the DSP menu.

Thanks, the issue was closed correctly.

So the resamping is adjustable (or at least mentioned) in 3 menus...
(also still confused - what is this "override sample rate" in the main
sound menu... I played with it but there was no effect - probably the SRC
took over if the "autodetect..." option is not checked)

As a bottom line -
even 0.7.2 works correctly with 24-bit and any supported by the sound card
sample rates
if one removes playback volume from the main GUI, SuperEQ and SRC resampler
from the DSP.

____

Why I still have to use 0.7.2 is another story...
The problem is with the *.cue files and simple *.flac (no meta data).
I am not sure about making new issue but this also affect the PC builds
(not only Raspberry Pi), that is why I was surprised I did not find it in
open issues, or am I mistaken?

At Raspberry: if I drug a directory (using the file browser plugin)
containing *.cue and *.flac files into the main play-list -
the *.cue file must refer to *.wav file (not to *.flac)!
Everything is good in 0.7.2 but for development version I must edit *.cue
file (or make copy of the original *.cue like

FILE "*cdimage.flac*" WAVE -> FILE "*cdimage.wav*" WAVE

also *this *.wav file is not present on disk*.
And there are no error messages!!!

Otherwise I have album as one track.

*At Intel PC* there is another problem:  if I drug the directory (using the
file browser plugin) containing *.cue and *.flac files into the main
play-list
(the *.cue refers to *.flac)

*two albums are open: one with the track list as expected + additional
*.flac file (as a separate album).*
So at Intel the deadbeef searches the track information inside the *.flac
even if this information was successfully taken from *.cue

At Intel, if I try to modify *.cue according to flac->wav logic - the
program complains -
*Invalid FILE entry cdimage.wav in cuesheet cdimage_wav.cue, and could not
guess any suitable file name*.

This is natural (but different from Raspberry).


*0.7.2 and development from ~ November 2017 work with standard *.cue on
both platforms as expected: one *.cue produces one track-list*

Maybe this "problem" is configuration related, but deleting
~/.config/deadbeef does not help.

Best, Dmitry

**Comment by Alexey-Yakovenko** [comment]
> So the resamping is adjustable (or at least mentioned) in 3 menus...

The sampling rate settings in the main sound settings tab is not related to resampling.
It's for specifying what the output device sampling rate should be set to.

The DSP plugin settings is for doing high quality resampling in deadbeef itself.

It takes over if the output device can't resample to the desired sampling rate.

And that takes us to the pulseaudio or ALSA (or any output) resampling.
This is the resampling performed by the system.
It is enabled / used by default, to avoid causing problems when resampler DSP plugin is not installed.

> (also still confused - what is this "override sample rate" in the main
sound menu... I played with it but there was no effect - probably the SRC
took over if the "autodetect..." option is not checked)

It allows to set output sampling rate directly, instead of letting the player choose it automatically from the input file.

**Comment by Alexey-Yakovenko** [comment]
> As a bottom line -
> even 0.7.2 works correctly with 24-bit and any supported by the sound card
> sample rates
> if one removes playback volume from the main GUI, SuperEQ and SRC resampler
> from the DSP.

Do you imply that the build from master doesn't? I didn't have any problems with it.
I tested it thoroughly and it worked fine.

**Comment by Alexey-Yakovenko** [comment]
Regarding your cuesheet post.. It seems you deleted it, but if you have problems with this -- please post it as a new issue.

**Comment by eshchenko** [comment]
>As a bottom line -
>even 0.7.2 works correctly with 24-bit and any supported by the sound card
>sample rates
>if one removes playback volume from the main GUI, SuperEQ and SRC resampler
>from the DSP.

>Do you imply that the build from master doesn't? I didn't have any
problems with it.
>I tested it thoroughly and it worked fine.
I can confirm - the build from master git version is working fine!

>> Regarding your cuesheet post.. It seems you deleted it, but if you have
problems with this -- please post it as a new issue.

I have to use 0.7.2 with some tricks because of the *.cue problem I will
describe soon in a new issue.
(I did not expect that this *.cue related part of my previous comment was
deleted)

And thanks for all your resampling related explanations!

Dmitry.

**Comment by Alexey-Yakovenko** [comment]
> (I did not expect that this *.cue related part of my previous comment was
deleted)

Oh btw, it's not deleted, still there, just got collapsed under "..." button in the comment.
