### ISSUE TITLE
gtk3ui: No window decoration under Plasma Wayland session

### ISSUE THREAD

**Issue by alive4ever** [DeaDBeeF-Player/deadbeef#2002]
### Steps to reproduce the problem
Log into a plasma-wayland session and launch deadbeef with gtk3 ui

### What's going on? Describe the problem in as much detail as possible.
No window decoration.

### Information about the software:
deadbeef: 0.7.2
gtk3: 3.22.29
plasma: framework 5.44, applications: 17.12.3, Qt 5.10.1

Deadbeef version: 0.7.2
OS: Arch Linux

```
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.22.26
connecting button tray signals
```

**Comment by Alexey-Yakovenko** [comment]
are you sure that plasma-wayland is capable of displaying window decorations on GTK applications? does it work with any other GTK app?

**Comment by Alexey-Yakovenko** [comment]
also, have you tried the latest build from master? it might have some new code for GtkApplication, which might affect this behavior in some random way.

**Comment by Alexey-Yakovenko** [comment]
and last but not least.. do you know if there's an easy way to get a linux distro with wayland and plasma-wayland running in a VM? I'm afraid I don't have any spare hardware to run this on to even try this out.

**Comment by alive4ever** [comment]
>are you sure that plasma-wayland is capable of displaying window decorations on GTK applications? does it work with any other GTK app?

Not sure.

Here is window decoration status on gtk3 apps using `GDK_BACKEND` environment variable set to wayland and x11

| App   | wayland   | x11   |
|---|---|---|
| deabeef   | no  | yes  |
| firefox   | -  | yes   |
| qemu-system-x86_64  | no  | yes  |
| gnome-terminal | no | no |
| nautilus | yes | yes |

Note: firefox doesn't run on native wayland.

> also, have you tried the latest build from master?

I've built latest git source and still no window decoration under native wayland.

Window decoration is available with `GDK_BACKEND=x11` [environment variable](https://developer.gnome.org/gtk3/stable/gtk-wayland.html), which results in running deadbeef via Xwayland.

Probably unrelated, but it seems that nautilus implements [CSD](https://wiki.gnome.org/Initiatives/CSD) for window decoration.

**Comment by alive4ever** [comment]
> and last but not least.. do you know if there's an easy way to get a linux distro with wayland and plasma-wayland running in a VM?

There is [KDE neon](https://neon.kde.org/), which contains bleeding edge stuff.

**Comment by Alexey-Yakovenko** [comment]
Well gnome terminal IS a native GTK3 application, so if it doesn't work either -- that seems like the same issue as you're experiencing with deadbeef. I suppose you just need to wait more, until this stuff is resolved in GTK and wayland.

**Comment by Alexey-Yakovenko** [comment]
@alive4ever one more thing that you could try:
There's a plugin for deadbeef, that essentially adds CSD to deadbeef.
http://github.com/saivert/ddb_misc_headerbar_GTK3

maybe it will help.

**Comment by Alexey-Yakovenko** [comment]
(it requires deadbeef build from master)

**Comment by Alexey-Yakovenko** [comment]
Actually, their github page says 0.7 should be fine too. I never tried.
