### ISSUE TITLE
Workaround for non-matching .cue file name

### ISSUE THREAD

**Issue by grinderX19** [DeaDBeeF-Player/deadbeef#2004]
### Steps to reproduce the problem
In case .cue file has a name different from the main file (f.e. "mainFile.flac" and "mainFile FLAC.cue"), deadbeef won't pick up the .cue.

### What's going on? Describe the problem in as much detail as possible.
Drag'n'dropping a dir with described files will display and play media file as one track.

### Proposed solution
Would be nice to have a workaround for this like the following:
IF (file names don't match AND there's only one .cue file in the dir)
  THEN use the .cue file in the dir anyway

### Information about the software:

Deadbeef version: DeaDBeeF-0.7.2
OS: Debian GNU/Linux 9.4 (stretch)

**Comment by Alexey-Yakovenko** [comment]
This problem has been solved on master. Please try it, and let me know if it still doesn't work.

**Comment by grinderX19** [comment]
Looks good in 1.8.0.
