### ISSUE TITLE
Play, Pause, Change Volume, Change Playback Order from Command Line

### ISSUE THREAD

**Issue by davestechshop** [DeaDBeeF-Player/deadbeef#2005]
Hello. Does DeaDBeeF have commands that allow controlling play, pause, volume level and playback order from the Linux command line? If yes, where is the documentation? Thank you.

Deadbeef version: 0.7.2
OS: Arch Linux KDE

**Comment by Bfgeshka** [comment]
It does, check `deadbeef --help`.

**Comment by davestechshop** [comment]
Thanks. What about changing volume? I don't see that option listed. Is there a custom way to change volume from the command line?

deadbeef 0.7.2
Usage: deadbeef [options] [--] [file(s)]
Options:
   --help  or  -h     Print help (this message) and exit
   --quit             Quit player
   --version          Print version info and exit
   --play             Start playback
   --stop             Stop playback
   --pause            Pause playback
   --toggle-pause     Toggle pause
   --play-pause       Start playback if stopped, toggle pause otherwise
   --next             Next song in playlist
   --prev             Previous song in playlist
   --random           Random song in playlist
   --queue            Append file(s) to existing playlist
   --gui PLUGIN       Tells which GUI plugin to use, default is "GTK2"
   --nowplaying FMT   Print formatted track name to stdout
                      FMT %-syntax: [a]rtist, [t]itle, al[b]um,
                      [l]ength, track[n]umber, [y]ear, [c]omment,
                      copy[r]ight, [e]lapsed
                      example: --nowplaying "%a - %t" should print "artist - title"
                      for more info, see http://github.com/Alexey-Yakovenko/deadbeef/wiki/Title-formatting
                      NOTE: --nowplaying is deprecated.
   --nowplaying-tf FMT  Print formatted track name to stdout, using the new title formatting
                      FMT syntax: http://github.com/Alexey-Yakovenko/deadbeef/wiki/Title-formatting-2.0
                      example: --nowplaying-tf "%artist% - %title%" should print "artist - title"

**Comment by Bfgeshka** [comment]
AFAIK, there is no way to change sound volume for deadbeef. Yet, you can manipulate overall system sound via cli.

**Comment by Alexey-Yakovenko** [comment]
everything answered it seems? closing

**Comment by kuba160** [comment]
option to change volume via command line came with commit ef8396e5f6fa9a53ed4c59e7a13737f6d63bbcc3, use master branch or wait for deadbeef 1.8 release.
