### ISSUE TITLE
Open Directory

### ISSUE THREAD

**Issue by davestechshop** [DeaDBeeF-Player/deadbeef#2006]
I wish to learn how custom shell commands work in DeaDBeeF. I started with a simple example - open a directory of music tracks into a new tab in DeaDBeeF. However, cannot seem to get it to work and I still do not understand how it is supposed to work.

### Steps to reproduce the problem

First try:
In Arch Linux KDE, use the DeaDBeeF Configure Custom Shell Command dialog and enter this command:
xdg-open %D

Then execute the command.  The result is a popup dialog with the error "Malformed URL". The dialog has the title KIO Client. 

Second try:
xdg-open /home/me/Music/Shakira

This causes Dolphin to open outside of DeaDBeeF. I assume that is not how it should work because that's pretty useless.

As a wild shot in the dark, I tried xdg-open $(kdialog --getexistingdirectory) and I did not get any obvious error but nothing is opened at all after I select a directory.

Deadbeef version: 0.7.2
OS: Arch Linux KDE

**Comment by Alexey-Yakovenko** [comment]
Shell commands are specifically for running external programs. They can't open anything within deadbeef.
