### ISSUE TITLE
[macOS] no longer able to reorder items in the playlist

### ISSUE THREAD

**Issue by chyiz** [DeaDBeeF-Player/deadbeef#2011]
### Steps to reproduce the problem
Prepare an playlist with multiple items. Try to drag one item to a new position in the playlist. 

### What's going on? Describe the problem in as much detail as possible.
After some update in April or March, I'm no longer able to reorder playlist by drag and drop. 

### Information about the software:
Deadbeef version: 1.8.0 alpha 4 / master
OS: macOS 11.13.4

**Comment by Alexey-Yakovenko** [comment]
The issue was a bit tough to find.. It turned out to not be a regression in deadbeef code as such, more like an OS or SDK update has deprecated the older / insecure data encoder, which was used pre-10.8 for drag-drop data, and it remained unnoticed for quite some time.

**Comment by Alexey-Yakovenko** [comment]
On the positive side, fixing this helped to notice and fix a few minor bugs / memory leaks in the drag-drop code.
