### ISSUE TITLE
alac plugin: 24bit/96khz files detected as 16/48 and don't play past 50%

### ISSUE THREAD

**Issue by huglovefan** [DeaDBeeF-Player/deadbeef#2015]
### Steps to reproduce the problem

1. add a 24/96 alac/m4a file to a playlist (preferably one that doesn't exist in a playlist already so the details don't come from a cache)
2. play it or view its properties

### What's going on? Describe the problem in as much detail as possible.

- the alac plugin from commit bb06346cb55e7445e3a9cb0c58a0380960bdfe5f (Oct 13, 2016) works and plays as expected [(screenshot)](https://files.catbox.moe/dmkeu1.png)
- versions from a32a95aaabc5eeeab0f8359a2b1422db4fe9717a (Nov 3, 2016) and later detect the file as 16-bit 48kHz [(screenshot)](https://files.catbox.moe/ang9if.png) and at least the latest version skips to the next track after playing half of the current one (the pulseaudio output plugin also logs `pulse: failed to write buffer` but alsa does it silently)

here's a [10-second sample file](https://files.catbox.moe/urgekt.m4a) sliced using ffmpeg, i only have a few alac files so i don't know about other sample rates and bit depths

### Information about the software:

Deadbeef version: devel/git, the bug isn't present in the latest stable version 0.7.2
OS: arch gnu+linux

as a workaround i've been compiling deadbeef with the old alac plugin (it works, just have to re-add the files to playlists to update the details)

**Comment by Alexey-Yakovenko** [comment]
Thanks for spotting this! Was quite a significant regression. I added a dirty fix to that, but it would suffice for now until the new ALAC plugin gets done (work in progress atm)
