### ISSUE TITLE
Current libraries linking situation?

### ISSUE THREAD

**Issue by Zlogene** [DeaDBeeF-Player/deadbeef#2017]
Hi, as the gentoo linux developer I would want to add deadbeef to gentoo portage. I have ready-to use ebuilds but I remember there was a problem like deadbeef uses thrid-pathy patched libraries to compile, so it would not work on gentoo systems "as-is". Althought, I have written the 7.0 version ebuild and it seems working fine (except some static links against existing libraries, but these libraries will not be installed anyway, without static option enabled as I can see, so should not be a problem).

Are there still some more expected problems?

**Comment by Alexey-Yakovenko** [comment]
There was never any technical problem with building, installing or running deadbeef on Gentoo (as well as most other Linux distributions).

The decision to allow applications to use their own libraries is purely political.
The basic rule of the linux distros is "bundled libs are forbidden".
However, it's generally not possible to build and run deadbeef without the use of its bundled libraries, without significant loss of functionality.
