### ISSUE TITLE
 Allow undo clear playlist

### ISSUE THREAD

**Issue by xgdgsc** [DeaDBeeF-Player/deadbeef#2019]
### Steps to reproduce the problem
People sometimes click the menu items and click the edit->clear unintentionally (as clear is on top of the menu). It could take a lot of effort to construct one playlist, but just one false click using touchpad could clear that effort. An option to undo clear playlist would help in such a rare but critical use case.
 
### Information about the software:

Deadbeef version: 0.7.2
 
OS:manjaro

**Comment by Alexey-Yakovenko** [comment]
Seems to be a subset of #490
Deadbeef doesn't have an undo system unfortunately.

**Comment by mrnom** [comment]
Maybe it will be easier to implement confirmation messages e.g. for _Edit -> Clear_ and _Remove Playlist_ actions to make them less unintentional as a result, this may solve part of the problem.

**Comment by mrnom** [comment]
Confirmation dialogs may partially solve the problem.

**Comment by Alexey-Yakovenko** [comment]
duplicate of #490
