### ISSUE TITLE
NSF(e) subtracks can't be read from/written to playlists

### ISSUE THREAD

**Issue by GeneralFailer** [DeaDBeeF-Player/deadbeef#2020]
Kind of related to  #1983, I guess.

Deadbeef version: 0.7.2

**Comment by Alexey-Yakovenko** [comment]
I can't understand the issue from the information you provided.

**Comment by GeneralFailer** [comment]
What I'm trying to say is that when saving playlists to a file, DeaDBeeF skips NSF/NSFe track entries. It also can't add them from playlist files.

**Comment by Alexey-Yakovenko** [comment]
well then it is indeed a duplicate of #1983
