### ISSUE TITLE
Deadbeef is freezing the whole system - asking for help in the diagnosis

### ISSUE THREAD

**Issue by Krzysztofci** [DeaDBeeF-Player/deadbeef#2021]
When the music is played, when the deadbeef is left in the foreground after a few dozen minutes deadbeef hangs the whole system. 

The graphic environment is not working, or even switching to the terminal. The player can not be controlled. The computer can not be controlled in any way. However, the music is played correctly.

Perhaps the problem is one of the plugins, unfortunately I can not get to it, checking each one after another is another several dozen minutes. However, there is no hang-up problem if deadbeef is minimized to the bar.

Deadbeef version:0.7.2
OS: The Mint 19 system, was also the same on previous versions.

I place it below config:
`adplug.surround 0
adplug.use_ken 1
alsa.buffer 8192
alsa.freeonstop 1
alsa.period 1024
alsa.resample 1
alsa_soundcard sysdefault:CARD=Xmod
ape.strip_apev2 0
ape.strip_id3v2 0
ape.write_apev2 1
ape.write_id3v2 1
artwork.cache.period 24
artwork.cache_reset_time 1517093639
artwork.enable_albumartorg 1
artwork.enable_embedded 1
artwork.enable_lastfm 1
artwork.enable_localfolder 0
artwork.enable_musicbrainz 1
artwork.enable_wos 1
artwork.filemask *cover*.jpg;*front*.jpg;*folder*.jpg;*cover*.png;*front*.png;*folder*.png
artwork.missing_artwork 1
artwork.nocover_path 
artwork.scale_towards_longer 1
artwork.scaled.cache_reset_time 1517093639
cdda.drive_speed 2
cdda.enable_nrg 0
cdda.freedb.enable 1
cdda.freedb.host freedb.org
cdda.freedb.port 8880
cdda.prefer_cdtext 1
cdda.protocol 1
chip.voices 255
cli_add_playlist_name Muzyka
cli_add_to_specific_playlist 0
close_send_to_tray 1
deadbeef_version 0.7.2
filebrowser.autofilter 1
filebrowser.bgcolor #444444
filebrowser.bgcolor_selected #f0544c
filebrowser.coverart_files cover.png;cover.jpg;folder.png;folder.jpg;front.png;front.jpg
filebrowser.coverart_scale 1
filebrowser.coverart_size 24
filebrowser.defaultpath /media/Dane/Muzyka
filebrowser.enabled 1
filebrowser.expanded_rows 
filebrowser.extra_bookmarks $HOME/.config/deadbeef/bookmarks
filebrowser.fgcolor #eeeeec
filebrowser.fgcolor_selected #000000
filebrowser.filter 
filebrowser.filter_enabled 0
filebrowser.font_size 0
filebrowser.fullsearch_wait 5
filebrowser.hidden 0
filebrowser.hide_navigation 1
filebrowser.hide_search 1
filebrowser.hide_toolbar 1
filebrowser.icon_size 24
filebrowser.save_treeview 0
filebrowser.search_delay 1000
filebrowser.show_coverart 1
filebrowser.showbookmarks 0
filebrowser.showhidden 0
filebrowser.showicons 1
filebrowser.sidebar_width 220
filebrowser.sort_treeview 1
filebrowser.treelines 0
filechooser.lastdir file:///media/HDD-Dane/Muzyka
filechooser.playlist.lastdir file:///home/krzysztof
global_preamp 0.0000000
gtkui.action_separators 0
gtkui.autoresize_columns 1
gtkui.color.bar_foreground 61680 21588 19532
gtkui.color.listview_odd_row 17475 17475 17475
gtkui.color.tabstrip_base 17476 17476 17476
gtkui.color.tabstrip_dark 12233 12233 12233
gtkui.columns.playlist [{"title":"♫","id":"1","format":"%playstatus%","size":"29","align":"0","color_override":"0","color":"#ff000000"},{"title":"N°.","id":"-1","format":"%tracknumber%","size":"33","align":"1","color_override":"0","color":"#ff000000"},{"title":"Wykonawca","id":"-1","format":"$if(%artist%,%artist%,Unknown Artist)","size":"116","align":"0","color_override":"0","color":"#ffdddddd"},{"title":"Album","id":"-1","format":"%album%","size":"221","align":"0","color_override":"0","color":"#ffdddddd"},{"title":"Tytuł","id":"-1","format":"%title%","size":"293","align":"0","color_override":"0","color":"#ff000000"},{"title":"Długość","id":"-1","format":"%length%","size":"67","align":"0","color_override":"0","color":"#ff000000"}]
gtkui.columns.search [{"title":"Wykonawca / Album","id":"-1","format":"%artist% - %album%","size":"153","align":"0","color_override":"0","color":"#ff000000"},{"title":"Numer ścieżki","id":"-1","format":"%tracknumber%","size":"50","align":"1","color_override":"0","color":"#ff000000"},{"title":"Tytuł","id":"-1","format":"%title%","size":"150","align":"0","color_override":"0","color":"#ff000000"},{"title":"Długość","id":"-1","format":"%length%","size":"50","align":"0","color_override":"0","color":"#ff000000"}]
gtkui.custom_tray_icon deadbeef_tray_icon
gtkui.delete_files_ask 1
gtkui.disable_seekbar_overlay 0
gtkui.embolden_current_track 1
gtkui.embolden_selected_tracks 1
gtkui.eq.visible 0
gtkui.hide_remove_from_disk 1
gtkui.hide_tray_icon 0
gtkui.italic_current_track 1
gtkui.layout.0.6.2 vbox expand="0 1 0" fill="0 1 0" homogeneous=0 {hbox expand="0 1 0" fill="0 1 0" homogeneous=0 {playtb {} waveform_seekbar {} volumebar {} } hsplitter pos=285 locked=0 {vsplitter pos=248 locked=0 {coverart {} tabs active=1 num_tabs=2 tab000="Pliki" tab001="Listy" {filebrowser {} pltbrowser {} } } hsplitter pos=0 locked=0 {placeholder {} tabs active=0 num_tabs=3 tab000="Lista odtwarzania" tab001="musical_spectrum" tab002="spectrogram" {hsplitter pos=770 locked=0 {vbox expand="1" fill="1" homogeneous=0 {vbox expand="1 0" fill="1 1" homogeneous=0 {playlist hideheaders=0 width=792 {} hbox expand="1 0" fill="1 1" homogeneous=0 {hsplitter pos=105 locked=1 {button color="#000000" textcolor="#000000" label="Odtwórz kolejno" action="order_linear" use_color=0 use_textcolor=0 {} hsplitter pos=86 locked=1 {button color="#000000" textcolor="#000000" label="Tasuj ścieżki" action="order_shuffle" use_color=0 use_textcolor=0 {} hsplitter pos=90 locked=1 {button color="#000000" textcolor="#000000" label="Tasuj albumy" action="order_shuffle_albums" use_color=0 use_textcolor=0 {} hsplitter pos=104 locked=1 {button color="#000000" textcolor="#000000" label="Odtwórz losowo" action="order_random" use_color=0 use_textcolor=0 {} hsplitter pos=103 locked=1 {button color="#000000" textcolor="#000000" label="Zapętl wszystko" action="loop_all" use_color=0 use_textcolor=0 {} hsplitter pos=93 locked=1 {button color="#000000" textcolor="#000000" label="Zapętl ścieżke" action="loop_track" use_color=0 use_textcolor=0 {} hsplitter pos=115 locked=1 {button color="#000000" textcolor="#000000" label="Przejdz do utworu" action="jump_to_current_track" use_color=0 use_textcolor=0 {} placeholder {} } } } } } } } button color="#000000" textcolor="#000000" label="Wycisz" action="toggle_mute" use_color=0 use_textcolor=0 {} } } } vsplitter pos=608 locked=0 {infobar {} scope {} } } musical_spectrum {} spectrogram {} } } } hbox expand="0 1 0" fill="0 1 1" homogeneous=0 {volumebar {} button color="#000000" textcolor="#000000" label="EQ" action="toggle_eq" use_color=0 use_textcolor=0 {} playtb {} } } 
gtkui.mmb_delete_playlist 1
gtkui.name_playlist_from_folder 1
gtkui.override_bar_colors 1
gtkui.override_listview_colors 0
gtkui.override_tabstrip_colors 0
gtkui.playlist.group_by_tf 
gtkui.pltbrowser.highlight_curr_plt 1
gtkui.pltbrowser.mmb_delete_playlist 0
gtkui.pltbrowser.show_duration_column 0
gtkui.pltbrowser.show_items_column 0
gtkui.pltbrowser.show_playing_column 1
gtkui.refresh_rate 1
gtkui.statusbar.visible 1
gtkui.sync 1
gtkui.tabscroll 0
gtkui.titlebar_playing_tf %artist% - %title% - DeaDBeeF-%_deadbeef_version%
gtkui.titlebar_stopped_tf DeaDBeeF-%_deadbeef_version%
gtkui.tray_volume_sensitivity 1
gtkui.unicode_playstate 0
gui_plugin GTK3
hotkey.key01 "Ctrl f" 0 0 find
hotkey.key02 "Ctrl o" 0 0 open_files
hotkey.key03 "Ctrl q" 0 0 quit
hotkey.key04 "Ctrl n" 0 0 new_playlist
hotkey.key05 "Ctrl a" 0 0 select_all
hotkey.key06 "Escape" 0 0 deselect_all
hotkey.key07 "Ctrl m" 0 0 toggle_stop_after_current
hotkey.key08 "Ctrl j" 0 0 jump_to_current_track
hotkey.key09 "F1" 0 0 help
hotkey.key10 "Delete" 1 0 remove_from_playlist
hotkey.key11 "Ctrl w" 0 0 remove_current_playlist
hotkey.key12 "Return" 0 0 play
hotkey.key13 "Ctrl p" 0 0 toggle_pause
hotkey.key14 "Alt 1" 0 0 playlist1
hotkey.key15 "Alt 2" 0 0 playlist2
hotkey.key16 "Alt 3" 0 0 playlist3
hotkey.key17 "Alt 4" 0 0 playlist4
hotkey.key18 "Alt 5" 0 0 playlist5
hotkey.key19 "Alt 6" 0 0 playlist6
hotkey.key20 "Alt 7" 0 0 playlist7
hotkey.key21 "Alt 8" 0 0 playlist8
hotkey.key22 "Alt 9" 0 0 playlist9
hotkey.key23 "Alt 0" 0 0 playlist10
hotkey.key24 "z" 0 0 prev
hotkey.key25 "x" 0 0 play
hotkey.key26 "c" 0 0 toggle_pause
hotkey.key27 "v" 0 0 stop
hotkey.key28 "b" 0 0 next
hotkey.key29 "n" 0 0 playback_random
hotkey.key30 "Ctrl k" 0 0 toggle_stop_after_album
hotkeys_created 1
ignore_archives 1
infobar.bio.cache.period 1.000000
infobar.bio.enabled 1
infobar.bio.locale pl
infobar.lyrics.alignment 0
infobar.lyrics.cache.period 0.000000
infobar.lyrics.enabled 1
infobar.lyrics.lyricsmania 1
infobar.lyrics.lyricstime 1
infobar.lyrics.lyricswikia 1
infobar.lyrics.megalyrics 1
infobar.lyrics.script 1
infobar.lyrics.script.path /home/krzysztof/.local/bin/deadbeef-infobar
infobar.similar.enabled 1
infobar.similar.max.artists 10.000000
junk.enable_cp1251_detection 0
lastfm.disable_np 0
lastfm.enable 0
lastfm.login 
lastfm.mbid 0
lastfm.password 
lastfm.prefer_album_artist 1
lastfm.scrobbler_url http://post.audioscrobbler.com
lastfm.submit_tiny_tracks 0
mainwin.geometry.h 774
mainwin.geometry.maximized 1
mainwin.geometry.w 1058
mainwin.geometry.x 162
mainwin.geometry.y 98
mp3.id3v1_encoding iso8859-1
mp3.id3v2_version 3
mp3.strip_id3v2 0
mp3.write_apev2 1
mp3.write_id3v1 1
mp3.write_id3v2 1
mpris_v1.enable 1
mpris_v2.enable 0
musical_spectrum.alignment 0
musical_spectrum.bar_delay 0
musical_spectrum.bar_falloff -1
musical_spectrum.bar_w 0
musical_spectrum.color.background 8738 8738 8738
musical_spectrum.color.gradient_00 11822 13364 13878
musical_spectrum.color.gradient_01 21845 22359 21331
musical_spectrum.color.gradient_02 34952 35466 34181
musical_spectrum.color.gradient_03 47802 48573 46774
musical_spectrum.color.gradient_04 54227 55255 53199
musical_spectrum.color.gradient_05 61166 61166 60652
musical_spectrum.color.gradient_06 62451 62451 62451
musical_spectrum.color.gradient_07 11822 13364 13878
musical_spectrum.color.gradient_08 47802 48573 46774
musical_spectrum.color.gradient_09 0 0 0
musical_spectrum.color.gradient_10 0 0 0
musical_spectrum.color.gradient_11 0 0 0
musical_spectrum.color.gradient_12 0 0 0
musical_spectrum.color.gradient_13 0 0 0
musical_spectrum.color.gradient_14 0 0 0
musical_spectrum.color.gradient_15 0 0 0
musical_spectrum.color.hgrid 26214 26214 26214
musical_spectrum.color.octave_grid 26214 26214 26214
musical_spectrum.color.vgrid 0 0 0
musical_spectrum.db_range 70
musical_spectrum.display_octaves_on_hover 0
musical_spectrum.draw_style 0
musical_spectrum.enable_bar_mode 1
musical_spectrum.enable_hgrid 1
musical_spectrum.enable_octave_grid 1
musical_spectrum.enable_vgrid 0
musical_spectrum.fft_size 8192
musical_spectrum.fill_spectrum 0
musical_spectrum.gaps 1
musical_spectrum.gradient_orientation 1
musical_spectrum.num_bars 132
musical_spectrum.num_colors 7
musical_spectrum.peak_delay 500
musical_spectrum.peak_falloff 90
musical_spectrum.refresh_interval 25
musical_spectrum.window 1
network.http_user_agent deadbeef
network.proxy 0
network.proxy.port 8080
network.proxy.type HTTP
output_plugin PulseAudio output plugin
playback.loop 0
playback.order 0
playback.volume -13.00000
playlist.current 7
playlist.cursor.0 0
playlist.cursor.1 -1
playlist.cursor.10 3
playlist.cursor.11 0
playlist.cursor.12 0
playlist.cursor.13 4
playlist.cursor.14 2
playlist.cursor.15 0
playlist.cursor.16 40
playlist.cursor.17 0
playlist.cursor.18 0
playlist.cursor.19 7
playlist.cursor.2 3
playlist.cursor.20 0
playlist.cursor.21 0
playlist.cursor.22 25
playlist.cursor.23 15
playlist.cursor.24 0
playlist.cursor.25 0
playlist.cursor.26 0
playlist.cursor.27 -1
playlist.cursor.3 0
playlist.cursor.4 0
playlist.cursor.5 0
playlist.cursor.6 0
playlist.cursor.7 0
playlist.cursor.8 0
playlist.cursor.9 7
playlist.pin.groups 0
playlist.scroll.0 1320
playlist.scroll.1 39951
playlist.scroll.10 0
playlist.scroll.11 0
playlist.scroll.12 0
playlist.scroll.13 0
playlist.scroll.14 0
playlist.scroll.15 0
playlist.scroll.16 986
playlist.scroll.17 0
playlist.scroll.18 284
playlist.scroll.19 0
playlist.scroll.2 0
playlist.scroll.20 0
playlist.scroll.21 0
playlist.scroll.22 280
playlist.scroll.23 0
playlist.scroll.24 0
playlist.scroll.25 0
playlist.scroll.26 0
playlist.scroll.27 104
playlist.scroll.3 0
playlist.scroll.4 0
playlist.scroll.5 0
playlist.scroll.6 0
playlist.scroll.7 0
playlist.scroll.8 0
playlist.scroll.9 0
playlist.scroll.cursorfollowplayback 1
playlist.stop_after_album 0
playlist.stop_after_album_reset 1
playlist.stop_after_current_reset 1
playlist.tab.00000 Muzyka
playlist.tab.00001 Amy Winehouse - Back To Black
playlist.tab.00002 Apollo 440
playlist.tab.00003 ATB [Mix]
playlist.tab.00004 Broke For Free
playlist.tab.00005 Cullah
playlist.tab.00006 Daft Punk - Best275z
playlist.tab.00007 Diablo Swing Orchestra - The Butcher's Ballroom -- Jamendo - OGG Vorbis q7 - 2009.07.23 [www.jamendo.com]
playlist.tab.00008 Don Henley
playlist.tab.00009 Eric Clapton - The Breeze An Appreciation of J.J. Cale
playlist.tab.00010 Guano Apes
playlist.tab.00011 Indila - Mini World
playlist.tab.00012 Jean Michel Jarre
playlist.tab.00013 JEKK
playlist.tab.00014 Ludwik Konopko - Taruna
playlist.tab.00015 LukHash
playlist.tab.00016 Marek Niedźwiedziecki
playlist.tab.00017 Moby - Discography
playlist.tab.00018 Muzyka ściągnięta u Pawła
playlist.tab.00019 Rage Against The Machine
playlist.tab.00020 Rammstein
playlist.tab.00021 Robert Miles
playlist.tab.00022 Sabaton
playlist.tab.00023 Scooter
playlist.tab.00024 The Beatles - discography (2009 Remastered)
playlist.tab.00025 The Offspring - Happy Hour [mp3-256-2010]
playlist.tab.00026 The Prodigy
playlist.tab.00027 Kovacs
prefwin.geometry.h 553
prefwin.geometry.w 815
prefwin.geometry.x 313
prefwin.geometry.y 162
replaygain_mode 0
replaygain_preamp 0.0000000
replaygain_scale 0
resume.paused 1
resume.playlist 27
resume.position 133.52896
resume.track 21
resume_last_session 1
searchwin.geometry.h 150
searchwin.geometry.w 450
searchwin.geometry.x 445
searchwin.geometry.y 287
shellexec.0 xset s off -dpms led 3 && cinnamon-screensaver-command -e:View/Zablokuj wygaszanie ekranu:00:common,
shellexec.1 xset s on +dpms -led 3 && screen -dmS agar cinnamon-screensaver:View/Odblokuj wygaszacz ekranu:01:common,
shellexec.2 screen -dmS dbgotob dbgotobed:Playback/Wyłącz komputer:TurnOFF:common,
shellexec.3 deadbeef-ed-tekstu:Edit/Edytuj tekst bieżącego nagrania:Edytuj tekst utworu:local,single,
spectrogram.color.gradient_00 11822 13364 13878
spectrogram.color.gradient_01 11822 13364 13878
spectrogram.color.gradient_02 62451 62451 62451
spectrogram.color.gradient_03 21845 22359 21331
spectrogram.color.gradient_04 47802 48573 46774
spectrogram.color.gradient_05 13107 13107 13107
spectrogram.color.gradient_06 13107 13107 13107
spectrogram.db_range 70
spectrogram.log_scale 1
spectrogram.num_colors 6
spectrogram.refresh_interval 25
streamer.16_to_24 0
streamer.8_to_16 0
trkproperties.geometry.h 400
trkproperties.geometry.w 931
trkproperties.geometry.x 218
trkproperties.geometry.y 238
waveform.bg_alpha 65535
waveform.bg_color_b 17476
waveform.bg_color_g 17476
waveform.bg_color_r 17476
waveform.border_width 0
waveform.cache_enabled 1
waveform.cursor_width 1
waveform.display_rms 1
waveform.fg_alpha 65535
waveform.fg_color_b 60652
waveform.fg_color_g 61166
waveform.fg_color_r 61166
waveform.fg_rms_alpha 65535
waveform.fg_rms_color_b 21331
waveform.fg_rms_color_g 22359
waveform.fg_rms_color_r 21845
waveform.font_size 18
waveform.log_enabled 0
waveform.max_file_length 180
waveform.mix_to_mono 1
waveform.num_samples 2048
waveform.pb_alpha 65535
waveform.pb_color_b 19532
waveform.pb_color_g 21588
waveform.pb_color_r 61680
waveform.refresh_interval 10
waveform.render_method 1
waveform.scroll_enabled 1
waveform.shade_waveform 1
waveform.soundcloud_style 0
wv.write_apev2 1
wv.write_id3v1 1`

**Comment by Alexey-Yakovenko** [comment]
There's no proof that deadbeef is causing this. Could be anything else.
It's very unlikely for a regular UI app to block X11 and the system key combinations (like ctrl+alt+f1 for terminal access).
Sounds more like a broken graphics (or any other) driver or something like that.
I suppose that you're rebooting your machine after this happens..
I can only suggest looking into Xorg logs and see if there's anything odd.

and I guess you tried that already, but try to delete or rename `~/.config/deadbeef`, and don't change any settings to see if any of your local settings have causes that.

The only code in deadbeef that's teoretically capable of causing such behavior is global hotkeys.

**Comment by Alexey-Yakovenko** [comment]
Well it has not been reported by anyone over the whole 0.7.2 life cycle (it's been out for over 2 years now) -- so this still indicates a problem with your specific configuration. Either hardware or software.
You can always run top/htop alongside deadbeef, and monitor memory and CPU usage, at the time when you notice system slowing down.

And since the problem doesn't happen for me -- I can't see how I can help..

**Comment by Alexey-Yakovenko** [comment]
And if the problem happens only on Mint -- changing to another distro could be a viable option too.

**Comment by Krzysztofci** [comment]
The problem is specific, because if the deadbeef is not minimized and will not be in the foreground, for example, the window of the htop terminal emulator above it will remain, the system will not hang. I think that the visualization plugin may be responsible for that. I have a total of 3 pieces, 4 if you count Waveform seekbar.

It looks more like this:
https://www.youtube.com/watch?v=awy4iGMxWcI&t=47s

And now my question is, are the tabs plugged in if they are invisible cards?
Sorry for my English.
Regards
Krzysztof

**Comment by Alexey-Yakovenko** [comment]
Well you are using a ton of third party plugins, which I never even installed myself.
Maybe they are causing issues. I can't provide any help with the stuff that I didn't make.
I can only help if the problem happens with default (built-in) plugins.

**Comment by Alexey-Yakovenko** [comment]
I don't think there's any automatic control of how the plugins suspend.
It's controlled by the plugin devs themselves.

**Comment by cboxdoerfer** [comment]
Like Alexey said you should first try a clean config, without any plugins and see if the issue remains. Then you can add one plugin at a time, having an eye on the CPU and memory usage of deadbeef in the system monitor of your choice, until the issue happens. Since many of the plugins you use were developed by me, and most of them are in fact more resource demanding than any other aspect of deadbeef, the chance is high that a visualization plugin is triggering that issue. If that's the case please move the discussion to the its bug tracker.

And yes, the visualization plugins do suspend most of their resource intensive calculations (e.g. FFT, drawing) if they are in a non-visible tab.
