### ISSUE TITLE
Game-music-emu plugin's fadeout feature doesn't work

### ISSUE THREAD

**Issue by GeneralFailer** [DeaDBeeF-Player/deadbeef#2022]
The looping tracks don't fade out for me regardless of the format, even though the plugin's configuration window implies that they should. Audacious, for example, fades them out fine.

Deadbeef version: 0.7.2

**Comment by Alexey-Yakovenko** [comment]
does it happen with the 1.8beta?

**Comment by GeneralFailer** [comment]
The current trunk seems to have fixed the issue, but only for vgm format.

**Comment by Alexey-Yakovenko** [comment]
OK, I'll check the issue out, but I'm pretty sure it was reported before, and it works by design.
It depends on the track type. Fadeouts only happen for tracks with infinite length, or something like that.

**Comment by Alexey-Yakovenko** [comment]
Just tried some looping NSF files, they fade out just fine.
Which files did you use, and what are the settings of the GME plugin?

**Comment by Alexey-Yakovenko** [comment]
Timed formats are not supposed to fade out -- they have the defined intro and outro.
What is your use-case?

**Comment by GeneralFailer** [comment]
Not in the case of looping tracks in these formats. They can't have an outro. As I have already said, Audacious fades them out fine.

**Comment by Alexey-Yakovenko** [comment]
Can you provide an example which have an intro, a looping part, and no outro?

**Comment by Alexey-Yakovenko** [comment]
To my best knowledge, deadbeef's GME plugin will only fade-out those chiptunes which don't have a predefined length. I.e. the ones like NSF, which play for the number of loops specified in the settings.
The other ones which specify the length won't fade out.

**Comment by Alexey-Yakovenko** [comment]
I don't have a big collection of any other GME chiptunes.. Found a few SPC files, all of them just have their length predefined, with no looping info, so there doesn't seem to be a way to find whether they are looping or not.

Just to give you some context..

This is an NSF, it's duration is unknown, so it will play for 5 minutes (default), then fade out:

![image](https://user-images.githubusercontent.com/1895698/44053966-86c6b2e4-9f41-11e8-8364-ab6f55ff6cd0.png)

And this is an SPC..
![image](https://user-images.githubusercontent.com/1895698/44053973-9052aa3e-9f41-11e8-8813-7cb45a73769a.png)

It says duration is 111000 ms (1:51). It doesn't say that the music needs to loop. There's no way to find out that is has a looping part. Obviously, I can make it fade -- but then other non-looping tunes would fade, even when they should not.

**Comment by GeneralFailer** [comment]
I can't say I'm well-versed in technical details, but Audacious manages to determine that it shouldn't fade out the track "Cease Fire" [here](http://snesmusic.org/v2/profile.php?selected=597&profile=set) while still fading out the stage themes and other looping tracks.

**Comment by Alexey-Yakovenko** [comment]
ok, thanks for the example files, I'll keep looking

**Comment by Alexey-Yakovenko** [comment]
I just looked how foo_gep does it with SPC..

Basically, it simply adds +10 seconds to the length all songs, and uses that for fading out.
Even for the songs which don't need fading. Those songs would play a bit of additional silence, bvut then will stop sooner than 10 sec because of silence detection.

**Comment by Alexey-Yakovenko** [comment]
It's still a bit quirky and might need more testing, and most likely you'd need to re-import the files into deadbeef -- but otherwise should work.
