### ISSUE TITLE
Feature Request: CoreAudio output plugin on OS X needs device selection options under Configuration

### ISSUE THREAD

**Issue by whorfin** [DeaDBeeF-Player/deadbeef#2025]
DeaDBeeF on OS X needs the CoreAudio plugin for output.
At present this uses whatever output device is set as default in Preferences
It would be very nice indeed to allow selecting any valid audio interface, when one is using high quality external interfaces for music playback but doesn't want regular system sounds to go to that output.

**Comment by Alexey-Yakovenko** [comment]
This has been implemented now, but hasn't really been tested very well. Feedback would be appreciated.

**Comment by whorfin** [comment]
Thank you!
Functionality works great, and solves my problem.
There is a slight UX bug illustrated with [video](https://www.dropbox.com/s/649b31hwqub8vlr/IMG_6199.mp4).
The placement of options gets shoved down if one looks at the Playback tab and then switches back to Sound.  Various samplerate options become unavailable as they're off the bottom of the panel.  This persists until DeaDBeeF is restarted.

**Comment by Alexey-Yakovenko** [comment]
wow.. it doesn't look correct even on the first frame of your video, before switching tabs.
is there something customized in your system that would have caused that?
It doesn't happen on at least 3 machines I tested it on.

**Comment by whorfin** [comment]
[1.8.1-beta2](https://sourceforge.net/projects/deadbeef/files/travis/osx/1.8/deadbeef-1.8.1-beta2-osx-x86_64.zip/download) is the version I tried.  Note that versions still report themselves as "1.0" in about.

I don't know how it's supposed to look, so I'm in a poor position to suggest why.  The main difference in my system and likely what you've tested is I have a tc electronics konnekt 24D, which is selected, and why "TC Near" shows up  as output device.

**Comment by Alexey-Yakovenko** [comment]
This is how it's supposed to look

![preferences](https://user-images.githubusercontent.com/1895698/56475677-c7fd2a80-648b-11e9-80ac-afa72eb51599.gif)

**Comment by whorfin** [comment]
I see 
Maybe things draw differently with more audio devices available?

**Comment by Alexey-Yakovenko** [comment]
No, still works correctly here even with many devices in the list.

**Comment by whorfin** [comment]
Tried on a second mac running Mojave and it behaved as you show.
Problematic machine is on High Sierra for what it's worth

Cheers

**Comment by Alexey-Yakovenko** [comment]
ah, that explains it. thanks for the update.
I hope it's fixable.
