### ISSUE TITLE
Lots of plugins are gone in the website.

### ISSUE THREAD

**Issue by laichiaheng** [DeaDBeeF-Player/deadbeef#2029]
### Steps to reproduce the problem
Browse the DeaDBeeF website
### What's going on? Describe the problem in as much detail as possible.
Lots of plugins are missing.
### Information about the software:

Deadbeef version: deadbeef-git
OS: Manjaro OS

**Comment by Alexey-Yakovenko** [comment]
Thanks for reporting this. I'm working on a fix. I identified the problem. and fixed most of the plugins, so they should show up soon. Some plugins would need more work.

**Comment by Alexey-Yakovenko** [comment]
Notes for what needs fixing:

ddb_misc_playback_order: needs to simulate `gtk_combo_box_text_new` for gtk 2.16 support
ddb_gnome_mmkeys: requires new glib/gdbus, fails to find `g_bus_get_sync`
mpris: fails to find `g_dbus_node_info_new_for_xml`

other plugins should be fine.

**Comment by Alexey-Yakovenko** [comment]
handed over the issues to the respective plugin devs.
