### ISSUE TITLE
Set cover art path as variable for encoder

### ISSUE THREAD

**Issue by Bfgeshka** [DeaDBeeF-Player/deadbeef#2032]
I believe that this feature is not very hard to implement. Key can be `%a` or `%c`.

**Comment by Alexey-Yakovenko** [comment]
Nothing is hard to implement. Always a matter of priorities and free time.

**Comment by Alexey-Yakovenko** [comment]
not actionable:
cover art isn't necessarily represented by a file.
I guess, what you really want is that deadbeef could copy the existing album art from a track to the converted track.
There's another feature request about that.
