### ISSUE TITLE
decoder->init function locks on fopen

### ISSUE THREAD

**Issue by BorisCarvajal** [DeaDBeeF-Player/deadbeef#2034]
Sometimes I get a little freeze just before playing next track, a half second pause about 3 seconds near the end of the current song.
I'm playing music from a very populated partition (using ntfs-3g) so I suspected the slow access was the cause, but why reading ahead could block the playing thread and GUI?
I tracked the issue to this code from the mp3 plugin in function cmp3_init:
```
deadbeef->pl_lock ();
info->buffer.file = deadbeef->fopen (deadbeef->pl_find_meta (it, ":URI"));
deadbeef->pl_unlock ();
```
I think it should only lock pl_find_meta not fopen. This piece of code is replicated for reading tags in each plugin too.
It also happens while I'm playing one song and I select another from the playlist and making it sure that it's from other folder (not cached or opened before), if I do a right click on it and press "Reload Metadata", here again the GUI and the sound stop while accessing the file.
No sure but this could become evident if you're playing files from a network share.

Moving the locks out of fopen solved both sound issues (#2035), although clicking "Reload Metadata" still freeze the GUI because the code runs on the same thread, and that's another story.

**Comment by Alexey-Yakovenko** [comment]
That's a good finding, and definitely needs fixing.
