### ISSUE TITLE
Replace DUMB with libopenmpt

### ISSUE THREAD

**Issue by shoober420** [DeaDBeeF-Player/deadbeef#2036]
The DUMB plugin is being succeeded by libopenmpt, which kode54 is also involved with. DUMB should be replaced with libopenmpt.

**Comment by Alexey-Yakovenko** [comment]
Is there any example of where libopenmpt is superiour to DUMB, aside from license?

**Comment by shoober420** [comment]
I was reading about it, and it’s tracker music playback is more accurate then DUMBs. It makes me wonder how accurate xmp is as well. xmp is used to playback tracker music when using the oldunreal patch for Unreal Gold.

**Comment by shoober420** [comment]
It also makes you wonder how well the APE decoder in deadbeef that uses code from “libavc and rockbox”, compare to how well ffmpeg decodes APE, since technically both DUMB and the APE decoder in deadbeef are not maintained anymore, unlike ffmpeg and libopenmpt, or libxmp.

**Comment by Alexey-Yakovenko** [comment]
do you have any actual facts to support this claim?

deadbeef decodes APE very well, on par with foobar2000 speed, and definitely faster and more stable than ffmpeg.

**Comment by Alexey-Yakovenko** [comment]
I did a little bit of research, and can say why it won't replace DUMB in deadbeef, probably ever.

The source code of the openmpt is huge (57MB at the time of writing), and I don't want to ship it with deadbeef.

It relies on C++ runtime libraries, which are always a pain, especially on Linux.

There may be some value in having libopenmpt support as an additional downloadable plugin though.

Closing the issue, because the way it's worded -- it won't happen.

**Comment by shoober420** [comment]
Did you look into the kode54 fork of lbopenmpt?

https://www.foobar2000.org/components/view/foo_openmpt54

In the foobar2000 page, kode54 himself states that it is more accurate.

**Comment by Alexey-Yakovenko** [comment]
all of that is cool and all, but foo_dumb doesn't ship with foobar2000, it's a "3rd party component" so to speak. there's nothing to replace in there. I hope you get the idea.

**Comment by shoober420** [comment]
I mean, if you want to have an inferior outdated plugin to playback music tracker music by default, that’s your call. It was just a suggestion, and I would be interested to know how accurate the decoding is with the current default APE plugin, which hasn’t been updated in a while, over the currently active and maintained ffmpeg.

**Comment by Alexey-Yakovenko** [comment]
Ok, cool, please let me know about your findings!

**Comment by kode54** [comment]
If it's of any use, here's plugin source code for a libopenmpt decoder, which has really no configuration, and uses the C API of libopenmpt:

https://bitbucket.org/losnoco/deadbeef_plugins/src/92778c63552a633194ad571d46f51409ce673828/plugins/openmpt/ompt.c?at=master&fileviewer=file-view-default
