### ISSUE TITLE
HTTP streaming audio starts stuttering after a few minutes of playback

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#2037]
### Steps to reproduce the problem

Start ~any~ (as it turned out) one of specific MP3 streams from shoutcast.
Play for a few minutes.

### What's going on? Describe the problem in as much detail as possible.

Sound stutters once every few seconds.

### Information about the software:

Deadbeef version: trunk
OS: happens on macOS, but most likely platform independent

**Comment by Alexey-Yakovenko** [comment]
Notes about the issue:

The HTTP buffer stays reliably full for about 8 minutes, then the speed of buffering drops very quickly for 2 minutes, until the buffer starvation starts causing stuttering at around 10 minutes into playback, without any way to recover aside from restarting the stream.

**Comment by stefson** [comment]
So, this is the macOS failure then? Here, with Linux, it happens most of the time a few seconds after hitting the play button of that stream (via mouse and interface or with the keyboard); also there is no stutter but a failure that makes the player jump to the next track in the playlist. If I had to bet, I'd blame curl_ssl abi breakage somewhere. 

Also other strange things happen with your static builds, like not playing anything remote anymore.

**Comment by Alexey-Yakovenko** [comment]
> So, this is the macOS failure then?

I reproduced it on macOS, but I assume that the problem is platform independent.

I thought this is the same problem as you had on Linux, but apparently it isn't.

And no, the stream doesn't abort. Just stuttering.

> If I had to bet, I'd blame curl_ssl abi breakage somewhere.

This issue is not related to SSL. I was playing only regular HTTP streams.

> Also other strange things happen with your static builds, like not playing anything remote anymore.

I recommend filing a new issue about this, and attach the full deadbeef log.

**Comment by stefson** [comment]
On the original issue, it's been all about encrypted mp3 streams, and all kind of information is available from the issue, including logs etc. You should delete all that spam about linking, so that we two can go on to discuss the real issue. If you come up with a patch for this issue here on macOS in the meantime, I'd be happy to test it for that it may fix the Linux problem at the same time.

**Comment by Alexey-Yakovenko** [comment]
> On the original issue, it's been all about encrypted mp3 streams, and all kind of information is available from the issue, including logs etc.

well you already mentioned two separate unrelated issues:

1. "not playing anything remote anymore."
2. stream aborts after a few seconds playing an HTTPS stream.

They need to be posted as 2 separate issues.

**Comment by Alexey-Yakovenko** [comment]
> You should delete all that spam about linking, so that we two can go on to discuss the real issue. 

Done.

> and all kind of information is available from the issue, including logs etc.

That is not true. You only provided a single log from a static build, which doesn't support SSL at all.

I need the logs from the build with SSL support.

**Comment by Alexey-Yakovenko** [comment]
Now.. I'm cleaning up this issue, because most of the posts in it are irrelevant.

**Comment by Alexey-Yakovenko** [comment]
The issue is invalid.. Confirmed that the server bandwidth cap is too low for 128kbps MP3, all other players stutter as well. Was unlucky with test stream choice.
