### ISSUE TITLE
Can't build on OS X 10.11 with XCode

### ISSUE THREAD

**Issue by jtl999** [DeaDBeeF-Player/deadbeef#2041]
### Steps to reproduce the problem
`git clone https://github.com/DeaDBeeF-Player/deadbeef`
`git submodule update --init`

Ensure YASM is installed.

Open `osx/deadbeef.xcodeproj` in XCode.

### What's going on? Describe the problem in as much detail as possible.

Get the error after building `<redacted>/deadbeef/plugins/cocoaui/HelpWindowController.swift:12:23: Use of unresolved identifier 'Bundle'`

Deadbeef version: HEAD
OS: OS X 10.11.6

**Comment by Alexey-Yakovenko** [comment]
You need latest XCode (9).

**Comment by Alexey-Yakovenko** [comment]
I mean, I can get rid of swift (there's only the help window implementation using it), but the build would have failed later anyway.
