### ISSUE TITLE
.sid file, HVSC long (up to date) "songlenght.txt database only partly read correct

### ISSUE THREAD

**Issue by SimonGerm** [DeaDBeeF-Player/deadbeef#2045]
### Steps to reproduce the problem
install actual HVSC
https://www.hvsc.c64.org/#download
go to "plugins" sidplayer
set the path to ......./hvsc/C64Music/DOCUMENTS/Songlengths.txt

make a new playlist

### What's going on? Describe the problem in as much detail as possible.

now select a file to add:
1) one of the front part of the database (lower about 3154661 bytes):
hvsc/C64Music/MUSICANS/H/Hubbard_Rob
ACE_II.sid
the songlegths will be shown correct like in database 5:14
2) two files closer to the end of the database:
/MUSICIANS/S/Siebold_Markus/Turrican_2-The_Final_Fight.sid
and (because this has more than one melody)
/MUSICIANS/S/Siebold_Markus/Twice_tune_1.sid
all will be shown with 3:00 playtime, what is the standart time from deadbeef
and not like it is inside database:
1:56 2:42 2:26 1:56 0:42 1:56 0:45 0:39 3:03
1:52

test:
split the database in 2 parts, of course the second must have
the entry: [Database] at first line.
select the second part of the database, and the files 
hvsc/C64Music/MUSICIANS/S/Siebold_Markus/Turrican_2-The_Final_Fight.sid
hvsc/C64Music/MUSICIANS/S/Siebold_Markus/Twice_tune_1.sid
will have the correct songlengths.

### Information about the software:

Deadbeef version : DeaDBeeF-0.7.2 (from standard tumbleweed repo)
OS: opensuse tumbleweed (20180726-0) 

please take care, hvsc introduced a new songlength database format "songlenghts.md5"
see hvsc/C64Music/DOCUMENTS/Songlenght.faq
because they write there that they will drop in future the old format, maybe a good idea:
instead of fixing only the old format, switch to the new format and check that this will work also
with long songlenght-files.

simoN

**Comment by Alexey-Yakovenko** [comment]
Please note: I did not implement the Songlengths.md5 support yet, but since it's a simplified version of Songlengths.txt -- it should be trivial to add later.

**Comment by SimonGerm** [comment]
Thanks for fix this bug,

simoN

**Comment by Alexey-Yakovenko** [comment]
FYI: I just added Songlengths.md5 support too.

**Comment by SimonGerm** [comment]
Hi,
sounds good, question:
did you plan in near future make a new release?
DeaDBeeF-0.7.2 is from 2016.....
simoN

**Comment by Alexey-Yakovenko** [comment]
Yes, I do. It's been in an almost ready state for the last few months, I just could not get to fixing the last critical issue (which turned out to be a lot of work). I hope to finish working on this issue in the next 2-3 weeks, and release the final beta.

**Comment by Tekl** [comment]
Does DeaDBeeF support milliseconds?
