### ISSUE TITLE
Back/previous song button behaviour on random order

### ISSUE THREAD

**Issue by proton** [DeaDBeeF-Player/deadbeef#2050]
### Steps to reproduce the problem

1. Set random playback order
2. Start playing music
3. Press "back"

### What's going on? Describe the problem in as much detail as possible.

It should return to the previous track, but starts playing random track.

### Information about the software:

Deadbeef version: 0.7.2
OS: Ubuntu 18.04

**Comment by Alexey-Yakovenko** [comment]
Random mode is just that -- random. Shuffle mode is what you need.
