### ISSUE TITLE
Playlist has no columns

### ISSUE THREAD

**Issue by Taur10** [DeaDBeeF-Player/deadbeef#2051]
This is an odd one, while I was moving things around to customize my DeadBeef, the columns disappeared from the playlist. All I get is song title, with no column name and no ability to add more columns.

![2018-09-14-194520_1060x197_scrot](https://user-images.githubusercontent.com/24876074/45580484-252a6100-b857-11e8-893c-c71b4f7f7398.png)

How do I get them back?

**Comment by Alexey-Yakovenko** [comment]
You can find and delete the borked column config in the configuration file: `~/.config/deadbeef/config`
Delete the line, and the columns should be rebuilt as defaults.
