### ISSUE TITLE
Queueing a playlist (.m3u) from command line adding to top of playlist

### ISSUE THREAD

**Issue by Nagasaki45** [DeaDBeeF-Player/deadbeef#2052]
### Steps to reproduce the problem

- Have a .m3u playlist. Let's call it `my_playlist.m3u`.
- Have some files already playing in deadbeef.
- `deadbeef --queue my_playlist.m3u`.
- The items from `my_playlist.m3u` are added to the top of the playlist.

### Expected results

The items from `my_playlist.m3u` should be added to the end of the playlist, as happen when queuing files or folders. 

### Information about the software:

Deadbeef version: 0.7.2
OS: arch

### Note

It might be a design decision. Or an issue with my configuration. In both cases I'm sorry in advance.

BTW, thanks for this great software!

**Comment by spvkgn** [comment]
> Deadbeef version: 0.7.2

1.8.0-RC add files to the end of playlist. Try to update it.

**Comment by Alexey-Yakovenko** [comment]
Thanks for spotting that this has been fixed.
