### ISSUE TITLE
Add possibility to display album art on desktop

### ISSUE THREAD

**Issue by Xalthy** [DeaDBeeF-Player/deadbeef#2056]
It would be great to display album art on desktop, like exaile does. It would be enough to set size and position on desktop. 

If it's not possible, it would be nice to set path to save current album art, for conky to pick up. 
I know that Deadbeef already saves all album arts in its cache folders, but now I have to copy them by script from there, and script is working all the time, not only when song changes.

**Comment by jtojnar** [comment]
It is quite easy to use MPRIS API for things like these:

https://gist.github.com/jtojnar/2abab73d11593c21cd93239e40d70a45

**Comment by Alexey-Yakovenko** [comment]
The provided information is not enough for me to understand what it is being requested.
Also, it's not guaranteed that deadbeef will save any image files in the disk cache.
