### ISSUE TITLE
SACD ISO playback support

### ISSUE THREAD

**Issue by ArminiusTux** [DeaDBeeF-Player/deadbeef#2059]
Since DeaDBeeF can handle any types of DSD [uncompressed, DST & Wavpack-DSD], it would be nice seeing SACD ISOs completing the chain and being accepted as well [drag&drop].

Useful code can be borrowed from e.g. [sacd-ripper](https://github.com/setmind/sacd-ripper) & [vfs.sacd](https://github.com/xbmc/vfs.sacd)

Deadbeef version: 1.8.x
OS: Linux [x86_64 & armhf], macOS

**Comment by Alexey-Yakovenko** [comment]
duplicate of #683
