### ISSUE TITLE
ReplayGain "scan per track" is not possible

### ISSUE THREAD

**Issue by vibrasphere111** [DeaDBeeF-Player/deadbeef#2063]
### Steps to reproduce the problem
- Install deadbeef through "ubuntu software", then download the replaygain plugin through the following link: http://sourceforge.net/projects/deadbeef/files/plugins/x86_64/ddb_misc_replaygain_scan-64400aa-x86_64.zip/download
- Install/add the plugin to deadbeef

### What's going on? Describe the problem in as much detail as possible.
When i right-click on any file in my playlist (no matter if flac / mp3..) i do have the option to choose "ReplayGain", but then only two further options: "scan as single album" and "remove replay gain info".

Normally there should be "scan per-file track gain" also available, right? i just can't find it.
I also tried to go to deadbeef>preferences>playback and change the replaygain mode to "title". But that has absolutely NO effect on the choices that i have when i rightclick on a track and want to scan/replaygain.

Where is the issue here? 
Do I have to get another plugin? 
Do i need a plugin at all or is everything i need delivered with deadbeef itself?

### Information about the software:

Deadbeef version: 0.7.2
OS: Ubuntu 18.04 (Bionic Beaver) 64bit Desktop

Appreciating all kinds of help to this!

**Comment by Alexey-Yakovenko** [comment]
The plugin you linked is a 3rd party plugin, developed by other people.
Please try here: https://github.com/Soukyuu/ddb_misc_replaygain_scan

Alternatively, you should switch to using deadbeef 1.8 beta, which comes with a built-in replay gain scanner:

https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8/deadbeef-static_1.8-beta3-1_x86_64.tar.bz2/download
