### ISSUE TITLE
Publish a new Release

### ISSUE THREAD

**Issue by archfan** [DeaDBeeF-Player/deadbeef#2066]
The last release is over 2 years old. Can you publish an updated release?

Asking for a friend.

Thanks.

**Comment by yssmcl** [comment]
https://github.com/DeaDBeeF-Player/deadbeef/issues/1945

**Comment by Alexey-Yakovenko** [comment]
I'm working on it. I'm fully aware that the previous stable release is >2 yr old.
I can't publish the new release until all major issues are fixed.
