### ISSUE TITLE
Syntax error when running configure

### ISSUE THREAD

**Issue by a0w8** [DeaDBeeF-Player/deadbeef#2067]
Trying to run ./configure gives me the following error:

> ./configure: line 24214: syntax error near unexpected token `ZIP,'

> ./configure: line 24214: `    PKG_CHECK_MODULES(ZIP, libzip, HAVE_ZIP=yes, HAVE_ZIP=no)'

Am I missing some package? or is there an actual syntax error?
As a side note, is it possible to clone the latest stable version instead? if so how do I do it?

Deadbeef version: Latest from git
OS: Debian Stretch

**Comment by kuba160** [comment]
Please check if you have `pkg-config` installed.

If you have cloned git repository you may change version by choosing another branch (or tag for specific version). To change the branch use `git checkout BRANCH`. Current branches are:
* `master` - for current development state
* `1.8` - next release (currently beta)
* `0.7` - current stable (*quite old*)

**Comment by a0w8** [comment]
I installed `pkg-config` and then it gave me an error for not finding Jansson. 
I had `libjansson4` already installed. Installing `libjansson-dev` fixed it.
