### ISSUE TITLE
Problem with removing SoundEQ in DSP list

### ISSUE THREAD

**Issue by BMSMobile** [DeaDBeeF-Player/deadbeef#2070]
### What's going on? Describe the problem in as much detail as possible

When I try to remove SoundEQ plugin from DSP list, the sound quality is MUCH better. But when I go to DSP menu, this SoundEQ is present again. How I can remove this default DSP plugin?

### Information about the software:

Deadbeef version: last
OS: AP-Linux

**Comment by Alexey-Yakovenko** [comment]
It's not possible to completely remove superEQ from DSP chain. However, when it's disabled -- it doesn't affect sound or performance in any way. It's completely bypassed.

**Comment by BMSMobile** [comment]
Уважаемый Алексей! Очень благодарен Вам за великолепное приложение для воспроизведения музыки! 
В данном случае, могу с Вами не согласиться. Именно при удалении выключенного SuperEQ из листа DSP, происходит скачок в звуке, примерно на полсекунды вперёд и качество звука в этот момент значительно улучшается. При этом, при каждом открытии окна настроек DSP, там уже снова присутствует SuperEQ и не понятно, портит ли он снова звук или «подключается» на следующем треке.

**Comment by BMSMobile** [comment]
Считаю Ваш плеер самым лучшим для воспроизведения на Linux, поскольку перепробовал много других и сравнивал. Не знаю, что происходит на программном уровне, но в результате удаления (нажимаю на кнопку - или загружаю пересет с отсутствующим SuperEQ в меню DSP) этого фильтра, происходят следующие изменения в звуке: больше воздуха и более прозрачный объем сцены, более натуральные тембры инструментов и голоса, становится выше динамический диапазон и все это хорошо слышно. Поверьте, все это не является самовнушением). Возможно, что на это влияет буфер и его перезагрузка, либо сам фильтр не является прозрачным для системы.

**Comment by Alexey-Yakovenko** [comment]
на практике, единственное что происходит при удалении supereq в UI -- это вызов функции reset которая дропает текущий буфер. если никаких других изменений не происходит - никакого влияния на звук быть не может.

никакой прозрачности фильтра нет. если он отключен -- он просто не используется. поток идет напрямую в буфер, без фильтра.

**Comment by Alexey-Yakovenko** [comment]
если хочется чтобы supereq вообще отсутствовал в программе -- можно удалить supereq.so.

**Comment by BMSMobile** [comment]
Спасибо за быстрый ответ! Постараюсь опытным путем установить, что именно влияет на звук - очистка буфера или присутствие SuperEQ.

**Comment by BMSMobile** [comment]
Уважаемый Алексей! 
Произвёл проверку работы плеера после удаления SuperEQ. Удалил, как Вы и советовали, файл supereq.so. После открытия меню DSP, там автоматически появился ресемплер, но после его удаления, больше в текущей сессии он не появлялся. 
Что хочу сказать, улучшения в звуке - налицо! Разрешение увеличилось, глубина сцены выросла, во всем диапазоне кристальная чистота и деликатность в звуке. Благодарю Вас за замечательное приложение и Вашу помощь, спасибо!

**Comment by BMSMobile** [comment]
Здравствуйте, Алексей! 
Разрешите поздравить с новогодними праздниками и пожелать Вам успехов в профессии, в которой так преуспели! 
Разрешите также подбросить Вам информацию к размышлению. После длительного прослушивания плеера, выяснилось, что на улучшение звука положительно влияет именно сброс буфера. После удаления плагина SuperEQ, при пустом меню DSP, произвожу загрузку пустого пресета, т.е. без списка плагинов. Это можно делать прямо во время воспроизведения. Происходит скачок и звук улучшается кардинально. Проявляется более глубина и объём, голос становится живее, звук чище. Особенно хорошо это заметно на композициях с большим количеством высоких частот, они становятся на место и разрешение увеличивается. DeaDBeef установлен под AP-Linux, файлы Flac проигрываются с сервера NAS Qnap по мегабитной сети. В связи с этим вопрос, возможно ли сделать автоматическим сброс буфера для каждого воспроизводимого файла? Чтобы каждый раз не загружать пресет в меню DSP, т.е. сбрасывать буфер.

**Comment by Alexey-Yakovenko** [comment]
Для начала стоит проверить, происходит ли эта проблема в свежих билдах (1.8beta или git master). Если происходит - это однозначно баг, который надо исправлять. Мне потребуется информация о конфигурации вашего железа - в частности, есть ли внешний цап, алса или пульса, как настроены, совпадают ли параметры файла с параметрами звукового вывода, и т.д.

**Comment by BMSMobile** [comment]
Версия AP-Linux V4, Версия DeaDBeef 0.7.2, вывод звука через ALSA на usb-s/pdif конвертер Amanero Combo384 и далее по коаксиалу на внешний цап. В настройках ALSA output plugin в DB отключён ресемплинг, Release device while stopped - включено, буфер - 8192, период - 1024. Bit perfect вывод настроен и проверяется подачей на цап файла с hdcd кодировкой, при этом на цапе загорается индикатор hdcd, параметры вывода совпадают. Бета-версии ещё не пробовал устанавливать.
