### ISSUE TITLE
Deadbeef 1.8 release estimate

### ISSUE THREAD

**Issue by C0rn3j** [DeaDBeeF-Player/deadbeef#2076]
I've noticed a bug that's present on the current stable release from 2016 which makes some songs not play at all, but they work flawlessly on the git version.

Hence a question I hope you won't find too annoying - How's the 1.8 stable release process going? 

I've seen that throughout the years there's been alpha and beta releases on sourceforge, but besides that I can't find any info.

**Comment by C0rn3j** [comment]
Am asking for an estimate when the release will be ready. 
I don't expect a specific date, a _"probably around X months"_ would suffice.

I already run the latest git (updated daily) since stable release won't play MP3s for me on Arch Linux.

**Comment by Alexey-Yakovenko** [comment]
I can't promise any specific dates. It's quite unlikely that I will have time to release it before end of march or so.
