### ISSUE TITLE
sndio problems

### ISSUE THREAD

**Issue by Kistelini** [DeaDBeeF-Player/deadbeef#2079]
### Steps to reproduce the problem
Running sndio on Linux, tested with current master, 1.8-beta4 and sndio backported to 0.7.2. Select sndio output driver, play back some files.

### What's going on? Describe the problem in as much detail as possible.
Playback stops when switching between tracks or doesn't start playing at all, sometimes it plays back with a lot of noise. Console prints:
```
sndio: failed to set parameters
sndio: failed to write buffer
pthread_join failed: Resource deadlock avoided
```

### Information about the software:

Deadbeef version: master, 1.8-beta4 and 0.7.2 with sndio patch
OS: Linux

**Comment by Alexey-Yakovenko** [comment]
The sndio plugin was a user-contributed code, which is not really supported/maintained by anyone.
I guess I'll have to remove it completely.
Thanks for the heads up.
