### ISSUE TITLE
artwork plugin loads embedded covers before external, which causes unexpected results

### ISSUE THREAD

**Issue by C0rn3j** [DeaDBeeF-Player/deadbeef#2080]
### Steps to reproduce the problem
Just use this cover as cover art in an album:
![cover](https://user-images.githubusercontent.com/1641362/51554495-bc429d80-1e75-11e9-8520-3255a01165b3.png)

While using for example this song from the album which has an embedded low-res cover:
https://cloud2.rys.pw/s/HiWaJqYPzWEJtFg

### What's going on? Describe the problem in as much detail as possible.
Cover art is very blurry when compared to the source picture since it gets loaded from the file itself rather than in-folder cover.
Originally posted in #1835 

![image](https://user-images.githubusercontent.com/1641362/51554115-d2039300-1e74-11e9-9764-0b7fc9072e0b.png)

~~Am using an MPRIS plugin, and the cover loads in the same bad quality on my phone over Kdeconnect also.~~
EDIT: Irrelevant

### Information about the software:
Deadbeef version: Latest git as of 2019-01-22
OS: Arch Linux

**Comment by Lithopsian** [comment]
I can't reproduce this.  Is it only with MPRIS?  Which GTK3 version?  Only with this particular image?  What happens if you resize the image?

**Comment by Alexey-Yakovenko** [comment]
It's quite likely that the media file has embedded cover of lower resolution, which is causing this issue.
In the newer plugin (used on mac and android) the priorities has been changed, but apparently not in the artwork-legacy.

**Comment by C0rn3j** [comment]
I've just made sure that downloading the file from gitlab results in an identical file - it does. The file is named cover.png

I've removed the MPRIS plugin just to be sure - no, it's not the cause, the image is still blurry.

I've switched to GTK2 - it happens there too. 

GTK3 version - 
gtk3 3.24.4-1

and as I have been going through these, I have removed the cover file entirely and the low res image still says, which confirms what @Alexey-Yakovenko just posted.

**Comment by Bfgeshka** [comment]
For checking you have to remove cover from the cache too.

**Comment by C0rn3j** [comment]
Removed cache, same results.

Using the cover for another album than the original one loads it fine in high quality, so it must be embedded.

**Comment by C0rn3j** [comment]
Since posting this I've thought about it and had some discussions - there should actually be a possibility to show all covers and switch between them.

Some albums apparently have album cover + separate music covers for different songs, so whether the built-in or file cover is used is irrelevant in those cases.

Tauon Music Box for example takes all the possible covers (file covers + embedded), marks them with E or F which you can see on hover along with the number of available covers and switches between them when clicked.

Should I open a new issue for this?

**Comment by Alexey-Yakovenko** [comment]
@C0rn3j 
Doesn't matter to me. Development process is not based on feature requests, but the users are free to post whatever they want to be added . or changed.
