### ISSUE TITLE
GTKUI plugin fails to load when GTK version is between 3.0 and 3.10

### ISSUE THREAD

**Issue by Lithopsian** [DeaDBeeF-Player/deadbeef#2081]
### Steps to reproduce the problem
Configure Deadbeef to use GTK3 and run on a system with GTK version at least GTL3.0, but less than GTK3.10.  Plugin will fail with message Undefined symbol: gapp
### What's going on? Describe the problem in as much detail as possible.
gapp appears to be defined as extern for all GTK3 versions, but not declared unless version is at least GTK3.10, but is used in progress.c for all GTK3 versions.
### Information about the software:

Deadbeef version: trunk
OS: Debian

**Comment by Alexey-Yakovenko** [comment]
That's a new system requirement of deadbeef on trunk. GTK3 < 3.10 is not supported anymore.
