### ISSUE TITLE
asm volatile ( "" ) is going to be rejected by >=g++-8.3.0

### ISSUE THREAD

**Issue by stefson** [DeaDBeeF-Player/deadbeef#2087]
hey there, I just wanted to mention this. 
Unless I'm misstaken, a few plugins use it, libwma for instance. 

upstream discussion about it is here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89585

**Comment by Alexey-Yakovenko** [comment]
To my best understanding, the upstream discussion is talking about when `asm volatile (...)` syntax is used in file scope, and only C++ mode is affected. Can you point out any example where this happens in deadbeef codebase? Especially considering that most code in deadbeef is written in C, and doesn't use G++.

Meanwhile, closing as unconfirmed.

**Comment by stefson** [comment]
you're right, it's only c++ mode and not c
