### ISSUE TITLE
[macOS] plugin info is not readable in dark mode

### ISSUE THREAD

**Issue by deseven** [DeaDBeeF-Player/deadbeef#2092]
### Steps to reproduce the problem
Try to read any plugin info with dark mode enabled.

![](https://d7.wtf/InvoluntaryChinantecanUnrevengeful.png)

### What's going on? Describe the problem in as much detail as possible.
Black text on a dark-grey background is not readable.

### Information about the software:

Deadbeef version: 1.0 (master)
OS: macOS 10.14.3

**Comment by Alexey-Yakovenko** [comment]
I was able to reproduce this problem once. Tried to look how to fix it, but the problem suddenly stopped happening, and I can no longer get it. Can you restarting deadbeef and switching dark mode on/off and see if it does the same on your mac?

**Comment by deseven** [comment]
Here is the video with me switching between normal and dark mode - https://d7.wtf/s/Screen%20Recording%202019-03-14%20at%2012.37.02.mp4

In my experience this usually happens when you assign a specific color to a cocoa control.

**Comment by deseven** [comment]
Actually same thing happens with help window.
![](https://d7.wtf/NahuatlecaFavorednessUnfiber.png)

**Comment by deseven** [comment]
Log window:
![](https://d7.wtf/TriakisicosahedralInterruptivelyEnzymically.png)
