### ISSUE TITLE
macOS: album art gets cropped vertically if it is taller than it is wide

### ISSUE THREAD

**Issue by tomjepp** [DeaDBeeF-Player/deadbeef#2095]
### Steps to reproduce the problem
1. Add a track with a portrait-shaped piece of album art to the playlist
2. Observe that the album art is cropped - the bottom is missing

### What's going on? Describe the problem in as much detail as possible.
The size of album art isn't known when group heights are calculated.

As such, the minimum reserved space for album art is as wide as the art column, and as tall as the art column is wide.

This means the album art gets cut off.

However - if the list of tracks is taller than the minimum, the art may be displayed full size.

### Information about the software:

Deadbeef version: master 9b369519
OS: macOS 10.13.4

**Comment by Alexey-Yakovenko** [comment]
isn't that a duplicate of #2096 ?

**Comment by tomjepp** [comment]
Yes, and this is fixed already. I'll close :)
