### ISSUE TITLE
[macOS] terrible album art plugin performance

### ISSUE THREAD

**Issue by deseven** [DeaDBeeF-Player/deadbeef#2099]
### Steps to reproduce the problem
1. Add "Album art" column.
2. Try to scroll, resize columns or resize window.

### What's going on? Describe the problem in as much detail as possible.
Everything is slow as hell, cpu load jumps up to 100% (that's on i7-7700k). [Here](https://d7.wtf/s/Screen%20Recording%202019-03-14%20at%2017.13.28.mp4) is the video that shows it in detail.  

@tomjepp says that "on scrolling etc it will request the same image several times and then end up redrawing the playlist view anything up to 10 times for a single piece of art (because it got triggered 10 times)".

### Information about the software:

Deadbeef version: 1.0 (master)
OS: 10.14.3

**Comment by Alexey-Yakovenko** [comment]
This is mostly fixed on medialib branch. It's not going to land on master quite yet, but if you really want faster album art on mac -- you may consider switching to medialib branch, and at least with some settings, the plugin works quite fine.
