### ISSUE TITLE
Lagging when resuming after paused or playing the next song after one is finished.

### ISSUE THREAD

**Issue by Incantatoric** [DeaDBeeF-Player/deadbeef#2106]
### Steps to reproduce the problem
Play any song, pause it and then resume it.
Wait until a song is finished and then switch to the next song.

### What's going on? Describe the problem in as much detail as possible.
There's a brief lagging - about 2-3 seconds - before it resumes or plays the next song.
I thought it was because the songs were in a separate ntfs HDD, but the same phenomenon happened when the songs were in the main SSD as well.
What's funny is that if I forcibly move the play bar to other location then there's no lagging.

[Here is the current deadbeef setting:](https://imgur.com/a/3lq4jqv)

I changed the ALSA output plugin to PulseAudio Output Plugin, but the result was the same. I also have Clementine and VLC installed and they do not suffer from this problem. I recently have installed deedbeef-mpris2-plugin so that media widget can recognize it, but the problem existed before it.

I'll provide any necessary information as needed.

### Information about the software:

Deadbeef version: 0.7.2
OS: Arch Linux, KDE

**Comment by Alexey-Yakovenko** [comment]
Can you verify if the same issue happens in 1.8-RC?

**Comment by Incantatoric** [comment]
@Alexey-Yakovenko I apologize for my ignorance, but I cannot figure out what 1.8-RC means.

**Comment by Alexey-Yakovenko** [comment]
This build: https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8/deadbeef-static_1.8.0-RC1-1_x86_64.tar.bz2/download

It's a release candidate of the next release.

**Comment by Incantatoric** [comment]
@Alexey-Yakovenko Yes! Both problems do not persist anymore. So I guess I have to wait for the next candidate for now while using the candidate version?

**Comment by Alexey-Yakovenko** [comment]
Pretty much. Thanks for checking.
