### ISSUE TITLE
DeaDBeeF dislikes some of the entries in the playlist containing online radio urls

### ISSUE THREAD

**Issue by ptkovsky** [DeaDBeeF-Player/deadbeef#2108]
### Steps to reproduce the problem
1. simply start DeaDBeeF
2. add a playlist containing a specific item
3. start playing it

### What's going on? Describe the problem in as much detail as possible.
When opening the player, adding a new playlist and trying to play its contents with the url at `http://147.175.61.100:8000/`, a Log window immediately pops up with the error suggesting that the player `Failed to play track: http://147.175.61.100:8000/`.

Testing the same case with other players behaving adequately in the above-mentioned case confirms the issue with DeaDBeeF.

### Information about the software:

DeaDBeeF version: 119ade1, current latest master build for osx available from travis
OS: macOS 10.14.4

**Comment by ptkovsky** [comment]
Thanks for the quick fix, Alexey. New build fixes the problem with the playlist entry that has been reported earlier. Just wanted to add that first time starting it showed other cosmetic errors. After the first install of https://github.com/DeaDBeeF-Player/deadbeef/commit/6d56a1d10f95c63b08b5651142d0f8eed660b914, logger immediately popped out with the information:
```
plugin aac_1_load not found or failed to load
plugin adplug_1_load not found or failed to load
plugin alac_1_load not found or failed to load
plugin artwork_1_load not found or failed to load
plugin converter_1_load not found or failed to load
```
Reinstalling fixed the issue.

Also wanted to add that I personally encounter other formats than `mp3`, particularly, there are a lot of `acc` radio streams available on the internet, so assuming `mp3` may be potentially good but somehow limited approach.

**Comment by Alexey-Yakovenko** [comment]
> plugin aac_1_load not found or failed to load

How deadbeef was installed? This error means that you had files called "aac_1.so", or perhaps "aac.1.so". It's not something that could happen if you just unpacked a zip, or ran make install.. So it means your installation method is doing something odd.

> Also wanted to add that I personally encounter other formats than mp3, particularly, there are a lot of acc radio streams available on the internet, so assuming mp3 may be potentially good but somehow limited approach.

It's a fallback. Deadbeef can't probe network streams against multiple codecs, so I had to add this.
Most streams have the content-type specified though, so they should work fine.

**Comment by ptkovsky** [comment]
Thank you very much for the detailed explanation. Indeed, the event looked strange. Just unpacked the zip and moved it to the Applications folder, as always, nothing special. Couldn't find any related "aac" or "so" files or the plugins folder in macOS to check for them, except for the file in the Resources folder named "aac.dylib" that looks fine to me though.

**Comment by Alexey-Yakovenko** [comment]
oops.. sorry I forgot you're on mac. I will try to reproduce it.. When copying app bundles over the previous version .. sometimes odd stuff happens.
