### ISSUE TITLE
Does the tag editor handle the id3v2 tag "Album Artist" correctly?

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2110]
### Steps to reproduce the problem
DeaDBeeF 0.7.2 displays the tag "Album Artist" as < BAND > in the tag editor. The new version 1.80 now knows "Album Artist" as key, but the display is not correct.  If the Id3v2 tag "Album Artist" exists it will still be displayed as < BAND >, the "Album Artist" field will keep empty.
If you insert a name in the tag editor under "Album Artist", DeaDBeeF 1.8.0 will save it as id3v2 tag "album artist", at least kid3-cli will display it like this and won't recognize it as correct "Album Artist" tag.

### Information about the software:
Deadbeef version: latest version of 1.8.0 (deadbeef-static_1.8.0-1_x86_64)
OS: Antergos Linux

**Comment by Alexey-Yakovenko** [comment]
The implementation in deadbeef was designed to be compatible with Foobar2000, which at the time used `TPE2` for Band and `TXXX Album Artist` for Album Artist.

However, testing it just now uncovered that this is no longer the case, and Foobar2000 has reversed the behavior. Now it uses `TPE2` for Album Artist, and writes the band into TXXX BAND.

Technically this was always an option in foobar2000, and now it became ON by default.

![TPE2](https://user-images.githubusercontent.com/1895698/55688332-8fcbf700-5977-11e9-9352-61c827351add.png)

However deadbeef doesn't (yet) have customization of this kind. So I guess I'll have to add this at some point to line up with fb2k.

**Comment by Alexey-Yakovenko** [comment]
By the way, I could not reproduce what you wrote:
> If the Id3v2 tag "Album Artist" exists it will still be displayed as < BAND >, the "Album Artist" field will keep empty.

I'm seeing both Album artist and Band, and they work as two independent fields.

**Comment by kpcee** [comment]
Thanks for the quick answer. If DeaDBeeF uses TPE2 for Band then the matter is already settled. kid3 uses TPE2 for Album Artist, so it's no mistake why DeaDBeeF displays it differently and the field Album Artist remains empty.
