### ISSUE TITLE
Use getaddrinfo() instead of gethostbyname()

### ISSUE THREAD

**Issue by luigino** [DeaDBeeF-Player/deadbeef#2111]
Building 1.8.0 on openSUSE Tumbleweed. and rpmlint gives out this warning:
```
deadbeef.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/deadbeef/mms.so
The binary calls gethostbyname(). Please port the code to use getaddrinfo().
```

Also see [this](http://udrepper.livejournal.com/16116.html).

**Comment by Alexey-Yakovenko** [comment]
I don't know if this change would affect functionality, and it's difficult to test, but the fix should at least shut up the message you're seeing.
