### ISSUE TITLE
Status bar localization does not apply

### ISSUE THREAD

**Issue by spvkgn** [DeaDBeeF-Player/deadbeef#2113]
### What's going on? Describe the problem in as much detail as possible.

In 1.8.0 status bar localization does not apply as it does in 0.7.2:

![Снимок экрана в 2019-04-08 16-11-16](https://user-images.githubusercontent.com/4147135/55720152-9743dc80-5a19-11e9-9c3a-f1c91e015758.png)

0.7.2:
![Снимок экрана в 2019-04-08 16-10-43](https://user-images.githubusercontent.com/4147135/55720256-d40fd380-5a19-11e9-99da-dcab8e7640d7.png)

### Information about the software:

Deadbeef version: 1.8.0
OS: Linux

**Comment by spvkgn** [comment]
@Alexey-Yakovenko Thanks, but it doesn't apply in 1.8.1-beta1.

![Снимок экрана в 2019-04-18 16-40-09](https://user-images.githubusercontent.com/4147135/56358730-f57e7580-61f8-11e9-843f-ba9e047923f8.png)

**Comment by Alexey-Yakovenko** [comment]
Yes, because at the time when beta1 was built -- this text has not been translated yet.
I will make sure to double check that localizations are working in beta2.
