### ISSUE TITLE
[Feature Request] "Sort As" option in playlist column settings

### ISSUE THREAD

**Issue by SpecialBomb** [DeaDBeeF-Player/deadbeef#2115]
What I'd like to propose is a feature that let's you display how the text is shown, but also have a separate input box in the column settings that tells deadbeef how to sort it when you click the column header.

So, this requires a bit of explanation. I originally thought I found a bug, as when I added an album into my playlist with more than one artist (while sorting by "Artist - Album"), it caused the tracks in question to appear elsewhere in the playlist, rather than grouped nicely by album. I didn't know, but that was because when you click the column headers to sort, it does so alphanumerically. I fixed my small issue by simply changing the column settings for "Artist - Album" to display the album first, then the artist, so it always sorts by the name of the album. A similar thing happens with disc sets and track numbers. If I sort the track numbers to decend and there is a two disc set album, then sort by album again, it will sort it by placing the first two tracks of each disk, then the second tracks and so on. I fixed this by changing the track number column to also display the disc number of the set first, then the track number.

For example, with "Album - Artist", you would edit the column settings to see the "Format:" input box, as well as a new input box that is toggleable with a checkmark called "Sort:". In the "Format:" input box, it would have "%artist% - %album%", but the "Sort:" box would have "%album%%artist%". This would let you display the artist and album name as normal, but actually sort it alphanumerically as the sort string, keeping the grouping of the albums consistent. Disabling the checkbox would simply mean that the "Format:" string is how its sorted, which is how it is by default.

### Information about the software:

Deadbeef version: 1.8.0
OS: Debian 9

**Comment by mallniya** [comment]
Isn't this implemented in 0.7.0?

**Comment by Alexey-Yakovenko** [comment]
no, I don't think so... clicking on a column would always sort by the displayed text, it doesn't have a separate sorting configuration

**Comment by mallniya** [comment]
My 1.8.8 installation has "Format" and "Sort format" fields within column edit window -- I thought it exactly what is described above. What is it then if not requested feature?

**Comment by Alexey-Yakovenko** [comment]
Thansk, you're right, it's the thing from this feature request. Sorry, I smh forgot that it was added. Closing.
