### ISSUE TITLE
Vorbis comment: "Album Artist" should be defined by the "ALBUMARTIST" field

### ISSUE THREAD

**Issue by Hasshu** [DeaDBeeF-Player/deadbeef#2118]
The "ALBUMARTIST" field is the _de facto_ standard for tagging an album artist in Vorbis comments, whereas "ALBUM ARTIST" (with a space) was an odd one out used by foobar2000 [before v1.1.8](http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Encouraged_Tag_Standards#Overview_of_Current_Recommendations) released back in 2011.

DeaDBeeF v1.8.0

**Comment by Hasshu** [comment]
Hmm... I just tested a few FLAC files with DeaDBeeF v1.8.1, and `<ALBUMARTIST>` is still shown as an extra key, while the proper "Album Artist" remains blank. The files in question were tagged via foobar2000.

**Comment by Alexey-Yakovenko** [comment]
Yeah this bug is about vorbis, not about FLAC. I heard that there's the same issue with FLAC files, which needs to be fixes in the same way, but I don't think it's been fixed yet.

**Comment by Hasshu** [comment]
Well, FLAC files are tagged with Vorbis comments, hence my surprise. Should I open a separate issue for that?

**Comment by Alexey-Yakovenko** [comment]
"vorbis comments" define only how key-value pairs are written within the tags, and the meaning of the names. They don't define how ogg or flac get tagged, i.e. how metadata packets are stored in the files. Therefore there isn't any common code between the two.

I wouldn't mind if you create another issue about flac.

**Comment by Hasshu** [comment]
> "vorbis comments"

To be frank, I'm not sure what is the proper term at this point: Wikipedia calls it "[Vorbis comment](https://en.wikipedia.org/wiki/Vorbis_comment)", while the XiphWiki refers to it as "[VorbisComment](https://wiki.xiph.org/VorbisComment)" (and both seem to treat it as a countable noun).

> They don't define how ogg or flac get tagged, i.e. how metadata packets are stored in the files. Therefore there isn't any common code between the two.

I see. My knowledge of audio metadata isn't particularly vast, so I expected the fix to be "universal".

**Comment by janbar** [comment]
fixed by version 5.5.0
