### ISSUE TITLE
Some functions in the context menu and as shortcuts work differently

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2119]
### Steps to reproduce the problem
If you use the ReplayGain Scanner in the context menu, all tracks that are marked will be processed there. But if you create a hotkey with the same function, only the current file will be used and the selection will be ignored. The same behavior when deleting files, context menu and shortcut working differently and can even lead in data loss. Since the context menu deletes all marked files but not the currently played file, a shortcut always deletes the currently played file and ignores the selection!

By the way, it would be very nice if the confirmation dialog would contain information about what or how many tracks will be deleted from disc instead of a hint how to turn it off or move it to trash.

### Information about the software:
Deadbeef version: 1.8.0
OS: Antergos Linux

**Comment by Alexey-Yakovenko** [comment]
I didn't yet have time to validate this, but are you sure that when configuring hotkeys you selected the right category? Each hotkey action can be used in on of several contexts, such as currently playing file, all selected files, etc.

**Comment by kpcee** [comment]
Huh, sorry for my mistake. I have not seen that the functions are multiple in the list and depending on where you select it, the behavior is different. Now it goes as it should.
