### ISSUE TITLE
Crashes on launch after exiting while playing a file on an external drive which is no longer available

### ISSUE THREAD

**Issue by ph0boss** [DeaDBeeF-Player/deadbeef#2120]
### Steps to reproduce the problem

Start playing a file on an external drive in DeadBeef
Exit the player (do not stop playback)
Unplug the drive
Launch DeadBeef Again
Get a crash

### What's going on? Describe the problem in as much detail as possible.
DeadBeef crashes on launch. Log example:

starting deadbeef 1.8.0
server_start
searching for GUI plugins in /home/ph0boss/.local/lib64/deadbeef
searching for GUI plugins in /home/ph0boss/.local/lib/deadbeef
searching for GUI plugins in /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 50 files
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK3
selected GUI plugin not found or failed to load, trying to find another GUI plugin
the plugin not found or failed to load
the plugin not found or failed to load
loading plugin /usr/lib64/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/ph0boss/.local/lib64/deadbeef
loading plugins from /home/ph0boss/.local/lib/deadbeef
loading plugins from /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 50 files
loading plugin /usr/lib64/deadbeef/aac.so
loading plugin /usr/lib64/deadbeef/adplug.so
loading plugin /usr/lib64/deadbeef/alac.so
loading plugin /usr/lib64/deadbeef/alsa.so
loading plugin /usr/lib64/deadbeef/artwork.so
loading plugin /usr/lib64/deadbeef/cdda.so
loading plugin /usr/lib64/deadbeef/converter.so
loading plugin /usr/lib64/deadbeef/converter_gtk3.so
loading plugin /usr/lib64/deadbeef/dca.so
loading plugin /usr/lib64/deadbeef/ddb_dumb.so
loading plugin /usr/lib64/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib64/deadbeef/ddb_shn.so
loading plugin /usr/lib64/deadbeef/dsp_libsrc.so
loading plugin /usr/lib64/deadbeef/ffap.so
loading plugin /usr/lib64/deadbeef/ffmpeg.so
loading plugin /usr/lib64/deadbeef/flac.so
loading plugin /usr/lib64/deadbeef/gme.so
loading plugin /usr/lib64/deadbeef/hotkeys.so
loading plugin /usr/lib64/deadbeef/in_sc68.so
loading plugin /usr/lib64/deadbeef/lastfm.so
loading plugin /usr/lib64/deadbeef/m3u.so
loading plugin /usr/lib64/deadbeef/mms.so
loading plugin /usr/lib64/deadbeef/mp3.so
loading plugin /usr/lib64/deadbeef/musepack.so
loading plugin /usr/lib64/deadbeef/notify.so
loading plugin /usr/lib64/deadbeef/nullout.so
loading plugin /usr/lib64/deadbeef/opus.so
loading plugin /usr/lib64/deadbeef/oss.so
loading plugin /usr/lib64/deadbeef/pltbrowser_gtk3.so
loading plugin /usr/lib64/deadbeef/psf.so
loading plugin /usr/lib64/deadbeef/pulse.so
loading plugin /usr/lib64/deadbeef/rg_scanner.so
loading plugin /usr/lib64/deadbeef/shellexec.so
loading plugin /usr/lib64/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib64/deadbeef/sid.so
loading plugin /usr/lib64/deadbeef/sndfile.so
loading plugin /usr/lib64/deadbeef/supereq.so
loading plugin /usr/lib64/deadbeef/tta.so
loading plugin /usr/lib64/deadbeef/vfs_curl.so
loading plugin /usr/lib64/deadbeef/vfs_zip.so
loading plugin /usr/lib64/deadbeef/vorbis.so
loading plugin /usr/lib64/deadbeef/vtx.so
loading plugin /usr/lib64/deadbeef/wavpack.so
loading plugin /usr/lib64/deadbeef/wildmidi.so
loading plugin /usr/lib64/deadbeef/wma.so
starting plugin GTK3 user interface
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter GTK3 UI
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin OSD Notify
starting plugin Null output plugin
starting plugin Opus player
starting plugin OSS output plugin
starting plugin Playlist browser GTK3
starting plugin PSF player using Audio Overload SDK
starting plugin PulseAudio output plugin
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec GTK3 UI
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
starting plugin FFMPEG audio player
streamer_set_output
selected output plugin: PulseAudio output plugin
INFO: from file /home/username/.config/deadbeef/playlists/0.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/1.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/2.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/3.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/4.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/5.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/6.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/7.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/8.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/9.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/10.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/11.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/12.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/13.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/14.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/15.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/16.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/17.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/18.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/19.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/20.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/21.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/22.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/23.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/24.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/25.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/26.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/27.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/28.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/29.dbpl
INFO: from file /home/username/.config/deadbeef/playlists/30.dbpl
resume: track 86 pos 66.177155 playlist 8
Failed to play track: /run/media/username/path_to_track/track_name.mp3
gtkui plugin compiled for gtk version: 3.24.1
Segmentation Fault
backtrace() returned 5 addresses
deadbeef(+0x5ea6a) [0x55824bb4fa6a]
/lib64/libc.so.6(+0x38600) [0x7f5f14b9f600]
deadbeef(+0x5099a) [0x55824bb4199a]
/lib64/libpthread.so.0(+0x858e) [0x7f5f14d3558e]
/lib64/libc.so.6(clone+0x43) [0x7f5f14c64683]

### Information about the software:

Deadbeef version: 1.8.0 (reproducible in both a static build from website and a version from OS repository)
OS: Fedora 29 x86_64

**Comment by kuba160** [comment]
I can confirm the issue on master. Only relevant when "Resume previous session on startup" is enabled.

Backtrace:
```
Failed to play track: /media/kuba/PATRIOT/Music/test.mp3
[New Thread 0x7fffdd42d700 (LWP 5588)]
[New Thread 0x7fffdcc2c700 (LWP 5589)]
[New Thread 0x7fffb3fff700 (LWP 5590)]
[New Thread 0x7fffb37fe700 (LWP 5591)]

Thread 5 "deadbeef-stream" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdfc32700 (LWP 5583)]
0x0000555555599a2e in streamer_seek_real (seekpos=<optimized out>) at streamer.c:1338
warning: Source file is more recent than executable.
1338	            if (fileinfo->plugin->seek (fileinfo, playpos) >= 0) {
(gdb) bt
Thread 5 (Thread 0x7fffdfc32700 (LWP 5583)):
#0  0x0000555555599a2e in streamer_seek_real (seekpos=<optimized out>) at streamer.c:1338
#1  0x0000555555599a2e in streamer_thread (unused=<optimized out>) at streamer.c:1488
#2  0x00007ffff761b6db in start_thread (arg=0x7fffdfc32700) at pthread_create.c:463
#3  0x00007ffff734488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
