### ISSUE TITLE
Manually playing a track in shuffle album mode doesn't mark previous tracks as played

### ISSUE THREAD

**Issue by RobertZenz** [DeaDBeeF-Player/deadbeef#2123]
The "Next" action (invoked through the GUI or through a hotkey) behaves quite oddly since the update to 1.8.

It works normally until you select a different song in the playlist through the mouse, pressing "Next" then jumps back to the previously "next" song.

Assume the following album:

 1. A
 2. B
 3. C
 4. D

Now A is starting to play:

 1. \> A
 2. B
 3. C
 4. D

Pressing "Next" at this point will work normally. However, if we now select and play C:

 1. A
 2. B
 3. \> C
 4. D

Pressing "Next" will jump to B:

 1. A
 2. \> B
 3. C
 4. D

More curiously, pressing "Next" again will jump us to D:

 1. A
 2. B
 3. C
 4. \> D

**Comment by Alexey-Yakovenko** [comment]
Are you sure that you don't have shuffle or random enabled?
This issue is not happening here.

**Comment by RobertZenz** [comment]
I had "Shuffle Albums" enabled.

**Comment by Alexey-Yakovenko** [comment]
OK, In shuffle albums, the order of playback is predetermined, so it still seems to work as designed.

**Comment by RobertZenz** [comment]
Could you explain that a little more? Because in 0.7.2 it behaves as I'd expect with the same settings, I'm only seeing this in 1.8.

**Comment by Alexey-Yakovenko** [comment]
Hmm.. I just re-tested the case with shuffle albums. It doesn't behave as designed.
Needs fixing. Thanks for getting back with this.

**Comment by RobertZenz** [comment]
Glad to hear you could reproduce it.
