### ISSUE TITLE
Top-bar icons bad contrast

### ISSUE THREAD

**Issue by riidom** [DeaDBeeF-Player/deadbeef#2126]
Deadbeef version: 1.8.0
OS: Kubuntu 18.04

Due to my theme, the icons in the topbar (play, pause, stop, next, prev etc.) have a bad contrast, I would like to change them.
My problem is, I don't know where to look for them, and if it's possible to place my version somewhere in ~/.config/deadbeef or if I have to overwrite the original ones and deal with it each update.
Lastly, are you interested in a PR about differently shaded icons?

**Comment by Alexey-Yakovenko** [comment]
Nothing to do with deadbeef, it's just using system icons.
Change your system icons - and they will change in all applications.
