### ISSUE TITLE
The main program cannot be called up

### ISSUE THREAD

**Issue by yanhuacuo** [DeaDBeeF-Player/deadbeef#2127]
I Compile the latest code in the Ubuntu19.04 succeed,but it doesn't work 

:(

**Comment by yanhuacuo** [comment]
the deadbeef-portable can't work too:

$ ./deadbeef
$ deadbeef devel [static] [portable]

The main program cannot be called up

**Comment by Alexey-Yakovenko** [comment]
Cool, please report this to ubuntu devs.
