### ISSUE TITLE
Horizontal scrollbar covers the bottom playlist name in playlist browser

### ISSUE THREAD

**Issue by ph0boss** [DeaDBeeF-Player/deadbeef#2128]
### Steps to reproduce the problem
1. Add several playlists to the playlist browser. The number of playlists should be big enough to not fit entirely into the playlist browser, so that a vertical scrollbar appears
2. At least one of the playlists should have a long enough name to not fit entirely, so that a horizontal scrollbar appears at the bottom
3. Hover mouse over the playlist browser
4. The playlist name at the bottom becomes covered by a scrollbar and it is temporarily impossible to click on it. 

### What's going on? Describe the problem in as much detail as possible.
Screenshot is attached.
![Screenshot_20190419_132909](https://user-images.githubusercontent.com/19243265/56421376-df30f200-62aa-11e9-913f-8d9484807c11.png)

### Information about the software:

Deadbeef version: 1.8.0
OS: Fedora 29 x86_64, KDE Plasma 5.15

**Comment by Alexey-Yakovenko** [comment]
can you try without kde? is it the same?

**Comment by Alexey-Yakovenko** [comment]
The scrollbars in GTK are supposed to overlap the content.
However they are tiny and doesn't obstruct the content, until mouse hovers over them.
I think the problem you're experiencing is KDE trying to render GTK elements in its own way, and doing it wrong.

This is what it looks like without KDE

Scrollbar is tiny and unobtrusive while mouse is away from it:

![image](https://user-images.githubusercontent.com/1895698/56425271-c842cd80-62b3-11e9-9d07-e6ce4c9735a3.png)

Then becomes clickable only if mouse is over it:

![image](https://user-images.githubusercontent.com/1895698/56425290-dee92480-62b3-11e9-8355-873d31108cda.png)

And everything is still perfectly clickable:

![scrollbar](https://user-images.githubusercontent.com/1895698/56425327-0cce6900-62b4-11e9-831e-e51b71f3b64b.gif)

**Comment by Alexey-Yakovenko** [comment]
Also, this is not something that's controlled by deadbeef, so if you think it's a bug -- it probably exists in all GTK applications on KDE, which have a scrollable list.
