### ISSUE TITLE
Disable behavior jump to next track on error 

### ISSUE THREAD

**Issue by pdanc** [DeaDBeeF-Player/deadbeef#2132]
### Steps to reproduce the problem
DeaDBeeF jump to next track when audio file has scratches or origin errors 

### What's going on? Describe the problem in as much detail as possible.
I ripped my old CD collection, and I have some ungly CD's with scratches. Well, is impossible find similar CD's (local rock bands) and I give up and admit audio files with errors, so when I listen some audio file, DeaDBeef jump to next track when detect error, but in spite of its errors  it is still audible track.

On VLC I can hear complete track despite the errors, but my favorite music player is DeaDBeef. So, How to disable the 'jump' behavior?

### Information about the software:

Deadbeef version: 1.8.0
OS: Ubuntu 18.04

**Comment by Alexey-Yakovenko** [comment]
A digital file can only have a scratch if you physically damage the media on which it is located.
If you have some files which don't play to the end -- the best course of action is to contact me by email, and provide a test file.

**Comment by Alexey-Yakovenko** [comment]
Support for ignoring FLAC stream errors has been added via commit 1821527bc47326c5b5ab1661f45947107b0d65dc
