### ISSUE TITLE
"Next track" menu item / hotkey repeats current track when repeat is set to "One Track"

### ISSUE THREAD

**Issue by usrshare** [DeaDBeeF-Player/deadbeef#2136]
### Steps to reproduce the problem
* Set the "Playback -> Repeat" option to "One Track"
* Use the "Next track" hotkey or toolbar button

### What's going on? Describe the problem in as much detail as possible.
* Instead of switching to the next track in the playlist, the current track repeats playing.
(The "Previous track" hotkey / toolbar button works as expected)

### Information about the software:

Deadbeef version: v1.8.0
OS: Alpine Linux

**Comment by Alexey-Yakovenko** [comment]
It sounds more like the Previous track is not quite working as expected :)
I will have to double-check though.

**Comment by Alexey-Yakovenko** [comment]
You are correct, the behavior is wrong.
