### ISSUE TITLE
Noise and interrupted playback via ALSA after trying to play deleted file

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2138]
### Steps to reproduce the problem
Step 1:
Create a new playlist, copy a folder with songs somewhere and paste them into the playlist. Set Shuffle off in DeaDBeeF to play the next song.
Select a song that runs longer than the next one. Delete the following (shorter) song from the directory, but not from the playlist!

Step 2:
Play the long song (you can jump with the mouse shortly before the end of the song), next comes a protocol message "Failed to play track: xxx". After that BeaDBeeF plays the song after next, but the playback is somehow hacked. It can also be recognized by the fact that the blue slider remains completely blue and is not reset.
The error doesn't occur if you click on the missing track directly. If the error cannot be reproduced immediately, restart BeaDBeeF and try again, it may take a few tries. It can also occur if the following song is longer, but the error does not always occur and the slider is set to the value of the previous song.

### What's going on? Describe the problem in as much detail as possible.
The playback of the song being played, under the above conditions, does not start from the beginning and the playback is in some way fragmented, difficult to describe. If necessary I can also make a screencast.

### Information about the software:
Deadbeef version:  DeaDBeeF 1.8.1 beta 2
OS: Antergos Linux

**Comment by Alexey-Yakovenko** [comment]
I could not reproduce the issue as you described, but I found some other issue under the same conditions and applied a fix. Could you verify if it's still happening to you on latest master?

**Comment by kpcee** [comment]
Many thanks for the very quick answer and for the patch. I downloaded the new version and the problem is partly fixed. The blue slider works as it should, but the music is still broken.
If I can hear that correctly, the effect is like playing the song for 2-3 seconds and then DeaDBeeF jumps a few seconds further which sounds very jagged. Playback ends prematurely and DeaDBeeF stops.

A smaller thing that I also noticed is that if you double click on the song that was deleted, there is a noise before DeaDBeeF jumps to the next song and plays the song. Not nice, but no big problem either.

**Comment by Alexey-Yakovenko** [comment]
Which output plugin do you have selected in preferences?

**Comment by kpcee** [comment]
Default ALSA Output (currently PulseAudio Sound Server) is selected. Plugin is empty.

**Comment by Alexey-Yakovenko** [comment]
I'm out of time for today to investigate this, but I hope I'll have some during the next week.

**Comment by kpcee** [comment]
Okay no problem and thanks for the quick help.
