### ISSUE TITLE
[Regression] Layout broken on startup

### ISSUE THREAD

**Issue by orbea** [DeaDBeeF-Player/deadbeef#2139]
### Steps to reproduce the problem

Start deadbeef with a layout that uses splitters.

### What's going on? Describe the problem in as much detail as possible.

When starting deadbeef with a layout that uses splitters it will forget the layout used when last closed.

I bisected this and found the first bad commit.
```
6a91aa7460d2f68c155ab0f9213b2b95b82477c0 is the first bad commit
commit 6a91aa7460d2f68c155ab0f9213b2b95b82477c0
Author: Alexey Yakovenko <wakeroid@gmail.com>
Date:   Tue Apr 23 20:47:31 2019 +0200

    gtkui: fixed regression in loading layouts with splitters

:040000 040000 0980d59115d2fbd794b502036c1c06af58513a59 f2f78950b8f921fd288df94e7a98274194a24629 M	plugins
```
6a91aa7460d2f68c155ab0f9213b2b95b82477c0

Here are some images that hopefully illustrate the issue.

How deadbeef looks before closing.
![before](https://i.imgur.com/pL2hekp.png)

How deadbeef looks after starting again.
![after](https://i.imgur.com/32t0YO6.png)

### Information about the software:

Deadbeef version: https://github.com/DeaDBeeF-Player/deadbeef/commit/a48741c859293fb4999447e29f0c350039a3cdf9
OS: `Slackware64-current`

**Comment by Alexey-Yakovenko** [comment]
> Start deadbeef with a layout that uses splitters.

This is not a repro.
There's an infinite number of ways to create layouts with splitters.
I recreated the layout as close as possible to what I see on your screenshot, and it gets loaded fine after restarting the player.

If you correct the problem in design mode and restart the player, does layout break again?
Did you create the layout in 1.8.0, or before that like in 0.7.2?

Here's a screenshot of the layout with splitters which works fine here:

![image](https://user-images.githubusercontent.com/1895698/57208693-77cab000-6fd5-11e9-8439-099e191808ac.png)

**Comment by orbea** [comment]
> This is not a repro.

Sorry, I am not sure exactly as I made this layout a long time ago, maybe sometime in 2015 based on issue https://github.com/DeaDBeeF-Player/deadbeef/issues/1432.

> If you correct the problem in design mode and restart the player, does layout break again?

Yes.

**Comment by Alexey-Yakovenko** [comment]
Then I will need you to send me your layout, to investigate.
it's stored in the config file, should be pretty easy to spot.

**Comment by orbea** [comment]
I have attached my `~/.config/deadbeef/config` file which seems to be the only one that could be relevant.

[config.txt](https://github.com/DeaDBeeF-Player/deadbeef/files/3148148/config.txt)

**Comment by Alexey-Yakovenko** [comment]
Thanks, I've been able to reproduce the issue.

**Comment by orbea** [comment]
@Alexey-Yakovenko Thanks, but I tested the current master (https://github.com/DeaDBeeF-Player/deadbeef/commit/5c68f92bb2ba7f471ed4528cf7be9eb8cd42084e) and found no difference. It still does not recall my layout and will squish the splitters with the spectrum, playlists and cover art.

**Comment by Alexey-Yakovenko** [comment]
Version 1.8.0 may corrupt some layouts made with older versions, so they won't come back to normal, and it's impossible to auto-recover. However, if you resize the panes of the wrong size, they should stay at the correct size after restart from now on.

**Comment by orbea** [comment]
I did try to correct the pane sizes both with and without design mode and it did not help unfortunately.

**Comment by Alexey-Yakovenko** [comment]
that's strange then. I can't reproduce it anymore again, but I'll do it again next weekend.

**Comment by orbea** [comment]
Thanks again! I can now confirm its fixed for me too.

**Comment by orbea** [comment]
@Alexey-Yakovenko Unfortunately it seems this issue is not entirely fixed yet. While it now recalls my layout when restarting deadbeef, the horizontal splitter between the spectrum and playlists is now forgotten after resizing the deadbeef window sometimes. I don't think this can be reproduced without running deadbeef for at least several hours, maybe longer.

Note that my tiling window manager has deadbeef resizing vertically every time I open a new terminal, but it rarely resizes horizontally.

![new_issue](https://i.imgur.com/CrEqL4j.png)

**Comment by Alexey-Yakovenko** [comment]
I won't be able to reproduce this, but I came up with a new much better idea how to fix this matter, so please try the latest version. I think it preserves the layout much more reliably, while still preventing it from breaking widget constraints.

**Comment by orbea** [comment]
I tried the current master (https://github.com/DeaDBeeF-Player/deadbeef/commit/fd16773638401ce5cf254532b252c30dcb5933ab) and so far it seems good. I'll close this for now and let you know if it fails again the in future. :)
