### ISSUE TITLE
DSD wrong sampling rate

### ISSUE THREAD

**Issue by B1tl0rd** [DeaDBeeF-Player/deadbeef#2144]
Hi.
DSD files, incorrect data in sample rate
http://www.2l.no/hires/index.html
file: http://www.lindberg.no/hires/test/2L-106/2L-106_stereo-11289k-1b_04.zip
Mediainfo
Sampling rate : 11.3 MHz
DeaDBeeF
Sampling rate : 1411200 (%samplerate%)
Deadbeef version: deadbeef-git r8454.dd17cab7c-1
OS:ArchLinux

**Comment by Alexey-Yakovenko** [comment]
Deadbeef decodes DSD files, and therefore obtains the samplerate, using ffmpeg library.
If you believe that ffmpeg reports wrong samplerate for this file -- please report this issue to ffmpeg developers.

**Comment by B1tl0rd** [comment]
Thank you
forget there is another wrong data.
Bit depth : 32 bits ( $meta(:bps) bit)

**Comment by Alexey-Yakovenko** [comment]
This has already been reported, see #2012
