### ISSUE TITLE
Track change but no jump

### ISSUE THREAD

**Issue by eblanca** [DeaDBeeF-Player/deadbeef#2145]
### Steps to reproduce the problem
I created a shiny new playlist, loaded a .cue file, it links to a .ogg file. Then play it.

### What's going on? Describe the problem in as much detail as possible.
Play the very first track, once it reaches the end, the highlighted selection doesn't follow the next track and even the status bar gets updated incorrectly.
![Schermata a 2019-05-18 13-08-02](https://user-images.githubusercontent.com/1640886/57968831-10671580-7970-11e9-9b4b-1cb9eda422d2.png)
Please note that the same issue appears also when I load more than one cue sheets in the same playlist (so, the first track of the new cue sheet is not the first track of the playlist), that is, the selection does not follow the next track and the time counter increases over the real track duration.

### Information about the software:

Deadbeef version: branch 1.8, git commit 15c9af499705dd304aea34119a72a0e35a000d9d built using gtk2 gui (gtk2-2.24.31), libvorbis 1.3.5-4+deb9u2 (I don't really think this is relevant, anyways)
OS: LMDE3 x64, gcc 6.3.0, binutils 2.28.

I just noticed a further detail: when I play a playlist loaded in the very same way (cue sheet -> vorbis encoded content) BUT created a long time ago with a previous deadbeef version, this bug doesn't appear. I can replicate this.

**Comment by Alexey-Yakovenko** [comment]
What would be really useful is if you have attached the cuesheet itself. Thanks.

**Comment by eblanca** [comment]
[Emerson, Lake & Palmer - 1970 - Emerson, Lake & Palmer.cue.txt](https://github.com/DeaDBeeF-Player/deadbeef/files/3194252/Emerson.Lake.Palmer.-.1970.-.Emerson.Lake.Palmer.cue.txt)

**Comment by eblanca** [comment]
Just forgot to mention: this bug ONLY raises when playing the first track of a cue sheet.
Both repeat and shuffle are OFF (that is, track 01 then track 02 and so on).

**Comment by eblanca** [comment]
Here I packed together a .cue file and two .dbpl files, both generated from this same cue sheet.
The older 0.dbpl was generated loading the cue sheet on 2016 october 8 by an up-to-date deadbeef snapshot. This playlist NEVER shows the bug.
The latter was generated a few minutes ago with latest code from 1.8 branch. This ALWAYS shows the bug.
They differ, isn't this weird?
[playlists.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/3220340/playlists.zip)

**Comment by Alexey-Yakovenko** [comment]
It's not weird at all -- there were many changes about what deadbeef writes to playlists.

**Comment by Alexey-Yakovenko** [comment]
Bug confirmed. Seems to be vorbis-specific (doesn't happen with other formats).

**Comment by Alexey-Yakovenko** [comment]
First bad commit according to bisect bb608662a1533e0c0a09397547935f1698dc98c1

**Comment by eblanca** [comment]
Thank you!

**Comment by Alexey-Yakovenko** [comment]
You are welcome! however, there has been an unfortunate regression in the opus playback caused by this change. I hope I'll have time to fix it today.
