### ISSUE TITLE
APE unplayable when using ffmpeg

### ISSUE THREAD

**Issue by shoober420** [DeaDBeeF-Player/deadbeef#2157]
### Steps to reproduce the problem

Add .ape extension to the ffmpeg plugin list

### What's going on? Describe the problem in as much detail as possible.

Deadbeef cannot playback APE using the ffmpeg plugin

Deadbeef version: Latest git
OS: Arch 64bit

This also happens when using the cmus music player.

https://github.com/cmus/cmus/issues/812

Here is the terminal output when playing back APE files with deadbeef using the ffmpeg plugin.

[ape @ 0x7fd9fc08d840] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc08d840] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc02c2c0] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc02c2c0] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc034a80] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc034a80] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc049740] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc049740] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc049740] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc049740] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc0421c0] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc0421c0] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc0b8b40] Got unexpected packet size after a partial decode
[ape @ 0x7fd9fc0b8b40] Got unexpected packet size after a partial decode

**Comment by Alexey-Yakovenko** [comment]
what about ffplay?
why do you even need to play ape using deadbeef via ffmpeg?

**Comment by Alexey-Yakovenko** [comment]
Long story short: ffmpeg plugin is present in deadbeef with the purpose of playing a few formats, which are not supported otherwise. They are configured in the ffmpeg file extension list by default, and support for them is included in deadbeef binaries. Any other formats are not guaranteed to work, and this is why they are disabled and not included in the binaries. You're welcome to use the provided standard ape plugin in deadbeef, which is well supported, and will play the ape files just fine.

**Comment by shoober420** [comment]
I tested the ape file with ffplay, and it works fine.

I understand you feel the standard ape plugin is adequate, but I have a minimal deadbeef install, and it doesnt install every single deadbeef plugin, the ape plugin being one of them. For a couple reasons, you may consider supporting ape through ffmpeg.

One would be for people who have a minimal deadbeef install, like me, and dont have all the deadbeef plugins install, because bloat. Another being ffmpeg is still maintained and updated, so its still active, unlike the standard ape plugin. One more being it would lessen the size and up keep of your project, and you could have it as an optional third party plugin, similar to how foobar does plugins.

Even if you dont desire some of those reasons, could you please look into supporting ape playback through ffmpeg?

**Comment by Alexey-Yakovenko** [comment]
Very unlikely. Not because I'm evil or whatever, but because my backlog is huge, and pretty much anything in it is higher priority / importance than fixing ffmpeg plugin.

**Comment by Alexey-Yakovenko** [comment]
> Another being ffmpeg is still maintained and updated, so its still active, unlike the standard ape plugin.

What made you write this false information?

**Comment by shoober420** [comment]
Whoops, I thought the ape decoder hadn’t been touched since like 2009. I just visited the site and saw it is indeed maintained, at least the windows side. My apologies.

**Comment by Alexey-Yakovenko** [comment]
APE decoders in deadbeef and ffmpeg are based on the same code by Dave Chapman from 2007.
The code used in deadbeef is getting regular updates as needed.

**Comment by shoober420** [comment]
In case someone has the same issue (very unlikely), I found a workaround. You can convert ape to flac using ffmpeg. The command would be as follows.

ffmpeg -i poop.ape poop.flac

You can do wav too if one so desires.
