### ISSUE TITLE
FLAC metadata: "Album Artist" should be defined by the "ALBUMARTIST" field

### ISSUE THREAD

**Issue by Hasshu** [DeaDBeeF-Player/deadbeef#2162]
DeaDBeeF v1.8.1

See also #2118

**Comment by Alexey-Yakovenko** [comment]
sorry I didn't notice this case was present, and didn't mention it in the commit.
It's fixed now in the commit 495c32593508921d7df9e366e39726486b296bdf

**Comment by Hasshu** [comment]
@Alexey-Yakovenko No worries. Thanks.
