### ISSUE TITLE
WavPack DSD playback does not playback at correct (PCM) samplerate

### ISSUE THREAD

**Issue by qwertycian** [DeaDBeeF-Player/deadbeef#2165]
### Steps to reproduce the problem
1. Disable any resampling globally, for example in PulseAudio config, so that all files are decoded by the sound device in their native samplerate.
2. Play PCM file of any type (flac, mp3, WavPack, etc.) and remember its samplerate. For example a CD rip will be 44.1 kHz and the DAC will get a 44.1 kHz stream. If the PCM file is 96 kHz, the DAC receives a 96 kHz stream. This works well.
3. Then play a WavPack DSD file, which will be converted on-the-fly to PCM by the WavPack decoder and sent to soundcard / DAC, and check which samplerate the DAC receives. This will always be the same samplerate as the last PCM file you played.
If the previous PCM file was a CD rip (44.1 kHz), the DSD file will be played as a 44.1 kHz PCM file. If the previous PCM track was not a CD rip, but a digital download with a 96 kHz samplerate, then the WavPack DSD will be played back as 96 kHz PCM stream. 
This is not how it should be. Expected behaviour would be that WavPack DSD files are always converted to a certain PCM samplerate, regardless of what was played before.
If the WavPack DSD file is the first file DeaDBeeF plays, it appears 44.1 kHz is chosen.

### What's going on? Describe the problem in as much detail as possible.
As far as I know, the built-in DSD-to-PCM conversion of WavPack should always output a 24 bit 352.8 kHz stream. It appears DeaDBeeF is resampling this. When switching between PCM files with different samplerates, DeaDBeeF always succesfully sends the stream in the correct samperate to the DAC. However, when switching to a WavPack DSD file, it does not, and uses the previously used samplerate, whichever that was.
**DSD playback should always happen at a certain PCM samplerate. This samplerate should be 352.8 kHz.**
I understand that not all devices support 352.8 kHz, and hence for compatibility reasons a lower samplerate could be chosen, such as 176.4 kHz or 88.2 kHz. However, the previous track certainly should not be influencing at what samplerate the DSD file is played.
I think the best solution would be to use 352.8 kHz by default, but for example add a small configuration window to the WavPack plugin where this could be set lower (or in the future be set to DoP output, who knows!).

### Information about the software:

Deadbeef version: 1.8.0 (from openSUSE repo)
OS: openSUSE Tumbleweed

**Comment by Alexey-Yakovenko** [comment]
What makes you think that this behavior has anything to do with wavpack at all? Have you tried playing a file in any other format at 352.8KHz? It all sounds more like a general issue, unrelated to wavpack.

**Comment by qwertycian** [comment]
Yes you are right, I am so sorry! It appears there is a problem with my setup: it will not output anything over 192 kHz, even though my DAC supports it. It used to work back in the (Windows?) days, but not anymore. I had assumed this would still work as it always did.

I have made a PCM test file with a 352.8 kHz and it shows the same problem. When using the ALSA output plugin, the previous samplerate is used because the system thinks 352.8 kHz is unsupported, I guess. When using the PulseAudio output plugin, the samplerate is set to 192 kHz and the test file is played back at half speed as a result. Interestingly, the WavPack DSD files are played back at 44.1 kHz when using the PulseAudio output plugin, not what I'd expect. I'd expect them to also be played back at 192 kHz at slower speed.

Anyway, I will be diving into ALSA and PulseAudio setup (great...), and you may close this 'issue'. Sorry again for wasting your time!

**Comment by qwertycian** [comment]
It works now. This is the solution:
1. Use ALSA output plugin.
2. Create file called .asoundrc in home directory
3. Enter the following into the file (depending on if your DAC is indeed at hw:1,0 like mine is):
```
pcm.device{
    type hw
    card 1
    device 0
}

pcm.!default{
    type plug
    slave.pcm "device"
}
```
4. Enjoy seemless samplerate switching up to and including 352.8 kHz, no matter the filetype.

I don't know why it is now suddenly possible to get a 352.8 kHz stream to the DAC, because the above doesn't really do anything as far as I know, just point into the right direction. I already had sound though, so the right direction was already known.
