### ISSUE TITLE
Selection properties gui module: Colors not customizable

### ISSUE THREAD

**Issue by bcoolumbo** [DeaDBeeF-Player/deadbeef#2166]
Colors for background and fonts of the selection properties module are not customizable by user. This looks ugly with a dark theming.
I can customize the colors for the playlist, the filebrowser plugin, the VU plugin and the spectrum plugin to have a dark background - but not for the selection (track) properties.
Deadbeef version: Deadbeef devel
OS: Linux

**Comment by Alexey-Yakovenko** [comment]
There's no UI to customize it, but since it is using standard GTK widgets -- you can customize it via using a dark GTK theme.
