### ISSUE TITLE
Customizable disk cache size

### ISSUE THREAD

**Issue by fightingdreamer** [DeaDBeeF-Player/deadbeef#2167]
### Steps to reproduce the problem
Play music from NAS over internet.

### What's going on? Describe the problem in as much detail as possible.
DeadBeef sometimes pause playing for a second, probably when cache drop to zero.
NAS connection have high latency, bandwidth is not a issue.

### Proposed solution:
Customize cache size.

### Information about the software:
Deadbeef version: Version 1.0 (fd16773) (latest build for OSX)
OS: MacOS 10.13.6

**Comment by Alexey-Yakovenko** [comment]
Which cache size are you talking about?

**Comment by Alexey-Yakovenko** [comment]
I think I understand your problem, but I don't think that deadbeef has a cache for that.
It doesn't copy the files before playback, and I'm assuming that when you're playing from a NAS - it's like mounted smb volume or something, and the files are cached by the OS. Obviously, if the OS couldn't cache the file quick enough -- there would be a stutter.
But it's not something that deadbeef is aiming to solve. If you want different kind of performance - you should be looking into how the OS is caching the files when getting them from NAS.
