### ISSUE TITLE
Getting location track info

### ISSUE THREAD

**Issue by mrgreen3** [DeaDBeeF-Player/deadbeef#2171]
### Steps to reproduce the problem
Add location url 
### What's going on? Describe the problem in as much detail as possible.

On loading location I get the first track name then radio station carries on playing but track never gets updated again unless restarted....

Url I use is

http://hi5.death.fm

### Information about the software:
Just love it....

Deadbeef version: 0.7.2
OS: Arch Linux

**Comment by Alexey-Yakovenko** [comment]
0.7.2 is not going to get any updates, and I believe the current release already has this issue fixed.

**Comment by mrgreen3** [comment]
Odd Arch is showing 0.7.2.,,,,sorry its flagged out of date... sorry for the noise!
