### ISSUE TITLE
Shortcuts for seeking forward and backward may seek out of bounds, and prevent switching to next track

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2174]
I found two little things again, nothing serious. If you use shortcuts for Seeking Forward +1 or +5%, you can jump outside the play time of the song. This happens because the function `void streamer_set_seek (float pos)` in the file streamer.c does not check whether the pos passed is outside of the play time.

You can fix the problem by commenting out the line `last_seekpos = pos;` (I couldn't find any disadvantages) or you can move the line to the function `static void streamer_seek_real (float seekpos),` which is started later but where there is a length check and in most cases the variable is set to -1 anyway.

The second thing is the status bar. If you jump within a playing song, the text of the statusbar will also hop, this also happens when changing a song. I don't know if it's easy to fix this, but it shouldn't be a problem to let the text of the status bar always be the same length by placeholders and thus prevent this jumping of the text. I inserted a picture for better understanding.  

![Unbenannt](https://user-images.githubusercontent.com/39984895/61588706-6b9bcb00-aba0-11e9-8a21-97aa4a1b6adf.png)

**Comment by Alexey-Yakovenko** [comment]
Please report the 2nd issue as a separate case. Although I don't think it's easily fixable or fixable at all. Sounds more like a design change to make status bar use fixed-width font and add placeholders into it.

**Comment by Alexey-Yakovenko** [comment]
Regarding the 1st issue -- what exactly happens when the jumping outside of play time occurs?
Is there any visible or audible outcome?

**Comment by kpcee** [comment]
If you press the shortcut fast enough, you can only see it at the status bar, I took a screenshot. A side effect is that Deadbeef doesn't automatically switch to the next track as long as you press the shortcut fast enough. This might be an idea to switch to the previous or next song if you jump to the position <= 0 or greater of the playing time. 
![Pic](https://user-images.githubusercontent.com/39984895/61695896-9b7bd780-ad34-11e9-87cd-65c6ebdc2693.png)

**Comment by Alexey-Yakovenko** [comment]
ok thanks

**Comment by Alexey-Yakovenko** [comment]
I fixed the out of bounds seeking issue. Adding functionality to skip to previous / next track in those cases is quite complex, and won't be done as part of this fix.
