### ISSUE TITLE
The length of the text of the status bar changes when using the seekbar

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2175]
When you use the seekbar, the length of the statusbar changes and the text hops back and forth, because the kbps value is temporarily missing. Also happens when jumping to the next song.
![Unbenannt](https://user-images.githubusercontent.com/39984895/61588706-6b9bcb00-aba0-11e9-8a21-97aa4a1b6adf.png)

**Comment by Alexey-Yakovenko** [comment]
In this particular case, the jumping occurs because immediate bitrate is not known for a short time period after seeking, since it gets reset. The jumpiness also occurs when bitrate changes.
Related issue: #1462

**Comment by Alexey-Yakovenko** [comment]
Closing because it's not actionable. The fields can have fairly arbitrary sizes, and one way or another they have to change to fit the text.
