### ISSUE TITLE
Synchronize current playlist with directory

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2176]
One very important thing for me is missing in Deadbeef at the moment, namely that you can synchronize playlists with directories and its subdirs, so new songs are recorded and deleted songs are removed.

I have implemented this function and wanted to ask if something like this could be taken over into Deadbeef or better as a plugin? I haven't tried it yet, but it should also work as a plugin. 

I solved this so that the user can select a directory and it will be read, new songs will be passed to Deadbeef and deleted songs will be removed from the playlist. Modified files or tags are not taken into account.

**Comment by Alexey-Yakovenko** [comment]
duplicates #654

**Comment by Alexey-Yakovenko** [comment]
Sorry, I didn't read to the end at first, since I'm not used to use github issue tracker as a messenger, and I have to filter quite a lot of dupes.
I don't know whether your code can be accepted into deadbeef or not. The only way to find out is to make a PR.
If it works as a plugin - it's even better. Just release it as a standalone, nobody can stop you from doing it.

**Comment by kpcee** [comment]
I post the code here, because it's not very long and a PR would do me a lot of work, because the changes in the GUI are still hardcoded and not realized with Glade.
Would these additions be okay or just a plugin? If it was okay, I'd do a PR.

I have made some other changes that extend the ReplayGain scanner and an automatic sorting when adding new files, how can we best discuss that?

```
// Sync playlist with directory
GSList *
get_files(const gchar *dir_path) {

    GSList *fpaths = NULL;
    GSList *dirs = NULL;
    DIR *cdir = NULL;
    struct dirent *cent = NULL;
    struct stat cent_stat;
    gchar *dir_pdup;

    if (dir_path == NULL) {
        return NULL;
    }

    dir_pdup = g_strdup ((const gchar*) dir_path);
    dirs = g_slist_append (dirs, (gpointer) dir_pdup);
    while (dirs != NULL) {
        cdir = opendir ((const gchar*) dirs->data);
        if (cdir == NULL) {
            g_slist_free (dirs);
            g_slist_free (fpaths);
            return NULL;
        }
        chdir ((const gchar*) dirs->data);
        while ((cent = readdir(cdir)) != NULL) {
            lstat (cent->d_name, &cent_stat);
            if (S_ISDIR (cent_stat.st_mode)) {
                if (g_strcmp0 (cent->d_name, ".") == 0 ||
                        g_strcmp0 (cent->d_name, "..") == 0) {
                    continue;
                }
                dirs = g_slist_append (dirs, g_strconcat ((gchar*) dirs->data, "/", cent->d_name, NULL));
            } else {
                fpaths = g_slist_append (fpaths, g_strconcat ((gchar*) dirs->data, "/", cent->d_name, NULL));
            }
        }
        g_free (dirs->data);
        dirs = g_slist_delete_link (dirs, dirs);
        closedir (cdir);
    }
    return fpaths;
}


gboolean
action_sync_playlist_handler_cb (void *data) {
    ddb_playlist_t *plt = deadbeef->plt_get_curr ();
    if (!plt) {
        return FALSE;
    }

    GSList *folder = show_file_chooser (_("Sync folder with playlist..."), GTKUI_FILECHOOSER_OPENFOLDER, FALSE);
    if (!folder) {
        return FALSE;
    }

    GSList *files = get_files (g_slist_last(folder)->data);
    if (!files) {
        return FALSE;
    }

    deadbeef->pl_lock ();
    DB_playItem_t *it = deadbeef->plt_get_first (plt, PL_MAIN);
    GSList* iterator = NULL;

    while (it) {
        DB_playItem_t *next = deadbeef->pl_get_next (it, PL_MAIN);
        const char *uri = deadbeef->pl_find_meta (it, ":URI");
      
        gboolean vanished_file = TRUE;
        for (iterator = files; iterator; iterator = iterator->next) {
            if (strcmp (iterator->data, uri) == 0) {
                files = g_slist_remove_link (files, iterator);
                g_slist_free (iterator);
                vanished_file = FALSE;
                break;
            }
        }
    
        if (vanished_file == TRUE) {
            deadbeef->plt_remove_item (plt, it);
        }

        deadbeef->pl_item_unref (it);
        it = next;
    }

    if (files) {
        gtkui_add_files (files);
    }

    g_slist_free (folder);
    deadbeef->pl_unlock ();
    deadbeef->plt_unref (plt);
    deadbeef->sendmessage (DB_EV_PLAYLISTCHANGED, 0, DDB_PLAYLIST_CHANGE_CONTENT, 0);
    return FALSE;
}


int
action_sync_playlist_handler (DB_plugin_action_t *act, int ctx) {
    gdk_threads_add_idle (action_sync_playlist_handler_cb, NULL);
    return 0;
}
```

**Comment by Alexey-Yakovenko** [comment]
> Would these additions be okay or just a plugin?

I can only answer whether the changes are ok after reading the complete code change and making sure it works, doesn't break any existing functions, and can be disabled if needed.

When you make a PR -- it's expected to be 100% complete and be ready for functional testing, including all of the necessary UI work.

After the feature lands, it's expected to be supported / maintained by the original contributor, unless it's trivial to fix. Otherwise it will get unmerged as soon as something breaks in it, and it becomes unmaintainable.

> I have made some other changes that extend the ReplayGain scanner and an automatic sorting when adding new files, how can we best discuss that?

You can make a PR, this feature of github is specifically designed to review the code and provide feedback. If you want to discuss a change in functionality without looking at the code, you're welcome to join our slack.

**Comment by kpcee** [comment]
My only concern was whether the source code met the general requirements. If not, then I don't need to start a PR first. The source is also complete, otherwise no further changes will be made to the existing source except for the GUI. 
If there are no flaws, then I will do a PR as soon as I have enough time. Have a nice day.

**Comment by Alexey-Yakovenko** [comment]
It's hard to tell whether it meets the requirements without pushing it through the CI pipeline and seeing whether it builds and passes the tests.

I would not use glib in cross-platform code.
But if you're not planning to make this code work on any other platform than Linux / gtkui -- then it should be fine.

**Comment by Alexey-Yakovenko** [comment]
`chdir ((const gchar*) dirs->data);`

This would change the current working directory of deadbeef process, which is a really bad idea to do even temporarily.
So this code definitely needs to be changed to work without using chdir.

**Comment by Alexey-Yakovenko** [comment]
Either way, all of that is supposed to be looked at as part of the pull request, since there's no way to track this feedback in the comments.
