### ISSUE TITLE
Empty metadata on CDImage does not get ignored in favor of using cddb

### ISSUE THREAD

**Issue by circuitikzuser** [DeaDBeeF-Player/deadbeef#2177]
### Steps to reproduce the problem
Create an iso image with k3b containing the metadata.
I verified that Clementine reads accurate metadata for all tracks from the iso served by cdemu.
So the problem is NOT with the iso or cdemu as Clementine reads it from the iso.

### What's going on? Describe the problem in as much detail as possible.

Deadbeef fails to read iso metadata and track and album details in the metadata but can play all tracks in the iso.
As mentioned verified correct metadata is on the iso and can be read with Clementine perfectly.
I also confirmed that audacious reads the metadata from the same isos perfectly.
So this is squarely a deadbeef problem.

### Information about the software:

Deadbeef version: 1.8.1
OS: Linux MX18 

NAME="MX"
VERSION="18 (Continuum)"
ID="mx"
VERSION_ID="18"
PRETTY_NAME="MX 18 (Continuum)"
ANSI_COLOR="0;34"
HOME_URL="https://mxlinux.org"
BUG_REPORT_URL="https://mxlinux.org"
PRETTY_NAME="MX 18.3 Continuum"
DISTRIB_ID=MX
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=Continuum
DISTRIB_DESCRIPTION="MX 18.3 Continuum"
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian

**Comment by Alexey-Yakovenko** [comment]
When you serve a cd image using cdemu, does it appear as a "real" cd drive to deadbeef?
What do you do to open such image in deadbeef?

**Comment by Alexey-Yakovenko** [comment]
Another thing that I need to know: what does it involve to create such an ISO image? Do I need to have a physical CD drive and an actual CD? would it work with any audio CD, or there has to be something special about it? Are we talking about ISO 9660 or something else?

**Comment by circuitikzuser** [comment]
It works exactly as a usual cd. Cdemu makes the iso available to be seen as a normal audio cd indistinguishable from a normal hardware cd.

That said, I seem to have found the problem.
I had to go to preferences, Audio  CD Player, then change settings to  checkboxes 1,3,4 checked and 2 unchecked. Then it worked.

Can I suggest that if your software detects no readable metadata, then it automatically try the settings I just described. Will solve a lot of hassle to unasuming users. 
Since it is either the one or the other settings, it is easy to implement.

**Comment by circuitikzuser** [comment]
Another question; 
your homepage shows deadbeef with a lot of album cover art etc.
http://deadbeef.sourceforge.net/
Deadbeef here has no art and just have text.

**Comment by Alexey-Yakovenko** [comment]
It may be a bit tricky to configure, but I believe the Help menu has the information about how to enable album art in the playlist.

**Comment by Alexey-Yakovenko** [comment]
Thanks for finding out what the problem was. Let's keep the issue open.

**Comment by circuitikzuser** [comment]
Thanks a lot, great application.

**Comment by circuitikzuser** [comment]
Alexey,
I used the design mode and dead beef now works way way better. 
Design mode is brilliant. If I may ask, which development lnguage do you use that enables designmode. Its really great.!
Will you have more options/items available in designmode?
Do you foresee that users can program their own items for designmode?
Absolutely amazing nice now.

I will switch from Clementine to Deadbeef. Deadbeef is just way more rugged and Clementine keeps breaking due to its reliance on Gstreamer. I created a nice interface now similar to Clementine.
You do not maybe have or know of a conversion tool that converts clementine playlists to Deadbeef ? 
Otherwise I just have to redo them all. It is worth it. Deadbeef is rock solid stable with cdemu.

**Comment by Alexey-Yakovenko** [comment]
@circuitikzuser 

Deadbeef is programmed in C.

The users can extend / add more widgets to design mode by developing plugins.
It's not very simple, but you could find some existing plugins on the wiki, and look at their sources.

Sorry, I don't know how to convert the playlists.

**Comment by circuitikzuser** [comment]
Thank you for your response, I updated my previous post with more questions I think other users will find very helpful too. It really is great software, but easily overlooked.

**Comment by Alexey-Yakovenko** [comment]
> Questiion: If I may ask, which development language do you use that enables designmode. Its really great.!

It's written in C. However it's not something that a language enables. I programmed it.

> Questiion: Will you have more options/items available in designmode?

I don't know what answer could be expected from this question.

> Questiion: Do you foresee that users can program their own items for designmode?

They can, and they do. There are plenty of user-created plugins which add more widgets to design mode.

> Questiion: You do not maybe have or know of a conversion tool that converts clementine playlists to Deadbeef ?

Sorry, nope.

> Question: I cannot figure out from the manual how run a command with the butto when added in design moe. I entered /usr/bin/xterm as the command to test for the button in the execute field, but it doesnt execute it.

I don't remember if this is possible. I think it is, but I don't have a linux machine nearby so can't test right now, but I'll try this when I can. It has been many years since I last used this.

**Comment by Alexey-Yakovenko** [comment]
> Also you can have one compulsory small add item that displays ads

I don't have any reasons to do this.

**Comment by circuitikzuser** [comment]
Thanks

**Comment by Alexey-Yakovenko** [comment]
Checked the button launching xterm, it works fine here..

1. add a new command
![image](https://user-images.githubusercontent.com/1895698/62317785-ae13b080-b49a-11e9-9803-2ee6bb76ab6f.png)
![image](https://user-images.githubusercontent.com/1895698/62317849-d3082380-b49a-11e9-8e2e-f513367f0459.png)

2. add a button in design mode, and choose the action you created in step 1
![image](https://user-images.githubusercontent.com/1895698/62318006-20849080-b49b-11e9-8cb0-155a0e7b3d7e.png)

**Comment by Alexey-Yakovenko** [comment]
I have fixed the cdtext vs cddb issue, but I have no way to test it since I don't have a CD drive or CD images, and I don't want to fiddle with cdemu in a VM. But would be nice if you could verify the fix.

**Comment by circuitikzuser** [comment]
Thank you very much, I will test it and get back to you.

**Comment by circuitikzuser** [comment]
Do you maybe know what the default settings are in the audio plugins?. I dont hae it anymore.  I changed it to something else that gave me the metadata as I mentioned in the previous posts, but I need to set it back to the defaults. You can just send me a screenprint of the default settings and I will test it with cdemu virtual cds.

**Comment by circuitikzuser** [comment]
Thank you for the tutorial on custom commands. I somehow messed up the last step, everything else I did right. It works now. Neat !
Absolutely greatest player out there, but since it starts up a blank page lots of people go somewhre else.
I didnt even know of design mode when I initially tried it.
Now it is the absolutel BEST player period .....
Thanks.

**Comment by Alexey-Yakovenko** [comment]
Use CDDB/FreeDB: yes
Prefer CD-Text over CDDB: yes

**Comment by circuitikzuser** [comment]
I made the changes and everything remained the same when I restarted deadbeef.
I dont know if it still remembers the previous album art work and song titles, but if not, then it is solved.

Do you suggest I attach a new cd that was never before used and then use your settings to make sure it works?

**Comment by Alexey-Yakovenko** [comment]
You need to remove the tracks from your playlist, and reopen the CD.

**Comment by circuitikzuser** [comment]
I already recreated large playlists.
I dont want to delete the playlists.

Best is I create another user on the system and then just do it there. 
I will do that as it doesnt risk my existing playlists.

**Comment by Alexey-Yakovenko** [comment]
I'm not asking you that. You just need to re-add 1 CD to playlist to verify the fix. That's it.

**Comment by Alexey-Yakovenko** [comment]
You can also just create an empty test playlist, add a CD for a test, then delete it when done.
No idea how did you come up with those ideas involving creating another user, but whatever works for you.

**Comment by circuitikzuser** [comment]
i created a new user and started deadbeef from that users account (takes 20 seconds on Linux).
deadbeef then starts with its installation defaults as there is no profiles in the new users home folder.
I made sure to set the audio plugins settings to what you said abve. Only Use CDDB/FreeDB: yes
Prefer CD-Text over CDDB: yes were selected.

deadbeef could not find any artwork or song titles for the same virtual cds that is now found with the different settings in the other user account.
So it doesnt sem to work.

**Comment by Alexey-Yakovenko** [comment]
Thanks for the detailed post. So did the fix work or not?

**Comment by circuitikzuser** [comment]
Sorr, I guess my posst  was too detailed for no reason and looks indecisive.

No it definitely did not work.

**Comment by Alexey-Yakovenko** [comment]
Is there any tool which I could use to create a CD image usable via cdemu from audio files, without ripping an actual CD?

**Comment by Alexey-Yakovenko** [comment]
(nvm, found one)

**Comment by Alexey-Yakovenko** [comment]
should work now

**Comment by circuitikzuser** [comment]
Do you have the exact link for the updated deadbeef, so I make sure I install the changes.

**Comment by Alexey-Yakovenko** [comment]
https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download

**Comment by circuitikzuser** [comment]
Still did not work with the new software.

Dont know why, but at least it does work with 1,3,4 selected and I can continue with that until I encounter a cd  that is not in the online database.
I guess you have to wait till more people complain about this in case this is a problem unique to my system.

**Comment by circuitikzuser** [comment]
Since I ran the new deadbeef in my account my system installed deadbeef does not recognize my playlists anymore, The new one must have  changed something in the config files.

**Comment by circuitikzuser** [comment]
It is no problem, I should have run it in my test account I created, so it is my fault.
Question:
1) Which app app can I use to open the database files ?
It will help me to quickly create new playlists.
2) Which file holds my interface that I designed as I dont want to redo that and need to back that up before the purge.

**Comment by Alexey-Yakovenko** [comment]
If you believe that running new deadbeef would corrupt the playlists or configuration files, you should create a new issue about that.

> Which app app can I use to open the playlist database files in my user account ?
> It will help me to quickly create new playlists.

I don't think that any other files can read deadbeef's playlists.

> Which file holds my interface that I designed as I dont want to redo that and need to back that up before the purge.

~/.config/deadbeef/config

**Comment by Alexey-Yakovenko** [comment]
I'm assuming that the original issue about opening CDs is solved, therefore I'm deleting all irrelevant messages and locking the case, to prevent misdirected posts.

**Comment by Alexey-Yakovenko** [comment]
The issue has been cleaned up, and is assumed to be fixed - mainly because I was able to reproduce the issue, apply a fix, and verify that the fix worked.

If you believe that the fix was not sufficient for your case, and additional work is necessary - please create a new issue.
