### ISSUE TITLE
request to align equalizer preset bands UI and add reset button

### ISSUE THREAD

**Issue by NektoNektovich** [DeaDBeeF-Player/deadbeef#2179]
Hello. There are two requests for improving the equalizer, which is built into the audio converter.
1- visually the length of the stripes is different. Is it possible to make the length of the strips the same?
2- I do not have enough of the reset button to quickly reset the strip values.
Linux deadbeef version 1.8.2
thank you in advance.
здравствуйте. есть две просьбы по улучшению эквалайзера, который встроен в аудио конвертер.
1- визуально длинна полос разная. можно ли сделать длинну полос одинаковой?
2- мне немного не хватает кнопки сброса для быстрого обнуления значений полос.
линукс версия deadbeef 1.8.2
заранее благодарю.

**Comment by NektoNektovich** [comment]
Alexey, thanks :)

**Comment by NektoNektovich** [comment]
there are two points:
1- player does not see the cover of the built-in vorbis comment.
2- very lacking sound effect plugin - reverberation, the setting force effect +/- 0, as is done in the plugin stereo widener.

есть еще два момента:
1- плеер не видит встроенные обложки в vorbis comment.
2- очень не хватает плагина аудиоэффекта ревербирации, с настройкой силы эффекта +/-0, как это сделано в плагине stereo widener.

**Comment by Alexey-Yakovenko** [comment]
@NektoNektovich 
There's no point in writing additional bugs / feature requests in the comments, they won't get any attention. It's best to post each issue individually.
