### ISSUE TITLE
Play button starts from the beginning

### ISSUE THREAD

**Issue by polishExperiment** [DeaDBeeF-Player/deadbeef#2180]
### Steps to reproduce the problem
Click in the middle of a track. Press play. Press play again.

### What's going on? Describe the problem in as much detail as possible.
Track starts playing from the beginning.

### Information about the software:
Deadbeef version:1.8.2-rc1
OS:Ubuntu 18.04

**Comment by polishExperiment** [comment]
Related to this? https://github.com/DeaDBeeF-Player/deadbeef/issues/1942

**Comment by Alexey-Yakovenko** [comment]
Works as designed
