### ISSUE TITLE
junk_copy function is not present

### ISSUE THREAD

**Issue by rossnomann** [DeaDBeeF-Player/deadbeef#2181]
Looks like junk_copy function was accidentally removed.

It was introduced here:
https://github.com/DeaDBeeF-Player/deadbeef/commit/40d3a5c66105914c1113bc7ef0649e13b3db690f

Currently I can not find it:
https://github.com/DeaDBeeF-Player/deadbeef/search?q=junk_copy&type=Code

**Comment by Alexey-Yakovenko** [comment]
Hmm this is very odd. It's present in the API, but it's not present in the library.
And it's been removed in 2010.
This is the commit that removed it 06698504cafb9d3b87674c51bbd49dbbb6a54db0

**Comment by Alexey-Yakovenko** [comment]
It looks like it's been replaced with a function pl_items_copy_junk, but the API was not corrected.

**Comment by Alexey-Yakovenko** [comment]
Anyway.. since we're almost 10 years into this issue, it will have to stay the way it is..
so .. just use pl_items_copy_junk instead. Which itself looks very outdated and doesn't do what I'd expect.
