### ISSUE TITLE
Keyboard P_layer buttons & Deadbeef.

### ISSUE THREAD

**Issue by circuitikzuser** [DeaDBeeF-Player/deadbeef#2186]
### Steps to reproduce the problem
none Never works.

### What's going on? Describe the problem in as much detail as possible.
Might not be a deadbeef issue, but would appreciate direction.
I cannot get Pause/Forward/Play etc to work on my keyboard with deadbeef. Works great with Clementine.
Where do I enter keybindings for these keyboard buttons for deadbeef ?
The usual keyboard shortcut config on the OS is completely unaware of deadbeef, but sees clementine.

### Information about the software:

Linux MX18.3/Pulseaudio/Jack/Alsa

Deadbeef version:
1.8.2
OS:
Linux MX18.3

**Comment by Alexey-Yakovenko** [comment]
I don't know what is P_layer, but installing MPRIS plugin might help. I'm not 100% sure though.

https://github.com/Serranya/deadbeef-mpris2-plugin

There's also a plugin gnome_mm_keys http://github.com/barthez/deadbeef-gnome-mmkeys/

Deadbeef doesn't support GNOME multimedia keys natively without plugins.

**Comment by circuitikzuser** [comment]
Player, I couldnt edit my error, there is no way to edit the title.
Ok thanks, I was not aware of the plugin issue. 
Thank you very much !

**Comment by Alexey-Yakovenko** [comment]
oh.. sorry, I should have figured that out.

**Comment by circuitikzuser** [comment]
It seems the solution for my problem above is as follows.
https://github.com/Serranya/deadbeef-mpris2-plugin/issues/9

**Comment by Alexey-Yakovenko** [comment]
You can probably also download the plugin binary from here http://deadbeef.sourceforge.net/plugins.html
