### ISSUE TITLE
Possible Bug:  When Jack/pulseaudio dies Deadbeef repeatedly run at high speed through current playlist

### ISSUE THREAD

**Issue by circuitikzuser** [DeaDBeeF-Player/deadbeef#2188]
### Steps to reproduce the problem
Linux with Pulseaudio running Jack sync and source.
Deadbeef uses Pulseaudio.

### What's going on? Describe the problem in as much detail as possible.
When Jack/pulseaudio dies Deadbeef repeatedly run at high speed through current playlist.
Not normal. Expected behavior would be to continue playing cd with no sound output or to stop, not run away.

### Information about the software:

Deadbeef version:  
1.8.2

OS: 
NAME="MX"
VERSION="18 (Continuum)"
ID="mx"
VERSION_ID="18"
PRETTY_NAME="MX 18 (Continuum)"
ANSI_COLOR="0;34"
HOME_URL="https://mxlinux.org"
BUG_REPORT_URL="https://mxlinux.org"
PRETTY_NAME="MX 18.3 Continuum"
DISTRIB_ID=MX
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=Continuum
DISTRIB_DESCRIPTION="MX 18.3 Continuum"
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

If you think it is worth it to investigate I will make a video and post it showing what happens. Let me know.
Otherwise deadbeef runs normally.

**Comment by Alexey-Yakovenko** [comment]
Would be great if you add more precise steps to reproduce the problems.
More specifically, how exactly to cause pulseaudio or jack to die, in your particular circumstances.

**Comment by circuitikzuser** [comment]
I will do so. 
It will take some time as I have an unexpected kernel issue I have to resolve first that is not related to this problem with pulseaudio/deadbeef. Once I solve that I will do a detailed description of what happens here.  but please keep this open.

**Comment by Alexey-Yakovenko** [comment]
Not reproducible
