### ISSUE TITLE
website: add a text that explains that plugins folder needs to be created if it doesn't exist

### ISSUE THREAD

**Issue by Mango2000** [DeaDBeeF-Player/deadbeef#2196]
Or maybe a hint somewhere in the Plugins Tab that you have to create it first for the plugins

**Comment by Alexey-Yakovenko** [comment]
2 questions to that:

1. what is "enty"
2. why should I add this hint there?

**Comment by Mango2000** [comment]
Ah sorry for not giving more infos. I meant entry. This path didn't existed on my manjaro kde installation. I installed DeadBeef 1.8.0 through the arch repo.

**Comment by Alexey-Yakovenko** [comment]
ok. now you only have the 2nd question to answer.

**Comment by Alexey-Yakovenko** [comment]
actually now I have a new question. what do you mean by this sentence?
"Make an entry to .local/lib/deadbeef/"

**Comment by Mango2000** [comment]
This entry does exist usually? Sorry I'm trying my best to explain this. My english is not the best though. I thought it would be easier for new users to understand where to put the plugin files in. And if it does not exist they could find out why not when there would be a hint.

**Comment by Mango2000** [comment]
I had no /lib/deadbeef/ in my .local folder

**Comment by Mango2000** [comment]
> actually now I have a new question. what do you mean by this sentence?
> "Make an entry to .local/lib/deadbeef/"

If this folder usually exist, it's an issue on my side. 
On the Deadbeef website it says: 'Download and extract .zip, copy the plugin to ~/.local/lib/deadbeef/'
And I was confused as a newbie because there was no such folder. I hope that's clear enough

**Comment by Alexey-Yakovenko** [comment]
I don't understand the problem.
When you download a plugin, you see this:
![image](https://user-images.githubusercontent.com/1895698/63592349-ac2ca100-c5b1-11e9-979d-bd20400b8e47.png)

Is that not enough?

**Comment by Alexey-Yakovenko** [comment]
Ok. So you're basically asking to change this text on the website, to explain that this folder needs to be created if it doesn't exist?

**Comment by Mango2000** [comment]
When you come from Win7, yes. I expected that the folder is already there. Nevermind, I need to learn some things now that I'm using linux. 
I know from other tutorials where it says: 'If the folder doesn't exist, create it

**Comment by Mango2000** [comment]
> Ok. So you're basically asking to change this text on the website, to explain that this folder needs to be created if it doesn't exist?

yes

**Comment by Alexey-Yakovenko** [comment]
ok I get it now.

**Comment by Mango2000** [comment]
Thank you!

**Comment by Alexey-Yakovenko** [comment]
added
