### ISSUE TITLE
%_path_raw% field provides path in non-expected format

### ISSUE THREAD

**Issue by kravich** [DeaDBeeF-Player/deadbeef#2197]
### Steps to reproduce the problem
Add custom column to playlist with %_path_raw% in "Format" filed

### What's going on? Describe the problem in as much detail as possible.
Foobar2000's title formatting reference states that %_path_raw% field [should produce URL](http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#.25_path_raw.25). However, the actual result differs - for network sources produced string is excatly a URL, but for local files it is actually an absolute file path:
![screen](https://user-images.githubusercontent.com/774509/63637853-dc189900-c6c4-11e9-84ba-73659e5680d5.png)

This happens because titleformatting engine uses ":URI" metadata record [as is](https://github.com/DeaDBeeF-Player/deadbeef/blob/master/tf.c#L2346) to produce %_path_raw% output.

Is it a bug or an expected result because of historical reasons?
If it is a bug, I am going to provide a fix for it.

### Information about the software:
Deadbeef version: 1.8.2
OS: Ubuntu Linux 19.10

**Comment by Alexey-Yakovenko** [comment]
Have you verified whether foobar 2000 actually produces URLs for file paths?

**Comment by Alexey-Yakovenko** [comment]
Nvm, I checked, it does, it's a bug, please feel free to submit a fix

**Comment by kravich** [comment]
Do I understand correctly that fix should affect only titleformatting API and should not change the semantic of ":URI" metadata record?

**Comment by Alexey-Yakovenko** [comment]
Yes, only title formatting
