### ISSUE TITLE
macOS Album art, Fetch from local folder ignores file mask

### ISSUE THREAD

**Issue by ryoplasmic** [DeaDBeeF-Player/deadbeef#2200]
### What's going on? Describe the problem in as much detail as possible.

Album art, fetch from local folder will pickup any pic in local folder, not those specified in local file mask: I have some song in a folder with some pics with some names not named folder cover or whatever names. When I launch the app, it will take that pic instead of embedded album art. I throw the same folder to Manjaro version and it can pic up only the embedded album art. It is a bug in macOS version.
### Information about the software:

Deadbeef version:  deadbeef-devel-osx-x86_64.zip | 2019-08-05 | 7.8 MB

OS: macOS 10.14.6

**Comment by Alexey-Yakovenko** [comment]
Could you please post them as 3 separate issues? Thanks.

**Comment by Alexey-Yakovenko** [comment]
Also I think you accidentally uploaded 2 of the same pics, and there's no screenshot demonstrating [] problem.

**Comment by ryoplasmic** [comment]
Hi,

I think I will leave the 1st issue here and edit/remove the 2 and 3. the 3 is created https://github.com/DeaDBeeF-Player/deadbeef/issues/2201

Thanks

**Comment by pihug12** [comment]
I think I'm still having this issue with DeaDBeeF 1.8.4 and Fedora 32. I play a file where there should be no artwork and DeaDBeeF picks a random JPG file in the same folder.

The pattern is set to: `*cover*.jpg;*front*.jpg;*folder*.jpg;*cover*.png;*front*.png;*folder*.png`

And the files picked don't respect this rule.

**Comment by Alexey-Yakovenko** [comment]
@pihug12 deadbeef doesn't use the same code for album art on mac and linux. It doesn't make sense to report a bug to a closed fixed issue on another platform related to different code. Please search for open issues that are related to your problem, and if there are none -- report the new one.
