### ISSUE TITLE
macOS Reload Metadata shows [] when Album Art column is group by Artist/Date/Album

### ISSUE THREAD

**Issue by ryoplasmic** [DeaDBeeF-Player/deadbeef#2201]
### Steps to reproduce the problem
Reload Metadata shows [] when Album Art column is group by Artist/Date/Album

### What's going on? Describe the problem in as much detail as possible.
reload meta data create foreign characters: While I am playing around with the album art settings, I try to Reload Metadata and there is a [ ] appears, see attached pic. Tested in Manjaro no this issue

### Information about the software:

Deadbeef version: deadbeef-devel-osx-x86_64.zip | 2019-08-05 | 7.8 MB

OS: macOS 10.14.6

![before reload](https://user-images.githubusercontent.com/43009072/63901929-b688d980-c9bb-11e9-8d4a-f31d4c7f8cf0.png)
![after reload](https://user-images.githubusercontent.com/43009072/63901928-b688d980-c9bb-11e9-9d2c-108f45b1fcfe.png)

The [] appears above the album art in the 2nd pic, -> LiSA - [] ...

**Comment by Alexey-Yakovenko** [comment]
oh ok. I get now what's going on.
I will need to know which file format is that, to be able to reproduce though, because loading / reloading metadata is format-specific.

**Comment by ryoplasmic** [comment]
This is a Hi-Res FLAC fro mora.jp

I double check with the flac I made and it seems the [ ] is belonging to the date. I can see the date . I put when I rip the disc. Those mora.jp flac does not have any value on the date field so it shows the [ ]

The same file plays under linux version does not show the [ ] when reload metadata.

**Comment by Hochiss** [comment]
Could anyone tell how to enable album art or such plugin in macOS version? 
any macOS ready build for 1.80? I download from sourceforge but it turns ourt v1.0 from 2016 correct?

**Comment by Alexey-Yakovenko** [comment]
@Hochiss 
deadbeef for macOS is not really versioned...
it's always "1.0" + revision number.

You can get album art by clicking Help -> Deadbeef Help, and following instructions.

**Comment by Alexey-Yakovenko** [comment]
I can't find any way to trigger this bug.
Can you share the flac?

**Comment by Alexey-Yakovenko** [comment]
OP out of contact.
