### ISSUE TITLE
Requests to playlist.

### ISSUE THREAD

**Issue by AsVHEn** [DeaDBeeF-Player/deadbeef#2203]
Hi, I have some questions/requests about:

- ~I had group by  `%album artist% - %album%`, but then I saw box sets like [this with 4 Cds](https://en.wikipedia.org/wiki/The_Complete_Capitol_Singles_Collection) are in same group. It can be split by adding `%DISC%` to "group by" but then there a "1" in every other group. So, can it be hide?~
Nevermind, done by using `%album artist% - %album% $ifgreater(%DISC%,1,%DISC%/%NUMDISCS%,)`

- Can I get `%artist% - %album%` align to left and `%year%` to right? I tried with pad and pad_right functions but I was unsuccessful with non monospaced fonts.

- "Open folder" option in context menu when right-click some track.

- Save personal "group by" when change to predefined options (because I missclicked and losed personal :smiley: ).
- And a ridiculous requests: Stars/hearths/whatever icon (clickable) for rating instead of number :smiley: .

(Fantastic software by the way)

Deadbeef version: 1.8.2
OS: Debian 10

**Comment by Alexey-Yakovenko** [comment]
> Can I get %artist% - %album% align to left and %year% to right?

Use 2 different columns. Otherwise no.

> "Open folder" option in context menu when right-click some track.

 shellexecui -> new command -> xdg-open

> Save personal "group by" when change to predefined options (because I missclicked and losed personal 😃 ).

This is kind of planned for the future, and should be solved via preset manager.

> And a ridiculous requests: Stars/hearths/whatever icon (clickable) for rating instead of number 

pretty sure it's been requested already. search for it.

**Comment by AsVHEn** [comment]
Thank you for your quick answer.

> > Can I get %artist% - %album% align to left and %year% to right?
> 
> Use 2 different columns. Otherwise no.
Can I use columns on "group text's title" (I don't know how to refer to it, sorry)? I guess I didn't write
 question correctly and I can only use columns on regular playlist part. Anyway monospaced font do the work :+1: .

**Comment by Alexey-Yakovenko** [comment]
> Can I use columns on "group text's title" (I don't know how to refer to it, sorry)?
No

**Comment by Alexey-Yakovenko** [comment]
Yeah, I kinda guessed that you had group title in mind. I don't think this is possible though.
Maybe it's better to ask people on slack, and they would advice something.

**Comment by fabertawe** [comment]
> > "Open folder" option in context menu when right-click some track.
> 
> shellexecui -> new command -> xdg-open

This doesn't work, [as I already reported #2191](https://github.com/DeaDBeeF-Player/deadbeef/issues/2191).

**Comment by AsVHEn** [comment]
> > > "Open folder" option in context menu when right-click some track.
> > 
> > 
> > shellexecui -> new command -> xdg-open
> 
> This doesn't work, [as I already reported #2191](https://github.com/DeaDBeeF-Player/deadbeef/issues/2191).
`xdg-open  %D` should be (to me work at least).

**Comment by fabertawe** [comment]
> > > > "Open folder" option in context menu when right-click some track.
> > > 
> > > 
> > > shellexecui -> new command -> xdg-open
> > 
> > 
> > This doesn't work, [as I already reported #2191](https://github.com/DeaDBeeF-Player/deadbeef/issues/2191).
> > `xdg-open  %D` should be (to me work at least).

Thank you for the feedback :)

Bizarrely after testing again, it works for me if I untick "Generic (Main Menu)" and use from the right click context menu. It doesn't work from the main menu! (as I was using it). I'll feed back to #2191
