### ISSUE TITLE
Feature Request: Support for Matroska container audio files (.mka)

### ISSUE THREAD

**Issue by Mango2000** [DeaDBeeF-Player/deadbeef#2204]

**Comment by Alexey-Yakovenko** [comment]
Any reason for me to spend time on this?
Is that not something that could be used via ffmpeg plugin?

**Comment by Mango2000** [comment]
Because I have a lot audio files in this format :) 
It's more common than some tracker music I guess.
I don't know how to use the ffmpeg plugin so that it works with mka files.
It's just a suggestion.

**Comment by Alexey-Yakovenko** [comment]
I never encountered any audio(-only) files in this format.

**Comment by Alexey-Yakovenko** [comment]
Anyway, this falls under category of what I consider exotics / strange wishes.
If that's something that you need, you'll have to use ffmpeg plugin.
You have to build it on your machine, and link it with the system-installed ffmpeg, which needs to include MKV and whatever audio codec(s) you put inside.
This can be done fairly trivially on linux.
On mac more tricky, but doable.
Once you have the plugin which can use system ffmpeg with mkv, you need to add an mkv file extension in the plugin's settings.

This is something that already works, unless proven otherwise..
Therefore closing the case.

**Comment by Mango2000** [comment]
I'll try that. Btw this format is supported by a lot of audio players already. But I'll try your hint, thanks

**Comment by Alexey-Yakovenko** [comment]
Yes, it's supported by deadbeef too.

**Comment by Alexey-Yakovenko** [comment]
Whether it works or not is another story, since you're probably the only person who would try this out.

**Comment by Mango2000** [comment]
I admit that It's exotic

**Comment by mrmatteastwood** [comment]
Hey guys! I'm wondering if you could go into a little detail about enabling mka playback in DeaDBeeF. I have v1.8.3 and I can see that the FFMPEG audio playback plugin is present in Preferences > Plugins.

In the plugin's config, I added .mka as a suppported file type, but when I drag my .mka files onto DeaDBeeF, it ignores them.

I read above that I need to build an extra plugin? How would I go about doing that? I'm on Linux Mint 19.3.

**Comment by Alexey-Yakovenko** [comment]
The official builds don't include all of the ffmpeg features. If you need the extras, such as mkv support -- you need to compile deadbeef locally, this way it will use the system version of ffmpeg.

**Comment by Alexey-Yakovenko** [comment]
same as written in https://github.com/DeaDBeeF-Player/deadbeef/issues/2204#issuecomment-526588326

**Comment by mrmatteastwood** [comment]
Ah, understood. Thanks! I misunderstood comment #2204, then.

**Comment by Alexey-Yakovenko** [comment]
The crucial part is that you need to have a build of ffmpeg plugin that uses the system version of ffmpeg.

**Comment by greenvorbisfan** [comment]
Модуль ffmpeg действительно поддерживает Matroska. Но при добавлении, например файлов MKA, содержащих DTS, плеер использует для декодирования не нативный модуль поддержки DTS, а всё тот же модуль ffmpeg. Плюс нативная поддержка Matroska помогла бы закрыть вопрос с чтением и редактированием тегов, модуль ffmpeg распознаёт их не полностью — не видит тегов, добавленных вручную, номера трека, количества и номера носителя, а также %album%, всех тегов ReplayGain.
Справедливости ради, НИ ОДИН аудиоплеер на *nix не имеет нативной поддержки Matroska — для DeaDBeeF это была бы воистину киллер-фича.
