### ISSUE TITLE
How to not remember the previous playing order?

### ISSUE THREAD

**Issue by laichiaheng** [DeaDBeeF-Player/deadbeef#2205]
### Steps to reproduce the problem
Play the music
### What's going on? Describe the problem in as much detail as possible.
The shuffle album doesn't work if I try to jump to the previous album, it always remembers the order of every song that I have played before. There is no way to directly jump to next random album, unless the album is over.
### Information about the software:

Deadbeef version:deadbeef-git
OS:Manjaro Linux

**Comment by Alexey-Yakovenko** [comment]
From your description, seems like the feature is working as designed. If you disagree, please describe your expectations more accurately.

**Comment by laichiaheng** [comment]
@Alexey-Yakovenko There should be a way to jump to random albums instead of random tracks only.

**Comment by Alexey-Yakovenko** [comment]
Then it's unrelated to shuffle modes.
There's already a feature request for what you want: #740

**Comment by Alexey-Yakovenko** [comment]
In fact, there's already an action that can be assigned to a hotkey, it's under Playback, Skip to Next album

**Comment by laichiaheng** [comment]
@Alexey-Yakovenko But it is really jumps to the Next album which is below the current album.

**Comment by Alexey-Yakovenko** [comment]
well, then no luck for now.
