### ISSUE TITLE
The sound volumn will be affected by spotify.

### ISSUE THREAD

**Issue by laichiaheng** [DeaDBeeF-Player/deadbeef#2211]
### Steps to reproduce the problem
1. Play music in Spotify first.
2. Play music in DeaDBeeF while Spotify is opened.
### What's going on? Describe the problem in as much detail as possible.
The sound volume of DeaDBeeF will be changed if the sound volumn of Spotify has been changed, no matter the music in Spotify stops or not.
![2019-09-12 00-52-08 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/64717816-926ae380-d4f7-11e9-8015-22828985c201.png)

### Information about the software:

Deadbeef version: r8538.878c0f936-1
OS: Manjaro

**Comment by laichiaheng** [comment]
It only happens to the ALSA plug-in.

**Comment by Alexey-Yakovenko** [comment]
Deadbeef itself doesn't do that. Most likely some hidden pulseaudio module is doing that. I can't help with that.
