### ISSUE TITLE
Remove From Disk the whole Playlist

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2215]
I took a look at the delete_from_disk_handler again. ;)
Among other things I have reworked the dialog and it now displays different warning messages.

I noticed the following, there are three different modes when deleting: 
* Selection (DDB_ACTION_CTX_SELECTION)
* Playlist (DDB_ACTION_CTX_PLAYLIST)
* Current song (DDB_ACTION_CTX_NOWPLAYING)

However, DDB_ACTION_CTX_PLAYLIST never seems to be used. If you go to the tab with the current playlist -> "Remove From Disk" the current selection will be deleted. The same with a shortcut Action -> Current Playlist -> Remove From Disk. Is that intended?

Deadbeef version: A slightly older version based on 1.8.0
OS: Linux

**Comment by Alexey-Yakovenko** [comment]
What do you mean by "never seems to be used"? Judging by the code, it's used in ~25 places, including pltmenu.c:153

https://github.com/DeaDBeeF-Player/deadbeef/blob/ea0f680a4948083e1e4fb3ee8eba007e7e4aed91/plugins/gtkui/pltmenu.c#L153

**Comment by Alexey-Yakovenko** [comment]
I checked the code in debugger, and it works as intended. The action in playlist context menu will delete all files in the playlist.

**Comment by kpcee** [comment]
You got me wrong, I'm not talking about removing from playlist, I'm talking about removing from disc. In the function 
```
gboolean
action_delete_from_disk_handler_cb (void *data) 
```
is a routine that removing the entire contents of a playlist from disk and that is imho dead code.
By the way there is a deadbeef->pl_save_current (); missing (DDB_ACTION_CTX_NOWPLAYING).

**Comment by Alexey-Yakovenko** [comment]
I don't think that I got you wrong. It's exactly what I verified, and I could not reproduce what you wrote.

And yeah, in this one case pl_save_current is missing indeed. That looks like a bug.

**Comment by kpcee** [comment]
Sorry the post is already 1 1/2 months ago and what I have written is also not quite right. You are right that the routine DDB_ACTION_CTX_PLAYLIST is started and is not dead code. But what I wrote fits, the routine doesn't delete the whole playlist, that's because there's a bug in it.

`DB_playItem_t *next = deadbeef->pl_get_next (it, PL_MAIN);`
is called after the item has been deleted by `delete_and_remove_track (uri, plt, it);` this interrupts the iteration, so it is impossible to delete the whole playlist. 

If I set `DB_playItem_t *next = deadbeef->pl_get_next (it, PL_MAIN);` further up before deleting the item the routine works as it should.
I don't understand why this works for you.

**Comment by Alexey-Yakovenko** [comment]
Hmm. OK, that sounds right. Thanks for spotting, fixed.

**Comment by Alexey-Yakovenko** [comment]
saving playlist after delete in nowplaying context also fixed

**Comment by Alexey-Yakovenko** [comment]
In fact, pl_save_current is wrong, since the edited playlist might be another one. I'll fix later.

**Comment by Alexey-Yakovenko** [comment]
> In fact, pl_save_current is wrong, since the edited playlist might be another one. I'll fix later.

And this is now fixed too.

**Comment by kpcee** [comment]
Thanks!
