### ISSUE TITLE
Please enable HTTPS for deadbeef.sourceforge.io

### ISSUE THREAD

**Issue by vszakats** [DeaDBeeF-Player/deadbeef#2224]
It's just a press of a button on the Sourceforge admin interface. Instructions here:
https://sourceforge.net/blog/introducing-https-for-project-websites/

![prweb_https](https://user-images.githubusercontent.com/1446897/65829170-9beb9e00-e2a2-11e9-8976-dc8d287bc28e.png)

**Comment by Alexey-Yakovenko** [comment]
Thanks for reminding about this. I was wondering about this possibility for a while, but it always slipped. I clicked the button, and the page said it will take effect soon.
