### ISSUE TITLE
[macOS] DeaDBeeF crashes loading large playlists with ALAC files

### ISSUE THREAD

**Issue by tomjepp** [DeaDBeeF-Player/deadbeef#2227]
### Steps to reproduce the problem
1. Have a large .m3u8 playlist (~500+ files) with lots of ALAC files in it
2. Load the playlist using File, Load Playlist
3. DeaDBeeF shows a lot of errors in the logs and quickly crashes.

### What's going on? Describe the problem in as much detail as possible.

When running DeaDBeeF under Xcode, I could not reproduce.

When running from a terminal, I get a collection of errors like the following:
```
/Volumes/m.2 Storage/Music/#Playlists/../Pokemon/(2000) Pokémon_ Gotta Catch the Sound!/15 Masuda Junichi & Masafumi Kawamura - Fanfare.m4a: Too many open files
ERROR: could not load: /Volumes/m.2 Storage/Music/#Playlists/../Pokemon/(2000) Pokémon_ Gotta Catch the Sound!/15 Masuda Junichi & Masafumi Kawamura - Fanfare.m4a
```

After repeating that for every remaining file in the playlist, it then throws:

```
2019-10-02 23:57:50.311 DeaDBeeF[87524:1455058] CoreText: System LastResort not available, using built-in copy.
2019-10-02 23:57:52.484 DeaDBeeF[87524:1455154] Persistent UI failed to open file file:///Users/thomas/Library/Saved%20Application%20State/com.deadbeef.DeaDBeeF.savedState/window_9.data: Too many open files (24)
Assertion failed: (temp_fd >= 0), function _open_and_mmap_for_reading, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/LanguageIdentifier/LanguageIdentifier-133/LanguageIdentifier.c, line 624.
zsh: abort      ./MacOS/DeaDBeeF
```

And the app terminates.

### Information about the software:

Deadbeef version: master `b0cdeb04`
OS: macOS Catalina 10.15 Developer Beta 10 (19A578c)

(yes, I know it's a beta OS, but this is on a test install and I still like music 😉)

**Comment by tomjepp** [comment]
OK, I had a further play with this, and it *looks* like this is caused by the AAC plugin leaking file handles when it finds a valid mp4 file but it does not have any AAC tracks in it - this (for me) because it's a playlist full of ALAC files.

I have no idea why this works under Xcode but not normally - maybe the FD limit is higher under Xcode?

**Comment by Alexey-Yakovenko** [comment]
@tomjepp your investigation is correct. I added `fclose` calls where appropriate, the issue should be solved.

**Comment by tj-prop** [comment]
Yep, I've rebuilt from current master and this seems to work fine.

Thanks!
