### ISSUE TITLE
Non-switchable log window upon opening directory with ALL files

### ISSUE THREAD

**Issue by unclebrr** [DeaDBeeF-Player/deadbeef#2229]
### Steps to reproduce the problem
deadbeef /dir/*

### What's going on? Describe the problem in as much detail as possible.
as soon as you have any non-sound files in loading directory (jpg, txt, info, etc) you have pop-up log window with error "failed to add file or folder ~/dir/info.txt"  (for example)
this behaviour could not be changed (switched off)
1.8.2 has a check for "Log window" it would be great for it to change behaviour of this "starting log window" too (feature request)

### Information about the software:
Deadbeef version: 1.8.2
OS: Linux leap 4.12.14-lp150.12.48-default #1 SMP Tue Feb 12 14:01:48 UTC 2019 (268f014) x86_64 x86_64 x86_64 GNU/Linux

**Comment by Alexey-Yakovenko** [comment]
Now that you actually wrote how you open the files -- this doesn't appear to be a bug.

It's the same as writing `deadbeef /dir/info.txt` (+ any other files which are in the same dir).

Perhaps what you want instead is `deadbeef /dir` -- this would not tell deadbeef to try to open info.txt, and there won't be an error.

**Comment by unclebrr** [comment]
Yes, sorry. I'll correct it.

**Comment by Alexey-Yakovenko** [comment]
Can you please confirm whether the problem happens when you pass `dir/*` or `dir`? They are two different cases, and I still don't have confirmation which one of them is presenting a problem for you.

**Comment by Alexey-Yakovenko** [comment]
Closing the case because of lack of communication with the poster. The conditions of the issue are not clear enough to do anything.

**Comment by unclebrr** [comment]
Sorry, missed it. It happens when I pass dir/*

**Comment by Alexey-Yakovenko** [comment]
> Anyway pls consider a feature request of not showing log window at all.

I am considering an option to let user disable it, if he doesn't want seeing errors.

**Comment by unclebrr** [comment]
Yes, that's what I've meant. Thank you.
