### ISSUE TITLE
Start mimimized with GTK3 - empty window appears

### ISSUE THREAD

**Issue by spvkgn** [DeaDBeeF-Player/deadbeef#2231]
### Steps to reproduce the problem

Start player with clean config, set GTK3 GUI and check minimize on startup option, restart.

### What's going on? Describe the problem in as much detail as possible.

DeaDBeeF window is empty and not minimized:

![Снимок экрана в 2019-10-04 19-23-56](https://user-images.githubusercontent.com/4147135/66215367-eca03400-e6b2-11e9-89e2-50cc8bd30f90.png)

### Information about the software:

Deadbeef version: devel
OS: Ubuntu 18.04 MATE

**Comment by Alexey-Yakovenko** [comment]
@kpcee do you want to look into this issue?
I didn't realize that I haven't tested the "start hidden" feature with GTK3, but turned out it doesn't work..

**Comment by kpcee** [comment]
As far as I can see this is due to a changed behaviour of Gtk3. The following source code automatically displays the window independent of gtk_widget_show (mainwin);. That is why the window is displayed without layout.
```
#if GTK_CHECK_VERSION(3,10,0)
#if USE_GTK_APPLICATION
    // This must be called before window is shown
    gtk_application_add_window ( GTK_APPLICATION (gapp), GTK_WINDOW (mainwin));
#endif
#endif
```
But we can't do without it either, because otherwise the gui plugin is closed automatically. We can prevent this with g_application_hold(), but even here the window is displayed automatically. If this is no bug in Gtk3, then we can't repair this imho.
We can go back as it was before, but keep the changes in the preference dialog, or we have to consider Gtk2 and Gtk3 separately.

**Comment by Alexey-Yakovenko** [comment]
Is it possible to defer this call to until the window needs to be shown?

**Comment by Alexey-Yakovenko** [comment]
I haven't tried this, but it looks like it should be possible to group this call with `gtk_widget_show (mainwin);`, and possibly add a global variable flag to ensure it's called only once. something like a new function `gtkui_mainwindow_show`, which would do all the checks, call `gtk_application_add_window` if needed (once), and then `gtk_widget_show (mainwin);`.

That is of course assuming no other problems will happen.. I haven't tried anything. But I can try this later.

**Comment by Alexey-Yakovenko** [comment]
ok I tried this, and you are correct. without any windows, the g_application_run would just return immediately, and the app would quit.

**Comment by Alexey-Yakovenko** [comment]
It looks like one way of fixing this problem is to register the window, and then hide it immediately using `gtk_widget_hide` after checking the `gtkui.start_hidden` flag.
This may cause other problems, but seems like GTK devs didn't have this use case in mind, and there's not much we could do.

**Comment by kpcee** [comment]
I have played around a little and the following works without problems. With the Gtk3 plugin the window is first displayed and then hidden with the old method, the Gtk2 plugin works without displaying the window. The other changes of the PR have no other negative effects.

```
#if GTK_CHECK_VERSION(3,10,0)
#if USE_GTK_APPLICATION
    // This must be called before window is shown
    gtk_application_add_window ( GTK_APPLICATION (gapp), GTK_WINDOW (mainwin));
#endif
#endif
#if GTK_CHECK_VERSION(3,0,0)
    printf("++++++ GTK3\n");
    wingeom_restore (mainwin, "mainwin", 40, 40, 500, 300, 0); 
    init_widget_layout ();
    gtk_widget_set_events (GTK_WIDGET (mainwin), gtk_widget_get_events (GTK_WIDGET (mainwin)) | GDK_SCROLL_MASK);
    //gtk_widget_show (mainwin);
    
    if (deadbeef->conf_get_int ("gtkui.start_hidden", 0)) {
        g_idle_add (mainwin_hide_cb, NULL);
    }
#elif GTK_CHECK_VERSION(2,16,0)
    printf("++++++ GTK2\n");
    if (!deadbeef->conf_get_int ("gtkui.start_hidden", 0)) {
        wingeom_restore (mainwin, "mainwin", 40, 40, 500, 300, 0);
        init_widget_layout ();
        gtk_widget_show (mainwin);
    }
#endif
```
