### ISSUE TITLE
CUE is lot loading when adding a folder to playlist.

### ISSUE THREAD

**Issue by g0ga** [DeaDBeeF-Player/deadbeef#2233]
### Only audio images (large flac/ape/wv/etc... files) are loaded without splitting those into tracks
(Still possible to open cue file directly and it will load media as needed, but not when adding a folder)

### Information about the software:

Deadbeef version: 1.8.2
OS: Archlinux

**Comment by Alexey-Yakovenko** [comment]
I just tried just that, and adding a folder splits the image into tracks according to the cuesheet.
You should verify that the filename in the cuesheet corrresponds to the actual file in the same folder. There should be something about the filenames that prevents deadbeef from matching them up.

**Comment by g0ga** [comment]
Files are okay and names are correct. Probably some weird build from archlinux (e.g. some dep missing during build) 0.7.5 works flawlessly when adding same folder.
![Screenshot_2019-10-06_22-17-05](https://user-images.githubusercontent.com/591802/66274412-1b6f0380-e887-11e9-8a28-9d92d6a1da81.png)
Let me try to rebuild it myself

**Comment by g0ga** [comment]
Rebuilt it, has exactly same problem. deadbeef-static build for archlinux from https://deadbeef.sourceforge.io/download.html has this problem too. Tried more than 10 artists that were loading well. Specially cleaned one to be super precise. Right filename (not like *.wav when it is flac) inside cue, file and folder named correctly (even removed spaces everywhere and special symbols), but still doesn't want to load.


```
[g0ga@home Joe_Satriani]✘ ls -r ./1986_Not_Of_This_Earth/
Not_Of_This_Earth.flac  Not_Of_This_Earth.cue
[g0ga@home Joe_Satriani]✘ cat ./1986_Not_Of_This_Earth/Not_Of_This_Earth.cue 
REM GENRE Rock
REM DATE 1986
REM DISCID 8909160A
REM COMMENT "ExactAudioCopy v1.0b3"
PERFORMER "Joe Satriani"
TITLE "Not Of This Earth"
FILE "Not_Of_This_Earth.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Not Of This Earth"
    PERFORMER "Joe Satriani"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "The Snake"
    PERFORMER "Joe Satriani"
    INDEX 00 04:00:07
    INDEX 01 04:04:15
  TRACK 03 AUDIO
    TITLE "Rubina"
    PERFORMER "Joe Satriani"
    INDEX 00 08:46:15
    INDEX 01 08:47:40
  TRACK 04 AUDIO
    TITLE "Memories"
    PERFORMER "Joe Satriani"
    INDEX 00 14:41:02
    INDEX 01 14:44:12
  TRACK 05 AUDIO
    TITLE "Brother John"
    PERFORMER "Joe Satriani"
    INDEX 00 18:48:22
    INDEX 01 18:50:15
  TRACK 06 AUDIO
    TITLE "The Enigmatic"
    PERFORMER "Joe Satriani"
    INDEX 00 20:58:55
    INDEX 01 21:00:72
  TRACK 07 AUDIO
    TITLE "Driving At Night"
    PERFORMER "Joe Satriani"
    INDEX 01 24:27:35
  TRACK 08 AUDIO
    TITLE "Hordes Of Locusts"
    PERFORMER "Joe Satriani"
    INDEX 00 28:00:22
    INDEX 01 28:01:00
  TRACK 09 AUDIO
    TITLE "New Day"
    PERFORMER "Joe Satriani"
    INDEX 00 32:57:60
    INDEX 01 33:00:17
  TRACK 10 AUDIO
    TITLE "The Headless Horseman"
    PERFORMER "Joe Satriani"
    INDEX 00 36:46:27
    INDEX 01 36:52:45
```

**Comment by Alexey-Yakovenko** [comment]
Ok thanks for the additional information, I'll see what can be done as soon as I have time.

**Comment by Alexey-Yakovenko** [comment]
I tested this cue with a test flac file, and it worked fine, both in 1.8.2 and trunk.
If you want to proceed with debugging this further, please contact me by email.

**Comment by Alexey-Yakovenko** [comment]
Closing the issue since I don't have anything to follow up with.
If you want to make this work -- please contact me privately.
