### ISSUE TITLE
Player sometimes crashes or deadlocks when attempting to play an Icy stream

### ISSUE THREAD

**Issue by ptkovsky** [DeaDBeeF-Player/deadbeef#2237]
### Steps to reproduce the problem
1. Add test playlist.
2. Try to play a specific entry.

### What's going on? Describe the problem in as much detail as possible.
In the test playlist featured in the issue https://github.com/DeaDBeeF-Player/deadbeef/issues/2235, there is an interesting entry `http://147.175.61.55:8000/` where DeadBeeF sometimes hangs and crashes when attempting to play it.

There is also another issue where when it does not hang, it plays mono sound instead of stereo.

I believe there is a problem with the source, but nevertheless, decided to report this behavior which seems very interesting and also sort of incorrect.

Other tested players do not hang and play stereo sound in this case.

### Information about the software:
Deadbeef version: b0cdeb0.
OS: macOS 10.15.

**Comment by ptkovsky** [comment]
Hi Alexey, thanks for your effort to fix the issue!

I quickly tested your yesterday's fixes, so when using https://github.com/DeaDBeeF-Player/deadbeef/commit/b257818658dedd681a13a8734163a18014a38834 and attempting to play the selected url ddress, the are two types of behavior:

1. Sometimes player immediately skips to the next playlist entry, and the Log windows pops out with the information (last part of it copied here):

`
selected output plugin: CoreAudio
resume: track -1 pos -1.000000 playlist -1
No suitable decoder found for stream http://147.175.61.55:8000/ of content-type audio/mpeg`

2. When clicking again in the next moment, player sometimes starts playing this same stream, but the above-mentioned bug with mono sound playback is still observed.

**Comment by Alexey-Yakovenko** [comment]
This is not what I was fixing. What you're observing is a different issue (actually multiple issues), described in #2235 that you reported.

**Comment by Alexey-Yakovenko** [comment]
So I investigated the stream at the URL in question.
It is actually mono. Maybe it becomes stereo at some point, I don't know, but at the time of writing this message -- it is mono.

**Comment by ptkovsky** [comment]
Yeah sure, looks like a separate issue.

About mono, remember I previously wrote that other tested players play stereo sound in this case? Here I was a little confused about what the correct behavior should be. I thought that DeaDBeeF may transform sound to stereo even when source is mono, like other players do it in this case. Technically and strictly speaking, playing mono here is the correct and expected behavior - what you get is what you output.
