### ISSUE TITLE
Question or Bug? I Thought The System Tray Icon Was Different?

### ISSUE THREAD

**Issue by 0pLuS0** [DeaDBeeF-Player/deadbeef#2239]
### Steps to reproduce the problem
I just run deadbeef

### What's going on? Describe the problem in as much detail as possible.
When I run deadbeef, I thought the system tray icon was the black and green color that appeared in the icons shown in the ```icon``` source directory?

### Information about the software:

Deadbeef version: 0.7.2
OS: Slackware 14.2 x64
Openbox 3.6.1

It's been a long time since I've used deadbeef, but I thought the last time I used it, that the system tray icon was the black and green color that are the icons listed in the icon directory of the source?

When I run deadbeef I have a silver and white icon appearing in the system tray that I have no idea where it's coming from.

I've attached a screen shot of this silver and white system tray icon, and I'm also attaching an icon from the source code, I assumed would appear in the system tray.

I really like the black and green looking icons and would like this to appear in my system tray.

![system_tray](https://user-images.githubusercontent.com/36190223/66636190-31225700-ec00-11e9-9413-7c466d093cd1.jpg)

![deadbeef](https://user-images.githubusercontent.com/36190223/66636199-35e70b00-ec00-11e9-9059-c40cdff947d5.png)

THANKS

**Comment by Alexey-Yakovenko** [comment]
The icon you're seeing comes from the currently selected icon theme on your computer.

**Comment by 0pLuS0** [comment]
@Alexey-Yakovenko HI

Ahh my mistake, I forgot about the icon themes, is there anyway to override this, without having to change all the icons for deadbeef in an icon theme?

SORRY I guess I must of been using an icon theme in the past that didn't have icons for deadbeef and forgot... :(

THANKS

**Comment by Alexey-Yakovenko** [comment]
It should be possible to specify a custom icon somewhere in deadbeef preferences, and use that to force it to use the default one.

**Comment by 0pLuS0** [comment]
All I see is in the Preferences > Plugins > GTK2 User interface: configure

```Custom status icon``` -  deadbeef_tray_icon

Other then this, not really sure, and not really sure if this is the option you are talking about, and if it, how to do this?

THANKS

**Comment by Alexey-Yakovenko** [comment]
I think you may put an absolute path to a PNG file in there.

**Comment by 0pLuS0** [comment]
Ok thanks...
