### ISSUE TITLE
[user story] Remember the last used directory

### ISSUE THREAD

**Issue by ussko** [DeaDBeeF-Player/deadbeef#2240]
It's not critical, but it's irritating. When I add more directories to a playlist I have to start browsing my filesystem anew from my home directory. If memory serves, in previous versions of DeaDBeeF I never faced such issues. I used to start browsing from the last directory I added.

Deadbeef version: 1.8.1
OS: Debian Linux 10.1

**Comment by Alexey-Yakovenko** [comment]
This was fixed in 1.8.2
