### ISSUE TITLE
plugin vfs_zip.so not found or failed to load

### ISSUE THREAD

**Issue by ytingone** [DeaDBeeF-Player/deadbeef#2242]
### Steps to reproduce the problem
just open deadbeef

### What's going on? Describe the problem in as much detail as possible.
there are a log window show this

### Information about the software:
1.8.2

Deadbeef version:1.8.2
OS: Manjaro

**Comment by Alexey-Yakovenko** [comment]
You should either install the optional dependencies for zip support, or ask the package maintainer to make said dependencies mandatory.
