### ISSUE TITLE
Starting playback by resuming previous session doesn't induce DB_EV_SONGSTARTED

### ISSUE THREAD

**Issue by loskutov** [DeaDBeeF-Player/deadbeef#2247]
### Steps to reproduce the problem
- Make sure the "Resume previous session on startup" option is enabled
- Start playback
- Restart DeaDBeeF
- The playback should be active, plugins receive the `DB_EV_TRACKINFOCHANGED` and `DB_EV_PLAYLISTCHANGED` events
- Stop playback, restart the player
- No playback active, plugins receive the same set of events

### What's going on? Describe the problem in as much detail as possible.
The issue here is that there's no simple (stateless) way on the plugin side to see that a song has started playing (the two cases above are indistinguishable unless you inspect `ctx->started_timestamp`). I think it would make sense to send `DB_EV_SONGSTARTED` in the case when a song actually started playing.
### Information about the software:

Deadbeef version: 1.8.2
OS: Linux

**Comment by kuba160** [comment]
I had a discussion with Alexey about playback status and generated events:

![image](https://user-images.githubusercontent.com/6359901/67503798-8cd0f380-f688-11e9-856b-d28007cf833e.png)
---
![image](https://user-images.githubusercontent.com/6359901/67503841-a1ad8700-f688-11e9-9e28-c0584f390596.png)

As I understand there is currently no way to tell playback status from the events with 100% coverage of all scenarios.

**Comment by loskutov** [comment]
Thanks for the info. However, I don't see how emitting a new event could break backward compatibility, so hopefully it's not the case here.

**Comment by Alexey-Yakovenko** [comment]
> The issue here is that there's no simple (stateless) way on the plugin side to see that a song has started playing (the two cases above are indistinguishable unless you inspect ctx->started_timestamp)

This is correct. There's no such way, and as was written before -- it's not possible to make such way without significantly changing the plugin API. Right now plugins have too much control, and may call low-level functions to pause/play/stop playback, without sending any events. Deadbeef doesn't have any way to detect these calls.

**Comment by Alexey-Yakovenko** [comment]
So to summarize why emitting a new event wouldn't solve anything:

your code would rely on this event, but then you'll encounter a situation where another plugin controls playback, and this event is still not sent. then you would still have to use a timer and poll the current state.

**Comment by loskutov** [comment]
I would suppose a situation where another plugin controls plugin bypassing the event-sending mechanism is an issue in the other plugin that should be fixed. For example, mpris2-plugin manages playback by sending messages. However, badly written plugins is one thing, the player itself is a different one. As the events mechanism exists in the first place, I think it's a reasonable assumption to make that at least the player itself respects this mechanism and sends appropriate events whenever playback is started.

**Comment by Alexey-Yakovenko** [comment]
I just double checked the code, and found that the DB_EV_SONGSTARTED is being sent on startup during the resume.
This makes this issue invalid.
