### ISSUE TITLE
Terminate after throwing Gio::ResolverError 

### ISSUE THREAD

**Issue by dakeryas** [DeaDBeeF-Player/deadbeef#2249]
### Steps to reproduce the problem
Load a new album into a playlist and try to play a song from it. It happens randomly with new albums, so it seems difficult to reproduce perfectly.

### What's going on? Describe the problem in as much detail as possible.
The crash happened when loading a new APE+CUE album from the Gnome Filebrowser into DeaDBeeF's main playlist, and *then* clicking on a track to play it. I tried to empty the playlist and load the same album again, it would also crash as soon as I would click on a track to play it. 

The trick was to load another album, play a song for a few seconds, then reload the "problematic album". Now the "problematic" album would not crash DeaDBeeF, but it seems to randomly choose problematic albums for such crashes.

### Information about the software:

Deadbeef version: Devel (from 2019-10-13) from http://ppa.launchpad.net/alex-p/deadbeef/ubuntu/dists/disco/main/binary-amd64/by-hash/SHA256/
OS: Ubuntu Disco 19.04 (Gnome)

Detailed terminal log:
[deadbeef.log](https://github.com/DeaDBeeF-Player/deadbeef/files/3775772/deadbeef.log)

(only the last two lines are unusual:
terminate called after throwing an instance of 'Gio::ResolverError'
[1]    3199 abort (core dumped)  GTK_THEME=Yaru-dark deadbeef
 the warnings are shown when DeaDBeeF is working fine).

**Comment by dakeryas** [comment]
I think it is actually related to the source code of lyricbar from `https://github.com/loskutov/deadbeef-lyricbar` since the code contains `auto gfile = Gio::File::create_for_uri(uri);`.

I have rebuilt the plugin catching the exception and printing more information, but since the crash seems random, it is very difficult to reproduce it and check that it comes from that plugin indeed.

**Comment by Alexey-Yakovenko** [comment]
Deadbeef doesn't use GTKMM (C++ version of GTK), and doesn't include "create surf" string.
The error is caused by a plugin, and you should report a bug to the developer of that plugin.
The workaround is, as usual, to uninstall the problematic plugin.
