### ISSUE TITLE
How to update deadbeef player if using the universal package for Debian

### ISSUE THREAD

**Issue by Heliosstyx** [DeaDBeeF-Player/deadbeef#2250]
### Information about the software:

Deadbeef version: actual
OS: Debian Buster

How I can update deadbeef player when I use the universal package .deb for Debian: 1. first removing the old package 2. install the new package or is there another way to automatically update the software? 

Thank you.

**Comment by Alexey-Yakovenko** [comment]
You should not need to delete the old package, unless the old one was installed from another source, e.g. a PPA or a some sort of deb repository.

**Comment by Alexey-Yakovenko** [comment]
There's currently no way to update deadbeef automatically.
