### ISSUE TITLE
partial dropping sound while playing from list after non-existing files.

### ISSUE THREAD

**Issue by dieug** [DeaDBeeF-Player/deadbeef#2254]
### Steps to reproduce the problem
1. make list from music dir.
2. delete some of files outside player from music dir
3. go on playing list
4. after errormessage in new window next sound files has shuttering and has partially disappeared pieces of sound. other pieces playing linearly, no pause, no silence in track.
5. for normal playing player has to be stopped and get playing again.

### What's going on? Describe the problem in as much detail as possible.

when file exists in player's list and not exists on fs, player cuts out and eats alive pieces of sound in next playing files.
it listens as "shuttering" in music.

### Information about the software:
deadbeef 1.8.2
debian testing x64

**Comment by Alexey-Yakovenko** [comment]
Thanks for reporting this. It was quite a serious and hard to debug case, but it was worth to dig in.
