### ISSUE TITLE
[PACKAGE REQUEST] Please add DeaDBee to Fedora repositories

### ISSUE THREAD

**Issue by silvioprog** [DeaDBeeF-Player/deadbeef#2256]
Hi.

It would be nice to make DeaDBee available in [Fedora](https://getfedora.org) allowing the user to install it via `# dnf install deadbeef`.

Thank you!

**Comment by Alexey-Yakovenko** [comment]
I don't think that anybody who could potentially read your message on this bug tracker will be able to help you. Linux distribution repositories is a closed / proprietary ecosystem, fully controlled by the developers / owners of the respective distros. You should contact Fedora support on their forums or bug tracker instead.

**Comment by silvioprog** [comment]
Thanks for answering. Unfortunately, it seems it isn't possible to add DeaDBeeF to Fedora repositories due to patent reasons: https://bugzilla.redhat.com/show_bug.cgi?id=520712

**Comment by Alexey-Yakovenko** [comment]
@silvioprog That's a cover-up and not a real reason. Especially since mp3 patents expired a few years ago. And also deadbeef can super-easily be compiled without any mp3 support.

Not that it would help to get into Fedora repos or similar.
