### ISSUE TITLE
Playlist doesn't redraw after drag-dropping files

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2264]
As far as I can see, the commit 

> commit 6db284b012ddcff990a1f0eda0afc341c3a015a2 (HEAD -> Seeking)
> Date:   Mon Nov 4 19:01:51 2019 +0100
> 
> cocoaui: fix replaygain scanner not triggering playlist save after changing file tags, also fix a typo in plt_save (#2257)

causes new errors. For example: drop files into a playlist no longer works, doesn't display files, only after restart or removing all tracks from playlist no longer works properly.

**Comment by Alexey-Yakovenko** [comment]
Thanks, I think it correlates with another report posted on Slack by @kuba160
