### ISSUE TITLE
An icy stream sometimes failing to play

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#2267]
### Steps to reproduce the problem

Play http://147.175.61.55:8000 multiple times.

### What's going on? Describe the problem in as much detail as possible.

The stream eventually fails to play, logging an error message

### Information about the software:

Deadbeef version: trunk
OS: all

@ptkovsky FYI

**Comment by Alexey-Yakovenko** [comment]
This problem happens because of an old hack, that relied on allocated pointers to be unique every time when HTTP_FILE structure is malloced, which is not the case.

**Comment by ptkovsky** [comment]
Very interesting, thank you for the detailed explanation of this issue.
