### ISSUE TITLE
Recent streamer commits broke playback

### ISSUE THREAD

**Issue by shoober420** [DeaDBeeF-Player/deadbeef#2268]
### Steps to reproduce the problem
Attempt to start track

### What's going on? Describe the problem in as much detail as possible.
Deadbeef will crash
### Information about the software:

Deadbeef version: https://github.com/DeaDBeeF-Player/deadbeef/commit/2eb8c10a7c11b8219798c4c37fb3f4f818af7c1d
OS: Arch Linux

```
gtkui plugin compiled for gtk version: 3.24.12
connecting button tray signals
Segmentation Fault
deadbeef: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
zsh: abort (core dumped)  deadbeef
```

**Comment by Alexey-Yakovenko** [comment]
works fine here, both mac and linux. can you provide backtrace?
