### ISSUE TITLE
Grouping fail on some albums

### ISSUE THREAD

**Issue by fabien-michel** [DeaDBeeF-Player/deadbeef#2273]
### Steps to reproduce the problem
Setup a playlist grouping to : 
- `%album artist% ['['%year%']' ]  %album% #%discnumber%`
-  OR just `%album%`

### What's going on? Describe the problem in as much detail as possible.
The groups are mis-created
The group is splitted into multiple groups bad ordered.

![deadbeef](https://user-images.githubusercontent.com/1167556/70146120-dce8a000-16a1-11ea-8ed4-364ed2b13cc7.png)

I expect deadbeef to group tracks by the returned value of the pattern and not some hided informations.
In the screenshot below, i expect two groups:
- `Ibrahim Maalouf [2018-11-16] 14.12.16 - Live in Paris #1`
- `Ibrahim Maalouf [2018-11-16] 14.12.16 - Live in Paris #2`

I'm not sure what can cause this behavior. multi-disc albums ? multi-artists (feat.) inside an album ?

### Information about the software:

Deadbeef version: 1.8.2
OS: Arch Linux

**Comment by kpcee** [comment]
Did you tag your music correctly? The behavior is normal for different artists in an album, in such a case you have to set %album artist% accordingly. For example "VA" or "Various Artists".

**Comment by fabien-michel** [comment]
Yes,  the music is tagged using MusicBrainz picard. The grouping pattern in the screenshot is `%album artist% ['['%year%']' ] %album% #%discnumber%` (so i'm already using `%album artist%`)
The problem occure even with only `%album%` as grouping pattern. 
In the screenshot you can see that the string of each group is the same (except for disc number)
DeadBeef seems to not grouping using the string output but something else.

**Comment by Alexey-Yakovenko** [comment]
It's quite clear that you confuse grouping with sorting.
The grouping doesn't change the ordering of tracks - by design.

If you want to see only 2 groups in playlist - you must also sort playlist by the same pattern (sort -> Custom).

**Comment by fabien-michel** [comment]
Ok i think I've finally understand. I need to have a column sorted by %album artist% too !
It was not obvious for me.
