### ISSUE TITLE
[feature request] album artwork & progressive jpgs

### ISSUE THREAD

**Issue by ghcatt** [DeaDBeeF-Player/deadbeef#2276]
how about support for progressive jpgs within album artwork?

**Comment by Alexey-Yakovenko** [comment]
Deadbeef is supposed to load progressive jpegs just like any other jpegs.
And I don't think there are any problems with that.

**Comment by ghcatt** [comment]
hm, i saved various pngs to progressive jpgs with the help of xnviewmp. they are only displayed in nonprogressive mode. so perhaps not deadbeef related.

on the other hand - foobar via wine would display both variants without problems (tested with various images).

**Comment by Alexey-Yakovenko** [comment]
What do you mean by "non-progressive mode"?

**Comment by ghcatt** [comment]
i mean saved as standard jpg.

**Comment by Alexey-Yakovenko** [comment]
what is the difference from user's standpoint? you should see the same picture.

**Comment by ghcatt** [comment]
about 20% reduction in filesize ;)

i would like to go all way progressive with jpgs.

**Comment by Alexey-Yakovenko** [comment]
That's not what I asked about.
I mean, you're implying that deadbeef doesn't load them correctly.
What is wrong? What do you see instead of the expected result?

**Comment by ghcatt** [comment]
sorry, missed that.

t shows nothing here (say blank).

**Comment by Alexey-Yakovenko** [comment]
so what you're saying, is that if you convert an image into progressive jpeg, and put it into a music folder as cover.jpg, all you see is blank? not even the default album image?

**Comment by ghcatt** [comment]
i retested with some progressive jpgs and all is working just fine. i don't know why it occured so constantly before?

sorry for the confusion.
