### ISSUE TITLE
album artwork - display custom image fails

### ISSUE THREAD

**Issue by ghcatt** [DeaDBeeF-Player/deadbeef#2277]
selecting a custom image as nocover-image in deadbeef 1.8.2 has no effect at all (remains blank)?

i tried with png and jpg images under various locations.

**Comment by Alexey-Yakovenko** [comment]
You are doing something wrong. It works as designed.

**Comment by ghcatt** [comment]
yes, indeed.

i assumed the nocover image to be displayed permanently (also for empty playlists). this is what i favour and tried to accomplish.

the same goes for the now-playing cover images. can they simply reflect the chosen (non-playing) song in playlist?

**Comment by Alexey-Yakovenko** [comment]
I don't think that deadbeef can be configured to what you described.

**Comment by ghcatt** [comment]
ok, nevermind.
