### ISSUE TITLE
reflecting song ratings as symbols?

### ISSUE THREAD

**Issue by ghcatt** [DeaDBeeF-Player/deadbeef#2278]
is it possible to reflect song ratings as symbols (in a row) in a custom column, so to have ♫♫♫♫♫ rather than just a number 5?

**Comment by Alexey-Yakovenko** [comment]
Yes, it should be possible.
E.g. by `$repeat(★,%rating%)$repeat(☆,$sub(5,%rating%))`
(I haven't verified this code, but you should get the idea)

**Comment by ghcatt** [comment]
thanks a lot, will try this.

**Comment by ghcatt** [comment]
works like charm, thank you.
