### ISSUE TITLE
filename=album-artwork-name?

### ISSUE THREAD

**Issue by ghost** [DeaDBeeF-Player/deadbeef#2279]
is this possible as of now: name-of-song.flac=name-of-song.png?

this way, one could have (external/nonembedded) albumartwork displayed for each individual song in a given folder.

**Comment by Alexey-Yakovenko** [comment]
I'm not entirely sure, but I don't think it's possible with the current code.

**Comment by mallniya** [comment]
As for https://github.com/DeaDBeeF-Player/deadbeef/issues/559 this issue is superseded by https://github.com/DeaDBeeF-Player/deadbeef/issues/1131
