### ISSUE TITLE
[feature request] open containing folder in filemanager

### ISSUE THREAD

**Issue by ghost** [DeaDBeeF-Player/deadbeef#2280]
via context menu entry on selected song. a quick jump feature.

**Comment by kpcee** [comment]
This is already possible, see [Open location from track context menu](https://github.com/DeaDBeeF-Player/deadbeef/issues/1610).

**Comment by ghcatt** [comment]
ok, i see. thanks a lot ;)

**Comment by Alexey-Yakovenko** [comment]
Will keep this open as an enhancement, since people are asking for this too often, not realizing how to make it work.
Possibly I should come up with some solution for predefined shellexec commands.

**Comment by pinballmachine** [comment]
I hope you still consider adding this as a default entry in the context menu. I found the solution by searching the open issues list, so it appears it can be made to work already, but having it by default would make life easier for a lot of people, I think.

**Comment by Alexey-Yakovenko** [comment]
Yes, I'm considering. It grew on me that this should be a default option, instead of the user having to configure it every time.

**Comment by mallniya** [comment]
Duplicate of https://github.com/DeaDBeeF-Player/deadbeef/issues/1526
