### ISSUE TITLE
show rating for mp3?

### ISSUE THREAD

**Issue by ghcatt** [DeaDBeeF-Player/deadbeef#2282]
i hope this has not been addressed before.

i have rated my collection of flacs and mp3 (id3v2 tags, more compatible) with the help of foobar (RATING field name).

the ratings show up just fine in deadbeef via a custom column ($repeat(⬥,%RATING%)$repeat(⬦,$sub(5,%RATING%))), but not for mp3s (just blank).

in mp3tag, the field name for mp3 is reflected as RATING WMP.

how to get _all_ ratings displayed correctly within the rating column (without retagging)?

**Comment by Alexey-Yakovenko** [comment]
sounds like the id3v2 rating field is not supported by deadbeef.

**Comment by ghcatt** [comment]
out of curiosity, i checked the remaining rating fields within mp3tag and tagged a few mp3s with it.

RATING MM
RATING WINAMP
RATING WMP

not sure if i used the correct values for these fields (i tried with 3), but they all seem to suffer from that possible bug. foobar is ok, db has no stars displayed for any of them.

**Comment by Alexey-Yakovenko** [comment]
I double-checked. Deadbeef preserves the POPM frames in id3v2 during tagging / conversion, but it doesn't convert them into text fields which could be used with title formatting.

Not a bug as such, and I believe there's at least one plugin that handles POPM somehow, but I think this should be relatively easy to fix.

**Comment by Alexey-Yakovenko** [comment]
Detailed breakdown of mapping POPM rating value to [0..5] (stars)
https://github.com/DeaDBeeF-Player/deadbeef/issues/1143#issuecomment-217169127

These 2 issues are very similar, but I'm not sure if they're the same, as this one is more focused on the title formatting side of things. I think both of them may be closed if this one is done.

**Comment by Alexey-Yakovenko** [comment]
A better and more reliable title formatting script:
```
$progress2($max(0,$min(5,%rating%)),5,5,★,☆)
```

It's simpler, and takes into account that rating is not necessarily stored in [0,5] range (a user can set it to any string)

**Comment by Alexey-Yakovenko** [comment]
(This requires the latest revision of deadbeef, since it fixes a bug in $progress and $progress2 impl, which caused this script to crash)
