### ISSUE TITLE
a few more feature requests

### ISSUE THREAD

**Issue by ghcatt** [DeaDBeeF-Player/deadbeef#2283]
probably not worth turning into separate issues?

_be able to mark all metadata in track properties for mass-editing (copy/cut/paste/remove) tags
highlight plugins installed by user + alphabetical sorting
make active playlist tab more prominent by default - quite difficult to distinguish from inactive ones atm (dark system theme though)
move seekbar via mousewheel
offer reset page/all buttons in settings
option to choose a default playlist format (say m3u8) + defined path
option to have tab & column names centered as well
option to save playlists with relative paths (../path/to/music/song.flac)
right click on a playlist tab: save playlist/all playlists_

perhaps add the symbol-rating column as a default? looking very neat, thanks again @alexey.

this could also be a nice addition - i made up a replaygain column, so to have a quick glimpse on tracks missing track / album gain:

format:  $if(%replaygain_track_gain%,♪♪  )$if(%replaygain_album_gain%,♫)

i just do not seem to find unfilled variants of notes to be used as placeholders, when rg is missing ;)

all the best

**Comment by Alexey-Yakovenko** [comment]
Closing as invalid, since every bug report or a feature report needs to be in a separate case.

**Comment by ghcatt** [comment]
agreed. i have more (time wasting) suggestions for db, might be splitting them one by one at a later point ;)
