### ISSUE TITLE
consistency of tag field names across formats

### ISSUE THREAD

**Issue by ghcatt** [DeaDBeeF-Player/deadbeef#2284]
first off, i am clearly no expert in this matter, so please appologize, if this is all a bit too vague.

this is about consistency of tag field names across formats.

now, here is the issue i was currently facing with mp3 (id3v2.3), while setting up custom columns in deadbeef for valid field names in my collection:

looking at the properties window of deadbeef, "custom" field names are displayed like this:

```
VorbisComments	ID3v2.3

<LANGUAGE>	<LANGUAGES>
<MEDIA TYPE>	<MEDIA_TYPE>
```

to have both columns displayed correctly for flacs and mp3, these format adjustments were needed:

%LANGUAGE%%LANGUAGES%

%MEDIA TYPE%%MEDIA_TYPE%

here is my question:

is there a global standard reference page for field names across formats, potentially to be adopted in deadbeef?

for instance, here is a page listing all ID3v2 tag frames natively supported by foobar2000:

https://wiki.hydrogenaud.io/index.php?title=Foobar2000:ID3_Tag_Mapping#cite_note-TXXX-1

the idea behind:

possibility to display all standard field names in deadbeef's properties window (without needing to create/adjust them) & making them avaiable in new column's type drop-down menu out of the box.

**Comment by Alexey-Yakovenko** [comment]
Deadbeef doesn't have a web page for that.
It does implement tag mapping internally, but that's not exposed to the user.
The language / languages and media type / media_type fields are not remapped at all, so it works "as-is", which is why you experience that problem.

**Comment by ghcatt** [comment]
thank you for replying.

ok, so prior to achieve consistency in tag field names for all formats, all possible tag remappings would have to be done in first place?

**Comment by Alexey-Yakovenko** [comment]
There's no such thing as "all possible tag remappings".
The number is infinite.

**Comment by ghcatt** [comment]
'all' (of that linked list), to be more specific.

**Comment by Alexey-Yakovenko** [comment]
well, yeah, to solve your problem -- the fields in question need to be remapped.
