### ISSUE TITLE
Can't queue files from file manager

### ISSUE THREAD

**Issue by thumos333** [DeaDBeeF-Player/deadbeef#2285]
I click an mp3 file, or open a folder with Deadbeef. The Deadbeef playlist clears, the new file or folder is added.

What I want to do, however, is to queue the file/folder at the end of the existing (default) playlist. Can this be done from a Linux file manager?

Deadbeef version: 1.8.2
OS: Solus OS

Thanks!

**Comment by Alexey-Yakovenko** [comment]
It should be possible. You need to configure your FM to run deadbeef with `--queue` parameter.

**Comment by thumos333** [comment]
Okay, will let know here if I find something out.
