### ISSUE TITLE
The progress bar starts from the beginning when resuming if I have paused the song.

### ISSUE THREAD

**Issue by laichiaheng** [DeaDBeeF-Player/deadbeef#2286]
### Steps to reproduce the problem
1. Pause the song.
2. Close DeaDBeeF player.
3. Open DeaDBeeF Player.
4. Play the song.
### What's going on? Describe the problem in as much detail as possible.
The progress bar starts from the beginning of the song, the the timestamp of the song is correct.
1. Pause the song before I close the player.
![2019-12-17 22-03-35 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/71002273-e2ba9880-2119-11ea-8510-e2e9bce56169.png)
2. The progress bar starts from the begging, but the music starts from the right timestamp.
![2019-12-17 22-03-49 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/71002325-fb2ab300-2119-11ea-929c-571d26acfd42.png)

### Information about the software:

Deadbeef version: deadbeef-git  r8745.0a3a03193-1
OS: Manjaro

**Comment by Alexey-Yakovenko** [comment]
Hmm it looks like the same or related problem as #2274, but revision of your build is the one that fixed it..
I probably missed something. Will take a look.

**Comment by laichiaheng** [comment]
> Hmm it looks like the same or related problem as #2274, but revision of your build is the one that fixed it..
> I probably missed something. Will take a look.

Yes, the music plays fine, but the progress bar does not.

**Comment by Alexey-Yakovenko** [comment]
Hmm.. I can't reproduce this. Any other details?

**Comment by laichiaheng** [comment]
@Alexey-Yakovenko It seems only happens when I pause the song the second time.

**Comment by Alexey-Yakovenko** [comment]
Thanks for the video! I still can't reproduce, but trying.

**Comment by Alexey-Yakovenko** [comment]
I reproduced it. It happens in shuffle = tracks, and every time after changing from shuffle off to shuffle tracks. Doesn't happen if shuffle is off.
