### ISSUE TITLE
how to add open containing folder to the context menu in deadbeef running under windows

### ISSUE THREAD

**Issue by cpuuntery** [DeaDBeeF-Player/deadbeef#2290]
### Steps to reproduce the problem
Try to add open containing folder to the context menu in deadbeef running under windows
### What's going on? Describe the problem in as much detail as possible.
the first thing I would like to say I did my research before opening an issue. and I already saw #1526 and #2280 and the option exists if you are running Linux. but if you are running windows the option is not available. and I know open-source programmers hate windows with passion. and the fact that Windows uses backward slash and Linux uses forward slash. and for whatever reason, the plugin ShellExec can not be compiled for windows. I can understand why ffmpeg plugin can not be compiled for windows because ffmpeg is complex so that to be expected. but the ShellExec plugin is very simple. so I hope that you can make ShellExec run under windows. or you can give me patched dll that I can put in the plugin folder 
### Information about the software:
Deadbeef version:1.8.2
OS: windows
[![Capture.png](https://i.postimg.cc/NG3HY9n2/Capture.png)](https://postimg.cc/c6cHBH0d)
[![Capture.png](https://i.postimg.cc/05DNYttr/Capture.png)](https://postimg.cc/t7RyyzGH)
[![On-Paste-20191222-170142.png](https://i.postimg.cc/HW2dpjBs/On-Paste-20191222-170142.png)](https://postimg.cc/w37S2qCS)

**Comment by Alexey-Yakovenko** [comment]
@kuba160 seems like this is something for you

**Comment by Alexey-Yakovenko** [comment]
@cpuuntery I don't think that most / any deadbeef contributors hate windows :)
it's just that most of us use either linux or mac exclusively, and don't even have a windows PC in range.

**Comment by cpuuntery** [comment]
well, I may jumped to conclusions and used the word hate. but a lot of open-source developers don't care about windows because it is a closed source proprietary software. [an example](https://blog.hiri.com/a-year-on-our-experience-launching-a-paid-proprietary-product-on-linux-db4f9116be08) . the only open-source program that care about windows and doesn't care about Linux is  notepad++ . and maybe someday in the future, you may feel bored. and want to try something new. and I am fairly certain that adding the functionality of opening containing folder is very easy. you can run windows in a VM and try to figure out how to make ShellExec work under windows. a man can hope and dream. aside from the ability to open containing folder. deadbeef has everything l need in a music player. I have a good knowledge regarding computer Science and software development but I don't know how to program in c if I knew I would contribute the fixing code to the project

**Comment by Alexey-Yakovenko** [comment]
We have a couple of devs who made the windows port, and are probably using it daily. They should be able to help, we just need to wait till they have time to check github.

I personally don't care about windows indeed, but it has nothing to do with it being proprietary. In fact most of the software I'm using, including the os, is proprietary and often commercial. I just don't have resources to support windows as well 🤣

Hope you'll get your problem resolved soon.

**Comment by kuba160** [comment]
Shellexec is missing from premake build script. As I remember it was a part of build before premake. You can try to extract shellexec plugin from such build. I'm away from home now, I will work on it later.

Issue in DeaDBeeF for Windows repo:
https://github.com/DeaDBeeF-for-Windows/deadbeef/issues/15

**Comment by cpuuntery** [comment]
@Alexey-Yakovenko and @kuba160 I was able to fix it by downloading the dll from this [link](https://github.com/DeaDBeeF-for-Windows/deadbeef/releases/download/2018-04-30/deadbeef-x86_64-GTK2.zip) .and copy it to the plugin folder .and delete the config folder to force deadbeef to use gtk2 instead of gtk3 .ShellExec does not work if you use gtk3 and you need to create a .bat file to convert the forward-slash to backward-slash 
the bat file should be inside the deadbeef directory 
bat file code 
`@echo off
set folder_path=%~1
set the_path=%folder_path:/=\%
explorer.exe %the_path:'="%`
the ShellExec command is `open_folder.bat "%D"`

**Comment by Alexey-Yakovenko** [comment]
@cpuuntery you should not use `"%D"`, since shellexec adds quotes automatically, and your approach would cause double-quoting.

**Comment by Alexey-Yakovenko** [comment]
Closing the issue, since it's more a windows-specific thing, that's solved in a different repo.
