### ISSUE TITLE
Splitters can't reach the window edges anymore

### ISSUE THREAD

**Issue by JakeSFR** [DeaDBeeF-Player/deadbeef#2292]
This is as far as I can move them (current master):

![db_bad](https://user-images.githubusercontent.com/6226504/71449194-976f3e00-2748-11ea-9995-556031b8000a.png)

And this is how it used to look like (0.7.2):

![db_good](https://user-images.githubusercontent.com/6226504/71449196-9f2ee280-2748-11ea-8f22-9ff009301483.png)

This works for me, but most likely breaks something else (`_ddb_splitter_fix_proportion()` is there for a reason, I suppose):

```
diff -ur deadbeef-master_old/plugins/gtkui/ddb_splitter.c deadbeef-master_new/plugins/gtkui/ddb_splitter.c
--- deadbeef-master_old/plugins/gtkui/ddb_splitter.c	2019-12-24 17:44:22.000000000 +0100
+++ deadbeef-master_new/plugins/gtkui/ddb_splitter.c	2019-12-25 14:24:41.547351000 +0100
@@ -492,11 +492,11 @@
     if (size != splitter->priv->child1_size) {
         if (splitter->priv->orientation == GTK_ORIENTATION_HORIZONTAL) {
             float gripsize = (float)splitter->priv->handle_pos.width/a.width;
-            ddb_splitter_set_proportion (splitter, CLAMP ((float)size/a.width, gripsize, 1-gripsize*2));
+            ddb_splitter_set_proportion (splitter, CLAMP ((float)size/a.width, 0.0f, 1-gripsize));
         }
         else {
             float gripsize = (float)splitter->priv->handle_pos.height/a.height;
-            ddb_splitter_set_proportion (splitter, CLAMP ((float)size/a.height, gripsize, 1-gripsize*2));
+            ddb_splitter_set_proportion (splitter, CLAMP ((float)size/a.height, 0.0f, 1-gripsize));
         }
     }
 }
@@ -914,8 +914,7 @@
         }
         else {
             // two children visible and proportional scaling is active
-            float p = _ddb_splitter_fix_proportion(splitter, sp_priv->proportion);
-            size = ceilf (con_size * p);
+            size = ceilf (con_size * sp_priv->proportion);
         }
     }
     return size;
```

I have a very simple setup - a playlist w/ tabs in the upper part of the splitter and 3 visual plugins, in hbox, in the bottom part, but most of the time I don't want to see these 3 plugins, so I keep the splitter's handle at the very bottom of the window.
In 0.7.2 it looks just fine, but in the current build a small part is always visible:

![db_plugins](https://user-images.githubusercontent.com/6226504/71449199-a950e100-2748-11ea-9974-cc4a7ac25ee5.jpg)

**Comment by Alexey-Yakovenko** [comment]
It looks like the placeholder widget might have a minimum size which prevents it from becoming that small.

**Comment by Alexey-Yakovenko** [comment]
Your suggested fix is mostly correct, although I can't see any reason for 2nd part of the patch.
I applied a fix, and it works fine for my test. Does it work for you?

**Comment by JakeSFR** [comment]
Yeah, you're right about the placeholder widget - I wasn't aware of that and simply didn't test the 1st part of the patch with some real widgets.
And since it wasn't working, I figured something more is needed.
But it works with real widgets, indeed.
Thank you!
