### ISSUE TITLE
ReplayGain scanner has a memory leak

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2293]
If you use the Replaygain scanner to process music, you can see in the task manager how continuously the memory footprint will increase. This memory will not be released even if you cancel or finish the task. Just a few files are enough to see the effect.

Deadbeef version: current git version: https://github.com/DeaDBeeF-Player/deadbeef/commit/9027857f7660090f2a55aa83f2d2050e27597865
OS: Linux

![Beispiel](https://user-images.githubusercontent.com/39984895/71466480-f45a0b00-27bf-11ea-9a27-92aec4a3d3f7.png)

**Comment by Alexey-Yakovenko** [comment]
Not present in cocoaui -- seems like memory is released properly.

**Comment by Alexey-Yakovenko** [comment]
Confirmed leak in GTKUI

**Comment by Alexey-Yakovenko** [comment]
I can't find any significant leak. Valgrind says that the GtkWindow leaks, which is solvable via calling `gtk_window_close`, but I'm yet to find another API which would work with GTK2.

**Comment by Alexey-Yakovenko** [comment]
A-ha.. the memory leak only happens with GTK2, so I'm assuming it's a bug in GTK2 which got fixed in GTK3.

Although I'm wondering why are you getting any noticeable numbers in task manager.
Valgrind reports 416 bytes.

Anyway.. I can't see how I can fix it. Please let me know if you have any more information, or a way to reproduce this with more memory lost.

**Comment by kpcee** [comment]
In order not to say something wrong here, I downloaded the latest Git version and tried to reproduce the problem here with Gtk2 + Gtk3. During my first tests I could not completely reproduce my described behaviour, but when you process multiple files two things happen anyway:

1. During ReplayGain more and more memory is used by DeaDBeeF
2. The used memory is not always completely released

Example: Start with 44,2 MiB, 100 files that are replaygaint 4 times:
After 1 pass: 53,7 MiB memory consumption, consumption during the process over 106 MiB 
After 2 pass: 63,5 MiB memory consumption, consumption during the process over 106 MiB 
After 3 pass: 92,2 MiB memory consumption, consumption during the process over 106 MiB
After 4 pass: the same as 3

The main problem is the constantly growing memory footprint (300 files takes over 230 MB). This way the whole memory can fill up and cause the system to crash when processing several thousand files. On the picture you can see that DeaDBeeF takes up 4,5 GiB RAM after a few thousand files. Systems with less memory crash accordingly earlier.

**Comment by Alexey-Yakovenko** [comment]
I could not get any proof of that using Valgrind on linux and Leaks tool on mac, tried both GTK2 and GTK3. I found many other memory leaks though.

Perhaps it's some specific codec leaking memory, and it's not replaygain scanner itself?

**Comment by kpcee** [comment]
I have now tested it with ogg and flac and observed two things. First, the memory consumption drops back to almost the initial value after the scan is finished, but the memory consumption swells to similarly large values and can take hundreds of MB. The first test was done with MP3 files 320 CBR and here the memory is not completely freed. 

I have also started Valgrind and also get no indication of memory leakage. After 10 scanned files the leak is only 4 KiB. But the xfce4-taskmanager still shows thie increasing memory consumption. Strange.

```
==143922== LEAK SUMMARY:
==143922==    definitely lost: 4,469 bytes in 37 blocks
==143922==    indirectly lost: 15,269 bytes in 625 blocks
==143922==      possibly lost: 7,171 bytes in 40 blocks
==143922==    still reachable: 4,687,948 bytes in 42,115 blocks
==143922==                       of which reachable via heuristic:
==143922==                         length64           : 6,336 bytes in 99 blocks
==143922==                         newarray           : 1,936 bytes in 41 blocks
==143922==         suppressed: 0 bytes in 0 blocks
```

**Comment by Alexey-Yakovenko** [comment]
I think you might be looking at virtual memory allocation, which is not really showing how much memory is in use. But I don't really have enough information. I will need to do more experiments.

One good way that I used to use back in my linux days was to run htop, and look at the "RES" column, I don't know if this is still a good way.

**Comment by kpcee** [comment]
I have tried it and the values are very similar, start with 44 MiB and after multiple runs of ~150 files the memory consumption rises to 129 MiB and stays that way. 
By the way, I once reported a bug in another program which could not be reproduced with Ubuntu and Kubuntu, but possibly only occurred with Xfce. There I also had a memory problem and the program started to use all memory when it was started several times. But if this is only specific for Xfce again, I don't know. 

![start](https://user-images.githubusercontent.com/39984895/72367685-eaf7fa80-36fc-11ea-999b-971943e485db.png)
![end](https://user-images.githubusercontent.com/39984895/72367690-edf2eb00-36fc-11ea-9917-57fd61d3d1ac.png)
