### ISSUE TITLE
'File -> Add location' doesn't work anymore

### ISSUE THREAD

**Issue by JakeSFR** [DeaDBeeF-Player/deadbeef#2294]
Linux, current master (f34deffcc0202c4196235b05e74d74dc2b04fb74).

I'm no longer (as opposed to v0.7.2 and, I just checked, v1.8.2) able to add any streams via 'Add location' option.
Just nothing happens and there's nothing in log/terminal output either.

It seems that the culprit lies right here:
https://github.com/DeaDBeeF-Player/deadbeef/commit/8204a9ada0e1f2e45f6ddb236ee1c4f0c0545f7d#diff-175f6cef69ed1cd1d6c8f597cc51b098L263-R267
```
-                    DB_playItem_t *it = deadbeef->plt_insert_file2 (0, plt, tail, text, NULL, NULL, NULL);
 #ifndef DISABLE_CUSTOM_TITLE
+                    DB_playItem_t *it = deadbeef->plt_insert_file2 (0, plt, tail, text, NULL, NULL, NULL);
```
After reverting this part, it started working again, but am not sure if that's the right way to fix it...

**Comment by Alexey-Yakovenko** [comment]
Thanks for spotting this! Seems like a result of a bad merge.
I'm surprised nobody noticed this before.
Will check as soon as I can.
