### ISSUE TITLE
ERROR: could not load: .opus file

### ISSUE THREAD

**Issue by Jee-bit** [DeaDBeeF-Player/deadbeef#2295]
### Steps to reproduce the problem
try loading or open an .opus file
### What's going on? Describe the problem in as much detail as possible.
Deadbeef cannot open the file
### Information about the software:
in Archlinux forums, one mentioned that it is a build problem solved by adding deb 'opusfile' but I don't know how tobuild and perhaps others will want to play or convert .opus files too
Deadbeef version:1.81 and 1.82
OS:debian

**Comment by Alexey-Yakovenko** [comment]
Here, I made a build https://deadbeef.sourceforge.io/download.html

**Comment by Jee-bit** [comment]
Pardon me, Thank you for your quick response, which one should I download, I downloaded every file again (for Debian
https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8.2/deadbeef-static_1.8.2-1_x86_64.tar.bz2/download
http://sourceforge.net/projects/deadbeef/files/travis/linux/1.8.2/deadbeef-static_1.8.2-1_amd64.deb/download
and all of them still give the same error ERROR: could not load: .../Exegesis.opus
https://bugs.archlinux.org/task/63484

**Comment by Alexey-Yakovenko** [comment]
I am still not 100% sure which linux distro you are using, since you mentioned both Arch and Debian.
There are packages for either of them - just read the text more carefully on the download page.
You can also download a universal archive that works without installing -- just unpack and run.
Opus works in all of them, without any external dependencies.

**Comment by Jee-bit** [comment]
Sir I'm using debian bullseye/sid and I downloaded the Archives as mention above on your download page unpacked and ran as you say ans as I mentioned in the duplicate post I downloaded everthing that will run on debian...
I mentioned Arch because those programmers confirmed the problem on this link
https://bugs.archlinux.org/task/63484
thank you for your help please

**Comment by Alexey-Yakovenko** [comment]
I don't think that library problems on archlinux can be the same as on debian, or the same as in statically linked binaries. Do you see the opus plugin in the plugin list in deadbeef preferences?

**Comment by Jee-bit** [comment]
Thank You for answering, yes i see the plugin, configure is greyed out though, is that normal
![Screenshot_deadbeef](https://user-images.githubusercontent.com/59305278/71546095-e9f46880-299b-11ea-9e05-f814e1ac79ca.png)

**Comment by Alexey-Yakovenko** [comment]
Yeah, it's normal and it indicates the plugin is working. You probably got a corrupt opus file. It can also be something entirely different, but with this little information this is all I can guess.

**Comment by Jee-bit** [comment]
Thank You so Much Sir, I didn't think it was corrupt because the opus file plays in 3 other players, however I downloaded sample files from xiph.org and the plugin works fine, so I will trouble shoot my file which I downloaded from Youtube, it was an audio stream from a video...
Thanks Again

**Comment by Alexey-Yakovenko** [comment]
Well it clearly states it's matroska/webm, which isn't supported by deadbeef, even if encapsulated audio is opus.

**Comment by Jee-bit** [comment]
Yes I see that about the container, thanks again, I love this player been using it for 3 years, don't want to look for another,
Thank You

**Comment by JakeSFR** [comment]
@Jee-bit: You can simply extract the audio stream (without converting it):

`ffmpeg -i infile -vn -acodec copy outfile.opus`

and DB should play it just fine.
