### ISSUE TITLE
Spectrum widget sometimes doesn't work

### ISSUE THREAD

**Issue by JakeSFR** [DeaDBeeF-Player/deadbeef#2298]
Let's use the following setup:
- Splitter (top and bottom)
- Playlist with Tabs in upper part
- HBox in lower part
- Spectrum in the 1st field of the HBox

Also, "Resume previous session on startup" must be enabled.

Now, while DB is playing a track, close it and launch again.
Song starts playing automatically, but the Spectrum widget is dead and it's necessary to press the Play button to revive it.

It seems to be GTK2 specific issue, can't reproduce it with GTK3.

**Comment by Alexey-Yakovenko** [comment]
Should be fixed now

**Comment by JakeSFR** [comment]
Ok, so I was able to reproduce it again a few times with some older build, but not even once with the current one.
Thanks!
