### ISSUE TITLE
Is it possible to support replaygain for DSF audio?

### ISSUE THREAD

**Issue by laichiaheng** [DeaDBeeF-Player/deadbeef#2305]
### Steps to reproduce the problem
Try to apply replaygain to DSF audio.
### What's going on? Describe the problem in as much detail as possible.
It fails.
### Information about the software:

Deadbeef version: deadbeef-git  r8770.fe514eeb3-1
OS: Manjaro

**Comment by laichiaheng** [comment]
I was wrong, it did add the replaygain to the file, although it display the error message.

**Comment by laichiaheng** [comment]
I was wrong again, it lost the replaygain data if I remove it from playlist.

**Comment by Alexey-Yakovenko** [comment]
DSF is supported via ffmpeg, and the ffmpeg plugin doesn't support tag writing.
I don't know how hard or easy it is to add such functionality, and I don't know whether DSF files support arbitrary metadata tags.

**Comment by Alexey-Yakovenko** [comment]
duplicate of #1603
