### ISSUE TITLE
MP3 file durations not correct

### ISSUE THREAD

**Issue by r-preston** [DeaDBeeF-Player/deadbeef#2309]
### Steps to reproduce the problem

Issue is inconsistent but persistent. Only some MP3s are affected, but those affected always have the same problem when Deadbeef is closed and reopened.
Willing to provide an MP3 that has the bug.

### What's going on? Describe the problem in as much detail as possible.

Some MP3s (no apparent pattern) show an incorrect duration in properties and on the now playing line. This false duration is always larger than the true duration by amounts ranging randomly from 5s to 60s.

When playing, the seek bar fills up as if the file has the wrong duration, and when the true duration is reached it skips to the next file.

See image attached for example

### Information about the software:

Deadbeef version: 1.8.2
OS: Arch Manjaro 18.1.5 Juhraya (Linux 4.19)
Desktop manager: i3 v4.17.1

![2020-01-13-135030_1920x1080_scrot](https://user-images.githubusercontent.com/29921297/72261497-dc321a80-360c-11ea-854a-7aec5294fdda.png)

**Comment by Alexey-Yakovenko** [comment]
The only way for me to investigate and fix the problem is if you provided a test file which demonstrates the problem. Please do this over the email.

**Comment by r-preston** [comment]
Hi Alexey

I've uploaded two examples that show the behaviour and one that does not at
this drive folder:
https://drive.google.com/open?id=1q2nroGFBP5BkNF1OcAMl7zZ4Q81vxWvD
I tried to send via email but the max attachment size is too small for
audio files.
I hope this helps.
