### ISSUE TITLE
"direct hardware device…" on Arch-based distro

### ISSUE THREAD

**Issue by Nelaer** [DeaDBeeF-Player/deadbeef#2313]
### Steps to reproduce the problem
1) install or download portable version of deadbeef
2) start the DeadBeef 
3) choose ALSA output plugin
4) open "Output device:" list
### What's going on? Describe the problem in as much detail as possible.
There are no options "direct hardware device *" on Arch-based distros, but on the same laptops there are on Debian-based distros.
### Information about the software:

Deadbeef version: 1.8.2
OS: Archlinux/Manjaro

**Comment by Alexey-Yakovenko** [comment]
The list of devices is part of ALSA / PulseAudio configuration. Deadbeef just displays the list, which it gets from ALSA, but it's not creating the list.

**Comment by Nelaer** [comment]
Thank you for reply
