### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by BRTPOB** [DeaDBeeF-Player/deadbeef#2319]
This is more of a question than a problem, but I've found how to sort my music, though I haven't figured out how to group them properly. How do I do that? I'm trying to copy my sorting/grouping from foobar, and it looks like DeaDBeeF is exactly what I want since the wine usage of foobar is destroying my system.

Thanks for the great app, and the help.

**Comment by Alexey-Yakovenko** [comment]
You can do grouping by right clicking the column headers, and using the context menu.
It's not exactly like foobar, since there are no grouping presets (yet), but it's pretty close nevertheless.
