### ISSUE TITLE
Gapless doesn't work when manually modifying playing tracks

### ISSUE THREAD

**Issue by BRTPOB** [DeaDBeeF-Player/deadbeef#2320]
### Steps to reproduce the problem
While playing a song with other songs in the playlist/queue, press Next (button, B, however); press C to pause, or press the pause button; press V to stop or press the stop button.
### What's going on? Describe the problem in as much detail as possible.
The gapless transition that occurs when a song naturally ends and moves into the next one doesn't exist, so it's very apparent and jarring when it occurs.
### Information about the software:

Deadbeef version: 1.8.3-alpha1
OS: Ubuntu 19.10

**Comment by Alexey-Yakovenko** [comment]
What you wrote doesn't make much sense from technical perspective, but it seems what you really want is the same as issues #950 and #662
