### ISSUE TITLE
Fix dragging tracks to new playlists moves instead of copies (in macOS) #Bug

### ISSUE THREAD

**Issue by ldexterldesign** [DeaDBeeF-Player/deadbeef#2322]
https://deadbeef-player.slack.com/archives/C0U2JAMGW/p1580002593002600

### Steps to reproduce the problem

1. Create new playlist
2. Drag track from default playlist to new playlist

### What's going on? Describe the problem in as much detail as possible.

Dragging track from one playlist to another should copy track not move it

Screencast: https://www.dropbox.com/s/wj8i1xi8ucepst8/foo.webm

### Information about the software:

Deadbeef version: [?]
OS: macOS 10.15.2 (19C57)

I think this is severe enough of an issue for bug status, rather than an enhancement, but do as you will

Yours hopefully

?: I'm a little unsure what version because I'm using [h]omebrew which links https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/deadbeef-devel.rb which links https://downloads.sourceforge.net/deadbeef/travis/osx/master/deadbeef-devel-osx-x86_64.zip which gives me this rather unhelpful about modal:

<img width="1792" alt="Screenshot 2020-01-30 at 03 35 52" src="https://user-images.githubusercontent.com/1715809/73416719-1cd0aa00-4316-11ea-834d-e735a444bac5.png">

h: https://brew.sh/

**Comment by JakeSFR** [comment]
Not sure how it works in Mac, but in Linux if I want to copy an item from one playlist to another, I just hold CTRL while dragging it:

![DB_DND_Copy](https://user-images.githubusercontent.com/6226504/73592568-18fe7c80-44fc-11ea-83f8-2ebc80d690e4.gif)

**Comment by Alexey-Yakovenko** [comment]
@JakeSFR it was not implemented correctly on mac
