### ISSUE TITLE
DTS channels missing

### ISSUE THREAD

**Issue by liyafe1997** [DeaDBeeF-Player/deadbeef#2323]
### Steps to reproduce the problem
Play this music:https://drive.google.com/open?id=1Zld3ZEF7_QSMY_cr0Vxdd5RsqOCrtrgo
The music is too big to upload here. 
### What's going on? Describe the problem in as much detail as possible.
This DTS format music has 6 channels, using other players all work fine but in Deadbeef only has 2 channels(Some sounds are missing). You can have a try to play this music by other players, like VLC, even foobar2000 in Windows, the sound is different.

![1](https://user-images.githubusercontent.com/18359157/73553938-c71b0f80-4485-11ea-8698-630c0eda8590.png)

### Information about the software:
Latest version for macOS (Download from https://sourceforge.net/projects/deadbeef/files/travis/osx/1.8/deadbeef-1.8.3-beta1-osx-x86_64.zip) 
Deadbeef version:
OS:macOS 10.15

**Comment by Alexey-Yakovenko** [comment]
It will display the 6 channel now, but you could only hear them if you really have 6 speakers. Deadbeef doesn't downmix multichannel into stereo.
