### ISSUE TITLE
deadbeef not finding the embedded album art

### ISSUE THREAD

**Issue by rafutek** [DeaDBeeF-Player/deadbeef#2325]
### Steps to reproduce the problem

- Open deadbeef
- select a music to play (mp3)
- (if the album art view is not present, go into design mode and add this view)
- default deadbeef album art shown (not the embedded one)

### What's going on? Describe the problem in as much detail as possible.

I use to download music with
youtube-dl -i -x --audio-format mp3  --embed-thumbnail ${URL} -o '%(title)s.%(ext)s'
and I play it on multiple divices where I can see the album art.

I tried to configure the album art plugin to allow deadbeef to find the embedded image but it doesn't seem to work, the default deadbeef cover is still here.

### Information about the software:

Deadbeef version: 1.8.1
OS: Debian 10

**Comment by Alexey-Yakovenko** [comment]
I tried with a random MP3 file which has an embedded album cover (APIC field), and it worked.
I couldn't download anything using youtube-dl, with this error "YouTube said: This video is unavailable."
Therefore, can't reproduce.

**Comment by JakeSFR** [comment]
I wanted to test it earlier, but stumbled across the 'Album Art column crash' bug and forgot about this one.

Youtube-dl uses ffmpeg to do things and indeed, album art embedded like this:

`ffmpeg -i in.mp3 -i in.jpg -c copy -map 0 -map 1 out.mp3`

doesn't show up in DB (it does in VLC).

Re-encoding with lame:

`lame -ti in.jpg in.mp3 out.mp3`

gives the same results as above.

The problem seems to be that both of the above methods set the image type to:

`$00 – Other`

whereas DB apparently shows the album art only if the type is:

`$03 – Cover (front)`

All other types are ignored.

**Comment by Alexey-Yakovenko** [comment]
@JakeSFR thanks a lot for the details!

**Comment by rafutek** [comment]
@JakeSFR thanks! Is it possible to change this variable value then?

**Comment by Alexey-Yakovenko** [comment]
@rafutek while technically it's the tagger's fault for not embedding the album cover with the correct type -- we can't do much about it, and it's an issue that needs fixing in the client.

You can change the picture type in some mp3 tag editors as a workaround though, but I can't recommend anything specific. Foobar2000 can do this most likely.

**Comment by JakeSFR** [comment]
@rafutek: EasyTag can do it, too (should be in Debian repo).

Or ffmpeg:
`ffmpeg -i input.mp3 -codec copy -metadata:s:v comment="Cover (front)" output.mp3`

@Alexey-Yakovenko: Both 3 and 0 types seem to be already supported, if I read it right, but only in the 'artwork' plugin:

```
const uint8_t *image_data = id3v2_artwork (f, minor_version, 3);
if (!image_data) {
    // try any cover if front is not available
    image_data = id3v2_artwork (f, minor_version, 0);
}
```

Maybe this simple workaround would be good enough for 'artwork-legacy'?
_artwork.c, added ' && *mime_end != 0':_

```
if (*mime_end != 3 && *mime_end != 0) {
    trace ("artwork: picture type=%d\n", *mime_end);
    return NULL;
}
```

**Comment by Alexey-Yakovenko** [comment]
Thanks, that works for me, I did just that.
