### ISSUE TITLE
[Nightly build] Debian package fails to install due to non-numeric version

### ISSUE THREAD

**Issue by RogueScholar** [DeaDBeeF-Player/deadbeef#2330]
### Steps to reproduce the problem
Download and install the Debian package from Sourceforge in the /travis/linux/master folder which is uploaded nightly. Doesn't matter the front end you choose (apt, aptitude, synaptic, muon, et al.), the error arises from dpkg and is always:

```bash
dpkg: error processing archive deadbeef-static_devel-1_amd64.deb (--unpack):
  parsing file '/var/lib/dpkg/tmp.ci/control' near line 1:
'  Version' field value 'devel-1': version number does not start with digit
```

### What's going on? Describe the problem in as much detail as possible.
This is just a constraint of Debian packaging, it's at least 20 years old by my memory, and unlikely to change. Version strings have to at least start with a digit though other characters are permitted after that, and even then only under very narrow contraints.

### Information about the software:
Deadbeef version: devel-1 (Though properly I would define it as 1.8.3-nightly20200205 and that would be my recommendation for the contents of the PORTABLE_VERSION file from which the string is sourced)
OS: Kubuntu 19.10 "Eoan Ermine"

@Alexey-Yakovenko I hate to be the bearer of unwelcome tidings, but [commit c19042b](https://github.com/DeaDBeeF-Player/deadbeef/commit/c19042b789b68d1bfaad1c0b29d7ab0e7ef325a3#diff-05bc60064136940c42b63c77c3c60a2f) broke the nightly Debian package build by removing the version number. I know a thing or two about Debian packaging, too, if you need to brainstorm a solution.

EDIT: typo correction

**Comment by Alexey-Yakovenko** [comment]
Fixed - the packages for non-versioned builds won't be uploaded anymore.

**Comment by uralets** [comment]
Ubuntu 22.04 nightly build from https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_amd64.deb/download
exhibits exactly this problem
