### ISSUE TITLE
The File browser does not set the default folder

### ISSUE THREAD

**Issue by nBalykin** [DeaDBeeF-Player/deadbeef#2331]
Unable to set default folder in **file browser** plugin. It always start in /home. "Go to default directiry" button doesnt work too. 
Sometimes it crashes after setting the default directory in the settings.

Deadbeef version: 1.8.2
OS: Mint 19.3

**Comment by Alexey-Yakovenko** [comment]
File browser plugin: https://gitlab.com/zykure/deadbeef-fb/issues
