### ISSUE TITLE
There's no way to disable Log Window popping up on errors

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#2342]
### Steps to reproduce the problem

* Run deadbeef
* Make it display any error message -- e.g. "Failed to play track"

### What's going on? Describe the problem in as much detail as possible.

* The user may become annoyed by any error messages that automatically popup

### Information about the software:

Deadbeef version: 1.8.2
OS: Linux, Mac

Relates to: #2339, #2229, #2193, #2272

**Comment by f1xmAn** [comment]
> The user may become annoyed by any error messages that automatically popup

True. It really annoys me when I connect or disconnect headphones a few times per day. (OS X)

**Comment by dikonov** [comment]
There is an option to permanently add the log to the main deadbeef window (in the design mode) and resize it small... The errors will not create popups anymore.

**Comment by coolKIH** [comment]
It's been quite a long time! I found that we can simply replace the log layer 0 with 1 in "coreaudio.c". That will prevent the Log Window from auto popping up.  

That is, in line 32, coreaudio.c, change
```c
#define trace(...) { deadbeef->log_detailed (&plugin.plugin, 0, __VA_ARGS__); }
```
to
```c
#define trace(...) { deadbeef->log_detailed (&plugin.plugin, 1, __VA_ARGS__); }
```

Is that alright? Will that cause any unexpected behavior? I tried myself on Mac and it works.

**Comment by Alexey-Yakovenko** [comment]
The behavior will be that this would disable all coreaudio error messages for all users, and it would not be possible to turn this back on.

**Comment by Alexey-Yakovenko** [comment]
Although, since it would still log the messages maybe it's ok. But, of course, this would not solve the problem "globally".
I applied this change on master.

**Comment by br3eze** [comment]
Arch -> Aur / Repo doesn't matter -> deadbeef-git-r10930.4dd17a826-1
Again and again..

**Comment by bubbleguuum** [comment]
Please consider adding an option to disable the log window entirely.

I'm using i3 as a window manager and have deadbeef in a scratchpad (invisible) window that can be made visible/invisible with a keyboard shortcut. The problem is that the log window also go into the scratchpad, thus sometimes when I make the scratchpad window visible, it shows the log window rather than the deadbeef main window.

**Comment by dobosken** [comment]
To prevent the log window from popping up on startup:
Remove [these](https://github.com/DeaDBeeF-Player/deadbeef/blob/3a430eddc586920c424bba64559de59de2b81b29/plugins/gtkui/gtkui.c#L1391-L1392) lines from `/plugins/gtkui/gtkui.c`.
The log can still be manually invoked from the _View_ tab.

**If you do this, do not waste anyone's time with a support ticket. You mess with this and run into an issue, that's your problem to solve.**

**Comment by ppw0** [comment]
> To prevent the log window from popping up on startup: Remove [these](https://github.com/DeaDBeeF-Player/deadbeef/blob/3a430eddc586920c424bba64559de59de2b81b29/plugins/gtkui/gtkui.c#L1391-L1392) lines from `/plugins/gtkui/gtkui.c`. The log can still be manually invoked from the _View_ tab.
> 
Do you by any chance know how to prevent it from flooding the journal with logs?
