### ISSUE TITLE
'Convert' does not work

### ISSUE THREAD

**Issue by Samael1982** [DeaDBeeF-Player/deadbeef#2345]
### Information about the software:
Deadbeef version:1.8.2
OS: Ubuntu 18.04
### Steps to reproduce the problem
deadbeef installed from default Ubuntu repository
### What's going on? Describe the problem in as much detail as possible.
Any try to convert files generates error. Usually I convert cue/ape and mp3 to mp3.
"Failed to execute the encoder, command used:
"lame -V2 - "/home/andersen/Music/mp3/Hovmod - 2019 - Doedsformasjon/05!!!_Hatskapt.mp3""
lame is installed and folder is accessible by dead-beef started user.
LAME 64bits version 3.100 (http://lame.sf.net)
usage: lame [options] <infile> [outfile]
***

drwxr-xr-x  2 user user     4096 січ 24 15:54  ./
drwxr-xr-x 92 user user     4096 лют 24 10:20  ../
-rw-rw-r--  1 user user  8168299 січ 24 15:54  05_Hatskapt.mp3

Foobar under wine with lame.exe , for example, works.

**Comment by Alexey-Yakovenko** [comment]
I can't reproduce the issue.
Tried on Ubuntu 18.04 and macOS.
I thought that maybe the exclamation marks are a problem, but they work fine.

> deadbeef installed from default Ubuntu repository

deadbeef is not present in any official Ubuntu repositories.

**Comment by Samael1982** [comment]
Yep, it was installed from SNAP :-(
Being downloaded and run, it converts tracks without troubles.
SNAP is EVIL
