### ISSUE TITLE
[BUG] Writing ReplayGain information to AAC files removes embedded cover art.

### ISSUE THREAD

**Issue by Sonico98** [DeaDBeeF-Player/deadbeef#2346]
### Steps to reproduce the problem

Select multiple AAC files and do a ReplayGain scan as a single album. Once the scan finishes, update the file tags.

### What's going on? Describe the problem in as much detail as possible.

Whenever RG tags are written, the embedded art on the AAC files gets removed. All the other tags are intact. I've looked at the tags after the scans with both Kid3 and MP3Tag, as well as many music players both on Android and Linux. I've tested this with a bunch of files already, all of them transcoded from FLAC with QAAC 2.68. It doesn't matter if the embedded art was present before the transcode or not, as Deadbeef will always remove it after writing RG tags. I've noticed this issue is NOT present with FLAC, but haven't tested with any other file formats.

### Information about the software:

Deadbeef version: 1.8.2
OS: ArchLinux x86_64 5.5.5-arch1-1

**Comment by Alexey-Yakovenko** [comment]
I didn't try in 1.8.2, but this is not an issue in master, which can be attributed to the new mp4 editing library, which replaced mp4ff.
