### ISSUE TITLE
GTKUI on Mac: shortcuts don't get applied until restarting the player

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#2349]
Repro:

* create new shortcut
* try using it
* shortcut is not working until restarting the player

**Comment by stefson** [comment]
for a reproducer on linux: what kind of shortcut have you created, and what did you restart (deadbeef-gui, xsession, kernel?)

**Comment by Alexey-Yakovenko** [comment]
I restarted deadbeef. There's no xsession on mac. This is a Mac-specific issue.
I haven't tried reproducing on linux.
It happens with any keyboard shortcut.

**Comment by Alexey-Yakovenko** [comment]
I updated the summary and repro to be more clear

**Comment by kuba160** [comment]
Issue is also present in Windows version.

**Comment by Alexey-Yakovenko** [comment]
I just verified on linux: the issue is not valid there.
