### ISSUE TITLE
dlopen error adplug.so: undefined symbol ...

### ISSUE THREAD

**Issue by algo99** [DeaDBeeF-Player/deadbeef#2351]
Build current devel version, install, run deadbeef from command line.
You'll see the message: 
`dlopen error adplug.so: undefined symbol ...`

Looks like you script updating `plugins/adplug/Makefile.in` and `plugins/adplug/Makefile.am` skipped all *.c files: files `adlibemu.c  debug.c  fmopl.c  nukedopl.c` in `plugins/adplug/adplug/` will not be built

**Comment by Alexey-Yakovenko** [comment]
sorry, missed the *.c files.
