### ISSUE TITLE
(feature request) webp image format support

### ISSUE THREAD

**Issue by ghcatt** [DeaDBeeF-Player/deadbeef#2354]
interresting lossy/lossless image format with several benefits over "classic" formats like jpeg or png.

further infos at https://developers.google.com/speed/webp

**Comment by Alexey-Yakovenko** [comment]
Deadbeef is not an image viewer. Why would you need it to support webp?

**Comment by ghcatt** [comment]
> Why would you need it to support webp?

displaying albumartwork?
