### ISSUE TITLE
[feature request] Resume playback on program restart

### ISSUE THREAD

**Issue by AngryPhantom** [DeaDBeeF-Player/deadbeef#2355]
Deadbeef version: **any**
OS: **Linux**

Is it possible to add **resume playback** functionality as in VLC when you pause a video, close the player and open this video again? It would be really **handy for long audio files** like podcasts, DJ sets etc.

Thank you!

**Comment by Alexey-Yakovenko** [comment]
This is already possible, just tick the "Resume previous session on startup" in the settings.

It can only remember resume position of one file though.
