### ISSUE TITLE
Seek / jump to time does not work on OSX

### ISSUE THREAD

**Issue by erdnuesse** [DeaDBeeF-Player/deadbeef#2357]
I wanted to seek inside my tracks. aka. jumping to a specific time.
Realized, the progress indicator does not move to the right during playback.

### Steps to reproduce the problem
Using on OSX
opening a FLAC or MP3
Play a File
click somewhere in the progress bar.

### What's going on? Describe the problem in as much detail as possible.
For each click, the song starts from the beginning, without the possibility jo jump anywhere in the track.

### Information about the software:
Deadbeef version: Version 1.0 (322e0ff)
OS: High Sierra 10.13.6 (17G11023)

**Comment by Alexey-Yakovenko** [comment]
I'm investigating the issue. Meanwhile, I suggest using a slightly older version from here:

https://sourceforge.net/projects/deadbeef/files/travis/osx/1.8.3/deadbeef-1.8.3-osx-x86_64.zip/download

**Comment by Alexey-Yakovenko** [comment]
The issue is not reproducible on Catalina, and I don't have access to any other versions, so it will be tricky to get this fixed. But I will try my best to figure it out.

**Comment by erdnuesse** [comment]
> I'm investigating the issue. Meanwhile, I suggest using a slightly older version from here:
will do.

If I can do anything to help, please advise. I am also IT-Expert. Not a dev, more Infrastructure guy, but I have already recently compiled apps on OSX for that matter.

**Comment by Alexey-Yakovenko** [comment]
Can't really advice anything, aside from stepping over the code in Xcode and seeing why it happens.

**Comment by Alexey-Yakovenko** [comment]
But I'm not sure whether it's possible to compile and debug the current codebase in older Xcode that's available in High Sierra, since I switched to Xcode11 quite some time ago.

**Comment by Alexey-Yakovenko** [comment]
Looking into the `/var/log/system.log` might help though. Maybe some exception is logged.

**Comment by erdnuesse** [comment]
`Starting app now`
`Mar 24 14:47:50 --- last message repeated 2 times ---`
`Mar 24 14:47:50 mbp-2010 com.apple.xpc.launchd[1] (com.apple.preference.displays.MirrorDisplays): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.`
`Mar 24 14:48:11 --- last message repeated 2 times ---`
`Mar 24 14:48:11 mbp-2010 com.apple.xpc.launchd[1] (com.apple.quicklook[11081]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook`
`Mar 24 14:48:20 mbp-2010 com.apple.xpc.launchd[1] 
(com.apple.preference.displays.MirrorDisplays): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.`

My tail -f outbup since starting the app (i pushed the first line in as root to mark the moment when I opened the app)
But this should be unrelated to playback, b/c these outputs continue, when playback is stopped.

**Comment by Alexey-Yakovenko** [comment]
ok. this doesn't contain anything interesting.

**Comment by Alexey-Yakovenko** [comment]
> other apps from other dev's have misbehaved because they were no longer compiled with support those models

Well, deadbeef is only developed and tested on the latest macOS, and compiled to work on 10.12+ or something like this. Maybe 10.13, can't remember exactly.

But compiling doesn't mean that everything will work correctly, anything can happen since it's not tested on older macOS versions.

**Comment by erdnuesse** [comment]
I realised, that the old version just colors the progress bar, the newer one has a moving slider, has that changed in the implementation, or is that just another side effect?

Current version
![the new version - not working](https://user-images.githubusercontent.com/4510296/77434934-e5e0b700-6de1-11ea-90b3-6515636f9dd9.png)

Old version
![the older version](https://user-images.githubusercontent.com/4510296/77435070-19234600-6de2-11ea-95dd-9c2052128c97.png)

**Comment by Alexey-Yakovenko** [comment]
Yes, the problem is caused by the new slider implementation.

**Comment by Alexey-Yakovenko** [comment]
also the slider is wrongly colored on your screenshot, so I suppose there's more than one problem.

**Comment by erdnuesse** [comment]
Aye. So, well, since the old implementation works for me, I guess I'm good for now, it's just a bummer that I may have to sit out _newer_ versions, but hey, it could be worse. 

Obviously I don't want to tell you what to do, but if the older implementation works on a wider set of platforms, I would (also obviously) be happy to see it rolled back. 

If you need testing of dev releases on my platform, happy to do so.
Anyway, take care!

**Comment by Alexey-Yakovenko** [comment]
Rolling back is not the way to go. Any new code can be incompatible in a similar way. Reverting because of incompatibility with old OS versions is simply not an option. This means development halts. People who need old OS versions could as well use the old application versions -- which equals to "everything is reverted to when it worked for them".

The only real option is to fix the issues, and maintain them working on 2 previous OS releases.
But even that is quite challenging and will take time.

**Comment by erdnuesse** [comment]
I only mentioned this because I assumed since everything else seemed to work, a slider vs a progress bar did not look like any critical feature - from my limited point of view. 
I also would encourage anyone to stick to rather one branch instead of two - and reverting "just" the slider back to working seemed like a possible way. But as I said, I don't know about coding this, so take all of this as baseless thoughts and without any serious value. 

Again, if compiling with my XCode to test could make any difference, just say the word.

**Comment by Alexey-Yakovenko** [comment]
Well, you could try and see if it works at all, and whether it gives any relevant errors.
At this point any new information is useful.

**Comment by Alexey-Yakovenko** [comment]
I'm trying to build with SDK 10.13 (already tried 10.14, and everything is still working fine)

**Comment by Alexey-Yakovenko** [comment]
It helped. There is a bug in macos sdk 10.14+, where it declares that `-[NSWindow convertPointFromScreen:]` is available on 10.12, while in reality it's 10.14+.

I couldn't find any reason why the thumb colors are wrong though.

**Comment by erdnuesse** [comment]
Maybe that's why.
![Screen Shot 2020-03-24 at 21 05 25](https://user-images.githubusercontent.com/4510296/77471831-3f150e80-6e13-11ea-8231-31b3ca99c0d0.png)

**Comment by Alexey-Yakovenko** [comment]
`[NSColor.windowBackgroundColor shadowWithLevel:0];`

On catalina this color is white (or very light).
It's quite unlikely that it's black on HS though.. so I'm puzzled.

**Comment by erdnuesse** [comment]
Oh you were talking about the upper screenshot. I thought the lower one.
