### ISSUE TITLE
Virtual Box shared folders permission issue

### ISSUE THREAD

**Issue by Vaskivo** [DeaDBeeF-Player/deadbeef#2358]
### Steps to reproduce the problem
1. Setup VirtualBox with Windows 10 host and Xubuntu guest.
2. Share host folder with guest, via VirtualBox's "share folder" feature.
3. Boot guest OS and login.
4. Add user to virtualbox's shared folders group: `sudo adduser $USER vboxsf`
5. Log out and login.
6. Open DeadBeef
7. File -> Open Files -> (navigate to shared folder)

### What's going on? Describe the problem in as much detail as possible.
When navigating to a Virtualbox's shared folder Deadbeef cannot read its contents. A "permission denied" error appears. I can access the folder and read its contents via bash, file explorer (thunar) and default media player (parole).

Groups and permissions:
```
vaskivo@vaskivo-VirtualBox:~$ ls -l | grep Music
drwxrwx--- 1 root    vboxsf  4096 mar 26 09:57 Music
vaskivo@vaskivo-VirtualBox:~$ groups $USER
vaskivo : vaskivo adm cdrom sudo dip plugdev lpadmin sambashare vboxsf docker
```

For some reason, I cannot give permissions to "all users". (maybe some virtualbox restriction)

### Information about the software:

Deadbeef version: 1.8.2
OS: uname -a -> `Linux vaskivo-VirtualBox 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
VirtualBox: 6.0.18

**Comment by Alexey-Yakovenko** [comment]
Can you post the error text exactly as it's displayed by deadbeef?

**Comment by Alexey-Yakovenko** [comment]
And also describe where it is displayed -- console, log window?
probably worth to post a screenshot.

**Comment by Alexey-Yakovenko** [comment]
Also it's not enough to have vboxsf permission on the Music folder.
You need to have that an all files and folders which deadbeef needs to access.

**Comment by Alexey-Yakovenko** [comment]
Other than that.. I'm not sure about vbox on windows, but vbox on mac has a very shitty audio driver, and I don't advice using it for music listening. You could run deadbeef natively on windows -- there's a windows port: https://deadbeef-for-windows.github.io/

**Comment by Vaskivo** [comment]
Here's a video showing the problem:

https://drive.google.com/file/d/1D9ET9YYVyoFVfNzkeGru_SMoxw8IFSdF/view?usp=sharing

**Comment by Alexey-Yakovenko** [comment]
Did you install deadbeef from snap?

**Comment by Alexey-Yakovenko** [comment]
The error you're seeing is typical when deadbeef is installed from a random snap package, that someone built and put on the internet.
If that is the case, I recommend to stop using the snap build - it's not an official build, made by a random person on the internet, and also it doesn't work.

**Comment by Alexey-Yakovenko** [comment]
I looked more carefully at the log in the video, and although it's blurry - I could see it's running from snap indeed. This is your problem, and I hope now you got your solution. Good luck!

**Comment by Vaskivo** [comment]
That was it.
I installed it using ubuntu's "Software catalog".

I installed it using the `.deb` in you website and it works. 

Thanks :+1:
