### ISSUE TITLE
soundtouch configuration is empty window on linux / GTK3

### ISSUE THREAD

**Issue by requiredregistration** [DeaDBeeF-Player/deadbeef#2360]
1.8.3

what happened to these features? playing backwards and tempo+pitch control were things that made deadbeef differ from the rest. now it's just another media player.

**Comment by Alexey-Yakovenko** [comment]
Ugh. Soundtouch plugin never really shipped. Eventually got deleted, cause nobody needs it.

**Comment by requiredregistration** [comment]
hold your horses there, alex. you closed it right away.

i mentioned these features, so, obviously, i used them.

the plugin is still in the plugins directory. https://github.com/DeaDBeeF-Player/deadbeef/tree/master/plugins/soundtouch

are you against having these features back?

**Comment by Alexey-Yakovenko** [comment]
I generally close issues that are not actionable. I answered your question - so there was no reason to keep it open.

Although I now realized that I only *planned* to delete the source, but really didn't.

So what is the problem? Seems like nothing has changed since 2014 in relation to this plugin.

**Comment by requiredregistration** [comment]
i'm sorry. there's no problem. i mistook your player for another one.

**Comment by MarcRdC** [comment]
If I may add something to the conversation, I do find it a sad fact that this plugin is no longer being maintained, as it may come in handy. The sources can still be compiled and the plugin is functional, except that the settings window remains empty.

**Comment by Alexey-Yakovenko** [comment]
At this point, I can't remember what was the problem with it, but I think it wasn't reentrant, and needed some fixing. But maybe I can update it. I'll take a look when I have time.

**Comment by MarcRdC** [comment]
Thank you very much, @Alexey-Yakovenko.

**Comment by Alexey-Yakovenko** [comment]
I tried to do what I could, but soundtouch library turned out to be not very good at validating its parameters, so it's crashes and freezes very often. The sound quality is also really poor for time stretching, so I don't really see much value in shipping it.

**Comment by MarcRdC** [comment]
O.K. You’re right, shipping it might not be a good idea, then. But the sources should stay available, so that it can be compiled and tested; what do you think?

**Comment by Alexey-Yakovenko** [comment]
Yeah, I'm not deleting them

**Comment by MarcRdC** [comment]
And thank you for taking the time to check.

**Comment by Alexey-Yakovenko** [comment]
I decided to go one step further, and did some changes:

* SoundTouch library updated to latest 2.1.2
* Parameter ranges and defaults changed to better values
* Added more parameter validation
* Removed parameters which didn't make sense
* Include the plugin in Mac and Linux builds

So, it should be available in the next build.

![image](https://user-images.githubusercontent.com/1895698/78182134-e45c6200-7465-11ea-9981-97b2ef783c0f.png)

**Comment by MarcRdC** [comment]
You are **amazing**! Tried to compile the current master but the configuration window is still empty on Linux with GTK3 plugin, even after resizing it.
![deadbeef_configure_soundtouch_2-fs8](https://user-images.githubusercontent.com/12560860/78190680-63549900-746c-11ea-87a8-85da4016082e.png)

**Comment by Alexey-Yakovenko** [comment]
You're doing it wrong, you need to add it to dsp chain in the preferences, and configure there.

**Comment by MarcRdC** [comment]
That is exactly what I did and how I got this window.

**Comment by Alexey-Yakovenko** [comment]
Ok, then there's a bug on linux which I wasn't aware of. Will need to have a closer look.

**Comment by MarcRdC** [comment]
O.K. Let me know if you need more information.

**Comment by Alexey-Yakovenko** [comment]
surprisingly, with GTK3 on mac it's working fine.

![image](https://user-images.githubusercontent.com/1895698/78217933-41cfcd80-74bd-11ea-9ded-7a5e95de4023.png)

**Comment by Alexey-Yakovenko** [comment]
also works on ubuntu 18.04..

I'll need to know more details about what you're running, and what is your system.

![image](https://user-images.githubusercontent.com/1895698/78218568-4ba60080-74be-11ea-8707-451179cb4912.png)

**Comment by MarcRdC** [comment]
I’m running DeaDBeeF compiled from master branch up to commit 4628508 under an up‐to‐date Arch Linux. The same behaviour can be seen with a clean config and GTK2 plugin. Configuration windows of other plugins do not have this symptom, as shown in the screenshots.

![deadbeef_resampler](https://user-images.githubusercontent.com/12560860/78238116-ba3d8b00-74cb-11ea-8890-815c24665641.png)

![deadbeef_hdcd](https://user-images.githubusercontent.com/12560860/78238149-c6294d00-74cb-11ea-881c-3f9aeeebe30d.png)

**Comment by Alexey-Yakovenko** [comment]
The resampler configuration looks wrong too. It's missing most of the UI elements.

**Comment by Alexey-Yakovenko** [comment]
@MarcRdC can you try running this build instead of custom build?
https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download

**Comment by MarcRdC** [comment]
Everything seems fine with this build — I had to copy the Soundtouch plugin, which was not present.

![deadbeef_resampler](https://user-images.githubusercontent.com/12560860/78245103-5ff5f780-74d6-11ea-883b-638a3f65b77d.png)

![deadbeef_soundtouch](https://user-images.githubusercontent.com/12560860/78245110-65534200-74d6-11ea-84cc-ea8a2a14071a.png)

**Comment by Alexey-Yakovenko** [comment]
Well, this means you have some problem with the local build. I'm not sure how to help with this...

**Comment by MarcRdC** [comment]
I don’t do extravagant things…

    ./autogen.sh
    ./configure --prefix=/usr
    make
    make DESTDIR="/" install

[build.log.gz](https://github.com/DeaDBeeF-Player/deadbeef/files/4421083/build.log.gz)

**Comment by tj-prop** [comment]
![resampler-gtk3](https://user-images.githubusercontent.com/54933261/78251710-a43ec300-74e9-11ea-8adb-5b204cc28eed.png)
This is a build on Arch of latest master (both up to date as of about 30 mins ago) with KDE + Breeze GTK3 theme. Looks correct to me?

**Comment by Alexey-Yakovenko** [comment]
@MarcRdC there's still something obviously wrong, and since it happens only on your machine -- it's impossible to reproduce and fix for anyone else, with the amount of information we have.

I suggest to try the following things:

* Build to a different prefix
* Run from a different (new) user
* Remove any 3rd party plugins

**Comment by Alexey-Yakovenko** [comment]
@tj-prop thanks a lot for verifying this!

**Comment by MarcRdC** [comment]
Thank you very much for your help, @Alexey-Yakovenko and @tj-prop. I found the culprit: the [`deadbeef-lyricbar`](https://github.com/loskutov/deadbeef-lyricbar) plugin. Everything is O.K. when I uninstall it. Will report the problem to its developer.

Long live DeaDBeeF!
