### ISSUE TITLE
DSP properties text is unreadable in macOS dark mode 

### ISSUE THREAD

**Issue by tomjepp** [DeaDBeeF-Player/deadbeef#2364]
### Steps to reproduce the problem
1 .Open preferences
2. select a DSP entry and view the settings for it

### What's going on? Describe the problem in as much detail as possible.
In light mode, the UI is usable:
<img width="637" alt="resampler-light" src="https://user-images.githubusercontent.com/637494/78450872-b8192f00-7679-11ea-8a6c-74137b37359d.png">

In dark mode, most of the UI is unreadable:
<img width="637" alt="resampler-dark" src="https://user-images.githubusercontent.com/637494/78450875-bea7a680-7679-11ea-8b52-5744e29b3846.png">

This also applies to SuperEQ:
<img width="637" alt="supereq-dark" src="https://user-images.githubusercontent.com/637494/78450878-c36c5a80-7679-11ea-87fa-a7db4341e6d3.png">

### Information about the software:

Deadbeef version: master `8bf4eb66`
OS: macOS Catalina 10.15.4 (19E266)

**Comment by Alexey-Yakovenko** [comment]
Good find!

**Comment by tomjepp** [comment]
Rebuilt and all fixed! Thanks!
