### ISSUE TITLE
Converter GTK3 UI deactivated

### ISSUE THREAD

**Issue by spvkgn** [DeaDBeeF-Player/deadbeef#2367]
### Steps to reproduce the problem

Get devel build https://sourceforge.net/projects/deadbeef/files/travis/linux/master/
Converter GTK3 UI plugin is missing

### What's going on? Describe the problem in as much detail as possible.

```
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
convgui: need converter>=1.4, but found 2.0
plugin Converter GTK3 UI failed to connect to dependencies, deactivated.
```

### Information about the software:

Deadbeef version: devel
OS: Ubuntu

**Comment by Alexey-Yakovenko** [comment]
Thanks for spotting, it was an unintended change.
