### ISSUE TITLE
Tooltip thin text for Korean letters

### ISSUE THREAD

**Issue by 64542426** [DeaDBeeF-Player/deadbeef#2368]
### Steps to reproduce the problem
If you can verify it with Sarasa-Gothic font and a Korean song?
### What's going on? Describe the problem in as much detail as possible.
I'm using "[Sarasa-Gothic](https://github.com/be5invis/Sarasa-Gothic)" font [download](https://github.com/be5invis/Sarasa-Gothic/releases) specifically i'm using **sarasa-term-hc-semibold.ttf** to display CJK characters on deadbeef, so far i'm happy with results regarding Asian languages/letters, the only concern i noted is the tooltip, the font for Korean language is a bit thin on tooltip, Japanese (Kanji,Hiragana,Katakana) are displayed correctly from both interface&tooltip, i don't have Chinese to test, but Korean letter displayed in thin, see image below
![2020-04-08--1586360008_582x148_scrot](https://user-images.githubusercontent.com/35492934/78804890-fe93c400-79c0-11ea-962d-fad2ae2b61f5.png)

### Information about the software:

Deadbeef version: Devel
OS: Devuan

**Comment by Alexey-Yakovenko** [comment]
Hello. The issue you're describing doesn't seem to be with a specific application, but with configuration of your system, or more specifically with GTK theme.
