### ISSUE TITLE
Debian Sid libpango dependency change

### ISSUE THREAD

**Issue by RattusSolarus** [DeaDBeeF-Player/deadbeef#2369]
Just a heads up that libpango1.0-0 has changed its name to libpango-1.0-0 in Debian Sid and libpango1.0-0 is now removed with system upgrade and also removes Deadbeef.
I just edited the control file of your .deb package to reflect the dependency change and the modified .deb installed fine after removal of the old libpango1.0-0

**Comment by Alexey-Yakovenko** [comment]
Hmm.. I'm not sure why the deb needs it in the control file. libpango is a dependency of GTK anyway. I think it's safe to remove the libpango dependency from the deb.

**Comment by Alexey-Yakovenko** [comment]
I removed the pango dependency upstream.
