### ISSUE TITLE
Some files are played at the wrong samplerate

### ISSUE THREAD

**Issue by keantoken** [DeaDBeeF-Player/deadbeef#2370]
I've had this problem for a long time. I am on Debian Sid and use the repository for Deadbeef.

When I play this file:

http://www.lindberg.no/hires/test/2L48SACD_14_stereo_96k.flac

And use the Secret Rabbit resampler to change to 192KHz, it plays at half speed.

However if I play this file:

http://www.lindberg.no/hires/test/2L-087_stereo-DXD_06.flac

WITHOUT the resampler, it plays at half speed. I have to add the resampler to get it to play normally.

**Comment by keantoken** [comment]
I should add I have 2 resampler plugins and both of them have the same problem with the 96KHz file.

I can give the Rabbit resampler the correct samplerate which is 192KHz but it will still play at half speed if I don't use the option to automatically detect samplerate. In that case both files work. But every configuration has problems with some file.

For the second file, I have the Rabbit resampler set to 192KHz output, but the Deadbeef output stream is at 96KHz and the track is played at half speed. The play time still moved in normal seconds though.

Sink Input #132
	Driver: protocol-native.c
	Owner Module: 11
	Client: 358
	Sink: 0
	Sample Specification: s24le 2ch 96000Hz
	Channel Map: front-left,front-right
	Format: pcm, format.sample_format = "\"s24le\""  format.rate = "96000"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
	Corked: no
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	Buffer Latency: 129296 usec
	Sink Latency: 100160 usec
	Resample method: soxr-vhq
	Properties:
		media.name = "Music"
		application.name = "Deadbeef"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "33"
		application.process.id = "6904"
		application.process.user = "keantoken"
		application.process.host = "ronin"
		application.process.binary = "deadbeef"
		application.language = "en_US.utf8"
		window.x11.display = ":0.0"
		application.process.machine_id = "3242b4d91f4c4897a148cb589986b5fb"
		application.process.session_id = "5"
		media.role = "music"
		application.icon_name = "deadbeef"
		module-stream-restore.id = "sink-input-by-media-role:music"

When I use the "detect samplerate" option, it plays at the right speed but still at 96KHz, not at the actual samplerate which is 192KHz. If I play the first file instead, the output samplerate and playback speed are correct.

So it seems Deadbeef is changing the output samplerate away from native for no reason, if certain files are played, and this causes my resamplers to not work right.

**Comment by keantoken** [comment]
$ pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 33
Server Protocol Version: 33
Is Local: yes
Client Index: 370
Tile Size: 65472
User Name: keantoken
Server Name: pulseaudio
Server Version: 13.0
Default Sample Specification: s32le 2ch 192000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.Generic.analog-stereo
Default Source: alsa_input.Generic.analog-stereo
Cookie: 189a:d652

**Comment by keantoken** [comment]
I am not using Deadbeef's "override samplerate" option.

**Comment by keantoken** [comment]
If I use the Override Samplerate option, both files play at the right speed. So perhaps resamplers are not meant to be used without this option?

However if I use no resamplers, and don't use the override samplerate option, the second file plays at the wrong speed because the output stream is set to 192KHz even though the file samplerate is higher. However the Pulseaudio resampler should be capable of resampling it so there is no reason to limit the samplerate.

If I use the Overrise Samplerate option and set the samplerate to 358KHz, it still plays at the wrong speed and the stream samplerate is still 192KHz.

**Comment by Alexey-Yakovenko** [comment]
You should not be using resampler the way you do.
It's not doing what you think. Keep it at default, and forget about it.

**Comment by keantoken** [comment]
If I keep it at default, the second file plays wrong because Deadbeef outputs the wrong samplerate.

**Comment by Alexey-Yakovenko** [comment]
![image](https://user-images.githubusercontent.com/1895698/79039494-ecdd3700-7be1-11ea-915f-6bca05eaa5fd.png)

This is the default.
The important part is "Autodetect" option. It ensures that samplerate is correct.
If this is off -- you will always get wrong playback speed with certain files.

**Comment by Alexey-Yakovenko** [comment]
The UI doesn't show it, but the first two options are mutually exclusive. When checkbox is on, the samplerate is controlled by the output -- that is, the "set samplerate directly" option will be ignored.
This is the **only** way to get correct playback speed.
