### ISSUE TITLE
Shuffe albums keeps playing same album

### ISSUE THREAD

**Issue by KernelModule** [DeaDBeeF-Player/deadbeef#2374]
### Steps to reproduce the problem
1. Enable album shufflng 
### What's going on? Describe the problem in as much detail as possible.
After playing last track on the album player always starts play same album from the beginning instead random album.
### Information about the software:

Deadbeef version: 1.8.3
OS: Ubuntu 18.04

**Comment by Alexey-Yakovenko** [comment]
Can't reproduce.
