### ISSUE TITLE
[Feature Request] Отдельная функция для копирования файлов 

### ISSUE THREAD

**Issue by Elserjo** [DeaDBeeF-Player/deadbeef#2378]
#Описание проблемы
Допустим имеется набор треков, которые необходимо привести к формату .flac c определенным шаблоном имени файла, например "%tracknumber% %title%". Это может быть осуществленно через "Конвертировать". 
После этого, сконвертированные треки нужно скопировать в другую директорию (например, смонтированный плеер), но уже по другому шаблону "%album artist%/%album%/%tracknumber% %title%". В этом случае для последующей конвертации, нужно снова менять шаблон имени файла на заданный ранее. 

#Желаемое поведение
Добавление отдельной опции в контекстном меню для копирования файлов со схожим функционалом, как у окна "Конвертировать". В этом случае шаблон имени файла не придется каждый раз менять вручную.

#Дополнение
Подобная фича есть у foobar. Выглядит приблизительно вот [так](https://yadi.sk/i/iCxL6yikhFDkbA)

**Comment by Alexey-Yakovenko** [comment]
насколько я вижу, вам нужна не вторая функция копирования, а то же самое что написано в другом фичреквесте #764, т.е. возможность иметь несколько независимых настроек конвертера для разных задач.
