### ISSUE TITLE
Strange behavior when using Numpad 5 as shortcut key

### ISSUE THREAD

**Issue by abielefeldt** [DeaDBeeF-Player/deadbeef#2380]
With NumLock on, create a new global shortcut using Numpad 5. E.g. `KP5` -> Show Help Page.

The shortcut you set won't work, although deadbeef will "blink" as though it recognizes the hotkey. If you uncheck "Global hotkey" the hotkey will then work within deadbeef.

Now turn off NumLock. Edit the shortcut to use Numpad 5 again. Now instead of `KP5` it will say `KPBegin`, and it will now work for global shortcuts but break for local ones.

Additionally, if you create a Shift+Numpad 5 shortcut, it will reverse whether the shortcut comes out as `KP5` or `KPBegin`.

Essentially, Numpad 5 is recognized as `KPBegin` if Numlock is off and Shift is not pressed. If either is on/pressed, it becomes `KP5`. They further cancel each other out to render it as `KPBegin`. `KP5` will only work as a local hotkey while `KPBegin` will only work as a global hotkey. This is true whether or not Ctrl or Alt are also used for the shortcut.

The workaround is to turn NumLock off or on when entering the shortcut depending on whether it uses Shift and whether it's local or global.

Deadbeef version: 1.8.2
OS: Confirmed on both Ubuntu 18.04 (GNOME) and Manjaro (KDE).

**Comment by Alexey-Yakovenko** [comment]
It's difficult to verify this bug for me, since I don't have any full size keyboards with num lock or keypad, but I asked around, and the bug is not happening. Please try in the latest release -- maybe it has been fixed by something else.
