### ISSUE TITLE
Metadata edition isn't save.

### ISSUE THREAD

**Issue by AsVHEn** [DeaDBeeF-Player/deadbeef#2381]
**### Steps to reproduce the problem**
To use "deadbeef->pl_set_meta_int(...)"  to edit a tag's field from a plugin.

**### What's going on? Describe the problem in as much detail as possible.**
Value changes as expected on playlist or track's properties, but, when program is restarted, values are back to their original state. 

**### Information about the software:**
Deadbeef version: 1.8.3
OS: Debian 10

**Comment by Alexey-Yakovenko** [comment]
It works as designed. This function is not supposed to modify the audio files. It updates the values in memory, and if the playItem is part of any playlist -- then the values will be saved as part of the playlist. If you need to save tags in audio files -- you need to look elsewhere. E.g. look how Converter does it, or track properties, or replaygain. They all can update tags.

**Comment by AsVHEn** [comment]
Ah, ok thank you so much. I was mental trying to figure out was I having doing wrong :D.
