### ISSUE TITLE
need location (file path) column in playlist

### ISSUE THREAD

**Issue by deathisinevitable** [DeaDBeeF-Player/deadbeef#2384]
really need location column in the playlist, and sort it by the location (full file path)

### Information about the software:

Deadbeef version: 1.8.3
OS: Ubuntu

**Comment by Alexey-Yakovenko** [comment]
Is there something specific, that prevents you from doing that? I believe this is supposed to work -- you can add any column and sort by anything.

**Comment by deathisinevitable** [comment]
but how?

**Comment by Alexey-Yakovenko** [comment]
`%path%`

**Comment by Alexey-Yakovenko** [comment]
Did you figure it out?
You need to use title formatting. %path% is the variable with full path, so you could use this for sorting etc.

**Comment by deathisinevitable** [comment]
thanks!
