### ISSUE TITLE
tracks from shoutcast streams don't get submitted to last.fm

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#2387]
### Steps to reproduce the problem

Play any shoutcast stream with last.fm scrobbling enabled
E.g. http://sc-gorillafm.1.fm:10020/

### What's going on? Describe the problem in as much detail as possible.

Tracks don't get scrobbled.

### Information about the software:

Deadbeef version: 1.8.3
OS: mac, linux

**Comment by jbwharris** [comment]
I did some more testing with various streams in 1.8.3 and wasn't able to get anything to submit tracks to last.fm. I just installed 1.8.1 and 1.8.2 for Mac and they do work, so there does look to have been a regression in the ability to scrobble radio in 1.8.3.
