### ISSUE TITLE
Design mode missing on MacOS

### ISSUE THREAD

**Issue by fosple** [DeaDBeeF-Player/deadbeef#2388]
### Steps to reproduce the problem
- Download latest master from https://sourceforge.net/projects/deadbeef/files/travis/osx/master/
- Open DeaDBeeF
- Click "View" in menu bar

### What's going on? Describe the problem in as much detail as possible.
- "Design mode" does not appear

![Deadbeef_no-design-mode](https://user-images.githubusercontent.com/4522947/81987533-21f20480-963a-11ea-99b1-120e58e95358.png)

![Deadbeef_no-design-mode_02](https://user-images.githubusercontent.com/4522947/81987850-c116fc00-963a-11ea-9d62-4661526916fd.png)

### Information about the software:

Deadbeef version: master from 14.05.2020 (Strangely "About" section in app says "Version 1.0 (a6ac452)")

OS: MacOS 10.14.6

Btw, really nice app. I'm already looking for a foobar2000 replacement for MacOS since a long time. DeaDBeeF looks like a really powerful and customisable alternative. Thanks for your work!

**Comment by Alexey-Yakovenko** [comment]
It's not a bug, mac version is still quite behind GTK version in features, and layout editing is one of those not implemented yet. The version is 1.0, since it doesn't matter - mac deadbeef is not getting stable releases, only CI builds.

**Comment by Alexey-Yakovenko** [comment]
There's no workaround -- the code for UI layout editing / modification is simply not been made for mac version. It is not able to load or use UI layout configuration of any kind.

**Comment by fosple** [comment]
Ok, thanks!

**Comment by Alexey-Yakovenko** [comment]
Design mode has been added. There are not many widgets yet, but this will come with time.

**Comment by fosple** [comment]
Thanks a lot @Alexey-Yakovenko - just tested it and it works perfectly 👍 :) Already looking forward to the "Playlist browser" widget.
