### ISSUE TITLE
Valid cue sheet raises exception

### ISSUE THREAD

**Issue by mgreshake** [DeaDBeeF-Player/deadbeef#2389]
### Steps to reproduce the problem

Execute a cue sheet that produces a negative return value of the method `pl_cue_get_field_value` in cueutils.c. Unfortunately, I cannot narrow down the problem yet. I have a whole bunch of cue sheets. Most of them work properly. So far, only one of them doesn't. Maybe because some tags contain special characters, but I'm not sure.

### What's going on? Describe the problem in as much detail as possible.

`if (field < 0) { goto error; }`

will drop an error, obviously. I think the query is too simple and sorts out some valid cue sheets.

### Information about the software:

Deadbeef version: a6ac452
OS: Kubuntu 20.04

**Comment by Alexey-Yakovenko** [comment]
So can you provide the problematic cuesheet?

**Comment by mgreshake** [comment]
Of course, sorry.

[Swiss & Die Andern - Grosse Freiheit.txt](https://github.com/DeaDBeeF-Player/deadbeef/files/4651395/Swiss.Die.Andern.-.Grosse.Freiheit.txt)

**Comment by Alexey-Yakovenko** [comment]
```
REM GENRE "Punk Rock"
REM DATE 2015
REM DISCID 8509260A
REM COMMENT "ExactAudioCopy v1.3"
PERFORMER "Swiss & Die Andern"
TITLE "Grosse Freiheit"
FILE "Track01.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Der Scheiss is' live"
    PERFORMER "Swiss & Die Andern"
    ISRC DEZ901401164
    FLAGS DCP
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Punk zur¸ck"
    PERFORMER "Swiss & Die Andern"
    ISRC DEZ901401165
    FLAGS DCP
    INDEX 00 03:37:60
FILE "Track02.flac" WAVE
    INDEX 01 00:00:00
  TRACK 03 AUDIO
    TITLE "Grosse Freiheit"
    PERFORMER "Swiss & Die Andern"
    ISRC DEZ901401167
    FLAGS DCP
    INDEX 00 03:33:66
FILE "Track03.flac" WAVE
    INDEX 01 00:00:00
  TRACK 04 AUDIO
    TITLE "Fick dich"
    PERFORMER "Swiss & Die Andern"
    ISRC DEZ901401168
    FLAGS DCP
    INDEX 00 03:59:12
FILE "Track04.flac" WAVE
    INDEX 01 00:00:00
  TRACK 05 AUDIO
    TITLE "Claire"
    PERFORMER "Swiss & Die Andern"
    ISRC DEZ901401169
    FLAGS DCP
    INDEX 00 03:40:74
FILE "Track05.flac" WAVE
    INDEX 01 00:00:00
  TRACK 06 AUDIO
    TITLE "Vermisse dich"
    PERFORMER "Swiss & Die Andern"
    ISRC DEZ901401173
    FLAGS DCP
    INDEX 00 03:08:57
FILE "Track06.flac" WAVE
    INDEX 01 00:00:00
  TRACK 07 AUDIO
    TITLE "Immer noch"
    PERFORMER "Swiss & Die Andern"
    ISRC DEZ901401175
    FLAGS DCP
    INDEX 00 03:01:74
FILE "Track07.flac" WAVE
    INDEX 01 00:00:00
  TRACK 08 AUDIO
    TITLE "F¸r dich k‰mpfen"
    PERFORMER "Swiss & Die Andern"
    ISRC DEZ901401176
    FLAGS DCP
    INDEX 00 03:58:04
FILE "Track08.flac" WAVE
    INDEX 01 00:00:00
  TRACK 09 AUDIO
    TITLE "Punkah auf Sri Lanka"
    PERFORMER "Swiss & Die Andern"
    ISRC DEZ901401179
    FLAGS DCP
    INDEX 00 04:12:68
FILE "Track09.flac" WAVE
    INDEX 01 00:00:00
  TRACK 10 AUDIO
    TITLE "Asche zu Staub"
    PERFORMER "Swiss & Die Andern"
    ISRC DEZ901401180
    FLAGS DCP
    INDEX 00 04:29:54
FILE "Track10.flac" WAVE
    INDEX 01 00:00:00
```

**Comment by denius** [comment]
After fixing this bug in https://github.com/DeaDBeeF-Player/deadbeef/commit/037fbabe93ec6f2f6e30fa92b583847759e318e5, there was another problem in .cue loading - DeaDBeeF shows all tracks of zero length, and only last one has the full length of the album. And it starts playing only from the first track, no matter which track is started.

If edit .cue to remove lines with `FLAGS DCP` then all good.

OS: ubuntu 18.04

**Comment by Alexey-Yakovenko** [comment]
sorry for that.. it was a bit tricky to repro and test. should work correctly now.

**Comment by gothluck** [comment]
I have the same problem on Ubuntu Studio 20.04.1 with DeadBeef 1.8.4:
if .cue sheet contain FLAGS DCP than all tracks have duration 0:00 and last track have duration of all .FLAC file.
If manually delete FLAGS DCP than all plays good.
This issues occurs in a last week or two.
![Screenshot_2020-12-11_17-53-38](https://user-images.githubusercontent.com/24501182/101925013-0d7ae800-3bda-11eb-830e-e1f53d9865bf.png)
![Screenshot_2020-12-11_17-54-50](https://user-images.githubusercontent.com/24501182/101925015-0e137e80-3bda-11eb-8ea6-9f03397351e2.png)
