### ISSUE TITLE
Feature request: Full scan option for mp3 file duration

### ISSUE THREAD

**Issue by yoyoma2** [DeaDBeeF-Player/deadbeef#2391]
Speed considerations force players to estimate duration. When the estimate is horribly wrong with certain mp3 files, it is necessary to have the option to perform a full scan to get usable results.

With the sample mp3 file given in issue #2390 mp3info gives the following results:

```
$ mp3info -p "%S\n" sample01.mp3
813
$ mp3info -F -p "%S\n" sample01.mp3
817
```
There is a four second error in the mp3info estimate vs the actual duration. In the deadbeef code cloned on 2020-05-19 there is an **eight second error** and no means to use the actual duration. Fixing issue #2390 by providing more accurate estimates would be nice but providing full scan ability for cases where estimates won't do, is still useful.

For those looking for this enhancement, a patch attached to issue #2390 gives you this ability in a quick/ugly way.

**Comment by Alexey-Yakovenko** [comment]
I don't think such option is necessary really.. VBR files get fully scanned anyway, and CBR size detection must always give accurate result, otherwise it's a bug. Therefore closing.

**Comment by yoyoma2** [comment]
Agreed. Your most recent duration code works well enough.
