### ISSUE TITLE
DeadBeef can't play a certain non-corrupted mp3 file

### ISSUE THREAD

**Issue by rasolar** [DeaDBeeF-Player/deadbeef#2392]
When I load a certain album to DeadBeef, the program can load all songs except one. I got this message error:

> ERROR: could not load: ~/Downloads/09. Héroe De Leyenda (Live).mp3

The problem is with `09. Héroe De Leyenda (Live).mp3`, the file `02. El Mar No Cesa.mp3` works fine, it's just for comparison.

The file `09. Héroe De Leyenda (Live).mp3` plays well in VLC and SMPlayer, so I don't think it's because of file corruption. And I tried this mp3 file renamed, but the problem persisted.

**Deadbeef version:** 1.8.3
**OS:** Kubuntu 20.04 64bit *(the file system is ext4)*

**Comment by Alexey-Yakovenko** [comment]
Thanks, got the files.
