### ISSUE TITLE
[mac][artwork] Local file mask being length limited on exit 

### ISSUE THREAD

**Issue by fightingdreamer** [DeaDBeeF-Player/deadbeef#2394]
### Steps to reproduce the problem
1. Open preferences > Plugins > Album Artwork
2. Set long file mask (example)
`front.png;front.jpg;folder.png;folder.jpg;cover.png;cover.jpg;f.png;f.jpg;*front*.png;*front*.jpg;*cover*.png;*cover*.jpg;*folder*.png;*folder*.jpg;Image0001.JPG;Cover.JPG;Cover.jpg;01.png;01.jpg;*.png;*.jpg;
`
3. Close preferences window
4. Exit DeadBeef
5. Start deadbeef
6. Open preferences > Plugins > Album Artwork
7. Get file mask (limited to 199 characters, 200 with '\0')
`front.png;front.jpg;folder.png;folder.jpg;cover.png;cover.jpg;f.png;f.jpg;*front*.png;*front*.jpg;*cover*.png;*cover*.jpg;*folder*.png;*folder*.jpg;Image0001.JPG;Cover.JPG;Cover.jpg;01.png;01.jpg;*.p`

### What's going on? Describe the problem in as much detail as possible.
In Plugin Album Artwork, local file mask being length limited on exit.

### Information about the software:
Lastest build for Mac OS.

Deadbeef version: Version 1.0 (3e7c048)
OS: Mac OS: 10.14.6

**Comment by Alexey-Yakovenko** [comment]
I bumped the max size to 1000 bytes.
