### ISSUE TITLE
Crash on editing mp3 tag for certain file

### ISSUE THREAD

**Issue by shooreek** [DeaDBeeF-Player/deadbeef#2396]
Program crashes on attempt to edit mp3 tag for certain file. Other mp3 files can be edited Ok with the same deadbeef version on the same system, problem occurs only with that file.

Steps:
1) Add file from link above to deadbeef
2) Modify tags (e.g. change Artist name or remove Album title)
3) Try to save -> program closes/crashes and next to mp3 file one can see <original_mp3_file_name>.temp file with zero length.

Deadbeef version: 1.8.3 (deb package)
OS: Kubuntu 18.04

**Comment by Alexey-Yakovenko** [comment]
Can't reproduce.

What I tried:

mac (latest build on master)
ubuntu 18.04: zip and deb
ubuntu 20.04: zip

**Comment by shooreek** [comment]
I'm back with the backtrace (I hope it is Ok), tried latest dev version and it is still crashing


`user@pc:~$ gdb deadbeef
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from deadbeef...done.
(gdb) r
Starting program: /usr/local/bin/deadbeef 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
starting deadbeef devel
server_start
searching for GUI plugins in /home/user/.local/lib64/deadbeef
searching for GUI plugins in /home/user/.local/lib/deadbeef
searching for GUI plugins in /usr/local/lib/deadbeef
load_plugin_dir /usr/local/lib/deadbeef: scandir found 88 files
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK3
selected GUI plugin not found or failed to load, trying to find another GUI plugin
the plugin not found or failed to load
the plugin not found or failed to load
loading plugin /usr/local/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/user/.local/lib64/deadbeef
loading plugins from /home/user/.local/lib/deadbeef
loading plugins from /usr/local/lib/deadbeef
load_plugin_dir /usr/local/lib/deadbeef: scandir found 88 files
loading plugin /usr/local/lib/deadbeef/aac.so
loading plugin /usr/local/lib/deadbeef/adplug.so
loading plugin /usr/local/lib/deadbeef/alac.so
loading plugin /usr/local/lib/deadbeef/alsa.so
loading plugin /usr/local/lib/deadbeef/cdda.so
loading plugin /usr/local/lib/deadbeef/converter.so
loading plugin /usr/local/lib/deadbeef/converter_gtk3.so
loading plugin /usr/local/lib/deadbeef/dca.so
loading plugin /usr/local/lib/deadbeef/ddb_dumb.so
loading plugin /usr/local/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/local/lib/deadbeef/ddb_shn.so
loading plugin /usr/local/lib/deadbeef/ddb_soundtouch.so
loading plugin /usr/local/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/local/lib/deadbeef/ffap.so
loading plugin /usr/local/lib/deadbeef/ffmpeg.so
loading plugin /usr/local/lib/deadbeef/flac.so
loading plugin /usr/local/lib/deadbeef/gme.so
loading plugin /usr/local/lib/deadbeef/hotkeys.so
loading plugin /usr/local/lib/deadbeef/in_sc68.so
loading plugin /usr/local/lib/deadbeef/m3u.so
loading plugin /usr/local/lib/deadbeef/mms.so
loading plugin /usr/local/lib/deadbeef/mp3.so
loading plugin /usr/local/lib/deadbeef/musepack.so
loading plugin /usr/local/lib/deadbeef/notify.so
loading plugin /usr/local/lib/deadbeef/nullout.so
loading plugin /usr/local/lib/deadbeef/oss.so
loading plugin /usr/local/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /usr/local/lib/deadbeef/psf.so
loading plugin /usr/local/lib/deadbeef/rg_scanner.so
loading plugin /usr/local/lib/deadbeef/shellexec.so
loading plugin /usr/local/lib/deadbeef/shellexecui_gtk3.so
loading plugin /usr/local/lib/deadbeef/sid.so
loading plugin /usr/local/lib/deadbeef/sndfile.so
loading plugin /usr/local/lib/deadbeef/supereq.so
loading plugin /usr/local/lib/deadbeef/tta.so
loading plugin /usr/local/lib/deadbeef/vfs_zip.so
loading plugin /usr/local/lib/deadbeef/vorbis.so
loading plugin /usr/local/lib/deadbeef/vtx.so
loading plugin /usr/local/lib/deadbeef/wavpack.so
loading plugin /usr/local/lib/deadbeef/wildmidi.so
loading plugin /usr/local/lib/deadbeef/wma.so
starting plugin GTK3 user interface
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter GTK3 UI
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Soundtouch
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
[New Thread 0x7fffd973b700 (LWP 11607)]
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin OSD Notify
starting plugin Null output plugin
starting plugin OSS output plugin
starting plugin Playlist browser GTK3
starting plugin PSF player using Audio Overload SDK
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec GTK3 UI
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
starting plugin FFMPEG audio player
selected output plugin: ALSA output plugin
INFO: from file /home/user/.config/deadbeef/playlists/0.dbpl
[New Thread 0x7fffd8f3a700 (LWP 11608)]
resume: track -1 pos -1.000000 playlist -1
[New Thread 0x7fffd8739700 (LWP 11609)]
[New Thread 0x7fffd7f38700 (LWP 11610)]
gtkui plugin compiled for gtk version: 3.22.30
[New Thread 0x7fffd7737700 (LWP 11611)]
[New Thread 0x7fffd6f36700 (LWP 11612)]
connecting button tray signals
[New Thread 0x7fffd5e9c700 (LWP 11613)]
[New Thread 0x7fffd569b700 (LWP 11614)]

Thread 9 "deadbeef-main" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd569b700 (LWP 11614)]
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:522
522     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: Нет такого файла или каталога.
(gdb) thread apply all backtrace

Thread 9 (Thread 0x7fffd569b700 (LWP 11614)):
#0  0x00007ffff73b1e4b in __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:522
#1  0x00005555555ab252 in junk_id3v2_add_comment_frame (tag=0x7fffd5698c60, frame_id=0x5555555cc99a "COMM", lang=0x5555555ccab5 "eng", descr=0x5555555cc132 "", value=0x555555ef7f35 "Только для ознакомления")
    at junklib.c:2171
#2  0x00005555555b213f in junk_rewrite_tags (it=0x5555558aec50, junk_flags=40, id3v2_version=3, id3v1_encoding=0x7fffd569adf0 "cp1252") at junklib.c:4747
#3  0x00007fffdc4ef9eb in cmp3_write_metadata (it=0x5555558aec50) at mp3.c:704
#4  0x00007ffff6b8bd06 in write_meta_worker (ctx=0x0) at trkproperties.c:556
#5  0x00007ffff761b6db in start_thread (arg=0x7fffd569b700) at pthread_create.c:463
#6  0x00007ffff734488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7fffd5e9c700 (LWP 11613)):
#0  0x00007ffff733e839 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff4ab687a in g_cond_wait_until () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4a43571 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4a98b14 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff4a98175 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff761b6db in start_thread (arg=0x7fffd5e9c700) at pthread_create.c:463
#6  0x00007ffff734488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fffd6f36700 (LWP 11612)):
#0  0x00007ffff7337bf9 in __GI___poll (fds=0x55555589df60, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff4a705c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4a70962 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff505e276 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff4a98175 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff761b6db in start_thread (arg=0x7fffd6f36700) at pthread_create.c:463
#6  0x00007ffff734488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fffd7737700 (LWP 11611)):
#0  0x00007ffff7337bf9 in __GI___poll (fds=0x555555891910, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
---Type <return> to continue, or q <return> to quit---
#1  0x00007ffff4a705c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4a706dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4a70721 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff4a98175 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff761b6db in start_thread (arg=0x7fffd7737700) at pthread_create.c:463
#6  0x00007ffff734488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fffd7f38700 (LWP 11610)):
#0  0x00007ffff76219f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555821878)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ffff76219f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x555555821820, cond=0x555555821850)
    at pthread_cond_wait.c:502
#2  0x00007ffff76219f3 in __pthread_cond_wait (cond=0x555555821850, mutex=0x555555821820) at pthread_cond_wait.c:655
#3  0x00005555555a7151 in cond_wait (c=93824995170384, m=93824995170336) at threading_pthread.c:221
#4  0x00005555555a58ed in messagepump_wait () at messagepump.c:130
#5  0x0000555555588f6e in player_mainloop () at main.c:826
#6  0x000055555558944a in mainloop_thread (ctx=0x0) at main.c:960
#7  0x00007ffff761b6db in start_thread (arg=0x7fffd7f38700) at pthread_create.c:463
#8  0x00007ffff734488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fffd8739700 (LWP 11609)):
#0  0x00007ffff733a03f in __GI___select (nfds=4, readfds=0x7fffd8738e60, writefds=0x0, exceptfds=0x0, timeout=0x7fffd8738e50) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x0000555555588b28 in server_loop (ctx=0x0) at main.c:689
#2  0x00007ffff761b6db in start_thread (arg=0x7fffd8739700) at pthread_create.c:463
#3  0x00007ffff734488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fffd8f3a700 (LWP 11608)):
#0  0x00007ffff73079d0 in __GI___nanosleep (requested_time=requested_time@entry=0x7fffd8f39e30, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007ffff733a877 in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#2  0x000055555559f630 in streamer_thread (unused=0x0) at streamer.c:1574
#3  0x00007ffff761b6db in start_thread (arg=0x7fffd8f3a700) at pthread_create.c:463
---Type <return> to continue, or q <return> to quit---
#4  0x00007ffff734488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fffd973b700 (LWP 11607)):
#0  0x00007ffff73079d0 in __GI___nanosleep (requested_time=requested_time@entry=0x7fffd973adc0, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007ffff733a877 in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#2  0x00007fffdcdfa0e2 in hotkeys_event_loop (unused=0x0) at hotkeys.c:501
#3  0x00007ffff761b6db in start_thread (arg=0x7fffd973b700) at pthread_create.c:463
#4  0x00007ffff734488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7fc7b80 (LWP 11603)):
#0  0x00007ffff7337bf9 in __GI___poll (fds=0x7fffffffc648, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff0eea747 in  () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007ffff0eec06f in  () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007ffff0eec1ef in xcb_wait_for_reply64 () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#4  0x00007ffff43186e8 in _XReply () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007ffff42fe435 in XGetWindowProperty () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007ffff5f5177f in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007ffff5f57810 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#8  0x00007ffff5f57329 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#9  0x00007ffff5f21d70 in gdk_display_get_event () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#10 0x00007ffff5f56f82 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#11 0x00007ffff4a70417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff4a70650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff4a706dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff5031efd in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007ffff6b4d3bb in gtkui_start () at gtkui.c:1515
#16 0x000055555558a58e in main (argc=1, argv=0x7fffffffdf98) at main.c:1345
(gdb) 
`

**Comment by Alexey-Yakovenko** [comment]
The issue you are having is caused by build settings from an unofficial build you are using. It should not be happening with any builds available to download from https://https://deadbeef.sourceforge.io/ -- so at least you have a workaround.
I'll investigate how to fix this though.

**Comment by Alexey-Yakovenko** [comment]
hmm. after inspecting the trace more carefully, it's not what I thought it was. It looked like unaligned memory access, but it looks like some garbage data access - which I still can't reproduce.

**Comment by shooreek** [comment]
But as far as I can see you haven't tried on Kubuntu, maybe it is the key... Some GUI-related stuff. Anyways, if you have any ideas on how to get more info on that crash, I will be happy to assist.

**Comment by Alexey-Yakovenko** [comment]
I have one idea, that you provided a wrong test file.
In your trace, the code being executed is adding a Comment field to the id3v2.
In the file you provided, this field is not present -- so this code won't ever execute for me.

**Comment by Alexey-Yakovenko** [comment]
also, the code which crashes is not related to UI at all. Kubuntu or not should not matter.

**Comment by Alexey-Yakovenko** [comment]
oh cool. I added this comment field same as you wrote, and it crashed.
all good, now it should be fixable.
