### ISSUE TITLE
SomaFM radio playback does not start

### ISSUE THREAD

**Issue by vdemin** [DeaDBeeF-Player/deadbeef#2399]
### Steps to reproduce the problem

Try to play radio stream from [somafm.com](http://somafm.com), any channel, e.g. [somafm.com/groovesalad](http://somafm.com/groovesalad/)

1. Add location http://somafm.com/groovesalad130.pls (AAC) or http://somafm.com/groovesalad256.pls (MP3)
2. Start playing the stream
3. Playback does not start

### What's going on? Describe the problem in as much detail as possible.

When I try to start playing the stream, I see the ellipsis in "♫" column and that's it.

### Information about the software:

Deadbeef version: 1.8.3
OS: Arch Linux

**Comment by Alexey-Yakovenko** [comment]
This regression was introduced by added workaround for issue #2125
I reverted it, the radio plays fine, and 2125 is not happening anymore -- so I suppose something else fixes it.
