### ISSUE TITLE
Trying to play specific formats pauses the track initially

### ISSUE THREAD

**Issue by JakeSFR** [DeaDBeeF-Player/deadbeef#2400]
Linux x86_64, clean config, official static build, current master https://github.com/DeaDBeeF-Player/deadbeef/commit/19dea257b38b7c1d03c52b126d3c54bb13f9936c.

As title says, trying to play a AAC/AMD/D00/FLAC/GYM/HSC/IT/M4A/MID/MOD/NSF/SAP/SID/VTX/WMA/XM file for the first time after starting DB, either by clicking Play button or double-clicking the track itself (or simply by starting DB when the option "Resume previous session on startup" is enabled), results in that track being paused.
After the first occurence everything starts working ok, so in order to reproduce it again, DB must be restarted.

AMR, MP3, OGG, OPUS and WAV files are not affected.

**Comment by Alexey-Yakovenko** [comment]
@JakeSFR I can't reproduce. Can you try any revision from before today? Do you have the same problem?

**Comment by JakeSFR** [comment]
> @JakeSFR I can't reproduce. Can you try any revision from before today? Do you have the same problem?

Hmm, initially I have observed it in a revision I downloaded a week ago or so and only then used the latest to ensure that it's still there.
But I just checked and it goes back to at least 0.8.3.

Anyway, to rule out my OS' (Fatdog64) possible interference, I tried again in Mint 18.3 and the same happens:

![out](https://user-images.githubusercontent.com/6226504/84697210-071ef280-af4e-11ea-8cfa-a7e56dc7c7dd.gif)

**Comment by Alexey-Yakovenko** [comment]
seems like a bug in the output plugin.. is it ALSA or Pulse?

**Comment by JakeSFR** [comment]
That would be ALSA.
Can't test DB with Pulse on Fatdog64, because we don't ship it, but Mint does, fortunately, and indeed, the problem doesn't occur with Pulse.

**Comment by Alexey-Yakovenko** [comment]
ok, I'll try to play with this as soon as I can.

**Comment by Alexey-Yakovenko** [comment]
Reproduced.
