### ISSUE TITLE
Crash on applying ReplayGain on some files with lyric tag

### ISSUE THREAD

**Issue by jonpatterns** [DeaDBeeF-Player/deadbeef#2402]
### Steps to reproduce the problem

1. Load a track with lyric tag 
2. In track property <UNSYNCED LYRICS> the lyrics will oddly have the prefix 'None:' (In Kid3 lyrics are shown normally under the property Lyrics)
3. Scan per file Track Gain if Not Scanned
4. Scanning completes successfully, but crashes on selecting update tags

### What's going on? 
Different errors are shown in terminal when crashing:

Segmentation Fault
malloc(): invalid size (unsorted)
Aborted (core dumped)

Segmentation Fault
malloc(): smallbin double linked list corrupted
Aborted (core dumped)

Segmentation Fault
corrupted double-linked list
Aborted (core dumped)

However, I tried adding lyrics to a different mp3 and it work okay without crashing.

The problem mp3s were downloaded from (Track 2-6): https://icnfly.bandcamp.com/album/oceans-beyond-earth-ep
So not sure if they are the problem, but I have nothing else to test.
I compiled the devel version and it did not crash following the above procedure. However, for a file that has been scanned the Lyrics property appears empty in Kid3 - however, it is still shown under <UNSYNCED LYRICS> in DeadBeef (still with the prefix 'None:')

### Information about the software:

Deadbeef version: 1.8.3
OS: Manjaro Linux XFCE (up to date)

**Comment by Alexey-Yakovenko** [comment]
The tag writing bug was valid in 1.8.3 indeed, but already has been fixed in 1.8.4-beta.
The bug with "None:" prepended to the lyrics is valid and being investigated.

**Comment by Alexey-Yakovenko** [comment]
The "None" text is in the tag, which is why deadbeef loads and displays it.. but since it's quite useless for display purpose, I changed the code to strip it.

I didn't test Kid3 compatibility yet, going to do this now

**Comment by Alexey-Yakovenko** [comment]
Checked Kid3, it loads the tag just fine here after editing in deadbeef.
Foobar2000 same.

**Comment by jonpatterns** [comment]
Brilliant, glad it's already been fixed. :)
