### ISSUE TITLE
Playback session/position is not saved immediately, and lost on abnormal termination

### ISSUE THREAD

**Issue by matklad** [DeaDBeeF-Player/deadbeef#2406]
Deadbeef is capable restoring the session after normal shutdown (closing the windows, exit shortcut etc). 

However, if the terminlatino is abnormal (`sudo poweroff`), the session is not restored. 

It would be nice if deadbeef persisted session after each track change/each 5 seconds, so that it can restore even after an abrupt crash. 

### Information about the software:

Deadbeef version: 1.8.0
OS: LInux/NixOs

**Comment by Oleksiy-Yakovenko** [comment]
This issue will not be fixed, since it conflicts with another scenario:
deadbeef crashes for a legit reason when trying to play certain media file (due to some unknown bug).
If "resume playback" is not cancelled -- this would lead to an unrecoverable crash-cycle.
