### ISSUE TITLE
[Question] Why DeaDBeef is not in the official repositories of Ubuntu yet?

### ISSUE THREAD

**Issue by hmslima** [DeaDBeeF-Player/deadbeef#2407]
DeaDBeeF is my favorite music player, and I am glad that I could install it in Kubuntu through a PPA.

\*ubuntu and its direct derivatives (like Linux Mint) are very popular, so why a project like DeaDBeeF is not already in the official repositories of Ubuntu while "minor" projects are already there? I know that users can install this software through many methods like I did, but making DeaDBeeF available in the official repositories would make the life of potential users easier.

I know that you cannot update the software in the \*ubuntu's repositories by yourselves, but I think that the software already is pretty stable, well at least it was in the version 1.8.3, I updated to the version 1.8.4 just now.

<hr>

I admit that I don't know what you have to do to put your software in the repositories of \*ubuntu, but since I see minor softwares from GitHub there, I think that it's not much difficult.

**Comment by Alexey-Yakovenko** [comment]
All aspects of this question cannot be easily explained in a bug tracker question format.

A short answer is: Deadbeef source code and development process is not compatible with requirements of Debian/Ubuntu, Gentoo and Fedora system maintainers, and cannot be changed without harming the quality / end users.

It's unlikely that you will ever see Deadbeef in the official "system" repositories of mainstream linux distributions.
