### ISSUE TITLE
Can't launch DeaDBeeF

### ISSUE THREAD

**Issue by fiftydinar** [DeaDBeeF-Player/deadbeef#2411]
Deadbeef version: 1.8.4 nightly
OS: Linux Manjaro KDE

As it says in the title, I can't launch DeaDBeeF. This happened after some Linux Manjaro update. I also tried older versions but it's not working. I executed deadbeef file as it should. I think that is because I have newer version of gtk2 (2.24.32-2) & gtk3 (3.24.20-1) which DeaDBeeF doesn't currently support. It says: GTK2 >= 2.16, and/or GTK3 >= 3.10.0. That's my opinion, I'm waiting for developer's solution. Thank you.

**Comment by Alexey-Yakovenko** [comment]
Please provide the log (printed to console)
