### ISSUE TITLE
DSD to .wv conversion creates big files

### ISSUE THREAD

**Issue by arielsboiardi** [DeaDBeeF-Player/deadbeef#2415]
### Steps to reproduce the problem

- Get a dsd (.dsf and .dff tested) file, for example [this free sample](http://www.lindberg.no/hires/test/2L-125_stereo-11289k-1b_04.dsf.zip) which is 276 MB
- Open in DeaDBeeF
- Convert with wavpack with default settings sample format 24 bit

### What's going on? Describe the problem in as much detail as possible.
Resulting file comes out to be 678 MB, while deconding with `wavpack [input file]` requires less time and produces a file of size 137.2 MB, which is more reasonable.

I honestly cannot figure out what is going on, because the files seem to me very similar in terms of bitrate, depth and so on. 
I hope not to be missing something crucial, in which case I apologize for losing your time. 

### Information about the software:

Deadbeef version: 1.8.4 
OS: Fedora 32
wavpack 5.3.0
libwavpack 5.3.0

**Comment by Alexey-Yakovenko** [comment]
dsf files get decoded at very high sampling rate -- 300K+.
When they are played back, they get resampled to something lower -- e.g. 48K or whatever your output device is configured to.

If you want to transcode into wavpack, you should add resampler to the converter DSP chain, and configure it to desired sampling rate.

Technically, what you're seeing works as designed.

**Comment by arielsboiardi** [comment]
It was definitely missing something...as expected...

So that resampling in the output stage is what caused the stemperate reading to be the same in both cases at about 120K...

Thanks for your kind support!
