### ISSUE TITLE
APE 24/44.1 - harsh noise

### ISSUE THREAD

**Issue by clasatas** [DeaDBeeF-Player/deadbeef#2416]
When encoding in ape 24 / 44.1 format, the records were damaged. If you decode ape file to wav using the console, then there are no problems. So the matter is in the player's decoder.
At 24/48 everything is fine.

Короче, перегнал я всю свою фонотеку в APE и был рад. Но когда услышал, что всё что в 24/44.1 угроблено стал совсем не рад. Дело оказалось не в кодеке, он то кодирует\декодирует без проблем, а в декодере deadbeef (а так же ffmpeg, gstreamer). После общения с автором APE, выяснил, что кодек последнее время активно развивается, меняется, а декодер в deadbeef, ffmpeg основан на устаревшем коде из rockbox. Так как теперь быть, идти на трекер rockbox ? Но там вряд ли помогут, так как в описании декодера:

> but 24-bit files are causing problems in the range decoder.

**Comment by Alexey-Yakovenko** [comment]
Все верно, deadbeef использует декодер APE основанный на коде rockbox и ffmpeg.
Также, можно опционально проигрывать APE средствами ffmpeg.
Официального monkey's audio decoder не будет в обозримом будущем, или вообще никогда.

> Так как теперь быть

использовать другие форматы, для которых есть нормальные кодеки в опенсорсе.
альтернативно -- использовать windows/wine и foobar2000.
