### ISSUE TITLE
Ubuntu -- player crashes when scanning the folder -- how do I send a log for a bug report?

### ISSUE THREAD

**Issue by deathisinevitable** [DeaDBeeF-Player/deadbeef#2420]
### Steps to reproduce the problem
1 we open the latest version of the player
2 try to scan the folder with music
3 and the player crashes

### Information about the software:

Deadbeef version:1.8.4
OS: Ubuntu

**Comment by Alexey-Yakovenko** [comment]
Please provide the call stack.
You can get it by following the instructions here:
https://github.com/DeaDBeeF-Player/deadbeef/wiki/GDB-HOWTO

**Comment by Alexey-Yakovenko** [comment]
No response from the reporter.
