### ISSUE TITLE
Album art filename search by album name metadata field

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#2424]
Feature request sent by email

> My music collection uses the Winamp format for album art display: if there is the an image file with the same name as the 'Album' metadata in the music file, it will display this before displaying image files named `folder.*`, `front*`, `cover.*` etc. This means that there can be several music files in a folder, and each can be assigned different album artwork. 
>
> Would it be possible to make an addition to the album art display facility of DeaDBeeF which offers this option? I would have thought it wouldn't be too difficult to put this into the series of searches the album art display does when it loads a new track.

**Comment by mallniya** [comment]
As for https://github.com/DeaDBeeF-Player/deadbeef/issues/559 this issue is superseded by https://github.com/DeaDBeeF-Player/deadbeef/issues/1131
