### ISSUE TITLE
Last FM Scrobbler not scrobbling

### ISSUE THREAD

**Issue by mistersister** [DeaDBeeF-Player/deadbeef#2425]
The Scrobbler apparently is not working. I can't see any scrobbles from Deadbeef on my last.fm profile

I have tried changing the scrobling endpoint from http to https as sugested on #1602 but there is no difference. Also I checked user/passwd.

Upon realizing the fact, I checked the web and upgraded to deadbeef 1.8.4 fro 1.8.3 and still not working. I can't say when the issue started since I don't check daily but looking at my scrobbling history looks like has been going on for a long time.

Tested on:
DeaDBeeF 1.8.3 static build on Arch Linux
DeaDBeeF 1.8.4 static build on Arch Linux

**Comment by Alexey-Yakovenko** [comment]
The scrobbler works fine -- I have scrobbles from this week.
The most common reason why it stops working is when your computer time is set wrong.

**Comment by KernelModule** [comment]
I have this problem too. Computer time is synced, I checked it.

**Comment by Alexey-Yakovenko** [comment]
It still works fine here. I don't know what I can do to help. These are my settings.
![image](https://user-images.githubusercontent.com/1895698/89863417-58dca580-dbaa-11ea-8a17-55efcc27a692.png)

**Comment by Alexey-Yakovenko** [comment]
There was only one change to lastfm plugin in May, which resolved a regression causing icy/shotcast streams to not scrobble.
It should not have affected regular file scrobbling. But you could try a build from master branch and see if it helps. At least in this case we'll know we're running the same code: https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download

**Comment by mistersister** [comment]
@KernelModule, I resolved my issue by enabling ntp on systemd:

`sudo timedatectl set-ntp yes`

**Comment by 4oo4** [comment]
I think having Send MusicBrainz ID enabled broke it for me, turning that off seems to fix it.
