### ISSUE TITLE
How to add filebrowser to UI correctly?

### ISSUE THREAD

**Issue by zilexa** [DeaDBeeF-Player/deadbeef#2426]
Ubuntu Budgie 20.04
Deadbeef .deb file downloaded from site and installed.

I have installed the filebrowser plugin correctly, but I do not understand how to add it to the UI. After enabling Design Mode, I still cannot do anything but replace an existing part of the UI. 
I only managed to replace some part of the UI with a filebrowser address, which is a bit useless:
![screenshot1](https://i.ibb.co/dQy1Yj6/Screenshot-from-2020-08-06-22-23-09.png)

How can I get it in a right-side column, for example like this screenshot (actually, exactly that layout, with the dark background and all, but most importantly the location of filebrowser):
![screenshot1](https://i.imgur.com/mESVgA0.png)

**Comment by kuba160** [comment]
You need to replace elements with placeholder elements such as splitter/vbox/hbox.

**Comment by zilexa** [comment]
I right clicked everywhere but don't get a context menu only at the top.. no splitter/vbox/hbox options..

**Comment by kuba160** [comment]
You find these in same menu where you replaced playlist with file browser. If you want to start fresh delete your config (it is probably in `.config/deadbeef` in your home directory).

**Comment by Alexey-Yakovenko** [comment]
You need to use design mode (which is similar to FB2K layout editing mode).
It allows to right click on UI elements, and replace / delete / copy / paste them with other elements.
This allows to create the layout structure that you need using container elements -- such as the aforementioned VBox/HBox/Splitter, set them up to your desired behavior, and then populate the containers with the UI elements you want.

**Comment by zilexa** [comment]
I have no clue what FB2K means and as mentioned I did use Design Mode. Right clicked everywhere but only get option to replace something at the top. I'm not a developer but not stupid either. It's not the most intuitive or user friendly way of organising an audio player UI so my question isn't that strange right?

**Comment by Alexey-Yakovenko** [comment]
FB2K means "Foobar2000" -- it's a popular music player for Windows, and Deadbeef was originally created to basically be a clone of it. The layout editing / design mode was intentionally created to be familiar to Foobar2000 users. It can be quite unintuitive.

if you enable "design mode" and right clicking the UI elements doesn't show the menu and doesn't allow you to edit the UI -- I suggest resetting the layout and starting over.

This can be achieved by editing ~/.config/deadbeef/config, and deleting the line with the layout.. I don't remember the option name, but it has "layout" word in it - I think it will be pretty obvious when you see it.

Your screenshot contains a 3rd party UI component, and I can't provide any support for it -- perhaps it's what's causing problem.

**Comment by zilexa** [comment]
Thanks for the explanation, with that I managed to create a similar layout. Next steps are to get the color scheme. I google some more.
