### ISSUE TITLE
Global hot keys aren't working after pc wakes up from sleep or restart

### ISSUE THREAD

**Issue by rb201** [DeaDBeeF-Player/deadbeef#2428]
### Steps to reproduce the problem
If I put the pc to sleep or is restarted, the play button on the keyboard is no longer active 

### What's going on? Describe the problem in as much detail as possible.
In my preferences, Key Combination XF86AudioPlay is set to perform the 'play/pause' action. Global is set to true. When the pc is restarted or awakened from sleep, the play button no longer functions. However, the hotkey is still set - the config is there in the menu, I simply have to hit the Apply button to activate it.

### Information about the software:
Deadbeef version: 1.8.3

OS:
Linux nebula 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 8.2.2004 (Core) 
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"

**Comment by vmarkovtsev** [comment]
I have figured out that it interferes with Chromium in my case. I [disabled media keys in Chromium](https://www.omgchrome.com/chrome-google-music-media-keys/) and this problem no longer bothers me.

**Comment by Alexey-Yakovenko** [comment]
When the system goes to sleep, and wakes up from sleep, it's a transparent process for the application, and it's not supposed to take any actions to adjust for any data loss that occurred. There's no point to add hacks on the application side, to detect that the system awoke from sleep, and deleted keyboard state, so the applications need to reapply it. Instead, the system needs to do it correctly. Fixing it on the application side would just make it worse, and will break something else for someone else. Therefore, I'm closing this as "won't fix".

**Comment by rb201** [comment]
Thanks for taking the time to look into this. What should the system be doing? What is 'it'? The application doesnt need to be hacked or checked if woken from sleep; If I need to reapply the application config, it seems that the application configuration is not applied ie the state of the app has changed.  Ensuring that the config is applied doesn't sound like a hack. At any rate thanks again, I will manage, the bug isn't a deal breaker
