### ISSUE TITLE
Won't submit scrobbles of the same song on repeat to last.fm

### ISSUE THREAD

**Issue by sennowa** [DeaDBeeF-Player/deadbeef#2430]
### Steps to reproduce the problem

1. Upon installing deadbeef, enter your last.fm credentials in the plugin.
2. Play the same song with playback set to "Repeat -> One song" multiple times.

### What's going on? Describe the problem in as much detail as possible.

The "now playing" information is being sent to the last.fm server, but after the song finishes and starts playing again, the scrobble doesn't get added to the profile.

### Information about the software:

Deadbeef version: 1.8.4
OS: Kubuntu 20.04

**Comment by Alexey-Yakovenko** [comment]
Fixed in commit eb7527370c923bda48f0bbf0f59a165ea0f63a84
