### ISSUE TITLE
"Delete from disk" deletes selected song instead of one you right-clicked

### ISSUE THREAD

**Issue by axredneck** [DeaDBeeF-Player/deadbeef#2432]
Yes, they can be different songs.

### Steps to reproduce the problem
- Start any song
- Right click song you want to delete
- Wait until current song ends and next one begins
- Click "Delete from disk"

### What's going on? Describe the problem in as much detail as possible.
Next song becomes selected, and "Delete from disk" deletes it, instead of one you right-clicked.

### Information about the software:

Deadbeef version: 1.8.4
OS: Arch Linux

**Comment by DaarkWel** [comment]
As some workaround and UI improvement I'd suggest add filename of removing song to the confirm dialog. Not just "Do you really want to delete selected file" as it is now, but an actual filename(s).

**Comment by axredneck** [comment]
@DaarkWel it will not help because it will display right name but will still delete wrong file.

**Comment by saivert** [comment]
foobar2000 doesn't move the selection with the currently playing track which is what I would have done to fix this.

An alternative approach is to simply not move the selection with the playing track if it has been changed by the user. So if the user starts playing a track but then never selects another track then deadbeef will move the selection with track changes. A flag that is reset every time you start playing a new track manually. Though I assume this flag would have to be per-playlist. What do people think?

**Comment by Alexey-Yakovenko** [comment]
Some progress on this issue:

I implemented the cross-platform infrastructure to capture track list at the moment when the context menu opens.
This way the selection changes won't affect the result of the context menu.

I integrated this code into macOS cocoaui, but gtkui for linux/windows still needs quite a bit more work.

**Comment by Alexey-Yakovenko** [comment]
The fix for GTKUI has been added on master branch.
It's not going to be included in the 1.8.7 release because of the risk though.
