### ISSUE TITLE
Long title-names from "Group by..." must be shortened

### ISSUE THREAD

**Issue by 64542426** [DeaDBeeF-Player/deadbeef#2436]
### Steps to reproduce the problem
I have songs where Artists are numerous or have long names for this reason it happens that the names are cut in half. Please [Check the image](https://i.imgur.com/TFLhq0y.png)
The long text above selected song is from group by Artists the same may happens to the group by Artist/Date/Album if text is long.

### What's going on? Describe the problem in as much detail as possible.
I hope to be clearly understandable

If group by names can follow the window dimension, will help to shorten the long names. Like:
_天海春香(CV:中村繪里子)/如月千早(CV:今井麻美)/萩原雪歩(CV:浅倉杏美)/水瀬伊織(CV:釘...

Something similar to the selected song where artist text is limited because the column is shortened.

Please consider this only a cosmetic record. Thank you!

### Information about the software:

Deadbeef version: latest-devel
OS: Devuan GNU/Linux 4 (chimaera/ceres)

**Comment by Alexey-Yakovenko** [comment]
There was a similar issue in cocoaui, which I fixed, but can't fix gtkui atm, will have to wait a bit, until I can run gtkui version on mac, and / or virtualbox with linux :)

**Comment by 64542426** [comment]
Nothing in a hurry bro, give priority those that matter the most.
