### ISSUE TITLE
Short tracks repeating on shuffle

### ISSUE THREAD

**Issue by alaviiva** [DeaDBeeF-Player/deadbeef#2438]
### Steps to reproduce the problem
* Create a playlist containing short tracks (a few seconds in duration)
* Set playback to shuffle 
* Start palyback

### What's going on? Describe the problem in as much detail as possible.
At the end of a track playback continues to next track on the list and these two repeat for a few times before continuing on a shuffled track. 
For example if you have a playlist containing tracks 1-10 playback would be something like 1,2,1,2,1,6,7,6,7,6,3,4,3 etc.

I generated some tracks containing 1 second of silence to help with testing.
[test.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/5143291/test.zip)

### Information about the software:

Deadbeef version: 1.8.4
OS: Ubuntu

**Comment by Alexey-Yakovenko** [comment]
Can you please check if this bug is still valid in 1.8.5-beta2?

**Comment by Alexey-Yakovenko** [comment]
nvm, verified myself, it's still valid
