### ISSUE TITLE
Album art now showing even when the plugin is installed and seems to work. (windows 10)

### ISSUE THREAD

**Issue by CoopJax** [DeaDBeeF-Player/deadbeef#2442]
### What's going on? Describe the problem in as much detail as possible.
I have not done anything to my deadbeef for some time and I wanted to see some album art. I found the plugin and tried to get it started but I cannot see any art on the side. I don't understand what to do and am wondering if it doesn't work on windows. I found the instructions but can't seem to find the "Group by" sub menu.
### Information about the software:
Nothing has been done to deadbeef except for a discord rich presence plugin.
Deadbeef version:
OS: Windows 10

**Comment by kuba160** [comment]
> I found the instructions but can't seem to find the "Group by" sub menu.
Right click headerbar (doesn't matter where), it should be on the last place in the context menu

**Comment by CoopJax** [comment]
That doesn't seem to do anything. I don't understand how to add a column either. I'm new to deadbeef so stay patient pls.

**Comment by kuba160** [comment]
You need to add new column with type `Album art` and then group by `Artist/Date/Album`.
![image](https://user-images.githubusercontent.com/6359901/92404398-c3deb500-f133-11ea-8b56-44fafddcd1ff.png)

**Comment by CoopJax** [comment]
Oh I was clicking on the wrong thing. Thanks for the help!
