### ISSUE TITLE
[Feature request] Show radio station names when adding locations

### ISSUE THREAD

**Issue by panos** [DeaDBeeF-Player/deadbeef#2446]
### Steps to reproduce the problem

- Add a bunch of radio stations, like, say, the ones by [SomaFM](https://somafm.com/listen/).
- Switch between them, a lot. The displayed metadata will change to the ones shown by the track that's currently playing.
- Your playlist now looks a bit messy.

**Comment by Alexey-Yakovenko** [comment]
duplicate of #2236
