### ISSUE TITLE
x86_64-pc-linux-gnu-gcc: error: unrecognized command-line option ‘-fblocks’

### ISSUE THREAD

**Issue by perfect7gentleman** [DeaDBeeF-Player/deadbeef#2449]
### Steps to reproduce the problem
build git version
### What's going on? Describe the problem in as much detail as possible.
doesn't build due to error
### Information about the software:
gcc-10.2
Deadbeef version: git
OS: Gentoo GNU/Linux

**Comment by Alexey-Yakovenko** [comment]
It's no longer supported to build deadbeef using GCC.
Deadbeef requires Clang.
You will also need to install libdispatch and libblocksruntime.
Documentation and build scripts are in the process of being updated to provide the appropriate information.

**Comment by martinetd** [comment]
Just stumbled on that as well -- personal opinion aside, would it be possible to add a configure check for it? Folks upgrading blindly like me would appreciate it :)

**Comment by Alexey-Yakovenko** [comment]
I'm not yet sure how to best implement this particular check, but please be sure I will add it as soon as it's decided.

**Comment by ToadKing** [comment]
This autoconf script might be what you want, but I know next to nothing about autotools or how to implement it.

https://www.gnu.org/software/autoconf-archive/ax_check_compile_flag.html

**Comment by Alexey-Yakovenko** [comment]
Thanks

**Comment by eleksir** [comment]
Лёш, ну какого хрена? Зачем ты притащил libdispatch? Из-за этого эпловского говна теперь надо использовать сравнительно свежий clang, а раньше можно было собрать всё и с помощью gcc.
Скажу больше - раньше deadbeef можно было собрать любым дремучим gcc или дремучим clang-ом, а сейчас нужен шланг с -fblоcks. Зачем ты портишь такой хороший софт таким вот эпловским говнишком?

**Comment by Alexey-Yakovenko** [comment]
-fblocks и libdispatch очень облегчает разработку. для тех кто не может или не хочет собирать - бинари предоставлены, и работают на линуксах 7-летней давности. по-моему, 7 лет вполне достаточно, и даже избыточно.
часто поступают запросы обновить тулчейн на что-то более свежее.

**Comment by perfect7gentleman** [comment]
У меня сборка минимальная и собирается GCC уже давно опять.

**Comment by nondeterministic** [comment]
I've just ran into the same issue with compiling 1.8.8. and I'm not sure what the Russian above means. But an easy fix just to get the code to compile is to run `./configure CC="clang-9" CXX="clang++-9"` on the command line, because the configure script still doesn't seem to set the correct tools and flags in this version. Hope, this is helpful to some.

**Comment by Alexey-Yakovenko** [comment]
@nondeterministic yes, this is exactly what the README file tells you to do:
```
1.2 Compiling

* Set CC and CXX environment variables to clang and clang++ respectively.
```

**Comment by Alexey-Yakovenko** [comment]
configure script is not supposed to override the user's choice of the compiler. the compiler to use is specified in the system environment variables. On linux it's typically gcc, on mac and windows it's clang.

**Comment by Alexey-Yakovenko** [comment]
The stuff you can't read in russian is not relevant to this issue, it's just some rants.

**Comment by nondeterministic** [comment]
Sorry, didn't see. I looked at `INSTALL` and saw only generic comments.

**Comment by Alexey-Yakovenko** [comment]
The INSTALL file is generated by autotools, so there's no custom content in there

**Comment by wdlkmpx** [comment]
I can't believe GCC is not supported, you might as well get rid of the auto tools build system. Deadbeef is DEAD now and forever.
