### ISSUE TITLE
Hotkeys eventually stop working

### ISSUE THREAD

**Issue by arcasinky** [DeaDBeeF-Player/deadbeef#2450]
### Steps to reproduce the problem
1. Start DeaDBeeF
2. Go to preferences, verify that media hotkeys are properly configured and that they work
3. Wait, possibly change focus to other apps
Result: Hotkeys eventually stop working
4. Go back to the hotkey settings dialog, click 'Apply'
Result: Hotkeys start working again.  For a while.
5. Wait
Result: Hotkeys eventually stop working

### What's going on? Describe the problem in as much detail as possible.
In a nutshell, hotkeys appear to work for a while then they stop working.  Pressing the 'play' hotkey, for example, causes Gnome to display a 'crossed-out zero' notification that I presume means that that key no longer defined.

In particular, the hotkeys I'm trying to use are 'next', 'prev', 'play/pause' and volume.  Inside DeaDBeeF's settings, the 'global' checkbox is checked.

This is easily reproducible if I change focus from DB to, say, vim running in a Gnome Terminal window but I also see it if I switch focus to, say, Firefox.  I could perhaps understand this behavior if the app that's getting focus defines its own media hotkeys but I can't believe that Gnome Terminal defines its own hotkeys.  In fact, I've twice seen DB's hotkeys stop working even if focus never leaves DB.

I can go back to DB's hotkey settings dialog, click 'apply' and hotkeys will start working again.  But they'll again quickly stop working.

I do not see this behavior with other music player apps like Audacious.

Any ideas what I'm doing wrong?

### Information about the software:

Deadbeef version: 1.8.4 (from OpenSUSE's "Packman" repository)
OS: OpenSUSE 15.2
Gnome: 3.34

**Comment by Alexey-Yakovenko** [comment]
Multimedia hotkeys are managed by GNOME, and can't work correctly when assigned from within the app.
You will need to use one of the available plugins, such as mpris or gnome-mm-keys.
