### ISSUE TITLE
design mode: can not remove vbox / hbox

### ISSUE THREAD

**Issue by milahu** [DeaDBeeF-Player/deadbeef#2451]
### Reproduce the problem

1. menu > view > design mode > on
2. remove one widget to make space
3. insert a vbox or hbox widget
4. try to remove the vbox / hbox

### Describe the problem

there is no easy way to remove the widget
somehow i got it removed, but dont know how exactly

usually, when i right-click a widget, i see the options
replace, delete, cut, copy, paste

with the splitter widgets, i must right-click the splitter/resize handle to get that menu

with the box widgets, there is no such handle
and right-clicking the widget-slots only gives the menu: insert, paste

### Possible solution

show the 'container menu' also on right-click on a container slot

### Version

Deadbeef version: 1.8.4

**Comment by Alexey-Yakovenko** [comment]
I agree that it's not the most convenient, but you will get the desired menu, if you click on one of the dividers in the vbox.
Although, if vbox has only 1 slot - yeah, there's a problem.

**Comment by milahu** [comment]
> you will get the desired menu, if you click on one of the dividers in the vbox.

aah, yes. problem is: the dividers are only 1px thick = poor accessibility
plus there is no "hover" effect on the divider, so i must guess where exactly i have to click

**Comment by Alexey-Yakovenko** [comment]
Agreed, the issue is there. I knew about it from the very moment when this feature was developed, but this one particular problem was not the highest importance :) and probably still isn't since this is something you do once and never go back.

**Comment by saivert** [comment]
@milahu can this be closed now considering above patch?

**Comment by Alexey-Yakovenko** [comment]
It can! Also, I already added the same Parent submenu to design mode implementation on mac :)
