### ISSUE TITLE
Integrate with KDE Plasma

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [DeaDBeeF-Player/deadbeef#2452]
I'm not sure how to put this right. Other media players are somehow integrated in KDE Plasma, so that you have play / pause buttons on the lock screen. Can this be implemented for deadbeef, too?
In combination with KDE Connect it would be very nice.

### Information about the software:

Deadbeef version: 1.8.4
OS: Manjaro 
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0

**Comment by kuba160** [comment]
Check 3rd party [deadbeef-mpris2-plugin](https://github.com/Serranya/deadbeef-mpris2-plugin).

**Comment by Alexey-Yakovenko** [comment]
Indeed. It should work via MPRIS plugin. Please let us know if it doesn't work for some reason.
