### ISSUE TITLE
"Album Artist" tagging issue on MP3 files

### ISSUE THREAD

**Issue by gapf2010** [DeaDBeeF-Player/deadbeef#2453]
### Steps to reproduce the problem
Add MP3 files tagged on iTunes to Deadbeef. Since I play my MP3 files from an iPod, that's the default for me.

### What's going on? Describe the problem in as much detail as possible.
The MP3 files have a comment of `<BAND>` showing the correct "Album Artist" information, however the actual "Album Artist" tag remains empty on the "Selection properties" dialog. This brings problems when grouping compilation albums by "Album Artist". Interestingly, the "Band / Album Artist" column displays the correct value for all of my MP3 files.

### Information about the software:

Deadbeef version: 1.8.4
OS: Fedora Linux 32

**Comment by gapf2010** [comment]
> Seems to work as intended. In MP3 Band and Album Artist are different fields, but they're both mapped to %album artist%, in this order: "album artist", "albumartist", "band", "artist", "composer", "performer"

Thanks for the explanation. So from a display point of view they work as intended, however grouping by "Album Artist" does not work as expected. Currently I have grouped albums like this: "%album artist% - %album%" but there are several groups with the same "album artist" and "album" group, but contain tracks only of a single artist. Needless to say, when playing by random "album" only a single group is played, not the whole album. For regular single-artist albums, the random album playing works well.

**Comment by Alexey-Yakovenko** [comment]
In this case, you need to use %artist% instead. It maps to this: "artist", "album artist", "albumartist", "composer", "performer"
(Actually, I think it should also include band, and this seems to be a bug, I'll add a fix)

**Comment by Alexey-Yakovenko** [comment]
Fixed in rev 5bcd39b7e29e8b6347a31734092dda3600e48b27
