### ISSUE TITLE
Play random albums does not work as expected (IMO)

### ISSUE THREAD

**Issue by gapf2010** [DeaDBeeF-Player/deadbeef#2455]
### Steps to reproduce the problem
Configure deadbeef to play random albums (Playback -> Shuffle -> Albums). Stop it if it's playing something currently. Click "play" or right-click the systray icon and choose "play random". It starts playing random songs, not albums. For it to start playing random albums, I have to click "previous track" several times, then it picks the option and it plays random albums well.

### What's going on? Describe the problem in as much detail as possible.
If configured to play random albums, both play button and "play random" should do just that: choose a random album and play it from the first song onwards. If I choose a song manually, then deadbeef should continue playing its album to the end, then choose another random album, play it and so on.

### Information about the software:

Deadbeef version: 1.8.4
OS: Fedora 32

**Comment by Alexey-Yakovenko** [comment]
Play Random action doesn't have anything to do with the current shuffle mode.
It literally just plays a RANDOM track.
It looks like you need to use another action  called "Skip to next album", which should do exactly what you're looking for, and it should be respecting the Shuffle mode.

**Comment by gapf2010** [comment]
Thanks for the explanation on "Play random", however that does not change the fact that the "Play" button still does not seem to work correctly. New bug opened: https://github.com/DeaDBeeF-Player/deadbeef/issues/2468
