### ISSUE TITLE
Need a different equalizer

### ISSUE THREAD

**Issue by MightyPrinny** [DeaDBeeF-Player/deadbeef#2456]
### What's going on? Describe the problem in as much detail as possible.

The current equalizer is a bit weird, I'd like to use presets I use in other music players, I use poweramp on my phone and it uses an equalizer with more standard frequencies (31, 62, 125, 250, 500, 1k, 2k, 4k, 8k, 16k). It would be nice if deadbeef had an alternative equalizer with these frequencies or a customizable one so it can be adjusted to sound like other music players.

### Information about the software:

Deadbeef version: 1.8.4
OS: Mx linux 19

**Comment by dikonov** [comment]
Also see #1921
