### ISSUE TITLE
[macOS] album art shows wrong images

### ISSUE THREAD

**Issue by deseven** [DeaDBeeF-Player/deadbeef#2457]
### Steps to reproduce the problem
1. Enable Album Art column.
2. Load big (1000+ entries) playlist.
3. Scroll down for some time.

### What's going on? Describe the problem in as much detail as possible.
I've updated to the latest nightly just recently and encountered a bug with album arts, when some of them are being replaced by a random image, sometimes on the fly. Restarting deadbeef changes this image to another one, i failed to understand the logic.

I tried resetting album art plugin settings to defaults, but it didn't help. I had no problems with it earlier (except for some minor flickering).  

Video: https://d7.wtf/s/Screen%20Recording%202020-10-08%20at%2002.26.54.mp4

### Information about the software:

Deadbeef version: Version 1.0 (5bcd39b)
OS: macOS 10.15.5

**Comment by Alexey-Yakovenko** [comment]
I was able to reproduce. I think something wrong happens to the tracks which don't have any album cover -- then a "random" album cover may get used, instead of the placeholder image. At least this is what I have observed here.

**Comment by deseven** [comment]
Most of my tracks have a correct album cover (as `cover.jpg` or `folder.jpg` inside each respective directory). I checked those on the video and they all 100% have it.

Anyway, i have something to add - this problem appears only when some music is playing. If i just restart deadbeef without starting playback everything is fine.

**Comment by Alexey-Yakovenko** [comment]
Ok, thanks for the info.

**Comment by tomjepp** [comment]
> I was able to reproduce. I think something wrong happens to the tracks which don't have any album cover -- then a "random" album cover may get used, instead of the placeholder image. At least this is what I have observed here.

I've also been able to reproduce. In my case all tracks have *embedded* album art and loading from local folders is disabled.

**Comment by deseven** [comment]
I updated again, because i saw some album art related commits in master. It got much much worse, now when playback is active deadbeef eats 100% of one core and cover arts keep switching between correct and incorrect ones, like there is internal civil war between two factions :D

Video: https://d7.wtf/s/Screen%20Recording%202020-11-30%20at%2009.23.54.mp4

**Comment by Alexey-Yakovenko** [comment]
out of date, most likely fixed already
