### ISSUE TITLE
'Stop after current track' option should uncheck itself after triggering once

### ISSUE THREAD

**Issue by clayrat** [DeaDBeeF-Player/deadbeef#2459]
### Steps to reproduce the problem

Check the option mentioned in the title, listen to a track, and then manually start another track. The option will stay checked, stopping playback after the second track.

### What's going on? Describe the problem in as much detail as possible.

The usual use-case for this option is the following: let the current track finish, then take a break from listening to music. After this break, one starts listening again, only to have the music stop after the first track, because the flag is still on. `foobar2000` unchecks this option for you automatically in this case.

### Information about the software:

Deadbeef version: 1.8.2
OS: Ubuntu 20.04.1

**Comment by Alexey-Yakovenko** [comment]
In deadbeef, it's a configurable option, look around the Playback tab in Preferences.

**Comment by clayrat** [comment]
Do you think it's reasonable to have that option on by default, btw?

**Comment by Alexey-Yakovenko** [comment]
Sorry, but no. Your use case does not seem to be the most usual / typical, and the more common use case is playing one track at a time using the "play next" button or shortcut, when you need the player to pause after finishing playing each track.
