### ISSUE TITLE
No cover art displayed at notification daemon

### ISSUE THREAD

**Issue by obi-juan88** [DeaDBeeF-Player/deadbeef#2460]
Steps to reproduce the problem

1. Enable shuffle tracks
2. Change song either by pressing "Next" or using next track key keybind

What's going on? Describe the problem in as much detail as possible.

When you enable shuffle tracks and change a track there is a chance cover art wont be displayed on the notification daemon (seems to be random).  This does not happen if you disable shuffle or you manually click on any song in a playlist.

Information about the software:

Deadbeef version: 1.8.4
OS: Debian 10 (Buster)

How did you install the product?

I used gdebi to install the deb package on the website

Please provide any additional information below.

I have tried several notifications daemons from xfce, mate or standalone (dunst)
All my cover arts are correctly displayed on the player itself

![2020-10-13-011359_169x71_scrot](https://user-images.githubusercontent.com/44253536/95822435-86041c00-0cf1-11eb-8984-cddffe4ecb7e.png)
![2020-10-13-011406_258x109_scrot](https://user-images.githubusercontent.com/44253536/95822439-88ff0c80-0cf1-11eb-91c4-7cd8c9d11620.png)

**Comment by gapf2010** [comment]
Same issue happens when using "shuffle albums".

**Comment by Alexey-Yakovenko** [comment]
NOTE to self: the issue is present in any shuffle mode, just more noticeable when shuffle is turned on.
Images would randomly show or not show. Also depends whether album art is displayed in the playlist.
Seems like a timing issue, where album art is not loaded fast enough to be displayed in the notification.

**Comment by Alexey-Yakovenko** [comment]
Seems to work fine starting with 1.9.0-beta5
