### ISSUE TITLE
do not remember previous session when open new song

### ISSUE THREAD

**Issue by maxorbase** [DeaDBeeF-Player/deadbeef#2461]
in many music player new song add to current session In continuation of previous tracks and remember the position of playlist
but in DeaDBeeF when open new song by file manager the song replaced with played song and playlist reset

is DeaDBeeF has configuration for when i open new song added to current playlist and remember of played song?

Deadbeef version: stable 1.8.4.1
OS:kubuntu 20.10

**Comment by Alexey-Yakovenko** [comment]
This is intended behavior.
In Deadbeef, the song is NOT added to current playlist.
It replaces the content of default playlist, which you can also configure.
If you want to append songs to the current playlist -- you may need to configure your file manager to run deadbeef with --queue option.
