### ISSUE TITLE
Some bugs and feature requests

### ISSUE THREAD

**Issue by absolutelynothinghere** [DeaDBeeF-Player/deadbeef#2462]
Hello, long time user of foobar2000 and new user of deadbeef here. Really happy with

### Bugs

1. Opening a file from the file manager wipes the default playlist, the file should append itself to the current playlist or at least provide an option to in settings.
1. Selecting a non-playing track shows its (text) metadata but does not show its album art, it needs to show the album art.
1. Empty playlists are removed upon reboot, they should remain.
1. The following module files do not play in deadbeef, but they play fine in foobar2000 and audacious:
    - https://u.teknik.io/6rZmM.S3M
    - https://u.teknik.io/s8DK8.S3M
    - https://u.teknik.io/nbJ4J.S3M
    - https://u.teknik.io/9CfBi.S3M

### Feature requests

1. Add "enqueue as default action" option, when activated it will make any opened files enqueue to predefined/current playlist rather than play.
1. Add an "undo" action for reverting changes to the playlist (adding/removing a track, sorting a playlist...etc).
1. Add "open containing folder" action, when clicked it would open the file manager and highlight the selected file in its respective folder.
1. Highlight new tracks right after they're added, whether by drag-n-drop or through the file manager.

**Deadbeef version:** 1.8.3
**OS:** Void Linux

**Comment by Alexey-Yakovenko** [comment]
Template not followed, one bug / feature request per issue please.
Also, many/most of the things you wrote have already been reported or requested, so please use search too.

**Comment by absolutelynothinghere** [comment]
@Alexey-Yakovenko  
Ok 👍 I searched through existing issues and here's what I found:

* Bug 1 is reported in #2461, the fix works but should be implemented as an option in the preferences window. This also addresses feature 1.
* Bug 2 is reported in #2121 and not yet fixed.
* Bug 3 is reported in #2257 and marked fixed, but is not fixed on my end. In fact, when I reboot **all** playlists disappear except the default playlist.
* Feature 2 is reported in #490 and not yet implemented.
* Feature 3 is reported in #1610 but doesn't work.

So I'll start new issues for bug 4 and feature 4. Should I start new issues for the rest or just bump the existing issues?

**Comment by Alexey-Yakovenko** [comment]
#2257 is not the same as Bug 3, please report as new bug.

Bug 1: should be more like a feature request to add an option to enqueue new tracks by default

Feature 3: It definitely works / worked last time I tried. If you can't figure out why it doesn't work on your side -- feel free to create a new bug report.

**Comment by Alexey-Yakovenko** [comment]
Bumping existing issues doesn't really help anything most of the time. They are prioritized and being worked on as soon as the time is available.
But if you really feel like it will help your peace of mind -- do it :)

**Comment by absolutelynothinghere** [comment]
Ok thank you 😀
