### ISSUE TITLE
Playlists disappear upon reboot

### ISSUE THREAD

**Issue by absolutelynothinghere** [DeaDBeeF-Player/deadbeef#2465]
### Steps to reproduce the problem

Create multiple playlists aside from the default one, close deadbeef normally and reboot.

### What's going on? Describe the problem in as much detail as possible.

If I create playlists other than the default playlist then reboot, all of them disappear except the default one.

### Information about the software:

Deadbeef version: 1.8.3
OS: Void Linux

**Comment by Alexey-Yakovenko** [comment]
I'm assuming you create the playlist empty? not adding any tracks to them?

**Comment by Alexey-Yakovenko** [comment]
Also you mentioned that you need to reboot the computer. Are you sure it's necessary? Can't you just restart the player?

**Comment by Alexey-Yakovenko** [comment]
Oh I think I'm starting to understand what the problem is. The playlist's would only get saved if you quit, but not when they are created, so if you reboot without quitting -- the files won't be saved at all.

**Comment by absolutelynothinghere** [comment]
> I'm assuming you create the playlist empty? not adding any tracks to them?

No, I checked again. Doesn't matter if the playlists are empty or full, they all disappear.

> Also you mentioned that you need to reboot the computer. Are you sure it's necessary? Can't you just restart the player?

When I restart the player the playlists remain, but when I finally reboot my computer they're gone. I always close the player properly, I never force-kill it. I could restart it a thousand times in the same session and nothing would go wrong.

**Comment by Alexey-Yakovenko** [comment]
Ok, so what you're saying is that:

* You run the player, create playlists, and restart the player -- playlists get saved and loaded just fine.
* After doing the above you restart the computer -- playlists disappear.

Is my understanding correct?

If so, please try the following:

1. Run deadbeef, create playlists, then quit the player, and verify that playlists are saved in ~/.config/deadbeef/playlists. They should be called 0.dbpl, 1.dbpl, 2.dbpl and so on
2. Reboot the computer, and DO NOT run deadbeef yet. Verify whether the playlist files are still there. See if they are readable and writable by the user.
3. Start deadbeef. Verify again whether the playlist files are still there.

**Comment by Alexey-Yakovenko** [comment]
Another thing to try and see if it solves the problem... You didn't specify how you installed deadbeef.
If you're not running [the official build](https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8.4/deadbeef-static_1.8.4-1_x86_64.tar.bz2/download), please give it a try and see if it solves the problem.

**Comment by absolutelynothinghere** [comment]
>Is my understanding correct?

Yes.

>If so, please try the following:

Ok I'll try it and reply back.

>You didn't specify how you installed deadbeef.

I installed it through my distro's repo... I'll try the tarball you linked as well and see what happens.

**Comment by absolutelynothinghere** [comment]
Ok so here are the results:

1. I opened deadbeef, created 2 playlists (aside from default) and closed the program.
1. I checked `~/.config/deadbeef/playlists` and the playlist files were there, however for some reason there was 7 of them (0 to 6).
1. I rebooted, checked the folder again, playlist files still there.
1. I opened deadbeef, all playlists gone except default, but the playlist files are still there.

This applies to both the version I installed from the repo and the version from the tarball.

**Comment by Alexey-Yakovenko** [comment]
This is not the normal behavior. It seems like deadbeef fails to write the configuration. I suggest checking very carefully that all files in the ~/.config/deadbeef are writable by your user.
At this point, it may make sense to delete the whole directory ~/.config/deadbeef, and start over, and see if it helps.

**Comment by absolutelynothinghere** [comment]
All files are readable and writable by me.

> delete the whole directory ~/.config/deadbeef, and start over

That worked, thanks. I think the problem was in the `config` file, it wasn't being updated to reflect the playlists in the `playlists` folder as those were getting saved normally. After deleting the whole folder it's working smoothly now.

**Comment by Alexey-Yakovenko** [comment]
Glad you got it fixed!
