### ISSUE TITLE
Play random albums does not work as expected (again - IMO)

### ISSUE THREAD

**Issue by gapf2010** [DeaDBeeF-Player/deadbeef#2468]
### Steps to reproduce the problem
Configure deadbeef to play random albums (Playback -> Shuffle -> Albums). Stop it if it's playing something currently. Click "play". It starts playing a random song, not the first song of a random album. For it to start playing random album correctly, I have to click "previous track" several times, then it picks the option and it plays random albums well.

### What's going on? Describe the problem in as much detail as possible.
This bug is opened again because the previous one (https://github.com/DeaDBeeF-Player/deadbeef/issues/2455) was closed without addressing the fact that the play button also does not seem to work correctly.

If configured to play random albums, play button should do just that: choose a random album and play it from the first song onwards. If I choose a song manually, then deadbeef should continue playing its album to the end, then choose another random album, play it and so on.

### Information about the software:
Deadbeef version: 1.8.4
OS: Fedora 32

**Comment by Alexey-Yakovenko** [comment]
Ok you didn't really have to open a new one -- you could have commented on the original one.
But whatever, what's done is done.

Regarding your vision how the play button is supposed to function.. It's not quite how it is designed.
When you press play, it ALWAYS, no matter what shuffle mode is selected, should play the track which is currently active.
There's this black or white frame, depending on the color scheme and selection, which is called Cursor, which indicates the current active track.
This track is supposed to play. No randomness there.

If there's no track pointed by the cursor -- nothing will happen. The current playing track will just continue playing, and if nothing is currently playing -- it will stay this way.

The logic which automatically selects next track to play, in accordance with shuffle mode, is coincidentally activated using Next button.

If you still have questions or concerns - please comment into the same issue, no need to create a new one.

**Comment by gapf2010** [comment]
Hmmm. Interesting. Even if unintuitive IMO, if it works as designed, then it's OK with me. Maybe adding more detail in deadbeef's documentation about the specific behavior of the three buttons? (play, play random and next). Anyway, it seems what I'm looking for is indeed the "next" button. Thanks!
