### ISSUE TITLE
Tagging m4a or converting to m4a eats all the RAM (if > 4G)

### ISSUE THREAD

**Issue by JakeSFR** [DeaDBeeF-Player/deadbeef#2474]
Linux x86_64, the latest static, official build (master).

This is kinda weird issue...
To repro: try to change metadata of a m4a file or convert anything to m4a (Nero FAAC).
There's no problem with tagging e.g. mp3s or converting to other formats, AFAICT.

Since the memleak grabs all available RAM (and maxes out CPU) in a matter of seconds and locks up the system, I tried this to limit the RAM used by DB, to see if it actually finishes tagging/converting:

`ulimit -v $((1024*1024))`

But, surprisingly, the problem didn't occur with the above.

Anyway, I have 4G of RAM + 4G of swap + 1G of ZRAM swap, so I disabled both swaps and... no problem with 4G of "pure" RAM only.
Adding 4G of regular or 1G of ZRAM swap makes DB to memleak again.

I tried that again in VBox (btw, Fatdog64-811 is my OS, but tested also with Mint-18.3-mate-64bit) and:
- with 1G of RAM: OK
- adding 1-3G of ZRAM swap: OK
- adding 4G of ZRAM swap: memleak, CPU maxed out, system lockup.

Looks like the problem manifests only if the overall memory > 4G.

![DB_m4a](https://user-images.githubusercontent.com/6226504/98149898-1cc99000-1ece-11eb-9467-98da45fd1e4c.png)

**Comment by Alexey-Yakovenko** [comment]
I found 2 memory leaks, fixed both. Hope it helps.

**Comment by JakeSFR** [comment]
Thanks, but unfortunately there's no improvement at all. :(
Well, I guess you weren't able to reproduce it?

I was trying to use valgrind, but at some point OOM reaper kicks in and kills DB.
The strange thing is that any subsequent use of valgrind doesn't result in the memleak anymore.
Without valgrind it's still there, though.
Some kind of a heisenbug, it seems...

**Comment by Alexey-Yakovenko** [comment]
I don't have a linux machine or a working VM at the moment.
I was running memory leaks checking in the mac version, and I found 2 which occurred during m4a tagging.
It is likely that there are more leaks that weren't detected.
It is also likely that this happens with some m4a files of specific structure, which I don't have.
I'll keep the bug open until I can verify in linux environment.

**Comment by JakeSFR** [comment]
Ok, no worries.
In the meantime attaching a test m4a generated with:
`ffmpeg -f lavfi -i "sine=frequency=1000:duration=5" test.m4a`


[test.m4a.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/5500911/test.m4a.zip)

**Comment by Alexey-Yakovenko** [comment]
Thanks for the file.
I still can't identify any new leaks (on mac), but I will take a look again as I regain access to a linux VM.

**Comment by Alexey-Yakovenko** [comment]
Confirmed the bug. It happens every time on linux. Virtual memory gets to 4GB and can lead to linux killing some processes. This is not normal, will be working on a fix.

**Comment by JakeSFR** [comment]
Alright, confirmed the fix, thanks!
