### ISSUE TITLE
Dark playback controls on a dark theme are not easy to see

### ISSUE THREAD

**Issue by xircon** [DeaDBeeF-Player/deadbeef#2477]
### Steps to reproduce the problem
Apply a dark theme

### What's going on? Describe the problem in as much detail as possible.
Can't see the playback buttons

### Information about the software:
Deadbeef version: Git version from aur
OS: endeavour os

Have searched an searched, tried lots of themes, how do I change the colour of the playback controls?

**Comment by Alexey-Yakovenko** [comment]
Screenshot?

**Comment by xircon** [comment]
![image](https://user-images.githubusercontent.com/1316691/99185812-2b247100-2744-11eb-9307-43afd98e87a8.png)

**Comment by xircon** [comment]
It looks better in the screenshot than it does on plasma :D

**Comment by Alexey-Yakovenko** [comment]
I don't think this is fixable on our side, this is just a shitty gtk theme. Pick another one, and select an icon theme which works well with it.

**Comment by xircon** [comment]
Are the controls hard coded?

**Comment by xircon** [comment]
It looks a lot worse in flat-remix:

![image](https://user-images.githubusercontent.com/1316691/99185965-0086e800-2745-11eb-9f91-416894c58a74.png)

**Comment by Alexey-Yakovenko** [comment]
The icon colors are defined by icon theme, they're not custom, you need a somewhat light(er) icon theme.

**Comment by xircon** [comment]
Thanks, understand, will find another icon theme.

**Comment by saivert** [comment]
Deadbeef uses standard icon names like: gtk-media-play, gtk-media-pause, etc. I suspect your theme misses these icons or replaces them with some icons that don't work well against dark background. The ones provided by Gnome are white icons with a dark shaded outline so should be visible against any background really. Look in your `/usr/share/icons/gnome/32x32/actions` directory.

These days one are supposed to use the newer `media-playback-start-symbolic`, etc. icon names and use the `gtk_image_new_from_icon_name()` API. The symbolic ones automatically fit themes better and I'm sure the theme authors are more aware of them than the older GTK+ stock icons.

If wanted I can make a PR to fix this when built against a sufficiently new GTK+ (3.10 according to docs).
