### ISSUE TITLE
[Feature Request] Add new API event to notify playback stop

### ISSUE THREAD

**Issue by SkyMaverick** [DeaDBeeF-Player/deadbeef#2479]
In a third-party plugin, it is impossible to reliably catch the "playlist ended, nothing is playing" state. How to act in such a situation?
Is it possible to add a new message to the API (DB_EV_STOPABLE for example)?

**Comment by kuba160** [comment]
I checked my ddb_discord_presence plugin. It uses 2 events to detect playback stop:
* `DB_EV_STOP` - playback stopped manually
* `DB_EV_SONGCHANGED` with `ctx->to = NULL` - playback ended as playlist ended or `Stop after current track/album` option stopped the playback.

**Comment by SkyMaverick** [comment]
I used DB_EV_SONGFINISHED in [my plugin](https://github.com/SkyMaverick/deadbeef-statusnotifier-plugin) (patched original for work in GNOME) but it looks like a bad idea. Your code looks definitely better. Thanks.
