### ISSUE TITLE
Window position don't save in Wayland session

### ISSUE THREAD

**Issue by SkyMaverick** [DeaDBeeF-Player/deadbeef#2481]
### Steps to reproduce the problem
DB window is located on the right half of the screen. After restarting DB returns the window to its previous position in Xorg-session, but in Wayland-session it returns fail position (0,0) and save this in config.
### What's going on? Describe the problem in as much detail as possible.
After minimize DB returns the window to its previous position in Wayland-session, but if I use StatusNotifier ([my patched verion](https://github.com/SkyMaverick/deadbeef-statusnotifier-plugin))  it returns fail position (0,0), what read in config (Xorg-session and other Xorg DE all works correct).
### Information about the software:
Deadbeef version: DeadBeeF 1.8.4 (official *.deb package)
OS: Ubuntu 20.04.1 (GNOME 3.36.3)

**Comment by Alexey-Yakovenko** [comment]
Doesn't sound like deadbeef problem. Have you tried any other GTK applications and see if they show the same issue?
~10 years ago when I was implementing that feature, I was using source code of Gaim (instant messenger, now called Pidgin) as a reference. Would be great if you could try it.

**Comment by saivert** [comment]
This is a limitation of Wayland. The compositor needs to support this feature. Only the window dimensions can be suggested by the application when creating the window but the compositor can ignore this.

**Comment by Alexey-Yakovenko** [comment]
Thanks, that's what I thought.
