### ISSUE TITLE
Playlist items invisible upon DB start

### ISSUE THREAD

**Issue by JakeSFR** [DeaDBeeF-Player/deadbeef#2484]
Linux x86_64, latest static build.

When DB starts, almost always none of the items in the current playlist are visible.
To make them visible some event is needed, like scrolling, clicking, losing focus, etc.

Looks like it's a GTK2-UI issue, can't repro it with GTK3.

The behaviour also seems to be co-dependent on CPU load.
The more load I produce (by simple `cat /dev/zero > /dev/null`), the lesser probabilty of the bug.
On my i3 (2 cores, 4 threads) it's enough to run 3 instances of the above in order to make the playlist visible practically every time DB starts.

I suspect one of these could've introduced the issue: https://github.com/DeaDBeeF-Player/deadbeef/commit/e25886a0ce28a41e0bdd23ca710307a3312c7276 https://github.com/DeaDBeeF-Player/deadbeef/commit/76027db8f2a67c3c167cd2eef2b60efc82734ee0

Anyway, I wasn't able to reproduce it in Mint, Ubuntu, Antix in VBox this time, though.
My guess is that when DB starts in such an environment, there's enough CPU load for the issue to not manifest.
Maybe it would work if my CPU had more than 4 threads and I could assing to VBox at least 4 of them.

But I can reproduce it in Fatdog64-811 both on real HW as well as VBox.
In the latter case, if I assign only 1 CPU thread to VBox, the bug rarely happens. If I assign 2 threads, it happens in ~30% of cases.
Also managed to repro it (VBox) in BionicPup64-8.0 and a couple of times in Porteus-OPENBOX-v4.0-x86_64.
I think distros like these are simply too lightweight in comparison to the other mentioned, "big" distros, so it's way easier for the bug to show up.

![out_2020-11-28_153905](https://user-images.githubusercontent.com/6226504/100518342-368a8a00-3191-11eb-8cee-cfb9de40dc40.gif)

**Comment by Alexey-Yakovenko** [comment]
Thanks for reporting in! It is indeed very likely that those commits caused this. I need to add one extra redraw call after the view size configuration settles down.

**Comment by JakeSFR** [comment]
Works now, thanks!
