### ISSUE TITLE
Permission denied /mnt when installed from official OS distro store

### ISSUE THREAD

**Issue by marbaa** [DeaDBeeF-Player/deadbeef#2491]
### Steps to reproduce the problem
Install deadbeef from official application explorer Discover 5.20.4

### What's going on? Describe the problem in as much detail as possible.
Cannot acces /mnt folder via File -> Add folder(s). Even if /mnt has 777 set.
![deadbeef_mnt](https://user-images.githubusercontent.com/40859847/101903573-c62e3080-3bb4-11eb-9edf-1643e28bd9c2.png)

However if I download the player from Sourceforge which is version 1.8.4, then opening /mnt works with standard 755 permissions.

### Information about the software:

Deadbeef version: 1.8.2
OS: Neon 20.04 KDE 5.20

**Comment by Alexey-Yakovenko** [comment]
Sorry, but I can't support unofficial 3rd party builds. You should contact the people who created the build instead.
