### ISSUE TITLE
[Linux / Fedora][DeadBeeF 1.8.4] Local file mask not respected for album art

### ISSUE THREAD

**Issue by pihug12** [DeaDBeeF-Player/deadbeef#2494]
### Steps to reproduce the problem

When I play a file where there should be no artwork, DeaDBeeF picks a random JPG file in the same folder.

The pattern is set to: `*cover*.jpg;*front*.jpg;*folder*.jpg;*cover*.png;*front*.png;*folder*.png`

The file name of the pictures picked don't respect this mask (`mpv-shot0002.jpg`, `62423173-7736d800-b6f0-11e9-9ddd-e48832259695.jpg`).

### Information about the software:

DeadBeeF version: 1.8.4
OS: Fedora 32

**Comment by kuba160** [comment]
I think the issue is present on Windows aswell, had some tracks in Downloads folder and it picked some pictures I had (1st one alphabetically I think). Thought at first that it was Windows only problem, maybe some regression happened when it was ported to Windows.
