### ISSUE TITLE
How do I change the interface language?

### ISSUE THREAD

**Issue by bamper45** [DeaDBeeF-Player/deadbeef#2495]
### Steps to reproduce the problem 
Open
### What's going on? Describe the problem in as much detail as possible.
How do I change the interface language?

### Information about the software:

Deadbeef version: deadbeef-2020-07-06
OS: Win 10

**Comment by kuba160** [comment]
It should automatically choose system language. It is possible that deadbeef is not translated into language you want (check https://www.transifex.com/deadbeef-player/deadbeef-player/languages/). Also update your deadbeef in case you have some other issues (https://sourceforge.net/projects/deadbeef/files/travis/windows/master/)

**Comment by saivert** [comment]
you can override the language with `LANG=sv_SE deadbeef` on command line. Basically override the environment variable to let it pick a different language.

**Comment by Alexey-Yakovenko** [comment]
Closing, since it seems the question has been answered?

**Comment by Kissaki** [comment]
> It should automatically choose system language.

I suspect it chooses by region or number and date formatting instead of Windows display language.

I'm using EN Windows display language, yet DeaDBeeF renders in DE. Not having a workaround through a setting is really unfortunate - and a deal breaker for me.

**Comment by Kissaki** [comment]
I guess I'll create a bug ticket for respecting display language.
