### ISSUE TITLE
File converter doesnt work anymore (Deadbeef 1.8.5-1)

### ISSUE THREAD

**Issue by obi-juan88** [DeaDBeeF-Player/deadbeef#2499]
### Steps to reproduce the problem

Try to convert any file. In my case I tried to convert a Flac file into a opus one.

### What's going on? Describe the problem in as much detail as possible.

When you try to convert any file and gui shows up, you cannot pick which encoder to use (that option is greyed out so you cannot pick one). I could not find any relevant info on my log but i'll attach it anyway.

### Information about the software:

Deadbeef version: Deadbeef 1.8.5-1
OS: Debian 10 Buster

![Captura de pantalla -2021-01-13 23-28-30](https://user-images.githubusercontent.com/44253536/104549204-fb84ce80-55f7-11eb-8b4c-30c51ab000b0.png)

[Log.txt](https://github.com/DeaDBeeF-Player/deadbeef/files/5812501/Log.txt)

**Comment by Alexey-Yakovenko** [comment]
This is bad.. it's not just a package problem, but also present in local builds.. Will have to make a new release. Should not take much time though.

**Comment by Alexey-Yakovenko** [comment]
Should be fixed in 1.8.6-rc1, waiting for the builds.

**Comment by Alexey-Yakovenko** [comment]
https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8/

**Comment by obi-juan88** [comment]
I can confirm this new build does indeed work. 
So far i tested converting a Wav file to Flac, Opus, Mp3 and Ogg succesfully.
If i run any issues i'll let you know. 
Thanks you.
