### ISSUE TITLE
Album sort order with CJK

### ISSUE THREAD

**Issue by Shinkirou** [DeaDBeeF-Player/deadbeef#2501]
Tested in the latest deadbeef 1.8.5, running on Linux Mint 20.1. My OS region is Portugal and the language is English US.

When sorting albums using %album%, the sorting order is displayed incorrectly in some cases. In particular, when some albums (in particular using CJK characters) partially share the same name, with just a different termination.

For instance, with these three album names:

新世紀エヴァンゲリオン II
新世紀エヴァンゲリオン III
新世紀エヴァンゲリオン

The order appears as above, instead of the expected behaviour, in which the last line would appear first, like so:

新世紀エヴァンゲリオン
新世紀エヴァンゲリオン II
新世紀エヴァンゲリオン III

I believe that the sort function considers the latin script characters first, and only then looks at the CJK characters. I tested changing the III characters in the III album to 3 and the order became:

新世紀エヴァンゲリオン 3
新世紀エヴァンゲリオン II
新世紀エヴァンゲリオン

This sorting behaviour does not happen if the albums use only latin script. In that case, the sorting happens as expected.

**Comment by Alexey-Yakovenko** [comment]
Are you sure that you are actually using **sorting**? Can you describe specific steps that you do to apply the sorting to playlist?

**Comment by Shinkirou** [comment]
Thank you for the quick reply.

I should have specified: this is using custom sort (sort by -> custom). The complete format is: 

%album% %album artist% %discnumber% $num(%track number%,4)

Additionally, the playlist is grouped using a custom format, but I don't see how that would influence the album order. The grouping is:

%album% ||| \[%date%\] %album artist% ||| Disc %discnumber%

**Comment by Alexey-Yakovenko** [comment]
when you specify `%album% %album artist%` -- are you sure this would not get expanded to double the album name?
The sorting strings then would then look like this:

```
新世紀エヴァンゲリオン II新世紀エヴァンゲリオン II
新世紀エヴァンゲリオン III新世紀エヴァンゲリオン III
新世紀エヴァンゲリオン新世紀エヴァンゲリオン
```

In which case, it kind of makes sense?

**Comment by Alexey-Yakovenko** [comment]
oh sorry, what I wrote above is wrong, I confused album and artist when writing.
Although this would still be a reason why it sorts this way.

The question still stands: does the problem persist if you sort using just %album% though?

**Comment by Shinkirou** [comment]
Ah, I see. Removing %album artist% from the custom sort format above indeed fixes the problem.

However, I have a couple of unrelated albums which happen to share the same name, and since I removed %album artist% are now mixed. I suppose I could fix this through the grouping format by changing the place where %album artist% appears. Just to check, is there another way to sort the albums which avoids this mix?

**Comment by Alexey-Yakovenko** [comment]
I guess you just need to add separators beetween items, like so:

`%album% - %album artist% - %discnumber% - $num(%track number%,4)`

**Comment by Shinkirou** [comment]
I didn't know about those separators. The sorting is perfect now. Thanks for the help!

**Comment by Alexey-Yakovenko** [comment]
great! was happy to help.
