### ISSUE TITLE
Please update to version 1.8.6 or 1.8.5 (regression)

### ISSUE THREAD

**Issue by AngryPhantom** [DeaDBeeF-Player/deadbeef#2506]
Please update the player to version 1.8.6 or at least 1.8.5 since there is a regression that got fixed (some mp3 files were playing only 5 sec of audio and then stopped). Anyway, the latest release is 1.8.6. So, it would be really nice to have it in the repo.

Unfortunately, I'm not an expert in xbps-src, otherwise I'd posted a pull request. I tried compiling the latest version but I'm getting errors and don't know how to fix them. Probably because it needs clang or some other new dependency, I'm not sure.

I'm using a "half-baked" 1.8.4 version of it (1.8.3 from repo + author's patch/fix). That was the last one that I managed to compile myself without issues.

Thank you in advance. Cheers.

**Comment by Alexey-Yakovenko** [comment]
I don't know what you're writing about, but it looks like you are writing to the wrong people / wrong website.

**Comment by AngryPhantom** [comment]
Oh, my gosh. I'm really sorry, I've posted this in the wrong github.
Cheers!
