### ISSUE TITLE
deafbeef src archive doesn't include the new external dependencies

### ISSUE THREAD

**Issue by stefson** [DeaDBeeF-Player/deadbeef#2507]
hey, I'm getting this error, and it seems to be about missing source folder in the src code archives, namely mp4p folder is blank: 

```
>>> Source configured.
>>> Compiling source in /var/tmp/portage/media-sound/deadbeef-1.8.6/work/deadbeef-1.8.6 ...
make -j12 
make  all-recursive
make[1]: Entering directory '/var/tmp/portage/media-sound/deadbeef-1.8.6/work/deadbeef-1.8.6'
Making all in pixmaps
make[2]: Entering directory '/var/tmp/portage/media-sound/deadbeef-1.8.6/work/deadbeef-1.8.6/pixmaps'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/var/tmp/portage/media-sound/deadbeef-1.8.6/work/deadbeef-1.8.6/pixmaps'
Making all in icons
make[2]: Entering directory '/var/tmp/portage/media-sound/deadbeef-1.8.6/work/deadbeef-1.8.6/icons'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/var/tmp/portage/media-sound/deadbeef-1.8.6/work/deadbeef-1.8.6/icons'
Making all in external
make[2]: Entering directory '/var/tmp/portage/media-sound/deadbeef-1.8.6/work/deadbeef-1.8.6/external'
make[2]: *** No rule to make target 'mp4p/src/mp4p.c', needed by 'mp4p/src/libmp4p_a-mp4p.o'.  Stop.
make[2]: Leaving directory '/var/tmp/portage/media-sound/deadbeef-1.8.6/work/deadbeef-1.8.6/external'
make[1]: *** [Makefile:787: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/media-sound/deadbeef-1.8.6/work/deadbeef-1.8.6'
make: *** [Makefile:575: all] Error 2
 * ERROR: media-sound/deadbeef-1.8.6::gentoo-extras failed (compile phase):
 *   emake failed
```

can you please allow mp4p folder to be included? thanks
happens on linux x86_64 if it matters

**Comment by Alexey-Yakovenko** [comment]
I downloaded the 1.8.6 source tarball, and it contains the mp4p folder.
Are you sure that you are downloading the correct file?

![image](https://user-images.githubusercontent.com/1895698/105642756-f6dbd800-5e8b-11eb-80e8-880d0aaea41b.png)

**Comment by stefson** [comment]
I downloaded via the tagged src archive from: https://github.com/DeaDBeeF-Player/deadbeef/archive/1.8.6.tar.gz ; what is the alternative url with the mp4p external included please?

**Comment by Alexey-Yakovenko** [comment]
The file you downloaded is a git snapshot, which doesn't include submodules.
It's autogenerated by github, and is completely useless. I'll try to remove / disable those files, to prevent further confusion, although I'm not sure whether this is possible.

You can find the source tarball link at the deadbeef website, in the download section:
https://deadbeef.sourceforge.io/download.html

**Comment by Alexey-Yakovenko** [comment]
@stefson Unfortunately, there doesn't seem to be any way to disable or hide those links with incomplete git archives. So.. Just don't use them :)

**Comment by stefson** [comment]
hey, that's okay, I just switch to sourceforge url for my build script

**Comment by stefson** [comment]
@Alexey-Yakovenko it was a bit of a nightmare to inject the mp4p source code into the git checkout today. Is there a specific configure switch that triggers it, or is it impossible to not pull it in?

**Comment by Alexey-Yakovenko** [comment]
@stefson 
> it was a bit of a nightmare to inject the mp4p source code into the git checkout today. Is there a specific configure switch that triggers it, or is it impossible to not pull it in?

I'm sorry, but I don't understand what you mean by this. What are you trying to inject and where?
mp4p is a submodule, and is a required dependency for AAC, ALAC, Album art, and more
