### ISSUE TITLE
Audio Screeching with ALSA Output

### ISSUE THREAD

**Issue by TheTerrior** [DeaDBeeF-Player/deadbeef#2512]
### Steps to reproduce the problem
Set playback to ALSA Direct hardware device without any conversions, and open a flac file.

### What's going on? Describe the problem in as much detail as possible.
The audio will usually be sped up, with a horrible screeching sound much louder than the music itself. After playing a flac and having this issue, other file types may sometimes experience the same thing if played right after (including mp3 or wav). After I stop playback and hit play again, the issue usually stops until I play a different file. This issue happens with most ALSA options, but does not happen with ALSA Default Audio Device. I've also tried messing with different ALSA plugin options, SRC options, and Override samplerate (I assumed it was a samplerate issue since the audio was sped up when the screeching happened). This issue does not happen with other music players.

### Information about the software:

Deadbeef version: 1.8.6
OS: Linux Mint 20.1

**Comment by Alexey-Yakovenko** [comment]
Could you please check if the build from master branch still has the same issue?
I applied a change to ALSA plugin that may help in theory, but currently can't verify.
Although I'll try reproducing at some point next week.

**Comment by Alexey-Yakovenko** [comment]
https://sourceforge.net/projects/deadbeef/files/travis/linux/master/

**Comment by TheTerrior** [comment]
Yes, it's happening exactly the same.

**Comment by Alexey-Yakovenko** [comment]
I tried to reproduce this, and it's not happening. What I did:

- ALSA plugin.
- Pulseaudio is stopped / autospawn disabled.
- Output is configured to use "Direct hardware device without any conversions".
- Resampler is disabled.
- Multiple files in various formats, with 22, 32, 44, 96 and 92 KHz sampling rate, and 16 and 24 bits per sample.
- I was playing all those files in varying order, and everything has worked as designed, without any problems.

There's not much else I can do so I'm closing this issue.
Please feel free to provide any additional details if you think they may help to reproduce the issue.
