### ISSUE TITLE
[DeaDBeef 1.8.6] Compilation error with gcc 10.2.0 (gcc: error: unrecognized command-line option '-fblocks')

### ISSUE THREAD

**Issue by Drag0nFly** [DeaDBeeF-Player/deadbeef#2516]
### Steps to reproduce the problem
Compile latest DeaDBeef with an up-to-date compiler. 

### What's going on? Describe the problem in as much detail as possible.
Somehow it incorrectly thinks the GNU compiler has "fblocks" support. I've tried manually disabling this in CFLAGS and build scripts, but to no avail. The toolchain is up-to-date (on a rolling Arch-based distro), and has no issues building numerous other packages from source.

Last part of error message:

make[2]: Leaving directory '/home/martin/asp/deadbeef/src/deadbeef-1.8.6/plugins/gme'
Making all in plugins/pulse
make[2]: Entering directory '/home/martin/asp/deadbeef/src/deadbeef-1.8.6/plugins/pulse'
  CC       pulse.lo
  CCLD     pulse.la
make[2]: Leaving directory '/home/martin/asp/deadbeef/src/deadbeef-1.8.6/plugins/pulse'
Making all in plugins/notify
make[2]: Entering directory '/home/martin/asp/deadbeef/src/deadbeef-1.8.6/plugins/notify'
  CC       notify_la-notify.lo
gcc: error: unrecognized command-line option '-fblocks'
make[2]: *** [Makefile:553: notify_la-notify.lo] Error 1
make[2]: Leaving directory '/home/martin/asp/deadbeef/src/deadbeef-1.8.6/plugins/notify'
make[1]: *** [Makefile:825: all-recursive] Error 1
make[1]: Leaving directory '/home/martin/asp/deadbeef/src/deadbeef-1.8.6'
make: *** [Makefile:610: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

### Information about the software:

Deadbeef version: 1.8.6
OS: ArchLinux-based (Parabola Linux libre rolling)

**Comment by Alexey-Yakovenko** [comment]
Starting with deadbeef-1.8.5 GCC is not supported.

**Comment by Drag0nFly** [comment]
Wait, what? An audio player for Linux which does not support GCC? On what basis was this decision made?

**Comment by Alexey-Yakovenko** [comment]
It's not a player just for Linux. It supports multiple platforms, including Windows and Mac.
Actually, most of the time it's being developed on Mac and Windows.
It is primarily developed using Clang, and we had to avoid using certain nice features just to stay compatible with GCC.
After some discussions, we verified that Clang supports all platforms which we need, and that it benefits code quality, and we decided to go with it.

**Comment by ngleb** [comment]
This could be a stupid question, but is clang required for plugins as well if it was used for compiling deadbeef itself? I installed libdispatch and could build deadbeef with clang and it is working, but I'm not sure what to do about plugins.

**Comment by Alexey-Yakovenko** [comment]
@ngleb plugins don't have to be built using clang.

**Comment by socketpair** [comment]
https://github.com/darlinghq/darling/issues/535#issuecomment-512968345
