### ISSUE TITLE
OSD Notify show track length

### ISSUE THREAD

**Issue by elig0n** [DeaDBeeF-Player/deadbeef#2517]
I am trying to display current track length on OSD Notify notification but %L from https://github.com/DeaDBeeF-Player/deadbeef/wiki/Title-formatting is not working neither in title nor content format. Some explanation would help.

Deadbeef version: 1.8.4
OSD Notify version: 1.0

**Comment by Alexey-Yakovenko** [comment]
You should be using title formatting 2.0 wiki page instead.
I just deleted the old one from table of contents.
What you are looking for is probably `%length%`
