### ISSUE TITLE
DeaDBeeF not recognizing many songs

### ISSUE THREAD

**Issue by Orangian** [DeaDBeeF-Player/deadbeef#2518]
### Steps to reproduce the problem
Install DeaDBeeF from the Manjaro Repositories
Add Music Folder
### What's going on? Describe the problem in as much detail as possible.
I have a music library with ~2500 songs, however, DeaDBeeF only recognizes ~1500 songs. AIMP on Windows recognizes them all fine, so I am not sure what the issue is. Is there a way to try to find if it isn't recognizing certain audio formats? This is too extensive to try to pin down exactly what isn't being recognized. Here is a list of all file formats within it:
AIFF
FLAC
M4A
MP3
OGG
OPUS
WAV
### Information about the software: Installed from the official Manjaro repositories

Deadbeef version: 1.8.4
OS: Manjaro Gnome (Fully up to date)

**Comment by Alexey-Yakovenko** [comment]
Have you tried one of the official builds? From deadbeef website?

**Comment by Orangian** [comment]
I'll try to install one of those now.

**Comment by Orangian** [comment]
I attempted to add my music folder again, and it threw many errors related to my OPUS files. Would you like me to upload one of them? [The log is here.](https://pastebin.com/Yszdck0a)

**Comment by Alexey-Yakovenko** [comment]
Sure.. please use email if possible: waker@users.sf.net

**Comment by Orangian** [comment]
Email has been sent. Thanks for the quick help! Oddly enough, the log only has about 37 songs error out though. The rest just don't seem to pop up. By using a command to count the number of every files, I came to this conclusion:
     33 .aiff
    415 .flac
      4 .ini
    102 .jpg
     93 .m4a
      1 .mid
    782 .mp3
    120 .ogg
    647 .opus
     73 .png
     79 .wav
The aiff, flac, m4a, mp3, ogg, opus, and wav files added up total to 2169 songs. Since 37 OPUS files errored out in the log, this means that 2132 songs should appear in the actual player, however, it only detects 2115 songs, meaning that it isn't finding 17 songs but isn't erroring out any in the log. Thanks for any help you can provide!

**Comment by Alexey-Yakovenko** [comment]
Thanks, will take a look as soon as i can

**Comment by Alexey-Yakovenko** [comment]
The wile you sent to me is not a normal opus file, it's a webm file, renamed to .opus file extension.
This is not supported by deadbeef.
