### ISSUE TITLE
I miss the option 'Disable disk cache'

### ISSUE THREAD

**Issue by Skabit** [DeaDBeeF-Player/deadbeef#2521]
DeadBeef is awesome but I like have a simple configuration and load one or two music albums per session. So I will have problems with lag issues when to load album art, and I found really unnecessary save album art cache. In my cache folder (~/.cache/deadbeef) I have many subfolders with a lot images even repeated when the album has multiple authors.

Look out in the deadbeef code I have the next lines, on the file [plugins.c](https://github.com/DeaDBeeF-Player/deadbeef/blob/5bcd39b7e29e8b6347a31734092dda3600e48b27/translation/plugins.c)

```
// xgettext:no-c-format
_("Disable disk cache");
 
```
But I can't find that option in the plugin preferences. Where is that option? 

Deadbeef version: 1.8.6
OS: Ubuntu 20.04

**Comment by Alexey-Yakovenko** [comment]
This option is present in the "new" album art plugin, which is not yet available for Linux. It was originally made for android, and currently is only used in the macOS version. The long term plan is to fully transition to this new plugin on all platforms, but it still has some unimplemented features and serious bugs compared to the linux version, so there's still a lot of work to do before this happens.
