### ISSUE TITLE
Xcodebuild requires Xcode

### ISSUE THREAD

**Issue by essentialols** [DeaDBeeF-Player/deadbeef#2523]
### Steps to reproduce the problem

I installed xcode command line tools using ```sudo xcode-select --install```. Then I run ```xcodebuild -project osx/deadbeef.xcodeproj -target DeaDBeeF -configuration Release```.

### What's going on? Describe the problem in as much detail as possible.

I get the error message ```xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance```.

### Information about the software:

Deadbeef version: 1.8.4
OS: Mac OS 11.1

**Comment by Alexey-Yakovenko** [comment]
I think the message is clear enough -- it tells that you need to install Xcode.

**Comment by essentialols** [comment]
The full environment? So the command line tools are not enough?

**Comment by Alexey-Yakovenko** [comment]
I'm not familiar with the command line tools, never used them, sorry.
