### ISSUE TITLE
intltoolize not found when building from source

### ISSUE THREAD

**Issue by TheTerrior** [DeaDBeeF-Player/deadbeef#2524]
### Steps to reproduce the problem
During compilation of DeaDBeeF, after cloning from GitHub.

### What's going on? Describe the problem in as much detail as possible.
I'm following the instructions to compile from source, after having cloned the GitHub code. I updated the submodules, but when I typed './autogen.sh', I got the error message "./autogen.sh: 8: intltoolize: not found".

### Information about the software:

OS: Linux Mint 20.1

**Comment by saivert** [comment]
Make sure package `intltool` is installed.

Read: https://github.com/DeaDBeeF-Player/deadbeef/blob/master/README

**Comment by TheTerrior** [comment]
Sorry if I'm bothering, I'm just new to compiling from source and all that, and I'm getting issues I'm not sure how to resolve. I installed all the prerequesites, but after running either "./configure --prefix=/usr" or "CC=clang CXX=clang++ ./configure" (they both result in the same thing), I get this:

./configure: line 21139: syntax error near unexpected token 'ZIP,'
./configure: line 21139  `      PKG_CHECK_MODULES(ZIP, libzip, HAVE_ZIP=yes, HAVE_ZIP=no)

**Comment by kuba160** [comment]
Check if you have pkg-config installed (#2067), @Alexey-Yakovenko maybe it would be nice to have more meaningful error message? Also it looks like pkg-config is missing in dependency list in [README](https://github.com/DeaDBeeF-Player/deadbeef/blob/master/README).

**Comment by TheTerrior** [comment]
It seems as though I have it installed, version 0.29.1-0ubuntu4.
