### ISSUE TITLE
Skip Deleted Tracks no longer works properly

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2525]
### Steps to reproduce the problem
[Recent changes](https://github.com/DeaDBeeF-Player/deadbeef/issues/2432) to the "Delete from disk" function have affected the "Skip Deleted Tracks" functionality. It still plays another song after deletion of the current one but this no longer works properly in the case of SHUFFLE_OFF. Instead of playing the next song in the playlist, it always plays the first one in the playlist. 

### Information about the software:

Deadbeef version: 1.8.6 (from Git c4b175db780d38fba6d6334028f521fac54ba53e)
OS: Arch Linux

**Comment by Alexey-Yakovenko** [comment]
None of those changes are part of the 1.8 branch, so I'm guessing you're not really using 1.8.6?

**Comment by kpcee** [comment]
The log window says "version 1.8.6", but I'm compiled the above mentioned Git version right after the new 1.8.6 was released.

**Comment by Alexey-Yakovenko** [comment]
1.8.6 lives on another branch, where this revision doesn't exist.

what you built is on master branch, which is not 1.8.x

**Comment by kpcee** [comment]
Okay, then the described problem concerns only the master branch and not the current final version.

**Comment by kpcee** [comment]
Just tested and works great, thanks.

**Comment by kpcee** [comment]
I compiled the latest git version 6757aac404e7bd7100ee41179ab2cb166123f7c6 and the described error still exists. If you use the context menu → "Remove Form Disk" it works as it should. However, if you use a shortcut, DeaDBeeF always jumps to the top of the list instead of playing the next piece. 

To test:
Shuffle → Off
Repeat → All Tracks
Shortcut → Remove From Disk, Selection (from my config file `hotkey.key30 "Ctrl Delete" 1 0 delete_from_disk`)

**Comment by Alexey-Yakovenko** [comment]
@kpcee could you please post this as a new issue?

**Comment by kpcee** [comment]
Okay done: https://github.com/DeaDBeeF-Player/deadbeef/issues/2594
