### ISSUE TITLE
Not showing Album Arts 

### ISSUE THREAD

**Issue by NevGi-cpu** [DeaDBeeF-Player/deadbeef#2528]
### Steps to reproduce the problem
Download and add a folder and when i add a album art section it doesnt display most of the songs album art. It shows the album arts of few songs from my collection.

### What's going on? Describe the problem in as much detail as possible. 
I download music from music platforms and autotag it using "AutomaTag" using anroid. Which fill the metadata and also download's the songs album cover and saves it. VLC, MusicBee,ec shows those album arts for all my songs. But Deadbeef doesn't show those same album art for most of my songs

### Information about the software:
I would also like to request a dark mode for deadbeef.
Deadbeef version:1.8.7
OS:windows 10 latest as of 12/02/2021

**Comment by Alexey-Yakovenko** [comment]
It's stated as a known issue right next to the windows download link :) Artwork plugin is not included in the windows build (yet).

**Comment by kuba160** [comment]
For dark theme there is a workaround, see [DeaDBeeF-for-Windows/#8](https://github.com/DeaDBeeF-for-Windows/deadbeef/issues/8#issuecomment-500205814). Shortly said: on Linux theme is handled by the system, and on Windows there is no such thing. DeaDBeeF would need to implement theme overriding similar to GIMP for example, but nobody is working on it now.

Artwork is included in windows build, but it is not considered fully functional. I tested DeaDBeeF 1.8.7 with different cover arts now and all of them worked fine. Is it possible that other players show coverart from an internet service like lastfm? (which deadbeef also supports, you just need to enable it in settings)
