### ISSUE TITLE
(feature) improve plugins section

### ISSUE THREAD

**Issue by ghost** [DeaDBeeF-Player/deadbeef#2529]
here is a few ideas to improve the plugins section:

* make plugins sortable via columns: **title - version - date - preferences**

when sorting by preferences, this could also be represented by a clickable symbol (for quick access) in two different colours:

blank - no settings avaiable
grey - standard
orange - modified

* display default plugins in a colour different to manually installed plugins

* button to export detailed informations on installed plugins to textfile

* button to reset all settings to default values

* button to export/import manual installed plugins

**Comment by saivert** [comment]
@dmidecodes some questions:

First of all: New plugin preference UI is in the works. It will implement reset to defaults per plugin (not for all plugins at once however).

I'm okay with some kind of indicator of modified configuration. But it will require reworking how plugin configuration is tracked. Need to think about this.

What do you mean by button to export/import manually installed plugins? Is it copying the actual plugin files to somewhere?

Manually installed plugins should generally be installed in $HOME/.local/lib64/deadbeef for 64 bit systems. So they are already contained somewhere.

Hardcoding a list of plugins that are shipped with DeaDBeeF is easy enough though.

What do you mean by button to export list of plugins? Is this something you intend for as a troubleshooting tool? The log spam on DeaDBeeF startup already lists plugins loaded. And what kind of information are you interested in here other than name and version?

**Comment by dmidecodes** [comment]
> First of all: New plugin preference UI is in the works. It will implement reset to defaults per plugin (not for all plugins at once however).

this is actually what i was thinking of - but a global reset-button could perhaps also be helpful under certain conditions?

> What do you mean by button to export/import manually installed plugins? Is it copying the actual plugin files to somewhere?

yes, something in that direction. initially, i was thinking about zipping and exporting all manually "installed" plugins as one file for a quick and user-friendly re-import (in case of an os re-install, for instance).

i quite like the idea of consolidating and compacting things in one place. in this case, appimages comes to my mind, which is probably the preferred method and way to go?

> Manually installed plugins should generally be installed in $HOME/.local/lib64/deadbeef for 64 bit systems. So they are already contained somewhere.

good you mention that, i will revert to lib64, now. i was a bit confused about the correct place, see: https://deadbeef.sourceforge.io/plugins.html

> What do you mean by button to export list of plugins?

yes, it was meant to be for troubleshooting reasons only and should contain plugin-name, quick info, version, date. will a 32/64bit information make sense here?

**Comment by saivert** [comment]
@dmidecodes  If you run nightlies or build from source you can try out some of the changes now. I have a PR for a new context menu on the plugin list which now has a Copy report menu item which copies a list of the plugins to the clipboard. This may not be as discoverable as one like but context menus are used a lot and people should expect them.

**Comment by dmidecodes** [comment]
thanks for letting me know.

i gave the nightly build a test-run and i like the new appearance with the 3 buttons on top + on the same level as the title. i think this has a positive effect on clarity, although i still would prefer a sortable columns view, if possible?

right now, the plugins are mixed up in non-alphabetical order, which makes it difficult to find a certain one immediately.

besides, finding out which plugin offers further settings could be done very quickly, via sorting by the config-symbol in differing colours. whether this is so easy to implement, is a different story, of course.

what do you think about the idea of double-clicking columns config, info + licence for detailed settings/informations, while only showing basic infos in the columns view itself:

```
title		config		info		licence
-----------------------------------------------------------------------
copy info	*symbol*	version 1.0	2017 daniel plakhotich
song rating	---		version 1.1	20xx christian hernvall
```

for instance, doubleclicking the config-symbol of "copy info" opens the settings-box and so on.

thanks a lot for the copy report function as well!

p.s.: did you already have time to include highlighting of manually installed plugins?

**Comment by saivert** [comment]
The current design of the plugins tab doesn't have room for a very wide list of plugins with the columns you like. I can maybe fit in version number and a configurability indicator but anything more requires a full redesign. The latest update was about getting rid of the separate dialog boxes for plugin preferences and have them popup in the preferences dialog and it mimics the design of the MacOS version of DeaDBeeF. Shading plugins if they are located in /usr/lib/deadbeef is also doable.

I suspect you use foobar2000 as reference but it has a dedicated page for just listing the installed components. And also a treeview where plugins and foobar2000's own preference pages share space.

**Comment by dmidecodes** [comment]
> I suspect you use foobar2000 as reference

true, and somehow undeniable :)

i am glad that ideas presented here are not immediately rejected harshly - especially because i cannot exactly estimate the limitations you have to struggle with.

however, i'm looking forward to any further features you can come up with, even if it will only be in future versions.

p.s.: off from sortable columns, is it possible to auto-sort the plugin titles in alphabetical order? this would help a lot.

**Comment by saivert** [comment]
![deadbeef-new-plugin-list](https://user-images.githubusercontent.com/63738/110382942-e6f30e80-805b-11eb-8711-59455de44fbf.png)

What do you think about this?

**Comment by dmidecodes** [comment]
well done, this is pretty awesome.

will header-bars also be sortable?

perhaps the connection between the symbols as an indicator for settings should be emphasized more.

can you do that:

place the symbol in front of "configuration" as well, then shorten the wording to "config" instead?

another little esthetic suggestion:

match the size of the column headings with those of the buttons on the right side so to get a unified look

p.s.: this is fun, perhaps i should take the step towards the design branche ;)

**Comment by saivert** [comment]
It seems like you think of the buttons Configuration, Info and License as columns in the way you describe these things but they are not. They are just differently styled tabs in a way that has been popularized as of late. Other GTK3 applications sometimes also put buttons like that in the headerbar.

Example:
![lollypop-headerbar-tabs](https://user-images.githubusercontent.com/63738/110460418-7507dd00-80ce-11eb-97e4-8345589ece98.png)


I rather not have any column headers in that list at all as it should be obvious what is what. After posting this I removed the title from the "has config" column. And the Title column is sortable and sorted alphabetically by default.

**Comment by Alexey-Yakovenko** [comment]
I don't mind this interface, but still I would consider simplifying it.

For example:

1. No column headers, always sort alphabetically
2. Add a drop down or a checkbox to filter by presence of configurable settings
3. The bold font -- I guess this signifies which plugins have non-default settings? This is nice.
4. Don't display the gear or the version number, they don't carry much value

**Comment by saivert** [comment]
The bold font is for third party plugins. Not those that have non default settings. There is no code that tracks this.
I'm going to look at the filter approach. Nice idea.

**Comment by dmidecodes** [comment]
> There is no code that tracks this.

that's a pity, but probably can't be changed? i guess this would have been a very decent feature.

the more minimal and clear, the better - therefore i am very curious about the suggestions that alexey made.
