### ISSUE TITLE
AAC won't play anymore

### ISSUE THREAD

**Issue by Michele64** [DeaDBeeF-Player/deadbeef#2532]
### Steps to reproduce the problem
Try to play any aac file

### What's going on? Describe the problem in as much detail as possible.
ERROR: could not load: /somefile.aac
failed to add file or folder /somefile.aac

### Information about the software:

Deadbeef version:  1.8.7
OS: xubuntu 20.10

**Comment by Alexey-Yakovenko** [comment]
Can't reproduce

**Comment by Michele64** [comment]
Sorry, but I still cannot play aac files. What kind of information can I provide?

**Comment by Alexey-Yakovenko** [comment]
Most likely you are not using the official build of deadbeef, and the one you are using doesn't include AAC support.
You can either decide to start using the official build, or you could contact the person who created the build your are using, and ask them to include AAC support.

**Comment by Michele64** [comment]
I'm using this one: ppa:starws-box/deadbeef-player
is that wrong?

**Comment by Alexey-Yakovenko** [comment]
Not wrong, just unofficial.
Anyone can take source code, and put it on the internet.
But as you found out, it can't play AAC. I believe, changing to using an official build from deadbeef website should solve this.

**Comment by Michele64** [comment]
hmm, did that (running sudo dpkg -i ./deadbeef-static_1.8.7-1_amd64.deb), same error

**Comment by Alexey-Yakovenko** [comment]
Are you sure that you are running the one you installed from /opt/deadbeef/bin?

**Comment by Michele64** [comment]
positive, I previously uninstalled the one from the ppa

**Comment by Michele64** [comment]
![deadbeef_2021-02-22_21-27-14](https://user-images.githubusercontent.com/13287876/108765957-c9e71780-7554-11eb-9109-ea2e15be8c5a.png)

**Comment by Alexey-Yakovenko** [comment]
can you please post the full log after running this command in console?
```
/opt/deadbeef/bin/deadbeef
```

**Comment by Michele64** [comment]
`starting deadbeef 1.8.7 [static]
server_start
searching for GUI plugins in /home/michele/.local/lib64/deadbeef
searching for GUI plugins in /home/michele/.local/lib/deadbeef
load_plugin_dir /home/michele/.local/lib/deadbeef: scandir found 6 files
searching for GUI plugins in /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 55 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/michele/.local/lib64/deadbeef
loading plugins from /home/michele/.local/lib/deadbeef
load_plugin_dir /home/michele/.local/lib/deadbeef: scandir found 6 files
loading plugin /home/michele/.local/lib/deadbeef/ddb_infobar.so
dlopen error: /home/michele/.local/lib/deadbeef/ddb_infobar.so: falsche ELF-Klasse: ELFCLASS32
trying /home/michele/.local/lib/deadbeef/ddb_infobar.fallback.so...
plugin ddb_infobar.so not found or failed to load
loading plugin /home/michele/.local/lib/deadbeef/ddb_lyrics.so
loading plugin /home/michele/.local/lib/deadbeef/ddb_misc_waveform_GTK3.so
loading plugin /home/michele/.local/lib/deadbeef/rating.so
loading plugins from /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 55 files
loading plugin /opt/deadbeef/lib/deadbeef/aac.so
loading plugin /opt/deadbeef/lib/deadbeef/adplug.so
loading plugin /opt/deadbeef/lib/deadbeef/alac.so
loading plugin /opt/deadbeef/lib/deadbeef/alsa.so
loading plugin /opt/deadbeef/lib/deadbeef/artwork.so
loading plugin /opt/deadbeef/lib/deadbeef/cdda.so
loading plugin /opt/deadbeef/lib/deadbeef/converter.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/dca.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_dumb.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_mono2stereo.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_shn.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_soundtouch.so
loading plugin /opt/deadbeef/lib/deadbeef/dsp_libsrc.so
loading plugin /opt/deadbeef/lib/deadbeef/ffap.so
loading plugin /opt/deadbeef/lib/deadbeef/ffmpeg.so
loading plugin /opt/deadbeef/lib/deadbeef/flac.so
loading plugin /opt/deadbeef/lib/deadbeef/gme.so
loading plugin /opt/deadbeef/lib/deadbeef/hotkeys.so
loading plugin /opt/deadbeef/lib/deadbeef/in_sc68.so
loading plugin /opt/deadbeef/lib/deadbeef/lastfm.so
loading plugin /opt/deadbeef/lib/deadbeef/m3u.so
loading plugin /opt/deadbeef/lib/deadbeef/mms.so
loading plugin /opt/deadbeef/lib/deadbeef/mp3.so
loading plugin /opt/deadbeef/lib/deadbeef/musepack.so
loading plugin /opt/deadbeef/lib/deadbeef/notify.so
loading plugin /opt/deadbeef/lib/deadbeef/nullout.so
loading plugin /opt/deadbeef/lib/deadbeef/opus.so
loading plugin /opt/deadbeef/lib/deadbeef/oss.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/psf.so
loading plugin /opt/deadbeef/lib/deadbeef/pulse.so
loading plugin /opt/deadbeef/lib/deadbeef/rg_scanner.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexec.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/sid.so
loading plugin /opt/deadbeef/lib/deadbeef/sndfile.so
loading plugin /opt/deadbeef/lib/deadbeef/supereq.so
loading plugin /opt/deadbeef/lib/deadbeef/tta.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_curl.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_zip.so
loading plugin /opt/deadbeef/lib/deadbeef/vorbis.so
loading plugin /opt/deadbeef/lib/deadbeef/vtx.so
loading plugin /opt/deadbeef/lib/deadbeef/wavpack.so
loading plugin /opt/deadbeef/lib/deadbeef/wildmidi.so
loading plugin /opt/deadbeef/lib/deadbeef/wma.so
starting plugin GTK3 user interface
starting plugin Lyrics
starting plugin Waveform Seekbar
starting plugin Song Rating
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter GTK2 UI
starting plugin Converter GTK3 UI
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Soundtouch
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin OSD Notify
starting plugin Null output plugin
starting plugin Opus player
starting plugin OSS output plugin
starting plugin Playlist browser GTK2
starting plugin Playlist browser GTK3
starting plugin PSF player using Audio Overload SDK
starting plugin PulseAudio output plugin
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec GTK2 UI
starting plugin Shellexec GTK3 UI
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
starting plugin FFMPEG audio player
selected output plugin: ALSA output plugin
INFO: from file /home/michele/.config/deadbeef/playlists/0.dbpl
INFO: from file /home/michele/.config/deadbeef/playlists/1.dbpl
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.10.8
`

**Comment by Michele64** [comment]
starting deadbeef 1.8.7 [static]
server_start
searching for GUI plugins in /home/michele/.local/lib64/deadbeef
searching for GUI plugins in /home/michele/.local/lib/deadbeef
load_plugin_dir /home/michele/.local/lib/deadbeef: scandir found 6 files
searching for GUI plugins in /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 55 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/michele/.local/lib64/deadbeef
loading plugins from /home/michele/.local/lib/deadbeef
load_plugin_dir /home/michele/.local/lib/deadbeef: scandir found 6 files
loading plugin /home/michele/.local/lib/deadbeef/ddb_infobar.so
dlopen error: /home/michele/.local/lib/deadbeef/ddb_infobar.so: falsche ELF-Klasse: ELFCLASS32
trying /home/michele/.local/lib/deadbeef/ddb_infobar.fallback.so...
plugin ddb_infobar.so not found or failed to load
loading plugin /home/michele/.local/lib/deadbeef/ddb_lyrics.so
loading plugin /home/michele/.local/lib/deadbeef/ddb_misc_waveform_GTK3.so
loading plugin /home/michele/.local/lib/deadbeef/rating.so
loading plugins from /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 55 files
loading plugin /opt/deadbeef/lib/deadbeef/aac.so
loading plugin /opt/deadbeef/lib/deadbeef/adplug.so
loading plugin /opt/deadbeef/lib/deadbeef/alac.so
loading plugin /opt/deadbeef/lib/deadbeef/alsa.so
loading plugin /opt/deadbeef/lib/deadbeef/artwork.so
loading plugin /opt/deadbeef/lib/deadbeef/cdda.so
loading plugin /opt/deadbeef/lib/deadbeef/converter.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/dca.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_dumb.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_mono2stereo.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_shn.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_soundtouch.so
loading plugin /opt/deadbeef/lib/deadbeef/dsp_libsrc.so
loading plugin /opt/deadbeef/lib/deadbeef/ffap.so
loading plugin /opt/deadbeef/lib/deadbeef/ffmpeg.so
loading plugin /opt/deadbeef/lib/deadbeef/flac.so
loading plugin /opt/deadbeef/lib/deadbeef/gme.so
loading plugin /opt/deadbeef/lib/deadbeef/hotkeys.so
loading plugin /opt/deadbeef/lib/deadbeef/in_sc68.so
loading plugin /opt/deadbeef/lib/deadbeef/lastfm.so
loading plugin /opt/deadbeef/lib/deadbeef/m3u.so
loading plugin /opt/deadbeef/lib/deadbeef/mms.so
loading plugin /opt/deadbeef/lib/deadbeef/mp3.so
loading plugin /opt/deadbeef/lib/deadbeef/musepack.so
loading plugin /opt/deadbeef/lib/deadbeef/notify.so
loading plugin /opt/deadbeef/lib/deadbeef/nullout.so
loading plugin /opt/deadbeef/lib/deadbeef/opus.so
loading plugin /opt/deadbeef/lib/deadbeef/oss.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/psf.so
loading plugin /opt/deadbeef/lib/deadbeef/pulse.so
loading plugin /opt/deadbeef/lib/deadbeef/rg_scanner.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexec.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/sid.so
loading plugin /opt/deadbeef/lib/deadbeef/sndfile.so
loading plugin /opt/deadbeef/lib/deadbeef/supereq.so
loading plugin /opt/deadbeef/lib/deadbeef/tta.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_curl.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_zip.so
loading plugin /opt/deadbeef/lib/deadbeef/vorbis.so
loading plugin /opt/deadbeef/lib/deadbeef/vtx.so
loading plugin /opt/deadbeef/lib/deadbeef/wavpack.so
loading plugin /opt/deadbeef/lib/deadbeef/wildmidi.so
loading plugin /opt/deadbeef/lib/deadbeef/wma.so
starting plugin GTK3 user interface
starting plugin Lyrics
starting plugin Waveform Seekbar
starting plugin Song Rating
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter GTK2 UI
starting plugin Converter GTK3 UI
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Soundtouch
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin OSD Notify
starting plugin Null output plugin
starting plugin Opus player
starting plugin OSS output plugin
starting plugin Playlist browser GTK2
starting plugin Playlist browser GTK3
starting plugin PSF player using Audio Overload SDK
starting plugin PulseAudio output plugin
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec GTK2 UI
starting plugin Shellexec GTK3 UI
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
starting plugin FFMPEG audio player
selected output plugin: ALSA output plugin
INFO: from file /home/michele/.config/deadbeef/playlists/0.dbpl
INFO: from file /home/michele/.config/deadbeef/playlists/1.dbpl
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.10.8

**Comment by Alexey-Yakovenko** [comment]
I can't see any problems in the log, everything looks good.
How do you open the file?
Is it some specific AAC file, or any file?
Does it work with AAC files in MP4 container?

**Comment by Michele64** [comment]
by default association or per drag n drop.
IO just tried an mkv container with aac audio and that does nothing, no output and no error messages

**Comment by Michele64** [comment]
I just extracted the audio fromm an mkv video and that file wors immediately witout any errors!

**Comment by Alexey-Yakovenko** [comment]
deadbeef doesn't support mkv, so it's not a very convincing test :)

when you extracted the file -- is it a raw aac, or an mp4?

**Comment by Michele64** [comment]
I tried another file, mp4 and it works flawlessly. I'm suspecting something is wrong with my audio only files. They ar recorded calls from my phone, can I sen one for further investigations?

**Comment by Michele64** [comment]
The fille specs are: 16kHz mono

**Comment by Michele64** [comment]
I just downgrades deadbeef to 1.8.4-1 and that version plays everything just fine. Then I tried Version 1.8.6-1 and it stops working. Does that help?

**Comment by Alexey-Yakovenko** [comment]
Yes, it would help a lot if you could send a test file.
There were quite many changes in the AAC decoder in 1.8.6, which should not affect raw AAC files, but they greatly affect the AAC in MP4 container.

**Comment by Michele64** [comment]
There you go :-)
[2021-02-18 15.37.32 ↓ +491628521359.aac.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/6025748/2021-02-18.15.37.32.%2B491628521359.aac.zip)

**Comment by Alexey-Yakovenko** [comment]
Thanks, I will look into it as soon as I can

**Comment by Alexey-Yakovenko** [comment]
Bug confirmed. The file is mp4 container renamed to have .aac file extension.

**Comment by Alexey-Yakovenko** [comment]
The issue has been resolved.
Thanks for helping and collaborating. The test file has helped a lot -- it's contained some data configuration which I didn't encounter before.
To get the fix, you'll need to update to the latest build from master branch when it's ready (takes about 20 minutes)
https://sourceforge.net/projects/deadbeef/files/travis/linux/master/

**Comment by Michele64** [comment]
that's wonderful! But when trying to install it shows an error (sorry it's in german):

dpkg: Fehler beim Bearbeiten des Archivs /media/michele/Data/Downloads/deadbeef-static_devel-1_amd64.deb (--install):
 Parsen der Datei »/var/lib/dpkg/tmp.ci/control«, nahe Zeile 1:
 Feld »Version« Wert »devel-1«: Versionsnummer beginnt nicht mit einer Ziffer

**Comment by Alexey-Yakovenko** [comment]
I think you can't install this deb.. since it doesn't have a version number. You will either have to build it yourself, or use this one:
https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download
