### ISSUE TITLE
plays only the first chapter of a long MP3

### ISSUE THREAD

**Issue by milahu** [DeaDBeeF-Player/deadbeef#2534]
### Steps to reproduce the problem

Specific MP3 file cuts off

### What's going on? Describe the problem in as much detail as possible.

deadbeef shows and plays only the first 3:23 minutes, which seems to be the first chapter of the file

mpv says the total length is 9:18:45

### Information about the software:

Deadbeef version: 1.8.4
OS: NixOS linux

**Comment by Alexey-Yakovenko** [comment]
mediainfo and foobar2000 all show this file the same as deadbeef. It seems to be a malformed file.

**Comment by Alexey-Yakovenko** [comment]
iTunes (Music.app) - same.

ffmpeg finds all audio content in this file, but prints a lot of errors like this:

> [mp3float @ 0x7fe633008800] Header missing
> Error while decoding stream #0:0: Invalid data found when processing input

So it's not like it's not technically possible to handle such files, it would just significantly increase the time needed to scan the files and add them to playlists, and this degraded performance is not acceptable.

I suggest you to remux this file using ffmpeg and repair it.

This command should do it:

```
ffmpeg -iY CORRUPT_FILE.mp3 -c:a copy -c:v copy GOOD_FILE.mp3
