### ISSUE TITLE
Wrong playback speed with any resampler active

### ISSUE THREAD

**Issue by AnacronoxDeVir** [DeaDBeeF-Player/deadbeef#2536]
Deadbeef version: 1.8+
OS: Linux Mint 20.1
Alsa output plugin, Alsa resampling off/on, Direct hardware device without any convertion

With any resampler dsp active (tried build-in secretrabbit & self-compiled SoX) deadbeef plays tracks with a wrong speed. Unless track's sample rate is equal to resmapler's target rate naturally.

My audicard supports up to 96khz so i set up Sox resampler to 96khz for 48, 96, 192. 44.1 for the rest. But only 96khz tracks get played correctly. The rest get either sped up or slowed down. Deadbeef 0.7.2 doesn't have this issue. Any 1.8+ does.

**Comment by Alexey-Yakovenko** [comment]
Seems like a misconfiguration. Delete the deadbeef configuration directory (`~/.config/deadbeef`), and it will reset to the default settings, which should work. If you care about your settings and playlists -- you could backup and compare the settings later, to find out what was wrong.

**Comment by AnacronoxDeVir** [comment]
That was literally the first thing i tried before posting here. Tried again just now. No config folder, freshly downloaded deadbeef binary. Preferences - Alsa output  + Direct hardware device output. Plugins - Alsa output plugin - Alsa resampling off. I put 192khz tack into playlist, load secret rabbit resampler with 96khz target samplerate and get heavily sped up playback. At least 2 times as fast as it should be by the sound of it.
`nano  /proc/asound/card0/pcm0p/sub0/hw_params`  shows still shows 192khz output. What really confuses me is that in deadbeef 0.7.2 resampler works as it should with the very same settings. hw_params show expected 96khz.

**Comment by Alexey-Yakovenko** [comment]
Your description sounds wrong already. You should not be "loading" secret rabbit resampler. Deadbeef configures it automatically, and unless you change how it's set up -- it should play at the right speed.

**Comment by Alexey-Yakovenko** [comment]
The default settings should look like this: 
![image](https://user-images.githubusercontent.com/1895698/108742152-b6798380-7537-11eb-92e4-e7adc5c6b68e.png)

please note, that the "autodetect" MUST be checked.
the value you put in the text box should not matter.

**Comment by AnacronoxDeVir** [comment]
So to actually enforce 96khz on my tracks using SoX (or secret rabbit) resampler correctly  i need to configure deadbeef 1.8+ like this: 
1. sound - override samplerate - 96khz
2. dsp - Sox resampler - autodetect?

**Comment by Alexey-Yakovenko** [comment]
That sounds right.

**Comment by AnacronoxDeVir** [comment]
Works as advertised with this settings. Thank you for your time and explanation.
