### ISSUE TITLE
Fail build 1.8.7 for armv7hl

### ISSUE THREAD

**Issue by Vascom** [DeaDBeeF-Player/deadbeef#2538]
### Steps to reproduce the problem
Try to build deadbeef for armv7hl

### What's going on? Describe the problem in as much detail as possible.
Build failed.
```
checking for armv7hl-redhat-linux-gnu-gcc... clang
checking whether the C compiler works... no
configure: error: in `/builddir/build/BUILD/deadbeef-1.8.7':
configure: error: C compiler cannot create executables
```
Full build log
https://koji.rpmfusion.org/kojifiles/work/tasks/271/470271/build.log

### Information about the software:
clang 11.1.0-0.4.rc2.fc34
Full list https://koji.rpmfusion.org/kojifiles/work/tasks/271/470271/root.log

Deadbeef version: 1.8.7
OS: Fedora Rawhide

**Comment by Alexey-Yakovenko** [comment]
Deadbeef technically builds and works just fine for ARM64 using clang.
However, I never tried this on linux, and I don't have access to linux hardware running arm.

As you can see in the log file which you linked, it says this:

> See `config.log' for more details

So you need to look in the config log, and see why the compiler fails.

**Comment by Vascom** [comment]
[config.log](https://github.com/DeaDBeeF-Player/deadbeef/files/6033867/config.log)

**Comment by Alexey-Yakovenko** [comment]
This is written in the log:

```
configure:4294: clang -O2 -flto -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS --config /usr/lib/rpm/redhat/redhat-hardened-clang.cfg -fstack-protector-strong   -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now  -flto conftest.c  >&5
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
clang-11: error: unable to execute command: Segmentation fault (core dumped)
clang-11: error: linker command failed due to signal (use -v to see invocation)
configure:4298: $? = 254
configure:4336: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "deadbeef"
| #define PACKAGE_TARNAME "deadbeef"
| #define PACKAGE_VERSION "1.8.7"
| #define PACKAGE_STRING "deadbeef 1.8.7"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "deadbeef"
| #define VERSION "1.8.7"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:4341: error: in `/builddir/build/BUILD/deadbeef-1.8.7':
configure:4343: error: C compiler cannot create executables
See `config.log' for more details

```

basically, it says that clang segfaulted when trying to compile an empty test program.

**Comment by Vascom** [comment]
OK, thanks.
May be in the future it will work...

**Comment by Alexey-Yakovenko** [comment]
Closing as invalid, since the logs clearly show that clang installation is broken, and seems to be a local install issue.
