### ISSUE TITLE
Add $rgb() function to group header

### ISSUE THREAD

**Issue by 237dmitry** [DeaDBeeF-Player/deadbeef#2540]
Please add  `$rgb()` function to `gtkui.playlist.group_by_tf` for the customization purposes.

**Comment by saivert** [comment]
@237dmitry 
If you run nightlies or build from source you can try this out now.

**Comment by 237dmitry** [comment]
> If you run nightlies or build from source you can try this out now.

I will definitely try it. I use 1.8.7 static. Thank you.

**Comment by 237dmitry** [comment]
![ss-20210306201608](https://user-images.githubusercontent.com/78153320/110215157-61cff400-7eb9-11eb-83d0-18f7e8afd0b4.png)
I am happy! Thank you a lot!

**Comment by saivert** [comment]
That looks nice!

**Comment by Alexey-Yakovenko** [comment]
Great job @saivert ! I will try to find time to integrate the same feature on mac :)

**Comment by Alexey-Yakovenko** [comment]
Now works on mac as well
