### ISSUE TITLE
`Add folder` doesn't load .cue if path contains symlink

### ISSUE THREAD

**Issue by icher** [DeaDBeeF-Player/deadbeef#2548]
`Add folder(s)` doesn't load .cue file with image (.ape, .flac etc.), if path contains symlink. `Follow symlinks` checkbox (`Add folder(s)` dialog) doesn't work. Same for drag-n-drop operations from file manager.

Manual selecting .cue file works as expected though, even if path contains symlink.

Deadbeef 1.8.4+, dev included.
OS: Fedora Linux 33
Gnome 38.3.1 Wayland

**Comment by Alexey-Yakovenko** [comment]
Triage:

Symlink made in shell
* cocoaui:
    * Drag-drop: doesn't add anything
    * Add folder(s): works, and loads cuesheet correctly
* gtkui:
    * Drag-drop: unsupported on mac, needs additional verification on linux
    * Add folder(s): loads the image, but ignores cuesheet (as reported)
     
A link made in Finder
* cocoaui:
    * Drag-drop: doesn't add anything
    * Add folder(s): works, and loads cuesheet correctly
* gtkui:
    * Drag-drop: unsupported on mac
    * Add folder(s): doesn't allow to select the link
