### ISSUE TITLE
Help me figure out " Custom Shell Commands"

### ISSUE THREAD

**Issue by 237dmitry** [DeaDBeeF-Player/deadbeef#2563]
#### Just question

I am trying to execute script via "Custom Shell Commands". To set metadata fields "add_timestamp", "first_played_timestamp", "last_played_timestamp" in _FileTime_ format and "play_count" as _integer_. This tags is for fb2k's playback statistics plugin (shared music collection on usb-HDD). But without success. If I run script from command shell (bash or pwsh) all work as expected.

The question: How call scripts from context menu? Which parameters or perhaps arguments have to be passed?

Thank you!

**Comment by kpcee** [comment]
To execute a script that changes the current file as argument, you have to enter the following:
`/home/$USER/Subdir/YourSkript.sh %F`

> %f filename without path
> %F full pathname/uri
> %d directory without path (e.g. /home/user/file.mp3 -> user)
> %D directory name with full path (e.g. /home/user/file.mp3 -> /home/user)
https://github.com/DeaDBeeF-Player/deadbeef/wiki/Title-formatting

**Comment by 237dmitry** [comment]
Thank you. Must script be the `#!/bin/sh` or this is not matter?

**Comment by kpcee** [comment]
It should make no difference whether "she-bang" is specified or not, only the file must be made executable.

**Comment by 237dmitry** [comment]
> It should make no difference

I have been trying. Thanks again!
