### ISSUE TITLE
Properties window too small

### ISSUE THREAD

**Issue by nopeinomicon** [DeaDBeeF-Player/deadbeef#2564]
### Steps to reproduce the problem
Open properties window

### What's going on? Describe the problem in as much detail as possible.
<img width="597" alt="image" src="https://user-images.githubusercontent.com/11370809/111751515-386c7c00-885a-11eb-993c-e11f68f9cdd3.png">
The preferences menu when on any other menu than plugins shrinks to a size that hides other settings buttons under an overflow menu. This doesn't inhibit the usage of the preferences dialog, it's just a slight hindrance, should categorize as a UX Issue.

### Information about the software:
Deadbeef version: Nightly (March 17 2021)
OS: macOS 11.2

**Comment by Alexey-Yakovenko** [comment]
This is already fixed on a work-in-progress branch, and will be released in version 1.9.0.

**Comment by Alexey-Yakovenko** [comment]
actually, it's already fixed in the current latest build on the master branch.
