### ISSUE TITLE
FLAGS DCP in cuesheets causes weird behaviour

### ISSUE THREAD

**Issue by dikonov** [DeaDBeeF-Player/deadbeef#2568]
### Steps to reproduce the problem
Try to play any image+cue album, while the cuesheet has FLAGS DCP inside.

### What's going on? Describe the problem in as much detail as possible.
Deadbeef fails to rewind, fails to switch to another track and fails to convert audio until the pesky flag is removed. All tracks have length 0.00. Playback always starts from the beginning and rewinding is not possible.

### Information about the software:

Deadbeef version: 1.8.4
OS: Linux

### Proposed solution
Ignore the DCP flag completely. Filter it when reading cuesheets.

**Comment by Alexey-Yakovenko** [comment]
this was fixed in one of the 3 bugfix releases which shipped after 1.8.4
