### ISSUE TITLE
Is it possible to know the number of album (not an issue)

### ISSUE THREAD

**Issue by Npa972** [DeaDBeeF-Player/deadbeef#2571]
Hello,
Is it possible to know (terminal or GUI) the number of album in the play list ?
Thank you for your work.
I use DeadBeef since a few day after a long time on Quodlibet wich became to heavy for me.
Question : there is no "man" file for DeadBeef ?

**Comment by Alexey-Yakovenko** [comment]
sorry, but unfortunately no to both questions.
command line help is available via deadbeef --help.
