### ISSUE TITLE
Rating doesn't work in new version deadbeef 

### ISSUE THREAD

**Issue by maxorbase** [DeaDBeeF-Player/deadbeef#2573]
A song rating plugin doesn't work in new version of deadbeef
after rating a song deadbeef closed and create empty temp file in song directory like this
Avalon - Ane Marie.mp3.temp
tested in kubuntu 20.10 , deadbeef Nightly builds and Stable builds 1.8.7 and 1.8.6

**Comment by maxorbase** [comment]
> I can reproduce this on network share (samba). On local filesystem it works fine.
> It only happens for me if you do try to rewrite the tags on a playing track though so it would seem to be some file locking issue maybe. This isn't an issue with the rating plugin. It happens if you use track properties editor as well.

I test rating plugin in playing mp3 and when music doesn't play. It does not matter which file you rating if rate file deadbeef crash.
Tag editor in track properties working well.

**Comment by Alexey-Yakovenko** [comment]
I tested with latest deadbeef from git VS the latest build of song rating plugin from git and from the plugins web page, both on mac and on linux.
Works fine for me, no crashes, the tags get updated.
I don't know whether the issue existed in the past, but currently it works fine.

**Comment by Alexey-Yakovenko** [comment]
One note though, I haven't tested ubuntu 20.10, since the latest I have is 20.04 (LTS)
