### ISSUE TITLE
Converting SID files to AAC/MP3/FLAC does not work (macOS)

### ISSUE THREAD

**Issue by Tekl** [DeaDBeeF-Player/deadbeef#2578]
### Steps to reproduce the problem

Select a SID song. Run the convert command and choose any of the presets format.

### What's going on? Describe the problem in as much detail as possible.

DeaDBeeF immediatly will hang on macOS

### Information about the software:

Deadbeef version: Version 1.0 (4505e1d) devel from 2021-04-03
OS: macOS 11.2.3

**Comment by Alexey-Yakovenko** [comment]
Thanks for noticing! Fixed :)
