### ISSUE TITLE
[Request] Make main window accessible when pop‐up or configuration windows are open

### ISSUE THREAD

**Issue by MarcRdC** [DeaDBeeF-Player/deadbeef#2582]
### Steps to reproduce the problem

As soon as a pop‐up or a configuration window is opened — from DeaDBeeF, of course —, then the main window cannot be interacted with.

### What's going on? Describe the problem in as much detail as possible.

When open, most pop‐up and configuration windows prevent interaction with the main window. But it could sometimes be useful to keep them all open and still be able to access the main interface.

### Information about the software:

Deadbeef version: devel, commit 4505e1d0f9a4f561116e2d6a9b08b1ca9158f578
GUI plugin: GTK3
OS: Arch Linux

**Comment by saivert** [comment]
This would require us to rework a lot of the dialogs and get rid of `gtk_dialog_run()` calls so it is possible to make them non-modal.

**Comment by Alexey-Yakovenko** [comment]
@saivert Some dialogs need to remain modal. Doesn't make sense to make them non-modal.
But preferences dialog is very simple to make non-modal.

**Comment by Alexey-Yakovenko** [comment]
Also, even if the dialogs are non-modal, it's fairly simple to limit them with only one instance of each.

**Comment by MarcRdC** [comment]
@Alexey-Yakovenko You know better which dialogs should keep their behavior if, indeed, it makes no sense to change it. I was mainly thinking about the preferences window and its sub‐windows as well as the configuration dialogs of some plugins — but maybe it depends on the plugins in question.

**Comment by Alexey-Yakovenko** [comment]
This is fixed on master and 1.8.8-beta
