### ISSUE TITLE
Is there a folder view?

### ISSUE THREAD

**Issue by Latrolage** [DeaDBeeF-Player/deadbeef#2583]
Does DeaDBeeF have a folder view instead of different playlists? I know I can just make each folder it's own playlist but having folder view as an option would be helpful

I may have missed it though, I couldn't find it anywhere

**Comment by Thorondir** [comment]
This [media libarry](https://github.com/sgomin/ddb_medialib) plugin might be what you're lookin for.

**Comment by Alexey-Yakovenko** [comment]
There's no native media library / folder browser.
It's in the works, but it will take some time before it can be released.
If you're on mac, you're welcome to try out a build from medialib branch.
