### ISSUE TITLE
Output device not shown in preferences

### ISSUE THREAD

**Issue by LeDechaine** [DeaDBeeF-Player/deadbeef#2589]
### Steps to reproduce the problem
I send sound through HDMI out of a RX580-4G graphics card.

### What's going on? Describe the problem in as much detail as possible.
HDMI device 9 is not in the list. List only shows HDMI devices 0 to 4, with/without any software conversions.
(ALSA asound.conf is: "type hw, card HDMI, device 9".)

### Information about the software:
Deadbeef version: 1.8.3
OS: Debian Testing

(Obviously, I can choose "alsa" and "default" to bypass this. But... all outputs should be in the list.)

**Comment by Alexey-Yakovenko** [comment]
Could you please post the output of `aplay -l` or `aplay -L` (preferably both)?

**Comment by LeDechaine** [comment]
**Crap.** That was a noob mistake.

"aplay -l" showed me HDMI-9 was actually HDMI 3. "aplay -L" confirmed it:

_hw:CARD=HDMI,DEV=9
HDA ATI HDMI, HDMI 3
Direct hardware device without any conversions_

Then HDMI 1-to-4 would not work but via command line I got the "resource or device busy" error with hdmi 3... but after rebooting, everything works #1.

**TL,DR: Alsa was using the output device (something froze in the background, I think), rebooting fixed everything. Sorry.**

**Comment by Alexey-Yakovenko** [comment]
no problem :)
