### ISSUE TITLE
Skip Deleted Tracks with shortcut works not properly

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2594]
### Steps to reproduce the problem
I compiled the latest git version and the described error https://github.com/DeaDBeeF-Player/deadbeef/issues/2525 still exists. If you use the context menu → "Remove Form Disk" it works as it should and the next song is played. However, if you use a shortcut DeaDBeeF always jumps to the top of the list instead of playing the next piece. 

### To test:
Shuffle → Off
Repeat → All Tracks
Shortcut → Remove From Disk, Selection (from my config file `hotkey.key30 "Ctrl Delete" 1 0 delete_from_disk`)

Deadbeef version: Git 6757aac404e7bd7100ee41179ab2cb166123f7c6
OS: Arch Linux, Xfce

**Comment by kpcee** [comment]
Just compiled and tested, works great. Muchas gracias!

**Comment by Alexey-Yakovenko** [comment]
@kpcee thanks for validation!
