### ISSUE TITLE
The linked AAC file doesn't play

### ISSUE THREAD

**Issue by fulalas** [DeaDBeeF-Player/deadbeef#2596]
This aac sample throws a floating point exception, while Mpv and Audacious open it normally: https://www.mediafire.com/file/93jd1sirx5ym1a1/11.-Return+of+the+King.aac

**Comment by Alexey-Yakovenko** [comment]
duplicate of #2148

**Comment by Alexey-Yakovenko** [comment]
The file doesn't cause a crash, but doesn't play either, therefore reopening to investigate.
