### ISSUE TITLE
Converting to [Built-in] Ogg FLAC fails

### ISSUE THREAD

**Issue by JakeSFR** [DeaDBeeF-Player/deadbeef#2602]
Linux x86_64, official DB-1.8.7 as well as the latest nightly build (deadbeef-static_devel-1_x86_64.tar.bz2, 2021-04-11).

Converting an mp3 to [Built-in] Ogg FLAC results in:

```
INFO: Make sure you know what you're doing when using --ignore-chunk-sizes.
      Improper use can cause flac to encode non-audio data as audio.
-: ERROR: unsupported format type 3
Write error (4096 bytes written out of 16000)
Failed to execute the encoder, command used:
flac --ignore-chunk-sizes --no-padding --ogg -o "/root/z.oga" -8 -
```

However, when I use this from CLI:

`lame --decode z.mp3 - | flac --ignore-chunk-sizes --no-padding --ogg -o z.oga -8 -`

conversion finishes successfully.

But then again, if I try to load that converted oga file in DB, it fails with:

`ERROR: could not load: /root/z.oga`

The file plays fine in VLC and ffplay.
It seems related to https://github.com/DeaDBeeF-Player/deadbeef/issues/2498, but changing the extension to either ogg or opus doesn't work for me.

Also, converting a FLAC file to [Built-in] Ogg FLAC converts the file fine, but with this error:

```
ERROR: could not load: /root/z.oga
cflac_write_metadata: FLAC__metadata_chain_read(_ogg) failed - code 0
converter: Failed to write FLAC metadata to /root/z.oga
```

Tested with flac 1.3.2 and 1.3.3 (latest).
Reproduced in Fatdog64-811 and Mint-18.3 (QEmu).

**Comment by Alexey-Yakovenko** [comment]
Since quite some time, MP3 is decoded in 32 bit resolution, and it seems like FLAC encoder doesn't support this.
This can't be reasonably fixed by changing the encoder settings, but you can configure the encoder to produce 24 bit stream, then the FLAC encoder would work.

![image](https://user-images.githubusercontent.com/1895698/118411664-f4e59100-b695-11eb-8599-543a719da16f.png)

**Comment by JakeSFR** [comment]
Oh, ok, that works. Thanks!
