### ISSUE TITLE
Question: How can I change many tracks metadata at once?

### ISSUE THREAD

**Issue by cocoonkid** [DeaDBeeF-Player/deadbeef#2608]
### Steps to reproduce the problem

Select multiple tracks. Click track properties.  Try to edit metadata or properties.

### What's going on? Describe the problem in as much detail as possible.

Nothing is changed/saved. Specifically I would like to change the path of many many tracks at once when I moved them to another directory  on my NAS.

 Right now I have to manually rebuild my playlist.

### Information about the software:

Deadbeef version: most recent
OS: Arch

**Comment by 237dmitry** [comment]
> Try to edit metadata or properties.
>> I would like to change the path

The path is not metadata

**Comment by Alexey-Yakovenko** [comment]
As long as this is a question: it's not possible without writing code.
