### ISSUE TITLE
The repeate one track option is always disabled.

### ISSUE THREAD

**Issue by asgharam** [DeaDBeeF-Player/deadbeef#2610]
the repeat all option is available but repeat one track is off.

Deadbeef version: couldn't find the version number. I installed from [aur](https://aur.archlinux.org/deadbeef-git.git).
OS: arch 5.12.5-arch1-1

**Comment by Alexey-Yakovenko** [comment]
It works fine here, and there's no code in deadbeef which disables this menu item (intentionally).
I only tried Ubuntu though.

Checking with discord community now to see if anyone could get it.

![image](https://user-images.githubusercontent.com/1895698/119700959-23acf580-be54-11eb-9a33-3fb93198a5d5.png)

**Comment by Alexey-Yakovenko** [comment]
Other people who use arch and install from AUR can't reproduce the issue either. You seem to have some local problem, which I would not be able to help with.

Sorry, but with the amount of information you provided it's not possible to guess what is wrong.

**Comment by asgharam** [comment]
I use global menu in kde panel and in the native GTK menu the option is enabled as expected. For gtk programs to use the global menu in kde panel, the appmenu-gtk-module is the dependency. the upstream url for appmenu-gtk-module is vala-panel-appmenu. Should I open an issue about it there or is this is about deadbeef?

**Comment by Alexey-Yakovenko** [comment]
It seems like the issue is caused by this global menu, yes.
I can't come up with any other reason for the menu items to be disabled in the playback menu.

**Comment by asgharam** [comment]
> It works fine here, and there's no code in deadbeef which disables this menu item (intentionally).
> I only tried Ubuntu though.
> 
> Checking with discord community now to see if anyone could get it.
> 
> ![image](https://user-images.githubusercontent.com/1895698/119700959-23acf580-be54-11eb-9a33-3fb93198a5d5.png)

btw what's the address of the discord server?

**Comment by Alexey-Yakovenko** [comment]
@asgharam there's a link in the README.md

**Comment by makidoll** [comment]
I have this same issue. Using deadbeef-git from aur as well, neither repeat options work for me. No errors were printed either

**Comment by Oleksiy-Yakovenko** [comment]
@makidoll does the workaround also work for you -- i.e. to not use the kde global menu feature?

**Comment by makidoll** [comment]
I'm using gnome and there's no global menu. I'll see if I can compile the code myself and debug it.

**Comment by makidoll** [comment]
I figured the issue. "Playback > Stop after current track" was enabled. I suppose it makes sense. I just never found the option whilst trying to figure out why it wasn't working.
