### ISSUE TITLE
Repeat is Off but it repeats

### ISSUE THREAD

**Issue by madprops** [DeaDBeeF-Player/deadbeef#2611]
Version: 1.8.7

I double click an audio file to play it on deadbeef.
Only that song in the playlist.
Repeat is: Off
Shuffle is: Random Tracks
I would expect it to stop after it's done playing.
The file repeats and plays again.

Why would it repeat when Repeat is off?

**Comment by madprops** [comment]
I see it only happens with Random Tracks. I guess it could be on purpose, and I should just use Random: Tracks

**Comment by Alexey-Yakovenko** [comment]
I think you are right, and when the mode is Random -- it would keep repeating randomly, and "repeat=off" wouldn't work.
I'm pretty sure it's by design, and yes -- shuffle tracks would do what you need.
