### ISSUE TITLE
%isplaying% is 1 for all on redraw playlist

### ISSUE THREAD

**Issue by white-dragon** [DeaDBeeF-Player/deadbeef#2612]
add custom column with Format=%isplaying%
is 1 for all
click button "next track": is 1 for current only
scroll playlist (or refocus window, etc): 1 for all
also when it 1 only for current doubleclick on other track: 1 for both (previous and current)
and many other strange things with it

Deadbeef version: 1.8.7
OS: Gentoo

1.8.7-r1 ebuild

**Comment by Alexey-Yakovenko** [comment]
Thanks for noticing. There was some misunderstanding of the specification on my side. Fixed.
