### ISSUE TITLE
Nightly GNU/Linux Build .deb fails to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by solstice0** [DeaDBeeF-Player/deadbeef#2619]
### Steps to reproduce the problem
`sudo dpkg -i deadbeef-static_devel-1_amd64.deb`

### What's going on? Describe the problem in as much detail as possible.
`dpkg: error processing archive deadbeef-static_devel-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 1:
 'Version' field value 'devel-1': version number does not start with digit
Errors were encountered while processing:
 deadbeef-static_devel-1_amd64.deb`

Deadbeef version: nightly build
OS: Ubuntu 20.04

**Comment by Alexey-Yakovenko** [comment]
"devel" is not a valid version number in debian.
These builds are mainly created to detect package building failures, but they are not suitable for installation

**Comment by uralets** [comment]
why offer this for dl/install then https://deadbeef.sourceforge.io/download.html??
makes no sense

**Comment by Oleksiy-Yakovenko** [comment]
There are builds and source code in the same folder which is installable / usable.
The packages are built as a side-product. Probably shouldn't be uploaded.

**Comment by uralets** [comment]
The link for the nightly builds points to the sourceforge dl page https://sourceforge.net/projects/deadbeef/files/travis/linux/master/, what is usable there?

**Comment by Oleksiy-Yakovenko** [comment]
This one [deadbeef-static_devel-1_x86_64.tar.bz2](https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download)

It doesn't require installation, just unpack and run
