### ISSUE TITLE
Add option to ignore leading words like 'The' when sorting playlist columns 

### ISSUE THREAD

**Issue by wcerfgba** [DeaDBeeF-Player/deadbeef#2626]
Thanks for all your work on DeaDBeeF, it's my favourite music player! :heart: 

One problem I have is that I like to have all my music in one big playlist and I sort it by Album and Album Artists so I can find everything. But some Album Artists have 'The' in the name which causes them to all group together around 'T', so for example if I have an album by "Dave Brubeck", that will be at the top of the list, but then an album by "The Date Brubeck Quartet" will be near the bottom of the list next to "The xx".

So currently my playlist sorts like this:
1. Benny Benassi
2. Dave Brubeck
3. Tenderlonious
4. The Dave Brubeck Quartet
5. The Funk Brothers
6. The xx
7. Traxman
8. Vulfpack

But really I would like to sort my playlist like this:
1. Benny Benassi
2. Dave Brubeck
3. The Dave Brubeck Quartet
4. The Funk Brothers
5. Tenderlonious
6. Traxman
7. Vulfpeck
8. The xx

Thank you!

**Comment by Alexey-Yakovenko** [comment]
You can strip the `The ` prefixes when sorting by using a custom title format expression, and doing something like this:

`$stripprefix(%artist%)`

As documented here: https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference
