### ISSUE TITLE
DeaDBeeF's Album art plugin fails to read embedded ID3v2 album art in mp3 files

### ISSUE THREAD

**Issue by ALEXjma** [DeaDBeeF-Player/deadbeef#2627]
### Steps to reproduce the problem
Play similar mp3 files in DeaDBeeF (be sure to only have embedded album art on and cache cleared/disabled)

### What's going on? Describe the problem in as much detail as possible.
DeaDBeeF's Album art plugin fails to read embedded ID3v2 album art in mp3 files even tough they are able to be read by everything else (MusicBrainz Picard, MP3Tag, Foobar, Aimp, Windows Explorer, Gnome file explorer etc...)

### Information about the software:

Deadbeef version: (deadbeef 1.8.7-1 [https://aur.archlinux.org/deadbeef.git], deadbeef-git r9683.5bcd39b7e-1 [https://aur.archlinux.org/deadbeef-git.git], DeadDBeeF master branch built from source by myself [https://github.com/DeaDBeeF-Player/deadbeef/tree/0a1108c5f8cec31505c7c6d872c66451205bbe25]
OS: Arch Linux

One way to fix it on my end is to re-encode the tags using something like MBpicard or MP3Tag but considering that it's a problem on DeaDBeeF's part and that I would have to re-encode 1000+ mp3s I'm defo not gonna do that

Side Note: I noticed that when building from source DeaDBeeF was building with the "artwork-legacy" plugin instead of the "artwork" plugin dunno if that's intentional

[Not working mp3.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/6766368/Not.working.mp3.zip)
[Working mp3.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/6766369/Working.mp3.zip)
[Extra examples.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/6766371/Extra.examples.zip)

**Comment by Alexey-Yakovenko** [comment]
Yes, the new artwork plugin (the non-legacy one) is still not ready to replace the artwork-legacy in deadbeef/gtkui, and is still being developed. So this is intentional.

Confirmed bug: the embedded image loads and displays fine in the new artwork plugin (cocoaui), and doesn't load in the legacy plugin.

**Comment by Alexey-Yakovenko** [comment]
Should work now
