### ISSUE TITLE
Progress bar does not allow user to go to a certain second

### ISSUE THREAD

**Issue by marcustone** [DeaDBeeF-Player/deadbeef#2631]
### Steps to reproduce the problem
Install Version 1.0 (bbe2f0a) on MacOS

### What's going on? Describe the problem in as much detail as possible.
Progress bar does not allow user to go to a certain second
![Snipaste_2021-07-09_23-17-04](https://user-images.githubusercontent.com/17929904/125100727-01bdb880-e10c-11eb-9567-5500497062b6.png)

### Information about the software:
The progress bar cannot be customized into spectrum like this
![Snipaste_2021-07-09_23-17-01](https://user-images.githubusercontent.com/17929904/125100646-ebaff800-e10b-11eb-9237-22d396240749.png)

Deadbeef version: Version 1.0 (bbe2f0a)
OS: 10.14.6

**Comment by marcustone** [comment]
Whenever I click the progress bar in order to go to a second second, it will restart the whole song from the very beginning

**Comment by Alexey-Yakovenko** [comment]
FYI: this is probably a compatibility issue. Deadbeef for mac is generally developed on the latest macos, which is 11.x, and soon will be 12.x. Upgrading to Catalina should help. If you're a developer yourself -- it would help if you could investigate the issue and provide a patch.

**Comment by marcustone** [comment]
Plus, you won't be able to add any song until you fully expand the album/artist to certain songs
![Snipaste_2021-07-09_23-28-34](https://user-images.githubusercontent.com/17929904/125102257-aab8e300-e10d-11eb-929f-0349ec26df8f.png)

**Comment by marcustone** [comment]
> FYI: this is probably a compatibility issue. Deadbeef for mac is generally developed on the latest macos, which is 11.x, and soon will be 12.x. Upgrading to Catalina should help. If you're a developer yourself -- it would help if you could investigate the issue and provide a patch.

10.11, 10.12 is old, 10.14 is not old sir
Besides, 10.14 Mojave is the last major version I can officially upgrade my Macbook towards without hacking the system image

**Comment by Alexey-Yakovenko** [comment]
> Plus, you won't be able to add any song until you fully expand the album/artist to certain songs

I understand your wish to try experimental / work-in-progress branch, but this work is not yet ready for the general users, and while the feedback is appreciated -- it's a little too soon to report issues about that.
I suggest to wait until medialibrary feature is finalized and released (or at least in the beta testing phase), and then go for it.

**Comment by Alexey-Yakovenko** [comment]
Btw, have you tried running a build from master branch instead of medialib? Does it have the same problem with the seek bar?

**Comment by marcustone** [comment]
> Btw, have you tried running a build from master branch instead of medialib? Does it have the same problem with the seek bar?

No I haven't, but the seek bar malfunctions is a sure thing. It bans user to go to a certain second directly but restarts the whole song. Where can I get Master branch by the way?

**Comment by Alexey-Yakovenko** [comment]
https://sourceforge.net/projects/deadbeef/files/travis/osx/master/deadbeef-devel-osx-x86_64.zip/download

**Comment by Alexey-Yakovenko** [comment]
I had to install Mojave on external hard drive to be able to reproduce and fix it, and it turned out to be quite tough problem.
Thankfully, it's fixed now.
Thanks for reporting.
