### ISSUE TITLE
Unable to seek after ~12:25h / 13:31h

### ISSUE THREAD

**Issue by SuperVirus** [DeaDBeeF-Player/deadbeef#2636]
DeaDBeeF is unable to seek beyond a certain timestamp in very long audio files.
The limit is about 13:31h for stereo files with a sample rate of 44.100 and about 12:25h for stereo files with a sample rate of 48.000.
Only seeking in the file is affected. Playback will continue beyond those limits without problems.

It guess a 32bit integer is used for the seek position:
44100×2×3600×13,5 => 4 286 520 000 samples
48000×2×3600×12,4 => 4 285 440 000 samples
Both values are close the maximum of 4 294 967 295 for a 32bit integer.

### Steps to reproduce the problem
- Open a very long (min 14h audio file in DeaDBeeF)
- Seek to a timestamp > 13:40h

### What's going on? Describe the problem in as much detail as possible
Depending on the decoder plugin the behavior differs:
- For FLAC and OPUS the seek does not happen and the playback continues.
- For ffmpeg (tested with MP4-AAC and OPUS) the playback position jumps to the start of the file.

### Information about the software:
Deadbeef version: 1.8.7 and git  6d3b11262d5fbe0326b408bc73ae01861505d4ef
OS: Arch Linux 64bit

Here are some 14h test files (FLAC, only silence)
:[testfiles.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/6812680/testfiles.zip)

**Comment by Alexey-Yakovenko** [comment]
It's the same with any files.. It's not hard to fix, but a little time consuming. In the meantime I'm doing 2 things:

1. adding a new extended decoder plugin interface, to add 64 bit seek offset API.
2. implementing the interface and using 64 bit offset in the flac plugin.

**Comment by Alexey-Yakovenko** [comment]
(not closing the issue yet, until it's fixed in all relevant decoders).

**Comment by Alexey-Yakovenko** [comment]
Sorry, it was closed by the git merge

**Comment by Alexey-Yakovenko** [comment]
A list of other codecs that could potentially benefit from the same fix, alphabetical order:
* aac
* alac
* ape (seektable is 32bit)
* mp3
* musepack
* sndfile
* tta (seektable is 32 bit)
* wavpack
* wma
