### ISSUE TITLE
Nonportable/confusing assumptions about x11 paths (hotkeys on OS X)

### ISSUE THREAD

**Issue by dmacks** [DeaDBeeF-Player/deadbeef#2638]
Building deadbeef-1.8.7 on OS X 10.13, x11 via XQuartz-2.8.1, 

X11/Xlib.h in not in default compiler path, so AC_CHECK_HEADER for it fails:
```
checking X11/Xlib.h usability... no
checking X11/Xlib.h presence... no
checking for X11/Xlib.h... no
```
But if I have -I for it in my CPPFLAGS, it is detected and -lX11 is propagated. To avoid build-failure, I also pass the analogous -L for X11 in LDFLAGS. It's possible that all sorts of platforms might have x11 in all sorts of unexpected places. **Improvement:** use AC_PATH_X to detect x11, which supports a standard set of flags.

Based on a test for platform=osx, configure then sets HAVE_HOTKEYS=yes (regardless of x11 detection). And in plugins/hotkeys/hotkeys.c, use of X11 is avoided regardless of detection. I'm not sure what runtime effect there is, but it seems like it would disable some functionality.

This is confusing from a builder/downstream-packager perspective. If the goal is to have a special hotkeys mode on OS X that doesn't use x11, then configure shouldn't bother looking for x11 on this platform because that's a wasted test and incorrectly suggests that this (non)detection has any effect on build options. The logic is:

1. verbosely detect x11
2. if (osx) {silently change hotkeys build options and runtime effects)

**Improvement:** add verbose message about ignoring that result when overriding it, or maybe refactor it is:

if (osx) {verbose message about not using x11 for hotkeys} else {verbosely detect x11}

I spent a while puzzling over why x11 was detected but then Xlib.h not invoked in hotkeys.c. Turns out that there is a second platform test in the .c that disables x11 even if it was detected. I'm not sure why, but it would be clearer to indicate this build-time configuration effect during configure. That would also provide a centralized place for hackers who want to experiment with enabling x11 on os x. **Improvement:** set and propagate HOTKEYS_NO_X11 instead of a second platform test and local macro in hotkeys.c.

**Comment by Alexey-Yakovenko** [comment]
Is there any reason why you're not following the normal build steps to compile deadbeef on mac, or not using the provided prebuilt binaries?
Deadbeef should not require X11 on mac, it's a fully native application which uses Cocoa.
Building it using the autotools scripts is theoretically possible, but it's not a supported or maintained path to build deadbeef on mac.

**Comment by Alexey-Yakovenko** [comment]
Also, just so you know: deadbeef for mac has not been officially released, and the only recommended way to use it is to use the master branch / or what's commonly called "trunk".
The numbered releases are for linux only, and most of the time they don't include the latest mac code.

**Comment by dmacks** [comment]
My gtk is x11 not native. That allows me to run GUI programs remotely (ssh tunnel) and cross-platform. Someone asked fink to package it, which already cherry-picks a bunch of git patches. As part of hacking for mac purposes, these are the details that are confusing and make it harder for us to help with portability.

**Comment by Alexey-Yakovenko** [comment]
Building or running Deadbeef with GTK and X11 on macOS is not supported by the developer team.
I'm sorry, but you're on your own with this.
