### ISSUE TITLE
[Feature Request] File operations

### ISSUE THREAD

**Issue by mistersister** [DeaDBeeF-Player/deadbeef#2640]
Since I couldn't find any plugins that do it nor could I make it work via shell commands, along the  "Remove from disk" context menu item, we could use an option to copy/move songs to different folders.

Many times you spot that song on a playlist that is not in the folder where it should be or you want to move/copy songs from different playlists all to the same folder. In these cases having the ability to right-click a bunch of songs and having an option to Copy To... / Move To .. would be very useful.

Thanks.

**Comment by Alexey-Yakovenko** [comment]
In deadbeef, copy & move files feature is performed by the Converter functionality.
It includes File Copy and File Move encoders just for that.
