### ISSUE TITLE
DeaDBeeF can not read music files .aac

### ISSUE THREAD

**Issue by GittyMejorado** [DeaDBeeF-Player/deadbeef#2641]
### Information about the software:

Deadbeef version: DeaDBeeF 1.8.8.1
OS: KDE NEON 5.22 User Edition

DeaDBeeF can not read music files .aac
This has happened to me in previous versions of DeaDBeeF Installed in other distributions like Kubuntu.
In DeadBeef I have installed the AAC Player version 2.0 complement but I simply can not find any option to play any .aac file
How could I solve it?

**Comment by GittyMejorado** [comment]
I have deadbeef installed, but when I execute the command the terminal throws me

deadbeef: command not found

**Comment by Alexey-Yakovenko** [comment]
How did you install it?

**Comment by Alexey-Yakovenko** [comment]
Please provide the following information:

* How to run in the console (locate the application on disk)
* console output
* how the player was installed

I can't help without this information at all, and I think your problem is not caused by the developers, but is caused by some random person on the internet, from whom you downloaded the package to install.

**Comment by GittyMejorado** [comment]
I install DeadBeef with the QApt installer, with the file deadbeef-static_1.8.8-1_amd64.deb

The executable file is located in /opt/deadbeef/bin/deadbeef 
When I enter the folder where the executable file is and I execute the terminal throws me
./deadbeef
starting deadbeef 1.8.8 [static]
server_start
searching for GUI plugins in /home/tau/.local/lib64/deadbeef
searching for GUI plugins in /home/tau/.local/lib/deadbeef
load_plugin_dir /home/tau/.local/lib/deadbeef: scandir found 36 files
searching for GUI plugins in /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 55 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/tau/.local/lib64/deadbeef
loading plugins from /home/tau/.local/lib/deadbeef
load_plugin_dir /home/tau/.local/lib/deadbeef: scandir found 36 files
loading plugin /home/tau/.local/lib/deadbeef/ddb_archive_reader.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_bs2b.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_copy_info_gtk2.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_copy_info_gtk3.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_customizabletb_gtk2.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_customizabletb_gtk3.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_gnome_mmkeys.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_bookmark_manager.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_filebrowser_GTK2.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_filebrowser_GTK3.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_headerbar_GTK3.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_playback_order_GTK2.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_playback_order_GTK3.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_playback_status_GTK2.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_playback_status_GTK3.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_quick_search_GTK2.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_quick_search_GTK3.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_replaygain_control_GTK2.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_replaygain_control_GTK3.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_waveform_GTK2.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_misc_waveform_GTK3.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_vis_musical_spectrum_GTK2.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_vis_musical_spectrum_GTK3.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_vis_spectrogram_GTK2.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_vis_spectrogram_GTK3.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_vis_vu_meter_GTK2.so
loading plugin /home/tau/.local/lib/deadbeef/ddb_vis_vu_meter_GTK3.so
loading plugin /home/tau/.local/lib/deadbeef/discord_presence.so
loading plugin /home/tau/.local/lib/deadbeef/jack.so
loading plugin /home/tau/.local/lib/deadbeef/mpris.so
loading plugin /home/tau/.local/lib/deadbeef/pulse2.so
loading plugin /home/tau/.local/lib/deadbeef/rating.so
loading plugin /home/tau/.local/lib/deadbeef/stereo_widener.so
loading plugin /home/tau/.local/lib/deadbeef/vfs_rar.so
loading plugins from /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 55 files
loading plugin /opt/deadbeef/lib/deadbeef/aac.so
loading plugin /opt/deadbeef/lib/deadbeef/adplug.so
loading plugin /opt/deadbeef/lib/deadbeef/alac.so
loading plugin /opt/deadbeef/lib/deadbeef/alsa.so
loading plugin /opt/deadbeef/lib/deadbeef/artwork.so
loading plugin /opt/deadbeef/lib/deadbeef/cdda.so
loading plugin /opt/deadbeef/lib/deadbeef/converter.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/dca.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_dumb.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_mono2stereo.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_shn.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_soundtouch.so
loading plugin /opt/deadbeef/lib/deadbeef/dsp_libsrc.so
loading plugin /opt/deadbeef/lib/deadbeef/ffap.so
loading plugin /opt/deadbeef/lib/deadbeef/ffmpeg.so
loading plugin /opt/deadbeef/lib/deadbeef/flac.so
loading plugin /opt/deadbeef/lib/deadbeef/gme.so
loading plugin /opt/deadbeef/lib/deadbeef/hotkeys.so
loading plugin /opt/deadbeef/lib/deadbeef/in_sc68.so
loading plugin /opt/deadbeef/lib/deadbeef/lastfm.so
loading plugin /opt/deadbeef/lib/deadbeef/m3u.so
loading plugin /opt/deadbeef/lib/deadbeef/mms.so
loading plugin /opt/deadbeef/lib/deadbeef/mp3.so
loading plugin /opt/deadbeef/lib/deadbeef/musepack.so
loading plugin /opt/deadbeef/lib/deadbeef/notify.so
loading plugin /opt/deadbeef/lib/deadbeef/nullout.so
loading plugin /opt/deadbeef/lib/deadbeef/opus.so
loading plugin /opt/deadbeef/lib/deadbeef/oss.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/psf.so
loading plugin /opt/deadbeef/lib/deadbeef/pulse.so
loading plugin /opt/deadbeef/lib/deadbeef/rg_scanner.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexec.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/sid.so
loading plugin /opt/deadbeef/lib/deadbeef/sndfile.so
loading plugin /opt/deadbeef/lib/deadbeef/supereq.so
loading plugin /opt/deadbeef/lib/deadbeef/tta.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_curl.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_zip.so
loading plugin /opt/deadbeef/lib/deadbeef/vorbis.so
loading plugin /opt/deadbeef/lib/deadbeef/vtx.so
loading plugin /opt/deadbeef/lib/deadbeef/wavpack.so
loading plugin /opt/deadbeef/lib/deadbeef/wildmidi.so
loading plugin /opt/deadbeef/lib/deadbeef/wma.so
starting plugin GTK3 user interface
starting plugin RAR, 7z and Gzip archive reader
starting plugin Headphone crossfeed (bs2b)
starting plugin Copy info
starting plugin Copy info
starting plugin Customizable toolbar for GTKUI(GTK2)
starting plugin Customizable toolbar for GTKUI(GTK3)
starting plugin GNOME multimedia keys support
starting plugin Bookmark Manager
starting plugin File Browser
starting plugin File Browser
starting plugin Headerbar for GTK3 UI
starting plugin Playback order menu
starting plugin Playback order menu
starting plugin Playback Status Widget
starting plugin Playback Status Widget
starting plugin Quick search
starting plugin Quick search
starting plugin Replay Gain Control GTK2 UI
starting plugin Replay Gain Control GTK3 UI
starting plugin Waveform Seekbar
starting plugin Waveform Seekbar
starting plugin Musical Spectrum
starting plugin Musical Spectrum
starting plugin Spectrogram
starting plugin Spectrogram
starting plugin VU Meter
starting plugin VU Meter
starting plugin Discord Rich Presence Plugin
starting plugin JACK output plugin
starting plugin MPRISv2 plugin
starting plugin PulseAudio output plugin version 2
starting plugin Song Rating
starting plugin Stereo widener
starting plugin RAR vfs
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter GTK2 UI
starting plugin Converter GTK3 UI
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Soundtouch
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin OSD Notify
starting plugin Null output plugin
starting plugin Opus player
starting plugin OSS output plugin
starting plugin Playlist browser GTK2
starting plugin Playlist browser GTK3
starting plugin PSF player using Audio Overload SDK
starting plugin PulseAudio output plugin
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec GTK2 UI
starting plugin Shellexec GTK3 UI
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
starting plugin FFMPEG audio player
selected output plugin: ALSA output plugin
INFO: from file /home/tau/.config/deadbeef/playlists/0.dbpl
INFO: from file /home/tau/.config/deadbeef/playlists/1.dbpl
INFO: from file /home/tau/.config/deadbeef/playlists/2.dbpl
INFO: from file /home/tau/.config/deadbeef/playlists/3.dbpl
plugin Copy info failed to connect to dependencies, deactivated.
[ddb_customizabletb_gtk2] Failed to connect to GTKUI(GTK2), deactivating
plugin Customizable toolbar for GTKUI(GTK2) failed to connect to dependencies, deactivated.
plugin File Browser failed to connect to dependencies, deactivated.
fb api2
plugin Playback order menu failed to connect to dependencies, deactivated.
plugin Playback Status Widget failed to connect to dependencies, deactivated.
plugin Quick search failed to connect to dependencies, deactivated.
replaygain control: can't find gtkui plugin
plugin Replay Gain Control GTK2 UI failed to connect to dependencies, deactivated.
plugin Waveform Seekbar failed to connect to dependencies, deactivated.
plugin Musical Spectrum failed to connect to dependencies, deactivated.
plugin Spectrogram failed to connect to dependencies, deactivated.
plugin VU Meter failed to connect to dependencies, deactivated.
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
resume: track -1 pos -1.000000 playlist -1
gtkui plugin compiled for gtk version: 3.10.8
connecting button tray signals

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.872: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.872: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.872: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.872: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.872: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.951: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.951: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.951: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.951: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.951: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.951: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.951: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:52.951: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)
create surf
create surf

** (deadbeef:4037097): WARNING **: 10:12:53.389: ddb_gnome_mmkeys: Failed to grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon was not provided by any .service files

(deadbeef:4037097): Gtk-WARNING **: 10:12:56.456: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:56.456: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:56.456: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:56.456: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:56.456: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:56.456: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:56.456: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

(deadbeef:4037097): Gtk-WARNING **: 10:12:56.456: for_size smaller than min-size (15 < 16) while measuring gadget (node check, owner GtkCheckButton)

--------------------------------------------------------------------------------------------------------------------------------

I do not blame the developer, DeaDBeeF works excellent for me, is my favorite player and is excellent, I just want to know the reason why I can not execute .aac files

**Comment by Alexey-Yakovenko** [comment]
There doesn't seem to be any problem with the installation, according to the log.
Potentially there's some problem with the aac files themselves.
Please send 1 such file over email for investigation to me, and I will see what can be done.
