### ISSUE TITLE
target samplerate to 48000KHz speeds up song

### ISSUE THREAD

**Issue by servimo** [DeaDBeeF-Player/deadbeef#2644]
When trying to change target samplerate to 48000KHz, in sound configuration, the song speeds up. 

*I use Pipewire.

**Comment by Alexey-Yakovenko** [comment]
* The player is doing what you tell it to do. Even if it results in wrong playback speed or whatever. Don't change the settings that you don't understand, and everything should work fine.
* Deadbeef doesn't support Pipewire natively. If you are having issues with Pipewire -- please seek assistance from pipewire developers, or community forums

**Comment by alexeysvrv** [comment]
@Alexey-Yakovenko Hi Alexey! Will be support in Deadbeef natively Pipewire backend?

**Comment by Alexey-Yakovenko** [comment]
@alexeysvrv It already exists: https://github.com/saivert/ddb_output_pw

**Comment by alexeysvrv** [comment]
@Alexey-Yakovenko Will there be native integration of this plugin into the player?

**Comment by Alexey-Yakovenko** [comment]
I can't neither confirm nor deny this
