### ISSUE TITLE
DeaDBeeF cannot read Replay Gain data added by foobar2000 from an embedded cue sheet

### ISSUE THREAD

**Issue by acc987** [DeaDBeeF-Player/deadbeef#2645]
### Steps to reproduce the problem
Open an audio file with an embedded cue sheet in foobar2000 and assign Replay Gain information. Open the audio file in DeaDBeeF and start playback. DeaDBeeF will start playback but ignore the Replay Gain information.

### What's going on? Describe the problem in as much detail as possible.
While cueutil.c seems to implement parsing Replay Gain data from an (embedded) cue sheet, it cannot parse such data when it was created/added by foobar2000. I have added an example for such a cue sheet as generated by foobar2000 (also demonstrating the formatting for negative, positive and zero gain adjustments used by foobar2000) below:

```
PERFORMER "Example Artist"
TITLE "Example Album"
REM REPLAYGAIN_ALBUM_GAIN 0.00 dB
REM REPLAYGAIN_ALBUM_PEAK 1.000000
FILE "Example File.wav" WAVE
  TRACK 01 AUDIO
    TITLE "Example Title"
    PERFORMER "Example Track Artist"
    REM REPLAYGAIN_TRACK_GAIN -1.00 dB
    REM REPLAYGAIN_TRACK_PEAK 1.000000
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Another Example Title"
    PERFORMER "Another Example Track Artist"
    REM REPLAYGAIN_TRACK_GAIN +1.00 dB
    REM REPLAYGAIN_TRACK_PEAK 1.000000
    INDEX 01 01:00:00
  TRACK 03 AUDIO
    TITLE "Yet Another Example Title"
    PERFORMER "Yet Another Example Track Artist"
    REM REPLAYGAIN_TRACK_GAIN 0.00 dB
    REM REPLAYGAIN_TRACK_PEAK 1.000000
    INDEX 01 02:00:00
```

I suspect that the issue stems from foobar2000 adding the gain adjustment in decibels, but I am not certain and would appreciate it if this can be looked into. Thanks in advance for your assistance (and for providing and maintaining DeaDBeeF in the first place).

### Information about the software:
DeaDBeeF version: 1.8.7
OS: openSUSE Leap 15.3

**Comment by Alexey-Yakovenko** [comment]
I can't reproduce the issue locally. Can you please send a sample file by email for investigation?

**Comment by acc987** [comment]
Yes, I also just noticed that not all files are affected, even though the formatting of the cue sheet is the same... I'll gladly send you a sample file once I have figured out a way to create a file that I can (feasibly) share with you. (I probably would have waited with creating the issue if I had noticed that not all files are affected beforehand.)

**Comment by acc987** [comment]
This issue is getting weirder by the minute: I have created a copy from one of the files exhibiting the issue in order to create a new version in which I replace the audio with a sine wave but keep the meta data. Afterwards, I noticed that the Replay Gain is successfully applied not only when playing back the copy containing only the sine wave but also when playing back the bit-identical copy of the original file, which exhibits the issue: So I have an audio file fileA located in folder folderA/, where the Replay Gain information is ignored, but when I copy the file (without changes) to a folder folderB/ and add it to a (new) playlist, DeaDBeeF will suddenly apply the Replay Gain as it is written to the embedded cue sheet.

Clearly the problem is not related to the individual file but I rather suspect that there is some cache preventing DeaDBeef from updating some metadata: Initially, I added the offending files to a playlist before Replay Gain information was added. I then added the Replay Gain information using foobar2000 and it seems that this information is somehow not updated. This behavior does not change even when deleting the album from the playlist and adding it back afterwards. Are there any caches that I can manually delete/reset?

**Comment by Alexey-Yakovenko** [comment]
There are no caches like this, but after updating metadata externally -- you have to re-add the file / cuesheet to deadbeef playlist.

**Comment by acc987** [comment]
As I did mention, the issue was not resolved by simply re-adding it to the playlist, but I now have a suspicion as to why I am experiencing this issue and must provide a bit more detail:

This folder audioFolder does not only contain an audio file audioFile with an embedded cue sheet with Replay Gain information but also a separate cue sheet cueFile referencing this audio file via the FILE command. The separate cue sheet, however, lacks the Replay Gain information.

I just confirmed the following behavior: When adding only audioFile via File / Add file(s), the Replay Gain information is read from the file, but when adding it implicitly by adding audioFolder via File / Add folder(s), the Replay Gain information is not being read. I am not sure how Add folder(s) works but could there be some kind of conflict between adding the audio file itself and adding it via adding the cue sheet file? (I am only keeping the cue sheet file for archival purposes and it should ideally be ignored by DeaDBeeF when adding folders, but I am not sure if it is possible to achieve this.)

**Comment by Alexey-Yakovenko** [comment]
Deadbeef always favors external files over embedded files.
It treats them as overrides for what is inside the file.
This includes cuesheet, album art, and probably other similar external metadata.

Currently there's no way to change this behavior, since it creates too many complications for various systems, but it may get implemented in the future.

You would have to either keep the external cuesheet up to date, or delete it.

**Comment by Alexey-Yakovenko** [comment]
> I am not sure how Add folder(s) works but could there be some kind of conflict between adding the audio file itself and adding it via adding the cue sheet file?

There's difference. Adding folders will find and use the external cuesheet files, file adding individual files will only use embedded cuesheets if they're present.

**Comment by Alexey-Yakovenko** [comment]
More precisely:

* Add folder(s):
   Use external cuesheet if present
   Use embedded cuesheet if present
   Otherwise no cuesheet
* Add file(s):
   Use external cuesheet if it's in the selected files list
   Use embedded cuesheet if present
   Otherwise no cuesheet
* Add single cuesheet file:
   Will use that cuesheet file, if the associated media file can be found

**Comment by acc987** [comment]
Thanks for the clarification!
