### ISSUE TITLE
Alignment of Duration

### ISSUE THREAD

**Issue by pkzc** [DeaDBeeF-Player/deadbeef#2646]
### Steps to reproduce the problem
Could you please right-align the Duration column in the songlist?
It is left-aligned now, but it would look more regular if right-aligned.
![Screenshot at 2021-08-09 14-22-04](https://user-images.githubusercontent.com/23018794/128705412-ec58873f-79d8-4c87-b5e9-3edaf1ede945.png)

### Information about the software:

Deadbeef version:
1.8.7, 1.8.8

OS:
Fedora Linux 34

**Comment by kpcee** [comment]
Right click on the Duration column -> Edit column and select Alignment right.

**Comment by pkzc** [comment]
That's perfect, thank you.
