### ISSUE TITLE
DeaDBeeF can't play FLAC stream from internet radio

### ISSUE THREAD

**Issue by jazznfunk** [DeaDBeeF-Player/deadbeef#2647]
### Steps to reproduce the problem: Just try to open FLAC stream from here:
https://www.hiresaudio.online/czech-radio/
stream: http://amp.cesnet.cz:8000/cro-jazz.flac

Stream is working on default Celluloid player and foobar2000 (through Wine)

### What's going on? Describe the problem in as much detail as possible. DeadBeaF gives an error:
No suitable decoder found for stream http://amp.cesnet.cz:8000/cro-d-dur.flac of content-type application/ogg
But, of course, DeadBeeF is playing local FLAC files.

### Information about the software:

Deadbeef version:1.8
OS: Linux Mint 20.1 Uma 64 bit Xfce

**Comment by Alexey-Yakovenko** [comment]
duplicate of #1122
