### ISSUE TITLE
The log window always open automatically

### ISSUE THREAD

**Issue by marcustone** [DeaDBeeF-Player/deadbeef#2649]
### Steps to reproduce the problem
Open Deadbeef

### What's going on? Describe the problem in as much detail as possible.
The log window always open automatically

### Information about the software:
Latest Mac version of Deadbeef

Deadbeef version:
OS: 10.14 Mojave

**Comment by Alexey-Yakovenko** [comment]
Can you post the content of the log window? It only opens when an error important enough occurs to show to the user.
I would have to know what the error is, and figure whether I need to suppress it, or it's something that the user needs to take action about.

**Comment by marcustone** [comment]
The log window will keep popping up as always
and I did not load any of the tracks

Failed to play track: /Users/mac/Downloads/鳥の詩 Piano.m4a
ERROR: could not load: /Users/mac/Music/Local/20190408 020700.m4a
ERROR: could not load: /Users/mac/Music/Local/20190416 095342.m4a
ERROR: could not load: /Users/mac/Music/Local/20190419 110615.m4a
ERROR: could not load: /Users/mac/Music/Local/20190419 110704.m4a
ERROR: could not load: /Users/mac/Music/Local/20190419 110800.m4a
ERROR: could not load: /Users/mac/Music/Local/Cheap Thrills - Sia.m4a
ERROR: could not load: /Users/mac/Music/MV/不潮不用花钱 MV.mp4
starting deadbeef devel [static] [portable]
server_start
searching for GUI plugins in /Applications/DeaDBeeF.app/Contents/PlugIns
load_plugin_dir /Applications/DeaDBeeF.app/Contents/PlugIns: scandir found 49 files
searching for GUI plugins in /Users/mac/Library/Application Support/Deadbeef/Plugins
load gui plugin
loading plugins from /Applications/DeaDBeeF.app/Contents/PlugIns
load_plugin_dir /Applications/DeaDBeeF.app/Contents/PlugIns: scandir found 49 files
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/aac.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/adplug.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/alac.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/artwork.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/converter.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/dca.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/ddb_dumb.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/ddb_mono2stereo.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/ddb_shn.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/ddb_soundtouch.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/dsp_libsrc.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/ffap.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/ffmpeg.dylib
dlopen error: dlopen(/Applications/DeaDBeeF.app/Contents/PlugIns/ffmpeg.dylib, 2): Library not loaded: /Users/waker/Downloads/ffmpeg-4.4/build/x86_64/lib/libavformat.58.dylib
  Referenced from: /Applications/DeaDBeeF.app/Contents/PlugIns/ffmpeg.dylib
  Reason: image not found
plugin ffmpeg.dylib not found or failed to load
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/flac.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/gme.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/hotkeys.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/in_sc68.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/lastfm.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/libavcodec.dylib
dlopen error: dlopen(/Applications/DeaDBeeF.app/Contents/PlugIns/libavcodec.dylib, 2): Library not loaded: /Users/waker/Downloads/ffmpeg-4.4/build/x86_64/lib/libavutil.56.dylib
  Referenced from: /Applications/DeaDBeeF.app/Contents/PlugIns/libavcodec.dylib
  Reason: image not found
plugin libavcodec.dylib not found or failed to load
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/libavformat.dylib
dlopen error: dlopen(/Applications/DeaDBeeF.app/Contents/PlugIns/libavformat.dylib, 2): Library not loaded: /Users/waker/Downloads/ffmpeg-4.4/build/x86_64/lib/libavcodec.58.dylib
  Referenced from: /Applications/DeaDBeeF.app/Contents/PlugIns/libavformat.dylib
  Reason: image not found
plugin libavformat.dylib not found or failed to load
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/libavutil.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/libflaclib.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/libjansson.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/liboggedit.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/libogglib.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/libopusfile.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/libopuslib.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/libvorbislib.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/libwavpacklib.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/m3u.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/medialib.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/mms.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/mp3.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/musepack.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/opus.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/psf.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/rg_scanner.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/sid.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/sndfile.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/supereq.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/tta.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/vfs_curl.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/vfs_zip.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/vorbis.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/vtx.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/wavpack.dylib
loading plugin /Applications/DeaDBeeF.app/Contents/PlugIns/wma.dylib
loading plugins from /Users/mac/Library/Application Support/Deadbeef/Plugins
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin Album Artwork
starting plugin Converter
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Soundtouch
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin Media Library
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin Opus player
starting plugin PSF player using Audio Overload SDK
starting plugin ReplayGain Scanner
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WMA player
starting plugin stdio vfs
starting plugin Cocoa UI
starting plugin CoreAudio
starting plugin Null output plugin
selected output plugin: CoreAudio
resume: track 0 pos 104.025833 playlist 0
ERROR: could not load: /Users/mac/Music/Tianliangui RM.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190408 020700.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190416 095342.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190517 012012.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190517 012144.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190517 012224.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190517 012446.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190517 012558.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190517 012739.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190517 013026.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190517 013053.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190517 013237.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190517 013328.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190616 220851.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190616 220906.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190826 202330.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190826 202440.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190826 202714.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190826 232416.m4a
ERROR: could not load: /Users/mac/Music/iTunes/iTunes Media/Voice Memos/20190826 232438.m4a

**Comment by Alexey-Yakovenko** [comment]
It pops up because it attempts to load some m4a files which it can't open.
My guess is that you have medialibrary enabled, which is scanning your music folders, and fails to load some of the track.
I suggest to disable medialibrary, since it's not yet in a fully usable state.
The easiest way is to edit the file `~/Library/Preferences/deadbeef/config`, and delete the entries with "medialib" in them.

**Comment by Alexey-Yakovenko** [comment]
also, it seems that you're running a slightly out of date build, which has issue with ffmpeg plugin -- I recommend to update to the latest master.

**Comment by Alexey-Yakovenko** [comment]
FYI: I disabled the medialib UI and the plugin on master branch, so this problem should not occur anymore

**Comment by marcustone** [comment]
It could possibly be plugin issue, since I did follow strictly to delete one line with medialib keyword, but the log window keeps popping up.
How can I get latest master version of Deadbeaf?
Or could I try nightly build?

**Comment by Alexey-Yakovenko** [comment]
Yes, this is the "nightly" build.

**Comment by Alexey-Yakovenko** [comment]
although you still need to wait a little bit until it finishes building. you can track the build here:
https://github.com/DeaDBeeF-Player/deadbeef/runs/3329367245?check_suite_focus=true

**Comment by marcustone** [comment]
Oh! Great stuff, is there a link for **master build**?

I see build #278, 
osx: jansson dependency fix DeaDBeeF Build #278
but where can I download #277? the filename ends with .app or .dmg?

**Comment by Alexey-Yakovenko** [comment]
there's no dmg, only zip.
You can always find it at the same URL here: https://sourceforge.net/projects/deadbeef/files/travis/osx/master/deadbeef-devel-osx-x86_64.zip/download

**Comment by br3eze** [comment]
HOW to just permanently HIDE this stupid log window? )
We don't care about errors, player works quite fine. It shows up EVERY autostart!  How to disable it completely?
Thanks )
