### ISSUE TITLE
The media library feature is not working in latest version

### ISSUE THREAD

**Issue by marcustone** [DeaDBeeF-Player/deadbeef#2650]
### Steps to reproduce the problem
Enable media library in preference, relaunch Deabbeef

### What's going on? Describe the problem in as much detail as possible.
The media library feature is not working in latest version

### Information about the software:
Version 1.0 (db3519e)

Deadbeef version:
OS: 10.14 Mojave

**Comment by Alexey-Yakovenko** [comment]
Not supposed to work yet. It's an unfinished/unreleased feature that's being worked on. Please ignore its presence in the preferences window in the meantime.

**Comment by 0spinboson** [comment]
so this is a different / separate effort? https://github.com/sgomin/ddb_medialib

**Comment by Oleksiy-Yakovenko** [comment]
Yeah, this is some other project, not from the "core deadbeef devs".
