### ISSUE TITLE
GTK plugins fail to connect to dependencies

### ISSUE THREAD

**Issue by Tyrn** [DeaDBeeF-Player/deadbeef#2651]
Hi,

When I'm trying to use a `*.cue` file (unsuccessfully), I'm getting the following log:

...
plugin Converter GTK3 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK3 failed to connect to dependencies, deactivated.
plugin Shellexec GTK3 UI failed to connect to dependencies, deactivated.

I checked the Deadbeef project README file, the runtime dependencies section; looks like I have all of them. Still, something may be missing, as I use KDE.

Yes, I know this is a question asked before; unfortunately, I did not find anything useful.

**Comment by Alexey-Yakovenko** [comment]
the errors you posted usually mean that you're running GTK2 UI, therefor GTK3 plugins can't connect to it and get deactivated.
It's not a real error - can be ignored.

I can't find any actionable question or a problem in your message, therefore closing.
