### ISSUE TITLE
deadbeef --version parses two different echoes into the terminal

### ISSUE THREAD

**Issue by stefson** [DeaDBeeF-Player/deadbeef#2654]
deadbeef --version shows: 

```
starting deadbeef 1.8.8
DeaDBeeF 1.8.8 Copyright © 2009-2021 Alexey Yakovenko
```

Deadbeef version: 1.8.8
OS: linux-amd64

I think it's common to only echoe the second line into the terminal, since you're not actually starting all the gui and what have you not.

**Comment by Alexey-Yakovenko** [comment]
It's not a bug. Diagnostic messages are supposed to be printed in any case.
But printing the --version text to stderr seems to be a bug.
Changing it to stdout.
