### ISSUE TITLE
German translation not fully complete

### ISSUE THREAD

**Issue by stefson** [DeaDBeeF-Player/deadbeef#2655]
number 4 in the list of entries is in english: 

![missing-locale](https://user-images.githubusercontent.com/14232936/129540898-f04c9a92-76e1-4f83-a59c-c6a573268a24.png)

### Information about the software:

Deadbeef version: 1.8.8
OS: linux-amd64

**Comment by Alexey-Yakovenko** [comment]
This will be updated in the next release, if the translators pick this up.
There's nothing the can be done in the meantime.

**Comment by stefson** [comment]
ah, found it: https://github.com/DeaDBeeF-Player/deadbeef/blob/master/po/de.po#L803

seems its empty, no wonder it defaults back to english! :D 

I can give you a translation if it helps you

**Comment by Alexey-Yakovenko** [comment]
You can submit the translation to transifex, when the new strings are available there.

**Comment by Alexey-Yakovenko** [comment]
I have pulled the latest strings from Transifex, and this text is already translated.
So you don't need to take any action.

**Comment by stefson** [comment]
thanks a lot for the fast fix, but what is this Transifex? Do they use machine learning to interpret? 

this https://github.com/DeaDBeeF-Player/deadbeef/blob/master/po/de.po#L804 says ```"delete into bin"``` , if you compare it with the original string its kind of imprecise

**Comment by Alexey-Yakovenko** [comment]
No, it's human translators (volunteers) who perform the translations.
