### ISSUE TITLE
spinbtn doesn't shows anymore on plugin's configuration

### ISSUE THREAD

**Issue by AsVHEn** [DeaDBeeF-Player/deadbeef#2657]
### Steps to reproduce the problem

 put a spinbtn on .plugin.configdialog (as in https://github.com/kpcee/deadbeef-silence_remover/blob/master/silence_remover.c )

### What's going on? Describe the problem in as much detail as possible.

No configuration options shows (spinbtn or not) on Preferences/Plugins.

### Information about the software:

Deadbeef version: 1.8.8
OS: Debian Testing

**Comment by Alexey-Yakovenko** [comment]
Does the spin button shows up in resampler settings for you, or any other plugin, such as DUMB?
I'm still seeing it:
![image](https://user-images.githubusercontent.com/1895698/130053596-f473bb67-a90c-46c6-83d3-9e07cc349482.png)

**Comment by Alexey-Yakovenko** [comment]
Also, are there any gtk errors in the log? (in console)

**Comment by Alexey-Yakovenko** [comment]
also would help if you state which GTK version is installed, and which GTK (2 or 3) deadbeef is using on your machine.

**Comment by AsVHEn** [comment]
![Captura de pantalla de 2021-08-19 12-47-58](https://user-images.githubusercontent.com/4272271/130056782-f8d27997-3601-43e0-87b0-e448138ff3b7.png)
This what a I see. No errors on console and using GTK3. But now trying replicate without custom plugins it worked, so it's obviously on my side.
Sorry for the inconvenience I should have checked it more before open Issue.
