### ISSUE TITLE
Shuffle Albums: After Play Random, Next skips to first track of album

### ISSUE THREAD

**Issue by rsekman** [DeaDBeeF-Player/deadbeef#2661]
### Steps to reproduce the problem

- Create a playlist with several albums.
- Set shuffle to Albums.
- Play Random (`n`).
- Next (`b`).

### What's going on? Describe the problem in as much detail as possible.

Expected behaviour: playback skips to the next track in the playlist.

Actual behaviour: playback skips to the first track of the album. (Exception: if the randomly chosen track is the first of its album, behaviour is as expected.)

### Information about the software:

Deadbeef version: 1.8.8
OS: Arch

### Comment

This behaviour is not entirely unwelcome for me, as it jury-rigs "random album", which is how "random" works in foobar2000 when it is set to shuffle by album. But it is unintuitive and it would be better to have "random album" as its own purpose-built feature.

**Comment by Alexey-Yakovenko** [comment]
I don't see this is as a bug, but so far, the way you explain it -- such change makes sense, so I'm changing it.
