### ISSUE TITLE
Album shuffle repeats the first album in a shuffle

### ISSUE THREAD

**Issue by rsekman** [DeaDBeeF-Player/deadbeef#2662]
### Steps to reproduce the problem

1. Create a playlist with many albums.
2. Double-click a track in the playlist or use Random track (`n`)
3. Use Next to skip to the last track of the album.
4. Let the track play to to the end; use the Seekbar to avoid listening to the entire track.

Playback now skips to the first track of the album.

5. Repeat steps 3 and 4.

Playback now skips to another, random album, as expected.

Subsequent repetitions of steps 3 and 4 also display expected behaviour.

The issue never occurs if Next is used for the final track of the album.

In the attached screen recording I use hotkeys for Random Track and Next.

https://user-images.githubusercontent.com/29686694/131263949-fe3ba67d-3f5e-4623-9d53-fafe060e00ba.mp4

### Information about the software:

Deadbeef version: `6e20e7f38`
OS: Arch

**Comment by Alexey-Yakovenko** [comment]
I think I have seen this (or similar) issue as well, thanks for the detailed explanation and a video. I'll fix it as soon as I can.

**Comment by Alexey-Yakovenko** [comment]
hmm strangely enough, I can't reproduce the issue even after trying ~10 times.

**Comment by Alexey-Yakovenko** [comment]
https://user-images.githubusercontent.com/1895698/131552453-5a172851-d7db-45e7-a672-c9ea4738374c.mov

**Comment by Alexey-Yakovenko** [comment]
The problem is not reproducible with GTKUI on mac either. Booting into linux now

**Comment by Alexey-Yakovenko** [comment]
Couldn't reproduce on linux either. Do you think there's any more information you could provide that could be useful?
BTW does the problem happen every time for you, or only "once in a while"?

**Comment by Alexey-Yakovenko** [comment]
https://user-images.githubusercontent.com/1895698/131553875-f21d83a3-5ce9-4b05-b10a-de9191888dd3.mov

**Comment by rsekman** [comment]
> Couldn't reproduce on linux either. Do you think there's any more information you could provide that could be useful?
> BTW does the problem happen every time for you, or only "once in a while"?

Ah, I think I figured it out. What is Repeat set to for you? I think the bug occurs  when Repeat is set to None, but not when it is set to Off.

https://user-images.githubusercontent.com/29686694/131555146-e6e779dd-3300-4b93-ba16-abb216d2acd1.mp4

It happens consistently for me when Repeat is set to None, even in playlists with hundreds of albums.

Thank you for taking the time and going to the effort of trying to reproduce the bug so soon!

**Comment by Alexey-Yakovenko** [comment]
Confirmed. With repeat=off happens every time, on any platform.

**Comment by Alexey-Yakovenko** [comment]
I applied the fix, and it seems to work. The code that I removed seems to have been necessary in the past, but it seems it's not needed anymore, and works correctly without it.

**Comment by rsekman** [comment]
I'm glad we were able to figure this one out; again, thanks a lot!
