### ISSUE TITLE
Pitch is shifted when playing through an external sound card on macOS

### ISSUE THREAD

**Issue by peczony** [DeaDBeeF-Player/deadbeef#2663]
When files are playing through an external sound card on macOS, pitch is shifted. Everything is fine in the other apps/players, see attached audio when I first play a file in Cog, then in Deadbeef.

https://mega.nz/file/1FFUgRCA#PbI3V_u_wOnu4dg7UyOQwudr1jYu_aeRIX1o-EFvPDg

Everything is also fine when playing through macbook speakers or headphone port.

No DSPs are enabled except the default SuperEQ in passthrough mode (problem doesn't go away when I turn it off)

Deadbeef version: Version 1.0 (5ea94be)
OS: Big Sur 11.5

**Comment by Alexey-Yakovenko** [comment]
If I read you correctly, and you really don't have any other DSPs except the SuperEQ -- that's the reason why resampling doesn't occur, and you get the output played at a wrong samplerate. Restore the resampler to the default state, and it will work as it was designed to work.
It needs to have Autodetect checkbox enabled.

**Comment by Alexey-Yakovenko** [comment]
If you don't want to use Deadbeef's resampler -- you can use built-in CoreAudio resampler, or even tell CoreAudio to use the soundcard's native samplerate (if it supports it), by playing with the settings in the Sound tab.
Basically, you'd want to disable the override.
![image](https://user-images.githubusercontent.com/1895698/131550195-0bf2111e-dd30-4db8-909e-1ef3ba212e7e.png)

**Comment by peczony** [comment]
Sorry, you are right. I must have deleted Resample DSP and forgotten about it. I returned the resampler (also had to tick “Autodetect sample rate from outputdevice”) and everything is OK now.

Btw if I understand it correctly, there is no «Reset to defaults» button in the DSP menu, it might be helpful.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/3784544/131550279-62588e6b-47b3-408f-a494-85543f33d468.png">

**Comment by Alexey-Yakovenko** [comment]
Yes, I agree a reset button would be nice. It's on my radar, but I'm too busy working on other things for now.
