### ISSUE TITLE
GTK override playlist text color incorrect

### ISSUE THREAD

**Issue by LisandraBrave** [DeaDBeeF-Player/deadbeef#2670]
### What's going on? Describe the problem in as much detail as possible.
With playlist GTK override enabled, successive entries are in a slow blue gradient, irrespective of color choices.

### Steps to reproduce the problem
Turn on GTK override, probably

### Information about the software:

Deadbeef version: 1.8.8
OS: Fedora 34

![image](https://user-images.githubusercontent.com/8226662/132291263-40c9b935-7b87-4231-af1a-f9d5d62e62b0.png)
![image](https://user-images.githubusercontent.com/8226662/132291312-50300585-f61a-426f-bb49-f5aed67d60ac.png)

Tested without any external plugins and the behavior is the same
Issue not present in 1.8.7

**Comment by Alexey-Yakovenko** [comment]
This does look wrong indeed. Can I ask you to look into `~/.config/deadbeef/config` file, and find the respective color entries, to inspect how they look there?

**Comment by Alexey-Yakovenko** [comment]
I can't reproduce this, but there were changes introduced in 1.8.8 which may have affected it this way.
By any change did you use the new `$rgb` or any other color-modifying title formatting such as `<<<` or `>>>`?

**Comment by LisandraBrave** [comment]
![image](https://user-images.githubusercontent.com/8226662/132742674-28f49cd2-88ae-4bec-82be-a23f21977dc0.png)
Nothing out of the ordinary in the config, and I haven't changed any title formatting. Looking at the column formatting in playlist view, if it's set to have a specific color *there* it functions properly, just not with the global override.
![image](https://user-images.githubusercontent.com/8226662/132743026-28078358-5fdb-41a8-ae66-fd250ef68203.png)

**Comment by Alexey-Yakovenko** [comment]
thanks, I'll keep looking what may have caused it. I'm quite sure it's the new $rgb and brightness change title formatting code, smh.

**Comment by Alexey-Yakovenko** [comment]
@LisandraBrave is there any chance for you to post the colors from the config as text, so I don't have to re-type them from your screenshot? :)

**Comment by Alexey-Yakovenko** [comment]
I think I fixed this, could you please double check that it's not occurring anymore?
