### ISSUE TITLE
Deadbeef crashes since kernel 5.14

### ISSUE THREAD

**Issue by sushi2503** [DeaDBeeF-Player/deadbeef#2674]
### Steps to reproduce the problem

Launch Deadbeef and start to play a file or en url radio and it freezes completely.

### What's going on? Describe the problem in as much detail as possible.

Since kernel 5.14 Deadbeef tries to play the file or connect to the url radio it freezes without any error in logs but with a kernel oops in journalctl (see below). It's not the case with all previous kernels and on my two laptops with integrated sound cards. The crashes are only on my destop computer but with the same OS as the two laptops :

### journalctl -f:

BUG: kernel NULL pointer dereference, address: 0000000000000000
sep 15 13:02:10 Cockpit kernel: #PF: supervisor read access in kernel mode
sep 15 13:02:10 Cockpit kernel: #PF: error_code(0x0000) - not-present page
sep 15 13:02:10 Cockpit kernel: PGD 0 P4D 0 
sep 15 13:02:10 Cockpit kernel: Oops: 0000 [#1] PREEMPT SMP NOPTI
sep 15 13:02:10 Cockpit kernel: CPU: 1 PID: 1293 Comm: deadbeef-stream Not tainted 5.14.3-arch1-1 #1 7079317413bd7f23458a4f12074dee48a4433dad
sep 15 13:02:10 Cockpit kernel: Hardware name: Gigabyte Technology Co., Ltd. GA-MA770-UD3/GA-MA770-UD3, BIOS FKb 07/08/2010
sep 15 13:02:10 Cockpit kernel: RIP: 0010:snd_dma_buffer_mmap+0x5/0x40 [snd_pcm]
sep 15 13:02:10 Cockpit kernel: Code: 83 fa 06 77 1c 48 8b 04 c5 60 85 15 c1 48 85 c0 74 0e 48 8b 40 08 48 85 c0 74 05 e9 b5 c0 ca f0 c3 0f 0b c3 90 0f 1f 44 00 00 <48> 63 07 8d 50 ff 83 fa 06 77 1b 48 8b 04 c5 60 85 15 c1 48 85 c0
sep 15 13:02:10 Cockpit kernel: RSP: 0018:ffffa1e340d23d38 EFLAGS: 00010246
sep 15 13:02:10 Cockpit kernel: RAX: ffff8b52dc988800 RBX: ffff8b52c24be400 RCX: 0000000000000000
sep 15 13:02:10 Cockpit kernel: RDX: 00000000001af000 RSI: ffff8b52e354fed8 RDI: 0000000000000000
sep 15 13:02:10 Cockpit kernel: RBP: 00007fc3a739e000 R08: 00000000040400fb R09: 0000000000001000
sep 15 13:02:10 Cockpit kernel: R10: ffff8b52e023f258 R11: 00007fc3a9e04000 R12: ffff8b52c2539b20
sep 15 13:02:10 Cockpit kernel: R13: 0000000000000008 R14: ffff8b52e354fed8 R15: ffff8b52c1e26a40
sep 15 13:02:10 Cockpit kernel: FS:  00007fc38ffff640(0000) GS:ffff8b53e7c40000(0000) knlGS:0000000000000000
sep 15 13:02:10 Cockpit kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
sep 15 13:02:10 Cockpit kernel: CR2: 0000000000000000 CR3: 00000001234f6000 CR4: 00000000000006e0
sep 15 13:02:10 Cockpit kernel: Call Trace:
sep 15 13:02:10 Cockpit kernel:  snd_pcm_mmap_data+0x127/0x140 [snd_pcm 52883601536316a338aa37d982c037da02ab8be0]
sep 15 13:02:10 Cockpit kernel:  mmap_region+0x415/0x690
sep 15 13:02:10 Cockpit kernel:  do_mmap+0x35f/0x550
sep 15 13:02:10 Cockpit kernel:  ? security_mmap_file+0x81/0xb0
sep 15 13:02:10 Cockpit kernel:  vm_mmap_pgoff+0xe2/0x190
sep 15 13:02:10 Cockpit kernel:  ? syscall_exit_to_user_mode+0x23/0x40
sep 15 13:02:10 Cockpit kernel:  ksys_mmap_pgoff+0x1c8/0x230
sep 15 13:02:10 Cockpit kernel:  do_syscall_64+0x5c/0x80
sep 15 13:02:10 Cockpit kernel:  ? do_syscall_64+0x69/0x80
sep 15 13:02:10 Cockpit kernel:  ? do_syscall_64+0x69/0x80
sep 15 13:02:10 Cockpit kernel:  ? syscall_exit_to_user_mode+0x23/0x40
sep 15 13:02:10 Cockpit kernel:  ? do_syscall_64+0x69/0x80
sep 15 13:02:10 Cockpit kernel:  ? do_syscall_64+0x69/0x80
sep 15 13:02:10 Cockpit kernel:  entry_SYSCALL_64_after_hwframe+0x44/0xae
sep 15 13:02:10 Cockpit kernel: RIP: 0033:0x7fc3a9b7b336
sep 15 13:02:10 Cockpit kernel: Code: 01 00 66 90 f3 0f 1e fa 41 f7 c1 ff 0f 00 00 75 2b 55 48 89 fd 53 89 cb 48 85 ff 74 37 41 89 da 48 89 ef b8 09 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 62 5b 5d c3 0f 1f 80 00 00 00 00 48 8b 05 01
sep 15 13:02:10 Cockpit kernel: RSP: 002b:00007fc38fffe378 EFLAGS: 00000246 ORIG_RAX: 0000000000000009
sep 15 13:02:10 Cockpit kernel: RAX: ffffffffffffffda RBX: 0000000000000001 RCX: 00007fc3a9b7b336
sep 15 13:02:10 Cockpit kernel: RDX: 0000000000000003 RSI: 0000000000001000 RDI: 0000000000000000
sep 15 13:02:10 Cockpit kernel: RBP: 0000000000000000 R08: 0000000000000010 R09: 0000000000000000
sep 15 13:02:10 Cockpit kernel: R10: 0000000000000001 R11: 0000000000000246 R12: 00007fc37404e500
sep 15 13:02:10 Cockpit kernel: R13: 00000000fffffffe R14: 0000000000000001 R15: 0000000000000000
sep 15 13:02:10 Cockpit kernel: Modules linked in: 8021q garp mrp stp llc hid_logitech_hidpp ip6t_REJECT nf_reject_ipv6 xt_hl ip6t_rt ipt_REJECT nf_reject_ipv4 xt_LOG nf_log_syslog xt_limit xt_addrtype xt_tcpudp snd_hda_codec_hdmi hid_logitech_dj snd_hda_intel snd_intel_dspcfg xt_conntrack snd_intel_sdw_acpi snd_hdsp snd_hda_codec snd_rawmidi snd_hda_core snd_seq_device snd_hwdep ip6table_filter snd_pcm r8169 ip6_tables snd_timer radeon usbhid realtek snd nf_conntrack_netbios_ns mdio_devres nf_conntrack_broadcast edac_mce_amd libphy soundcore nf_nat_ftp nf_nat acpi_cpufreq nf_conntrack_ftp nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c iptable_filter it87 hwmon_vid fuse bpf_preload ip_tables x_tables ext4 crc32c_generic crc16 mbcache jbd2 ata_generic pata_acpi pata_atiixp sr_mod cdrom amdgpu drm_ttm_helper ttm agpgart gpu_sched i2c_algo_bit drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops cec drm
sep 15 13:02:10 Cockpit kernel: CR2: 0000000000000000
sep 15 13:02:10 Cockpit kernel: ---[ end trace db72d421f9015bc8 ]---
sep 15 13:02:10 Cockpit kernel: RIP: 0010:snd_dma_buffer_mmap+0x5/0x40 [snd_pcm]
sep 15 13:02:10 Cockpit kernel: Code: 83 fa 06 77 1c 48 8b 04 c5 60 85 15 c1 48 85 c0 74 0e 48 8b 40 08 48 85 c0 74 05 e9 b5 c0 ca f0 c3 0f 0b c3 90 0f 1f 44 00 00 <48> 63 07 8d 50 ff 83 fa 06 77 1b 48 8b 04 c5 60 85 15 c1 48 85 c0
sep 15 13:02:10 Cockpit kernel: RSP: 0018:ffffa1e340d23d38 EFLAGS: 00010246
sep 15 13:02:10 Cockpit kernel: RAX: ffff8b52dc988800 RBX: ffff8b52c24be400 RCX: 0000000000000000
sep 15 13:02:10 Cockpit kernel: RDX: 00000000001af000 RSI: ffff8b52e354fed8 RDI: 0000000000000000
sep 15 13:02:10 Cockpit kernel: RBP: 00007fc3a739e000 R08: 00000000040400fb R09: 0000000000001000
sep 15 13:02:10 Cockpit kernel: R10: ffff8b52e023f258 R11: 00007fc3a9e04000 R12: ffff8b52c2539b20
sep 15 13:02:10 Cockpit kernel: R13: 0000000000000008 R14: ffff8b52e354fed8 R15: ffff8b52c1e26a40
sep 15 13:02:10 Cockpit kernel: FS:  00007fc38ffff640(0000) GS:ffff8b53e7c40000(0000) knlGS:0000000000000000
sep 15 13:02:10 Cockpit kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
sep 15 13:02:10 Cockpit kernel: CR2: 0000000000000000 CR3: 00000001234f6000 CR4: 00000000000006e0

### Information about the software:

Deadbeef version: 1.8.8
OS: Archlinux up to date.

###  Hardware information:

Sound card RME 9632

cat /proc/asound/pcm : 

00-00: RME Hammerfall HDSP 9632 : RME Hammerfall HDSP 9632 : playback 1 : capture 1
01-03: HDMI 0 : HDMI 0 : playback 1
01-07: HDMI 1 : HDMI 1 : playback 1
01-08: HDMI 2 : HDMI 2 : playback 1
01-09: HDMI 3 : HDMI 3 : playback 1
01-10: HDMI 4 : HDMI 4 : playback 1
01-11: HDMI 5 : HDMI 5 : playback 1

lspci :

00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD/ATI] RX780/RX790 Host Bridge
00:02.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RX780/RD790 PCI to PCI bridge (external gfx0 port A)
00:0a.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD790 PCI to PCI bridge (PCI express gpp port F)
00:11.0 SATA controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 SATA Controller [AHCI mode]
00:12.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
00:12.1 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0 USB OHCI1 Controller
00:12.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller
00:13.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
00:13.1 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0 USB OHCI1 Controller
00:13.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 SMBus Controller (rev 3c)
00:14.1 IDE interface: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 IDE Controller
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 LPC host controller
00:14.4 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 PCI to PCI Bridge
00:14.5 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI2 Controller
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor HyperTransport Configuration
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Address Map
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor DRAM Controller
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Miscellaneous Control
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Link Control
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cape Verde PRO [Radeon HD 7750/8740 / R7 250E]
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Oland/Hainan/Cape Verde/Pitcairn HDMI Audio [Radeon HD 7000 Series]
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 02)
03:06.0 Multimedia audio controller: Xilinx Corporation RME Hammerfall DSP (rev 9a)

**Comment by Alexey-Yakovenko** [comment]
Seems like a kernel bug to me too.

**Comment by sushi2503** [comment]
Thanks for your prompt answer.

Yes for me it sounds like a kernel bug too and I already tried 5.14.6 without success. I'm gona report it @ arch and see...

Cheers
