### ISSUE TITLE
Deadbeef GLib-CRITICAL

### ISSUE THREAD

**Issue by sushi2503** [DeaDBeeF-Player/deadbeef#2678]
### Steps to reproduce the problem
Just launch Deadbeef.

### What's going on? Describe the problem in as much detail as possible.
When launching the player without playing any file this warning appear at the end of the start log : 

(deadbeef:1391): GLib-CRITICAL **: 07:56:16.964: Source ID 19 was not found when attempting to remove it

And if I stop playing a file and then start to play another one few minutes later the same warning appear again but with a different Source ID like : 

(deadbeef:1391): GLib-CRITICAL **: 08:53:06.352: Source ID 3699 was not found when attempting to remove it

I have this warning on my desktop computer and one of my two laptops but not on my second laptop. They have all the same desktop environment (xfce4) and the same OS.

### Information about the software:

Deadbeef version: 1.8.8-2
OS: Archlinux up to date
Alsa only on all machines

Let me know which infos you need for further investigation.

Thanks.

**Comment by Alexey-Yakovenko** [comment]
> Let me know which infos you need for further investigation.

* You mentioned that on one machine it's not happening. What's different on that machine?
* The full Deadbeef startup log would help a lot (plugin list)
* GTK version from the 2 different machines (one that has the problem, and one that doesn't)

If none of this helps - I may ask for some other things.

**Comment by sushi2503** [comment]
There is no difference about the OS between the two machines, it's only an hardware difference. On my affected desktop I have an PCI RME HDSP 9632 sound card and an integrate sound card on the non affected laptop and also an integrate sound card on the affected laptop.

The full startup log of the affected desktop :

starting deadbeef 1.8.8
server_start
INFO: unlink socket: Aucun fichier ou dossier de ce type
searching for GUI plugins in /home/pilote/.local/lib64/deadbeef
searching for GUI plugins in /home/pilote/.local/lib/deadbeef
searching for GUI plugins in /usr/lib/deadbeef
load_plugin_dir /usr/lib/deadbeef: scandir found 57 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /usr/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/pilote/.local/lib64/deadbeef
loading plugins from /home/pilote/.local/lib/deadbeef
loading plugins from /usr/lib/deadbeef
load_plugin_dir /usr/lib/deadbeef: scandir found 57 files
loading plugin /usr/lib/deadbeef/aac.so
loading plugin /usr/lib/deadbeef/adplug.so
loading plugin /usr/lib/deadbeef/alac.so
loading plugin /usr/lib/deadbeef/alsa.so
loading plugin /usr/lib/deadbeef/artwork.so
loading plugin /usr/lib/deadbeef/cdda.so
loading plugin /usr/lib/deadbeef/converter.so
loading plugin /usr/lib/deadbeef/converter_gtk2.so
loading plugin /usr/lib/deadbeef/converter_gtk3.so
loading plugin /usr/lib/deadbeef/dca.so
loading plugin /usr/lib/deadbeef/ddb_dumb.so
loading plugin /usr/lib/deadbeef/ddb_misc_waveform_GTK3.so
loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib/deadbeef/ddb_shn.so
loading plugin /usr/lib/deadbeef/ddb_soundtouch.so
loading plugin /usr/lib/deadbeef/ddb_vis_musical_spectrum_GTK3.so
loading plugin /usr/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/lib/deadbeef/ffap.so
loading plugin /usr/lib/deadbeef/ffmpeg.so
loading plugin /usr/lib/deadbeef/flac.so
loading plugin /usr/lib/deadbeef/gme.so
loading plugin /usr/lib/deadbeef/hotkeys.so
loading plugin /usr/lib/deadbeef/in_sc68.so
loading plugin /usr/lib/deadbeef/lastfm.so
loading plugin /usr/lib/deadbeef/m3u.so
loading plugin /usr/lib/deadbeef/mms.so
loading plugin /usr/lib/deadbeef/mp3.so
loading plugin /usr/lib/deadbeef/musepack.so
loading plugin /usr/lib/deadbeef/notify.so
loading plugin /usr/lib/deadbeef/nullout.so
loading plugin /usr/lib/deadbeef/opus.so
loading plugin /usr/lib/deadbeef/oss.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /usr/lib/deadbeef/psf.so
loading plugin /usr/lib/deadbeef/pulse.so
loading plugin /usr/lib/deadbeef/rg_scanner.so
loading plugin /usr/lib/deadbeef/shellexec.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk2.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib/deadbeef/sid.so
loading plugin /usr/lib/deadbeef/sndfile.so
loading plugin /usr/lib/deadbeef/supereq.so
loading plugin /usr/lib/deadbeef/tta.so
loading plugin /usr/lib/deadbeef/vfs_curl.so
loading plugin /usr/lib/deadbeef/vfs_zip.so
loading plugin /usr/lib/deadbeef/vorbis.so
loading plugin /usr/lib/deadbeef/vtx.so
loading plugin /usr/lib/deadbeef/wavpack.so
loading plugin /usr/lib/deadbeef/wildmidi.so
loading plugin /usr/lib/deadbeef/wma.so
starting plugin GTK3 user interface
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter GTK2 UI
starting plugin Converter GTK3 UI
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Waveform Seekbar
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Soundtouch
starting plugin Musical Spectrum
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin OSD Notify
starting plugin Null output plugin
starting plugin Opus player
starting plugin OSS output plugin
starting plugin Playlist browser GTK2
starting plugin Playlist browser GTK3
starting plugin PSF player using Audio Overload SDK
starting plugin PulseAudio output plugin
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec GTK2 UI
starting plugin Shellexec GTK3 UI
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
starting plugin FFMPEG audio player
selected output plugin: ALSA output plugin
INFO: from file /home/pilote/.config/deadbeef/playlists/0.dbpl
INFO: from file /home/pilote/.config/deadbeef/playlists/1.dbpl
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.24.30

(deadbeef:1355): GLib-CRITICAL **: 20:24:17.171: Source ID 19 was not found when attempting to remove it

GTK3 version on both machines (included on the affected laptop) : 1:3.24.30+62+g8d04980f38-2

I'm asking myself to try to copy the settings from the non affected laptop to the affected desktop to see if the problem comes from the settings ?

**Comment by Alexey-Yakovenko** [comment]
Ok I see you have a few extra plugins installed.
Can you remove them and see if this helps?

ddb_vis_musical_spectrum_GTK3, ddb_misc_waveform_GTK3

**Comment by sushi2503** [comment]
Ok, you mean remove then just from Deadbeef's interface or remove them completely from the os ?

If you need, I have the settings files of the tree machines.

**Comment by Alexey-Yakovenko** [comment]
at the very least from the interface

**Comment by sushi2503** [comment]
Bingo ! It's the waveform seekbar (ddb_misc_waveform_GTK3). I had just to take them of the interface.

The strange thing is that I have the ddb_misc_waveform_GTK3 plugins on all machines, the affected desktop, the non affected laptop and the affected laptop.

What about trying to copy the ddb_misc_waveform_GTK3.so from the non affected laptop to the affected desktop ?

**Comment by Alexey-Yakovenko** [comment]
Well, what we found is that this error is caused by a 3rd party plugin. You can report the bug to the plugin dev here:
https://github.com/cboxdoerfer/ddb_waveform_seekbar/issues

**Comment by sushi2503** [comment]
Thanks a lot ! 

I could solve the problem by just copying the file ddb_misc_waveform_GTK3.so from the non affected laptop to the affected desktop and no GLib-CRITICAL anymore.

I would take the opportunity to congratulate you and the contributors for that great player which I use every day since almost 10 years with the same pleasure. A master piece of an software.

**Comment by Alexey-Yakovenko** [comment]
❤️
