### ISSUE TITLE
Methods to execute something on song change

### ISSUE THREAD

**Issue by G2G2G2G** [DeaDBeeF-Player/deadbeef#2682]
I'm trying to read the song playing (which is easy with `deadbeef --nowplaying-tf "%artist% - %title%"`) 

However there's no sense in requesting that constantly, is there a way to execute a shell script, python script, executable program or anything like that whenever the song changes?

**Comment by Alexey-Yakovenko** [comment]
There's no "built-in" way of doing this, you would need to develop a plugin to run the scripts at the moments you want.
