### ISSUE TITLE
Deadbeef not launching under wayland (artwork.so was the issue)

### ISSUE THREAD

**Issue by Roddyboii** [DeaDBeeF-Player/deadbeef#2694]
### Steps to reproduce the problem
1. Launch deadbeef under Wayland (I'm using KDE but I've also tried GNOME)
2. Nothing happens afterward.

### What's going on? Describe the problem in as much detail as possible.
Here's what the terminal says:
https://pastebin.com/yfgdDLVx

```
starting plugin Album Artwork
pthread_setschedprio failed: Invalid argument
plugin Album Artwork failed to start, deactivated.
free(): double free detected in tcache 2
[1]    428707 abort (core dumped)  deadbeef
```

Removing artwork.so from /usr/lib/deadbeef works but there's no album cover anymore.
I found out that this only happens when I add the album cover in my layout.

### Information about the software:
Deadbeef version: both the latest deadbeef stable (1.8.8-2) and the latest deadbeef-devel
OS: Arch Linux

**Comment by Roddyboii** [comment]
Okay update. I tried this again on a clean arch install. It works fine.

It stopped working again after I installed lib32-gst-plugins-bad, lib32-gst-plugins-ugly, and lib32-lilbffmpeg (I needed the codecs for a game running on wine), same artwork.so issue.

**Comment by Alexey-Yakovenko** [comment]
@Roddyboii Recently I replaced the artwork plugin with the new version which doesn't use pthread at all.
I suppose, this bug is not relevant any more. But it would still be nice if you could try it out and see if the problem is really solved.
