### ISSUE TITLE
Tracks load out of order if drag to dock icon

### ISSUE THREAD

**Issue by waaykool** [DeaDBeeF-Player/deadbeef#2696]
### Steps to reproduce the problem

Select all numbered audio tracks inside of a folder, drag and drop into Main window or into Dock Icon.

### What's going on? Describe the problem in as much detail as possible.

If numbered tracks are dragged into main window, they cue up in order (eg: track 01, 02, 03...), as expexted.

If same numbered tracks are dragged into Dock icon instead of main window, tracks cue up with track 02 first (eg: 02, 03, 04...) with track 01 randomly placed into the middle or at the end of playlist.

### Information about the software:

Deadbeef versions: (6924215) & (f66b1cb)
OS: Mac OSX 10.14.6

**Comment by Alexey-Yakovenko** [comment]
For me, it's even worse.
I drag tracks 01..10, and the 01,09 and 10 are not added at all (via dock).
So at least I confirm there's a bug :)

**Comment by Alexey-Yakovenko** [comment]
So.. I fixed the "dropped" files, that wasn't hard.

The sorting order -- it's not caused by deadbeef, the files are coming in some weird order from the OS / finder.
I added alphabetical sort on top, let's see how that goes.

**Comment by waaykool** [comment]
The latest version (4f2b076), seems to have fixed this issue for me. Thanks!!
