### ISSUE TITLE
Albums with more than 9 discs are out of order if the filename has no leading zero

### ISSUE THREAD

**Issue by BatteryPine** [DeaDBeeF-Player/deadbeef#2709]
### Steps to reproduce the problem
Drag a folder for an album with 10 or more discs into the playlist.
### What's going on? Describe the problem in as much detail as possible.
Whenever I drag a folder into the playlist panel or load a folder through the file browser plug-in, the disc order will be out of order for the playlist if 1 to 9 are prefixed in the filename without any leading zeros.
The top is how the playlist looks if the filename starts with 1-, 2-, 3- etc. The bottom is how the playlist looks if the filename starts with 01-, 02-, 03- etc.
![1](https://user-images.githubusercontent.com/22846912/143731255-42303984-e0d7-495d-84a8-852189887e43.png)
### Information about the software:

Deadbeef version: 1.8.8
OS: Pop!_OS

**Comment by Alexey-Yakovenko** [comment]
deadbeef doesn't automatically sort playlists by tags when adding files.
The files are coming in arbitrary order, in which a file manager arranged them.
Usually the order is alphabetically sorted by filenames.
So to fix this problem - you would need to right click / sort / ...

**Comment by Alexey-Yakovenko** [comment]
There's also a checkbox in "Autosort playlist" if you right click on the playlist columns, this would make the playlist remember its last sort option, and re-apply it every time files are added to the playlist.

**Comment by Alexey-Yakovenko** [comment]
I just checked this feature, and since it was a little obscure - I added a few improvements.
* It will now remember the sort settings even when sorting empty playlist
* The option is now also available on mac
* The menu item got a tooltip explaining what it does:
![image](https://user-images.githubusercontent.com/1895698/143763307-98d02ac1-a4d3-4e2f-98a2-3b48fe97ae6d.png)
