### ISSUE TITLE
GTK2 gui fails to load

### ISSUE THREAD

**Issue by TwoFinger** [DeaDBeeF-Player/deadbeef#2711]
### Steps to reproduce the problem
Have GTK2 selected in the GUI plugin dropdown list in the Settings -> GUI/Misc -> Player tab.
Start deadbeef.

### What's going on? Describe the problem in as much detail as possible.
The program starts with the GTK3 gui plugin loaded, not GTK2.

### Information about the software:

Deadbeef version: The latest code from github. Must be a regression in the last couple of days.
OS: Linux

Here's an excerpt from stdout:

```
load_plugin_dir /usr/lib/deadbeef: scandir found 55 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
found selected GUI plugin: GTK2
loading plugin /usr/lib/deadbeef/ddb_gui_GTK2.so
dlopen error: /usr/lib/deadbeef/ddb_gui_GTK2.so: undefined symbol: gtk_menu_popup_at_pointer
trying /usr/lib/deadbeef/ddb_gui_GTK2.fallback.so...
selected GUI plugin not found or failed to load, trying to find another GUI plugin
the plugin not found or failed to load
the plugin not found or failed to load
```

**Comment by Alexey-Yakovenko** [comment]
thanks for noticing :)

**Comment by TwoFinger** [comment]
@Alexey-Yakovenko wow, that was fast! Thank you, man!
