### ISSUE TITLE
Files with non-ascii characters are not opening from file manager on Windows

### ISSUE THREAD

**Issue by landroid570** [DeaDBeeF-Player/deadbeef#2717]
In DeaDBeeF version 1.8.8, if there are Russian characters in the path or the name of audio files, when opening by double-clicking or launching from the command line, or when viewing through F3 in the file manager, DeaDBeeF gives an error "failed to add file or folder". If there are no Russian characters in the path or the name of the audio files, everything works fine. How can I fix this?
The same is true in versions starting from 1.8.5. If you open audio files from the player, the Russian letters are displayed correctly in the playlist.
And in the version "DeaDBeeF for Windows 2020-07-06", on the contrary, Russian files are opened from the command line, but in the player itself in the playlist in% filename_ext% Russian characters are not displayed.

OS: Windows 7 or 10 (x64)

**Comment by landroid570** [comment]
![изображение](https://user-images.githubusercontent.com/95489987/145536238-9f726b4d-6b22-4c73-8aa3-c5df18286a40.png)
![изображение](https://user-images.githubusercontent.com/95489987/145536277-c2b3d536-0979-4b7f-85f6-6702a7ab7797.png)
if the file name contains russian characters, then writes "failed to add file or folder"

**Comment by dtantono** [comment]
Yeah, it seems the workaround is I have to click file -> open file -> and select the mp3 file as a workaround which is not normal.
