### ISSUE TITLE
WMA files don't play anymore

### ISSUE THREAD

**Issue by JakeSFR** [DeaDBeeF-Player/deadbeef#2720]
I just upgraded to the latest [2e7cb4201da0d514eec2307a3b933245e0cc615c] official Linux build and:

`ERROR: could not load: /path/to/some.wma`

Btw, with wma.so plugin from 1.8.8 they play just fine.

**Comment by Alexey-Yakovenko** [comment]
I just tried with all WMA files I have in my test files, and all of them still play just fine.
(Although I tried on mac, so I guess I should try the same on linux too)

**Comment by JakeSFR** [comment]
I can't build the whole DB, because I don't have Clang set up, but I managed to rebuild the wma plugin alone from the current sources.
Pristine build - still doesn't work.
With e88a7a5a8a6739505973931adee4af82ef4946cc reverted - works.

Apparently there is some weird difference between Mac and Linux if it comes for that code...

**Comment by Alexey-Yakovenko** [comment]
Confirmed on linux, no wma files could be opened.

**Comment by Alexey-Yakovenko** [comment]
Ahh it worked on mac because it fell back to ffmpeg plugin, which coincidentally can play wma.
Now can reproduce on mac as well.

**Comment by JakeSFR** [comment]
Yeah, that makes sense.

I was surprised that it didn't work for me (wma is on ffmpeg's list), but I just realized that the official build is probably linked against ffmpeg compiled without non-free codecs like asf, aac, etc.

Anyway, thanks for the fix!

**Comment by Alexey-Yakovenko** [comment]
It doesn't have to do with non-free, it's only to save size. there's no need to duplicate the codecs.
(Although I'm surprised that my mac ffmpeg build includes wma, should fix this)
