### ISSUE TITLE
Crash on mp3 file with zero size

### ISSUE THREAD

**Issue by shooreek** [DeaDBeeF-Player/deadbeef#2727]
### Steps to reproduce the problem
* Create zero size file, call it file.mp3
* Add file to playlist
* Double-click -> Deadbeef closes/crashes

Probably this applies to other file types as well.

I somehow managed to get Deadbeef continuously crashing on startup after playing of zero-sized mp3 files, probably it tries to resume playing and crashes each time I start it. I've solved this by removing ~/.config/deadbeef. Whatever it is, it might be bad idea to have such behavior out of the box. Maybe there can be some startup crash detection flag that won't allow Deadbeef to crash on the same file again and again. So we have two bugs in this report 1) Crash on zero size file 2) Continuous startup crash

### Information about the software:

Deadbeef version: 1.8.8 deb package
OS: Kubuntu 18.04

**Comment by Alexey-Yakovenko** [comment]
Thanks for reporting, and the idea to avoid resuming after crash is also great. I fixed and added everything :)
