### ISSUE TITLE
Seek doesn't work for Musepack

### ISSUE THREAD

**Issue by UE2Q** [DeaDBeeF-Player/deadbeef#2731]
Well, the title says it all really. The playback itself works, but when I try to seek - it stops.

Great player otherwise, appreciate your work.

Deadbeef version: 1.8.8
OS: Manjaro Linux

**Comment by Alexey-Yakovenko** [comment]
sorry, github ate my message.

I was asking whether you could provide a sample file :)
On my computer everything works fine.

Also it would be nice to if you post the full deadbeef log (view -> Log in the menu).

**Comment by Alexey-Yakovenko** [comment]
Thanks. Seeking partially works, but there's definitely some strange behavior. I'll investigate.

**Comment by Alexey-Yakovenko** [comment]
Thanks for reporting it. The bug was caused by a recent change, that was intending to fix an undefined behavior compiler warning, but the fix itself was wrong.

**Comment by Alexey-Yakovenko** [comment]
The fix is available on master branch, and will be included in the 1.9beta2 and up.

**Comment by UE2Q** [comment]
Excellent, much obliged.
