### ISSUE TITLE
Some WAV files won't load

### ISSUE THREAD

**Issue by JakeSFR** [DeaDBeeF-Player/deadbeef#2733]
Latest nightly Linux build.

I just noticed this, originally with samples extracted from this soundfont: https://musical-artifacts.com/artifacts/421.
But it's enough to convert (probably) anything to **pcm_s24le** (also _pcm_s64le_ and possibly others, but not _pcm_s32le_):

`ffmpeg -i in.mp3 -acodec pcm_s24le out.wav`

to get:

`ERROR: could not load: /path/to/out.wav`

They play fine in VLC, ffplay and even aplay.
Attaching a sample from the aforementioned soundfont: [1_A2-stereo.wav.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/7927457/1_A2-stereo.wav.zip)

**Comment by Alexey-Yakovenko** [comment]
Reproduced. Surprisingly, only occurs on linux, but not on mac. Probably libsndfile needs an update.
mac build uses 1.0.28, and linux uses 1.0.23.

**Comment by Alexey-Yakovenko** [comment]
Seems like it helped, works for me now.

**Comment by JakeSFR** [comment]
Does it work for you also with the file I attached? Because it doesn't for me, for some reason, neither with other files converted to _pcm_s24le_.
It works if I convert them to mono using ffmpeg's `-ac 1` options, but I just checked and it worked even in 1.8.8.

**Comment by Alexey-Yakovenko** [comment]
hmm no. your file still doesn't work on linux, but the file which I created with your ffmpeg command works fine.
It is stereo, S24.
![image](https://user-images.githubusercontent.com/1895698/150859672-24ce3c5a-1679-44a5-8d43-6316cee2f7ba.png)

**Comment by Alexey-Yakovenko** [comment]
This is the track properties of your file on mac
![image](https://user-images.githubusercontent.com/1895698/150859781-92abd7e9-6321-46d3-aaf7-32f5a34053d7.png)

**Comment by Alexey-Yakovenko** [comment]
Both my and your files work on linux in local build of deadbeef. So I guess there's still something weird with libsndfile build.
I'll try to build it differently (but will have to do it on another day -- out of time for today)

**Comment by JakeSFR** [comment]
Sure, no worries, take your time, thanks!

**Comment by Alexey-Yakovenko** [comment]
The problem is actually quite fancy.
I can't add the files to playlist using portable build, they both fail.
But if they're already in the playlist (added via local build) - they do play fine.

**Comment by JakeSFR** [comment]
Hmm, yeah, or if I change the extension to **.aiff**, then it works too.

**Comment by Alexey-Yakovenko** [comment]
Super strange. I've tried changing the file extension to aiff, and after that I'm able to add file to playlist.
This shouldn't matter at all, since libsndfile is not accessing the filename -- but somehow it matters.
Puzzling.

**Comment by Alexey-Yakovenko** [comment]
So far I'm out of ideas what to try.. libsndfile is not very good at exposing internal details about the error. I'll have to modify it to expose some logging. The only thing I know for sure is that the system-provided library works fine, but not the static one which portable build is using.

**Comment by JakeSFR** [comment]
If I remove the **dca.so** plugin from the plugins dir, it works as well.
So maybe it's something with _libdca_?

**Comment by Alexey-Yakovenko** [comment]
Hmmm I don't know, but that's many suspicious things.
It doesn't explain at all why the exactly the same code in sndfile_init and sndfile_insert causes different result on the same input file / input data.
I can't really give a simple answer, but I highly doubt dca plugin has anything to do with it.

**Comment by Alexey-Yakovenko** [comment]
I tried a few things, and so far the only thing that worked is changing the optimization flag from -O3 to -O0.
The issue doesn't seem to be caused by the build of libsndfile, but it is something within the sndfile deadbeef plugin.
Also the problem doesn't occur even with -O3 if I build with newer version of clang.
I'll keep looking, and maybe will try to upgrade clang in the CI image.

**Comment by Alexey-Yakovenko** [comment]
It seems that some uninitialized memory was the culprit. I'm still puzzled why the static analyzer, address sanitizer and the compiler itself were not able to produce a single warning about it.

**Comment by JakeSFR** [comment]
Confirmed, thanks!
