### ISSUE TITLE
Album art for playlist group could source image file from another directory

### ISSUE THREAD

**Issue by mallniya** [DeaDBeeF-Player/deadbeef#2753]
### Steps to reproduce the problem
Get 2 audio files with image files like cover.jpg (not forgetting to configure album art plugin to source such filename) in different directories, so our filetree looks like this:
```
dir_a/
  audio1.flac
  cover.jpg
dir_b/
  audio2.flac
  cover.jpg
```
all 4 files are not the same.

### What's going on? Describe the problem in as much detail as possible.
It works like expected (showing 2 different images for every track) **except** for cases, when artist and album tags are the same. At first I thought it somehow linked to playlist grouping, but it doesn't seem to be the case, because if one set custom grouping by %title% this behavior would persist. i.e. clicking "Refresh cover art" with different selected track each time causes change of image for both tracks.
Expected behavior is to source image from file's directory when grouping allows to show individual image for this specific grouping case.

And if artist and album collision is a rare concern, then re-issue of album in different year is a more common case, especially in personal collections.

### Information about the software:
Deadbeef version: 1.8.8
OS: Arch

**Comment by Alexey-Yakovenko** [comment]
deadbeef 1.9.0 has a new album art plugin, which supposedly fixes this problem. There's no sense in reporting artwork bugs about 1.8.8, unless the same bugs persist in 1.9.0-beta.
