### ISSUE TITLE
DCA plugin fails to detect DTS in some DTS-wav files.

### ISSUE THREAD

**Issue by dikonov** [DeaDBeeF-Player/deadbeef#2755]
### Steps to reproduce the problem
Воспроизвести DTS WAV полученный граббером с DTS CD. Обычно это касается только 1-й дорожки.

### What's going on? Describe the problem in as much detail as possible.
DTS  не обнаруживается. Слышно ШШШШШШШШШШ.
### Information about the software:
Все версии deadbeef

Deadbeef version: 1.8.4
OS: Linux  5.10.78

Разбор пары проблемных файлов показал, что они содержат много килобайт нулей и чего-то непонятного между заголовком RIFF WAVE и первым фреймом DTS.  
- Если отрезать 44 байта заголовка wav, то голый DTS файл воспроизводится. 
- Если вырезать мусор между заголовком и началом DTS,  то тот же самый поток воспроизводится и в WAV с тем же самым заголовком (хотя в нем потом еще нужно поправить поля длины данных).

Моя гипотеза: 
Плагин dca перестает искать DTS фреймы и ошибочно решает, что у нас простой wav, если не-dts данных в начале файла много. Мешающий мусор в виде нулей может оказаться техническим lead-in CD перед первой дорожкой, который грабберы иногда цепляют к собственно данным (?).

**Comment by dikonov** [comment]
Было бы здорово еще добавить в настройку кнопку отключения плагинов dca и dolby, чтобы потоки AC3 и DTS передавались на раскодирование ресиверу. Это нужно при подключении по оптике. Многоканальный PCM в оптический провод toslink не проходит, а закодированный dts - проходит.

**Comment by Alexey-Yakovenko** [comment]
@dikonov 
я не могу данный баг воспроизвести, за неимением возможности воссоздать проблематичный файл.

вы можете переслать мне файл для разбора?

**Comment by dikonov** [comment]
Я не смогу переслать большие аудиофайлы через гит, но попробую связаться почтой.

**Comment by Alexey-Yakovenko** [comment]
да, лучше файлообменник и линк на почту - я напишу когда скачаю

**Comment by Alexey-Yakovenko** [comment]
The problem has been fixed by increasing the buffer size to 64K. However, the files produce some noice in the beginning, which normally should not happen. Most likely it's another bug, I'll try to fix it separately.
