### ISSUE TITLE
WV format not recognised when opening over VFS

### ISSUE THREAD

**Issue by dikonov** [DeaDBeeF-Player/deadbeef#2759]
### Steps to reproduce the problem
Open a remote folder containing .wv compressed audio files over gnome-vfs. I used Cinnamon Nemo file manager and a ssh (sftp) connection. The file I used was a 24-192 LP rip. Click a file to open it with deadbeef. Drug a second .wv file to the deadbeef window. 

### What's going on? Describe the problem in as much detail as possible.
The first file plays normally, but the second fails to be recognised and cannot play. The waveform plugin shows some weird data, as if the file was LPCM mistakenly opened as a standard PCM. 

### Information about the software:

Deadbeef version: 1.8.4
OS: ALTLinux

The same files opened from a local folder play well.

**Comment by Alexey-Yakovenko** [comment]
Deadbeef doesn't support gvfs directly. You will need to install a plugin - such as [this one](https://github.com/asv/deadbeef-gvfs)
