### ISSUE TITLE
GTKUI: artwork plugin consumes unexpectedly high amount of RAM

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#2762]
### What's going on? Describe the problem in as much detail as possible.

As described in the comment of another issue:
https://github.com/DeaDBeeF-Player/deadbeef/issues/2740#issuecomment-1053800451

### Information about the software:

Deadbeef version: 1.9.0-RC1
OS: Linux (presumably Arch with KDE)

**Comment by Npa972** [comment]
Hi perhaps can you close this issue ?
I use the last 1.9.2 beta1 and memory increases of course when scrolling into the playlist with covers but not like before.
And one important thing is that memory decreases after a while.
I suppose you have improved a lot of things since February.
Thanks.

**Comment by Alexey-Yakovenko** [comment]
Thanks, closing.
