### ISSUE TITLE
GTK3 UI plugin does not work with Wayland 1.20

### ISSUE THREAD

**Issue by Aranjedeath** [DeaDBeeF-Player/deadbeef#2763]
### Steps to reproduce the problem
I am using KDE NEON. I am using Deadbeef 1.8.8. NEON just shipped Wayland 1.20, which the gtk3 gui plugin appears not to like. 

I am not using wayland directly, so this is probably wayland 1.20 through xwayland. 

I get lines like the following when launching deadbeef from CLI:

```
starting deadbeef 1.8.8 [static]
server_start
searching for GUI plugins in /home/aranjedeath/.local/lib64/deadbeef
searching for GUI plugins in /home/aranjedeath/.local/lib/deadbeef
searching for GUI plugins in /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 57 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK3.so
dlopen error: /lib/x86_64-linux-gnu/libwayland-cursor.so.0: undefined symbol: wl_proxy_marshal_flags
trying /opt/deadbeef/lib/deadbeef/ddb_gui_GTK3.fallback.so...
selected GUI plugin not found or failed to load, trying to find another GUI plugin
the plugin not found or failed to load
the plugin not found or failed to load
loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK2.so
loading plugins from /home/aranjedeath/.local/lib64/deadbeef
loading plugins from /home/aranjedeath/.local/lib/deadbeef
loading plugins from /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 57 files
loading plugin /opt/deadbeef/lib/deadbeef/aac.so
loading plugin /opt/deadbeef/lib/deadbeef/adplug.so
```

This is a change -- I had Wayland 1.18 previously, and everything worked great.

### What's going on? Describe the problem in as much detail as possible.
Apparently GTK3 Gui plugin runs into this issue and falls back to gtk2 UI (which is unusable due to the lack of KDE integration with it). The colors are unusably wrong, basically. 

### Information about the software:

Deadbeef version: 1.8.8
OS: KDE NEON

![image](https://user-images.githubusercontent.com/8355878/157361551-84b55bca-d1c8-4db7-bfd1-83fdf6beac71.png)

**Comment by Alexey-Yakovenko** [comment]
Such errors typically indicate that some library is not installed, or that some library is out of date.

Try installing / updating the GTK and wayland libraries.

**Comment by Alexey-Yakovenko** [comment]
Not actionable
