### ISSUE TITLE
Request for 32 bit deadbeef-static .deb file, version 0.7.2

### ISSUE THREAD

**Issue by minuxlintebiandedition** [DeaDBeeF-Player/deadbeef#2765]
On sourceforge, the latest 32 bit static version in .deb format is version 0.6x which still has the dependency on gtk2.0

Please can we have this in version 0.7.2

Deadbeef version: 0.7.2
OS: debian linux , usually lmde

**Comment by Alexey-Yakovenko** [comment]
We no longer provide 32 bit binaries, and there are no plans to do so.
32 bit support is no longer guaranteed to work, since we are not testing on 32 bit systems.
However, we don't intentionally remove 32 bit support, and there's a chance that you would be able to build on your own.

**Comment by minuxlintebiandedition** [comment]
I have no idea how to build my own! Somebody is compiling the regular .deb file in 32 bit for the deb-multimedia.org repositories
They have version 0.7.2 in stretch and 1.8.1 in later repos.
It's a bit of a chore to install that way, much easier to have the static version.
I'm using it in 32 bit all the time. Might be able to do some testing.

**Comment by Alexey-Yakovenko** [comment]
> I have no idea how to build my own!

It's as simple as following the instructions written in the README.md file

**Comment by minuxlintebiandedition** [comment]
Thanks, so do I download the source code (from where???) into a folder, then make that folder the current working directory, then install git, Clan toolchain then follow the instructions in readme.md?

It looks like I need to feed it some code, as the readme.md instructions seem to be independent of the deadbeef source code?

**Comment by Alexey-Yakovenko** [comment]
You don't have to install git, but the rest is required.
Latest source code is here: https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9.1/deadbeef-1.9.1.tar.bz2/download
Unpack, and follow instructions.
There's nothing super unusual -- just the typical linux build steps.
* Install dependencies (including clang toolchain)
* export CC=clang CXX=clang++
* ./configure
* make
* sudo make install

**Comment by minuxlintebiandedition** [comment]
where am I going wrong?

root@ausra:~# apt install Clang toolchain
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package Clang
E: Unable to locate package toolchain
root@ausra:~# synaptic

(synaptic:11142): Gtk-CRITICAL **: 23:05:09.907: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
Discarding: 8 over 9
Discarding: 14 over 15
Discarding: 14 over 15
root@ausra:~# apt install git
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  git-man liberror-perl
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk
  gitweb git-cvs git-mediawiki git-svn
Recommended packages:
  ssh-client
The following NEW packages will be installed:
  git git-man liberror-perl
0 upgraded, 3 newly installed, 0 to remove and 6 not upgraded.
Need to get 7,386 kB of archives.
After this operation, 37.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://deb.debian.org/debian bullseye/main amd64 liberror-perl all 0.17029-1 [31.0 kB]
Get:2 https://deb.debian.org/debian bullseye/main amd64 git-man all 1:2.30.2-1 [1,827 kB]
Get:3 https://deb.debian.org/debian bullseye/main amd64 git amd64 1:2.30.2-1 [5,527 kB]
Fetched 7,386 kB in 27s (276 kB/s)                                             
Selecting previously unselected package liberror-perl.
(Reading database ... 241238 files and directories currently installed.)
Preparing to unpack .../liberror-perl_0.17029-1_all.deb ...
Unpacking liberror-perl (0.17029-1) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a2.30.2-1_all.deb ...
Unpacking git-man (1:2.30.2-1) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.30.2-1_amd64.deb ...
Unpacking git (1:2.30.2-1) ...
Setting up liberror-perl (0.17029-1) ...
Setting up git-man (1:2.30.2-1) ...
Setting up git (1:2.30.2-1) ...
Processing triggers for man-db (2.9.4-2) ...
localepurge: Disk space freed:   8572 KiB in /usr/share/locale
localepurge: Disk space freed:      0 KiB in /usr/share/man
localepurge: Disk space freed:      0 KiB in /usr/share/gnome/help
localepurge: Disk space freed:      0 KiB in /usr/share/aptitude
localepurge: Disk space freed:      0 KiB in /usr/share/help

Total disk space freed by localepurge: 8572 KiB

root@ausra:~# cd /home/remix/make/deadbeef-0.7.2/
root@ausra:/home/remix/make/deadbeef-0.7.2# git submodule update --init
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
root@ausra:/home/remix/make/deadbeef-0.7.2# ./autogen.sh
-bash: ./autogen.sh: No such file or directory
root@ausra:/home/remix/make/deadbeef-0.7.2# nano autogen.sh


Use "fg" to return to nano.

[1]+  Stopped                 nano autogen.sh
root@ausra:/home/remix/make/deadbeef-0.7.2# xed

** (xed:17468): WARNING **: 23:19:49.638: Could not load Peas repository: Typelib file for namespace 'Peas', version '1.0' not found

** (xed:17468): WARNING **: 23:19:49.638: Could not load PeasGtk repository: Typelib file for namespace 'PeasGtk', version '1.0' not found

(xed:17468): Gtk-WARNING **: 23:19:50.616: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

** (xed:17468): WARNING **: 23:20:22.880: Set document metadata failed: Setting attribute metadata::xed-spell-language not supported

** (xed:17468): WARNING **: 23:20:22.881: Set document metadata failed: Setting attribute metadata::xed-encoding not supported

** (xed:17468): WARNING **: 23:20:28.535: Set document metadata failed: Setting attribute metadata::xed-position not supported
root@ausra:/home/remix/make/deadbeef-0.7.2# autogen.sh
autogen.sh: command not found
root@ausra:/home/remix/make/deadbeef-0.7.2# ls
autogen.sh  deadbeef  deadbeef.png  doc  locale  pixmaps  plugins
root@ausra:/home/remix/make/deadbeef-0.7.2# nemo

(nemo:17523): Gtk-WARNING **: 23:21:16.300: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
ERROR SET META:15 Setting attribute metadata::nemo-icon-view-auto-layout not supported
CinnamonDesktop-Message: 23:21:16.700: Ignoring thumbnailer with missing binary: '/usr/bin/gdk-pixbuf-thumbnailer'
Running autopoint...
/home/remix/make/deadbeef-0.7.2/autogen.sh: 4: autopoint: not found
Running aclocal...
/home/remix/make/deadbeef-0.7.2/autogen.sh: 5: aclocal: not found
root@ausra:/home/remix/make/deadbeef-0.7.2# autogen.sh
autogen.sh: command not found
root@ausra:/home/remix/make/deadbeef-0.7.2# xed configure.ac

** (xed:17573): WARNING **: 23:25:18.960: Could not load Peas repository: Typelib file for namespace 'Peas', version '1.0' not found

** (xed:17573): WARNING **: 23:25:18.960: Could not load PeasGtk repository: Typelib file for namespace 'PeasGtk', version '1.0' not found

(xed:17573): Gtk-WARNING **: 23:25:19.900: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

** (xed:17573): WARNING **: 23:25:31.255: Set document metadata failed: Setting attribute metadata::xed-spell-language not supported

** (xed:17573): WARNING **: 23:25:31.255: Set document metadata failed: Setting attribute metadata::xed-encoding not supported

** (xed:17573): WARNING **: 23:25:36.716: Set document metadata failed: Setting attribute metadata::xed-position not supported
root@ausra:/home/remix/make/deadbeef-0.7.2# co
codepage                  compare-im6               compute_member
col                       compare-im6.q16           compute_relabel
colcrt                    compgen                   conjure
colrm                     complete                  conjure-im6
column                    compopt                   conjure-im6.q16
combinediff               compose                   continue
comm                      composite                 convert
command                   composite-im6             convert-im6
command-not-found         composite-im6.q16         convert-im6.q16
command_not_found_handle  compute_av                coproc
compare                   compute_create            corelist
root@ausra:/home/remix/make/deadbeef-0.7.2# nemo

(nemo:17582): Gtk-WARNING **: 23:25:56.281: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
ERROR SET META:15 Setting attribute metadata::nemo-icon-view-auto-layout not supported
CinnamonDesktop-Message: 23:25:56.711: Ignoring thumbnailer with missing binary: '/usr/bin/gdk-pixbuf-thumbnailer'
# _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
# watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
# unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
# watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
root@ausra:/home/remix/make/deadbeef-0.7.2# con
conjure          conjure-im6.q16  convert          convert-im6.q16
conjure-im6      continue         convert-im6      
root@ausra:/home/remix/make/deadbeef-0.7.2# configure.ac
configure.ac: command not found
root@ausra:/home/remix/make/deadbeef-0.7.2# CC=clang CXX=lang++ configure
configure: command not found
root@ausra:/home/remix/make/deadbeef-0.7.2# CC=clang CXX=lang++
root@ausra:/home/remix/make/deadbeef-0.7.2# make install
make: *** No rule to make target 'install'.  Stop.
root@ausra:/home/remix/make/deadbeef-0.7.2#

**Comment by Alexey-Yakovenko** [comment]
You don't seem to be following instructions precisely enough.
Please try again, and note that commands need to be entered precisely.
From what I can tell,  you typed `configure` instead of `./configure`.
Here's a screenshot of the instructions from README.md

<img width="861" alt="image" src="https://user-images.githubusercontent.com/1895698/171295199-cb0db7d9-a198-43d0-88e1-53a955a8498c.png">

**Comment by minuxlintebiandedition** [comment]
`root@ausra:/# ./configure
./configure: line 1: dnl: command not found
./configure: line 2: syntax error near unexpected token `[deadbeef],'
./configure: line 2: `AC_INIT([deadbeef], [devel])'
root@ausra:/# `

Tried to create 'configure' by copying the text from configure.ac from this website and pasting it into xed.
