### ISSUE TITLE
gui plugin has quit.

### ISSUE THREAD

**Issue by xManan** [DeaDBeeF-Player/deadbeef#2766]
### What's going on? Describe the problem in as much detail as possible.
compilied deadbeef 1.8.8 from source.
upon launching deadbeef I get the following message:

starting deadbeef 1.8.8
server_start
searching for GUI plugins in /home/manan/.local/lib64/deadbeef
searching for GUI plugins in /home/manan/.local/lib/deadbeef
searching for GUI plugins in /usr/local/lib/deadbeef
load_plugin_dir /usr/local/lib/deadbeef: scandir found 51 files
load gui plugin
selected GUI plugin not found or failed to load, trying to find another GUI plugin
loading plugins from /home/manan/.local/lib64/deadbeef
loading plugins from /home/manan/.local/lib/deadbeef
loading plugins from /usr/local/lib/deadbeef
load_plugin_dir /usr/local/lib/deadbeef: scandir found 51 files
loading plugin /usr/local/lib/deadbeef/adplug.so
loading plugin /usr/local/lib/deadbeef/alac.so
loading plugin /usr/local/lib/deadbeef/dca.so
loading plugin /usr/local/lib/deadbeef/ddb_dumb.so
loading plugin /usr/local/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/local/lib/deadbeef/ddb_shn.so
loading plugin /usr/local/lib/deadbeef/ddb_soundtouch.so
loading plugin /usr/local/lib/deadbeef/gme.so
loading plugin /usr/local/lib/deadbeef/hotkeys.so
loading plugin /usr/local/lib/deadbeef/in_sc68.so
loading plugin /usr/local/lib/deadbeef/m3u.so
loading plugin /usr/local/lib/deadbeef/mms.so
loading plugin /usr/local/lib/deadbeef/musepack.so
loading plugin /usr/local/lib/deadbeef/nullout.so
loading plugin /usr/local/lib/deadbeef/oss.so
loading plugin /usr/local/lib/deadbeef/psf.so
loading plugin /usr/local/lib/deadbeef/rg_scanner.so
loading plugin /usr/local/lib/deadbeef/shellexec.so
loading plugin /usr/local/lib/deadbeef/sid.so
loading plugin /usr/local/lib/deadbeef/supereq.so
loading plugin /usr/local/lib/deadbeef/tta.so
loading plugin /usr/local/lib/deadbeef/vtx.so
loading plugin /usr/local/lib/deadbeef/wildmidi.so
loading plugin /usr/local/lib/deadbeef/wma.so
starting plugin Adplug player
starting plugin ALAC player
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Soundtouch
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MusePack decoder
starting plugin Null output plugin
starting plugin OSS output plugin
starting plugin PSF player using Audio Overload SDK
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin SID player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin VTX player
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
selected output plugin: Null output plugin
INFO: from file /home/manan/.config//deadbeef/playlists/0.dbpl
streamer_dsp_chain_load: plugin SRC not found. preset will not be loaded
streamer_dsp_chain_load: error loading /home/manan/.config//deadbeef/dspconfig
resume: track -1 pos -1.000000 playlist -1
gui plugin has quit; waiting for mainloop thread to finish

and it stays like this

### Information about the software:
OS: Ubuntu 20.04.1
gtk+2-2.24.20
gtk+3-3.24.20

**Comment by Alexey-Yakovenko** [comment]
From what I can tell -- you did not install the build dependencies before compiling.
Please follow the README file to get the list of dependencies (not the README.md, but the other one without extension).
