### ISSUE TITLE
plugins: Makefiles should include deadbeef.h as prerequisite

### ISSUE THREAD

**Issue by rsekman** [DeaDBeeF-Player/deadbeef#2769]
### Steps to reproduce the problem

```sh
touch deadbeef.h
make
```

### What's going on? Describe the problem in as much detail as possible.

Since all plugins depend on functions and types from `deadbeef.h`, `make` should rebuild all plugins, but it doesn't. `make -B` can be issued but can take a long time to run. The issue is that `deadbeef.h` is not listed as a prerequisite in the relevant Makefles. For example  in `plugins/gtkui/Makefile.am`:

```c
GTKUI_SOURCES = \
    ../../utf8.c\
```
Simply adding `../../deadbeef.h` should fix the problem.

### Information about the software:

Deadbeef version: master
OS:

**Comment by Alexey-Yakovenko** [comment]
I can confirm the problem, but smh adding deadbeef.h to the _SOURCES doesn't help -- changing deadbeef.h doesn't rebuild anything, even in the modules where _SOURCES already had it.

If you come up with a patch, please let me know.

**Comment by Oleksiy-Yakovenko** [comment]
I did further investigation, and failed to make it work with autotools.
I found this statement in autotools documentation:
> Header files listed in a ‘_SOURCES’ definition will be included in the distribution **but otherwise ignored**. 

I'm not sure whether this is some recent behavior change, or it's always been this way -- but seems to be working as designed.
If this is bothering you - please consider using another build system.
Deadbeef supports premake5 for building on windows and linux, and it handles header file changes just fine.

Here's how it can be used:

1. Download premake5. At the time of writing, the latest version is  v5.0.0-beta2, and can be downloaded [from this page](https://premake.github.io/download/).
2. Unpack it somewhere, I did into /usr/local/bin
3. Generate a makefile:
```
/usr/local/bin/premake-5.0.0-beta2-linux/premake5 gmake
```
4. Build using `make` as usual, this would make a debug build. Use `make config=release_linux` to make a release build.
5. Find the build results in `bin/debug` or `bin/release`
