### ISSUE TITLE
Question: Album Artwork - Cache update period?

### ISSUE THREAD

**Issue by 0pLuS0** [DeaDBeeF-Player/deadbeef#2773]
### Steps to reproduce the problem
When I place the Cache update period on 0 I noticed in the config this line;

```artwork.cache_reset_time 1648679584```

### What's going on? Describe the problem in as much detail as possible.
I thought if the Cache update period is on 0, then there is no ```artwork.cache_reset_time``` line listed in the config?

### Information about the software:

Deadbeef version: 1.8.8
OS: Slackware 15.0

THANKS

Here's screen shots of the settings...

![preferences](https://user-images.githubusercontent.com/36190223/160942596-e7ceeb6c-86a1-4d56-a96c-10dee085acdd.jpg)

![artwork_cache](https://user-images.githubusercontent.com/36190223/160942741-e21099e2-60cb-469b-9dbf-03e82f5cfc45.jpg)

**Comment by Alexey-Yakovenko** [comment]
Seems like a bug. However, deadbeef 1.9.0 will have a new "rewrite" of the artwork plugin, and I believe this issue most likely is fixed there.

**Comment by 0pLuS0** [comment]
I don't see this in 1.9.1 :)
