### ISSUE TITLE
Playlist glitch after sort by random, then crash

### ISSUE THREAD

**Issue by 71864315** [DeaDBeeF-Player/deadbeef#2774]
### Steps to reproduce the problem
1) Drag any song in playlist.
2) Click Edit > Sort by > Random.
3) Drag any song in playlist again (not necessary the same). Maybe you will have to do this few times, then playlist will glitch, some songs dissapear.
4) Click Edit > Sort by > Random. Deadbeef will crash.

### What's going on? Describe the problem in as much detail as possible.
After moving and sorting songs playlist will eventually glitch, then if you sort again - crash. It makes no difference if you use GTK2 or GTK3. The problem is observed only when sorting by random. I can't reproduce it when selecting sort by Title, Album or any other but random.

### Information about the software:

Deadbeef version: 1.8.8
OS: Arch Linux 5.15.32-xanmod1-tt-1, but the issue persist in fresh Ubuntu 21.10 install in virtual machine with default Deadbeef settings

[deabeef.log](https://github.com/DeaDBeeF-Player/deadbeef/files/8394075/deabeef.log)

https://user-images.githubusercontent.com/29060641/161179724-8b870e56-18c6-4d45-b2fc-5dbf77e5e993.mp4

**Comment by JakeSFR** [comment]
Happens also with the latest static devel (2022-03-03).
I can reproduce it every time, when, after the initial random sorting, I immediately drag the track that used to be on top of the unsorted playlist.

**Comment by Alexey-Yakovenko** [comment]
Does it still happen? I just tried on trunk, no errors, no glitches, and no crashes. ASAN is silent.

**Comment by JakeSFR** [comment]
Yes, I also can confirm. Additionaly tried in Mint and the same happens.

The important thing is to, right after sorting, drag the previously 1st track, in order to produce the glitch, like this:

https://user-images.githubusercontent.com/6226504/174348745-d7f45407-c71b-4c94-b8c7-870b35ab4490.mp4


Btw, when I sort and then re-launch DB, the glitch doesn't happen; it has to be in the same session.

**Comment by Alexey-Yakovenko** [comment]
Reproduced
