### ISSUE TITLE
Waveform Seekbar + any YM2151/OPM chiptune = distorted sound

### ISSUE THREAD

**Issue by axredneck** [DeaDBeeF-Player/deadbeef#2778]
### Steps to reproduce the problem
- Add [Waveform Seekbar](https://github.com/cboxdoerfer/ddb_waveform_seekbar) to DeaDBeeF's interface
- Play some YM2151/OPM chiptune (can be found [here](https://vgmrips.net/packs/systems/sharp) and [here](https://vgmrips.net/packs/system/capcom/cp-system) for example)

### What's going on? Describe the problem in as much detail as possible.
Noise instead of music, at least first time (playing the same track again usually works right)

### Information about the software:

Deadbeef version: both 1.8.8 and Git ccacc95a188b4b4e9fae8370834a8a74e0d4458a
OS: Arch Linux

**Comment by axredneck** [comment]
Yes, it is

**Comment by Alexey-Yakovenko** [comment]
I can't reproduce this problem with or without waveform seekbar plugin.
Tried:
* Deadbeef latest build from master
* Ubuntu18.04 and Manjaro
* Pulse and ALSA output
* On manjaro, I installed pipewire, which caused pulseaudio output in deadbeef to stop working, but music still played fine using ALSA output

It seems like there's something with your setup, which you forgot to mention, and without knowing it I would not be able to reproduce.

**Comment by axredneck** [comment]
I don't know what can be wrong with my setup.

**Comment by Alexey-Yakovenko** [comment]
I didn't mean that anything is wrong in your setup -- just that your setup has something different from what I have, and without knowing what this difference is, it becomes very hard or impossible to reproduce the issue

Here are some examples that can make the difference

* Any non-default settings in ALSA/Pulse/Pipewire/Deadbeef
* Any additional plugins installed for Deadbeef
* Hardware configuration - such as  soundcard / external DAC
* Bluetooth headphones/speakers vs wired

**Comment by axredneck** [comment]
Meanwhile Foobar2000 has exactly the same issue, so it's probably a bug of GameMusicEmu plugin.

**Comment by axredneck** [comment]
Fixed in Game Music Emu 0.5
