### ISSUE TITLE
[Request] Changing visualizations background colors

### ISSUE THREAD

**Issue by 64542426** [DeaDBeeF-Player/deadbeef#2779]
If possible, please add support for changing background colors to the Visualizations rather than using the static black.

**Comment by Alexey-Yakovenko** [comment]
Pretty sure I've already done this... Could you please check the 1.9.0-rc1? You should be able to change the visualization background color in preferences.

**Comment by 64542426** [comment]
Hi, sorry for not put more info about player version. I'm using version 1.9.0 Devel version
So far only color of the text is possible, background doesn't have a feature as i can see.

As you can note there is a static black background for both Spectrum/Oscilloscope
And the dialog doesn't show a way to change it, the only feature is the equalizer color.
I selected the orange and as we see is covered very good, but the background is still black, wish i can customized to other color.

![2022-04-08--1649445084_1398x798_scrot](https://user-images.githubusercontent.com/35492934/162490027-9430f892-b95d-4191-b089-da506678bf94.png)
![2022-04-08--1649445439_652x199_scrot](https://user-images.githubusercontent.com/35492934/162490735-d89a087b-c2fc-41bc-9b0f-ffd02d73b459.png)

**Comment by Alexey-Yakovenko** [comment]
sorry, good point - I implemented it on mac, but not on linux yet.

**Comment by 64542426** [comment]
Thank you very much

**Comment by Oleksiy-Yakovenko** [comment]
This is now done on master branch (global, not per widget).
There's also possibility to have per-widget configurability, but this is not done yet.
