### ISSUE TITLE
I am unable to convert my music to opus in macOS devel build

### ISSUE THREAD

**Issue by Akczht** [DeaDBeeF-Player/deadbeef#2783]
### Steps to reproduce the problem
1. open DeaDBeeF 
2. add some music
3. convert it to opus

## What's going on? Describe the problem in as much detail as possible.

on the log window error comes 

Write error (-1 bytes written out of 12000)
Failed to execute the encoder, command used:
opusenc --hard-cbr --birate 256 - "/Users/akshat/Downloads/Greatest/20. Bee Gees - Children Of The World.opus"

### Information about the software:

Deadbeef version: devel latest MAc mybe 1.8.8
OS:macOS Monterey 12.3.1

**Comment by Alexey-Yakovenko** [comment]
Deadbeef doesn't include encoders, you need to install opusenc (and whatever other encoders you want to use), and make sure they're in PATH.

**Comment by Akczht** [comment]
where should I install them and where to install them

**Comment by Akczht** [comment]
from terminal I am able to access opusenc just fine , but deadbeef is unable to access them

**Comment by Alexey-Yakovenko** [comment]
As long as opusenc can be found by deadbeef, it should work. The opusenc executable needs to be in a location which is part of the PATH environment variable (e.g. /usr/local/bin)

**Comment by Akczht** [comment]
Oh! Thanks It's working now , I just used the whose macports bin dir , for its command . DeaDBeeF is good .

**Comment by Akczht** [comment]
> As long as opusenc can be found by deadbeef, it should work. The opusenc executable needs to be in a location which is part of the PATH environment variable (e.g. /usr/local/bin)

Also after converting I don't get the album art and other arts attached to the converted file , how can I fix that ?

**Comment by Alexey-Yakovenko** [comment]
I'm afraid this is not supported. See #1684

**Comment by Akczht** [comment]
Oh , Ok then . BTW do you happen to know of any foobar2000 alternatives for macOS , I want to manage my music collection on my macOS machine only .

**Comment by Alexey-Yakovenko** [comment]
Sorry, I've not encountered anything aside of foobar2000 itself running under wine.

**Comment by Akczht** [comment]
Very sad to hear that , Thanks! though
