### ISSUE TITLE
equalizer interface distortion

### ISSUE THREAD

**Issue by NektoNektovich** [DeaDBeeF-Player/deadbeef#2786]
xubuntu 22.04, deadbeef 1.8.8
parametric equalizer interface is unnecessarily stretched in the Russian interface.
![Снимок экрана_2022-05-03_03-53-43](https://user-images.githubusercontent.com/53621368/166390739-993e8bdf-a2c1-4bc9-bf4a-5a2c9401a6f0.png)

**Comment by Alexey-Yakovenko** [comment]
There will be no russian interface. Слава Україні!
