### ISSUE TITLE
Tofu in Title (No blue and yellow heart)

### ISSUE THREAD

**Issue by Npa972** [DeaDBeeF-Player/deadbeef#2790]
![Capture d’écran_2022-05-13_16-04-57](https://user-images.githubusercontent.com/49346431/168382068-f8768071-d023-4164-afef-8b7909264ea0.png)
### Steps to reproduce the problem
Just open DeadBeef on Archlinux
### What's going on? Describe the problem in as much detail as possible.
Tofu in title. I suppose that a blue and yellow heart should appear ?
I tried to install noto-fonts but non change
### Information about the software:

Deadbeef version:
OS: archlinux
Deadbeef 1.9

**Comment by xtrahigh** [comment]
If you still want to see these streams of schizophrenia, install the [noto-fonts-emoji](https://archlinux.org/packages/extra/any/noto-fonts-emoji/) package

**Comment by Alexey-Yakovenko** [comment]
You can remove the hearts in the preferences (GUI / Misc tab).
