### ISSUE TITLE
Threadsanitizer undefined symbols in plugins

### ISSUE THREAD

**Issue by jpramosi** [DeaDBeeF-Player/deadbeef#2799]
Hello, I have tried to compile deadbeef with '-fsanitize=thread' flag.
However when loading the plugins, it failed to find the required symbols.
For example `undefined symbol: __tsan_ignore_thread_begin`

The corresponding build commands:
```
./autogen.sh

CC=clang \
CXX=clang++ \
CFLAGS="-g -O0 -fsanitize=thread -pthread -funwind-tables -fno-omit-frame-pointer -fno-optimize-sibling-calls" \
LDFLAGS="-fsanitize=thread" \
ASAN_OPTIONS=detect_leaks=0 ./configure \
--disable-silent-rules \
--enable-artwork \
--enable-artwork-network

make -j 20
```

[configure.log](https://github.com/DeaDBeeF-Player/deadbeef/files/8747653/configure.log)
[config.log](https://github.com/DeaDBeeF-Player/deadbeef/files/8747651/config.log)
[build.log](https://github.com/DeaDBeeF-Player/deadbeef/files/8747644/build.log)
[deadbeef.log](https://github.com/DeaDBeeF-Player/deadbeef/files/8747645/deadbeef.log)

Deadbeef version: 1.9.0-1_x86_64
OS: Kubuntu-22.04

**Comment by Alexey-Yakovenko** [comment]
not a deadbeef problem -- you should seek for help on clang forums instead.

**Comment by jpramosi** [comment]
I've forgot to add `-rdynamic` to 'LDFLAGS'.

_"... This instructs the linker to add all symbols, not only used ones, to the dynamic symbol table."_
