### ISSUE TITLE
OSD Notify does not respect Album art size (px) setting.

### ISSUE THREAD

**Issue by kierun** [DeaDBeeF-Player/deadbeef#2804]
### Steps to reproduce the problem

1. Enable OSD Notify in plugins.
2. Set Show Album Art.
3. Set a maximum size to 256 px -- or whatever.
4. Load a file with a large cover.
5. Play the file.

### What's going on? Describe the problem in as much detail as possible.

The OSD Notification will appear with a giant image, regardless of the maximum size setting.

### Information about the software:

* Deadbeef version: 1.9.1
* OS: Fedora 35
* Package: deadbeef-1.9.1-1.fc35.x86_64

**Comment by Alexey-Yakovenko** [comment]
@kierun Hi,
which desktop environment are you using?

**Comment by kierun** [comment]
> @kierun Hi, which desktop environment are you using?

[Awesome WM](https://awesomewm.org/).

However, it used to work fine till I updated deadbeef the last time.

**Comment by Alexey-Yakovenko** [comment]
Does Awesome WM have its own notification daemon? Can you find out which one? I can imagine, awesome does not have its own.. so you have to install something, to get notifications to display at all?

**Comment by kierun** [comment]
It does: [naughty](https://awesomewm.org/apidoc/libraries/naughty.html). Reading the documentation, I found [this](https://awesomewm.org/doc/api/libraries/naughty.html#beautiful.notification_icon_size) thus set it as `beautiful.notification_icon_size = 256` and upon re-starting my VM, the icons are now `256x256`. I guess my problem is fixed? ¯\\\_(ツ)\_/¯ 

However, I would assume that the OSD Notification plug-in does the resize of the image before sending it to whatever notification daemon there is. Or is it more of a request to the notification daemon to set the size?

**Comment by Alexey-Yakovenko** [comment]
I just checked the code, and the option which is supposed to resize the image before sending it to notification is not functional. Most likely it remained unnoticed when updating to the new artwork plugin.
I will have to re-implement it somehow.

**Comment by kierun** [comment]
Apologies for being the bearer of bad news… Do let me know if want me to test things.

Which is the new artwork plugin? I have the `Loads album artwork from embedded tags, local directories, or internet services` at 2.0.

**Comment by Alexey-Yakovenko** [comment]
The new one is the one that comes with deadbeef 1.9.0 and newer.

**Comment by Oleksiy-Yakovenko** [comment]
I added the code to scale the images before displaying.
It's not perfect, and could be improved slightly to improve caching -- but it should be good enough to start testing it.
