### ISSUE TITLE
Feature request- Add Play/Pause action to deadbeef.desktop file

### ISSUE THREAD

**Issue by ziomek64** [DeaDBeeF-Player/deadbeef#2830]
It would be great to have joined play/pause shortcut in kde shortcuts too, not just separately. I hope I'm submitting issue in the right place. It's up to the developer of software to implement those right?

Deadbeef version: 1.9.1 
OS: Linux - EndeavourOS, arch based

**Comment by Alexey-Yakovenko** [comment]
@ziomek64 What specifically do you call "kde shortcuts"? it's not clear to me at all what you're asking about :)

**Comment by kuba160** [comment]
If you want integration with kde media controls - you should install mpris plugin: https://github.com/DeaDBeeF-Player/deadbeef-mpris2-plugin

**Comment by ziomek64** [comment]
@Alexey-Yakovenko I mean these - https://imgur.com/a/W013xTD - it's in Polish but you should what this is

@kuba160 I'll see what this is

**Comment by Alexey-Yakovenko** [comment]
Oh ok, I see. I think it takes those actions from the .desktop file.
This should be easy.

**Comment by Alexey-Yakovenko** [comment]
@ziomek64 added on master, could you please confirm whether it works for you, when you have the chance?

**Comment by ziomek64** [comment]
I'm pretty much newbie with linux and I don't want to install from source and dunno how to later remove it. I always use pacman or AUR helper for my arch based distro. Someone else might try it, should be easy for them. I'm using mpris2 plugin as @kuba160 suggested for now.

**Comment by kuba160** [comment]
You could install `deadbeef-git` from AUR which follows development branch (master) compared to version releases.

I don't think you made it clear enough what you want to achieve. mpris plugin will make kde "recognize" deadbeef as a media player and you should be able to control it via playback buttons on the keyboard by default (and through play icon in tray and from kdeconnect as well). You can also add global shortcuts in deadbeef settings which should work as long as you are not using Wayland and they (probably even better solution) will only work when deadbeef is running.

@Alexey-Yakovenko I tried KDE Shortcut page and Toggle Pause didn't appear on that list, it looks like it only shows items listed under Actions. Adding it there will add it to deadbeef context menu as well I guess. I'd suggest to have Pause button act as Toggle Pause, unless there is some usecase where it is not desired.

**Comment by ziomek64** [comment]
@kuba160 deadbeef-git is not updated every single commit sadly

I wanted to achieve global control with one gimmick for me only. I'm using Razer keyboard, I have open-source driver called openrazer. I wanted to have control over media with custom buttons on the left of the keyboard mapped as follow
`    'M1': 'XF86Tools',
    'M2': 'XF86Launch5',
    'M3': 'XF86Launch6',
    'M4': 'XF86Launch7',
    'M5': 'XF86Launch8',`

But for some reason M1 which is XF86Tools does not work as a global key for me in deadbeef preferences (I can bind it, but it does not work if global is to true). That's why I wanted to have it in KDE or whatever that will give me global control for that key to control media (play/pause). If you know why that might be, let me know.

**Comment by kuba160** [comment]
With mpris plugin you could add custom shortcuts in System Services -> Media Controller. This will make shortcuts work for other media such as vlc or firefox.

But yeah, it is annoying how macro keys (M1..Mn) work on linux. For my macropad I had to use higher function keys (F13..F13+n) to achieve desired behavior.

**Comment by ziomek64** [comment]
@kuba160 and so I did.

So no way to bind M1 - XF86Tools in deadbeef to make it work as global?

**Comment by kuba160** [comment]
I think I tried mapping that to Discord and I didn't succeed, so I think it might not be deadbeef related issue.

**Comment by ziomek64** [comment]
Why does it work fine in KDE shortcuts?
