### ISSUE TITLE
in ~/.config/deadbeef/config each lines is present twice

### ISSUE THREAD

**Issue by sp31415t1** [DeaDBeeF-Player/deadbeef#2835]
### Steps to reproduce the problem

run deadbeef with version 1.9.1 and the "static" build
close it
less ~/.config/deadbeef/config

### What's going on? Describe the problem in as much detail as possible.
In my ~/.config/deadbeef/config, the content is present twice.
Maybe the content is 'dumped' twice in the file
maybe related to my setup, but I don't see why.

### Information about the software:

Deadbeef version: 1.9.1 static
OS: linux debian testing up-to-date

**Comment by kuba160** [comment]
This has been fixed in a8ad6b4bc782a67a6f6f1f4b5e3719a7b5f1b377, it is in 1.9.2-beta1 already and will be included in next stable version release.
