### ISSUE TITLE
Multimedia keys not working in Ubuntu 22.04 Jammy Jellyfish

### ISSUE THREAD

**Issue by Logicwax** [DeaDBeeF-Player/deadbeef#2837]
### Steps to reproduce the problem
having an issue where media keys are not working in latest ubuntu 22.04 Jammy with GNOME 42.2 on wayland.

When i press media keys, GNOME gives me the error pop-up (circle with line through it).

if i goto deadbeef key settings, and try to set a key binding for Toggle pause (even global) it detects it (my apple keyboard with the F8 play/pause button registers as XF86Launch9 in deadbeef). In fact, toggling "global" doesn't work at all for ANY keys (either in deadbeef or out).

### Information about the software:

Deadbeef version: 1.9.1
OS: Ubuntu 22.04, Jammy Jellyfish.  GNOME 42.2 /  wayland.

**Comment by Alexey-Yakovenko** [comment]
@Logicwax global hotkeys support in deadbeef is based on X11 functionality, and can't be used with wayland.
You can use MPRIS plugin to get the same functionality, it's available here: https://deadbeef.sourceforge.io/plugins.html

**Comment by Alexey-Yakovenko** [comment]
I closed this issue, since this functionality is not possible to get on deadbeef side, because GNOME reserves the global multimedia hotkeys internally, and the only way to get this functionality is to use MPRIS or similar.
The global hotkeys functionality in deadbeef is primarily useful with X11 window managers, and can't be used with environments like GNOME.

**Comment by Logicwax** [comment]
@Oleksiy-Yakovenko when you say "MPRIS" do you mean "Gnome muiltimedia keys support" plugin?


why is it other players have no problem playing nice with gnome, but deadbeef cant?

**Comment by Oleksiy-Yakovenko** [comment]
I refer to [this plugin](http://sourceforge.net/projects/deadbeef/files/plugins/x86_64/mpris-4da29ba-linux-x86_64.zip/download).

Deadbeef can play nice with GNOME when this plugin installed.
(I don't argue that this plugin should be included in the base install, but it has not been done yet)

**Comment by Oleksiy-Yakovenko** [comment]
the other plugin called gnome-mm-keys should also work.

**Comment by Logicwax** [comment]
> I refer to [this plugin](http://sourceforge.net/projects/deadbeef/files/plugins/x86_64/mpris-4da29ba-linux-x86_64.zip/download).

Thanks!   Works great.  Exactly what I needed.    

> Deadbeef can play nice with GNOME when this plugin installed. (I don't argue that this plugin should be included in the base install, but it has not been done yet)

This stuff should really be included in the base install.

> the other plugin called gnome-mm-keys should work as well. I'm not sure what the difference is..

Nope, I tried that already.   It doesn't work for me.   Maybe its due to latest gnome 42 and wayland?
