### ISSUE TITLE
[Request] Tracking play count of songs

### ISSUE THREAD

**Issue by f0pdoodle** [DeaDBeeF-Player/deadbeef#2841]
It would be neat to have a way to track how many times you have played a song. Perhaps someone could work on a plugin similar to the rating plugin. I have tried a workaround with custom shell commands but I am not experienced enough.

**Comment by f0pdoodle** [comment]
Nevermind there's already a plugin that seems to work for this.
Here it is: https://github.com/adwylie/deadbeef-playcount

**Comment by the81kid** [comment]
Hi, I've been trying to add that play count plugin but without success. I get error messages in the terminal when I try to follow the instructions. I'm not a pro at compiling so I may well be missing some steps or making rookie mistakes. Is there another (more noobie friendly) way to install the play count plugin?

Thanks in advance!
