### ISSUE TITLE
mpris applet in Plasma no longer show artwork.

### ISSUE THREAD

**Issue by mistersister** [DeaDBeeF-Player/deadbeef#2849]
Today I updated to v1.9.1 (static build) and noticed that the mpris applet on the taskbar no longer shows any artwork of the song currently playing.

If I launch v1.8.8, said applet shows the cover art no problem.

See attached pics with both v1.9.1 and v1.8.8

![Screenshot_20220901_175802](https://user-images.githubusercontent.com/3819621/187960003-dceb15d6-a2e5-486a-8bc0-3eb548afde1c.png)
![Screenshot_20220901_175855](https://user-images.githubusercontent.com/3819621/187960007-28482153-ca4a-45ee-b7f7-da6c2c317c08.png)

Deadbeef version: Static build 1.9.1

Operating System: Arch Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5
Kernel Version: 5.19.5-arch1-1 (64-bit)
Graphics Platform: X11

**Comment by kuba160** [comment]
Artwork backend changed with 1.9 release (if I remember correctly?), I guess you are using old mpris plugin which is not compatible with newer artwork backend. If this is the case then you need to update to version found here on [github](https://github.com/DeaDBeeF-Player/deadbeef-mpris2-plugin) or use AUR package: [deadbeef-mpris2-plugin-git](https://aur.archlinux.org/packages/deadbeef-mpris2-plugin-git)

**Comment by mistersister** [comment]
Updating the mpris plugin fixed it. However, before posting the bug report I cheked the tags page of the plugin repo and says latest version is 1.14 which is what I had at the moment. 

Seems is not up to date?

**Comment by Mart-Bogdan** [comment]
I don't know what is that applet, I can't see it at all.

But other palyers are showing media controls on Lock-screen and on taskbar thumbnails. For example: VLC, Elisa. But DeaDBeeF don't.

**Comment by Mart-Bogdan** [comment]
Ok. My bad. Had to install `deadbeef-mpris2-plugin`
