### ISSUE TITLE
Removing playing track breaks playing queue

### ISSUE THREAD

**Issue by br3eze** [DeaDBeeF-Player/deadbeef#2850]
### Steps to reproduce the problem
Remove playing track from playlist

### What's going on? Describe the problem in as much detail as possible.
Next track will be the first one in playlist, but not the next one.
'Delete from disk' option works well in this case.

### Information about the software:

Deadbeef version: 1.9.1
OS: Artix Linux

**Comment by Oleksiy-Yakovenko** [comment]
Can confirm that the issue occurs as described. It also occurs the same with delete from disk (unless the option to "skip deleted tracks" is turned on - but that is not quite the same thing).
