### ISSUE TITLE
Git version uninstallable in Debian Testing.

### ISSUE THREAD

**Issue by LeDechaine** [DeaDBeeF-Player/deadbeef#2853]
### Steps to reproduce the problem
git clone https://github.com/DeaDBeeF-Player/deadbeef.git
git submodule update --init
./autogen.sh
CC=clang CXX=clang++ ./configure
make

### What's going on? Describe the problem in as much detail as possible.
For some reason libdispatch0 is unavailable, so you have to get all this from **unstable**.

```
> libpthread-workqueue-dev_0.9.1-1_amd64.deb
> libkqueue-dev_2.3.1-1_amd64.deb
> libblocksruntime-dev_0.4.1-1.1_amd64.deb
> libdispatch-dev_0~svn197-3.3_amd64.deb
> libpthread-workqueue0_0.9.1-1_amd64.deb
> libkqueue0_2.3.1-1_amd64.deb
> libdispatch0_0~svn197-3.3_amd64.deb
```

Then, you'll get this error on **make**:

> CCLD     ffmpeg.la
> /usr/bin/ld: /usr/local/lib/libavcodec.a(h264_weight_10bit.o): warning: relocation against `ff_pw_1' in read-only section `.text'
> /usr/bin/ld: /usr/local/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32 against symbol `ff_pw_9' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: bad value
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Information about the software:
Deadbeef version: Git
OS: $ uname -a
Linux symphony 5.18.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.14-1 (2022-07-23) x86_64 GNU/Linux

This makes Deadbeef basically completely unusable in Debian because [this bug](https://github.com/DeaDBeeF-Player/deadbeef/issues/2809) affects 1.9.1, and not only when I click on some files: Deadbeef now segfaults basically every time a song changes. I really hope for version 1.9.2 soon, I loved DeaDBeeF... when it didn't crash.

Until then I'll downgrade to 1.8 or something.

**Comment by Oleksiy-Yakovenko** [comment]
I'm not sure what I can do about this. I can't make debian to ship certain library which it's missing.
If it lacks a library -- you can either download a deadbeef build which ships it (all the official builds do),
or you need to build / install the library yourself / find a 3rd party repository or package.

If you just need a build of latest version -- you can get the latest git build always at the same location:
https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download

**Comment by Oleksiy-Yakovenko** [comment]
> I really hope for version 1.9.2 soon

It's coming in a couple of days. I just kicked off the RC1.

**Comment by LeDechaine** [comment]
Way sooner than I thought LOL thanks! :grin:
