### ISSUE TITLE
Album Art Plugin suddenly disappeared.

### ISSUE THREAD

**Issue by HeathenHacks** [DeaDBeeF-Player/deadbeef#2855]
### Steps to reproduce the problem

-Not really sure how to reproduce it and maybe it's only on my end.

### What's going on? Describe the problem in as much detail as possible.

-I've installed DeaDBeeF via the AUR and have been using it for months, yesterday, I noticed that it's not displaying my music's album arts/covers.

Upon checking the plugins, apparently, it disappeared.

### Information about the software:

I'm using deadbeef version 1.9.1 on an Arch-based distro.
![Screenshot_20220921_130240](https://user-images.githubusercontent.com/43103175/191418751-07adcf9f-2aa0-4743-92e9-b602b89e0b60.png)

Deadbeef version: 1.9.1
OS: ArcoLinux (5.19.9-arch1-1)
Plasma 5.25.5

**Comment by Oleksiy-Yakovenko** [comment]
Some dependency has changed, and deadbeef needs to be reinstalled / recompiled. Just do that, and everything should be back to normal.

**Comment by HeathenHacks** [comment]
Oh, you're right. Thanks for the tip.

Much appreciated.
