### ISSUE TITLE
Flac files problem loading plugin

### ISSUE THREAD

**Issue by Entusiast** [DeaDBeeF-Player/deadbeef#2860]
2022 SEP 24
### Steps to reproduce the problem

Open directory file (flac) select open with deadbeaf
open window showing log
log:  dlopen error: libFLAC.so.8: cannot open shared object file: no such file or directory.

os: Arcolinux 5.19.10-arch1-1

### What's going on? Describe the problem in as much detail as possible.

Previous deadbeef version (before upgrade) works ok, but after upgrading, can't play flac files

### Information about the software:

Deadbeef version:
OS:

**Comment by Oleksiy-Yakovenko** [comment]
Please see https://github.com/DeaDBeeF-Player/deadbeef/issues/2855

**Comment by Entusiast** [comment]
> Please see #2855

After read #2855 I remove deadbeef using add/remove software. Then, installing deadbeef again, and the problem remains.

I open a folder with flac files, selecting one, then clic 'open with deadbeaf' and the problem loading libFlac.so.8 remain. And doesn't play the file. 

I use external hifiman DAC. ¿This could be the problem? (before last update, I play flac files with no problem, and with the same hardware)

DeadBeef-1.9.1
OS: Arcolinux
Kernel: 5.19.11 -arch1-1
![ArcoLinux_2022-09-26_17-40-18](https://user-images.githubusercontent.com/67836566/192393263-c49f591e-8b03-4c4a-8942-1c2991996f6f.png)

**Comment by Oleksiy-Yakovenko** [comment]
Either way, you're using an unofficial build of Deadbeef (I suppose, a package from a linux distro) -- they, the maintainers of that package, need to rebuild it to work with the new version of libFLAC.

(I wrongly assumed that you installed from AUR or something, where it builds from source code)

**Comment by Entusiast** [comment]
Thanks for your attention and answer.
...
Deadbeef is a very good player. Easy to use, simple, and powerfull.
