### ISSUE TITLE
5097 IOT instruction (core dumped)  ./deadbeef

### ISSUE THREAD

**Issue by strider85** [DeaDBeeF-Player/deadbeef#2864]
### Steps to reproduce the problem
random crashes

### What's going on? Describe the problem in as much detail as possible.
random crashes, I tried to run the app from the command line and that's the output:

double free or corruption (out)
[1]    5097 IOT instruction (core dumped)  ./deadbeef

Deadbeef version:1.9.2
OS: Arch Linux

**Comment by Oleksiy-Yakovenko** [comment]
Is there any other information than this?Did you use the official build of deadbeef? Is there a stack trace?

**Comment by strider85** [comment]
That's all I got from the command line.
I use the official deadbeef build, with just 2 plugins: Waveform Seekbar and Headerbar GTK3 UI. I'm using Archlinux and Gnome (Wayland).

**Comment by Oleksiy-Yakovenko** [comment]
What CPU do you have?

**Comment by strider85** [comment]
AMD Ryzen 7 5800X

**Comment by Oleksiy-Yakovenko** [comment]
ok.. there should not be any problems with running deadbeef on this CPU.

Any chance for you to reproduce the crash when running deadbeef using gdb?

Instructions are provided here:
https://github.com/DeaDBeeF-Player/deadbeef/wiki/Reporting-a-crash-using-gdb

**Comment by strider85** [comment]
Thread 162 (Thread 0x7fffe29fb6c0 (LWP 20386) "deadbeef-main"):
#0  0x00007fffed8160ca in  () at /opt/deadbeef/lib/deadbeef/flac.so
#1  0x00007fffed810eaa in  () at /opt/deadbeef/lib/deadbeef/flac.so
#2  0x00007fffed81286d in  () at /opt/deadbeef/lib/deadbeef/flac.so
#3  0x00007fffed8149f0 in  () at /opt/deadbeef/lib/deadbeef/flac.so
#4  0x00007fffed803df1 in  () at /opt/deadbeef/lib/deadbeef/flac.so
#5  0x00007ffff20174fb in waveform_generate_wavedata () at /home/michele/.local/lib/deadbeef/ddb_misc_waveform_GTK3.so
#6  0x00007ffff2017a34 in waveform_get_wavedata () at /home/michele/.local/lib/deadbeef/ddb_misc_waveform_GTK3.so
#7  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#8  0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

Thread 161 (Thread 0x7fff93fff6c0 (LWP 20384) "deadbeef-alsa"):
#0  0x00007ffff7ae6545 in clock_nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff7aeb057 in nanosleep () at /usr/lib/libc.so.6
#2  0x00007ffff7b16f19 in usleep () at /usr/lib/libc.so.6
#3  0x00007ffff1003167 in  () at /opt/deadbeef/lib/deadbeef/alsa.so
#4  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#5  0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

Thread 160 (Thread 0x7fffc16216c0 (LWP 20383) "alsa-pipewire"):
#0  0x00007ffff7b20d36 in epoll_wait () at /usr/lib/libc.so.6
#1  0x00007ffff07764f9 in  () at /usr/lib/spa-0.2/support/libspa-support.so
#2  0x00007ffff0768d01 in  () at /usr/lib/spa-0.2/support/libspa-support.so
#3  0x00007ffff03b0a9a in  () at /usr/lib/libpipewire-0.3.so.0
#4  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#5  0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

Thread 159 (Thread 0x7fffc2e246c0 (LWP 20381) "deadbeef-stream"):
#0  0x00007ffff7b20d36 in epoll_wait () at /usr/lib/libc.so.6
#1  0x00007ffff07764f9 in  () at /usr/lib/spa-0.2/support/libspa-support.so
#2  0x00007ffff0768d01 in  () at /usr/lib/spa-0.2/support/libspa-support.so
#3  0x00007ffff0361237 in  () at /usr/lib/libpipewire-0.3.so.0
#4  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#5  0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

Thread 158 (Thread 0x7fffe09f76c0 (LWP 20379) "deadbeef-main"):
#0  0x00007ffff7aa149c in  () at /usr/lib/libc.so.6
#1  0x00007ffff7a51958 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff7a3b53d in abort () at /usr/lib/libc.so.6
#3  0x00007ffff7a3b45c in  () at /usr/lib/libc.so.6
#4  0x00007ffff7a4a486 in  () at /usr/lib/libc.so.6
#5  0x00007ffff705b152 in  () at /usr/lib/libcairo.so.2
#6  0x00007ffff701a78a in  () at /usr/lib/libcairo.so.2
#7  0x00007ffff2015ac6 in waveform_draw () at /home/michele/.local/lib/deadbeef/ddb_misc_waveform_GTK3.so
#8  0x00007ffff2017a69 in waveform_get_wavedata () at /home/michele/.local/lib/deadbeef/ddb_misc_waveform_GTK3.so
#9  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#10 0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7fffe19f96c0 (LWP 19960) "dconf worker"):
#0  0x00007ffff7b13e5f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff61dde2f in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff61860d2 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff1acaebe in  () at /usr/lib/gio/modules/libdconfsettings.so
#4  0x00007ffff61b4c55 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#6  0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

**Comment by strider85** [comment]
Thread 8 (Thread 0x7fffe21fa6c0 (LWP 19959) "deadbeef-hotkey"):
--Type <RET> for more, q to quit, c to continue without paging--
#0  0x00007ffff7ae6545 in clock_nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff7aeb057 in nanosleep () at /usr/lib/libc.so.6
#2  0x00007ffff7b16f19 in usleep () at /usr/lib/libc.so.6
#3  0x00007fffece11b9a in  () at /opt/deadbeef/lib/deadbeef/hotkeys.so
#4  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#5  0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7fffe31fc6c0 (LWP 19957) "gdbus"):
#0  0x00007ffff7b13e5f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff61dde2f in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff6186d7f in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff637923c in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff61b4c55 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#6  0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffe39fd6c0 (LWP 19956) "gmain"):
#0  0x00007ffff7b13e5f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff61dde2f in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff61860d2 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff6186122 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff61b4c55 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#6  0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffe41fe6c0 (LWP 19955) "deadbeef-main"):
#0  0x00007ffff7a9c306 in  () at /usr/lib/libc.so.6
#1  0x00007ffff7a9eb20 in pthread_cond_wait () at /usr/lib/libc.so.6
#2  0x00000000004349d3 in cond_wait ()
#3  0x0000000000420854 in messagepump_wait ()
#4  0x000000000041e385 in player_mainloop ()
#5  0x000000000041fb16 in mainloop_thread ()
#6  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#7  0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7ffff2acd6c0 (LWP 19954) "deadbeef-server"):
#0  0x00007ffff7b1663c in select () at /usr/lib/libc.so.6
#1  0x000000000041e205 in server_loop ()
#2  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#3  0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffe49ff6c0 (LWP 19953) "deadbeef-stream"):
#0  0x00007ffff7ae6545 in clock_nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff7aeb057 in nanosleep () at /usr/lib/libc.so.6
#2  0x00007ffff7b16f19 in usleep () at /usr/lib/libc.so.6
#3  0x0000000000429113 in streamer_thread ()
#4  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#5  0x00007ffff7b21700 in  () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7ea1000 (LWP 19949) "deadbeef-main"):
#0  0x00007ffff7b13e5f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff61dde2f in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff61860d2 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff634d03e in g_application_run () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff6c973b8 in  () at /opt/deadbeef/lib/deadbeef/ddb_gui_GTK3.so
#5  0x000000000041f968 in main ()

**Comment by Oleksiy-Yakovenko** [comment]
it seems like you cut an important line of information, which tells which thread has crashed.

Typically, it comes right before the backtrace itself.

**Comment by Oleksiy-Yakovenko** [comment]
nvm, I see where the crash is:
```
Thread 158 (Thread 0x7fffe09f76c0 (LWP 20379) "deadbeef-main"):
#0  0x00007ffff7aa149c in  () at /usr/lib/libc.so.6
#1  0x00007ffff7a51958 in raise () at /usr/lib/libc.so.6
>>> #2  0x00007ffff7a3b53d in abort () at /usr/lib/libc.so.6
#3  0x00007ffff7a3b45c in  () at /usr/lib/libc.so.6
#4  0x00007ffff7a4a486 in  () at /usr/lib/libc.so.6
#5  0x00007ffff705b152 in  () at /usr/lib/libcairo.so.2
#6  0x00007ffff701a78a in  () at /usr/lib/libcairo.so.2
#7  0x00007ffff2015ac6 in waveform_draw () at /home/michele/.local/lib/deadbeef/ddb_misc_waveform_GTK3.so
#8  0x00007ffff2017a69 in waveform_get_wavedata () at /home/michele/.local/lib/deadbeef/ddb_misc_waveform_GTK3.so
#9  0x00007ffff7a9f74d in  () at /usr/lib/libc.so.6
#10 0x00007ffff7b21700 in  () at /usr/lib/libc.so.6
```

**Comment by Oleksiy-Yakovenko** [comment]
It seems that waveform seekbar plugin is doing something odd.

**Comment by Oleksiy-Yakovenko** [comment]
Another user has reported the same issue #2865, but with more informative backtrace.

**Comment by strider85** [comment]
I solved it by installing the latest version of the plugin.
