### ISSUE TITLE
Deadbeef randomly crashing when a song ends on latest version

### ISSUE THREAD

**Issue by f0pdoodle** [DeaDBeeF-Player/deadbeef#2865]
### Steps to reproduce the problem

Open deadbeef
Start playing a song
Song ends
Sometimes the next one begins fine
Sometimes song doesn't begin
Entire window crashes
Can't close it normally, have to close it in htop

The way I reproduce it consistently is by repeatingly spamming next song which makes it crash within 5-10 seconds.

### What's going on? Describe the problem 

I've been getting random crashes on the latest deadbeef build 1.9-2-2. It crashes after a song ends, or I play the next one manually. Sometimes it only happens after one song is played, sometimes a couple. It always happens when I spam next song very quickly. The crashes don't happen very consistently, but if I just do nothing while it's playing in the background, it usually happens every 20 minutes or so, it also doesn't seem to matter which song is playing although all of my songs are in .mp3.

### Information about the software:
CPU: AMD Ryzen 5 3600
audio: pulseaudio

I have a lot of plugins installed: musical spectrum, spetrogram, lyric bar, vu meter, pretty much all of them.
The crashes only occur on the new version deadbeef 1.9.2-2, 1.9.1-1 is fine.

Deadbeef version: deadbeef 1.9.2-2
OS: archlinux
DE: KDE Plasma 5.25.5

Here is the gdb log:
https://pastebin.com/TXYHkf8w

Judging by this line:

send_with_reply_and_block error: (Created too many similar notifications in quick succession)

I thought it had something to do with the notification plugin mixing with KDE Plasma. But, the crashes still happen if I uncheck 'Fix for KDE 2.23.5' in the OSD Notify configuration menu, and even if I completely disable the notification plugin.

Here is a gdb log where I had the notification plugin disabled:

https://pastebin.com/5sqdDeRn

The issue is also present when using the deadbeef-git package from the AUR.

I'm not sure how to fix this, so I downgraded back to the 1.9.1-1 and all is fine there. I also wanted to thank you for making sure a great music player, regardless of this issue.

**Comment by f0pdoodle** [comment]
It might be an issue with kde plasma and the osd-notify plugin, judging by this line in the gdb log: 

send_with_reply_and_block error: (Created too many similar notifications in quick succession)

The crashes still happen if I uncheck 'Fix for KDE 2.23.5' in the OSD Notify configuration menu, and even if I completely disable the notification plugin.

**Comment by f0pdoodle** [comment]
> Seems like there's a new deadlock that was introduced in 1.9.2, which may affect plugins which decode audio files (converter, waveform-seekbar, etc). Thanks for detailed backtrace. I'll look into it.

No problem. I appreciate all the work you've put into this, so take your time.

**Comment by Oleksiy-Yakovenko** [comment]
@f0pdoodle another user in the #2864 mentioned that installing the latest version of waveform-seekbar plugin has solved the problem.

**Comment by f0pdoodle** [comment]
> @f0pdoodle another user in the #2864 mentioned that installing the latest version of waveform-seekbar plugin has solved the problem.
I tried updating the plugin from the AUR, and then straight from their github, doesn't seem to work, I removed the plugin entirely just to see and that didn't change anything either.

**Comment by kpcee** [comment]
> Seems like there's a new deadlock that was introduced in 1.9.2, which may affect plugins which decode audio files (converter, waveform-seekbar, etc). Thanks for detailed backtrace. I'll look into it.

I have the same problem in one of my plug-ins, which makes the latest version of DeaDBeeF freeze. The problem is the call of  
`DB_playItem_t *playedSong = deadbeef->streamer_get_playing_track();  `
As long as a song is playing everything works, but as soon as no song is playing the call leads to a freeze of the UI.

**Comment by Oleksiy-Yakovenko** [comment]
oh, nice find. this is actually pretty difficult to find.
It was introduced in May 2022, and the diff looks like this:
```
@@ -321,10 +323,12 @@ streamer_get_streaming_track (void) {
 
 playItem_t *
 streamer_get_playing_track (void) {
+    streamer_lock();
     playItem_t *it = (buffering_track && !playing_track) ? buffering_track : playing_track;
     if (it) {
         pl_item_ref (it);
     }
+    streamer_unlock();
     return it;
 }
```

It would deadlock if some code calls this function from inside a pl_lock/unlock block. Which, technically, always was a problem -- the lock structure is such that it's only allowed to call pl_lock inside of streamer_lock, but not the other way around.

However, I understand that it can be quite problematic to enforce this correct behavior in the plugins. I'll see if I can make some kind of workaround.

**Comment by Oleksiy-Yakovenko** [comment]
Latest master should work without deadlocks. However, it is recommended to update the plugins to use `streamer_get_playing_track_safe` (in a correct way of course)

**Comment by f0pdoodle** [comment]
Latest master works as expected, thanks!
