### ISSUE TITLE
Nothing happens when Design Mode is enabled, and the setting doesn't persist upon application exit/restart

### ISSUE THREAD

**Issue by 0x199x** [DeaDBeeF-Player/deadbeef#2872]
### Steps to reproduce the problem

1. Go to View, and tick "Design Mode"
2. Exit Deadbeef
3. Relaunch deadbeef

### What's going on? Describe the problem in as much detail as possible.

Two issues:
- Nothing happens visually when Design Mode is turned on
- If I enable Design mode, and then exit and relaunch Deadbeef, the menu shows Design Mode is disabled

### Information about the software:

Deadbeef version:  devel, compiled minutes ago
OS: EndeavourOS 

https://user-images.githubusercontent.com/89231731/195151132-da3720f6-210c-47dc-ae1c-35cecd899bbe.mp4

**Comment by Oleksiy-Yakovenko** [comment]
When you enable design mode the first time -- you should see a little dialog, giving quick instructions how to use it, with a checkbox to never show it again. You probably checked it off.

Other than that, everything you described everything works as it should.
Design mode is not supposed to persist after restart.
Try using mouse right click on various UI elements, and you'll probably figure out how to use it.

**Comment by Oleksiy-Yakovenko** [comment]
> When you enable design mode the first time -- you should see a little dialog, giving quick instructions how to use it, with a checkbox to never show it again. You probably checked it off.

Sorry, I forgot that this has been made only on mac. GTK / Linux version doesn't seem to have this.
Anyway, try right clicking on the UI, and you'll see how to use it.

**Comment by 0x199x** [comment]
Gotcha, I see how that works now.  Thanks.  I misunderstood the purpose of design mode
