### ISSUE TITLE
cocoaui/mac: no artwork image does not load

### ISSUE THREAD

**Issue by tomjepp** [DeaDBeeF-Player/deadbeef#2877]
### Steps to reproduce the problem
Create an album art column and load a file with no album art:
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/637494/196555981-93fd954c-eb8e-4124-a8c2-b02a2eaa7a28.png">

### What's going on? Describe the problem in as much detail as possible.
It's trying to load `DeaDBeeF.app/Contents/Resources/pixmaps/noartwork.png`, but that file is actually located at `DeaDBeeF.app/Contents/Resources/noartwork.png`.

Editing the pixmaps path on macOS to just be the same as the resources path works, but I'm not sure that's a suitable fix? for example: https://github.com/tomjepp/deadbeef/commit/cdec1ca7bdb83f6d114150c34725235c1980c522

### Information about the software:
Deadbeef version: DeaDBeeF macOS nightly from https://deadbeef.sourceforge.io/download.html, as well as a build of master from 9c7025d83a8e88134a20e2ff870ee1f7b161f724
OS: macOS Monterey 12.6

**Comment by mirko77** [comment]
It does not load from embedded metadata in `.opus` files either.

**Comment by Oleksiy-Yakovenko** [comment]
@mirko77 loading embedded images from .ogg (and opus) files was just added yesterday
It's unrelated to this bug.

**Comment by mirko77** [comment]
@Oleksiy-Yakovenko ok, thank you. Good to know
