### ISSUE TITLE
Lyrics only returned partially when text contains semicolon

### ISSUE THREAD

**Issue by mihawk90** [DeaDBeeF-Player/deadbeef#2881]
### Steps to reproduce the problem
1. install [lyricbar plugin](https://github.com/loskutov/deadbeef-lyricbar) and add a panel for it
2. play track with lyrics containing one or more `;`
3. check lyrics sidebar

### What's going on? Describe the problem in as much detail as possible.
When playing a song containing a semicolon `;` the lyrics are only shown up to that point.
I'm not super familiar with C++ so I am hoping I'm reporting this in the right place.
At first I assumed this was an issue with the plugin, however when I take a look at their code, they seem to just get the lyrics straight from DB without doing any transformation of their own:

https://github.com/loskutov/deadbeef-lyricbar/blob/a1b2dbac3439086b50c85315d640d852ad2e816b/src/utils.cpp#L87-L95

So it seems DB is only returning up to the first occurance of a semicolon by itself. If I were to guess I'd say this is because DB is assuming this to be a multi-value field, which for most fields makes sense, however for fields like lyrics or even the comments field, this doesn't seem to make a whole lot of sense.

Info from `metaflac` and `mediainfo` lists only a single field (as intended):

```
z% mediainfo 18\ Amsterdam.flac 
General
Complete name                            : 18 Amsterdam.flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
[...]
Lyrics                                   : [Verse 1] / I'm sorry, mother, I'm sorry, I let you down / Well, these days I'm fine; no, these days I tend to lie /  / I'll take the Western train, just by the side of Amsterdam [...]
```

```
z% metaflac --export-tags-to=- 18\ Amsterdam.flac 
[...]
LYRICS=[Verse 1]
I'm sorry, mother, I'm sorry, I let you down
Well, these days I'm fine; no, these days I tend to lie

I'll take the Western train, just by the side of Amsterdam
[...]
```

In the lyrics sidebar, this ends up like this:
![image](https://user-images.githubusercontent.com/556162/198860102-d5ad2dea-3e65-4f4d-bf29-7d0c9f17bcb8.png)

### Information about the software:

Deadbeef version: 1.9.2
deadbeef-lyricbar version: 3d75413
OS: Fedora

PS: Apparently that plugin has been abandoned now (see README), any chance this could get forked under the Deadbeef org?

**Comment by Oleksiy-Yakovenko** [comment]
Hello,

I investigated a bit, the bug occurs after editing tags in deadbeef (reading tags written by other apps will work fine).

**Comment by Oleksiy-Yakovenko** [comment]
I didn't find a better way to solve this than to treat Comment and Lyrics fields as special case, which should not be split by semicolons into multiple values. In order to fix the files which already have the incorrectly written lyrics fields -- you'll need to edit and overwrite the lyrics in such files, they will not get fixed automatically.

**Comment by mihawk90** [comment]
> I investigated a bit, the bug occurs after editing tags in deadbeef (reading tags written by other apps will work fine).

Hey, thanks for investigating :)

The tags were actually written with Picard, I haven't touched them in Deadbeef.

I assume when editing them in deadbeef they were split into multiple fields? That's why I read them using metaflac, to make sure they were in a single field :D 

> I didn't find a better way to solve this than to treat Comment and Lyrics fields as special case

Figures, but I don't see a case where one would need this anyway, different languages aside maybe?
