### ISSUE TITLE
Deadbeef plays mono track in left channel only. A more desirable behaviour would be to play in both left and right.

### ISSUE THREAD

**Issue by jonpatterns** [DeaDBeeF-Player/deadbeef#2882]
### Steps to reproduce the problem

Play mono track; tried both flac and mp3

### What's going on? Describe the problem in as much detail as possible.

Deadbeef plays mono track in left channel only. A more desirable behaviour would be to play in both left and right. I can’t find an option for this.

### Information about the software:

Plugins has ‘Mono to Stereo’, not sure if this is for this purpose or something else.

Deadbeef version: 1.9.2
OS: Manjaro Linux  - using Jack sound system.

**Comment by Oleksiy-Yakovenko** [comment]
Hi, you can add the Mono 2 stereo plugin in the DSP chain, and it will solve this problem.

I thought I have solved this problem specifically in 1.9.2 release - at least with more common output plugins.
I will have to check it.

**Comment by Oleksiy-Yakovenko** [comment]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/1895698/198874699-92eef71f-0430-4954-b1cf-4969b38beee1.png">

**Comment by jonpatterns** [comment]
Thanks, for the quick response. My mistake, I didn't realize I had to add to DSP chain. Doing that fixed the problem.

Brilliant! : -)

**Comment by Oleksiy-Yakovenko** [comment]
I double checked this issue, and it seems like this should work correctly under normal circumstances (mono -> stereo conversion should automatically duplicate the single channel into L+R).
However, I'm assuming that there can be an issue when using Jack, which itself can be configured to play Mono as "left only" -- in which case deadbeef can only provide a workaround, such as "mono to stereo" DSP plugin.
Closing.
