### ISSUE TITLE
Playing SHOUTcast streams freezes UI in v1.9.2.

### ISSUE THREAD

**Issue by bubbleguuum** [DeaDBeeF-Player/deadbeef#2885]
Deadbeef version: 1.9.2
Distro: openSUSE Tumbleweed

Repro steps:

- File > Add location
- add this SHOUTcast cast stream:  http://stream.novafm.dk/nova128.m3u
- attempt to play it
=> UI Freeze entirely. deadbeef process can be killed with SIGTERM.

This seems to also happen with other SHOUTcast streams.

v1.9.1 works fine, which makes me thinks it is a deadbeef issue rather than a distro (compiling or packaging) issue.

**Comment by Oleksiy-Yakovenko** [comment]
@bubbleguuum there was one similar deadlock issue, which got resolved in 1.9.3.
Can you try it and see whether issue still occurs for you?

**Comment by bubbleguuum** [comment]
I download and ran this static version:
https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9.3/deadbeef-static_1.9.3-1_x86_64.tar.bz2/download

And it hangs the same way playing SHOUTcast streams.
I started the static version with the default config, to make sure my existing config would not cause problems.
Interestingly, this SHOUTcast stream plays fine:  http://direct.fipradio.fr/live/fipbordeaux-midfi.mp3

**Comment by Oleksiy-Yakovenko** [comment]
ok thanks

**Comment by bubbleguuum** [comment]
Thanks you for the quick fix !
