### ISSUE TITLE
Installed deadbeef.desktop fails validation

### ISSUE THREAD

**Issue by slashbeast** [DeaDBeeF-Player/deadbeef#2887]
### What's going on? Describe the problem in as much detail as possible.

The installed from template deadbeef.desktop file fails validation of https://freedesktop.org/wiki/Software/desktop-file-utils/

```
% desktop-file-validate /usr/share/applications/deadbeef.desktop
/usr/share/applications/deadbeef.desktop: error: value "Play;Pause;Toggle Pause;Stop;Next;Prev;" for key "Actions" in group "Desktop Entry" contains invalid action identifier "Toggle Pause",
only alphanumeric characters and '-' are allowed
/usr/share/applications/deadbeef.desktop: error: file contains group "Desktop Action Toggle Pause", which has an invalid action identifier, only alphanumeric characters and '-' are allowed
/usr/share/applications/deadbeef.desktop: error: action group "Desktop Action Next" exists, but there is no matching action "Next"
/usr/share/applications/deadbeef.desktop: error: action group "Desktop Action Stop" exists, but there is no matching action "Stop"
/usr/share/applications/deadbeef.desktop: error: action group "Desktop Action Prev" exists, but there is no matching action "Prev"

```

### Information about the software:

Deadbeef version: 1.9.2
OS: Gentoo ~amd64

**Comment by Oleksiy-Yakovenko** [comment]
This can't really be fixed, as far as I know.
We define some actions used in Ubuntu, and they are valid and functional, but they fail validation of some tools which think that those actions are invalid.

Although if you can provide a working solution for this problem - I'd gladly accept it.

**Comment by slashbeast** [comment]
Ack, thanks for responding!
