### ISSUE TITLE
Alsa cracking,hissing, too fast sound , pulse works good

### ISSUE THREAD

**Issue by ziomek64** [DeaDBeeF-Player/deadbeef#2888]
### Steps to reproduce the problem 
No idea at this point

### What's going on? Describe the problem in as much detail as possible.
Well today i woke up and wanted to play music but I couldn't stand this completely destroyed sound. From what I've gathered it's on alsa, pulse works fine. Some songs will be cracking, some will be just bass and nothing else, some will be fine but playing at 2x speed or half speed.  Some of them will actually play correctly . Strangely enough when playing this completely destroyed song and when I double click on it it will work fine second time.

I don't know what should I do to be honest. Other players with alsa work.
### Information about the software:

Deadbeef version: 1.9,3
OS: EndeavourOS (arch-based)

**Comment by calin-semeniuc** [comment]
Same problem. It seems to fix if I try again other tracks. I also use EndeavourOS and the problem seems to appear also on mpv.

**Comment by ziomek64** [comment]
@calin-semeniuc it might be pipewire alsa issue then? There were some updates, i have 0.3.60 version

**Comment by Oleksiy-Yakovenko** [comment]
Related to #2886?

**Comment by Oleksiy-Yakovenko** [comment]
It is not clear to me what is going on, and whether it's pipewire or not. If it is pipewire -- there's nothing I can do at the moment -- please see my comment in #2886.

**Comment by ziomek64** [comment]
But i'm playing with alsa dont I?

**Comment by Oleksiy-Yakovenko** [comment]
I don't have a way of knowing this. If you have an active sound server installed -- it would intercept the audio playback, regardless of which API is used.
