### ISSUE TITLE
Can't set space to toggle pause locally

### ISSUE THREAD

**Issue by TheTerrior** [DeaDBeeF-Player/deadbeef#2889]
### Steps to reproduce the problem
Go into the hotkeys, bind space to toggle pause, local.

### What's going on? Describe the problem in as much detail as possible.
This should cause deadbeef to play and pause when space is pressed, but instead nothing happens. If I set it to global, then it works (but obviously setting space to toggle pause globally is problematic). Other keybinds do work locally, like ctrl+space. I've also tried play/pause, and it has the same behavior as toggle pause. Other keybinds like c (default for toggle pause) work as intended, it's just space that's acting strange.

### Information about the software:
Deadbeef version: 1.9.3 (latest on Arch repos)
OS: Arch Linux

**Comment by kpcee** [comment]
Hmm, I can't confirm this, works perfectly here with space als local shortcut. Arch Linux, Xfce, Deadbeef 1.9.3.
