### ISSUE TITLE
It was nice to see the language pool of the DeadBeef growing. What happened to Russian translation of the interface?!

### ISSUE THREAD

**Issue by simurq** [DeaDBeeF-Player/deadbeef#2901]
### Steps to reproduce the problem
Отсутствует перевод интерфейса на русском.
No Russian translation.

### What's going on? Describe the problem in as much detail as possible.
Не можем найти русский перевод интерфейса, который раньше присутствовал в пакете.
Cannot find the Russian translation of the interface, which was available previously.

Deadbeef version: 1.9.1
OS: Pop!_OS (Ubuntu/Linux)

Hi there, can you please advise where my team and I can find the Russian translation of DeadBeef interface? As I said, the translation was previously available and widely popular among the team but now we cannot find it in the repo anymore.

It's not a big deal, as my team and I are fluent in 4 languages, which are still shipped with DeadBeef - we can switch to one of them anyway. **But it was nice to see the language pool of the DeadBeef growing...**

Thank you!

**Comment by Oleksiy-Yakovenko** [comment]
It has been removed.
