### ISSUE TITLE
macOS Version / Column

### ISSUE THREAD

**Issue by big610** [DeaDBeeF-Player/deadbeef#2904]
macOS Version Number #
macOS DeadDBeeF/About/devel (6abb658)
What software app can I use to decipher (6abb658)? What do you use & your method?
macOS software reads the version number as devel. 
An example using any 3rd party app, tells me my current version is Version:devel Date:12/22/22 & my version is out of date I need Version:1.9.4 Date:12/17/22.
This issue has always existed. 
My only macOS Download is here: https://sourceforge.net/projects/deadbeef/ this is the only macOS Download, labeled as Nightly, & also here: https://deadbeef.sourceforge.io/download.html Both are the identical. No Stable. Software Update Software nags me to get the Stable, when none exists. 

Column Feature Request:

Track Properties:
Ability to show all/add in a Column. Instead of having to go to Properties for each individually. 

Title / Track Artist Column
How do I refresh reload all Columns in one command click? Is it possible? Can it be added to implement?

**Comment by Oleksiy-Yakovenko** [comment]
I'm sorry, but I can't understand what you wrote.

**Comment by big610** [comment]
What language would you prefer I translate or send screenshots?

**Comment by Oleksiy-Yakovenko** [comment]
English would be great.

**Comment by big610** [comment]
![DeaDBeef devel (6abb658)](https://user-images.githubusercontent.com/35133409/209406229-209515e4-606c-4304-893a-56fa45c87e73.png)
Need Stable Version Number. Does not read 1.9.4

**Comment by Oleksiy-Yakovenko** [comment]
From README.md on github: https://github.com/DeaDBeeF-Player/deadbeef/blob/master/README.md
There is no stable / released version of deadbeef for macOS. Only development builds.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/1895698/209406329-dcd16c89-eb98-4760-a05c-52e77f2e9904.png">

**Comment by big610** [comment]
![DeeDbeeF http Column :Refresh](https://user-images.githubusercontent.com/35133409/209407275-85064442-589d-4a80-8df3-d0cedff926b4.png)
Feature Request:
Track Properties:
Ability to show all/add in a Column the https. Instead of having to go to Properties for each individually to view each http.
Refresh Button, to refresh al current streams.

**Comment by Oleksiy-Yakovenko** [comment]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/1895698/209409095-b40fb744-85f8-4a27-93c9-1ebadea61230.png">

**Comment by Oleksiy-Yakovenko** [comment]
%path% works too

**Comment by Oleksiy-Yakovenko** [comment]
There's no way to "refresh" stream titles etc without playing them all.
I have added a feature request for you:
https://github.com/DeaDBeeF-Player/deadbeef/issues/2905

**Comment by big610** [comment]
To add the Track Properties Location http path's, to a Column;
 I see nothing defined in DeeDBeeF Preferences. Where is Type:Custom location? This would be to add a Custom Column?

**Comment by Oleksiy-Yakovenko** [comment]
You can right click the columns and click Add
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1895698/209410154-b6ba04d4-a3de-4565-a860-405717db85df.png">

**Comment by big610** [comment]
Thank you Column Add with your suggestion: %path% , is perfect.
I will wait patiently to test Refresh in #2905, see how the ability works. I'm running Radio Station streams, hoping to re-see the Radio Stations title, overtaken by Title & Artist.

What software app can I use to decipher your # (6abb658) What do you use & your method? What kind of number format is it?

**Comment by Oleksiy-Yakovenko** [comment]
It's a SHA1 commit hash from git. There is nothing to decipher.

**Comment by Oleksiy-Yakovenko** [comment]
It points to a revision from which the build was made -- as you can see, you can click it on github, and navigate to the specific change in the code.

**Comment by Oleksiy-Yakovenko** [comment]
btw, you should download the newest build -- since the build that you have contains an unfortunate bug that I introduced today in the morning (in the revision https://github.com/DeaDBeeF-Player/deadbeef/commit/6abb658d9802d7d1a16d95fb17113a927fb2ad56) -- and I just fixed it 30 min ago.

**Comment by big610** [comment]
Thank you for version attention bug alert. With macOS having no Stable, only a Nightly, I would wait for 3rd party macOS Software to tell me like today, 1.9.3 moved to 1.9.4. Then take what the Nightly offered. 

https://github.com/DeaDBeeF-Player/deadbeef/blob/master/ChangeLog
I see you do when you have time. Can you please add a date, going forward. Understand you personal life & rest comes first.
I would parallel your Change for a new Version then take & update the macOS Nightly, what you are offering.
I wish you could put out 1 stable macOS every few months or 3-4 months, when you have time.
