### ISSUE TITLE
Metadata Display 

### ISSUE THREAD

**Issue by jauntyd** [DeaDBeeF-Player/deadbeef#2908]
Hello:
I love using the music player, first of. I do, however, have one small request....at least I hope it's not a big deal. 

If you select a track in the playlist view by right-clicking, then selecting "Track Properties" there is a window with the file's metadata.

When I format the metadata in Mousepad, while matching the font size and font family to Deadbeef, the music player displays a second column of metadata unaligned. 

Please see: https://i.imgur.com/N5AMbuy.png
On the right is Mousepad, where I enter the metadata. On the left is my Deadbeef display. I am trying to get Deadbeef to display the text like it is in Mousepad....aligned.

Deadbeef version: 0.7.2
OS: FreeBSD 13.1-RELEASEp5 (installed from ports)

If I can be of any assistance, please let me know.
Thanks in advance!
Jauntyd

**Comment by Oleksiy-Yakovenko** [comment]
I don't know whether it's hard or easy.. In theory, it may be possible to tell the GtkTreeView to use certain tab stops, but I don't know whether it's possible in reality.

**Comment by jauntyd** [comment]
I was able to achieve what I was looking for. I am using tagutil, YAML, Mousepad and FreeBSD to paste metadata into Deadbeef and I wanted to have multiple columns in a specific tag aligned.

1. Paste metadata into desired tag name (the example above uses "Credits")
2. Indent, with spaces, the metadata
3. Change from indenting with spaces to indent with tabs
4. Set tab width at 9
5. Align metadata and enjoy!

**Comment by Oleksiy-Yakovenko** [comment]
@jauntyd does it mean that the issue should be closed?
I doubt this is really doable in any meaningful way -- you won't be able to make all audio players / tag viewers / editors to align the text the same way.

**Comment by jauntyd** [comment]
Yes, I think it should be closed.
