### ISSUE TITLE
Track Properties via shortcut can display wrong files

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2910]
### Steps to reproduce the problem
1. A hotkey was created (F2) → Selected Tracks → Track properties.
2. Create two playlists, A and B and fill them with some songs.
3. In playlist A you select one or more files and click in the context menu Track Properties, then you close the window with Close, then press F2, the displayed information is identical. 
4. Now switch to Playlist B and select one or more files and press F2.

### What's going on? Describe the problem in as much detail as possible.
Now the selected tracks from playlist B are not displayed, but from playlist A as before.
Even if you now double-click on a track in playlist B and press F2, nothing changes and the wrong files are displayed. Only if you click again on context menu → Track Properties the selected files from playlist B are displayed.

### Information about the software:
Deadbeef version: 1.9.4
OS: Linux

**Comment by kpcee** [comment]
Wow that was super fast! :thumbsup: I wish you a nice weekend.

**Comment by Oleksiy-Yakovenko** [comment]
you too! :)

**Comment by kpcee** [comment]
Thank you!
