### ISSUE TITLE
Can't get alsa audio to work when using deadbeef from nix. And I get a diferent issue if using pulseaudio instead.

### ISSUE THREAD

**Issue by Samueru-sama** [DeaDBeeF-Player/deadbeef#2913]
I'm using Void linux, deadbeef is availbe in the official repos however the current version is very old and does not support my configuration file, I also have the nix package manager installed so I decided to give it a go and well it almost works.

When using Alsa output plugin, nothing plays, I get this error in the terminal: 

ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/nix/store/rz45273l509rqn3m61pcgc26kaj41nj5-alsa-lib-1.2.7.2/lib/alsa-lib/libasound_module_pcm_pulse.so: cannot open shared object file: No such file or directory)
could not open audio device (No such device or address)
failed to init sound output

Normally I setup deadbeef with the alsa output plugin and the output device defaults to the pulseaudio sound server, this how I always got it to work.

If I instead use the pulseaudio plugin, which does work in this case, I get a weird bug with the animations in deadbeef when playing music which become very very laggy, they look as if they are playing at 5 fps.

And this issue with the animations when using pulseaudio isn't new, I also had it when using deadbeef in several other linux distributions, but since using ALSA with the pulseaudio server fixed the issue, I've never bothered to go into much detail as to why it happens.

### Information about the software:

Deadbeef version: 1.9.4. There are two versions in the nix package manager, one with and without plugins, both have the same issues.
OS: Void Linux x86_64 Kernel 6.1.9.

**Comment by Oleksiy-Yakovenko** [comment]
Hi, this doesn't seem like deadbeef bug to me..
It seems like you forgot to install some package.
You seem to be missing this package: [alsa-plugins-pulseaudio](https://voidlinux.pkgs.org/current/voidlinux-main-aarch64/alsa-plugins-pulseaudio-1.2.7.1_1.aarch64.xbps.html)

**Comment by Samueru-sama** [comment]
> Hi, this doesn't seem like deadbeef bug to me.. It seems like you forgot to install some package. You seem to be missing this package: [alsa-plugins-pulseaudio](https://voidlinux.pkgs.org/current/voidlinux-main-aarch64/alsa-plugins-pulseaudio-1.2.7.1_1.aarch64.xbps.html)

Hi Oleksiy, sorry but I do have that depency installed already, I posted both issues since a solution to either works for me.

The other issue with deadbeef lagging when using pulseaudio instead of alsa is something that might be a bug, it is an issue that I've had with several different linux distributions, and I didn't have to deal with it since I didn't have the issue with alsa, but now since I can't get alsa to work I have to deal with it.

Here is a long reddit thread that I made a few months ago when I encountered the lag issue thinking that it was video driver related when it wasn't.

https://www.reddit.com/r/archlinux/comments/yrehie/deadbeef_lags_only_when_im_not_watching_videos_on/

I also posted this video showing exactly the problem: https://streamable.com/uxrrdn

Notice what happens when I close pavu control, all the animations in the player become very laggy. 

launching deadbeef with PULSE_LATENCY_MSEC=5 deadbeef on the terminal fixes the issue. Changing the buffer size of the pulseaudio plugin doesn't fix it though.

**Comment by Oleksiy-Yakovenko** [comment]
The other (lagging) issue is a known problem, it can be fixed by installing a "pulse2" plugin and using it instead of the "build-in" pulse plugin.
You can find it prebuilt in the plugin downloads page:
https://deadbeef.sourceforge.io/plugins.html

**Comment by Oleksiy-Yakovenko** [comment]
> Hi Oleksiy, sorry but I do have that dependency installed already

It's still not a deadbeef problem -- it's a message from ALSA that says that it can't find a plugin.

**Comment by Samueru-sama** [comment]
> The other (lagging) issue is a known problem, it can be fixed by installing a "pulse2" plugin and using it instead of the "build-in" pulse plugin. You can find it prebuilt in the plugin downloads page: https://deadbeef.sourceforge.io/plugins.html

Thanks, unfourtunatly that didn't work either, I can setup the plugin in the preferences but it still uses the default one, and if I remove the default plugin I can no longer use pulseaudio as the output plugin.

As a solution what I have right now is exporting the PULSE_LATENCY_MSEC=5 to my ~/.profile in the mean time, until deadbeef gets updated to a newer version in the void repos.
