### ISSUE TITLE
Работа поиска в режиме фильтра

### ISSUE THREAD

**Issue by poedyatel** [DeaDBeeF-Player/deadbeef#2916]
Добавьте пожалуйста режим при котором поиск будет фильтовать плейлист и оставлять только треки имеющие запрашиваемое вхождение в любом из тегов или имени, как это сделано у clementine. 
Это очень удобный инструмент для некоторых специфичных задач связанных с сортировкой, например я хочу увидеть в большой коллекции сразу все варианты какой-то одной песни, или ищу ремиксы. Да и в целом такой поиск эффективней 
По факту я вообще не пользуюсь текущим поиском, слишком часто он не позволяет найти то что я хочу, поскольку я могу не помнить точного названия песни, помню какое то слово, не всегда первое, или помню артиста. Ввожу слово что помню, попадаю совершенно на другую песню где тоже такое слово есть. Ввожу артиста, попадаю либо на другую песню, либо вообще на кавер. 
Например я искал песню rammstein одноименного коллектива, так и написал, получил такой ответ:
![image](https://user-images.githubusercontent.com/114159416/219875293-f25a393e-395a-4c30-83e6-440baf5aeaf3.png)

Clementine фильтрует список и я вижу то что мне нужно:
![image](https://user-images.githubusercontent.com/114159416/219875340-07c2df14-ce93-4dba-9bc0-fd3c84d49359.png)

**Comment by Oleksiy-Yakovenko** [comment]
Hello, and good evening.

Issues created in any other language than English are considered invalid, and will be discarded.
