### ISSUE TITLE
Сохранение пользовательского шаблона группировки плейлиста

### ISSUE THREAD

**Issue by poedyatel** [DeaDBeeF-Player/deadbeef#2917]
Я использую пользовательскую группировку плейлиста, иногда нужно её отключать, но тогда составленный шаблон забывается, пожалуйста, сделайте так чтобы он сохранялся, не очень удобно хранить шаблон в тектовом файле.
Возможно имеет смысл сделать поддержку более чем одного пользовательского шаблона, но мне вполне хватает двух режимов отображения - без группировки и мой шаблон.

**Comment by Oleksiy-Yakovenko** [comment]
Hello, and good evening.

Issues created in any other language than English are considered invalid, and will be discarded.
