### ISSUE TITLE
Hot keys for time navigation

### ISSUE THREAD

**Issue by artenax** [DeaDBeeF-Player/deadbeef#2919]
Здравствуйте.
С удивлением обнаружил, что в deadbeef нет горячих клавиш для перемотки по треку. Сделайте, пожалуйста. На любое разумное время.
В Audacious есть, хоть и надо настраивать.

Зачем это может быть нужно?
Представьте, например, слепой или слабовидящий человек слушает многочасовые аудиокниги и хочет пропустить уже прослушанное ранее. Или просто человек лежит на диванчике в наушниках, клавиатура рядом, а до мыши далеко тянуться. Горячие клавиши переключения на следующий/предыдущий трек есть, а для навигации внутри трека нет. А он может быть большим, в случае аудиокниг.

**Comment by Oleksiy-Yakovenko** [comment]
Hello, and good evening.

Issues created in any other language than English are considered invalid, and will be discarded.
