### ISSUE TITLE
spectrum is rendered/drawn into y-axis labels

### ISSUE THREAD

**Issue by Logicwax** [DeaDBeeF-Player/deadbeef#2925]
### Steps to reproduce the problem

I'm using 1.9.5 on ubuntu 22.04.   I have the spectrum visualization configured across the entire bottom of the interface, and it appears that spectrum freq lines are rendered even on-top of the y-axis labels as opposed to being rendered within the confines of the axis labels..  Here is an attached screenshot:
https://imgur.com/a/YIwkREi

Deadbeef version: 1.9.5
OS: ubuntu 22.04 (wayland, gnome 42.5)

**Comment by Logicwax** [comment]
I tried the latest nightly, and this issue still persists (maximizing to fullscreen looks fine though).   but any other size of window the same issue persists.

**Comment by Oleksiy-Yakovenko** [comment]
This is what I'm seeing in the latest build from master branch:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/1895698/226099726-d34c92c6-332b-4ae9-b8b4-19f3068a0188.png">
