### ISSUE TITLE
Different behaviors for covers depending on design

### ISSUE THREAD

**Issue by Npa972** [DeaDBeeF-Player/deadbeef#2926]
**Design A**
With classic design mod, all my albums have covers.
I had to add some off them manually (thanks for "simplified cache covers" option).
Actually everything is perfect with covers in this design. No one is missing for each album even when changing track playback (i mean it's OK for the entire album).
![Capture d’écran_2023-02-25_15-39-18](https://user-images.githubusercontent.com/49346431/221376706-121ec72d-4c7f-4072-ba36-7ba2abb7562b.png)

**Design B**
I would like a new design with cover and spectrum in panels.
![Capture d’écran_2023-02-25_15-36-31](https://user-images.githubusercontent.com/49346431/221377030-630352a2-ab32-4876-9fab-6aeca9689519.png)
But for some album (generally OGG or OGA) i just have the covers for the first track. I did not check all my album.
And Deadbeef create a "false" (text files) cover for **each** track in cache (covers2).
I check that covers are well embedded in all the track of the album : OK
I think the cover management is different in the two design.
My question : is there a way that Design B works like design A (album per album)

Thanks to make DeaDBeeF better and better.

Deadbeef version: 1.9.5
OS: Archlinux

**Comment by Oleksiy-Yakovenko** [comment]
Seems like a big to me.. I don't know why this happens, will need to investigate.

**Comment by Npa972** [comment]
I did a few more checks.
- a cover seems to be created for each selected track in design B with **multi artists album**. No cover is created with single artist album (the cover already in cache is used).
- in design A a cover is created for each album (based on first track ?)
- it seems that it only concerns multi-artist albums (album artist = VA)
- OGG formats are concerned but also some albums in mp3

Not simple...

**Comment by Npa972** [comment]
Hi Oleksiy, i took time to investigate and i had a tag problem.
I retag all affected albums carefully with kid3 and now i can have all the cover in B design.
But i still think that cover management is different between this two design ?
Thanks

**Comment by Oleksiy-Yakovenko** [comment]
Sorry, I didn't have time to investigate yet, so I don't have an answer

**Comment by Oleksiy-Yakovenko** [comment]
After having a 2nd look.. I think I see what the problem is.
The 1st screenshot displays album art which it loads based on the first track in the group / album.
The 2nd screenshot displays album art of the current selected track -- which probably doesn't have a cover art file.
That's where the difference comes from.
Now it no longer looks like a bug - works as designed.

**Comment by Npa972** [comment]
Ok i understand, thank you to take time.
