### ISSUE TITLE
cdda.so plugin fails to load due to old symbol name paranoia_cachemodel_size

### ISSUE THREAD

**Issue by nieder** [DeaDBeeF-Player/deadbeef#2930]
running deadbeef-1.9.5, startup has this non-fatal error:
```
loading plugin /sw/lib/deadbeef/cdda.so
dlopen error: dlopen(/sw/lib/deadbeef/cdda.so, 2): Symbol not found: _paranoia_cachemodel_size
  Referenced from: /sw/lib/deadbeef/cdda.so
  Expected in: flat namespace
 in /sw/lib/deadbeef/cdda.so
trying /sw/lib/deadbeef/cdda.fallback.so...
plugin cdda.so not found or failed to load
```
The problem is that the actual symbol name is `_cdio_paranoia_cachemodel_size`. 
This is on macOS with cdio-paranoia2 v10.2+2.0.1. The file `libcdio-paranoia2.symbols` from Ubuntu's libcdio-paranoia2 package also has the new prefixed symbol name:
```
$ cat libcdio-paranoia2.symbols 
libcdio_paranoia.so.2 libcdio-paranoia2 #MINVER#
 CDIO_PARANOIA_2@CDIO_PARANOIA_2 10.2+2.0.0
 cdio_paranoia_cachemodel_size@CDIO_PARANOIA_2 10.2+2.0.0
```

**Comment by Oleksiy-Yakovenko** [comment]
It seems like you need to install a different major version of libcdio-paranoia (version1)

**Comment by Oleksiy-Yakovenko** [comment]
Also, the official build of deadbeef for mac doesn't include audio cd support, so you should not be getting this error.
Seems like you got something from a 3rd party.
You should probably contact them instead of me.
