### ISSUE TITLE
when loading music files from a folder, deadbeef crashes when a broken music file is included

### ISSUE THREAD

**Issue by saufall** [DeaDBeeF-Player/deadbeef#2939]
### Steps to reproduce the problem
load music folder, choose a folder contatinng a broken .mp4 file or any other fire, run.
### What's going on? Describe the problem in as much detail as possible.
deadbeef crashes as it is unable to process the file and quits the loading process.
### Information about the software:
deabeef 1.95 fc37
Deadbeef version:
OS: nobara

is there any way to tell deadbeef to skip files that cannot be recognized? I can load files while carefully avoiding broken files but its too time consuming an i have 900gb+ music files in different folders all over the place in my external HD. its much easier if i can load the whole external HD, skip the broken files and load the rest.

**Comment by Oleksiy-Yakovenko** [comment]
Hi, unfortunately, when this happens - it indicates a bug, and there's no way to auto-skip it.
If you could send me an example of the file in question - I would be willing to figure out how it causes deadbeef to crash, and fix it.
If you are ok with doing it -- please use email or discord DM.

**Comment by saufall** [comment]
Its a broken mp4 video file. It breaks the loading every time.
________________________________

**Comment by Oleksiy-Yakovenko** [comment]
@saufall I think you replied to github notification -- which works to send a message to github, but what I meant it to use the email address from my profile

**Comment by Oleksiy-Yakovenko** [comment]
Clothing since I was not able to reproduce the problem with the provided file, and there was no followup.
