### ISSUE TITLE
A UPNP plugin for Deadbeef?

### ISSUE THREAD

**Issue by servimo** [DeaDBeeF-Player/deadbeef#2942]
It will be nice if we can have a UPNP plugin to send music to DDB2 in Android. Would this be possible?

**Comment by Oleksiy-Yakovenko** [comment]
DDB2 is abandonware, it's not going to be updated or supported. (I'm not planning to develop anything new for android in the future).

I'm not sure though whether your'e asking for a UPNP plugin in the desktop deadbeef.
(I don't know anything about UPNP / never used it).
However, I smh doubt that what you want is possible without making a new release of DDB2.

**Comment by servimo** [comment]
I asked for a upnp plugin for Deadbeef because, I see one in Foobar2000. What I didn't think is that maybe this is contributions of others developers to foobar2000. It's ok to close.
