### ISSUE TITLE
deadbeef --toggle-pause actually plays the selected track, even if it was stopped

### ISSUE THREAD

**Issue by w-jablonski** [DeaDBeeF-Player/deadbeef#2949]
### Steps to reproduce the problem

Start deadbeef afresh. Also press the `Stop` button if you want. Then from the command line, hit `deadbeef --toggle-pause`

### What's going on? Describe the problem in as much detail as possible.

The selected song plays, even thou it was stopped. This behaviour IMO belongs to the `--play-pause` switch, which does exactly that correctly.

### Information about the software:

Deadbeef version: 1.9.5
OS: Arch, swayWM

**Comment by Oleksiy-Yakovenko** [comment]
Hmm you are right that both commands currently do exactly the same thing. I'm not sure why -- probable result of evolution some long time ago.

What behavior do you expect instead?

**Comment by w-jablonski** [comment]
Expected behavior for `deadbeef --toggle-pause`: 
Pause the track if it is currently playing.
Unpause the track if it is currently paused.
Do nothing, if no track is either playing or paused.

**Comment by Oleksiy-Yakovenko** [comment]
Ok, it seems to make sense, I'll try to do it.
