### ISSUE TITLE
Changing Shuffle mode from Off to Albums plays first song of album next

### ISSUE THREAD

**Issue by Unmoon** [DeaDBeeF-Player/deadbeef#2950]
### Steps to reproduce the problem
1. Change shuffle mode to Off
2. Play song 2 (or later) from an album
3. Change shuffle mode to Albums
4. Skip to next track / let current song play to the end
5. First track of album is played

### What's going on? Describe the problem in as much detail as possible.
Instead of continuing to next track per album order, first track of the album is played.

### Information about the software:

Deadbeef version: 1.9.5
OS: Pop!_OS 22.04 LTS

**Comment by Unmoon** [comment]
This seems to also happen when shutting down, and starting the player again when using the "Albums" shuffle mode with 
"Settings -> Playback -> Resume previous session on startup" checked.

**Comment by Oleksiy-Yakovenko** [comment]
I'm not experiencing this problem. I follow the steps precisely like this:

* Shuffle off
* Play any song (e.g nr. 4 in an album)
* Shuffle Albums
* Play next
* Playback switches to the next song after the currently playing one (nr. 5 in the same album)
* When the whole album ends: another random album is chosen

Did I miss any steps?

**Comment by Unmoon** [comment]
No, that seems correct, and I can still reproduce this. Took a video (I changed song before turning off shuffle, but either way seems to "work").

https://github.com/DeaDBeeF-Player/deadbeef/assets/7273082/51fa9148-4bd4-41ec-b562-69be773ad3a4
