### ISSUE TITLE
Hide top menu?

### ISSUE THREAD

**Issue by NikolayKuraga** [DeaDBeeF-Player/deadbeef#2951]
How to hide the menu? That one, with "File", "Edit", "View" and other options.
There is a file manager Thunar in xfce 4.12, 4.14, 4.16, and I can hide Thunar's top menu using "Ctrl+m". And it looks really nice.
Can I do the same in DeaDBeeF?

Deadbeef version: 1.9.5
OS: Devuan GNU/Linux 4 (chimaera)

**Comment by Oleksiy-Yakovenko** [comment]
You can achieve this by adding `gtkui.show_menu 0` to the config file `~/.config/deadbeef/config`.
It's intentionally not in the menu itself, since it would not be possible to access it if the menu is hidden.

**Comment by ts1a** [comment]
> Ctrl+m
this works here, the same way it works in Thunar

**Comment by ts1a** [comment]
> Ctrl+m

this works here, the same way it works in Thunar

**Comment by NikolayKuraga** [comment]
> > Ctrl+m
> 
> this works here, the same way it works in Thunar
Doesn't work... @ts1a , what distro do you have? Desktop environment? Where and how did you get DeaDBeeF?

**Comment by kuba160** [comment]
Ctrl+m (at least on windows) has default binding to 'Playback/Toggle Stop After Current Track'. There is 'View/"Show/Hide menu"' action that you can use to change that behavior.

**Comment by NikolayKuraga** [comment]
Guys, this worked:
1) Edit > Preferences
2) Choose "Hotkeys" tab
3) Add new hotkey.
4) Set Action "Show/Hide menu"
5) Set key combination "Ctrl m". There will be conflict with "Playback/Toggle Stop After Current Track", so I just deleted that hotkey.
GREAT PLAYER, love it, thank you!
