### ISSUE TITLE
Sorry. I found a typo.

### ISSUE THREAD

**Issue by maxnort** [DeaDBeeF-Player/deadbeef#2953]
### Steps to reproduce the problem
from the main menu, click "edit" and select "Advanced Replay Gain Settings"

window pops up to adjust "Relay Gain Properties", not replay gain.

### What's going on? Describe the problem in as much detail as possible.
I think that's enough

### Information about the software:

Deadbeef version:1.9.5
OS: Debian Linux

I have no issue with typo's. I wish I could stop grepping.

**Comment by Oleksiy-Yakovenko** [comment]
I can't find such option in Deadbeef. You're probably using some plugin which has this bug.
