### ISSUE TITLE
Searching a large playlist makes audio stutter

### ISSUE THREAD

**Issue by Unmoon** [DeaDBeeF-Player/deadbeef#2955]
### Steps to reproduce the problem
1) Play a song
2) Open search window in a large playlist (~47000 tracks for me)
3) Start (relatively quickly) typing in the search window
4) Observe audio stuttering

### What's going on? Describe the problem in as much detail as possible.
Audio stutters while searching. Expectation is that audio playback continues without any noticeable difference while searching.

### Information about the software:

Deadbeef version: 1.9.5
OS: Pop!_OS 22.04 LTS

**Comment by kpcee** [comment]
I can confirm this with a playlist with over 26,000 tracks, for example, the addition of music tracks leads to the said audio stuttering / stopping. Also, the iteration of the playlist with plug-ins seems to work much, much slower than in the previous version.

Deadbeef version: 1.9.5
Arch Linux

**Comment by nsvg** [comment]
The same thing happens on my system with one playlist over 65000 tracks and another with 20000. Issue occurs while searching, skipping a song, going to a next/random song, changing playback shuffle mode.

When nothing is playing but another app which uses sound is open (for example VLC), the issue still occurs, if there is no other app which uses sound, the issue disappears.

Issue happens whether I am using laptop speakers or when I am using a DAC.

Happens in both the binary and the compiled app, DeadBeef version 1.9.5 on MacOS Monterey 12.6.6.

**Comment by Oleksiy-Yakovenko** [comment]
I pushed an experimental fix on master branch. It's highly untested (unknown whether if breaks something else), but it should help against stuttering both while searching, and in other situations.

Let's try it out for some time and see what happens :)
