### ISSUE TITLE
text appears as squares

### ISSUE THREAD

**Issue by badmanbro** [DeaDBeeF-Player/deadbeef#2958]
### Steps to reproduce the problem
upon opening
### What's going on? Describe the problem in as much detail as possible.
text appears as squares
### Information about the software:

Deadbeef version:1.8.7
OS: Linux Fedora 38 Workstation
![image](https://github.com/DeaDBeeF-Player/deadbeef/assets/136496926/b4bdb074-239b-4768-9847-cd8bf33f4aa9)

**Comment by kpcee** [comment]
This is certainly a problem of the used font, does it make a difference when switching between the GUI plugin GTK2 and GTK3 or updating to the current version 1.9.5?

**Comment by Oleksiy-Yakovenko** [comment]
Deadbeef is not adjusting UI font, and uses defaults. Seems like you're running GTK2 UI in deadbeef, but GTK2 is not configured properly.
Try running deadbeef with `--gui gtk3` argument from command line, perhaps it would help.

**Comment by Oleksiy-Yakovenko** [comment]
Closing since there's no response and not enough information to act upon
