### ISSUE TITLE
Track Properties Window is huge

### ISSUE THREAD

**Issue by Samueru-sama** [DeaDBeeF-Player/deadbeef#2960]
### Steps to reproduce the problem

Open DeaDBeef, select a track on the playlist , right click and select Track Properties.

### What's going on? Describe the problem in as much detail as possible.

The Track Properties windows is too big, its default size even makes wider than my 1440x900 monitor, if I resize the window and then close it, the size doesn't save either.

Screenshots: https://imgur.com/a/lfSLrlc

This only happens to the track properties, other windows like preferences, configure custom shell commands, convert, etc don't have this issue.

Example of the other windows not having this issue: https://imgur.com/a/QsFCwaM

### Information about the software:

Deadbeef version: deadbeef-git from the Aur.
OS: Arch Linux.

**Comment by Oleksiy-Yakovenko** [comment]
I'm not sure what I'm seeing on the screenshot. This window doesn't have titlebar?

There's nothing special about this window, its default size is 400x400 px, and the size/position is also persisted.

So there's definitely something odd happening on your machine, but it's not very obvious to me what exactly.

By chance, are you running some exotic desktop environment / window manager, which can affect the normal positioning of UI windows?

**Comment by Samueru-sama** [comment]
> I'm not sure what I'm seeing on the screenshot. This window doesn't have titlebar?
> 
> There's nothing special about this window, its default size is 400x400 px, and the size/position is also persisted.
> 
> So there's definitely something odd happening on your machine, but it's not very obvious to me what exactly.
> 
> By chance, are you running some exotic desktop environment / window manager, which can affect the normal positioning of UI windows?

I'm using i3wm, and yes titlebars are disabled.

It is only the window for the track properties that has the issue, every other window doesn't have it.

**Comment by Oleksiy-Yakovenko** [comment]
I'm fairly sure that it is i3wm that is causing the problem, since it doesn't appear under normal circumstances. Even on different operating systems. I'm not sure how to help with that. As I already stated, there's nothing special about this window.

**Comment by Samueru-sama** [comment]
> I'm fairly sure that it is i3wm that is causing the problem, since it doesn't appear under normal circumstances. Even on different operating systems. I'm not sure how to help with that. As I already stated, there's nothing special about this window.

Alright, thanks for clearing that up, will ask for help at i3.
