### ISSUE TITLE
Writing MP4/M4A tags corrupts file

### ISSUE THREAD

**Issue by ToadKing** [DeaDBeeF-Player/deadbeef#2961]
### Steps to reproduce the problem
* Make a dummy M4A file:
```ffmpeg -f lavfi -i "sine=frequency=1000:duration=5" test.m4a```
* Run `ffprobe` to see that it's not corrupted
* Open the file in Deadbeef and add ReplayGain tags to it.
* Run `ffprobe` on the file again.

### What's going on? Describe the problem in as much detail as possible.
After adding ReplayGain tags, FFmpeg/ffprobe thinks the file is corrupted and print an error: `[mov,mp4,m4a,3gp,3g2,mj2 @ 0x############] error reading header`. Deadbeef and some other audio players can still play the file but other ones (especially ones using FFmpeg as a backend) do not. Namely these files no longer play in my Sony Walkman A306.

### Information about the software:

Deadbeef version: c8e39422eaa72927dee6cb4bafa7208584142f2d
OS: Archlinux

**Comment by Oleksiy-Yakovenko** [comment]
I investigated a bit, but couldn't yet find anything obviously wrong with tag writer or the data itself.
Some data inside of `dref` atom that gets discarded, which doesn't *seem* to have any importance -- but other than that I didn't notice any major difference "before/after".

This part:
```
0000aba0  00 00 00 1c 64 72 65 66  00 00 00 00 00 00 00 01  |....dref........| 
0000abb0  00 00 00 0c 75 72 6c 20  00 00 00 01 00 00 04 70  |....url .......p| 
```

Turns into this:
```
0000aba0  00 00 00 10 64 72 65 66  00 00 00 00 00 00 00 00  |....dref........|
```

In other words, the empty `url ` atom is stripped, and then dref is written with 0 items.
Perhaps this is not valid? Not sure.

**Comment by Oleksiy-Yakovenko** [comment]
It turned out to be this, the `url ` atom was important to ffmpeg for some reason, and it was discarded because of a bug.
Seems to work fine now.
