### ISSUE TITLE
Album art with super-small filesize not displaying

### ISSUE THREAD

**Issue by ToadKing** [DeaDBeeF-Player/deadbeef#2964]
### Steps to reproduce the problem
Try to show the album art on a track with this PNG cover:

![front](https://github.com/DeaDBeeF-Player/deadbeef/assets/1023440/1a59f87f-3f9e-40a5-924e-a7582ee8de04)

(Filesize should be ~1.4KB)

### What's going on? Describe the problem in as much detail as possible.
No cover art is displayed.

### Information about the software:

Deadbeef version: devel (c8e3942)
OS: Archlinux

**Comment by Oleksiy-Yakovenko** [comment]
Good catch. It was confusing me for a while as to why it isn't working, but I was not the first who was hit with this problem, and the answer was found [here](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/110).
