### ISSUE TITLE
DeaDBeeF places socket file in ~/.config

### ISSUE THREAD

**Issue by ron-at-swgy** [DeaDBeeF-Player/deadbeef#2968]
### Steps to reproduce the problem

Using OpenBSD-current with DeaDBeeF installed from packages (`pkg_add deadbeef`), take a look in ~/.config/deadbeef:

```
[rdahlgren@builder :: ~/.config/deadbeef] $ ls -l
total 16
-rw-------  1 rdahlgren  rdahlgren  3925 Jul 21 11:06 config
-rw-r--r--  1 rdahlgren  rdahlgren     0 Jul 20 17:00 dspconfig
drwxr-xr-x  2 rdahlgren  rdahlgren   512 Jul 20 14:41 playlists
-rw-r--r--  1 rdahlgren  rdahlgren     0 Jul 21 10:49 running
srwxr-xr-x  1 rdahlgren  rdahlgren     0 Jul 21 10:49 socket
```

### What's going on? Describe the problem in as much detail as possible.

Putting this special file in `~/.config` causes my backup strategy to break, as bsd tar cannot 
 handle encountering a special file (like a socket). I like to backup the entire config directory.

Is there a means to configure the location of the socket perhaps? Thank you!

### Information about the software:

Deadbeef version: DeaDBeeF 1.9.3 Copyright © 2009-2021 Oleksiy Yakovenko
OS: OpenBSD builder.sw.gy 7.3 GENERIC.MP#1297 amd64

**Comment by Oleksiy-Yakovenko** [comment]
Hi,

you can use environment variable `DDB_SOCKET_DIR` to specify socket path. It's a folder path, and you will need to create it yourself. At least this is what I see in the code. Hope this helps.

**Comment by ron-at-swgy** [comment]
That's an excellent find, thank you! I'll give it a try

------- Original Message -------

**Comment by ron-at-swgy** [comment]
I just tested setting the DDB_SOCKET_DIR variable to point to a particular folder in my home directory. I deleted the existing ~/.config/deadbeef/socket file

On starting deadbeef, it recreated the socket file in ~/.config/deadbeef unfortunately

------- Original Message -------

**Comment by Oleksiy-Yakovenko** [comment]
Sorry for not following up sooner.
I checked the code, and tried setting this variable, and it works as described.
You should double check that the environment variable is set in the same process / shell where you start deadbeef.
I don't have a way to tell, but a common mistake is to set a variable in terminal, and then run a UI application using an icon or menu from a desktop environment. In this case the variable would only be visible from the shell where you set it, so it wouldn't work.

**Comment by ron-at-swgy** [comment]
I was setting the variable in my ~/.zshrc (for Z shell) rather than ~/.xsession and using my window manager to launch DeaDBeeF. Now that I have the environment variable set in ~/.xsession it works as expected.

User error! Thank you for the assistance

------- Original Message -------
