### ISSUE TITLE
Can't build 1.9.5 for Fedora 39

### ISSUE THREAD

**Issue by Vascom** [DeaDBeeF-Player/deadbeef#2976]
deadbeef 1.9.5
GCC 13.2.1
```
libbinio/binio.cpp:498:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  register long bits;
  ^~~~~~~~~
```
Full build log https://koji.rpmfusion.org/kojifiles/work/tasks/3886/603886/build.log
How to fix the problem?

**Comment by Oleksiy-Yakovenko** [comment]
You will need to apply this patch
https://github.com/DeaDBeeF-Player/deadbeef/commit/ec70bec029c379ea17442c95b2ad346a0a68d9d0

**Comment by Vascom** [comment]
Thanks.
