### ISSUE TITLE
Editing tags has no effect for FLAC

### ISSUE THREAD

**Issue by Gooberpatrol66** [DeaDBeeF-Player/deadbeef#2982]
### Steps to reproduce the problem
1.right click -> track properties
2.type anything in a field
3.click apply
4.close
5.right click -> track properties, the edit has not been saved

### What's going on? Describe the problem in as much detail as possible.
???

### Information about the software:

Deadbeef version: 1.9.5 (gentoo package version and nix package version)
OS: gentoo

**Comment by kpcee** [comment]
Works for me with version 1.9.5. Did you press the return key before clicked Apply? This is necessary so that the changes are saved.

**Comment by llakssz** [comment]
Could clicking `Apply` save the current changes in the active text field, without having to hit enter/return?
I was also confused about this behavior, and came across this issue :)

**Comment by Oleksiy-Yakovenko** [comment]
@llakssz There's a quirk in GTK which makes it tough to capture the value of such edit without pressing Return. It should be possible do fix, but until this is fixed -- you have to confirm the edit with Return and then press Apply or OK.

**Comment by llakssz** [comment]
Would you consider disabling the Apply button if there are no changes to be made? / Only enable when changes are detected?

**Comment by Oleksiy-Yakovenko** [comment]
I didn't know it's not disabled when there are no changes.
Sounds like a bug to me. (I typically use deadbeef on Mac, and there it works as intended)
Please report a bug and I'll fix it when I have time.
