### ISSUE TITLE
Add DeaDBeeF to apt catalogue

### ISSUE THREAD

**Issue by jesus2099** [DeaDBeeF-Player/deadbeef#2985]
### Steps to reproduce the problem

`apt list deadbeef`

### What's going on? Describe the problem in as much detail as possible.

DeaDBeeF is not available in Debian `apt` package catalogue.

I like installing my applications this way for easy tracking, updating and uninstalling.

This has preventing me, [several](https://community.metabrainz.org/t/looking-for-a-foobar2000-equivalent-on-linux/483198/3?u=jesus2099) [times](https://github.com/quodlibet/quodlibet/discussions/4221#discussioncomment-6794460), from testing this foobar2000 replacement candidate.

**Comment by Oleksiy-Yakovenko** [comment]
This has been tried before, it's not gonna work.
Apt catalogue, as you call it, is not an open platform -- not everything can be added there, and not by everyone.
In particular, it has been concluded that Deadbeef can't be added there.

**Comment by jesus2099** [comment]
> This has been tried before, it's not gonna work.

I searched past tickets before creating this and didn't find mentions of that.

> In particular, it has been concluded that Deadbeef can't be added there.

Why was it not possible for DeaDBeeF, while Audacious is in apt?
Because someone doesn't like the name, or something like that?

**Comment by Oleksiy-Yakovenko** [comment]
Haha, no I don't think they disliked the name (at least I don't think they said that).
The "official" reason for refusal is that Deadbeef is engineered in a way that doesn't comply with Debian's guidelines.

The guidelines in question are quite arbitrary, most audio/video applications (and most of large applications, such as web browsers) are not compliant, and can't be.

So I suppose they decide based on a ratio "nr of violations divided by company size".

Anyway, it didn't work out, and possibly never will. It doesn't bother me too much.

**Comment by Oleksiy-Yakovenko** [comment]
Fun story:

There's one linux audio player (which is in Debian and Fedora repos), that borrowed a codec implementation from Deadbeef, and prior to that the codec in question was stated as the reason for not accepting Deadbeef into at least one of the repos.

So, I don't know how it is decided, but there's simply not much that I can do.

**Comment by jesus2099** [comment]
I don't understand where it's said if these "bugs" are fixed or wontfixed:

Debian Bug report logs:

- [#576975](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=576975): RFP: deadbeef -- Ultimate Music Player
  - [#533555](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=533555): Clauses 4-6 can be ignored by a new clause 8; clarify copyright file

Apparently the problem was some content of the [licence used by library called DUMB](https://dumb.sourceforge.net/index.php?page=licences).

But would that still be a problem today?
New licence in newer versions?
Other approved packages using DUMB? Names?

**Comment by Oleksiy-Yakovenko** [comment]
I don't think DUMB is the real problem here.
There's an easy option to `--disable-dumb` at build time, or even strip it from the tarball.
There were more similar issues, and a few issues unrelated to the license.
Either way, I personally am not interested in spending time up on that.
From the previous experience, it's a lot of effort (and stress) and zero result.
It sounds like a hobby project for someone who wants to waste a lot of time.

**Comment by Oleksiy-Yakovenko** [comment]
And yes, libdumb itself is in the repo, as far as I can tell:
https://packages.debian.org/buster/libdumb1
So it should not be a problem in itself. I don't even know why this conversation about dumb took place :)
