### ISSUE TITLE
clang build failure - gettextP.h:120:1: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]

### ISSUE THREAD

**Issue by orbea** [DeaDBeeF-Player/deadbeef#2987]
Building deadbeef with stricter clang configurations results in build failures in files generated using `autopoint` and `AM_GNU_GETTEXT`.
```
clang -c -DLOCALEDIR=\"/usr/share/locale\" -DLOCALE_ALIAS_PATH=\"/usr/share/locale\" -DLIBDIR=\"/usr/lib\" -DBUILDING_LIBINTL -DBUILDING_DLL -DIN_LIBINTL -DENABLE_RELOCATABLE=1 -DIN_LIBRARY -DINSTALLDIR=\"/usr/lib\" -DNO_XMALLOC -Dset_relocation_prefix=libintl_set_relocation_prefix -Drelocate=libintl_relocate -DDEPENDS_ON_LIBICONV=1 -DHAVE_CONFIG_H -I. -I. -I..  -g -O2  -D_GNU_SOURCE -D__EXTENSIONS__  -DLIBDIR=\"/usr/lib\" -DPREFIX=\"/usr\" -DDOCDIR=\"/usr/share/doc/deadbeef-1.9.5-r2\" -DDDB_WARN_DEPRECATED=1 -fvisibility=hidden  bindtextdom.c
mv t-ref-del.sed ref-del.sed
clang -c -DLOCALEDIR=\"/usr/share/locale\" -DLOCALE_ALIAS_PATH=\"/usr/share/locale\" -DLIBDIR=\"/usr/lib\" -DBUILDING_LIBINTL -DBUILDING_DLL -DIN_LIBINTL -DENABLE_RELOCATABLE=1 -DIN_LIBRARY -DINSTALLDIR=\"/usr/lib\" -DNO_XMALLOC -Dset_relocation_prefix=libintl_set_relocation_prefix -Drelocate=libintl_relocate -DDEPENDS_ON_LIBICONV=1 -DHAVE_CONFIG_H -I. -I. -I..  -g -O2  -D_GNU_SOURCE -D__EXTENSIONS__  -DLIBDIR=\"/usr/lib\" -DPREFIX=\"/usr\" -DDOCDIR=\"/usr/share/doc/deadbeef-1.9.5-r2\" -DDDB_WARN_DEPRECATED=1 -fvisibility=hidden  dcgettext.c
mv t-charset.alias charset.alias
clang -c -DLOCALEDIR=\"/usr/share/locale\" -DLOCALE_ALIAS_PATH=\"/usr/share/locale\" -DLIBDIR=\"/usr/lib\" -DBUILDING_LIBINTL -DBUILDING_DLL -DIN_LIBINTL -DENABLE_RELOCATABLE=1 -DIN_LIBRARY -DINSTALLDIR=\"/usr/lib\" -DNO_XMALLOC -Dset_relocation_prefix=libintl_set_relocation_prefix -Drelocate=libintl_relocate -DDEPENDS_ON_LIBICONV=1 -DHAVE_CONFIG_H -I. -I. -I..  -g -O2  -D_GNU_SOURCE -D__EXTENSIONS__  -DLIBDIR=\"/usr/lib\" -DPREFIX=\"/usr\" -DDOCDIR=\"/usr/share/doc/deadbeef-1.9.5-r2\" -DDDB_WARN_DEPRECATED=1 -fvisibility=hidden  dgettext.c
In file included from dcgettext.c:23:
./gettextP.h:120:1: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
SWAP (i)
^
1 error generated.
make[2]: *** [Makefile:242: dcgettext.o] Error 1
```
Build log: [deadbeef-build.log](https://github.com/DeaDBeeF-Player/deadbeef/files/12456247/deadbeef-build.log)

This is fixed in `gettext-0.22`, but increasing the `AM_GNU_GETTEXT_VERSION` in `configure.ac` is not straight forward.

See these two Gentoo issues for more info:
https://bugs.gentoo.org/908414
https://bugs.gentoo.org/893728

### Information about the software:

Deadbeef version: 2f4c05cb7467315aea94cf8d70821478bcdb8e39
OS: `Gentoo`
Clang: `16.0.6`

**Comment by Oleksiy-Yakovenko** [comment]
So, if this is a problem in gettext source that is installed as part of gentoo package -- what action are you expecting from me on this report?

**Comment by orbea** [comment]
> So, if this is a problem in gettext source that is installed as part of gentoo package

Its a problem with the upstream gettext which ships `/usr/share/gettext/archive.dir.tar.xz` that currently contains a directory for every gettext version from `0.10.35` to `0.22.0`. Every single one of these has build issues with clang except for the most recent `0.22.0` version. However Deadbeef is currently using `0.18`.

https://github.com/DeaDBeeF-Player/deadbeef/blob/2f4c05cb7467315aea94cf8d70821478bcdb8e39/configure.ac#L21

> what action are you expecting from me on this report?

Updating the `AM_GNU_GETTEXT_VERSION` line in `configure.ac` from `0.18` to `0.22` would solve this issue for me and anyone else with a similar clang configuration. Assuming that is currently possible?

**Comment by Oleksiy-Yakovenko** [comment]
gettext 0.22 was released in 2023, so bumping this dependency would break compatibility with older systems.

**Comment by orbea** [comment]
That is an understandable concern, we can leave this open for now or you can close it if you prefer?

**Comment by Oleksiy-Yakovenko** [comment]
Will close, since I can't really action on this for now.
