### ISSUE TITLE
Feature request: Changes to the Playback Order plugin. 

### ISSUE THREAD

**Issue by Samueru-sama** [DeaDBeeF-Player/deadbeef#2992]
The plugin gives you the option to change between linear, shuffle tracks, shuffle albums or random, it would be great if the drop down menu also displayed the options to change the current repeat mode alongside all the other shuffle options. 

Also the ability to remove the text to the left that says 'Order:' so that it only shows the drop down menu instead.

**Comment by Oleksiy-Yakovenko** [comment]
I think you're posting to the wrong place -- you should visit this plugin's web page, and request changes there.

**Comment by Samueru-sama** [comment]
> I think you're posting to the wrong place -- you should visit this [plugin's web page](https://github.com/cboxdoerfer/ddb_playback_order), and request changes there.

Oh sorry, I just noticed that repo is abandoned, if anyone reading this is having the same issue as me, I was able to remove the "Order:" label by editing the main.c file and searching for the text  "Order:" and removing it, after compiling and replacing the existing plugin I no longer have the label.

**Comment by Oleksiy-Yakovenko** [comment]
I don't think it's fully abandoned, but I don't know whether developer is interested in adding features / changing how it works.
