### ISSUE TITLE
Question: Stream Radio URL Format?

### ISSUE THREAD

**Issue by 0pLuS0** [DeaDBeeF-Player/deadbeef#2995]
### Steps to reproduce the problem

Add radio station URL: File > Add location
Click play

### What's going on? Describe the problem in as much detail as possible.

When I try to add in this URL http://digitalaudiobroadcasting.net:8004/stream it fails, I get this popup message;

```Failed to play track: http://digitalaudiobroadcasting.net:8004/stream```

This online radio station shows their URL in the same format I see at many other sites; ```.com:port/stream```

Why doesn't this URL work?

 This is the website I was trying to play; https://newwave.radio/ all of their URL address for the various media players are the same; ```.net:8004/stream```.

### Information about the software:

Deadbeef version: 1.9.5
OS: Slackware 15.0

THANKS

**Comment by Oleksiy-Yakovenko** [comment]
I don't know why it fails for you, but it plays fine for me.
Unless you're already running the official deadbeef build, did you check that you have all necessary built-in components installed?

**Comment by 0pLuS0** [comment]
I've been listenting to Radio stations for several years with deadbeef.

So I don't get why this URL doesn't work, here's the plugins I have compiled in.

Plugin Summary:

    aac: no - AAC player (m4a, aac, mp4) based on FAAD2
    adplug: yes - adplug player (OPL2/OPL3 emulation)
    alac: yes - ALAC plugin
    alsa: yes - ALSA output
    artwork: yes - Cover art plugin
    cdda: yes - cd audio player
    converter: yes - plugin for converting files to any formats
    coreaudio: no - CoreAudio output plugin
    dca: yes - libdca (DTS Audio) player plugin
    dsp_src: yes - High quality samplerate conversion using libsamplerate
    dumb: yes - DUMB module plugin, for MOD, S3M, etc
    ffap: yes - Monkey's audio (APE) decoder
    ffmpeg: yes - ffmpeg codecs
    flac: yes - flac player
    gme: yes - chiptune music player based on GME
    gtkui3: yes - GTK3 user interface
    gtkui: no - GTK2 user interface
    hotkeys: yes - Local and global hotkeys support
    lastfm: yes - last.fm scrobbler
    libretro: yes - Libretro resampler plugin
    m3u: yes - M3U and PLS playlist support
    mms: yes - mms streaming support
    mono2stereo: yes - mono2stereo DSP plugin
    mp3: yes - mp3 plugin
    libmad: yes - libmad backend for mp3 plugin
    libmpg123: yes - libmpg123 backend for mp3 plugin
    musepack: yes - musepack player plugin
    notify: yes - notification-daemon support plugin
    nullout: yes - NULL output
    opus: yes - ogg opus player
    oss: yes - oss output plugin
    pltbrowser: yes - playlist browser gui plugin
    psf: yes - PSF player, using Audio Overload SDK
    pipewire: yes - Pipewire output plugin
    pulse: yes - PulseAudio output plugin
    rgscanner: yes - plugin for ReplayGain scanner support
    sc68: yes - sc68 Atari ST And Amiga player
    shellexec: yes - shell commands plugin
    shellexecui: yes - GTK user interface for setting up shellexec plugin
    shn: yes - SHN plugin based on xmms-shn
    sid: yes - SID player based on libsidplay2
    sndfile: yes - PCM (wav,aiff,etc) player based on libsndfile
    soundtouch: yes - SoundTouch plugin used for time stretching and pitch shifting
    stdio: yes - Standard IO plugin
    supereq: yes - Equalizer based on Super EQ library by Naoki Shibata
    tta: yes - TTA player plugin
    vfs_curl: yes - http/ftp streaming support
    vfs_zip: yes - zip archive support
    vorbis: yes - ogg vorbis player
    vtx: yes - vtx file player (ay8910/12 emulation)
    wavpack: yes - wavpack player
    wildmidi: yes - WildMidi player plugin
    wma: yes - WMA plugin

**Comment by 0pLuS0** [comment]
After posting this, I went back and compiled in faad2 support and now the stream works.

I didn't realize faad2 is needed for some radio streams.

THANKS
