### ISSUE TITLE
Compilation on Rasberry Pi OS

### ISSUE THREAD

**Issue by olevenets2** [DeaDBeeF-Player/deadbeef#3003]
### Steps to reproduce the problem

Error compiling from source code.

### What's going on? Describe the problem in as much detail as possible.
I'm trying to compile a program on my raspberry pi 4 and I'm getting an error about missing unmet dependency: lastfm.c:26:10: fatal error: 'dispatch/dispatch.h' file not found

The libdispatch package is currently missing from the repository, as is the second libblockruntime package. Is there any workaround to build the program?

### Information about the software:

Deadbeef version: git
OS: Debian GNU/Linux 11 (bullseye) aarch64

**Comment by Oleksiy-Yakovenko** [comment]
Before compiling, you need to [read this file](https://github.com/DeaDBeeF-Player/deadbeef/blob/master/README)
It answers your questions.
