### ISSUE TITLE
Editing FLAC tracks properties not persistent. 

### ISSUE THREAD

**Issue by sushi2503** [DeaDBeeF-Player/deadbeef#3006]
Hello,

Changing FLAC tracks properties then Enter and Apply is not persistent. If I delete the tracks and reload them again the values are not changed. I'm trying to change the number of album tracks from 7 to 07 without success. But if I right click on the album tracks and reload metadata it changes to the right value.

### What's going on? Describe the problem in as much detail as possible.
It's the same case as in (closed) issue #2982 

### Information about the software:

Deadbeef version: 1.9.5-3
OS: Archlinux

Thanks for any help.

**Comment by Oleksiy-Yakovenko** [comment]
When you change the value, try pressing "Enter" after, or click outside of the text field. Otherwise it would not get applied when you click OK or Apply.

**Comment by kpcee** [comment]
Works for me, tested with ffmpeg what is saved. But you have to use the return key and not enter. If you use enter, a new paragraph is inserted and the changes are not applied. This is indeed confusing and could be changed.

**Comment by Oleksiy-Yakovenko** [comment]
> return key and not enter

Not sure what's the difference, but I meant the key highlighted in white:
<img width="162" alt="image" src="https://github.com/DeaDBeeF-Player/deadbeef/assets/1895698/5ce04c40-56ec-47ae-a769-9c7420bcc204">

**Comment by Oleksiy-Yakovenko** [comment]
> I'm asking myself if this package is needed on Archlinux ?
> extra/id3lib 3.8.3-18
> Library for reading, writing, and manipulating ID3v1 and ID3v2 tags

deadbeef doesn't use this library, and flac doesn't use id3.

you should check which plugin in deadbeef is used for FLAC files.
You can see this in the 2nd tab of track properties.

**Comment by kpcee** [comment]
> > return key and not enter
> 
> Not sure what's the difference, but I meant the key highlighted in white: 

Yes, this is exactly the key I meant, in German it is usually called Return key, because it has no name on it. However, there is another key on the numeric keypad called Enter and can also used as return but in Deadbeef it inserts a paragraph.
![Tastatur](https://github.com/DeaDBeeF-Player/deadbeef/assets/39984895/e7638f2e-1840-49ce-ac3d-7ad8964df58c)

**Comment by Oleksiy-Yakovenko** [comment]
Ah this explains it..
This file is loading metadata from cuesheet.
So even if you change the tag -- it would not really change what you see, since cuesheet takes precedence.
You need to edit the cue file instead.

**Comment by Oleksiy-Yakovenko** [comment]
Yes, you can delete them.

**Comment by Oleksiy-Yakovenko** [comment]
yes.

And I'm not sure why it's 07.. seems like cuesheet loader adds a leading 0 for whatever reason..
If this needs to be fixed -- I will need to dig a little bit.
