### ISSUE TITLE
deadbeef is not playing current playlist after filebrowser replace current playlist

### ISSUE THREAD

**Issue by sp31415t1** [DeaDBeeF-Player/deadbeef#3008]
### Steps to reproduce the problem

Open deadbeef (to read local files)
I'm browsing files with filebrowser
If I double click an album, then album is loaded in playlist, song change instantly.
If I click the green tick ('replace current playlist'), then playlist is changed correctly, but at the end of current file, deadbeef is looping on current file instead of playing the current playlist

### What's going on? Describe the problem in as much detail as possible.

deadbeef is not playing the current playlist, but the old one (which has been replaced)

### Information about the software:

Deadbeef version: 1.9.5
OS: Linux debian stable uptodate
2 plugins : filebrowser waveform_seekbar

**Comment by Oleksiy-Yakovenko** [comment]
I would have suggested to contact the plugin's dev, but he abandoned the plugin some years ago.
So your only feasible option is to fix it yourself, if you know some basic programming.

**Comment by sp31415t1** [comment]
I would like to reopen the bug.
I have read the code in filebrowser, but nothing particular.

I tried to reproduce it without filebrowser and using only regular feature.

Steps:
remove all entries in playlist (press ctrl+A, del key)
drag n drop a directory (containg file)
playlist is updated
at the end of the file, deadbeef is not reading the first item in playlist

It can be reproduced at 50% (it is strange).
I think it was not present in 1.9.4 .

**Comment by Oleksiy-Yakovenko** [comment]
Thanks, reopened, I'll check it out

**Comment by Oleksiy-Yakovenko** [comment]
Can you please clarify what this sentence means?
> at the end of the file, deadbeef is not reading the first item in playlist

**Comment by sp31415t1** [comment]
response made by memory. not tested today.
current playlist has 5 files. Currently playing the 3rd file.
remove all files from playlist (ctrl+a , del key), no file displayed in current playlist
drag and drop a repository containing 7 files, the 7 files are correctly displayed in the playlist.
I was fast enough to not reach the end of the 3rd file, so I'm still listening it.
After playing the 3rd file, it should play the 1st file of current playlist (with 7 files)
But it played the 4th file from old playlist.
And after it loops on the 4th file.
I never listened the new playlist.

Is it more clear ?

**Comment by Oleksiy-Yakovenko** [comment]
ah ok, I think I understand.

So you're replacing playlist with new files, while some track is playing, but instead of switching to track1 it continuing playing currentIndex+1 ?

**Comment by sp31415t1** [comment]
yes, and then looping (maybe index has been lost)

**Comment by Oleksiy-Yakovenko** [comment]
Confirmed, definitely a bug... will fix

**Comment by Oleksiy-Yakovenko** [comment]
It behaves slightly differently for me, but I'm testing on mac:

it plays the last track of the previous playlist content, before I cleared it.

**Comment by sp31415t1** [comment]
Hi,
I'm sorry to bother you again...
I tried version 1.9.6, bug is present.
Did you find a fix ?
Regards

**Comment by sp31415t1** [comment]
Thank you.
