### ISSUE TITLE
Latest build doesn't compile under C++17

### ISSUE THREAD

**Issue by zetef** [DeaDBeeF-Player/deadbeef#3012]
### Steps to reproduce the problem
Try to compile the latest deadbeef version under Paman 11.6.0-1.

### What's going on? Describe the problem in as much detail as possible.
I am trying to compile the latest build but the compilation stops for the libbinio plug.
The following error comes up:
```
libbinio/binio.cpp:498:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  register long bits;
  ^~~~~~~~~
```

### Information about the software:
Building w/ Paman 11.6.0-1/pacman v6.0.2
Deadbeef version: 1.9.5-3 from the AUR
OS: Manjaro Linux 23.0.4/GNOME 44.5

**Comment by Oleksiy-Yakovenko** [comment]
I believe this is already fixed in the next upcoming release, but you can apply it as a patch from here: ec70bec029c379ea17442c95b2ad346a0a68d9d0
