### ISSUE TITLE
supereq: RAND_MAX implicit conversion changes value

### ISSUE THREAD

**Issue by isf63** [DeaDBeeF-Player/deadbeef#3014]
Deadbeef version: 1.9.6
OS: Arch Linux
Kernel: linux-6.6.1.arch1-1
Compiler: clang-16.0.6-1

This tiny bug changes the expected value of RAND_MAX to another due to int->float conversion. I don't know if it has any unintentional side effects.

```
Equ.cpp:146:39: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-const-int-float-conversion]
        state->ditherbuf[i] = (float(rand())/RAND_MAX-0.5);
                                            ~^~~~~~~~
/usr/include/stdlib.h:87:18: note: expanded from macro 'RAND_MAX'                                                                             
#define RAND_MAX        2147483647
                        ^~~~~~~~~~
```

**Comment by Oleksiy-Yakovenko** [comment]
This is not a bug, just a compiler warning, and also it's in 3rd party code which I'm hesitant to change.
I recommend to lower your warning level if you don't want to see it.
