### ISSUE TITLE
FLAC files playback is faster than it sould be (on MacOS)

### ISSUE THREAD

**Issue by kles4enko** [DeaDBeeF-Player/deadbeef#3031]
### Steps to reproduce the problem
1. Open any flac file and play it using Deadbeef. (test file attached)
2. Open and play same file in any other player, i.e. VLC.
3. Feel the difference in speed?

### What's going on? Describe the problem in as much detail as possible.
Did not see that issue before, in previous versions.

### Information about the software:
Deadbeef version: devel (e972757) - latest nightly for macos from the site.
OS: Sonoma 14.2 (23C64)

[Creaton001A.flac.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/13696144/Creaton001A.flac.zip)

**Comment by kles4enko** [comment]
Installed the app via homebrew `brew install deadbeef-nightly` today. Now I can't reproduce this bug. Now flac's playback has expected speed. But as I see there was a bugfix for Sonoma too. I don't beileve it is relates somehow.

Deadbeef version: devel (a49b03f)
OS: Sonoma 14.2.1 (23C71)

**Comment by Oleksiy-Yakovenko** [comment]
Thanks for the update. I didn't have a chance to try this out on Sonoma yet, but I'll do as soon as I can.

**Comment by Oleksiy-Yakovenko** [comment]
Verified on sonoma, no problems observed.
