### ISSUE TITLE
[GME plugin] Tracks play exactly 10 seconds shorter than track length

### ISSUE THREAD

**Issue by spamegg1** [DeaDBeeF-Player/deadbeef#3032]
### Steps to reproduce the problem
1. Open an NSFE file (Nintendo Sound Format Extended)
2. Play a track
3. Track ends playback _**exactly 10 seconds**_ earlier than the track length, moves on to the next track.

### What's going on? Describe the problem in as much detail as possible.
I tried tens of different NSFE files and hundreds of different tracks, the issue is consistent.

(Note that the fadeout length is not relevant, the issue happens with any fadeout length, even 0.)

The issue is not present in Deadbeef 1.9.5 (using [deadbeef-static_1.9.5-1_amd64.deb](https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9.5/deadbeef-static_1.9.5-1_amd64.deb/download))

Could it be caused by [this commit?](https://github.com/DeaDBeeF-Player/deadbeef/commit/a839dd6505277dd3f694a6282b282375c2e8bfa1) I believe this was between 1.9.5 and 1.9.6.

### Information about the software:

Deadbeef version: 1.9.6 (using [deadbeef-static_1.9.6-1_amd64.deb](https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9.6/deadbeef-static_1.9.6-1_amd64.deb/download))
OS: Linux

**Comment by Oleksiy-Yakovenko** [comment]
I'm not observing the problem.

Yes, fadeout is applied, which doesn't make sense with known length -- I'll need to come up with some solution to that.
But when I change fadeout to 0 -- songs play in full length, according to what I see in playlist and track properties.

**Comment by Oleksiy-Yakovenko** [comment]
<img width="559" alt="image" src="https://github.com/DeaDBeeF-Player/deadbeef/assets/1895698/8092d2b8-9e2d-4b59-9d19-7d694642774b">

**Comment by Oleksiy-Yakovenko** [comment]
I have tried the same thing on Linux, same results.

**Comment by spamegg1** [comment]
Thanks, I'll investigate more and try to replicate some other way. I'll reopen if I find something.
