### ISSUE TITLE
AIFF files show as "wav" in Codec column

### ISSUE THREAD

**Issue by garuffalo** [DeaDBeeF-Player/deadbeef#3033]
### Steps to reproduce the problem

Show "Codec" column. Open AIFF files. They all show as "wav" (lower case).

### What's going on? Describe the problem in as much detail as possible.

Other files' codecs are shown properly, e.g., FLAC, ALAC, APE, MP4 AAC, RAW AAC, MP3 (all upper case). I understand that WAV and AIFF are virtually the same type of file, but other music players I've used had no problem discerning the info. I sometimes use the Codec info to sort files, since I have all of the above file types on my computer, including actual WAV and AIFF files.

### Information about the software:

Deadbeef version: 1.9.6
OS: Linux Mint 21.2 Cinnamon

**Comment by Oleksiy-Yakovenko** [comment]
I have added the code to set filetype correctly, but you'll need to re-add the files to playlists for this to take effect.
