### ISSUE TITLE
Translations errors in DeaDBeeF devel

### ISSUE THREAD

**Issue by Npa972** [DeaDBeeF-Player/deadbeef#3034]
### Steps to reproduce the problem
Open contextual menu
1.9.6 : "Actualiser la pochette"
Devel : "Refresh covert art"

### What's going on? Describe the problem in as much detail as possible.
Translation is not good as before. I did not check everything but for example text is missing in pipewire plugin window.
### Information about the software:

Deadbeef version: stable and devel
OS: Archlinux

1.9.6
![Capture d’écran_2023-12-26_15-36-15](https://github.com/DeaDBeeF-Player/deadbeef/assets/49346431/76811030-6ab1-4b9b-8843-732170062445)

Devel
![Capture d’écran_2023-12-26_15-38-14](https://github.com/DeaDBeeF-Player/deadbeef/assets/49346431/8203abb3-b543-4e54-852a-8bdfa437d1d4)

Devel
![Capture d’écran_2023-12-26_15-45-05](https://github.com/DeaDBeeF-Player/deadbeef/assets/49346431/7080e71e-8c73-4f2c-9a93-fafa80ece090)

1.9.6
![Capture d’écran_2023-12-26_15-45-35](https://github.com/DeaDBeeF-Player/deadbeef/assets/49346431/4618dbac-83f1-4f37-a04f-514bc8657f00)

**Comment by Oleksiy-Yakovenko** [comment]
This specific error has been fixed already a few days ago.
There were other errors, but they should not be affecting 1.9.6 - and they're fixed on master as well.
