### ISSUE TITLE
Player fails to launch from a $PATH directory unless the full path is indicated in the .desktop launcher file on Linux

### ISSUE THREAD

**Issue by simurq** [DeaDBeeF-Player/deadbeef#3036]
### Steps to reproduce the problem
1. Extracted the [portable Linux version](https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9.6/deadbeef-static_1.9.6-1_x86_64.tar.bz2/download) to custom directory `~/Portables/deadbeef`, which contains the executable.
2. Added the launcher file `deadbeef.desktop` to `~/.local/share/applications` with the [following](https://pastebin.com/NCDX8B7J) content.
3. Exported directory `~/Portables/deadbeef` to the $PATH via `~/.profile`: `export PATH=$PATH:$HOME/Portables/deadbeef`
4. Sourced `~/.profile` and even restarted the computer.
5. Applied `chmod +x` to the launcher file to make it executable.
6. Clicked on the program icon under Applications and Favorites but failed to launch the program.

### What's going on? Describe the problem in as much detail as possible.
The program fails to launch from a legit $PATH directory when clicked on its icons under Applications and Favorites. It also fails to run when launched from the terminal with the following error:
```
starting deadbeef 1.9.6 [static]
server_start
searching for GUI plugins in /home/<my-username>/.local/lib64/deadbeef
searching for GUI plugins in /home/<my-username>/.local/lib/deadbeef
searching for GUI plugins in /opt/deadbeef/lib/deadbeef
load gui plugin
selected GUI plugin not found or failed to load, trying to find another GUI plugin
loading plugins from /home/<my-username>/.local/lib64/deadbeef
loading plugins from /home/<my-username>/.local/lib/deadbeef
loading plugins from /opt/deadbeef/lib/deadbeef
starting plugin stdio vfs
failed to find output plugin!
```
However, when I move the whole deadbeef directory to `/opt` (because of the above error message), clicking on deadbeef icons under Applications and Favorites _successfully launches_ the player.

Also, it launches well when the _full path_ to the custom directory `~/Portables/deadbeef` is specified in the .desktop launcher file: `Exec=/home/<my-username>/Portables/deadbeef` (without "<" and ">" and with my real username).

Interestingly, I use the same technique (exporting the location of portable programs to $PATH) and specify only the program's name under `Exec=application %F` in the .desktop launcher file, and it works okay, deadbeef being the only exception so far though, alas.

### Information about the software:
**Kernel:** 6.6.6
**OS:** Pop!_OS 22.04 (Debian/Ubuntu)
**Deadbeef:** 1.9.6

**Comment by Samueru-sama** [comment]
I also have this issue, didn't think it was a bug since deadbeef is the only portable app, the rest are appimages. 

I keep my portable apps in `~/.local/share/bin/apps` while `~/.local/share/bin` is in PATH and contains either symlinks or scripts that point to each individual application. 

Then the desktop entries in` ~/.local/share/applications` have the name of the exec instead of the full path. 

Deadbeef didn't work this way, in fact even if I make a symlink to the deadbeef exec from `~/.local/share/bin` to its location it doesn't work, it gives the same error you had, I had to add the following script in the PATH and that works: 

```
#!/bin/sh
$HOME/.local/bin/apps/deadbeef-1.9.6/deadbeef
```
