### ISSUE TITLE
permission denied to add network folder

### ISSUE THREAD

**Issue by mister-bum** [DeaDBeeF-Player/deadbeef#3039]
### Steps to reproduce the problem
- Install DeaDBeeF vanilla from Ubuntu Discover.
- Mount a folder that is located on a NAS via the `/etc/fstab` to the mount point `~/Music/_NAS`. 
- Try to add `~/Music/_NAS` in DeaDBeeF

### What's going on? Describe the problem in as much detail as possible.
While trying to add the folder DeaDBeeF reports: Error opening directory '/home/username/Music/_NAS': permission denied

### Information about the software:
Deadbeef version: 1.8.7-snap1
OS: Kubuntu 22.04

The NAS folder is mounted as read-only, as I do not want every application to mess up my music collection.  Also, the mount point ~/Music/_NAS is owned by root, which could be related to the problem. However, this setup works flawlessly with Amarok for the last years.

Please note that Discover provides the snap version - maybe that is related to the problem?

**Comment by Oleksiy-Yakovenko** [comment]
deadbeef 1.8.7 is 3 years old, you should consider updating

You didn't provide any logs or relevant information to investigate why this problem may be occurring on your computer, and I don't know what is Ubuntu Discover, but this Discover thingie may be the reason for the problem.

You should try installing deadbeef from another source, such as the deb package or prebuilt binary from the deadbeef website.

**Comment by mister-bum** [comment]
Many thanks for your swift reply. To answer your points:

**Comment by Oleksiy-Yakovenko** [comment]
> or as flatpack or as snap.

Flatpack and snap are specifically known as sandbox environments, which can restrict applications from accessing your files.

**Comment by Oleksiy-Yakovenko** [comment]
> However I would have expected that a quite basic feature (such as network access) had been successfully implemented much earlier. No offense meant, I just explain my decision.

Deadbeef doesn't support network shared by itself. It relies on your operating system to handle this. 
And loading files from a mounted smb share should work just fine.
I'm fairly sure that snap or flatpack or whatever else is preventing this. It's a fairly common problem.
You can either configure your system to allow deadbeef accessing your files, or stop using sandboxed packages.

**Comment by Oleksiy-Yakovenko** [comment]
> Regarding "any logs or relevant information" - what exactly do you need to know?

Usually it should be enough to post console log when running deadbeef in console (such as gnome-terminal),
which will probably show that you are running deadbeef from a snap sandbox, and that's your problem.

**Comment by mister-bum** [comment]
> I'm fairly sure that snap or flatpack or whatever else is preventing this. It's a fairly common problem.

Absolutely! I am not a big fan of these either. I just uninstalled the snap version and installed the latest version from sourceforge.io and this version can access the network :-)

Many thanks again for your support.

**Comment by Oleksiy-Yakovenko** [comment]
Was happy to help!
