### ISSUE TITLE
Manually set global hotkeys do not work (Ubuntu 22.04)

### ISSUE THREAD

**Issue by samael-1982** [DeaDBeeF-Player/deadbeef#3040]
### Steps to reproduce the problem
Deadbeef 1.9.6 pre-built version x64_amd linux
OS Ubuntu 22.04

### What's going on? Describe the problem in as much detail as possible.
Trying to add some global hotkeys for play/pouse/volume. They being set, but then they worked only in active deadbeef window. If another window is active - they do not work
### Information about the software:

Deadbeef version: 1.9.6
OS: Ubuntu 22.04 LTS
![image](https://github.com/DeaDBeeF-Player/deadbeef/assets/88877761/af9cf014-50f1-4687-8471-8f56b87bad80)

**Comment by Oleksiy-Yakovenko** [comment]
There's a high chance that this is not gonna work, because GNOME may block global hotkeys functionality.

The preferred way in GNOME/Ubuntu (and most other linux DEs) is to install MPRIS plugin [from here](https://deadbeef.sourceforge.io/plugins.html), and then use system hotkeys for play/pause etc.

**Comment by samael-1982** [comment]
@Oleksiy-Yakovenko but how to use it? I've installed it, global hotkey still not working.  What to do to make global hotkey work so?
Setiings are minimal just logging and repeat shuffle.

**Comment by Oleksiy-Yakovenko** [comment]
> but how to use it? I've installed it, global hotkey still not working.

Typically you don't need to do anything else, just press the standard keys which GNOME recognizes as playback control keys.

Perhaps this page would be of help?
https://help.gnome.org/users/rhythmbox/stable/shortcuts.html.en

> What to do to make global hotkey work so?

You would need to stop using GNOME and run a lightweight WM which allows the use of global hotkeys.

**Comment by Oleksiy-Yakovenko** [comment]
There's also this reddit post which may be helpful:
https://www.reddit.com/r/gnome/comments/ghg7y0/media_controls_on_gnome_like_play_pause_next/
