### ISSUE TITLE
Stuttering since some last (kernel?) update

### ISSUE THREAD

**Issue by sushi2503** [DeaDBeeF-Player/deadbeef#3053]
### Steps to reproduce the problem

Launch a music file or a radio.

### What's going on? Describe the problem in as much detail as possible.

Files or radios are unstable, stuttering, accelerating like a buffer/timing problem. The same files or radios are playing without problems through mpv. I have tried to change the buffer size without success. Somethings strange, if I play the same radio it shows ~ 60 kbps in Deadbeef and 150 kbps in mpv (aac).

https://fr1.streamhosting.ch/lounge64.aac

No error in journalctl nor xsenssion-erros and Deadbeef journal.

### Information about the software:

Deadbeef version:
1.9.6-1

Sound card:
RME HDSP 9632

OS:
Archlinux up to date

Let me know if you need more information.

Thank you.

Edit : I have tried to revert the kernel from 6.7.9 to 6.7.7 but the problem still occur. Sounds like something else is causing it.

**Comment by Oleksiy-Yakovenko** [comment]
Did you try restoring it back to defaults and see if it helps?

**Comment by Oleksiy-Yakovenko** [comment]
> Somethings strange, if I play the same radio it shows ~ 60 kbps in Deadbeef and 150 kbps in mpv (aac).
> https://fr1.streamhosting.ch/lounge64.aac

I checked this stream, 60 is correct.

**Comment by Oleksiy-Yakovenko** [comment]
This specific one is a setting, which tells ALSA which buffer/period size it should be using while interacting with the application. It's possible that under some circumstances ALSA will use the same buffer size for soundcard data, but this is not guaranteed.

**Comment by Oleksiy-Yakovenko** [comment]
Small buffer size reduces latency, but increases the likelihood of stuttering when the application can't process data with high enough frequency. In music playback, latency is only important as long as it doesn't affect visualizations and pausing/unpausing in a significant way. So you should always prefer the buffer which is as large as possible, but not large enough to introduce issues in visualizations. So if you aim for 60fps -- you need the buffer at most 1/60th of a second.

**Comment by Oleksiy-Yakovenko** [comment]
> Just a question, is there any way to play (repeat mode) just a sequence from a file ?

what do you mean by a sequence? a playlist?

**Comment by Oleksiy-Yakovenko** [comment]
Sorry, but no -- I don't believe there's such feature in deadbeef UI. You would need to create a CUE file for that.
