### ISSUE TITLE
[Q/FR] Adding podcast streams

### ISSUE THREAD

**Issue by DJManas** [DeaDBeeF-Player/deadbeef#3054]
Hi,

this is not bug, but rather feature request or question. I can see, that DeaDBeeF is able to stream data from web, e.g. podcast, but am I able to load RSS url for podcast to playlist, with ability of update when new episodes come out and wit deletion of listened episodes? If yes, how is it possible?

Deadbeef version: 1.9.6
OS: Gentoo Linux RinceWind 6.7.9-Air SMP PREEMPT_DYNAMIC Fri Mar  8 03:31:34 CET 2024 x86_64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz GenuineIntel GNU/Linux

Thanks,
Regards,
Petr Sourek

**Comment by Oleksiy-Yakovenko** [comment]
To answer your question: no, deadbeef doesn't load podcast url. It doesn't have any special features for supporting podcasts.

**Comment by DJManas** [comment]
Ok, thanks.
