### ISSUE TITLE
BadAccess

### ISSUE THREAD

**Issue by AdamCalculator** [DeaDBeeF-Player/deadbeef#3061]
The player starts, but after closing, when trying to open it, nothing happens; when called from the terminal, this error occurs

```
convgui: gtkui plugin not found
shellexecui: can't find gtkui plugin
resume: track 98 pos 2.933289 playlist 0
gtkui plugin compiled for gtk version: 2.24.33
The program 'deadbeef' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 8 error_code 10 request_code 33 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

## OS - linux

**Comment by Oleksiy-Yakovenko** [comment]
This looks like something you should figure out on your own.
You decided to not share any information about your system or deadbeef build, so there's no way for me to know what's going on.

**Comment by AdamCalculator** [comment]
![image](https://github.com/DeaDBeeF-Player/deadbeef/assets/156993728/6a79c04a-d601-4ffd-aa1f-341f172082d3)

![image](https://github.com/DeaDBeeF-Player/deadbeef/assets/156993728/1cadb30b-3449-47f7-b843-e772651fb9ce)

**Comment by Oleksiy-Yakovenko** [comment]
Perhaps the first thing to try would be to run a newer version of deadbeef than the one from 2 years ago.
Chances are, if the issue is caused by deadbeef -- it was fixed in those 2 years that passed.

**Comment by AdamCalculator** [comment]
Okay, Thanks, I wonder where I was able to download such an outdated version, I recently reinstalled the system....
