### ISSUE TITLE
Raspberry Pi: cue files are not shown after commit 8fa263e32d7aee22c3ea1bcea7e93ca285f00930

### ISSUE THREAD

**Issue by eshchenko** [DeaDBeeF-Player/deadbeef#3070]
### Steps to reproduce the problem
Compile deadbeef from fresh git on **raspberry pi**. 
Drop a directory with flac and cue files.

### What's going on? Describe the problem in as much detail as possible.
Cue file is not shown:
![wrong_cue](https://github.com/DeaDBeeF-Player/deadbeef/assets/36866934/fb34171e-31ad-4c8d-9209-ac85e928a19d)

The cue were shown correctly before
commit 8fa263e32d7aee22c3ea1bcea7e93ca285f00930
8fa263e32 configure: Use AC_SYS_LARGEFILE 2023-06-12

If in the configure.ac I comment the line containing
AC_SYS_LARGEFILE 
the cue is shown correctly:
![correct_cue_AC_SYS_LARGEFILE_commented](https://github.com/DeaDBeeF-Player/deadbeef/assets/36866934/a5e572b4-84de-43c9-b171-4ecaf74b84e0)

To conclude - this roll back and the roll back described in the issue #3052 
make the fresh deadbeef on raspberry pi usable: 
both jpeg art is scaled up correctly and cue is shown as expected: 
![correct_cue_currect_picture](https://github.com/DeaDBeeF-Player/deadbeef/assets/36866934/d52abf18-1ecb-4e08-a249-d53dcf0bffad)

The cue file is attached:
[cue.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/14843968/cue.zip)

### Information about the software:

Deadbeef version: starting from commit 8fa263e32d7aee22c3ea1bcea7e93ca285f00930
OS: Two 32 bit Raspbian OS were tested:
Compilation on Buster:
uname -a
Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 126.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

cat /proc/version
Linux version 5.10.103-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1529 SMP Tue Mar 8 12:24:00 GMT 2022
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Compilation on Bookworm
uname -a
Linux raspberrypi 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux

cat /proc/cpuinfo 
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

cat /proc/version 
Linux version 6.6.20+rpt-rpi-v8 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07)
 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
**It is interesting to note that on the "old" Intel the cue problem is not reproducible.**
uname -a
Linux HP-EliteBook-8530p 4.2.8-040208ckt13-generic #201607131532 SMP Wed Jul 13 19:34:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

cat /proc/version 
Linux version 4.2.8-040208ckt13-generic (kernel@gomeisa) (gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2) ) #201607131532 SMP Wed Jul 13 19:34:20 UTC 2016
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Best regards, Dmitry

**Comment by Oleksiy-Yakovenko** [comment]
@eshchenko can you try again with latest master -- commit #cbd5d9b more specifically?
It's quite suspicious that only cue files stop working after the commit you referred to, which introduced the use of AC_SYS_LARGEFILE.
If this fix doesn't help, I'll try to investigate more. It's problematic to revert, because in my understanding this would break musl builds. Potentially may require a special manually specified configure flag for musl users.

**Comment by eshchenko** [comment]
Dear Oleksiy
I had just compiled the fresh git -
Unfortunately the cue problem remains.
How can I help you?
Best, Dmitry


пт, 3 мая 2024 г. в 20:02, Oleksiy Yakovenko ***@***.***>:

**Comment by Oleksiy-Yakovenko** [comment]
I made another attempt -- basically keeping both AC_SYS_LARGEFILE, and using lseek64 in vfs_stdio.
Please give it a try.

Other than that, I still can't see any obvious problem with the code. It would take some debugging on device to figure out what goes wrong.

**Comment by Oleksiy-Yakovenko** [comment]
It might help if you post your config.log after running ./configure

**Comment by Oleksiy-Yakovenko** [comment]
Thanks for the logs. From the logs, the only impression I could get is that AC_SYS_LARGEFILE is not really working on RPI system. Maybe it doesn't work with any 32 bit systems.
Either way, I think that removing it would not do harm anymore, since I already added glibc ifdef, so the code should run fine on musl systems.

**Comment by Oleksiy-Yakovenko** [comment]
There's a downside of this change: on 32 bit systems which don't use glibc there would not be large file support.
This will primarily affect more exotic systems. I hope to find a better fix in the future.
