### ISSUE TITLE
Media library plug-in: how does it work ?

### ISSUE THREAD

**Issue by jcelerier** [DeaDBeeF-Player/deadbeef#3071]
### Steps to reproduce the problem

- Open deadbeef with the media library plug-in
- No media library visible anywhere

### What's going on? Describe the problem in as much detail as possible.

- I see "Media library" in the plug-in list but in my UI there is nothing that looks like a media library (tried with the GTK2 and GTK3 plug-in): 
![](https://github.com/DeaDBeeF-Player/deadbeef/assets/2772730/b0ea6f1c-e9c5-4210-b83a-f98238eb0189)

- The menus (File, Edit, View etc) don't mention anything related

### Information about the software:

Deadbeef version:
Built from git master e7aa955ab 

OS:
Linux

**Comment by Oleksiy-Yakovenko** [comment]
Medialib is not really a released feature yet, but if you need to try it out -- you will need to add it by using design mode.
