### ISSUE TITLE
playlist browser does not mark currently playing one

### ISSUE THREAD

**Issue by elandorr** [DeaDBeeF-Player/deadbeef#3075]
### Steps to reproduce the problem
Add the playlist browser item and multiple lists.

### What's going on? Describe the problem in as much detail as possible.
No indication is shown about which one is active. The "playing" column is empty.

Preferably it would bolden or color mark it, without another column taking up space.

As a sidenote: Can the font in the playlist browser be changed somehow? There's no option in regular settings.

![image](https://github.com/DeaDBeeF-Player/deadbeef/assets/56206745/6b4117bc-90dd-47c4-a434-266b0943f2cb)

### Information about the software:

Deadbeef version: 1.9.6
OS: linux 6.8.4

**Comment by Oleksiy-Yakovenko** [comment]
I can't reproduce this, it seems to be working fine

<img width="189" alt="image" src="https://github.com/DeaDBeeF-Player/deadbeef/assets/1895698/b2c0aa3d-0500-46b3-9e47-4b653b23fdeb">

**Comment by Oleksiy-Yakovenko** [comment]
> As a sidenote: Can the font in the playlist browser be changed somehow? There's no option in regular settings.

You can probably customize it by modifying the GTK theme / CSS, but not from Deadbeef settings.

**Comment by Oleksiy-Yakovenko** [comment]
Ok, confirmed -- this bug occurs in GTK2 but not in GTK3 plugin.
