### ISSUE TITLE
DeadBeeF won't load MP3 files

### ISSUE THREAD

**Issue by taitox** [DeaDBeeF-Player/deadbeef#3077]
### Steps to reproduce the problem
Try to load, using any means, some specific songs or folders.

### What's going on? Describe the problem in as much detail as possible.
As said in the title, DeadBeeF refuses to load any files encoded in MP3. Any FLAC file plays just fine, alongside somewhat niche formats such as VGM, GBS that are also supported without any extra effort.

### Information about the software:
Deadbeef version: 1.9.6-1, installed from AUR
OS: Linux, kernel 6.8.4-arch1-1

**Comment by Oleksiy-Yakovenko** [comment]
Most likely you don't have the MP3 libraries installed. Try installing libmpg123 or libmad, and it should start working.
