### ISSUE TITLE
Failed to execute the encoder

### ISSUE THREAD

**Issue by nsvg** [DeaDBeeF-Player/deadbeef#3078]
### Steps to reproduce the problem
Choose a file
click convert

get following error:
Write error (-1 bytes written out of 8000)
Failed to execute the encoder, command used:
lame -V2 - "/Users/USERNAME/Music/MUSIK/Lossless/A/Anna von Hausswolff/(2020) All Thoughts Fly [FLAC]/All Thoughts Fly.mp3"

### What's going on? Describe the problem in as much detail as possible.
On macos with apple silicon, converting does not work. Does not matter which format, I get the error exemplified with the file above while converting FLAC to mp3.
I have installed lame separately, via homebrew and via macports. Neither seem to do the trick (I used one at a time).
Have tried different directories, same issues.

On my old mac (intel i5 2020) using either deadbeef from sourceforge or from github, it converts without a problem.

Is it apple silicon that is the issue?

For the record, using media human audio converter, I can convert files without a problem on the apple silicon laptop.

### Information about the software:

Deadbeef version: devel (1), from github (latest)
OS: macos sonoma 14.4.1, using apple silicon (m3max)

**Comment by Oleksiy-Yakovenko** [comment]
Currently I don't have access to AS mac, but it should not be an issue generally, since deadbeef runs natively both on Intel and AS macs.

I can't really answer why it doesn't work, since I don't have enough details, but you can check a few things:

* Is `lame` in your PATH environment variable?
* Does deadbeef have permission to run it?
* Does it work if you run it directly on command line?

**Comment by nsvg** [comment]
Hi,
Thank you for the quick reply
-lame is in the PATH
-I have just given deadbeef full disk access
-lame runs directly from the command line

I just tried and it still does not convert

**Comment by Oleksiy-Yakovenko** [comment]
I will investigate as soon as I can.

**Comment by nsvg** [comment]
By the way, I checked on the intel mac, and deadbeef does not have full
disk access, and it converts without issue.

**Comment by Oleksiy-Yakovenko** [comment]
Did you check that deadbeef itself is not running in Rosetta mode?

**Comment by nsvg** [comment]
I'll check that after work!

Den fre 12 apr. 2024 11:29Oleksiy Yakovenko ***@***.***>
skrev:

**Comment by nsvg** [comment]
It was not running in Rosetta mode (using Rosetta mode did not change anything)

**Comment by nsvg** [comment]
I’ll keep fiddling and trying :)

**Comment by thomasjepp** [comment]
Hey - can you run `which lame` and post the results?

I tried this on my AS mac and the problem for me is that homebrew installs lame to `/opt/homebrew/bin/lame` - which isn't *actually* in PATH, because homebrew changes PATH by adding extra bits to `.zshrc` and/or `.zprofile`.

On an intel mac, lame ends up in `/usr/local/bin/lame`, which I believe is in PATH by default.

**Comment by nsvg** [comment]
output is `/opt/homebrew/bin/lame`

I added manually to path (`etc/paths`) when installed via homebrew, still nothing. Even when installed via macports, nothing happened.

The only commands that work in the convert dialog are file cope and file move, none of the others work. Can you convert to different / any formats at all?

**Comment by thomasjepp** [comment]
When I was testing, I found creating a symlink pointing to /opt/homebrew/bin/lame in /usr/local/bin made it work.

**Comment by Oleksiy-Yakovenko** [comment]
> I added manually to path (etc/paths) when installed via homebrew, still nothing.

You should probably search for a newer way of setting environment variables globally on mac.
Unfortunatelly it's not trivial.
Hopefulle one of the solutions provided here should work:
https://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite

**Comment by nsvg** [comment]
Thanks for the link. For some reason on AS adding to path has not been as straightforward as it was on the intel mac, don't know why really since both are on latest sonoma. I had to use that less optimal way (`etc/paths`), because some python based software I use for work (xray larch) could not be added to path easily and doing it manually somehow worked.

I will try the symlink solution!

**Comment by nsvg** [comment]
> When I was testing, I found creating a symlink pointing to /opt/homebrew/bin/lame in /usr/local/bin made it work.

it works, thanks!

**Comment by Oleksiy-Yakovenko** [comment]
Thanks for the investigation. I'll keep this issue open, since I would like to mitigate it somewhat.

**Comment by Oleksiy-Yakovenko** [comment]
Should be fixed now, converter will now add the standard homebrew and macports bin paths to the PATH env variable before trying to run the command line encoders.
