### ISSUE TITLE
Library in deadbeef?

### ISSUE THREAD

**Issue by KOT040188** [DeaDBeeF-Player/deadbeef#3082]
I found this page on the wiki https://github.com/DeaDBeeF-Player/deadbeef/wiki/Customizing-Media-Library-Queries Is this a media library? How to get it and use it????

**Comment by Oleksiy-Yakovenko** [comment]
Media library is not part of the 1.9.6 release, but you can try it by running a nightly build.
On mac it's available without any additional configuration (in the left sidebar), and on linux/gtk you would need to add Media library browser to the UI using design mode.
