### ISSUE TITLE
No chance to build for modern Debian i386?

### ISSUE THREAD

**Issue by greenais** [DeaDBeeF-Player/deadbeef#3085]
### Steps to reproduce the problem
Compile from source on Debian Bookworm i386

### What's going on? Describe the problem in as much detail as possible.
configure ends with no issues, but make brings error
```
n file included from gtkui.c:47:
./covermanager/covermanager.h:29:10: fatal error: 'dispatch/dispatch.h' file not found
#include <dispatch/dispatch.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
which probably isn't unexpected since both 
libblockruntime
libdispatch
strict dependencies are absent in Debian Stable (i.e.libdispatch was completely removed in 2022), which, in turn, means that Deadbeef can't be compiled for amd64 as well.
But official downloads page offers .deb package for amd64 - how, are there any "secret" tips on how to build on modern Debian?

There is no pre-compiled option offered for Debian i386, so building is the last resort which is... impossible?
Please advise

### Information about the software:

Deadbeef version: latest source 1.9.6
OS: Debian 12 Bookworm

**Comment by Oleksiy-Yakovenko** [comment]
It's totally possible, you would just need to compile the dependencies which are not provided by your distribution.
The official packages don't really use much of prepackaged distribution libraries. Most dependencies are "built in".
