### ISSUE TITLE
$longer(x,y) is supposed to be a boolean function

### ISSUE THREAD

**Issue by percontation** [DeaDBeeF-Player/deadbeef#3087]
`tf_func_longer` just calls `tf_func_longest`, which I believe is wrong.

The documentation I see says that `$longer(x,y)` is supposed to be like `$greater($len(x),$len(y))`, rather than like `$longest(x,y)`.

**Comment by Oleksiy-Yakovenko** [comment]
Fixed, thanks for noticing!
