### ISSUE TITLE
Crash when changing appearance

### ISSUE THREAD

**Issue by misscx** [DeaDBeeF-Player/deadbeef#3090]
As shown in the picture below, deadbeef crashed after clicking OK.
![截图 2024-05-12 21-39-20](https://github.com/DeaDBeeF-Player/deadbeef/assets/5102639/a2f435b9-6db7-4fb0-b7b8-7b0b68db698d)

### Information about the software:

Deadbeef version: 1.9.6
OS: ubuntu24.04

**Comment by Oleksiy-Yakovenko** [comment]
Just FYI: I won't be able to try reproducing and fixing this until June or so. Hope you can find a workaround in the meantime.

**Comment by Oleksiy-Yakovenko** [comment]
I managed to get the crash once, and then it never reproduced.
Is it the same for you, or does it crash every time?

**Comment by Oleksiy-Yakovenko** [comment]
Also, can you confirm that you're running GTK2 UI in deadbeef? From screenshot it looks like GTK2.

**Comment by Oleksiy-Yakovenko** [comment]
I found a reliable repro for this behavior -- just clicking the color button, and then immediately hitting Enter. Repeating this 5-10 times would result in either a crash or hang.

The crash is a non-debuggable GTK error handler (seemingly some bug in how it interacts with X11).
And the hang is sitting in xcb_wait_for_reply64 during tooltip handling.

None of these are deadbeef bugs, they're internal to GTK, and I would not be able to fix them.
GTK3 plugin in deadbeef doesn't seem to have this problem, so I recommend to switch to that.
