### ISSUE TITLE
Feature request: displaying bitspersample (like 16 or 24 bits) in the tracklist

### ISSUE THREAD

**Issue by jrm-omg** [DeaDBeeF-Player/deadbeef#3096]
### Steps to reproduce the problem

- Customizing the tracklist column
- Adding the `%:bitspersample%` or `%bitspersample%` tag
- Bits per sample not displayed :B

### What's going on? Describe the problem in as much detail as possible.

Wish I could display the bits per sample in the track list, like [Foobar2k's](https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#Technical_information_functions) :shushing_face: 

For now I can only display : `%samplerate%`, `%codec%`, `%bitrate%` and `%:codec_profile%` which is still very appreciated, though

### Information about the software:

Deadbeef version: 1.9.1
OS: Linux Mint

**Comment by Oleksiy-Yakovenko** [comment]
$info(bitspersample) is not yet implemented in deadbeef, but in the meantime you could use %:BPS% -- this one works
