### ISSUE TITLE
Menubar missing 

### ISSUE THREAD

**Issue by Pandoroeo** [DeaDBeeF-Player/deadbeef#3104]
### Information about the software: 

Deadbeef version: 1.9.6
OS: Endeavour os (Arch linux based distro) 

Log: https://pastebin.com/nyAGNe7w

Desktop enviorment: Kde plasma
Window manager: Wayland

System info: 
![image](https://github.com/DeaDBeeF-Player/deadbeef/assets/137426202/07ea9137-004c-4bfd-8820-71da22b65509)

**Comment by Oleksiy-Yakovenko** [comment]
> The toolbar with the file, edit, view, and help tabs doesn't exist. I don't know why.

It is what people usually call "menu bar", correct?

If it has anything to do with deadbeef settings -- you can either delete the config, or you can search for menu-related options in the configuration file (~/.config/deadbeef/config), and maybe you'll get some new ideas.

**Comment by Pandoroeo** [comment]
> It is what people usually call "menu bar", correct?

Yes, that's what I meant.

> If it has anything to do with deadbeef settings -- you can either delete the config, or you can search for menu-related options in the configuration file (~/.config/deadbeef/config), and maybe you'll get some new ideas.

I tried to completely nuke my install. I deleted everything related to deadbeef (I.e. configs, install, etc..) I downloaded the tar.bz2 and unzipped it. I then ran the deadbeef file, but the menubar was still missing. This is the config it generated: 

<details>
<summary>DeadBeef config</summary>

deadbeef_version 1.9.6
gtkui.columns.playlist [{"title":"♫","id":"1","format":"%playstatus%","sort_format":"","size":"50","align":"0","color_override":"0","color":"#ff000000"},{"title":"Artist / Album","id":"-1","format":"$if(%artist%,%artist%,Unknown Artist)[ - %album%]","sort_format":"","size":"150","align":"0","color_override":"0","color":"#ff000000"},{"title":"Track No","id":"-1","format":"%tracknumber%","sort_format":"","size":"50","align":"1","color_override":"0","color":"#ff000000"},{"title":"Title","id":"-1","format":"%title%","sort_format":"","size":"150","align":"0","color_override":"0","color":"#ff000000"},{"title":"Duration","id":"-1","format":"%length%","sort_format":"","size":"50","align":"0","color_override":"0","color":"#ff000000"}]
gtkui.columns.search [{"title":"Artist / Album","id":"-1","format":"$if(%artist%,%artist%,Unknown Artist)[ - %album%]","sort_format":"","size":"150","align":"0","color_override":"0","color":"#ff000000"},{"title":"Track No","id":"-1","format":"%tracknumber%","sort_format":"","size":"50","align":"1","color_override":"0","color":"#ff000000"},{"title":"Title","id":"-1","format":"%title%","sort_format":"","size":"150","align":"0","color_override":"0","color":"#ff000000"},{"title":"Duration","id":"-1","format":"%length%","sort_format":"","size":"50","align":"0","color_override":"0","color":"#ff000000"}]
gtkui.layout.1.9.0 {"type":"vbox","legacy_params":" expand=\"0 1\" fill=\"1 1\" homogeneous=0","children":[{"type":"hbox","legacy_params":" expand=\"0 1 0\" fill=\"1 1 1\" homogeneous=0","children":[{"type":"playtb"},{"type":"seekbar"},{"type":"volumebar","settings":{"scale":"db"}}]},{"type":"tabbed_playlist","legacy_params":" hideheaders=0 width=1920"}]}
gtkui.playlist.group_by_tf 
gtkui.search.group_by_tf 
gtkui.statusbar.visible 1
gtkui.tabscroll 0
hotkey.key01 "Ctrl f" 0 0 find
hotkey.key02 "Ctrl o" 0 0 open_files
hotkey.key03 "Ctrl q" 0 0 quit
hotkey.key04 "Ctrl n" 0 0 new_playlist
hotkey.key05 "Ctrl a" 0 0 select_all
hotkey.key06 "Escape" 0 0 deselect_all
hotkey.key07 "Ctrl m" 0 0 toggle_stop_after_current
hotkey.key08 "Ctrl j" 0 0 jump_to_current_track
hotkey.key09 "F1" 0 0 help
hotkey.key10 "Delete" 1 0 remove_from_playlist
hotkey.key11 "Ctrl w" 0 0 remove_current_playlist
hotkey.key13 "Alt Return" 1 0 track_properties
hotkey.key14 "Return" 0 0 play
hotkey.key15 "Ctrl p" 0 0 toggle_pause
hotkey.key16 "Alt 1" 0 0 playlist1
hotkey.key17 "Alt 2" 0 0 playlist2
hotkey.key18 "Alt 3" 0 0 playlist3
hotkey.key19 "Alt 4" 0 0 playlist4
hotkey.key20 "Alt 5" 0 0 playlist5
hotkey.key21 "Alt 6" 0 0 playlist6
hotkey.key22 "Alt 7" 0 0 playlist7
hotkey.key23 "Alt 8" 0 0 playlist8
hotkey.key24 "Alt 9" 0 0 playlist9
hotkey.key25 "Alt 0" 0 0 playlist10
hotkey.key26 z 0 0 prev
hotkey.key27 x 0 0 play
hotkey.key28 c 0 0 toggle_pause
hotkey.key29 v 0 0 stop
hotkey.key30 b 0 0 next
hotkey.key31 n 0 0 playback_random
hotkey.key32 "Ctrl k" 0 0 toggle_stop_after_album
hotkeys_created 1
mainwin.geometry.h 300
mainwin.geometry.maximized 1
mainwin.geometry.w 500
mainwin.geometry.x 40
mainwin.geometry.y 40
output_plugin alsa
playback.loop 1
playback.volume.normalized 1.0000000
playlist.cursor.0 0
playlist.scroll.0 0
playlist.scroll.cursorfollowplayback 1
playlist.tab.00000 Default
resume.paused 0
resume.playlist -1
resume.position -1.000000
resume.track -1

</details>

**Comment by Oleksiy-Yakovenko** [comment]
Can you post a screenshot of:
1. deadbeef running without the menu
2. another GTK app running with the menu?

**Comment by Oleksiy-Yakovenko** [comment]
I can't explain why this happens, but I can suggest one thing:

Open deadbeef settings, and check which UI is selected -- GTK2 or GTK3.
Try changing to the other one, and restart deadbeef.
Maybe this is the culprit.

**Comment by Pandoroeo** [comment]
> I can't explain why this happens, but I can suggest one thing:
> 
> Open deadbeef settings, and check which UI is selected -- GTK2 or GTK3. Try changing to the other one, and restart deadbeef. Maybe this is the culprit.

I can't access the deadbeef settings because the menubar is missing. Is there a shortcut of some sort I can use to access settings? (Even manually adding it?) Thanks!

**Comment by Pandoroeo** [comment]
> You can run deadbeef from command line, and specify the ui from there. I believe it should look like `--gui GTK2` or `--gui GTK3`

I opened deadbeef with --gui GTK2 and it now works, even when I'm not running it through cmd. Huh, how odd. (I ran it using ./deadbeef --gui GTK2). Thanks for your help!
