### ISSUE TITLE
Volume while playing Amiga Modules is too low

### ISSUE THREAD

**Issue by ralph303** [DeaDBeeF-Player/deadbeef#3108]
### Steps to reproduce the problem
Download and play some Amiga Module, for example:
https://modarchive.org/index.php?request=view_by_moduleid&query=50003

### What's going on? Describe the problem in as much detail as possible.
The volume is much too low compared to playing an MP3 or playing sound in Firefox for example

### Information about the software:
Deadbeef version: 1.9.6
OS: Fedora Linux Asahi Remix 40 (Workstation Edition)

**Comment by Oleksiy-Yakovenko** [comment]
I'm listening to both MP3s and mod files of various kinds on a daily basis, and there's no problem with the volume.
I just tried the mod file you linked, and it's also playing at normal volume.
Can you make an audio recording so that I can get an appropriate impression how much is the volume difference on your computer between mod files and other files? You should be able to do it with your phone.

**Comment by Oleksiy-Yakovenko** [comment]
Also one thing that is important to know is that a lot of (especially modern) recordings are highly compressed, so they will sound louder.

So it depends which audio files you're comparing to.

I just tried comparing a MOD against some well mastered tracks from synth-wave albums, and they were about the same percepted loudness. Other albums like modern metal were highly compressed, so they were basically using full dynamic range (louder).

Older metal album (Megadeth - Rust in peace) was properly mastered as well, and sounded at the same level.

Then I tried some techno / trance albums, and they were somewhere in between (slightly louder, but not compressed to the limit).

**Comment by Oleksiy-Yakovenko** [comment]
Aside of that, you can try playing with the plugin which is responsible for MOD playback.
It's called DUMB module player, and it has its own volume control. Maybe you accidentally lowered it, or maybe you just don't like the default level -- either was it might help (you'll need to restart a playing track for that setting to take effect).

**Comment by Oleksiy-Yakovenko** [comment]
<img width="815" alt="image" src="https://github.com/user-attachments/assets/de872417-d82c-4cae-acb4-7e560c86317e">

**Comment by ralph303** [comment]
Thanks for you suggestions, the internal volume helps a bit, but the differnce in volume is still huge.
I uploaded a video which shows playback with the default settings:
https://uploadnow.io/f/JVjxVWw

**Comment by ralph303** [comment]
I uploaded a second video comparing the sound output of DeaDBeeF and XMP:
https://uploadnow.io/f/nvbDkSY

Playback via XMP is not only much louder, there is also more dynamic range. Something is missing in the module playback of the DUMB plugin, it's less dynamic and there is nearly no bass.

**Comment by Oleksiy-Yakovenko** [comment]
I tried foobar2000 to get some comparison.
The volume level is the same if I set "internal DUMB volume" to 128 in deadbeef, but high frequencies are missing in deadbeef.
Will investigate.

**Comment by Oleksiy-Yakovenko** [comment]
The high(er) frequency output is some additional feature of foo_dumb/foo_deaf called "Use playptmod for MOD" in the component settings.
I don't know how this feature works, and there doesn't seem to be any source code to find out.

If I disable this option -- FB2K+foo_deaf plays similar / identical as deadbeef.

**Comment by Oleksiy-Yakovenko** [comment]
Also, of course using openmpt plugin in FB2K playback is quite different. So yeah -- I believe that this is just how DUMB plays. Crank it to 128, and that's all you get :)
Btw -- you can also get openmpt plugin for deadbeef from here (I don't know whether it works though).
https://bitbucket.org/losnoco/deadbeef_plugins/src/master/plugins/openmpt/

**Comment by ralph303** [comment]
Thanks for pointing me to OpenMPT, that helped alot!
