### ISSUE TITLE
DeadBeef doesn't recognize mounts

### ISSUE THREAD

**Issue by RayB39872** [DeaDBeeF-Player/deadbeef#3109]
### Steps to reproduce the problem
Ubuntu 24.04. WD elements 4TB, Qnap NAS231P3. Mmusic files mp3/flas on both.
### What's going on? Describe the problem in as much detail as possible.
Mounts are recognised by VLC on ubuntu 24.04 and can play, however, like to use a dedicated music player DeadBeef, no mounts recognised, nor wb or nas
### Information about the software:
see above
Deadbeef version: 1.8.7
OS: 24.04

**Comment by Oleksiy-Yakovenko** [comment]
Deadbeef installed from snap package?

**Comment by RayB39872** [comment]
Yes....

**Comment by RayB39872** [comment]
got it working now, appearantly the install didn't complete:
sudo apt install ./deadbeef-static*amd64.deb
sudo chown -R _apt:root /var/cache/apt/archives/partial/
sudo chmod -R 700 /var/cache/apt/archives/partial/

**Comment by Oleksiy-Yakovenko** [comment]
Cool. Yes, the official build (called static on the website) is the right one, it should work.
Snap build is unofficial, and is known to have this sort of problems.
