### ISSUE TITLE
Two file browser plugin trouble spots

### ISSUE THREAD

**Issue by tmsg-gh** [DeaDBeeF-Player/deadbeef#3112]
### Steps to reproduce the problem
None really. Happens immediately after unpacking from the latest sourceforge release, adding the file browser plugin and running deadbeef.

### What's going on? Describe the problem in as much detail as possible.
1. The four icons (below the file browser path entry box) are not shown. I assume they're simply missing from my icon set but I've no idea what these missing icon files (or filenames) might be. See this:
![db](https://github.com/user-attachments/assets/bc5f3c4e-1adf-4c7b-a61b-669df2784429)

2. If I set a default path in the file browser plugin settings, this is not reflected in the file browser path entry box when I restart deadbeef. Also clicking the last of the four icons doesn't jump to the default directory... IOW I always have to enter that directory manually.

Other than that I am pretty impressed: was for a long time on the lookout to replace foobar2k and deadbeef comes closer than any others I've tried :+1:

### Information about the software:
Deadbeef version: 1.9.6
OS: Debian 12/amd 64/XFCE/Adwaita icon set.

**Comment by Oleksiy-Yakovenko** [comment]
Hello,
File browser plugin is a separate project, you can report issues to it over here:

https://gitlab.com/zykure/deadbeef-fb/-/issues
