### ISSUE TITLE
Allow building with gcc, do not force clang (possibly, for no-GUI version)

### ISSUE THREAD

**Issue by barracuda156** [DeaDBeeF-Player/deadbeef#3114]
### Steps to reproduce the problem
Try building with gcc

### What's going on? Describe the problem in as much detail as possible.
Configure fails:
```
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_DeaDBeeF/DeaDBeeF/work/deadbeef-1.9.6" && ./configure --prefix=/opt/local --disable-alsa --disable-oss --disable-pipewire --disable-pulse --disable-gtk2 --enable-coreaudio --enable-gtk3 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether sleep supports fractional seconds... yes
checking filesystem timestamp resolution... 2
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /opt/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking xargs -n works... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... ccache /opt/local/bin/gcc-mp-14
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether ccache /opt/local/bin/gcc-mp-14 accepts -g... yes
checking for ccache /opt/local/bin/gcc-mp-14 option to enable C11 features... none needed
checking whether ccache /opt/local/bin/gcc-mp-14 understands -c and -o together... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking for sys/param.h... yes
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking build system type... powerpc-apple-darwin10.0.0d2
checking host system type... powerpc-apple-darwin10.0.0d2
checking how to print strings... printf
checking for a sed that does not truncate output... /opt/local/bin/gsed
checking for grep that handles long lines and -e... /opt/local/bin/ggrep
checking for egrep... /opt/local/bin/ggrep -E
checking for fgrep... /opt/local/bin/ggrep -F
checking for ld used by ccache /opt/local/bin/gcc-mp-14... /opt/local/bin/ld
checking if the linker (/opt/local/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /opt/local/bin/nm -B
checking the name lister (/opt/local/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert powerpc-apple-darwin10.0.0d2 file names to powerpc-apple-darwin10.0.0d2 format... func_convert_file_noop
checking how to convert powerpc-apple-darwin10.0.0d2 file names to toolchain format... func_convert_file_noop
checking for /opt/local/bin/ld option to reload object files... -r
checking for file... file
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /opt/local/bin/nm -B output from ccache /opt/local/bin/gcc-mp-14 object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if ccache /opt/local/bin/gcc-mp-14 supports -fno-rtti -fno-exceptions... no
checking for ccache /opt/local/bin/gcc-mp-14 option to produce PIC... -fno-common -DPIC
checking if ccache /opt/local/bin/gcc-mp-14 PIC flag -fno-common -DPIC works... yes
checking if ccache /opt/local/bin/gcc-mp-14 static flag -static works... no
checking if ccache /opt/local/bin/gcc-mp-14 supports -c -o file.o... yes
checking if ccache /opt/local/bin/gcc-mp-14 supports -c -o file.o... (cached) yes
checking whether the ccache /opt/local/bin/gcc-mp-14 linker (/opt/local/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin10.0.0d2 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether the compiler supports GNU C... (cached) yes
checking whether ccache /opt/local/bin/gcc-mp-14 accepts -g... (cached) yes
checking for ccache /opt/local/bin/gcc-mp-14 option to enable C11 features... (cached) none needed
checking whether ccache /opt/local/bin/gcc-mp-14 understands -c and -o together... (cached) yes
checking whether the compiler supports GNU C++... yes
checking whether ccache /opt/local/bin/g++-mp-14 accepts -g... yes
checking for ccache /opt/local/bin/g++-mp-14 option to enable C++11 features... none needed
checking how to run the C++ preprocessor... ccache /opt/local/bin/g++-mp-14 -E
checking for ld used by ccache /opt/local/bin/g++-mp-14... /opt/local/bin/ld
checking if the linker (/opt/local/bin/ld) is GNU ld... no
checking whether the ccache /opt/local/bin/g++-mp-14 linker (/opt/local/bin/ld) supports shared libraries... yes
checking for ccache /opt/local/bin/g++-mp-14 option to produce PIC... -fno-common -DPIC
checking if ccache /opt/local/bin/g++-mp-14 PIC flag -fno-common -DPIC works... yes
checking if ccache /opt/local/bin/g++-mp-14 static flag -static works... no
checking if ccache /opt/local/bin/g++-mp-14 supports -c -o file.o... yes
checking if ccache /opt/local/bin/g++-mp-14 supports -c -o file.o... (cached) yes
checking whether the ccache /opt/local/bin/g++-mp-14 linker (/opt/local/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin10.0.0d2 dyld
checking how to hardcode library paths into programs... immediate
checking whether the compiler supports GNU Objective C... yes
checking whether ccache /opt/local/bin/gcc-mp-14 accepts -g... yes
checking for egrep... (cached) /opt/local/bin/ggrep -E
checking for ccache /opt/local/bin/gcc-mp-14 option to enable large file support... none needed
checking whether byte ordering is bigendian... yes
checking whether NLS is requested... yes
checking for msgfmt... /opt/local/bin/msgfmt
checking for gmsgfmt... /opt/local/bin/msgfmt
checking for xgettext... /opt/local/bin/xgettext
checking for msgmerge... /opt/local/bin/msgmerge
checking how to run the C preprocessor... ccache /opt/local/bin/gcc-mp-14 -E
checking for egrep -e... (cached) /opt/local/bin/ggrep -E
checking whether we are using the GNU C Library 2 or newer... no
checking for ranlib... (cached) ranlib
checking whether the -Werror option is usable... yes
checking for simple visibility declarations... yes
checking for inline... inline
checking for size_t... yes
checking for stdint.h... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for getpagesize... yes
checking for working mmap... yes
checking whether integer division by zero raises SIGFPE... no
checking for inttypes.h... yes
checking for unsigned long long int... yes
checking for inttypes.h... (cached) yes
checking whether the inttypes.h PRIxNN macros are broken... no
checking for ld used by GCC... /opt/local/bin/ld
checking if the linker (/opt/local/bin/ld) is GNU ld... no
checking for shared library run path origin... done
checking whether imported symbols can be declared weak... no
checking for pthread.h... yes
checking for pthread_kill in -lpthread... yes
checking for multithread API to use... posix
checking for pthread_rwlock_t... yes
checking for argz.h... no
checking for inttypes.h... (cached) yes
checking for limits.h... yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getcwd... yes
checking for getegid... yes
checking for geteuid... yes
checking for getgid... yes
checking for getuid... yes
checking for mempcpy... no
checking for munmap... yes
checking for stpcpy... yes
checking for strcasecmp... yes
checking for strdup... yes
checking for strtoul... yes
checking for tsearch... yes
checking for uselocale... yes
checking for argz_count... no
checking for argz_stringify... no
checking for argz_next... no
checking for __fsetlocking... no
checking whether feof_unlocked is declared... yes
checking whether fgets_unlocked is declared... no
checking for iconv... yes
checking for working iconv... yes
checking how to link with libiconv... -liconv
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for bison... bison
checking version of bison... 3.8.2, ok
checking for long long int... yes
checking for wchar_t... yes
checking for wint_t... yes
checking for intmax_t... yes
checking whether printf() supports POSIX/XSI format strings... yes
checking whether we are using the GNU C Library 2.1 or newer... no
checking for stdint.h... (cached) yes
checking for SIZE_MAX... yes
checking for stdint.h... (cached) yes
checking for working fcntl.h... no (bad O_NOATIME)
checking for CFPreferencesCopyAppValue... yes
checking for CFLocaleCopyCurrent... yes
checking for ptrdiff_t... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for asprintf... yes
checking for fwprintf... yes
checking for newlocale... yes
checking for putenv... yes
checking for setenv... yes
checking for setlocale... yes
checking for snprintf... yes
checking for strnlen... no
checking for wcslen... yes
checking for wcsnlen... no
checking for mbrtowc... yes
checking for wcrtomb... yes
checking whether _snprintf is declared... no
checking whether _snwprintf is declared... no
checking whether getc_unlocked is declared... yes
checking for nl_langinfo and CODESET... yes
checking for LC_MESSAGES... yes
checking for CFPreferencesCopyAppValue... (cached) yes
checking for CFLocaleCopyCurrent... (cached) yes
checking whether included gettext is requested... no
checking for GNU gettext in libc... no
checking for GNU gettext in libintl... yes
checking whether to use NLS... yes
checking where the gettext function comes from... external libintl
checking how to link with libintl... -lintl -Wl,-framework -Wl,CoreFoundation
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for iconv... (cached) yes
checking for working iconv... (cached) yes
checking how to link with libiconv... -liconv
checking for iconv declaration... (cached) 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for intltool >= 0.40.0... 0.51.0 found
checking for intltool-update... /opt/local/bin/intltool-update
checking for intltool-merge... /opt/local/bin/intltool-merge
checking for intltool-extract... /opt/local/bin/intltool-extract
checking for xgettext... (cached) /opt/local/bin/xgettext
checking for msgmerge... (cached) /opt/local/bin/msgmerge
checking for msgfmt... (cached) /opt/local/bin/msgfmt
checking for gmsgfmt... (cached) /opt/local/bin/msgfmt
checking whether C compiler accepts -fblocks... no
configure: error: Clang is required to build DeaDBeeF. Please check the README file.
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_DeaDBeeF/DeaDBeeF/work/deadbeef-1.9.6" && ./configure --prefix=/opt/local --disable-alsa --disable-oss --disable-pipewire --disable-pulse --disable-gtk2 --enable-coreaudio --enable-gtk3 
Exit code: 1
```

### Information about the software:

Deadbeef version: 1.9.6
OS: macOS 10.6

**Comment by barracuda156** [comment]
I took a look at the source code, looks like gcc can build only GUI-less version, since even GTK GUI, unfortunately, uses blocks quite a bit.
That is still better than nothing though, and for audio GUI is not really required.

**Comment by Oleksiy-Yakovenko** [comment]
Deadbeef codebase makes use of blocks (closures) which are a clang extension. As soon as gcc provides an alternative, supporting gcc will be considered, but currently it's not feasible.

**Comment by barracuda156** [comment]
> Deadbeef codebase makes use of blocks (closures) which are a clang extension. As soon as gcc provides an alternative, supporting gcc will be considered, but currently it's not feasible.

Yes, I have noticed that, but blocks are used almost exclusively in GUI-related stuff. GUI can be made optional, CLI player should still work (and no need to support cover art then).

P. S. GCC upstream considers adding support for blocks, but no timeline at the moment. They are aware of the issue.

**Comment by Oleksiy-Yakovenko** [comment]
I can't offer an easy solution to this. A lot of users asked to add an error when gcc is used. If you want to do exotic things - please remove the check from configure.ac

**Comment by barracuda156** [comment]
@Oleksiy-Yakovenko Just for the record, I could compile `DeaDBeeF` with GTK3 GUI on macOS with gcc without blocks. While some optional components use blocks a lot, they can be disabled via configure args. The only two places where blocks are used in required components are `main.c` and `plugins.c`, where block syntax was added in 698993731e93eea0d80f5152a7e9e316e835d8aa and 201c12a999b3f36354b53934ee4de4a3648d1929 – reverting these commits worked as a quick solution (should not be too hard to switch from blocks to portable C code).
If you could consider addressing these two instances, the problem will be solved for everyone.

**Comment by Oleksiy-Yakovenko** [comment]
@barracuda156 It seems like you're seeing Deadbeef's dependency on Clang as an accident, that needs addressing.
This is not the case. It was a deliberate choice, in order to be able to use blocks and libdispatch.
GCC doesn't provide an alternative. But if / when it does -- please be sure, GCC will be supported.
Before that time, it would not be possible to use GCC because the codebase relies on blocks and libdispatch for concurrency, and this is not going to change in the meantime.

**Comment by Oleksiy-Yakovenko** [comment]
I looked at the 2 files (main.c and plugins.c), and you're correct that it's possible to convert them to portable code without losing much convenience, at least it may be considered.
Before I spend any time on this, do you mind to share what's your specific use-case for building deadbeef with GCC?

**Comment by Oleksiy-Yakovenko** [comment]
I cleaned it up, main.c and plugins.c should now be buildable with gcc.

**Comment by barracuda156** [comment]
@Oleksiy-Yakovenko Thank you for looking into that. My personal use-case is to have a high-res audio player on powerpc macOS, where clang is broken (it never generated correct code for this target). I saw DeaDBeeF recommended on Head-Fi, and it uses CoreAudio, which makes it a great option. (Audacious can use CoreAudio, but there are some weird issues with endianness in it, I could only fix playback partly, and FLAC/ALAC still do not play – but those are exactly my regular formats.)
There are not many users of macOS on powerpc, admittedly (though some are, and they could appreciate a modern player working), however it seems to be broken on NetBSD as well, which also uses GCC as the system compiler. There is only a WIP old version: https://pkgsrc.se/wip/deadbeef 
So fixing DeaDBeeF for gcc will help NetBSD port.

**Comment by Oleksiy-Yakovenko** [comment]
It's hard for me to imagine why someone would decide to daily a mac from 20 years ago -- assuming not having access to almost any modern software or security patches. But to each their own.
Good to know that big endian support is still working in deadbeef.

**Comment by barracuda156** [comment]
> assuming not having access to almost any modern software

I would not say almost any, since largely everything is available, with a few exceptions – web browsing and online messengers (those are impactful for most users, so I am not downplaying the problem). These are not specific to old macOS though, and to a certain extent even Linux on powerpc is affected, and *BSD more so.

Specifically for audio old hardware is perfectly fine – it does not need GPU and is not too computationally intensive. And FireWire is more than enough for high-res files.

**Comment by barracuda156** [comment]
@Oleksiy-Yakovenko I realized that my report about the successful build _with gcc_ was ahead of time – being happy that it worked, I forgot that on my arm64 system the default compiler is clang. It also turned out that I missed initially a lot of instances with blocks in the GUI part, because I assumed, by mistake, that I have disabled those components. (While it actually works to disable GUI completely, the app does not launch without some GUI plugin available.)

However, after some hours of hackery and rebuilds, I got the functional app on powerpc. Can’t really test switching between DACs on this machine, but the playback works.

![Image](https://github.com/user-attachments/assets/b433a466-bdab-4ddd-be0d-6e483307ff84)

Looks like I need to set the right combo of bit-depth and rate in macOS Midi setup, otherwise speed of playback is wrong. This is definitely not something about your app, since audacious behaved the same when output settings in Midi setup mismatched those of a given file. There is probably some way to make it independent of the OS settings.

Interface is neat and slick (this is a huge plus for G4 machines).

Most of plugins built fine; `adplug` fails due to an upstream bug which was fixed in https://github.com/adplug/adplug/issues/247 (should work once the code gets updated); I have disabled medialib and artwork, since there are a lot of blocks used there; `portaudio` builds but did not work at least on arm64 machine (since CoreAudio works, there is no real need in `portaudio` anyway).

Thank you, very nice player!

**Comment by Oleksiy-Yakovenko** [comment]
> Looks like I need to set the right combo of bit-depth and rate in macOS Midi setup, otherwise speed of playback is wrong.

It sounds like you are missing the resampler plugin. There are two of them, but you'd probably have a better chance building the dsp_libsrc one.

**Comment by barracuda156** [comment]
@Oleksiy-Yakovenko Thank you, I will check it.
And for bit-perfect playback this recommendation still stands?
https://github.com/DeaDBeeF-Player/deadbeef/issues/1908
Is there an exclusive mode, so that only deadbeef can output to a given device?

**Comment by Oleksiy-Yakovenko** [comment]
I didn't really try this on mac, but I believe so, if you need bit perfect playback -- you just put the volume to 100%, and ensure no resampling / eq is applied.

**Comment by Oleksiy-Yakovenko** [comment]
And no, there's no special exclusive mode.

**Comment by barracuda156** [comment]
@Oleksiy-Yakovenko Will this be portable to deadbeef code? https://github.com/zaps166/QMPlay2/commit/e5400355054ce423d992f4e55d65c80fd3b4f460
(I mean what is your opinion re whether a similar code may work to the same effect, not whether you will port it or not yourself – obviously, there may not be such an interest or demand from typical users of the app.)
P. S. Or that is just redundant for CoreAudio here, since it is used directly?

**Comment by Oleksiy-Yakovenko** [comment]
Aside of boilerplate, it looks like the only thing of importance that this code does is `ResetNominalSampleRate`, which should be trivially addable.
I don't know whether or not it would do anything useful without trying, and I don't have suitable hardware to try.

**Comment by barracuda156** [comment]
@RJVB René, what do you think re CoreAudio and bit-perfect playback here?

**Comment by Oleksiy-Yakovenko** [comment]
Also FYI: I tried this approach in the past, but didn't like it since it affects audio in other applications and causes some samplerate-distortion. But it definitely works, in the sense that it may switch system samplerate to the device native one.
I believe, it should be possible to achieve the same thing without touching deadbeef code, just by configuring system samplerate via Audio MIDI Setup.

**Comment by barracuda156** [comment]
> it should be possible to achieve the same thing without touching deadbeef code, just by configuring system samplerate via Audio MIDI Setup

The issue with going via Audio MIDI setup is that, AFAIU, it requires to set the format there to match the format of a given file. Now consider a case – very typical, IMO – when albums have different combos of bitdepth and samplerate. It is technically possible to switch that every time, of course, but far from being convenient. That assumes I have marked every album with its format; if not, then I will need to correct the settings when playback already started.

**Comment by Oleksiy-Yakovenko** [comment]
Yes, that is true -- but it should be good enough to try it out.

**Comment by RJVB** [comment]
>Also FYI: I tried this approach in the past, but didn't like it since it affects audio in other applications and causes some samplerate-distortion.

That argument should be moot. You don't enable bitperfect playback if you're also going to be playing other audio through the same device. Bitperfect playback is about getting the maximum playback quality for music that you're going to be giving all your attention to. Even then it's for a large part a purely psychological reassurance because even when converting between 44.1kHz and 48kHz the quality loss is usually barely noticeable (on a double-blind listening test).

**Comment by Oleksiy-Yakovenko** [comment]
Ok, yes, also true. What I meant is that I didn't like this as default / the only option. It's viable as special setting (or when sending DSD/DTS data).

**Comment by RJVB** [comment]
On Monday June 09 2025 14:05:27 Oleksiy Yakovenko wrote:
>It's viable as special setting.

It definitely should be, yes.
