### ISSUE TITLE
Tracks without leading zeros in their number sorted incorrectly

### ISSUE THREAD

**Issue by eko5z** [DeaDBeeF-Player/deadbeef#3122]
### Steps to reproduce the problem
1. Add an album whose tracks have numbers without leading zeroes, and there are 10 or more tracks
2. Observe the problem

### What's going on? Describe the problem in as much detail as possible.
The tracks are sorted incorrectly, as visible on the attached image.
![obraz](https://github.com/user-attachments/assets/356cea71-7213-439b-9bb3-8f1f3457a548)

### Information about the software:
Deadbeef version: 1.9.6
OS: NixOS 24.05.4639.6f6c45b5134a (Uakari)

**Comment by Npa972** [comment]
Hi, that's weird. Nether had this problem.
![image](https://github.com/user-attachments/assets/087bb1b7-2565-4d66-a611-d54e48810305)

**Comment by Oleksiy-Yakovenko** [comment]
Deadbeef sorts files by filenames, that's probably the issue. I remember there was either a built in option or a 3rd party auto-sort plugin, try searching for that. It will sort playlists every time when new files are added.
