### ISSUE TITLE
libdispatch is missing in Ubuntu 24.04

### ISSUE THREAD

**Issue by mgreshake** [DeaDBeeF-Player/deadbeef#3123]
### Steps to reproduce the problem

Run deadbeef under Ubuntu 24.04.

### What's going on? Describe the problem in as much detail as possible.

When I run deadbeef under Ubuntu 24.04, I get the follow error message:

`deadbeef: error while loading shared libraries: libdispatch.so.0: cannot open shared object file: No such file or directory`

It seems that Ubuntu has removed the libdispatch package from its last LTS release (see [here](https://answers.launchpad.net/ubuntu/+source/libdispatch/+question/709495)). Unfortunately, deadbeef has quite a few dependencies on this package.

### Information about the software:

Deadbeef version: 1.9.6
OS: Kubuntu 24.04

Built deadbeef from source. Use file browser plugin.

**Comment by mgreshake** [comment]
Of course, you can build libdispatch from source. The repo can be found here:

[https://github.com/apple/swift-corelibs-libdispatch.git](https://github.com/apple/swift-corelibs-libdispatch.git)

However, it may be a good idea to remove the dependencies successively.

**Comment by Oleksiy-Yakovenko** [comment]
I'm not sure why it's reported as an issue. Do you have some problem with running the app?

**Comment by Oleksiy-Yakovenko** [comment]
You seem to be running a build which dynamically links libdispatch, and you don't have the library installed.

Option 1: install the library
Option 2: use another build which includes the library

The official build from deadbeef website ships with libdispatch bundled, so you should not have any issues with it.

If you prefer to make your own build - you either need to install libdispatch, or use the same build script as github workflows use.
