### ISSUE TITLE
Dependency is not satisfiable: libgtk2.0-0 (>= 2.12.0)  when installing on Linux Mint 22 

### ISSUE THREAD

**Issue by Xmetalfanx** [DeaDBeeF-Player/deadbeef#3141]
### Steps to reproduce the problem
Install latest dev deb or 1.9.6 deb on a system based on Ubuntu 24.04

### What's going on? Describe the problem in as much detail as possible.
I am still testing things to make sure i am not missing something but trying (the regular 1.9.6. deb first of course) to install the DEB via "gdebi" in the command line results in 

`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libgtk2.0-0 (>= 2.12.0)
`

I do already have a copy of 1.9.5 installed that i would have installed the same way, some time ago on Mint 21.3  (CURRENTLY ON Mint 22 after an inplace Mint 21.3 (Ubuntu 22.04 based) to Mint 22 (Ubuntu 24.04 base) upgrade that went fine

I just tried the 1.9.5 DEB and that gives the same message now.  

I have also downloaded the 1.9.6 Deadbeef tarball and extracted that and it runs a-ok instantly .. .no problems what so ever 

I am not sure what happened and hesitated to make this report as it MAY not be related to anything you have done.  If i find out it was something else that goofed up, I will be sure to report back 

### Information about the software:

Deadbeef version:  1.9.6
OS: Mint 22 (Ubuntu 24.04 based)

**Comment by Xmetalfanx** [comment]
I just tested the 1.9.6 DEB in a live VM of Linux Mint 22 and everything installed fine ... so as I suspected before .. this MAY NOT be related to anything wrong with the DEB, but something wrong with my setup/install

**Comment by Oleksiy-Yakovenko** [comment]
I have never used "gdebi", but have you tried using `dpkg -i ...` instead?

**Comment by Oleksiy-Yakovenko** [comment]
Either way, I don't really know why this occurs, maybe GTK2 is no longer available from the repository? That's not something I can fix really. Closing.

**Comment by Xmetalfanx** [comment]
> I have never used "gdebi", but have you tried using `dpkg -i ...` instead?

I think it was somewhat "force of habit" and i thought (could be COMPLETELY wrong here) gdebi handled deps better or something 

Anyway I tried your suggestion and it installed a-ok and works fine.

Whatever happened it's NOT related to Deadbeef code, I am sure of that now 

I may investigate just for my own curiosity at some point.

Thank you for your time and work on an amazing program
