### ISSUE TITLE
On XFCE, XF86 audio keys do not work when bound as hotkeys

### ISSUE THREAD

**Issue by manicmou** [DeaDBeeF-Player/deadbeef#3145]
### Steps to reproduce the problem
On (my) xfce desktop, bind keys like XF86AudioPlay to Play/Pause and XF86AudioNext to Next.
### What's going on? Describe the problem in as much detail as possible.
These hotkeys do not function. I know that some input is being received since I can bind these keys, and when I bind other keys to the same function they work. I have seen some discussion about media playback keys being blocked on GNOME, but there isn't much information about the same happening on xfce so I am not sure what is happening.

These also work if I bind them to deadbeef command line options, so there's a workaround, but it's confusing as to why these don't work in application.
### Information about the software:

Deadbeef version: 1.9.6
OS: EndeavourOS, 6.11.9-arch1-1

Hotkey config:
![image](https://github.com/user-attachments/assets/ae6fde67-cf81-45e5-9273-79ad91d91243)

**Comment by Oleksiy-Yakovenko** [comment]
It's because you're binding them as global hotkeys. Most linux DEs will intercept those keys, and won't allow apps to get them. 

To remedy this issue, you could use MPRIS or gnome_mm_keys plugin.

**Comment by manicmou** [comment]
No, I've tried these as non-global. They don't work even when I have the app focused.

**Comment by Oleksiy-Yakovenko** [comment]
I think it's caused by the same combination of factor. If DE intercepts those keys to control media playback -- they never reach the app.

**Comment by manicmou** [comment]
Again, I have a workaround, but this seems like functionality that _should_ exist since I can bind the keys in the first place. If that's not your intention, that's fine, but I want to make it clear what the situation is.

**Comment by Oleksiy-Yakovenko** [comment]
To verify that it works when DE does not get in the way -- you could create a new X session which runs on a simple window manager (like fluxbox or twm, or similar), and most likely it will work without problem. But heavier DEs won't allow that, and I don't think me or you can do much about this.. Maybe there's some setting in XFCE which could disable that behavior.
