### ISSUE TITLE
Last.fm plugin - scrobble online radio streams

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#408]
Original [issue 479](https://code.google.com/p/ddb/issues/detail?id=479) created by Alexey-Yakovenko on 2012-04-19T10:50:07.000Z:

Currently, last.fm plugin doesn't scrobble online radio streams. It looks like you jump from your local track to stream and you can see correct &quot;now playing&quot; track (from the stream) on last.fm page, but only about 10 seconds, then connection with l.fm loses or something else.

It will be nice to add this feature.

**Comment by erdnaxeli** [comment]
I see this closed. Why ? Won't fix ?

**Comment by Alexey-Yakovenko** [comment]
no, because it has been implemented.
