### ISSUE TITLE
Playlist switcher.

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#535]
Original [issue 633](https://code.google.com/p/ddb/issues/detail?id=633) created by Alexey-Yakovenko on 2012-04-19T11:50:07.000Z:

submitted by: nobody
Date: 2010-07-16 12:05:04

Очень хотелось бы увидеть возможность переключения между плей-листами не только табами, но и списком (например как в foobar2000) или на подобии плагина playlist_dropdown у всё того же foobar2000.

**Comment by aquirel** [comment]
Why it was closed? Is there a chance that it will be implemented ever?
This feature could be very handy when there are a lot of playlists.
It also will be nice to have playlists sorted in this dropdown.

**Comment by Alexey-Yakovenko** [comment]
It is closed because it was implemented about 2 years ago.

**Comment by aquirel** [comment]
Oh, do you mean playlist browser widget?
I thought there's an intention to create dropdown widget.
Anyway, sorry for bothering you. And thanks for the great player :)
