### ISSUE TITLE
Различные способы группировки для разных плейлистов.

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#536]
Original [issue 634](https://code.google.com/p/ddb/issues/detail?id=634) created by Alexey-Yakovenko on 2012-04-19T11:50:08.000Z:

submitted by: nobody
Date: 2010-07-18 11:44:49

А еще лучше выбор такой возможности в настройках. Полезно, например, если есть сборники, которые хорошо группируются по Artist/Date/Album, и наборы саундтреков, которые при токой группировке выглядят не очень.

**Comment by yunake** [comment]
мечтаю о таком функционале. Алексей, можешь рассказать как ты видишь реализацию? рано или поздно я этим займусь, но хотелось бы сразу делать так чтобы ты принял пулл-реквест.

**Comment by Alexey-Yakovenko** [comment]
я думаю, что ты видишь реализацию лучше чем я, потому что мне этот фичреквест вообще не нужен. я не пользуюсь группировкой.

**Comment by Alexey-Yakovenko** [comment]
@yunake 

> хотелось бы сразу делать так чтобы ты принял пулл-реквест.

как это работает:

* придумай что ты хочешь получить -- какие нужны настройки, какие новые окошки, меню, и т.п.
* опиши свое виденье как это будет работать
* получи отзывы от других разработчиков (скорее всего, в начале окажется, что твоя идея ломает 20 других юз-кейсов, и их все надо учитывать)
* переработай виденье до тех пор, пока другие разработчики не скажут "ок, это должно взлететь"
* подумай какие изменения нужны в коде, чтобы получить желаемое
* расскажи о них
* получи отзывы
* после этого начинай писать код
* получил прототип? выложи на гитхаб, покажи код, получи отзывы что сделано криво, и как сделать правильно
* доработай прототип с учетом отзовов
* когда все работает у тебя, сообщи остальным чтобы протестировали
* вероятно, на этом этапе уже можно делать PR

**Comment by Alexey-Yakovenko** [comment]
marking as a duplicate of the new issue #1931, which is more up to date and in english.
