### ISSUE TITLE
console ui

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#572]
Original [issue 670](https://code.google.com/p/ddb/issues/detail?id=670) created by Alexey-Yakovenko on 2012-04-19T11:50:41.000Z:

submitted by: andreyk-mad
Date: 2010-11-04 13:00:31

А что тут еще домавить - плагин для руления плеером из консоли хочется.

**Comment by Shellcat-Zero** [comment]
@kuba160 @Alexey-Yakovenko I'm very interested in accomplishing this.  Is the goal to have this supported via plugin like https://github.com/kuba160/ddb_gui_prompt or would this be a native feature (or separate version) of Deadbeef?  If someone would like to tell me what needs to be done (and where to look in the code) to get this accomplished, I'm very eager to start coding.  At present, it seems that ddb_gui_prompt [needs some work](https://github.com/kuba160/ddb_gui_prompt/issues/2#issuecomment-432592167) to load/manipulate files.

**Comment by Alexey-Yakovenko** [comment]
@Shellcat-Zero deadbeef is based on modular architecture, where almost everything is implemented as a plugin. Whether a plugin is shipped as part of deadbeef, or separately, is decided based on the quality of the plugin and its importance. The best course of action is to join up with Jakub. He has something working already, and he's got a bunch of experience with deadbeef APIs.

**Comment by nkk64** [comment]
Me too would love to have Music On Console player (in fact norton/midnight commander-type) style console interface. Any chance there was any progress in that direction?

**Comment by Alexey-Yakovenko** [comment]
There was progress -- see the https://github.com/DeaDBeeF-Player/deadbeef/issues/572#issuecomment-433407105
The ddb_gui_console does exactly what this issue is about.
It's not even remotely at feature parity with existing UI frontends, but I suppose it's better than nothing.

**Comment by Alexey-Yakovenko** [comment]
The ddb_gui_prompt is another variant of the same.

**Comment by nkk64** [comment]
Thanks for prompt reply. Strangely when I clicked that kuba160/ddb_gui_prompt page while reading this thread it just timed out. But now it worked - I'll try it right now :)

**Comment by Alexey-Yakovenko** [comment]
I think github is experiencing some issues right now.. Some pages randomly aren't loading.

**Comment by nkk64** [comment]
Btw how it comes that deadbeef sound is noticeably better compared to moc (I use both for playing flac-s through ALSA without any conversions to external USB-connected DAC)? And thank you - sound is really good indeed!

**Comment by Alexey-Yakovenko** [comment]
I don't know.. I never compared sound with any other players.

**Comment by Alexey-Yakovenko** [comment]
Multiple versions of this is available as 3rd party plugins
