### ISSUE TITLE
Peak Meter or VU Meter

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#605]
Original [issue 703](https://code.google.com/p/ddb/issues/detail?id=703) created by Alexey-Yakovenko on 2012-04-19T11:51:24.000Z:

submitted by: tedtriol
Date: 2011-03-24 10:20:01

A peak meter or VU meter makes a music player &quot;alive&quot;

**Comment by mallniya** [comment]
We have it now as a [plugin](https://github.com/cboxdoerfer/ddb_vu_meter)
