### ISSUE TITLE
add option to move "delete from disk" into sub-submenu

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#608]
Original [issue 706](https://code.google.com/p/ddb/issues/detail?id=706) created by Alexey-Yakovenko on 2012-04-19T11:51:28.000Z:

submitted by: nobody
Date: 2011-04-19 16:05:25

E.g. by simply putting the &quot;Remove From Disk&quot; item in a sub (sub) menu.
This is a very useful function, and I don't want to turn it off.
Imho the gtk confirmation dialog is not protection enough.

**Comment by Alexey-Yakovenko** [comment]
On mac, the confirmation dialog is protective enough, since in this situation -- the No button becomes default, so pressing Enter or Escape, or clicking the brightly accented default button with the mouse will definitely NOT delete the file.

Perhaps something like this is possible with GTK?

@saivert do you know?

And here's how it looks on Mac.

![image](https://user-images.githubusercontent.com/1895698/126080052-78ca90c4-e8b8-4428-8764-736f68210ca0.png)

**Comment by saivert** [comment]
No button is default on GTK as well.

And to make the yes button signify destructive action you can add an appropriate style class for this for GTK3 at least:
```c
#if GTK_CHECK_VERSION(3,0,0)
        GtkWidget *btn = gtk_dialog_get_widget_for_response(GTK_MESSAGE_DIALOG(dlg), GTK_RESPONSE_YES);
        gtk_style_context_add_class (gtk_widget_get_style_context(btn), "destructive-action");
#endif
```

![Screenshot from 2021-07-18 22-07-32](https://user-images.githubusercontent.com/63738/126080838-62988a5c-d939-4ece-9546-8ae90a2afdee.png)

**Comment by Alexey-Yakovenko** [comment]
Wow this design looks horrible -- it totally makes it look like the "Yes" button is default :)
But I'm trying it out now.

**Comment by Alexey-Yakovenko** [comment]
It looks terrible, but does the job, and works fine.

**Comment by Alexey-Yakovenko** [comment]
Thanks for the code :)
