### ISSUE TITLE
Remember minimization to tray after restart

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#618]
Original [issue 716](https://code.google.com/p/ddb/issues/detail?id=716) created by Alexey-Yakovenko on 2012-04-19T11:51:38.000Z:

submitted by: nobody
Date: 2011-05-17 08:28:25

DeaDBeeF minimized to tray, but if I close it (from tray menu, or system shutdown) and start again - DeaDBeeF opens as normal window. Will be good if DeaDBeeF remember own state.

**Comment by kpcee** [comment]
Done with "[gtkui: added an option to start deadbeef hidden](https://github.com/DeaDBeeF-Player/deadbeef/commit/3ac4cc03fe52356784a50836cf361eed61dcc797)".
