### ISSUE TITLE
[cuesheet] tracks+cue support, direct loading

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#648]
Original [issue 746](https://code.google.com/p/ddb/issues/detail?id=746) created by Alexey-Yakovenko on 2012-04-19T11:52:11.000Z:

submitted by: anonymous
Date: 2011-08-15 13:13:11

Better algoritm
1) loading cuesheets also ape, flac etc
2) Exclude ape, flac etc which have link from cuesheets

**Comment by wdlkmpx** [comment]
I think i'll try to add a plugin for this. I might need some help though. If you could revert https://github.com/Alexey-Yakovenko/deadbeef/commit/81817d3c195537e5359587617c505b7f68ff5d14  i'd be more inspired hehe...
