### ISSUE TITLE
add libgsf and timidity

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#653]
Original [issue 751](https://code.google.com/p/ddb/issues/detail?id=751) created by Alexey-Yakovenko on 2012-04-19T11:52:14.000Z:

submitted by: personxys
Date: 2011-09-06 22:47:46

timidity is a midi player with many features (including custom soundfonts _wink_) : http://timidity.sourceforge.net/
libgsf plays *.gsf and *.minigsf (gameboy advance sound format)
more info here: http://wiki.linuxfromscratch.org/blfs/wiki/libgsf
and here: http://www.linuxfromscratch.org/blfs/view/cvs/general/libgsf.html

**Comment by WORD559** [comment]
I know this is a very old issue and has probably been lost in the works, but I'd like to bump the issue and show my desire to see this transpire. I do have a fair few GSFs that aren't playable in DeaDBeeF, which is a real shame. It's one of the only chiptune formats it _can't_ play at this point.

**Comment by joshbarrass** [comment]
This issue's been sitting here a while, so perhaps someone else has already taken this on, but I couldn't anything last I looked. I finally got some free time to work on this myself and I have now written my own GSF decoder plugin: https://github.com/joshbarrass/deadbeef_GSFdecoder

There are still a couple of things I need to implement (e.g. fadeout), a few bugs I need to fix, some improvements to add and some modifications I'll need to make if I want it to be compatible with the deadbeef-plugin-builder, but it is in a working state! There are a few (pre-)releases available on the [release page](https://github.com/joshbarrass/deadbeef_GSFdecoder/releases) for anyone interested.

**Comment by Oleksiy-Yakovenko** [comment]
@joshbarrass Congrats, and great job!

Let me know if I can help with anything.

I only looked at the code briefly, and one thing that I noticed is that, potentially, you will encounter re-entrancy problems, since the plugin is using a bunch of what looks like global variables holding the decoder state.

This will lead to problems if you try to run certain plugins which decode files in background (converter, waveform seekbar), while another file is playing.

I don't know whether it's fixable though. But I think it should be.

**Comment by joshbarrass** [comment]
Thank you! :D

I'm aware of this issue (I encountered it first-hand with the converter), but I think it should be quite straightforward to fix. I've left an issue open on the repo to remind me about it, and I'm hoping I'll get a chance later this week to work on it.

**Comment by joshbarrass** [comment]
@Oleksiy-Yakovenko that issue is now fixed, and I've tested that the converter can now run at the same time as playback

**Comment by Oleksiy-Yakovenko** [comment]
Cool, congrats :)

**Comment by Oleksiy-Yakovenko** [comment]
I will update the plugins wiki page to include your new plugin (sorry, can't do it now - but I'll get to it ASAP)

**Comment by joshbarrass** [comment]
Awesome, thanks! And there's no rush -- whenever you get an opportunity

**Comment by Oleksiy-Yakovenko** [comment]
done!

**Comment by Oleksiy-Yakovenko** [comment]
I'm closing the issue then. I'll ignore that this feature request asks for Timidity as well. If somebody needs it - they may post another request :)
