### ISSUE TITLE
Fade out on stop

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#662]
Original [issue 760](https://code.google.com/p/ddb/issues/detail?id=760) created by Alexey-Yakovenko on 2012-04-19T11:52:22.000Z:

submitted by: nobody
Date: 2011-11-24 11:59:20

I would like to request feature of fading away sound on stopping/pausing. It is very nice feature which makes stopping music in middle of song more pleasing to the ear.

**Comment by shaforostoff** [comment]
and please make it with configurable length. foobar2000 allows fadeout to be as long as 10 seconds. i use this feature in argentine tango DJing

**Comment by aufkrawall** [comment]
This would really be a nice feature, I'd really appreciate it.

**Comment by mallniya** [comment]
There is a [plugin](https://github.com/tiborhari/ddb_fade) for this now

**Comment by Alexey-Yakovenko** [comment]
thanks, added a link to wiki
