### ISSUE TITLE
[android] dsp plugins support

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#667]
Original [issue 765](https://code.google.com/p/ddb/issues/detail?id=765) created by Alexey-Yakovenko on 2012-04-19T11:52:25.000Z:

submitted by: nobody
Date: 2012-01-07 20:13:03

deadbeef is the best player in android. If it can add some DSP like in Linux, it would be great.
MOST I needed plugin  is resampler, bs2b

**Comment by Alexey-Yakovenko** [comment]
Irrelevant since deadbeef is no longer developed for android. Closing.
