### ISSUE TITLE
Configurable Seek Time

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#781]
Original [issue 879](https://code.google.com/p/ddb/issues/detail?id=879) created by Alexey-Yakovenko on 2012-09-10T23:58:27.000Z:

I have tried many of the audio players available for GNU Linux and deadbeef has become my favorite for a long list of reasons. There is just one small problem. The Seek Forward and Seek Backward actions are not configurable. I have added Global Hotkeys for these actions. In some tracks, it will skip approximately 7 minutes ahead or 7 minutes back when the hotkeys are pressed. The amount of seek seems to change with each different audio file I play. I can't find anyway to configure this or a way to hack the amount of seek manually.

For obvious reasons, this is not useful. I would be fantastic to have seek time forward and backward available as a configuration option that could be specified in seconds. I usually like to have it set to around 5-10 seconds so I can skip back in small increments if I missed something that was said in an eBook / podcast, or I can hold the hotkeys down to continue seeking further if necessary.

I'd be happy to donate towards implementing this feature.

**Comment by kuba160** [comment]
DeaDBeeF has now options to seek by 1s, 5s, 1% or 5%. I also wrote a simple plugin that adds 2 customizable seek presets ([ddb_cust_seek](https://github.com/kuba160/ddb_cust_seek)).
