### ISSUE TITLE
Album Art column shows no cover

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#815]
Original [issue 913](https://code.google.com/p/ddb/issues/detail?id=913) created by Alexey-Yakovenko on 2012-11-25T12:17:54.000Z:

<b>What steps will reproduce the problem?</b>
<b>Какие шаги приводят к воспроизведению</b>
<b>проблемы?</b>
1. Add album art column
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
<b>Какой ожидаемый вывод? Что вы видите</b>
<b>вместо него?</b>
I would like to see the album cover.

<b>What version of the product are you using? On what operating system and CPU</b>
<b>architecture?</b>
<b>Какую версию продукта вы используете? На</b>
<b>какой операционной системе и</b>
<b>архитектуре CPU?</b>
Ubuntu 12.04.1 amd64. DeaDBeeF-0.5.6 amd64.

<b>How did you install the product?</b>
<b>Как вы установили продукт?</b>
Using deb file from official web site.

<b>Please provide any additional information below.</b>
<b>Пожалуйста, предоставьте любую</b>
<b>дополнительную информацию ниже.</b>
It WORKS if done the following described by http://danielj.se/2011/09/29/how-to-show-album-art-in-deadbeef/ :

Right click the bar right over the playlist and add Album Art from the Add Column window.
Right click the bar again and choose Artist/Date/Album under Group by.
Done!
If you don’t want it to separate the playlist by artist. Choose Custom under the Group by menu instead, and type [%y] %b in the Format field.

**Comment by C0rn3j** [comment]
Can the Album art column label say "Only works when grouping is enabled, read help" when grouping is disabled? 

Or implement anything that won't just make it look like it's broken when grouping is disabled.

Would've saved me some time.
