### ISSUE TITLE
Add support for multimedia keys (which are now on most keyboards)

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#828]
Original [issue 926](https://code.google.com/p/ddb/issues/detail?id=926) created by Alexey-Yakovenko on 2012-12-20T19:44:56.000Z:

DeaDBeeF is awesome. But I'd like to control it like a music player -- through the multimedia keys (most keyboards have play/pause, stop and previous/next). I tried to do that through global keybindings, but it didn't recognise the media keys. I, and probably many people, would like to have this feature.

Thanks!

**Comment by kode54** [comment]
Linking to the repository of the solution, which currently works with Gnome 3 as of this post.

https://github.com/zhanghai/deadbeef-gnome-mmkeys.git

**Comment by Alexey-Yakovenko** [comment]
Also available in binary: https://deadbeef.sourceforge.io/plugins.html

**Comment by Logicwax** [comment]
having an issue where media keys are not working in latest ubuntu 22.04 Jammy with GNOME 42.2 on wayland.

When i press media keys, GNOME gives me the error pop-up (circle with line through it).

if i goto deadbeef key settings, and try to set a key binding for Toggle pause (even global) it detects it (my apple keyboard with the F8 play/pause button registers as XF86Launch9 in deadbeef).     In fact, toggling "global" doesn't work at all for ANY keys (either in deadbeef or out).

**Comment by Alexey-Yakovenko** [comment]
@Logicwax global hotkeys support in deadbeef is based on X11 functionality, and can't be used with wayland.

**Comment by Unixware** [comment]
nor working even on X11 !! lolz

**Comment by Oleksiy-Yakovenko** [comment]
@Unixware last time I tried it worked, but with Linux every system is different, so nothing is guaranteed to be available at all.

Specifically with global hotkeys in deadbeef, you need to be running X11, and you need to be using the keys which are not grabbed as global hotkeys by other applications, or the WM/DE.

So yeah, it can be fairly limiting.

I have not encountered situation when it was not working at all, but of course it is also possible -- depends how deadbeef was compiled. There are options and other circumstances which may cause this functionality to be disabled.

**Comment by kode54** [comment]
There is an mpris2 plugin for DeaDBeeF already, and both GNOME and Plasma implement their shell-wide global media keys using this system.

https://github.com/DeaDBeeF-Player/deadbeef-mpris2-plugin

For wlroots compositors, you can program your compositor with global hotkeys for the media keys your keyboard has, and assign them to run playerctl:

https://github.com/altdesktop/playerctl
