### ISSUE TITLE
Where is deadbeef looking for tray icons? 

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#868]
Original [issue 966](https://code.google.com/p/ddb/issues/detail?id=966) created by Alexey-Yakovenko on 2013-08-05T01:25:56.000Z:

This is more a question than a bug. 

I would like to change the tray icon. There is a function for this under the GTK2 user interface plugin, &quot;Custom status icon&quot;. But whatever I enter there has no effect. Where is deadbeef looking for the icon file that I enter?

**Comment by imabuddha** [comment]
Just wanted to leave some info for any Raspberry Pi OS users (might apply to others as well). I put the icons & a desktop file that I created as noted in this gist: https://gist.github.com/imabuddha/03ba8a6638c77854c4389180e7ca3859

Now menu, tray, and app icons all appear properly. 🙇
