### ISSUE TITLE
Please show number of files to be deleted in dialog box

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#900]
Original [issue 998](https://code.google.com/p/ddb/issues/detail?id=998) created by Alexey-Yakovenko on 2013-11-16T22:42:34.000Z:

(Enhancement request, NOT a bug)

Action: 
User selects 'Delete from disk' by context menu.

What is the expected output? 
&lt;**Number**&gt; files will be deleted. Proceed?

What do you see instead?
Files will be deleted. Proceed?

What version of the product are you using?
trunk, built from source

<b>Please provide any additional information below.</b>

I'd like to request this minor change, since it will probably prevent the user from doing something _very_ stupid.
I'd like to have the NUMBER of files shown that I'm planning to delete from disk in the user dialog. Just to be sure no files far above selected by accident will be deleted as well.
Although it's not _that_ prone to errors since you have to multi-select files (CTRL), it's still better to know what dangerous thing you're about to do next. ;)

Hope I was not too confusing.

**Comment by kpcee** [comment]
Done with [gtkui: improved remove from disk feature](https://github.com/DeaDBeeF-Player/deadbeef/commit/8ad89ddfbdbf494d7b406820729fad7ec91efc75).
