### ISSUE TITLE
config's last.fm password isn't been encrypt.

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#913]
Original [issue 1011](https://code.google.com/p/ddb/issues/detail?id=1011) created by Alexey-Yakovenko on 2013-11-28T15:02:56.000Z:

<b>What steps will reproduce the problem?</b>
1. be sure the plug-in has been set well.
2. open &quot;~/config/deadbeef/config&quot; file.
3. view &quot;lastfm.password&quot; line.

What is the expected output? 
the password should be encrypt or use tokens.

What do you see instead?
clean and not-encrypted password.

<b>What version of the product are you using? On what operating system and CPU</b>
<b>architecture?</b>
version 0.6.0-2 (compile from snapshot 3b4f24) on fedora 20 x86_64.

<b>How did you install the product?</b>
self-compile, make install

<b>Please provide any additional information below.</b>
this would be a enhancement request, since the last.fm account info is not really important, but still a risk if computer got steal or been hacked ;)
do a encryption or use token (i'm not sure if they have auth login or not) might be a good idea.

**Comment by anewuser** [comment]
When you decide to implement the new Last.fm scrobbler API, take a look at their authentication API too. The Last.fm plugin provided with [Audacious](http://audacious-media-player.org/) uses that, so that users never have to type their passwords or usernames in the program. It just opens the Last.fm website on the default web browser for you to connect your account to the player, and they apparently stay connected permanently, unless you revoke the access to your account.

**Comment by Samueru-sama** [comment]
Hey I think something needs to be done about this, because github is full of leaked passwords now, like I began contacting people about this but there is so many leaked passwords omg.

**Comment by Oleksiy-Yakovenko** [comment]
@Samueru-sama 
Do people post their deadbeef configs to github?
I sort of didn't anticipate that anyone does this.
But I agree that some action is required. I'll see if it's possible to convert a password to hash, and delete the password from configs.

**Comment by Samueru-sama** [comment]
> Do people post their deadbeef configs to github?

Yes!

**Comment by Oleksiy-Yakovenko** [comment]
I checked, and there's no hash that can be stored which could replace the password for lastfm auth.

Potentially it would help if the lastfm plugin is upgraded to use lastfm scrobbler API v2, which uses a different authentication mechanism. I would have to check whether it's the case.

Another approach is to save lastfm password in a separate file, which the users could add to their .gitignore,
but of course it's only a mitigation, not a solution.

**Comment by Samueru-sama** [comment]
> Another approach is to save lastfm password in a separate file, which the users could add to their .gitignore,
> but of course it's only a mitigation, not a solution.

I'm ok with this solution, ideally with the file clearly named password and it is not placed in `$XDG_CONFIG_HOME` and instead it is on `XDG_DATA` or `XDG_STATE`.

**Comment by Oleksiy-Yakovenko** [comment]
The problem is that solution would take about the same amount of time as implementing lastfm v2 API, so I'd rather go with this one.
Deadbeef doesn't currently support multiple config files for individual plugin settings, and it feels like an overkill to add one just for that.

**Comment by kuba160** [comment]
Another possibility would be to use gnome keyring to store password I guess? (I'm not very familiar with it some more research would be needed, but I think it does not require gnome to work)

**Comment by Oleksiy-Yakovenko** [comment]
This would require all the same work (+ extra steps), as storing the password in a separate file.
Obviously this is also a possibility, and I'm sure some users would prefer that approach.
However, this would also require implementing a similar keychain mechanism for Mac and Windows -- which is more difficult than it sounds.
From what I remember, mac apps are required to be codesigned, which requires apple developer subscription (Which I'm not willing to pay).

**Comment by Oleksiy-Yakovenko** [comment]
> but I think it does not require gnome to work

and yeah, it doesn't require GNOME to work, but it won't work if gnome keyring software is not installed -- which means, some fallback mechanism would have to be implemented for the Linux users as well -- which will make it 4 different password backends to support 3 platforms :)

**Comment by Oleksiy-Yakovenko** [comment]
I'm not even factoring-in all the annoying dbus code that would have to be written just to support GNOME keyring, and/or potentially introducing more dependencies just to save a single password :)

**Comment by Oleksiy-Yakovenko** [comment]
I have thought about it a bit more, and concluded that even if I implement lastfm v2 API, but store session token in the config file -- it may result in the same sort of problems (i.e. the token leaking via config files posted on github).

So the only viable solution is to have a mechanism to move the passwords out of the config.
I'll keep brainstorming on how to do it in the least intrusive way, so that plugins can do it as simple as now without causing security flaws.

**Comment by Oleksiy-Yakovenko** [comment]
Just pushed the fix which should migrate the login credentials to a file in XDG_STATE_HOME, and its respective counterparts on mac/win.
It may need a bit more fixing in case something unexpected happens on windows or linux, since I only tested mac so far.
