### ISSUE TITLE
Efficiently edit a metadata tag across multiple selected files

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#989]
Original [issue 1087](https://code.google.com/p/ddb/issues/detail?id=1087) created by Alexey-Yakovenko on 2014-03-29T10:52:23.000Z:

<b>What steps will reproduce the problem?</b>
<b>Какие шаги приводят к воспроизведению</b>
<b>проблемы?</b>
1. Добавить в плейлист альбом, выделить файлы.
2. Кликнуть правой кнопкой, выбрать Track Properties.
3. Дважды кликнуть на заголовок поля, которое различается между треками (например, Track Title).

<b>What is the expected output? What do you see instead?</b>
<b>Какой ожидаемый вывод? Что вы видите</b>
<b>вместо него?</b>

В fb2k в таком сценарии показывается диалог, позволяющий редактировать конкретно указанное поле в выбранных выбранных файлах. В этом же плеере клик по заголовку поля ни к чему не приводит, а клик по значению позволяет только перезаписать его во всех треках (чем-то одним).

<b>What version of the product are you using? On what operating system and CPU</b>
<b>architecture?</b>
<b>Какую версию продукта вы используете? На</b>
<b>какой операционной системе и</b>
<b>архитектуре CPU?</b>

Ubuntu 13.10

deadbeef-static_0.6.1-5_amd64.deb

**Comment by dgutov** [comment]
Really looking forward to this.

**Comment by Alexey-Yakovenko** [comment]
I'm pretty sure this has been implemented already.. Please check 1.8alpha, and let me know if something is missing.

**Comment by dgutov** [comment]
I've tried both the today's devel build and the 1.8.0-alpha4.

I select all tracks in an album, then enter Track Properties. After that, I either:

* Double-click on "Track Title".
* or right-click on it and pick "Edit".

Nothing happens. No errors in the console either.

**Comment by Alexey-Yakovenko** [comment]
Did you try on mac or linux? I remember implementing this feature.. it doesn't work for me on mac.. maybe I broke something by accident. but it can't be the same on Linux..

**Comment by dgutov** [comment]
GNU/Linux, yes. Ubuntu 17.10.

**Comment by dgutov** [comment]
You did: 
![Screenshot from 2019-04-20 23-03-29](https://user-images.githubusercontent.com/271877/56461758-953a3000-63c0-11e9-9676-06e974b92c38.png)

Could you un-disable it, then?

**Comment by Alexey-Yakovenko** [comment]
It's not yet possible to edit tags for multiple items in GTK version of deadbeef.
Enabling the item won't help that.

**Comment by Alexey-Yakovenko** [comment]
(It already works on mac though, so it's only a matter of someone porting it to linux)

**Comment by dgutov** [comment]
Is it a GTK limitation?

**Comment by Alexey-Yakovenko** [comment]
No, it has nothing to do with GTK. deadbeef is not using GTK on mac.

**Comment by dgutov** [comment]
I mean on Linux. Why it's not implemented yet.

If it's not a GTK limitation, depending on the difficultly, I might give it a shot sometime. Could you point at the respective MacOS implementation?

**Comment by Alexey-Yakovenko** [comment]
Because nobody implemented it yet for linux.
The code starts around here: https://github.com/DeaDBeeF-Player/deadbeef/blob/master/plugins/cocoaui/TrackPropertiesWindowController.m#L750
most of it is in the same file.

And here's a screenshot if you want to know how the UI is supposed to look

![image](https://user-images.githubusercontent.com/1895698/56461943-08d93e80-63bb-11e9-89ab-2658d50aa136.png)

**Comment by Alexey-Yakovenko** [comment]
Now works in GTKUI too!
![image](https://user-images.githubusercontent.com/1895698/148698527-51cec5f7-a652-4056-98f6-e83d13eef6d9.png)
