### ISSUE TITLE
Option to alter the playback speed

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#993]
Original [issue 1091](https://code.google.com/p/ddb/issues/detail?id=1091) created by Alexey-Yakovenko on 2014-04-08T14:34:26.000Z:

(ENHANCEMENT request, no bug report.)

It would be great if the playback speed could be altered, for the following reason: imagine your friend ripped one of his LPs for you, and the audio quality is very good, however you figure out that the pitch is a little too high (since his turntable has aged quite a bit)

Happened quite sometimes on here...

Maybe it could be possible to 'steal' a little code from MPlayer which has this already implemented ( $ mplayer -speed x.yy sample.mp3 )

**Comment by Weej1** [comment]
Please, I would love to see this implemented - currently I'm having to use audacious and DeadBeef together - Audacious has the pitch/speed plug in built in by default, but lacks quite a few features that you can find within DeadBeef.  I understand that the ver. of SoundTouch in DB 0.5.x was not "thread safe" (not a programmer here so I don't know what that is) but i DID see that SoundTouch was recently updated too, perhaps this version fixes whatever issue you had with it in the first place? 

Either way thanks for your hardwork - I just hope to see this implemented soon as a plugin or something.

**Comment by Gooberpatrol66** [comment]
same

**Comment by shengdie** [comment]
waiting for this.

**Comment by blueto01h** [comment]
me too

**Comment by Alexey-Yakovenko** [comment]
SoundTouch plugin is available again in deadbeef since 2020/2021, and allows to change the playback speed
